// Generated from bindings.scm and the vocabulary by `pnpm exec tsx packages/cli/src/cli.ts tool bindings-inventory --write`. Do not edit.
/// <reference path="../codegen/src/dsl/authoring-globals.d.ts" />
import { alias, bindings, field, rename } from '../codegen/src/dsl/dsl-authoring.ts';

export default bindings({
	hash: "4255560810e5d6453284d850d4620e0bb2dede92139aef3c62cbd90ddbc7c819",
	patches: {
		_expression_within_for_in_clause: { "-1": alias(sym("lambda_within_for_in_clause"), sym("lambda_expression")) },
		assignment_eq: { "0": field("name"), "1/1": field("value") },
		assignment_type: { "0": field("name") },
		assignment_typed: { "0": field("name"), "1/3": field("value") },
		attribute: { "2": field("property") },
		case_clause: { "1": field("case_patterns") },
		case_list_pattern: { "1/0": field("list_pattern_case_patterns") },
		case_tuple_pattern: { "1/0": field("list_pattern_case_patterns") },
		class_definition: { "3": field("bases") },
		conditional_expression: { "0": field("consequence") },
		default_parameter: { "2": field("default") },
		dictionary_comprehension: { "2": field("comprehension_clauses") },
		expression: { "-5": alias(sym("lambda"), sym("lambda_expression")) },
		generator_expression: { "2": field("comprehension_clauses") },
		list_comprehension: { "2": field("comprehension_clauses") },
		named_expression: { "0": field("left"), "2": field("right") },
		print_statement_chevron: { "1": field("chevron") },
		set_comprehension: { "2": field("comprehension_clauses") },
		subscript: { "0": field("object") },
		try_statement: { "3": field("handlers"), "4/0": field("alternative"), "5/0": field("finalizer") },
		type_parameter: { "1": field("types") },
		typed_default_parameter: { "4": field("default") }
	},
	renames: [
		rename("function_definition", "function_declaration"),
		rename("class_definition", "class_declaration"),
		rename("typed_parameter", "typed_parameter_declaration"),
		rename("default_parameter", "default_parameter_declaration"),
		rename("typed_default_parameter", "typed_default_parameter_declaration"),
		rename("type_parameter", "type_parameter_declaration"),
		rename("assignment_eq", "variable_declaration"),
		rename("type_alias_statement", "type_alias_declaration"),
		rename("block", "block_statement"),
		rename("for_statement", "for_loop_statement"),
		rename("while_statement", "while_loop_statement"),
		rename("raise_statement", "throw_statement"),
		rename("import_from_statement", "from_import_statement"),
		rename("print_statement_chevron", "chevron_print_statement"),
		rename("with_item", "item_with_clause"),
		rename("for_in_clause", "for_comprehension_clause"),
		rename("if_clause", "if_comprehension_clause"),
		rename("chevron", "chevron_print_clause"),
		rename("relative_import", "relative_import_clause"),
		rename("import_prefix", "prefix_relative_import_clause"),
		rename("aliased_import", "alias_import_clause"),
		rename("wildcard_import", "wildcard_import_clause"),
		rename("comprehension_clauses", "comprehension_clause"),
		rename("pair", "pair_element"),
		rename("list_splat", "splat_element"),
		rename("dictionary_splat", "dictionary_splat_element"),
		rename("parenthesized_list_splat", "parenthesized_splat_element"),
		rename("call", "call_expression"),
		rename("binary_operator", "binary_expression"),
		rename("boolean_operator", "logical_binary_expression"),
		rename("unary_operator", "unary_expression"),
		rename("not_operator", "not_unary_expression"),
		rename("augmented_assignment", "compound_assignment_expression"),
		rename("named_expression", "assignment_expression"),
		rename("attribute", "member_expression"),
		rename("subscript", "subscript_expression"),
		rename("slice", "slice_expression"),
		rename("await", "await_expression"),
		rename("yield", "yield_expression"),
		rename("interpolation", "interpolation_expression"),
		rename("list_comprehension", "list_comprehension_expression"),
		rename("set_comprehension", "set_comprehension_expression"),
		rename("dictionary_comprehension", "dictionary_comprehension_expression"),
		rename("generator_expression", "generator_comprehension_expression"),
		rename("list", "list_collection_expression"),
		rename("tuple", "tuple_collection_expression"),
		rename("expression_list", "bare_tuple_collection_expression"),
		rename("set", "set_collection_expression"),
		rename("dictionary", "dictionary_collection_expression"),
		rename("ellipsis", "ellipsis_literal"),
		rename("format_specifier", "format_interpolation_expression"),
		rename("type_conversion", "conversion_interpolation_expression"),
		rename("pattern_list", "bare_tuple_pattern"),
		rename("list_splat_pattern", "splat_pattern"),
		rename("union_pattern", "or_case_pattern"),
		rename("dict_pattern", "dictionary_case_pattern"),
		rename("keyword_pattern", "keyword_case_pattern"),
		rename("splat_pattern", "splat_case_pattern"),
		rename("class_pattern", "class_case_pattern"),
		rename("complex_pattern", "complex_case_pattern"),
		rename("case_tuple_pattern", "tuple_case_pattern"),
		rename("case_list_pattern", "list_case_pattern"),
		rename("member_type", "path_type"),
		rename("string", "string_literal"),
		rename("escape_sequence", "escape_string_literal"),
		rename("concatenated_string", "concatenated_string_literal"),
		rename("integer_decimal_plain", "integer_number_literal"),
		rename("integer_decimal_long", "big_integer_number_literal"),
		rename("integer_decimal_imaginary", "imaginary_integer_number_literal"),
		rename("integer_hex", "hex_integer_number_literal"),
		rename("integer_binary", "binary_integer_number_literal"),
		rename("integer_octal", "octal_integer_number_literal"),
		rename("float_point", "float_number_literal"),
		rename("float_leading_point", "leading_point_float_number_literal"),
		rename("float_scientific", "scientific_float_number_literal"),
		rename("true", "true_boolean_literal"),
		rename("false", "false_boolean_literal"),
		rename("none", "null_literal"),
		rename("dotted_name", "dotted_identifier"),
		rename("decorator", "decorator_attribute"),
		rename("comment", "line_comment")
	],
	splits: []
});
