// Auto-generated by @sittir/codegen — do not edit

import type * as T from '../types-internal.js';
import { TSKindId } from '../types.js';
import type { AdmitBound, NonEmptyArray } from '@sittir/types';
import {
	withAccessors,
	describeValue,
	restItems,
	coerceBooleanKeywordStorage,
	coerceKindEnumStorage,
	coerceMixedEnumStorage,
	rejectBareText
} from '@sittir/common/utils';
import { withMethods } from '../utils.js';

function _assertNonEmpty<T>(arr: readonly T[], label: string): asserts arr is readonly [T, ...(readonly T[])] {
	if (arr.length === 0) {
		throw new Error(`${label}: requires at least one element`);
	}
}

const _leafRe_buildIdentifier = /^(?:(?:[a-zA-Z0-9\-_][a-zA-Z0-9.\-_]*))$/u;
const _leafRe_buildImmediateIdentifier = /^(?:(?:[a-zA-Z0-9\-_][a-zA-Z0-9.\-_]*))$/u;
const _leafRe_buildStringContentText = /^(?:(?:[^"\\\n]+))$/u;
export const _slotRe_buildEscapeSequence_content = /^(?:(?:.))$/u;
export const _slotRe_buildComment_content = /^(?:(?:.*))$/u;

export function buildProgram(): T.EmptyProgram;
export function buildProgram(...children: AdmitBound<T.Definition[], T.AdmittedNodes>): T.Program.Bound;
export function buildProgram(...children: AdmitBound<T.Definition[], T.AdmittedNodes>): T.Program.Bound {
	const _definitions = rejectBareText(children, 'Program.definitions', 'a built Definition');
	return withMethods(
		withAccessors(
			{
				$type: TSKindId.Program as const,
				$source: 2 as const,
				$named: true as const,
				_definitions,
				$with: { definitions: (...vs: T.Definition[]) => buildProgram(...restItems('definitions', vs)) }
			},
			{
				definitions: () => _definitions
			}
		)
	) as unknown as T.Program.Bound;
}

export function buildEscapeSequence(value: AdmitBound<string, T.AdmittedNodes>): T.EscapeSequence.Bound {
	const _content = value;
	if (_content !== undefined && !_slotRe_buildEscapeSequence_content.test(_content))
		throw new Error(`escape_sequence.content: text does not match pattern: ${describeValue(_content)}`);
	return withMethods(
		withAccessors(
			{
				$type: TSKindId.EscapeSequence as const,
				$source: 2 as const,
				$named: true as const,
				_content,
				$with: {
					content: (value: string) => buildEscapeSequence(value)
				}
			},
			{
				content: () => _content
			}
		)
	) as unknown as T.EscapeSequence.Bound;
}

export function buildIdentifier(text: string): T.Identifier.Bound {
	if (text.length === 0) throw new Error(`identifier: text must be non-empty`);
	if (!_leafRe_buildIdentifier.test(text))
		throw new Error(`identifier: text does not match pattern: ${describeValue(text)}`);
	return withMethods({
		$type: TSKindId.Identifier as const,
		$source: 2 as const,
		$named: true as const,
		$text: text
	});
}

export function buildImmediateIdentifier(text: string): T.ImmediateIdentifier.Bound {
	if (text.length === 0) throw new Error(`_immediate_identifier: text must be non-empty`);
	if (!_leafRe_buildImmediateIdentifier.test(text))
		throw new Error(`_immediate_identifier: text does not match pattern: ${describeValue(text)}`);
	return withMethods({
		$type: TSKindId.ImmediateIdentifier as const,
		$source: 2 as const,
		$named: true as const,
		$text: text
	});
}

export function buildCapture(
	value: AdmitBound<T.ImmediateIdentifier, T.AdmittedNodes>
): ReturnType<typeof _buildCapture>;
export function buildCapture(text: string): ReturnType<typeof _buildCapture>;
export function buildCapture(...args: unknown[]) {
	if (args.length === 0 || (args.length === 1 && typeof args[0] !== 'object')) {
		return _buildCapture(args[0] as T.ImmediateIdentifier);
	}
	const prebuilt =
		args.length === 1 &&
		typeof args[0] === 'object' &&
		args[0] !== null &&
		(args[0] as { $type?: unknown }).$type === (TSKindId.ImmediateIdentifier as const);
	return prebuilt
		? _buildCapture(args[0] as T.ImmediateIdentifier)
		: _buildCapture((buildImmediateIdentifier as (...a: unknown[]) => unknown)(...args) as T.ImmediateIdentifier);
}
function _buildCapture(value: AdmitBound<T.ImmediateIdentifier, T.AdmittedNodes>): T.Capture.Bound {
	const _name = rejectBareText(value, 'Capture.name', 'buildImmediateIdentifier(…)');
	return withMethods(
		withAccessors(
			{
				$type: TSKindId.Capture as const,
				$source: 2 as const,
				$named: true as const,
				_name,
				$with: {
					name: (value: T.ImmediateIdentifier) => buildCapture(value)
				}
			},
			{
				name: () => _name
			}
		)
	) as unknown as T.Capture.Bound;
}

export function buildString(value?: AdmitBound<T.StringContent, T.AdmittedNodes>): ReturnType<typeof _buildString>;
export function buildString(
	...children: AdmitBound<(T.StringContentText | T.EscapeSequence)[], T.AdmittedNodes>
): ReturnType<typeof _buildString>;
export function buildString(...args: unknown[]) {
	if (args.length === 0 || (args.length === 1 && typeof args[0] !== 'object')) {
		return _buildString(args[0] as T.StringContent);
	}
	const prebuilt =
		args.length === 1 &&
		typeof args[0] === 'object' &&
		args[0] !== null &&
		(args[0] as { $type?: unknown }).$type === (TSKindId.StringContent as const);
	return prebuilt
		? _buildString(args[0] as T.StringContent)
		: _buildString((buildStringContent as (...a: unknown[]) => unknown)(...args) as T.StringContent);
}
function _buildString(value?: AdmitBound<T.StringContent, T.AdmittedNodes>): T.String.Bound {
	const _string_content = rejectBareText(value, 'String.stringContent', 'a built StringContent');
	return withMethods(
		withAccessors(
			{
				$type: TSKindId.String as const,
				$source: 2 as const,
				$named: true as const,
				_string_content,
				$with: {
					stringContent: (value?: T.StringContent) => buildString(value)
				}
			},
			{
				stringContent: () => _string_content
			}
		)
	) as unknown as T.String.Bound;
}

export function buildImmediateString(
	value?: AdmitBound<T.StringContent, T.AdmittedNodes>
): ReturnType<typeof _buildImmediateString>;
export function buildImmediateString(
	...children: AdmitBound<(T.StringContentText | T.EscapeSequence)[], T.AdmittedNodes>
): ReturnType<typeof _buildImmediateString>;
export function buildImmediateString(...args: unknown[]) {
	if (args.length === 0 || (args.length === 1 && typeof args[0] !== 'object')) {
		return _buildImmediateString(args[0] as T.StringContent);
	}
	const prebuilt =
		args.length === 1 &&
		typeof args[0] === 'object' &&
		args[0] !== null &&
		(args[0] as { $type?: unknown }).$type === (TSKindId.StringContent as const);
	return prebuilt
		? _buildImmediateString(args[0] as T.StringContent)
		: _buildImmediateString((buildStringContent as (...a: unknown[]) => unknown)(...args) as T.StringContent);
}
function _buildImmediateString(value?: AdmitBound<T.StringContent, T.AdmittedNodes>): T.ImmediateString.Bound {
	const _string_content = rejectBareText(value, 'ImmediateString.stringContent', 'a built StringContent');
	return withMethods(
		withAccessors(
			{
				$type: TSKindId.ImmediateString as const,
				$source: 2 as const,
				$named: true as const,
				_string_content,
				$with: {
					stringContent: (value?: T.StringContent) => buildImmediateString(value)
				}
			},
			{
				stringContent: () => _string_content
			}
		)
	) as unknown as T.ImmediateString.Bound;
}

export function buildStringContent(
	...children: AdmitBound<(T.StringContentText | T.EscapeSequence)[], T.AdmittedNodes>
): T.StringContent.Bound {
	const _content = rejectBareText(children, 'StringContent.content', 'buildStringContentText(…)');
	return withMethods(
		withAccessors(
			{
				$type: TSKindId.StringContent as const,
				$source: 2 as const,
				$named: true as const,
				_content,
				$with: {
					contents: (...vs: (T.StringContentText | T.EscapeSequence)[]) =>
						buildStringContent(...restItems('contents', vs))
				}
			},
			{
				contents: () => _content
			}
		)
	) as unknown as T.StringContent.Bound;
}

export function buildParameters(
	...children: AdmitBound<(T.Capture | T.String | T.Identifier)[], T.AdmittedNodes>
): T.Parameters.Bound {
	_assertNonEmpty(children, 'parameters.children');
	const _elements = rejectBareText(children, 'Parameters.elements', 'buildIdentifier(…)');
	return withMethods(
		withAccessors(
			{
				$type: TSKindId.Parameters as const,
				$source: 2 as const,
				$named: true as const,
				_elements,
				$with: {
					elements: (...vs: (T.Capture | T.String | T.Identifier)[]) => buildParameters(...restItems('elements', vs))
				}
			},
			{
				elements: () => _elements
			}
		)
	) as unknown as T.Parameters.Bound;
}

export function buildComment(value: AdmitBound<string, T.AdmittedNodes>): T.Comment.Bound {
	const _content = value;
	if (_content !== undefined && !_slotRe_buildComment_content.test(_content))
		throw new Error(`comment.content: text does not match pattern: ${describeValue(_content)}`);
	return withMethods(
		withAccessors(
			{
				$type: TSKindId.Comment as const,
				$source: 2 as const,
				$named: true as const,
				_content,
				$with: {
					content: (value: string) => buildComment(value)
				}
			},
			{
				content: () => _content
			}
		)
	) as unknown as T.Comment.Bound;
}

export function buildList(config: T.List.Config): T.List.Bound {
	const _definitions = rejectBareText(config.definitions ?? [], 'List.definitions', 'a built Definition');
	const _elements = rejectBareText(config.elements ?? [], 'List.elements', 'a built ListElement');
	return withMethods(
		withAccessors(
			{
				$type: TSKindId.List as const,
				$source: 2 as const,
				$named: true as const,
				_definitions,
				_elements,
				$with: {
					definitions: (...values: NonEmptyArray<T.Definition>) =>
						buildList({ ...config, definitions: restItems('definitions', values) }),
					elements: (...values: T.ListElement[]) => buildList({ ...config, elements: restItems('elements', values) })
				}
			},
			{
				definitions: () => _definitions,
				elements: () => _elements
			}
		)
	) as unknown as T.List.Bound;
}

export function buildGrouping(config: T.Grouping.Config): T.Grouping.Bound {
	const _grouping_group = rejectBareText(config.groupingGroup ?? [], 'Grouping.groupingGroup', 'a built GroupingGroup');
	const _elements = rejectBareText(config.elements ?? [], 'Grouping.elements', 'a built ListElement');
	return withMethods(
		withAccessors(
			{
				$type: TSKindId.Grouping as const,
				$source: 2 as const,
				$named: true as const,
				_grouping_group,
				_elements,
				$with: {
					groupingGroups: (...values: NonEmptyArray<T.GroupingGroup>) =>
						buildGrouping({ ...config, groupingGroup: restItems('groupingGroups', values) }),
					elements: (...values: T.ListElement[]) =>
						buildGrouping({ ...config, elements: restItems('elements', values) })
				}
			},
			{
				groupingGroups: () => _grouping_group,
				elements: () => _elements
			}
		)
	) as unknown as T.Grouping.Bound;
}

export function buildMissingNode(): T.EmptyMissingNode;
export function buildMissingNode(config?: Partial<T.MissingNode.Config>): T.MissingNode.Bound;
export function buildMissingNode(config: Partial<T.MissingNode.Config> = {}): T.MissingNode.Bound {
	const _name = rejectBareText(config.name, 'MissingNode.name', 'buildIdentifier(…)');
	const _elements = rejectBareText(config.elements ?? [], 'MissingNode.elements', 'a built ListElement');
	return withMethods(
		withAccessors(
			{
				$type: TSKindId.MissingNode as const,
				$source: 2 as const,
				$named: true as const,
				_name,
				_elements,
				$with: {
					name: (value?: T.Identifier | T.String) => buildMissingNode({ ...config, name: value }),
					elements: (...values: T.ListElement[]) =>
						buildMissingNode({ ...config, elements: restItems('elements', values) })
				}
			},
			{
				name: () => _name,
				elements: () => _elements
			}
		)
	) as unknown as T.MissingNode.Bound;
}

export function buildAnonymousNode(config: Partial<T.AnonymousNode.Config> = {}): T.AnonymousNode.Bound {
	const _name = rejectBareText(
		coerceMixedEnumStorage<NonNullable<T.AnonymousNode['_name']>>(config.name, [['_', TSKindId.Underscore] as const]),
		'AnonymousNode.name',
		'a built String'
	);
	const _elements = rejectBareText(config.elements ?? [], 'AnonymousNode.elements', 'a built ListElement');
	return withMethods(
		withAccessors(
			{
				$type: TSKindId.AnonymousNode as const,
				$source: 2 as const,
				$named: true as const,
				_name,
				_elements,
				$with: {
					name: (value: NonNullable<T.AnonymousNode.Config>['name']) => buildAnonymousNode({ ...config, name: value }),
					elements: (...values: T.ListElement[]) =>
						buildAnonymousNode({ ...config, elements: restItems('elements', values) })
				}
			},
			{
				name: () => _name,
				elements: () => _elements
			}
		)
	) as unknown as T.AnonymousNode.Bound;
}

export function buildFieldDefinition(config: T.FieldDefinition.Config): T.FieldDefinition.Bound {
	const _name = rejectBareText(config.name, 'FieldDefinition.name', 'buildIdentifier(…)');
	const _definition = rejectBareText(config.definition, 'FieldDefinition.definition', 'a built Definition');
	return withMethods(
		withAccessors(
			{
				$type: TSKindId.FieldDefinition as const,
				$source: 2 as const,
				$named: true as const,
				_name,
				_definition,
				$with: {
					name: (value: T.Identifier) => buildFieldDefinition({ ...config, name: value }),
					definition: (value: T.Definition) => buildFieldDefinition({ ...config, definition: value })
				}
			},
			{
				name: () => _name,
				definition: () => _definition
			}
		)
	) as unknown as T.FieldDefinition.Bound;
}

export function buildNegatedField(
	value: AdmitBound<T.Identifier, T.AdmittedNodes>
): ReturnType<typeof _buildNegatedField>;
export function buildNegatedField(text: string): ReturnType<typeof _buildNegatedField>;
export function buildNegatedField(...args: unknown[]) {
	if (args.length === 0 || (args.length === 1 && typeof args[0] !== 'object')) {
		return _buildNegatedField(args[0] as T.Identifier);
	}
	const prebuilt =
		args.length === 1 &&
		typeof args[0] === 'object' &&
		args[0] !== null &&
		(args[0] as { $type?: unknown }).$type === (TSKindId.Identifier as const);
	return prebuilt
		? _buildNegatedField(args[0] as T.Identifier)
		: _buildNegatedField((buildIdentifier as (...a: unknown[]) => unknown)(...args) as T.Identifier);
}
function _buildNegatedField(value: AdmitBound<T.Identifier, T.AdmittedNodes>): T.NegatedField.Bound {
	const _identifier = rejectBareText(value, 'NegatedField.identifier', 'buildIdentifier(…)');
	return withMethods(
		withAccessors(
			{
				$type: TSKindId.NegatedField as const,
				$source: 2 as const,
				$named: true as const,
				_identifier,
				$with: {
					identifier: (value: T.Identifier) => buildNegatedField(value)
				}
			},
			{
				identifier: () => _identifier
			}
		)
	) as unknown as T.NegatedField.Bound;
}

export function buildPredicate(config: T.Predicate.Config): T.Predicate.Bound {
	const _prefix = coerceKindEnumStorage<NonNullable<T.Predicate['_prefix']>>(config.prefix, [
		['#', TSKindId.Pound] as const,
		['.', TSKindId.Dot] as const
	]);
	const _name = rejectBareText(config.name, 'Predicate.name', 'buildImmediateIdentifier(…)');
	const _type = coerceKindEnumStorage<NonNullable<T.Predicate['_type']>>(config.type, [
		['?', TSKindId.Qmark] as const,
		['!', TSKindId.Bang] as const
	]);
	const _parameters = rejectBareText(config.parameters, 'Predicate.parameters', 'a built Parameters');
	return withMethods(
		withAccessors(
			{
				$type: TSKindId.Predicate as const,
				$source: 2 as const,
				$named: true as const,
				_prefix,
				_name,
				_type,
				_parameters,
				$with: {
					prefix: (value: NonNullable<T.Predicate.Config>['prefix']) => buildPredicate({ ...config, prefix: value }),
					name: (value: T.ImmediateIdentifier) => buildPredicate({ ...config, name: value }),
					type: (value: NonNullable<T.Predicate.Config>['type']) => buildPredicate({ ...config, type: value }),
					parameters: (value?: T.Parameters) => buildPredicate({ ...config, parameters: value })
				}
			},
			{
				prefix: () => _prefix,
				name: () => _name,
				type: () => _type,
				parameters: () => _parameters
			}
		)
	) as unknown as T.Predicate.Bound;
}

export function buildListElementQuantifier(
	value: AdmitBound<TSKindId.Star | TSKindId.Plus | TSKindId.Qmark, T.AdmittedNodes>
): T.ListElementQuantifier.Bound {
	const _quantifier = coerceKindEnumStorage<NonNullable<T.ListElementQuantifier['_quantifier']>>(value, [
		['*', TSKindId.Star] as const,
		['+', TSKindId.Plus] as const,
		['?', TSKindId.Qmark] as const
	]);
	return withMethods(
		withAccessors(
			{
				$type: TSKindId.ListElementQuantifier as const,
				$source: 2 as const,
				$named: true as const,
				_quantifier,
				$with: {
					quantifier: (value: NonNullable<TSKindId.Star | TSKindId.Plus | TSKindId.Qmark>) =>
						buildListElementQuantifier(value)
				}
			},
			{
				quantifier: () => _quantifier
			}
		)
	) as unknown as T.ListElementQuantifier.Bound;
}

export function buildGroupExpressionArm(config: T.GroupExpressionArm.Config): T.GroupExpressionArm.Bound {
	const _left = rejectBareText(config.left, 'GroupExpressionArm.left', 'a built Definition / GroupExpressionArm');
	const _right = rejectBareText(config.right, 'GroupExpressionArm.right', 'a built Definition / GroupExpressionArm');
	return withMethods(
		withAccessors(
			{
				$type: TSKindId.GroupExpressionArm as const,
				$source: 2 as const,
				$named: true as const,
				_left,
				_right,
				$with: {
					left: (value: T.Definition | T.GroupExpressionArm) => buildGroupExpressionArm({ ...config, left: value }),
					right: (value: T.Definition | T.GroupExpressionArm) => buildGroupExpressionArm({ ...config, right: value })
				}
			},
			{
				left: () => _left,
				right: () => _right
			}
		)
	) as unknown as T.GroupExpressionArm.Bound;
}

export function buildNamedNodeExpressionArm(config: T.NamedNodeExpressionArm.Config): T.NamedNodeExpressionArm.Bound {
	const _left = rejectBareText(
		config.left,
		'NamedNodeExpressionArm.left',
		'a built Definition / NegatedField / NamedNodeExpressionArm'
	);
	const _right = rejectBareText(
		config.right,
		'NamedNodeExpressionArm.right',
		'a built Definition / NegatedField / NamedNodeExpressionArm'
	);
	return withMethods(
		withAccessors(
			{
				$type: TSKindId.NamedNodeExpressionArm as const,
				$source: 2 as const,
				$named: true as const,
				_left,
				_right,
				$with: {
					left: (value: T.Definition | T.NegatedField | T.NamedNodeExpressionArm) =>
						buildNamedNodeExpressionArm({ ...config, left: value }),
					right: (value: T.Definition | T.NegatedField | T.NamedNodeExpressionArm) =>
						buildNamedNodeExpressionArm({ ...config, right: value })
				}
			},
			{
				left: () => _left,
				right: () => _right
			}
		)
	) as unknown as T.NamedNodeExpressionArm.Bound;
}

export function buildGroupingGroup(config: T.GroupingGroup.Config): T.GroupingGroup.Bound {
	const _group_expression = rejectBareText(
		config.groupExpression,
		'GroupingGroup.groupExpression',
		'a built Definition / GroupExpressionArm'
	);
	const _anchor = coerceBooleanKeywordStorage(config.anchor);
	return withMethods(
		withAccessors(
			{
				$type: TSKindId.GroupingGroup as const,
				$source: 2 as const,
				$named: true as const,
				_group_expression,
				_anchor,
				$with: {
					groupExpression: (value: T.Definition | T.GroupExpressionArm) =>
						buildGroupingGroup({ ...config, groupExpression: value }),
					anchor: (value?: NonNullable<T.GroupingGroup.Config>['anchor']) =>
						buildGroupingGroup({ ...config, anchor: value })
				}
			},
			{
				groupExpression: () => _group_expression,
				anchor: () => _anchor
			}
		)
	) as unknown as T.GroupingGroup.Bound;
}

export function buildStringContentText(text: string): T.StringContentText.Bound {
	if (text.length === 0) throw new Error(`string_content_text: text must be non-empty`);
	if (!_leafRe_buildStringContentText.test(text))
		throw new Error(`string_content_text: text does not match pattern: ${describeValue(text)}`);
	return withMethods({
		$type: TSKindId.StringContentText as const,
		$source: 2 as const,
		$named: true as const,
		$text: text
	});
}

export const buildAnchor: TSKindId.Anchor = TSKindId.Anchor;

export function buildNamedNodePlain(config: T.NamedNodePlain.Config): T.NamedNodePlain.Bound {
	const _name = rejectBareText(
		coerceMixedEnumStorage<NonNullable<T.NamedNodePlain['_name']>>(config.name, [['_', TSKindId.Underscore] as const]),
		'NamedNodePlain.name',
		'buildIdentifier(…)'
	);
	const _named_node_group = rejectBareText(
		config.namedNodeGroup,
		'NamedNodePlain.namedNodeGroup',
		'a built NamedNodeGroup'
	);
	const _elements = rejectBareText(config.elements ?? [], 'NamedNodePlain.elements', 'a built ListElement');
	return withMethods(
		withAccessors(
			{
				$type: TSKindId.NamedNodePlain as const,
				$source: 2 as const,
				$named: true as const,
				_name,
				_named_node_group,
				_elements,
				$with: {
					name: (value: NonNullable<T.NamedNodePlain.Config>['name']) =>
						buildNamedNodePlain({ ...config, name: value }),
					namedNodeGroup: (value?: T.NamedNodeGroup) => buildNamedNodePlain({ ...config, namedNodeGroup: value }),
					elements: (...values: T.ListElement[]) =>
						buildNamedNodePlain({ ...config, elements: restItems('elements', values) })
				}
			},
			{
				name: () => _name,
				namedNodeGroup: () => _named_node_group,
				elements: () => _elements
			}
		)
	) as unknown as T.NamedNodePlain.Bound;
}

export function buildNamedNodeSupertyped(config: T.NamedNodeSupertyped.Config): T.NamedNodeSupertyped.Bound {
	const _supertype = rejectBareText(config.supertype, 'NamedNodeSupertyped.supertype', 'buildIdentifier(…)');
	const _name = rejectBareText(config.name, 'NamedNodeSupertyped.name', 'buildImmediateIdentifier(…)');
	const _named_node_group = rejectBareText(
		config.namedNodeGroup,
		'NamedNodeSupertyped.namedNodeGroup',
		'a built NamedNodeGroup'
	);
	const _elements = rejectBareText(config.elements ?? [], 'NamedNodeSupertyped.elements', 'a built ListElement');
	return withMethods(
		withAccessors(
			{
				$type: TSKindId.NamedNodeSupertyped as const,
				$source: 2 as const,
				$named: true as const,
				_supertype,
				_name,
				_named_node_group,
				_elements,
				$with: {
					supertype: (value: T.Identifier) => buildNamedNodeSupertyped({ ...config, supertype: value }),
					name: (value: T.ImmediateIdentifier | T.ImmediateString) =>
						buildNamedNodeSupertyped({ ...config, name: value }),
					namedNodeGroup: (value?: T.NamedNodeGroup) => buildNamedNodeSupertyped({ ...config, namedNodeGroup: value }),
					elements: (...values: T.ListElement[]) =>
						buildNamedNodeSupertyped({ ...config, elements: restItems('elements', values) })
				}
			},
			{
				supertype: () => _supertype,
				name: () => _name,
				namedNodeGroup: () => _named_node_group,
				elements: () => _elements
			}
		)
	) as unknown as T.NamedNodeSupertyped.Bound;
}

export function buildNamedNodeGroupChildren(config: T.NamedNodeGroupChildren.Config): T.NamedNodeGroupChildren.Bound {
	const _anchor = coerceBooleanKeywordStorage(config.anchor);
	const _named_node_expressions = rejectBareText(
		config.namedNodeExpressions ?? [],
		'NamedNodeGroupChildren.namedNodeExpressions',
		'a built Definition / NegatedField / NamedNodeExpressionArm'
	);
	return withMethods(
		withAccessors(
			{
				$type: TSKindId.NamedNodeGroupChildren as const,
				$source: 2 as const,
				$named: true as const,
				_anchor,
				_named_node_expressions,
				$with: {
					anchor: (value?: NonNullable<T.NamedNodeGroupChildren.Config>['anchor']) =>
						buildNamedNodeGroupChildren({ ...config, anchor: value }),
					namedNodeExpressions: (...values: NonEmptyArray<T.Definition | T.NegatedField | T.NamedNodeExpressionArm>) =>
						buildNamedNodeGroupChildren({ ...config, namedNodeExpressions: restItems('namedNodeExpressions', values) })
				}
			},
			{
				anchor: () => _anchor,
				namedNodeExpressions: () => _named_node_expressions
			}
		)
	) as unknown as T.NamedNodeGroupChildren.Bound;
}

export function buildNamedNodeGroupAnchoredLast(
	config: T.NamedNodeGroupAnchoredLast.Config
): T.NamedNodeGroupAnchoredLast.Bound {
	const _anchor = coerceBooleanKeywordStorage(config.anchor);
	const _named_node_expressions = rejectBareText(
		config.namedNodeExpressions ?? [],
		'NamedNodeGroupAnchoredLast.namedNodeExpressions',
		'a built Definition / NegatedField / NamedNodeExpressionArm'
	);
	const _last = rejectBareText(
		config.last,
		'NamedNodeGroupAnchoredLast.last',
		'a built Definition / NegatedField / NamedNodeExpressionArm'
	);
	return withMethods(
		withAccessors(
			{
				$type: TSKindId.NamedNodeGroupAnchoredLast as const,
				$source: 2 as const,
				$named: true as const,
				_anchor,
				_named_node_expressions,
				_last,
				$with: {
					anchor: (value?: NonNullable<T.NamedNodeGroupAnchoredLast.Config>['anchor']) =>
						buildNamedNodeGroupAnchoredLast({ ...config, anchor: value }),
					namedNodeExpressions: (...values: (T.Definition | T.NegatedField | T.NamedNodeExpressionArm)[]) =>
						buildNamedNodeGroupAnchoredLast({
							...config,
							namedNodeExpressions: restItems('namedNodeExpressions', values)
						}),
					last: (value: T.Definition | T.NegatedField | T.NamedNodeExpressionArm) =>
						buildNamedNodeGroupAnchoredLast({ ...config, last: value })
				}
			},
			{
				anchor: () => _anchor,
				namedNodeExpressions: () => _named_node_expressions,
				last: () => _last
			}
		)
	) as unknown as T.NamedNodeGroupAnchoredLast.Bound;
}

export const buildTight: TSKindId.Tight = TSKindId.Tight;

export const buildSpace: TSKindId.Space = TSKindId.Space;

export const buildTab: TSKindId.Tab = TSKindId.Tab;

export const buildNewline: TSKindId.Newline = TSKindId.Newline;

export const buildBlankline: TSKindId.Blankline = TSKindId.Blankline;

export const buildDoubleBlankline: TSKindId.DoubleBlankline = TSKindId.DoubleBlankline;

export const buildIndent: TSKindId.Indent = TSKindId.Indent;

export const buildDedent: TSKindId.Dedent = TSKindId.Dedent;

export type FluentKindMap = {
	program: T.Program.Bound;
	escape_sequence: T.EscapeSequence.Bound;
	identifier: T.Identifier;
	_immediate_identifier: T.ImmediateIdentifier;
	capture: T.Capture.Bound;
	string: T.String.Bound;
	immediate_string: T.ImmediateString.Bound;
	string_content: T.StringContent.Bound;
	parameters: T.Parameters.Bound;
	comment: T.Comment.Bound;
	list: T.List.Bound;
	grouping: T.Grouping.Bound;
	missing_node: T.MissingNode.Bound;
	anonymous_node: T.AnonymousNode.Bound;
	field_definition: T.FieldDefinition.Bound;
	negated_field: T.NegatedField.Bound;
	predicate: T.Predicate.Bound;
	list_element_quantifier: T.ListElementQuantifier.Bound;
	group_expression_arm: T.GroupExpressionArm.Bound;
	named_node_expression_arm: T.NamedNodeExpressionArm.Bound;
	grouping_group: T.GroupingGroup.Bound;
	string_content_text: T.StringContentText;
	anchor: T.Anchor;
	named_node_plain: T.NamedNodePlain.Bound;
	named_node_supertyped: T.NamedNodeSupertyped.Bound;
	named_node_group_children: T.NamedNodeGroupChildren.Bound;
	named_node_group_anchored_last: T.NamedNodeGroupAnchoredLast.Bound;
	_tight: T.Tight;
	_space: T.Space;
	_tab: T.Tab;
	_newline: T.Newline;
	_blankline: T.Blankline;
	_double_blankline: T.DoubleBlankline;
	_indent: T.Indent;
	_dedent: T.Dedent;
};

export const _factoryMap = {
	program: buildProgram,
	escape_sequence: buildEscapeSequence,
	identifier: buildIdentifier,
	_immediate_identifier: buildImmediateIdentifier,
	capture: buildCapture,
	string: buildString,
	immediate_string: buildImmediateString,
	string_content: buildStringContent,
	parameters: buildParameters,
	comment: buildComment,
	list: buildList,
	grouping: buildGrouping,
	missing_node: buildMissingNode,
	anonymous_node: buildAnonymousNode,
	field_definition: buildFieldDefinition,
	negated_field: buildNegatedField,
	predicate: buildPredicate,
	list_element_quantifier: buildListElementQuantifier,
	group_expression_arm: buildGroupExpressionArm,
	named_node_expression_arm: buildNamedNodeExpressionArm,
	grouping_group: buildGroupingGroup,
	string_content_text: buildStringContentText,
	anchor: buildAnchor,
	named_node_plain: buildNamedNodePlain,
	named_node_supertyped: buildNamedNodeSupertyped,
	named_node_group_children: buildNamedNodeGroupChildren,
	named_node_group_anchored_last: buildNamedNodeGroupAnchoredLast,
	_tight: buildTight,
	_space: buildSpace,
	_tab: buildTab,
	_newline: buildNewline,
	_blankline: buildBlankline,
	_double_blankline: buildDoubleBlankline,
	_indent: buildIndent,
	_dedent: buildDedent
} as const;
export type _FactoryMap = typeof _factoryMap;
