// Auto-generated by @sittir/codegen — do not edit
import { describe, it, expect } from 'vitest';
import { ir } from '../src/ir.js';
import { TSKindId } from '../src/types.js';

describe('pattern', () => {
	it('factory produces correct type', () => {
		const node = ir.pattern({
			$type: TSKindId.Alternation,
			$text: 'test',
			$source: 2,
			$named: true,
			_term: [
				{
					$type: TSKindId.Term,
					$text: 'test',
					$source: 2,
					$named: true,
					_term_group: [
						{
							$type: TSKindId.TermGroup,
							$text: 'test',
							$source: 2,
							$named: true,
							_content: { $type: TSKindId.StartAssertion, $text: '^', $source: 2, $named: true } as any
						} as any
					]
				} as any
			]
		} as any);
		expect(node.$type).toBe(TSKindId.Pattern);
		expect(node.$source).toBe(2);
	});
	it('render produces non-empty string', () => {
		const node = ir.pattern({
			$type: TSKindId.Alternation,
			$text: 'test',
			$source: 2,
			$named: true,
			_term: [
				{
					$type: TSKindId.Term,
					$text: 'test',
					$source: 2,
					$named: true,
					_term_group: [
						{
							$type: TSKindId.TermGroup,
							$text: 'test',
							$source: 2,
							$named: true,
							_content: { $type: TSKindId.StartAssertion, $text: '^', $source: 2, $named: true } as any
						} as any
					]
				} as any
			]
		} as any);
		const rendered = node.$render!();
		expect(rendered.length).toBeGreaterThan(0);
		expect(rendered).toContain('^');
	});
});

describe('pattern sub-factories', () => {
	it('alternation builds the parent', () => {
		const node = ir.pattern.alternation({
			$type: TSKindId.Term,
			$text: 'test',
			$source: 2,
			$named: true,
			_term_group: [
				{
					$type: TSKindId.TermGroup,
					$text: 'test',
					$source: 2,
					$named: true,
					_content: { $type: TSKindId.StartAssertion, $text: '^', $source: 2, $named: true } as any
				} as any
			]
		} as any);
		expect(node.$type).toBe(TSKindId.Pattern);
		expect((node as any).content()?.$type).toBe(TSKindId.Alternation);
		expect(node.$render!().length).toBeGreaterThan(0);
	});
	it('term builds the parent', () => {
		const node = ir.pattern.term({
			$type: TSKindId.TermGroup,
			$text: 'test',
			$source: 2,
			$named: true,
			_content: { $type: TSKindId.StartAssertion, $text: '^', $source: 2, $named: true } as any
		} as any);
		expect(node.$type).toBe(TSKindId.Pattern);
		expect((node as any).content()?.$type).toBe(TSKindId.Term);
		expect(node.$render!().length).toBeGreaterThan(0);
	});
});

describe('alternation', () => {
	it('factory produces correct type', () => {
		const node = ir.alternation({
			$type: TSKindId.Term,
			$text: 'test',
			$source: 2,
			$named: true,
			_term_group: [
				{
					$type: TSKindId.TermGroup,
					$text: 'test',
					$source: 2,
					$named: true,
					_content: { $type: TSKindId.StartAssertion, $text: '^', $source: 2, $named: true } as any
				} as any
			]
		} as any);
		expect(node.$type).toBe(TSKindId.Alternation);
		expect(node.$source).toBe(2);
	});
	it('render produces non-empty string', () => {
		const node = ir.alternation({
			$type: TSKindId.Term,
			$text: 'test',
			$source: 2,
			$named: true,
			_term_group: [
				{
					$type: TSKindId.TermGroup,
					$text: 'test',
					$source: 2,
					$named: true,
					_content: { $type: TSKindId.StartAssertion, $text: '^', $source: 2, $named: true } as any
				} as any
			]
		} as any);
		const rendered = node.$render!();
		expect(rendered.length).toBeGreaterThan(0);
		expect(rendered).toContain('^');
	});
});

describe('term', () => {
	it('factory produces correct type', () => {
		const node = ir.term({
			$type: TSKindId.TermGroup,
			$text: 'test',
			$source: 2,
			$named: true,
			_content: { $type: TSKindId.StartAssertion, $text: '^', $source: 2, $named: true } as any,
			_quantifier: { $type: TSKindId.ZeroOrMore, $text: 'test', $source: 2, $named: true } as any
		} as any);
		expect(node.$type).toBe(TSKindId.Term);
		expect(node.$source).toBe(2);
	});
	it('render produces non-empty string', () => {
		const node = ir.term({
			$type: TSKindId.TermGroup,
			$text: 'test',
			$source: 2,
			$named: true,
			_content: { $type: TSKindId.StartAssertion, $text: '^', $source: 2, $named: true } as any,
			_quantifier: { $type: TSKindId.ZeroOrMore, $text: 'test', $source: 2, $named: true } as any
		} as any);
		const rendered = node.$render!();
		expect(rendered.length).toBeGreaterThan(0);
		expect(rendered).toContain('^');
		expect(rendered).toContain('test');
	});
});

describe('term sub-factories', () => {
	it('group builds the term_group form', () => {
		const node = ir.term.group({
			content: { $type: TSKindId.StartAssertion, $text: '^', $source: 2, $named: true } as any
		});
		expect(node.$type).toBe(TSKindId.TermGroup);
		expect(node.$render!().length).toBeGreaterThan(0);
	});
});

describe('any_character', () => {
	it('factory produces the kind id', () => {
		expect(ir.anyCharacter()).toBe(TSKindId.AnyCharacter);
	});
});

describe('start_assertion', () => {
	it('factory produces the kind id', () => {
		expect(ir.startAssertion()).toBe(TSKindId.StartAssertion);
	});
});

describe('end_assertion', () => {
	it('factory produces the kind id', () => {
		expect(ir.endAssertion()).toBe(TSKindId.EndAssertion);
	});
});

describe('boundary_assertion', () => {
	it('factory produces the kind id', () => {
		expect(ir.boundaryAssertion()).toBe(TSKindId.BoundaryAssertion);
	});
});

describe('non_boundary_assertion', () => {
	it('factory produces the kind id', () => {
		expect(ir.nonBoundaryAssertion()).toBe(TSKindId.NonBoundaryAssertion);
	});
});

describe('lookaround_assertion', () => {
	it('factory produces correct type', () => {
		const node = ir.lookaroundAssertion({
			$type: TSKindId.LookaheadAssertion,
			$text: 'test',
			$source: 2,
			$named: true,
			_content: TSKindId.Eq as never,
			_pattern: {
				$type: TSKindId.Pattern,
				$text: 'test',
				$source: 2,
				$named: true,
				_content: {
					$type: TSKindId.Alternation,
					$text: 'test',
					$source: 2,
					$named: true,
					_term: [
						{
							$type: TSKindId.Term,
							$text: 'test',
							$source: 2,
							$named: true,
							_term_group: [
								{
									$type: TSKindId.TermGroup,
									$text: 'test',
									$source: 2,
									$named: true,
									_content: { $type: TSKindId.StartAssertion, $text: '^', $source: 2, $named: true } as any
								} as any
							]
						} as any
					]
				} as any
			} as any
		} as any);
		expect(node.$type).toBe(TSKindId.LookaroundAssertion);
		expect(node.$source).toBe(2);
	});
	it('render produces non-empty string', () => {
		const node = ir.lookaroundAssertion({
			$type: TSKindId.LookaheadAssertion,
			$text: 'test',
			$source: 2,
			$named: true,
			_content: TSKindId.Eq as never,
			_pattern: {
				$type: TSKindId.Pattern,
				$text: 'test',
				$source: 2,
				$named: true,
				_content: {
					$type: TSKindId.Alternation,
					$text: 'test',
					$source: 2,
					$named: true,
					_term: [
						{
							$type: TSKindId.Term,
							$text: 'test',
							$source: 2,
							$named: true,
							_term_group: [
								{
									$type: TSKindId.TermGroup,
									$text: 'test',
									$source: 2,
									$named: true,
									_content: { $type: TSKindId.StartAssertion, $text: '^', $source: 2, $named: true } as any
								} as any
							]
						} as any
					]
				} as any
			} as any
		} as any);
		const rendered = node.$render!();
		expect(rendered.length).toBeGreaterThan(0);
		expect(rendered).toContain('^');
	});
});

describe('lookaround_assertion sub-factories', () => {
	it('lookaheadAssertion builds the parent', () => {
		const node = ir.lookaroundAssertion.lookaheadAssertion({
			content: '=',
			pattern: {
				$type: TSKindId.Pattern,
				$text: 'test',
				$source: 2,
				$named: true,
				_content: {
					$type: TSKindId.Alternation,
					$text: 'test',
					$source: 2,
					$named: true,
					_term: [
						{
							$type: TSKindId.Term,
							$text: 'test',
							$source: 2,
							$named: true,
							_term_group: [
								{
									$type: TSKindId.TermGroup,
									$text: 'test',
									$source: 2,
									$named: true,
									_content: { $type: TSKindId.StartAssertion, $text: '^', $source: 2, $named: true } as any
								} as any
							]
						} as any
					]
				} as any
			} as any
		});
		expect(node.$type).toBe(TSKindId.LookaroundAssertion);
		expect((node as any).content()?.$type).toBe(TSKindId.LookaheadAssertion);
		expect(node.$render!().length).toBeGreaterThan(0);
	});
	it('lookbehindAssertion builds the parent', () => {
		const node = ir.lookaroundAssertion.lookbehindAssertion({
			content: '=',
			pattern: {
				$type: TSKindId.Pattern,
				$text: 'test',
				$source: 2,
				$named: true,
				_content: {
					$type: TSKindId.Alternation,
					$text: 'test',
					$source: 2,
					$named: true,
					_term: [
						{
							$type: TSKindId.Term,
							$text: 'test',
							$source: 2,
							$named: true,
							_term_group: [
								{
									$type: TSKindId.TermGroup,
									$text: 'test',
									$source: 2,
									$named: true,
									_content: { $type: TSKindId.StartAssertion, $text: '^', $source: 2, $named: true } as any
								} as any
							]
						} as any
					]
				} as any
			} as any
		});
		expect(node.$type).toBe(TSKindId.LookaroundAssertion);
		expect((node as any).content()?.$type).toBe(TSKindId.LookbehindAssertion);
		expect(node.$render!().length).toBeGreaterThan(0);
	});
	it('lookaheadAssertion.eq builds the parent', () => {
		const node = ir.lookaroundAssertion.lookaheadAssertion.eq({
			pattern: {
				$type: TSKindId.Pattern,
				$text: 'test',
				$source: 2,
				$named: true,
				_content: {
					$type: TSKindId.Alternation,
					$text: 'test',
					$source: 2,
					$named: true,
					_term: [
						{
							$type: TSKindId.Term,
							$text: 'test',
							$source: 2,
							$named: true,
							_term_group: [
								{
									$type: TSKindId.TermGroup,
									$text: 'test',
									$source: 2,
									$named: true,
									_content: { $type: TSKindId.StartAssertion, $text: '^', $source: 2, $named: true } as any
								} as any
							]
						} as any
					]
				} as any
			} as any
		});
		expect(node.$type).toBe(TSKindId.LookaroundAssertion);
		expect((node as any).content()?.$type).toBe(TSKindId.LookaheadAssertion);
		expect(node.$render!().length).toBeGreaterThan(0);
	});
	it('lookaheadAssertion.bang builds the parent', () => {
		const node = ir.lookaroundAssertion.lookaheadAssertion.bang({
			pattern: {
				$type: TSKindId.Pattern,
				$text: 'test',
				$source: 2,
				$named: true,
				_content: {
					$type: TSKindId.Alternation,
					$text: 'test',
					$source: 2,
					$named: true,
					_term: [
						{
							$type: TSKindId.Term,
							$text: 'test',
							$source: 2,
							$named: true,
							_term_group: [
								{
									$type: TSKindId.TermGroup,
									$text: 'test',
									$source: 2,
									$named: true,
									_content: { $type: TSKindId.StartAssertion, $text: '^', $source: 2, $named: true } as any
								} as any
							]
						} as any
					]
				} as any
			} as any
		});
		expect(node.$type).toBe(TSKindId.LookaroundAssertion);
		expect((node as any).content()?.$type).toBe(TSKindId.LookaheadAssertion);
		expect(node.$render!().length).toBeGreaterThan(0);
	});
	it('lookbehindAssertion.eq builds the parent', () => {
		const node = ir.lookaroundAssertion.lookbehindAssertion.eq({
			pattern: {
				$type: TSKindId.Pattern,
				$text: 'test',
				$source: 2,
				$named: true,
				_content: {
					$type: TSKindId.Alternation,
					$text: 'test',
					$source: 2,
					$named: true,
					_term: [
						{
							$type: TSKindId.Term,
							$text: 'test',
							$source: 2,
							$named: true,
							_term_group: [
								{
									$type: TSKindId.TermGroup,
									$text: 'test',
									$source: 2,
									$named: true,
									_content: { $type: TSKindId.StartAssertion, $text: '^', $source: 2, $named: true } as any
								} as any
							]
						} as any
					]
				} as any
			} as any
		});
		expect(node.$type).toBe(TSKindId.LookaroundAssertion);
		expect((node as any).content()?.$type).toBe(TSKindId.LookbehindAssertion);
		expect(node.$render!().length).toBeGreaterThan(0);
	});
	it('lookbehindAssertion.bang builds the parent', () => {
		const node = ir.lookaroundAssertion.lookbehindAssertion.bang({
			pattern: {
				$type: TSKindId.Pattern,
				$text: 'test',
				$source: 2,
				$named: true,
				_content: {
					$type: TSKindId.Alternation,
					$text: 'test',
					$source: 2,
					$named: true,
					_term: [
						{
							$type: TSKindId.Term,
							$text: 'test',
							$source: 2,
							$named: true,
							_term_group: [
								{
									$type: TSKindId.TermGroup,
									$text: 'test',
									$source: 2,
									$named: true,
									_content: { $type: TSKindId.StartAssertion, $text: '^', $source: 2, $named: true } as any
								} as any
							]
						} as any
					]
				} as any
			} as any
		});
		expect(node.$type).toBe(TSKindId.LookaroundAssertion);
		expect((node as any).content()?.$type).toBe(TSKindId.LookbehindAssertion);
		expect(node.$render!().length).toBeGreaterThan(0);
	});
});

describe('pattern_character', () => {
	it('factory produces correct type', () => {
		const node = ir.patternCharacter('a');
		expect(node.$type).toBe(TSKindId.PatternCharacter);
		expect(node.$source).toBe(2);
		expect(node.$text).toBe('a');
	});
});

describe('character_class', () => {
	it('factory produces correct type', () => {
		const node = ir.characterClass();
		expect(node.$type).toBe(TSKindId.CharacterClass);
		expect(node.$source).toBe(2);
	});
	it('render does not throw on minimal config', () => {
		const node = ir.characterClass();
		expect(() => node.$render!()).not.toThrow();
	});
});

describe('posix_character_class', () => {
	it('factory produces correct type', () => {
		const node = ir.posixCharacterClass({
			$type: TSKindId.PosixClassName,
			$text: 'test',
			$source: 2,
			$named: true
		} as any);
		expect(node.$type).toBe(TSKindId.PosixCharacterClass);
		expect(node.$source).toBe(2);
	});
	it('render produces non-empty string', () => {
		const node = ir.posixCharacterClass({
			$type: TSKindId.PosixClassName,
			$text: 'test',
			$source: 2,
			$named: true
		} as any);
		const rendered = node.$render!();
		expect(rendered.length).toBeGreaterThan(0);
		expect(rendered).toContain('test');
	});
});

describe('posix_class_name', () => {
	it('factory produces correct type', () => {
		const node = ir.posixClassName('test');
		expect(node.$type).toBe(TSKindId.PosixClassName);
		expect(node.$source).toBe(2);
		expect(node.$text).toBe('test');
	});
});

describe('class_range', () => {
	it('factory produces correct type', () => {
		const node = ir.classRange({
			start: { $type: TSKindId.ClassCharacter, $text: 'test', $source: 2, $named: true } as any,
			end: { $type: TSKindId.ClassCharacter, $text: 'test', $source: 2, $named: true } as any
		});
		expect(node.$type).toBe(TSKindId.ClassRange);
		expect(node.$source).toBe(2);
	});
	it('render produces non-empty string', () => {
		const node = ir.classRange({
			start: { $type: TSKindId.ClassCharacter, $text: 'test', $source: 2, $named: true } as any,
			end: { $type: TSKindId.ClassCharacter, $text: 'test', $source: 2, $named: true } as any
		});
		const rendered = node.$render!();
		expect(rendered.length).toBeGreaterThan(0);
	});
});

describe('class_character', () => {
	it('factory produces correct type', () => {
		const node = ir.classCharacter('a');
		expect(node.$type).toBe(TSKindId.ClassCharacter);
		expect(node.$source).toBe(2);
		expect(node.$text).toBe('a');
	});
});

describe('anonymous_capturing_group', () => {
	it('factory produces correct type', () => {
		const node = ir.anonymousCapturingGroup({
			$type: TSKindId.Pattern,
			$text: 'test',
			$source: 2,
			$named: true,
			_content: {
				$type: TSKindId.Alternation,
				$text: 'test',
				$source: 2,
				$named: true,
				_term: [
					{
						$type: TSKindId.Term,
						$text: 'test',
						$source: 2,
						$named: true,
						_term_group: [
							{
								$type: TSKindId.TermGroup,
								$text: 'test',
								$source: 2,
								$named: true,
								_content: { $type: TSKindId.StartAssertion, $text: '^', $source: 2, $named: true } as any
							} as any
						]
					} as any
				]
			} as any
		} as any);
		expect(node.$type).toBe(TSKindId.AnonymousCapturingGroup);
		expect(node.$source).toBe(2);
	});
	it('render produces non-empty string', () => {
		const node = ir.anonymousCapturingGroup({
			$type: TSKindId.Pattern,
			$text: 'test',
			$source: 2,
			$named: true,
			_content: {
				$type: TSKindId.Alternation,
				$text: 'test',
				$source: 2,
				$named: true,
				_term: [
					{
						$type: TSKindId.Term,
						$text: 'test',
						$source: 2,
						$named: true,
						_term_group: [
							{
								$type: TSKindId.TermGroup,
								$text: 'test',
								$source: 2,
								$named: true,
								_content: { $type: TSKindId.StartAssertion, $text: '^', $source: 2, $named: true } as any
							} as any
						]
					} as any
				]
			} as any
		} as any);
		const rendered = node.$render!();
		expect(rendered.length).toBeGreaterThan(0);
		expect(rendered).toContain('^');
	});
});

describe('named_capturing_group', () => {
	it('factory produces correct type', () => {
		const node = ir.namedCapturingGroup({
			content: '(?<',
			groupName: { $type: TSKindId.GroupName, $text: 'test', $source: 2, $named: true } as any,
			pattern: {
				$type: TSKindId.Pattern,
				$text: 'test',
				$source: 2,
				$named: true,
				_content: {
					$type: TSKindId.Alternation,
					$text: 'test',
					$source: 2,
					$named: true,
					_term: [
						{
							$type: TSKindId.Term,
							$text: 'test',
							$source: 2,
							$named: true,
							_term_group: [
								{
									$type: TSKindId.TermGroup,
									$text: 'test',
									$source: 2,
									$named: true,
									_content: { $type: TSKindId.StartAssertion, $text: '^', $source: 2, $named: true } as any
								} as any
							]
						} as any
					]
				} as any
			} as any
		});
		expect(node.$type).toBe(TSKindId.NamedCapturingGroup);
		expect(node.$source).toBe(2);
	});
	it('render produces non-empty string', () => {
		const node = ir.namedCapturingGroup({
			content: '(?<',
			groupName: { $type: TSKindId.GroupName, $text: 'test', $source: 2, $named: true } as any,
			pattern: {
				$type: TSKindId.Pattern,
				$text: 'test',
				$source: 2,
				$named: true,
				_content: {
					$type: TSKindId.Alternation,
					$text: 'test',
					$source: 2,
					$named: true,
					_term: [
						{
							$type: TSKindId.Term,
							$text: 'test',
							$source: 2,
							$named: true,
							_term_group: [
								{
									$type: TSKindId.TermGroup,
									$text: 'test',
									$source: 2,
									$named: true,
									_content: { $type: TSKindId.StartAssertion, $text: '^', $source: 2, $named: true } as any
								} as any
							]
						} as any
					]
				} as any
			} as any
		});
		const rendered = node.$render!();
		expect(rendered.length).toBeGreaterThan(0);
	});
});

describe('named_capturing_group sub-factories', () => {
	it('lparenQmarkLt builds the parent', () => {
		const node = ir.namedCapturingGroup.lparenQmarkLt({
			groupName: { $type: TSKindId.GroupName, $text: 'test', $source: 2, $named: true } as any,
			pattern: {
				$type: TSKindId.Pattern,
				$text: 'test',
				$source: 2,
				$named: true,
				_content: {
					$type: TSKindId.Alternation,
					$text: 'test',
					$source: 2,
					$named: true,
					_term: [
						{
							$type: TSKindId.Term,
							$text: 'test',
							$source: 2,
							$named: true,
							_term_group: [
								{
									$type: TSKindId.TermGroup,
									$text: 'test',
									$source: 2,
									$named: true,
									_content: { $type: TSKindId.StartAssertion, $text: '^', $source: 2, $named: true } as any
								} as any
							]
						} as any
					]
				} as any
			} as any
		});
		expect(node.$type).toBe(TSKindId.NamedCapturingGroup);
		const seated = (node as any).content();
		expect(seated?.$text ?? seated).toBe(TSKindId.LparenQmarkLt);
		expect(node.$render!().length).toBeGreaterThan(0);
	});
	it('lparenQmarkpLt builds the parent', () => {
		const node = ir.namedCapturingGroup.lparenQmarkpLt({
			groupName: { $type: TSKindId.GroupName, $text: 'test', $source: 2, $named: true } as any,
			pattern: {
				$type: TSKindId.Pattern,
				$text: 'test',
				$source: 2,
				$named: true,
				_content: {
					$type: TSKindId.Alternation,
					$text: 'test',
					$source: 2,
					$named: true,
					_term: [
						{
							$type: TSKindId.Term,
							$text: 'test',
							$source: 2,
							$named: true,
							_term_group: [
								{
									$type: TSKindId.TermGroup,
									$text: 'test',
									$source: 2,
									$named: true,
									_content: { $type: TSKindId.StartAssertion, $text: '^', $source: 2, $named: true } as any
								} as any
							]
						} as any
					]
				} as any
			} as any
		});
		expect(node.$type).toBe(TSKindId.NamedCapturingGroup);
		const seated = (node as any).content();
		expect(seated?.$text ?? seated).toBe(TSKindId.LparenQmarkpLt);
		expect(node.$render!().length).toBeGreaterThan(0);
	});
});

describe('non_capturing_group', () => {
	it('factory produces correct type', () => {
		const node = ir.nonCapturingGroup({
			$type: TSKindId.Pattern,
			$text: 'test',
			$source: 2,
			$named: true,
			_content: {
				$type: TSKindId.Alternation,
				$text: 'test',
				$source: 2,
				$named: true,
				_term: [
					{
						$type: TSKindId.Term,
						$text: 'test',
						$source: 2,
						$named: true,
						_term_group: [
							{
								$type: TSKindId.TermGroup,
								$text: 'test',
								$source: 2,
								$named: true,
								_content: { $type: TSKindId.StartAssertion, $text: '^', $source: 2, $named: true } as any
							} as any
						]
					} as any
				]
			} as any
		} as any);
		expect(node.$type).toBe(TSKindId.NonCapturingGroup);
		expect(node.$source).toBe(2);
	});
	it('render produces non-empty string', () => {
		const node = ir.nonCapturingGroup({
			$type: TSKindId.Pattern,
			$text: 'test',
			$source: 2,
			$named: true,
			_content: {
				$type: TSKindId.Alternation,
				$text: 'test',
				$source: 2,
				$named: true,
				_term: [
					{
						$type: TSKindId.Term,
						$text: 'test',
						$source: 2,
						$named: true,
						_term_group: [
							{
								$type: TSKindId.TermGroup,
								$text: 'test',
								$source: 2,
								$named: true,
								_content: { $type: TSKindId.StartAssertion, $text: '^', $source: 2, $named: true } as any
							} as any
						]
					} as any
				]
			} as any
		} as any);
		const rendered = node.$render!();
		expect(rendered.length).toBeGreaterThan(0);
		expect(rendered).toContain('^');
	});
});

describe('flags', () => {
	it('factory produces correct type', () => {
		const node = ir.flags('test');
		expect(node.$type).toBe(TSKindId.Flags);
		expect(node.$source).toBe(2);
		expect(node.$text).toBe('test');
	});
});

describe('zero_or_more', () => {
	it('factory produces correct type', () => {
		const node = ir.zeroOrMore('*');
		expect(node.$type).toBe(TSKindId.ZeroOrMore);
		expect(node.$source).toBe(2);
		expect(node.$text).toBe('*');
	});
});

describe('one_or_more', () => {
	it('factory produces correct type', () => {
		const node = ir.oneOrMore('+');
		expect(node.$type).toBe(TSKindId.OneOrMore);
		expect(node.$source).toBe(2);
		expect(node.$text).toBe('+');
	});
});

describe('optional', () => {
	it('factory produces correct type', () => {
		const node = ir.optional('?');
		expect(node.$type).toBe(TSKindId.Optional);
		expect(node.$source).toBe(2);
		expect(node.$text).toBe('?');
	});
});

describe('count_quantifier', () => {
	it('factory produces correct type', () => {
		const node = ir.countQuantifier({ $type: TSKindId.DecimalDigits, $text: 'test', $source: 2, $named: true } as any);
		expect(node.$type).toBe(TSKindId.CountQuantifier);
		expect(node.$source).toBe(2);
	});
	it('render produces non-empty string', () => {
		const node = ir.countQuantifier({ $type: TSKindId.DecimalDigits, $text: 'test', $source: 2, $named: true } as any);
		const rendered = node.$render!();
		expect(rendered.length).toBeGreaterThan(0);
		expect(rendered).toContain('test');
	});
});

describe('count_quantifier sub-factories', () => {
	it('arm builds the parent', () => {
		const node = ir.countQuantifier.arm({
			decimalDigits: { $type: TSKindId.DecimalDigits, $text: 'test', $source: 2, $named: true } as any
		});
		expect(node.$type).toBe(TSKindId.CountQuantifier);
		expect((node as any).content()?.$type).toBe(TSKindId.CountQuantifierArm);
		expect(node.$render!().length).toBeGreaterThan(0);
	});
});

describe('backreference_escape', () => {
	it('factory produces correct type', () => {
		const node = ir.backreferenceEscape({ $type: TSKindId.GroupName, $text: 'test', $source: 2, $named: true } as any);
		expect(node.$type).toBe(TSKindId.BackreferenceEscape);
		expect(node.$source).toBe(2);
	});
	it('render produces non-empty string', () => {
		const node = ir.backreferenceEscape({ $type: TSKindId.GroupName, $text: 'test', $source: 2, $named: true } as any);
		const rendered = node.$render!();
		expect(rendered.length).toBeGreaterThan(0);
		expect(rendered).toContain('test');
	});
});

describe('named_group_backreference', () => {
	it('factory produces correct type', () => {
		const node = ir.namedGroupBackreference({
			$type: TSKindId.GroupName,
			$text: 'test',
			$source: 2,
			$named: true
		} as any);
		expect(node.$type).toBe(TSKindId.NamedGroupBackreference);
		expect(node.$source).toBe(2);
	});
	it('render produces non-empty string', () => {
		const node = ir.namedGroupBackreference({
			$type: TSKindId.GroupName,
			$text: 'test',
			$source: 2,
			$named: true
		} as any);
		const rendered = node.$render!();
		expect(rendered.length).toBeGreaterThan(0);
		expect(rendered).toContain('test');
	});
});

describe('decimal_escape', () => {
	it('factory produces correct type', () => {
		const node = ir.decimalEscape('\\10');
		expect(node.$type).toBe(TSKindId.DecimalEscape);
		expect(node.$source).toBe(2);
		expect(node.$text).toBe('\\10');
	});
});

describe('character_class_escape', () => {
	it('factory produces correct type', () => {
		const node = ir.characterClassEscape({
			$type: TSKindId.UnicodeCharacterEscape,
			$text: 'test',
			$source: 2,
			$named: true
		} as any);
		expect(node.$type).toBe(TSKindId.CharacterClassEscape);
		expect(node.$source).toBe(2);
	});
	it('render produces non-empty string', () => {
		const node = ir.characterClassEscape({
			$type: TSKindId.UnicodeCharacterEscape,
			$text: 'test',
			$source: 2,
			$named: true
		} as any);
		const rendered = node.$render!();
		expect(rendered.length).toBeGreaterThan(0);
		expect(rendered).toContain('test');
	});
});

describe('character_class_escape sub-factories', () => {
	it('arm builds the parent', () => {
		const node = ir.characterClassEscape.arm({
			content: 'test' as any,
			unicodePropertyValueExpression: {
				$type: TSKindId.UnicodePropertyValueExpression,
				$text: 'test',
				$source: 2,
				$named: true,
				_unicode_property: { $type: TSKindId.UnicodeProperty, $text: 'test', $source: 2, $named: true } as any
			} as any
		});
		expect(node.$type).toBe(TSKindId.CharacterClassEscape);
		expect((node as any).content()?.$type).toBe(TSKindId.CharacterClassEscapeArm);
		expect(node.$render!().length).toBeGreaterThan(0);
	});
	it('unicodeCharacterEscape builds the parent', () => {
		const node = ir.characterClassEscape.unicodeCharacterEscape('\\u0000');
		expect(node.$type).toBe(TSKindId.CharacterClassEscape);
		expect((node as any).content()?.$type).toBe(TSKindId.UnicodeCharacterEscape);
		expect(node.$render!().length).toBeGreaterThan(0);
	});
});

describe('unicode_character_escape', () => {
	it('factory produces correct type', () => {
		const node = ir.unicodeCharacterEscape('\\u0000');
		expect(node.$type).toBe(TSKindId.UnicodeCharacterEscape);
		expect(node.$source).toBe(2);
		expect(node.$text).toBe('\\u0000');
	});
});

describe('unicode_property_value_expression', () => {
	it('factory produces correct type', () => {
		const node = ir.unicodePropertyValueExpression({
			unicodeProperty: { $type: TSKindId.UnicodeProperty, $text: 'test', $source: 2, $named: true } as any
		});
		expect(node.$type).toBe(TSKindId.UnicodePropertyValueExpression);
		expect(node.$source).toBe(2);
	});
	it('render produces non-empty string', () => {
		const node = ir.unicodePropertyValueExpression({
			unicodeProperty: { $type: TSKindId.UnicodeProperty, $text: 'test', $source: 2, $named: true } as any
		});
		const rendered = node.$render!();
		expect(rendered.length).toBeGreaterThan(0);
	});
});

describe('unicode_property', () => {
	it('factory produces correct type', () => {
		const node = ir.unicodeProperty('test');
		expect(node.$type).toBe(TSKindId.UnicodeProperty);
		expect(node.$source).toBe(2);
		expect(node.$text).toBe('test');
	});
});

describe('control_escape', () => {
	it('factory produces correct type', () => {
		const node = ir.controlEscape('\\n');
		expect(node.$type).toBe(TSKindId.ControlEscape);
		expect(node.$source).toBe(2);
		expect(node.$text).toBe('\\n');
	});
});

describe('control_letter_escape', () => {
	it('factory produces correct type', () => {
		const node = ir.controlLetterEscape('\\ca');
		expect(node.$type).toBe(TSKindId.ControlLetterEscape);
		expect(node.$source).toBe(2);
		expect(node.$text).toBe('\\ca');
	});
});

describe('identity_escape', () => {
	it('factory produces correct type', () => {
		const node = ir.identityEscape('a');
		expect(node.$type).toBe(TSKindId.IdentityEscape);
		expect(node.$source).toBe(2);
	});
	it('render produces non-empty string', () => {
		const node = ir.identityEscape('a');
		const rendered = node.$render!();
		expect(rendered.length).toBeGreaterThan(0);
	});
});

describe('group_name', () => {
	it('factory produces correct type', () => {
		const node = ir.groupName('test');
		expect(node.$type).toBe(TSKindId.GroupName);
		expect(node.$source).toBe(2);
		expect(node.$text).toBe('test');
	});
});

describe('decimal_digits', () => {
	it('factory produces correct type', () => {
		const node = ir.decimalDigits('1');
		expect(node.$type).toBe(TSKindId.DecimalDigits);
		expect(node.$source).toBe(2);
		expect(node.$text).toBe('1');
	});
});

describe('term_group', () => {
	it('factory produces correct type', () => {
		const node = ir.termGroup({
			content: { $type: TSKindId.StartAssertion, $text: '^', $source: 2, $named: true } as any
		});
		expect(node.$type).toBe(TSKindId.TermGroup);
		expect(node.$source).toBe(2);
	});
	it('render produces non-empty string', () => {
		const node = ir.termGroup({
			content: { $type: TSKindId.StartAssertion, $text: '^', $source: 2, $named: true } as any
		});
		const rendered = node.$render!();
		expect(rendered.length).toBeGreaterThan(0);
	});
});

describe('term_group sub-factories', () => {
	it('startAssertion builds the parent', () => {
		const node = ir.termGroup.startAssertion({});
		expect(node.$type).toBe(TSKindId.TermGroup);
		expect((node as any).content()).toBe(TSKindId.StartAssertion);
		expect(node.$render!().length).toBeGreaterThan(0);
	});
	it('endAssertion builds the parent', () => {
		const node = ir.termGroup.endAssertion({});
		expect(node.$type).toBe(TSKindId.TermGroup);
		expect((node as any).content()).toBe(TSKindId.EndAssertion);
		expect(node.$render!().length).toBeGreaterThan(0);
	});
	it('boundaryAssertion builds the parent', () => {
		const node = ir.termGroup.boundaryAssertion({});
		expect(node.$type).toBe(TSKindId.TermGroup);
		expect((node as any).content()).toBe(TSKindId.BoundaryAssertion);
		expect(node.$render!().length).toBeGreaterThan(0);
	});
	it('nonBoundaryAssertion builds the parent', () => {
		const node = ir.termGroup.nonBoundaryAssertion({});
		expect(node.$type).toBe(TSKindId.TermGroup);
		expect((node as any).content()).toBe(TSKindId.NonBoundaryAssertion);
		expect(node.$render!().length).toBeGreaterThan(0);
	});
	it('lookaroundAssertion builds the parent', () => {
		const node = ir.termGroup.lookaroundAssertion({
			content: {
				$type: TSKindId.LookaheadAssertion,
				$text: 'test',
				$source: 2,
				$named: true,
				_content: TSKindId.Eq as never,
				_pattern: {
					$type: TSKindId.Pattern,
					$text: 'test',
					$source: 2,
					$named: true,
					_content: {
						$type: TSKindId.Alternation,
						$text: 'test',
						$source: 2,
						$named: true,
						_term: [
							{
								$type: TSKindId.Term,
								$text: 'test',
								$source: 2,
								$named: true,
								_term_group: [
									{
										$type: TSKindId.TermGroup,
										$text: 'test',
										$source: 2,
										$named: true,
										_content: { $type: TSKindId.StartAssertion, $text: '^', $source: 2, $named: true } as any
									} as any
								]
							} as any
						]
					} as any
				} as any
			} as any
		});
		expect(node.$type).toBe(TSKindId.TermGroup);
		expect((node as any).content()).toBeDefined();
		expect(node.$render!().length).toBeGreaterThan(0);
	});
	it('patternCharacter builds the parent', () => {
		const node = ir.termGroup.patternCharacter({ content: ['a'] });
		expect(node.$type).toBe(TSKindId.TermGroup);
		expect((node as any).content()).toBeDefined();
		expect(node.$render!().length).toBeGreaterThan(0);
	});
	it('characterClass builds the parent', () => {
		const node = ir.termGroup.characterClass({ content: [] });
		expect(node.$type).toBe(TSKindId.TermGroup);
		expect((node as any).content()).toBeDefined();
		expect(node.$render!().length).toBeGreaterThan(0);
	});
	it('posixCharacterClass builds the parent', () => {
		const node = ir.termGroup.posixCharacterClass({
			content: { $type: TSKindId.PosixClassName, $text: 'test', $source: 2, $named: true } as any
		});
		expect(node.$type).toBe(TSKindId.TermGroup);
		expect((node as any).content()).toBeDefined();
		expect(node.$render!().length).toBeGreaterThan(0);
	});
	it('anyCharacter builds the parent', () => {
		const node = ir.termGroup.anyCharacter({});
		expect(node.$type).toBe(TSKindId.TermGroup);
		expect((node as any).content()).toBe(TSKindId.AnyCharacter);
		expect(node.$render!().length).toBeGreaterThan(0);
	});
	it('decimalEscape builds the parent', () => {
		const node = ir.termGroup.decimalEscape({ content: ['\\10'] });
		expect(node.$type).toBe(TSKindId.TermGroup);
		expect((node as any).content()).toBeDefined();
		expect(node.$render!().length).toBeGreaterThan(0);
	});
	it('characterClassEscape builds the parent', () => {
		const node = ir.termGroup.characterClassEscape({
			content: { $type: TSKindId.UnicodeCharacterEscape, $text: 'test', $source: 2, $named: true } as any
		});
		expect(node.$type).toBe(TSKindId.TermGroup);
		expect((node as any).content()).toBeDefined();
		expect(node.$render!().length).toBeGreaterThan(0);
	});
	it('backreferenceEscape builds the parent', () => {
		const node = ir.termGroup.backreferenceEscape({
			content: { $type: TSKindId.GroupName, $text: 'test', $source: 2, $named: true } as any
		});
		expect(node.$type).toBe(TSKindId.TermGroup);
		expect((node as any).content()).toBeDefined();
		expect(node.$render!().length).toBeGreaterThan(0);
	});
	it('namedGroupBackreference builds the parent', () => {
		const node = ir.termGroup.namedGroupBackreference({
			content: { $type: TSKindId.GroupName, $text: 'test', $source: 2, $named: true } as any
		});
		expect(node.$type).toBe(TSKindId.TermGroup);
		expect((node as any).content()).toBeDefined();
		expect(node.$render!().length).toBeGreaterThan(0);
	});
	it('anonymousCapturingGroup builds the parent', () => {
		const node = ir.termGroup.anonymousCapturingGroup({
			content: {
				$type: TSKindId.Pattern,
				$text: 'test',
				$source: 2,
				$named: true,
				_content: {
					$type: TSKindId.Alternation,
					$text: 'test',
					$source: 2,
					$named: true,
					_term: [
						{
							$type: TSKindId.Term,
							$text: 'test',
							$source: 2,
							$named: true,
							_term_group: [
								{
									$type: TSKindId.TermGroup,
									$text: 'test',
									$source: 2,
									$named: true,
									_content: { $type: TSKindId.StartAssertion, $text: '^', $source: 2, $named: true } as any
								} as any
							]
						} as any
					]
				} as any
			} as any
		});
		expect(node.$type).toBe(TSKindId.TermGroup);
		expect((node as any).content()).toBeDefined();
		expect(node.$render!().length).toBeGreaterThan(0);
	});
	it('namedCapturingGroup builds the parent', () => {
		const node = ir.termGroup.namedCapturingGroup({
			content: '(?<',
			groupName: { $type: TSKindId.GroupName, $text: 'test', $source: 2, $named: true } as any,
			pattern: {
				$type: TSKindId.Pattern,
				$text: 'test',
				$source: 2,
				$named: true,
				_content: {
					$type: TSKindId.Alternation,
					$text: 'test',
					$source: 2,
					$named: true,
					_term: [
						{
							$type: TSKindId.Term,
							$text: 'test',
							$source: 2,
							$named: true,
							_term_group: [
								{
									$type: TSKindId.TermGroup,
									$text: 'test',
									$source: 2,
									$named: true,
									_content: { $type: TSKindId.StartAssertion, $text: '^', $source: 2, $named: true } as any
								} as any
							]
						} as any
					]
				} as any
			} as any
		});
		expect(node.$type).toBe(TSKindId.TermGroup);
		expect((node as any).content()).toBeDefined();
		expect(node.$render!().length).toBeGreaterThan(0);
	});
	it('nonCapturingGroup builds the parent', () => {
		const node = ir.termGroup.nonCapturingGroup({
			content: {
				$type: TSKindId.Pattern,
				$text: 'test',
				$source: 2,
				$named: true,
				_content: {
					$type: TSKindId.Alternation,
					$text: 'test',
					$source: 2,
					$named: true,
					_term: [
						{
							$type: TSKindId.Term,
							$text: 'test',
							$source: 2,
							$named: true,
							_term_group: [
								{
									$type: TSKindId.TermGroup,
									$text: 'test',
									$source: 2,
									$named: true,
									_content: { $type: TSKindId.StartAssertion, $text: '^', $source: 2, $named: true } as any
								} as any
							]
						} as any
					]
				} as any
			} as any
		});
		expect(node.$type).toBe(TSKindId.TermGroup);
		expect((node as any).content()).toBeDefined();
		expect(node.$render!().length).toBeGreaterThan(0);
	});
	it('enable builds the parent', () => {
		const node = ir.termGroup.enable({
			enabled: { $type: TSKindId.Flags, $text: 'test', $source: 2, $named: true } as any
		});
		expect(node.$type).toBe(TSKindId.TermGroup);
		expect((node as any).content()).toBeDefined();
		expect(node.$render!().length).toBeGreaterThan(0);
	});
	it('toggle builds the parent', () => {
		const node = ir.termGroup.toggle({
			enabled: { $type: TSKindId.Flags, $text: 'test', $source: 2, $named: true } as any,
			disabled: { $type: TSKindId.Flags, $text: 'test', $source: 2, $named: true } as any
		});
		expect(node.$type).toBe(TSKindId.TermGroup);
		expect((node as any).content()).toBeDefined();
		expect(node.$render!().length).toBeGreaterThan(0);
	});
	it('disable builds the parent', () => {
		const node = ir.termGroup.disable({
			disabled: { $type: TSKindId.Flags, $text: 'test', $source: 2, $named: true } as any
		});
		expect(node.$type).toBe(TSKindId.TermGroup);
		expect((node as any).content()).toBeDefined();
		expect(node.$render!().length).toBeGreaterThan(0);
	});
	it('lookaroundAssertion.lookaheadAssertion builds the parent', () => {
		const node = ir.termGroup.lookaroundAssertion.lookaheadAssertion({
			content: [
				{
					content: '=',
					pattern: {
						$type: TSKindId.Pattern,
						$text: 'test',
						$source: 2,
						$named: true,
						_content: {
							$type: TSKindId.Alternation,
							$text: 'test',
							$source: 2,
							$named: true,
							_term: [
								{
									$type: TSKindId.Term,
									$text: 'test',
									$source: 2,
									$named: true,
									_term_group: [
										{
											$type: TSKindId.TermGroup,
											$text: 'test',
											$source: 2,
											$named: true,
											_content: { $type: TSKindId.StartAssertion, $text: '^', $source: 2, $named: true } as any
										} as any
									]
								} as any
							]
						} as any
					} as any
				}
			]
		});
		expect(node.$type).toBe(TSKindId.TermGroup);
		expect((node as any).content()).toBeDefined();
		expect(node.$render!().length).toBeGreaterThan(0);
	});
	it('lookaroundAssertion.lookbehindAssertion builds the parent', () => {
		const node = ir.termGroup.lookaroundAssertion.lookbehindAssertion({
			content: [
				{
					content: '=',
					pattern: {
						$type: TSKindId.Pattern,
						$text: 'test',
						$source: 2,
						$named: true,
						_content: {
							$type: TSKindId.Alternation,
							$text: 'test',
							$source: 2,
							$named: true,
							_term: [
								{
									$type: TSKindId.Term,
									$text: 'test',
									$source: 2,
									$named: true,
									_term_group: [
										{
											$type: TSKindId.TermGroup,
											$text: 'test',
											$source: 2,
											$named: true,
											_content: { $type: TSKindId.StartAssertion, $text: '^', $source: 2, $named: true } as any
										} as any
									]
								} as any
							]
						} as any
					} as any
				}
			]
		});
		expect(node.$type).toBe(TSKindId.TermGroup);
		expect((node as any).content()).toBeDefined();
		expect(node.$render!().length).toBeGreaterThan(0);
	});
	it('lookaroundAssertion.lookaheadAssertion.eq builds the parent', () => {
		const node = ir.termGroup.lookaroundAssertion.lookaheadAssertion.eq({
			content: [
				{
					pattern: {
						$type: TSKindId.Pattern,
						$text: 'test',
						$source: 2,
						$named: true,
						_content: {
							$type: TSKindId.Alternation,
							$text: 'test',
							$source: 2,
							$named: true,
							_term: [
								{
									$type: TSKindId.Term,
									$text: 'test',
									$source: 2,
									$named: true,
									_term_group: [
										{
											$type: TSKindId.TermGroup,
											$text: 'test',
											$source: 2,
											$named: true,
											_content: { $type: TSKindId.StartAssertion, $text: '^', $source: 2, $named: true } as any
										} as any
									]
								} as any
							]
						} as any
					} as any
				}
			]
		});
		expect(node.$type).toBe(TSKindId.TermGroup);
		expect((node as any).content()).toBeDefined();
		expect(node.$render!().length).toBeGreaterThan(0);
	});
	it('lookaroundAssertion.lookaheadAssertion.bang builds the parent', () => {
		const node = ir.termGroup.lookaroundAssertion.lookaheadAssertion.bang({
			content: [
				{
					pattern: {
						$type: TSKindId.Pattern,
						$text: 'test',
						$source: 2,
						$named: true,
						_content: {
							$type: TSKindId.Alternation,
							$text: 'test',
							$source: 2,
							$named: true,
							_term: [
								{
									$type: TSKindId.Term,
									$text: 'test',
									$source: 2,
									$named: true,
									_term_group: [
										{
											$type: TSKindId.TermGroup,
											$text: 'test',
											$source: 2,
											$named: true,
											_content: { $type: TSKindId.StartAssertion, $text: '^', $source: 2, $named: true } as any
										} as any
									]
								} as any
							]
						} as any
					} as any
				}
			]
		});
		expect(node.$type).toBe(TSKindId.TermGroup);
		expect((node as any).content()).toBeDefined();
		expect(node.$render!().length).toBeGreaterThan(0);
	});
	it('lookaroundAssertion.lookbehindAssertion.eq builds the parent', () => {
		const node = ir.termGroup.lookaroundAssertion.lookbehindAssertion.eq({
			content: [
				{
					pattern: {
						$type: TSKindId.Pattern,
						$text: 'test',
						$source: 2,
						$named: true,
						_content: {
							$type: TSKindId.Alternation,
							$text: 'test',
							$source: 2,
							$named: true,
							_term: [
								{
									$type: TSKindId.Term,
									$text: 'test',
									$source: 2,
									$named: true,
									_term_group: [
										{
											$type: TSKindId.TermGroup,
											$text: 'test',
											$source: 2,
											$named: true,
											_content: { $type: TSKindId.StartAssertion, $text: '^', $source: 2, $named: true } as any
										} as any
									]
								} as any
							]
						} as any
					} as any
				}
			]
		});
		expect(node.$type).toBe(TSKindId.TermGroup);
		expect((node as any).content()).toBeDefined();
		expect(node.$render!().length).toBeGreaterThan(0);
	});
	it('lookaroundAssertion.lookbehindAssertion.bang builds the parent', () => {
		const node = ir.termGroup.lookaroundAssertion.lookbehindAssertion.bang({
			content: [
				{
					pattern: {
						$type: TSKindId.Pattern,
						$text: 'test',
						$source: 2,
						$named: true,
						_content: {
							$type: TSKindId.Alternation,
							$text: 'test',
							$source: 2,
							$named: true,
							_term: [
								{
									$type: TSKindId.Term,
									$text: 'test',
									$source: 2,
									$named: true,
									_term_group: [
										{
											$type: TSKindId.TermGroup,
											$text: 'test',
											$source: 2,
											$named: true,
											_content: { $type: TSKindId.StartAssertion, $text: '^', $source: 2, $named: true } as any
										} as any
									]
								} as any
							]
						} as any
					} as any
				}
			]
		});
		expect(node.$type).toBe(TSKindId.TermGroup);
		expect((node as any).content()).toBeDefined();
		expect(node.$render!().length).toBeGreaterThan(0);
	});
	it('characterClassEscape.arm builds the parent', () => {
		const node = ir.termGroup.characterClassEscape.arm({
			content: [
				{
					content: 'test' as any,
					unicodePropertyValueExpression: {
						$type: TSKindId.UnicodePropertyValueExpression,
						$text: 'test',
						$source: 2,
						$named: true,
						_unicode_property: { $type: TSKindId.UnicodeProperty, $text: 'test', $source: 2, $named: true } as any
					} as any
				}
			]
		});
		expect(node.$type).toBe(TSKindId.TermGroup);
		expect((node as any).content()).toBeDefined();
		expect(node.$render!().length).toBeGreaterThan(0);
	});
	it('characterClassEscape.unicodeCharacterEscape builds the parent', () => {
		const node = ir.termGroup.characterClassEscape.unicodeCharacterEscape({ content: ['\\u0000'] });
		expect(node.$type).toBe(TSKindId.TermGroup);
		expect((node as any).content()).toBeDefined();
		expect(node.$render!().length).toBeGreaterThan(0);
	});
	it('namedCapturingGroup.lparenQmarkLt builds the parent', () => {
		const node = ir.termGroup.namedCapturingGroup.lparenQmarkLt({
			content: [
				{
					groupName: { $type: TSKindId.GroupName, $text: 'test', $source: 2, $named: true } as any,
					pattern: {
						$type: TSKindId.Pattern,
						$text: 'test',
						$source: 2,
						$named: true,
						_content: {
							$type: TSKindId.Alternation,
							$text: 'test',
							$source: 2,
							$named: true,
							_term: [
								{
									$type: TSKindId.Term,
									$text: 'test',
									$source: 2,
									$named: true,
									_term_group: [
										{
											$type: TSKindId.TermGroup,
											$text: 'test',
											$source: 2,
											$named: true,
											_content: { $type: TSKindId.StartAssertion, $text: '^', $source: 2, $named: true } as any
										} as any
									]
								} as any
							]
						} as any
					} as any
				}
			]
		});
		expect(node.$type).toBe(TSKindId.TermGroup);
		expect((node as any).content()).toBeDefined();
		expect(node.$render!().length).toBeGreaterThan(0);
	});
	it('namedCapturingGroup.lparenQmarkpLt builds the parent', () => {
		const node = ir.termGroup.namedCapturingGroup.lparenQmarkpLt({
			content: [
				{
					groupName: { $type: TSKindId.GroupName, $text: 'test', $source: 2, $named: true } as any,
					pattern: {
						$type: TSKindId.Pattern,
						$text: 'test',
						$source: 2,
						$named: true,
						_content: {
							$type: TSKindId.Alternation,
							$text: 'test',
							$source: 2,
							$named: true,
							_term: [
								{
									$type: TSKindId.Term,
									$text: 'test',
									$source: 2,
									$named: true,
									_term_group: [
										{
											$type: TSKindId.TermGroup,
											$text: 'test',
											$source: 2,
											$named: true,
											_content: { $type: TSKindId.StartAssertion, $text: '^', $source: 2, $named: true } as any
										} as any
									]
								} as any
							]
						} as any
					} as any
				}
			]
		});
		expect(node.$type).toBe(TSKindId.TermGroup);
		expect((node as any).content()).toBeDefined();
		expect(node.$render!().length).toBeGreaterThan(0);
	});
});
