// @generated from packages/python/.sittir/src/parser.c — do not hand-edit.
// Per-kind numeric ID constants matching the TS-side `TSKindId` enum.
//
// IDs come from `enum ts_symbol_identifiers` in parser.c (KindID
// runtime migration design, 2026-04-30). Use these constants when
// matching on `KindId` values; the inner u16 is the parser.c-derived
// symbol id.

use ::sittir_core::types::KindId;

pub const IDENTIFIER: KindId = KindId(1);
pub const IMPORT: KindId = KindId(2);
pub const DOT: KindId = KindId(3);
pub const FROM: KindId = KindId(4);
pub const __FUTURE_U: KindId = KindId(5);
pub const COMMA: KindId = KindId(6);
pub const AS: KindId = KindId(7);
pub const STAR: KindId = KindId(8);
pub const GT_GT: KindId = KindId(9);
pub const ASSERT: KindId = KindId(10);
pub const COLON_EQ: KindId = KindId(11);
pub const RETURN: KindId = KindId(12);
pub const DEL: KindId = KindId(13);
pub const RAISE: KindId = KindId(14);
pub const PASS: KindId = KindId(15);
pub const BREAK: KindId = KindId(16);
pub const CONTINUE: KindId = KindId(17);
pub const IF: KindId = KindId(18);
pub const COLON: KindId = KindId(19);
pub const ELIF: KindId = KindId(20);
pub const ELSE: KindId = KindId(21);
pub const MATCH: KindId = KindId(22);
pub const CASE: KindId = KindId(23);
pub const FOR: KindId = KindId(24);
pub const IN: KindId = KindId(25);
pub const WHILE: KindId = KindId(26);
pub const TRY: KindId = KindId(27);
pub const EXCEPT: KindId = KindId(28);
pub const STAR2: KindId = KindId(29);
pub const FINALLY: KindId = KindId(30);
pub const WITH: KindId = KindId(31);
pub const DEF: KindId = KindId(32);
pub const LPAREN: KindId = KindId(33);
pub const RPAREN: KindId = KindId(34);
pub const STAR_STAR: KindId = KindId(35);
pub const GLOBAL: KindId = KindId(36);
pub const NONLOCAL: KindId = KindId(37);
pub const EXEC: KindId = KindId(38);
pub const ANON_TYPE: KindId = KindId(39);
pub const EQ: KindId = KindId(40);
pub const CLASS: KindId = KindId(41);
pub const LBRACK: KindId = KindId(42);
pub const RBRACK: KindId = KindId(43);
pub const AT: KindId = KindId(44);
pub const PIPE: KindId = KindId(45);
pub const LBRACE: KindId = KindId(46);
pub const RBRACE: KindId = KindId(47);
pub const _ANONYMOUS: KindId = KindId(48);
pub const PLUS: KindId = KindId(49);
pub const DASH: KindId = KindId(50);
pub const NOT: KindId = KindId(51);
pub const AND: KindId = KindId(52);
pub const OR: KindId = KindId(53);
pub const SLASH: KindId = KindId(54);
pub const PERCENT: KindId = KindId(55);
pub const SLASH_SLASH: KindId = KindId(56);
pub const AMP: KindId = KindId(57);
pub const CARET: KindId = KindId(58);
pub const LT_LT: KindId = KindId(59);
pub const TILDE: KindId = KindId(60);
pub const IS: KindId = KindId(61);
pub const ANON_LAMBDA: KindId = KindId(62);
pub const ANON_YIELD: KindId = KindId(63);
pub const ELLIPSIS: KindId = KindId(64);
pub const ESCAPE_SEQUENCE: KindId = KindId(65);
pub const BSLASH: KindId = KindId(66);
pub const FORMAT_SPECIFIER_TOKEN1: KindId = KindId(67);
pub const TYPE_CONVERSION: KindId = KindId(68);
pub const INTEGER: KindId = KindId(69);
pub const FLOAT: KindId = KindId(70);
pub const PRINT: KindId = KindId(71);
pub const ASYNC: KindId = KindId(72);
pub const ANON_AWAIT: KindId = KindId(73);
pub const TRUE: KindId = KindId(74);
pub const FALSE: KindId = KindId(75);
pub const NONE: KindId = KindId(76);
pub const COMMENT: KindId = KindId(77);
pub const LINE_CONTINUATION: KindId = KindId(78);
pub const SEMI: KindId = KindId(79);
pub const DASH_GT: KindId = KindId(80);
pub const PLUS_EQ: KindId = KindId(81);
pub const DASH_EQ: KindId = KindId(82);
pub const STAR_EQ: KindId = KindId(83);
pub const SLASH_EQ: KindId = KindId(84);
pub const AT_EQ: KindId = KindId(85);
pub const SLASH_SLASH_EQ: KindId = KindId(86);
pub const PERCENT_EQ: KindId = KindId(87);
pub const STAR_STAR_EQ: KindId = KindId(88);
pub const GT_GT_EQ: KindId = KindId(89);
pub const LT_LT_EQ: KindId = KindId(90);
pub const AMP_EQ: KindId = KindId(91);
pub const CARET_EQ: KindId = KindId(92);
pub const PIPE_EQ: KindId = KindId(93);
pub const LT: KindId = KindId(94);
pub const LT_EQ: KindId = KindId(95);
pub const EQ_EQ: KindId = KindId(96);
pub const BANG_EQ: KindId = KindId(97);
pub const GT_EQ: KindId = KindId(98);
pub const GT: KindId = KindId(99);
pub const LT_GT: KindId = KindId(100);
pub const _NEWLINE: KindId = KindId(101);
pub const _INDENT: KindId = KindId(102);
pub const _DEDENT: KindId = KindId(103);
pub const STRING_START: KindId = KindId(104);
pub const _STRING_CONTENT: KindId = KindId(105);
pub const ESCAPE_INTERPOLATION: KindId = KindId(106);
pub const STRING_END: KindId = KindId(107);
pub const MODULE: KindId = KindId(108);
pub const _STATEMENT: KindId = KindId(109);
pub const _SIMPLE_STATEMENTS: KindId = KindId(110);
pub const IMPORT_STATEMENT: KindId = KindId(111);
pub const IMPORT_PREFIX: KindId = KindId(112);
pub const RELATIVE_IMPORT: KindId = KindId(113);
pub const FUTURE_IMPORT_STATEMENT: KindId = KindId(114);
pub const IMPORT_FROM_STATEMENT: KindId = KindId(115);
pub const _IMPORT_LIST: KindId = KindId(116);
pub const ALIASED_IMPORT: KindId = KindId(117);
pub const WILDCARD_IMPORT: KindId = KindId(118);
pub const PRINT_STATEMENT: KindId = KindId(119);
pub const CHEVRON: KindId = KindId(120);
pub const ASSERT_STATEMENT: KindId = KindId(121);
pub const EXPRESSION_STATEMENT: KindId = KindId(122);
pub const NAMED_EXPRESSION: KindId = KindId(123);
pub const _NAMED_EXPRESSION_LHS: KindId = KindId(124);
pub const RETURN_STATEMENT: KindId = KindId(125);
pub const DELETE_STATEMENT: KindId = KindId(126);
pub const RAISE_STATEMENT: KindId = KindId(127);
pub const PASS_STATEMENT: KindId = KindId(128);
pub const BREAK_STATEMENT: KindId = KindId(129);
pub const CONTINUE_STATEMENT: KindId = KindId(130);
pub const IF_STATEMENT: KindId = KindId(131);
pub const ELIF_CLAUSE: KindId = KindId(132);
pub const ELSE_CLAUSE: KindId = KindId(133);
pub const MATCH_STATEMENT: KindId = KindId(134);
pub const _MATCH_BLOCK: KindId = KindId(135);
pub const CASE_CLAUSE: KindId = KindId(136);
pub const FOR_STATEMENT: KindId = KindId(137);
pub const WHILE_STATEMENT: KindId = KindId(138);
pub const TRY_STATEMENT: KindId = KindId(139);
pub const EXCEPT_CLAUSE: KindId = KindId(140);
pub const FINALLY_CLAUSE: KindId = KindId(141);
pub const WITH_STATEMENT: KindId = KindId(142);
pub const WITH_CLAUSE: KindId = KindId(143);
pub const WITH_ITEM: KindId = KindId(144);
pub const FUNCTION_DEFINITION: KindId = KindId(145);
pub const PARAMETERS: KindId = KindId(146);
pub const LAMBDA_PARAMETERS: KindId = KindId(147);
pub const LIST_SPLAT: KindId = KindId(148);
pub const DICTIONARY_SPLAT: KindId = KindId(149);
pub const GLOBAL_STATEMENT: KindId = KindId(150);
pub const NONLOCAL_STATEMENT: KindId = KindId(151);
pub const EXEC_STATEMENT: KindId = KindId(152);
pub const TYPE_ALIAS_STATEMENT: KindId = KindId(153);
pub const CLASS_DEFINITION: KindId = KindId(154);
pub const TYPE_PARAMETER: KindId = KindId(155);
pub const PARENTHESIZED_LIST_SPLAT: KindId = KindId(156);
pub const ARGUMENT_LIST: KindId = KindId(157);
pub const DECORATED_DEFINITION: KindId = KindId(158);
pub const DECORATOR: KindId = KindId(159);
pub const BLOCK: KindId = KindId(160);
pub const EXPRESSION_LIST: KindId = KindId(161);
pub const DOTTED_NAME: KindId = KindId(162);
pub const CASE_PATTERN: KindId = KindId(163);
pub const _SIMPLE_PATTERN: KindId = KindId(164);
pub const UNION_PATTERN: KindId = KindId(165);
pub const DICT_PATTERN: KindId = KindId(166);
pub const _KEY_VALUE_PATTERN: KindId = KindId(167);
pub const KEYWORD_PATTERN: KindId = KindId(168);
pub const SPLAT_PATTERN: KindId = KindId(169);
pub const CLASS_PATTERN: KindId = KindId(170);
pub const COMPLEX_PATTERN: KindId = KindId(171);
pub const _PARAMETERS: KindId = KindId(172);
pub const _PATTERNS: KindId = KindId(173);
pub const PARAMETER: KindId = KindId(174);
pub const PATTERN: KindId = KindId(175);
pub const TUPLE_PATTERN: KindId = KindId(176);
pub const LIST_PATTERN: KindId = KindId(177);
pub const DEFAULT_PARAMETER: KindId = KindId(178);
pub const TYPED_DEFAULT_PARAMETER: KindId = KindId(179);
pub const LIST_SPLAT_PATTERN: KindId = KindId(180);
pub const DICTIONARY_SPLAT_PATTERN: KindId = KindId(181);
pub const AS_PATTERN: KindId = KindId(182);
pub const _EXPRESSION_WITHIN_FOR_IN_CLAUSE: KindId = KindId(183);
pub const EXPRESSION: KindId = KindId(184);
pub const PRIMARY_EXPRESSION: KindId = KindId(185);
pub const NOT_OPERATOR: KindId = KindId(186);
pub const BOOLEAN_OPERATOR: KindId = KindId(187);
pub const BINARY_OPERATOR: KindId = KindId(188);
pub const UNARY_OPERATOR: KindId = KindId(189);
pub const _NOT_IN: KindId = KindId(190);
pub const _IS_NOT: KindId = KindId(191);
pub const COMPARISON_OPERATOR: KindId = KindId(192);
pub const LAMBDA: KindId = KindId(193);
pub const LAMBDA_WITHIN_FOR_IN_CLAUSE: KindId = KindId(194);
pub const ASSIGNMENT: KindId = KindId(195);
pub const AUGMENTED_ASSIGNMENT: KindId = KindId(196);
pub const PATTERN_LIST: KindId = KindId(197);
pub const _RIGHT_HAND_SIDE: KindId = KindId(198);
pub const YIELD: KindId = KindId(199);
pub const ATTRIBUTE: KindId = KindId(200);
pub const SUBSCRIPT: KindId = KindId(201);
pub const SLICE: KindId = KindId(202);
pub const CALL: KindId = KindId(203);
pub const TYPED_PARAMETER: KindId = KindId(204);
pub const TYPE: KindId = KindId(205);
pub const SPLAT_TYPE: KindId = KindId(206);
pub const GENERIC_TYPE: KindId = KindId(207);
pub const UNION_TYPE: KindId = KindId(208);
pub const CONSTRAINED_TYPE: KindId = KindId(209);
pub const MEMBER_TYPE: KindId = KindId(210);
pub const KEYWORD_ARGUMENT: KindId = KindId(211);
pub const LIST: KindId = KindId(212);
pub const SET: KindId = KindId(213);
pub const TUPLE: KindId = KindId(214);
pub const DICTIONARY: KindId = KindId(215);
pub const PAIR: KindId = KindId(216);
pub const LIST_COMPREHENSION: KindId = KindId(217);
pub const DICTIONARY_COMPREHENSION: KindId = KindId(218);
pub const SET_COMPREHENSION: KindId = KindId(219);
pub const GENERATOR_EXPRESSION: KindId = KindId(220);
pub const PARENTHESIZED_EXPRESSION: KindId = KindId(221);
pub const _COLLECTION_ELEMENTS: KindId = KindId(222);
pub const FOR_IN_CLAUSE: KindId = KindId(223);
pub const IF_CLAUSE: KindId = KindId(224);
pub const CONDITIONAL_EXPRESSION: KindId = KindId(225);
pub const CONCATENATED_STRING: KindId = KindId(226);
pub const STRING: KindId = KindId(227);
pub const STRING_CONTENT: KindId = KindId(228);
pub const INTERPOLATION: KindId = KindId(229);
pub const _F_EXPRESSION: KindId = KindId(230);
pub const _NOT_ESCAPE_SEQUENCE: KindId = KindId(231);
pub const FORMAT_SPECIFIER: KindId = KindId(232);
pub const AWAIT: KindId = KindId(233);
pub const POSITIONAL_SEPARATOR: KindId = KindId(234);
pub const KEYWORD_SEPARATOR: KindId = KindId(235);
pub const _KW_ASYNC_MARKER: KindId = KindId(236);
pub const _SIMPLE_STATEMENTS_ELEMENTS: KindId = KindId(237);
pub const _SUBJECTS: KindId = KindId(238);
pub const _CASE_PATTERNS: KindId = KindId(239);
pub const _WITH_CLAUSE_WITH_ITEMS: KindId = KindId(240);
pub const _TYPES: KindId = KindId(241);
pub const _ARGUMENT_LIST_ELEMENTS: KindId = KindId(242);
pub const _EXPRESSION_LIST_EXPRESSIONS: KindId = KindId(243);
pub const _LIST_PATTERN_CASE_PATTERNS: KindId = KindId(244);
pub const _DICT_PATTERN_ELEMENTS: KindId = KindId(245);
pub const _PATTERN_LIST_PATTERNS: KindId = KindId(246);
pub const _SUBSCRIPTS: KindId = KindId(247);
pub const _DICTIONARY_ELEMENTS: KindId = KindId(248);
pub const _FUTURE_IMPORT_STATEMENT_ARM: KindId = KindId(249);
pub const _EXCEPT_CLAUSE_ARM: KindId = KindId(250);
pub const _SLICE_GROUP: KindId = KindId(251);
pub const _AUGMENTED_ASSIGNMENT_OPERATOR: KindId = KindId(252);
pub const _EXCEPT_CLAUSE_AS: KindId = KindId(253);
pub const CASE_TUPLE_PATTERN: KindId = KindId(254);
pub const CASE_LIST_PATTERN: KindId = KindId(255);
pub const CASE_AS_PATTERN: KindId = KindId(256);
pub const COMPREHENSION_CLAUSES: KindId = KindId(257);
pub const _PRINT_ARGUMENTS: KindId = KindId(258);
pub const _PRINT_CHEVRON_ARGUMENTS: KindId = KindId(259);
pub const PRINT_STATEMENT_ARM1: KindId = KindId(260);
pub const PRINT_STATEMENT_ARM2: KindId = KindId(261);
pub const _WILDCARD_PATTERN: KindId = KindId(262);
pub const _ASSIGNMENT_EQ: KindId = KindId(263);
pub const _ASSIGNMENT_TYPE: KindId = KindId(264);
pub const _ASSIGNMENT_TYPED: KindId = KindId(265);
pub const _EXPRESSION_STATEMENT_TUPLE: KindId = KindId(266);
pub const _WITH_CLAUSE_BARE: KindId = KindId(267);
pub const _WITH_CLAUSE_PAREN: KindId = KindId(268);
pub const _MATCH_BLOCK_BLOCK: KindId = KindId(269);
pub const _SUITE_BLOCK_WITH_INDENT: KindId = KindId(270);
pub const _SIMPLE_PATTERN_NEGATIVE: KindId = KindId(271);
pub const _EXCEPT_CLAUSE_LIST: KindId = KindId(272);
pub const _COMPARISON_OPERATOR_COMPARATOR: KindId = KindId(273);
pub const _YIELD_FROM_CLAUSE: KindId = KindId(274);
pub const MODULE_REPEAT1: KindId = KindId(275);
pub const IMPORT_PREFIX_REPEAT1: KindId = KindId(276);
pub const _IMPORT_LIST_REPEAT1: KindId = KindId(277);
pub const ASSERT_STATEMENT_REPEAT1: KindId = KindId(278);
pub const IF_STATEMENT_REPEAT1: KindId = KindId(279);
pub const TRY_STATEMENT_REPEAT1: KindId = KindId(280);
pub const GLOBAL_STATEMENT_REPEAT1: KindId = KindId(281);
pub const DECORATED_DEFINITION_REPEAT1: KindId = KindId(282);
pub const DOTTED_NAME_REPEAT1: KindId = KindId(283);
pub const UNION_PATTERN_REPEAT1: KindId = KindId(284);
pub const _PARAMETERS_REPEAT1: KindId = KindId(285);
pub const _PATTERNS_REPEAT1: KindId = KindId(286);
pub const COMPARISON_OPERATOR_REPEAT1: KindId = KindId(287);
pub const _COLLECTION_ELEMENTS_REPEAT1: KindId = KindId(288);
pub const FOR_IN_CLAUSE_REPEAT1: KindId = KindId(289);
pub const CONCATENATED_STRING_REPEAT1: KindId = KindId(290);
pub const STRING_REPEAT1: KindId = KindId(291);
pub const STRING_CONTENT_REPEAT1: KindId = KindId(292);
pub const FORMAT_SPECIFIER_REPEAT1: KindId = KindId(293);
pub const _SIMPLE_STATEMENTS_ELEMENTS_REPEAT1: KindId = KindId(294);
pub const _SUBJECTS_REPEAT1: KindId = KindId(295);
pub const _CASE_PATTERNS_REPEAT1: KindId = KindId(296);
pub const _WITH_CLAUSE_WITH_ITEMS_REPEAT1: KindId = KindId(297);
pub const _EXEC_STATEMENT_OPTIONAL1_REPEAT1: KindId = KindId(298);
pub const _TYPES_REPEAT1: KindId = KindId(299);
pub const _ARGUMENT_LIST_ELEMENTS_REPEAT1: KindId = KindId(300);
pub const _EXPRESSION_LIST_EXPRESSIONS_REPEAT1: KindId = KindId(301);
pub const _DICT_PATTERN_ELEMENTS_REPEAT1: KindId = KindId(302);
pub const _PATTERN_LIST_PATTERNS_REPEAT1: KindId = KindId(303);
pub const _SUBSCRIPTS_REPEAT1: KindId = KindId(304);
pub const _DICTIONARY_ELEMENTS_REPEAT1: KindId = KindId(305);
pub const COMPREHENSION_CLAUSES_REPEAT1: KindId = KindId(306);
pub const _PRINT_ARGUMENTS_REPEAT1: KindId = KindId(307);
pub const _MATCH_BLOCK_BLOCK_REPEAT1: KindId = KindId(308);
pub const _EXCEPT_CLAUSE_LIST_REPEAT1: KindId = KindId(309);
pub const _AS_PATTERN_TARGET: KindId = KindId(310);
pub const _FORMAT_EXPRESSION: KindId = KindId(311);
pub const _NAMES: KindId = KindId(312);

/// Map a `KindId` back to its grammar kind string for diagnostics.
/// Returns `"<unknown>"` for ids not in this grammar's symbol table.
pub fn kind_name_from_id(id: KindId) -> &'static str {
    match id.0 {
        1 => "identifier", // "identifier"
        2 => "import", // "import"
        3 => ".", // "dot"
        4 => "from", // "from"
        5 => "__future__", // "__future__"
        6 => ",", // "comma"
        7 => "as", // "as"
        8 => "*", // "star"
        9 => ">>", // "gt_gt"
        10 => "assert", // "assert"
        11 => ":=", // "colon_eq"
        12 => "return", // "return"
        13 => "del", // "del"
        14 => "raise", // "raise"
        15 => "pass", // "pass"
        16 => "break", // "break"
        17 => "continue", // "continue"
        18 => "if", // "if"
        19 => ":", // "colon"
        20 => "elif", // "elif"
        21 => "else", // "else"
        22 => "match", // "match"
        23 => "case", // "case"
        24 => "for", // "for"
        25 => "in", // "in"
        26 => "while", // "while"
        27 => "try", // "try"
        28 => "except", // "except"
        29 => "*", // "star2"
        30 => "finally", // "finally"
        31 => "with", // "with"
        32 => "def", // "def"
        33 => "(", // "lparen"
        34 => ")", // "rparen"
        35 => "**", // "star_star"
        36 => "global", // "global"
        37 => "nonlocal", // "nonlocal"
        38 => "exec", // "exec"
        39 => "type", // "anon_type"
        40 => "=", // "eq"
        41 => "class", // "class"
        42 => "[", // "lbrack"
        43 => "]", // "rbrack"
        44 => "@", // "at"
        45 => "|", // "pipe"
        46 => "{", // "lbrace"
        47 => "}", // "rbrace"
        48 => "_", // "_"
        49 => "+", // "plus"
        50 => "-", // "dash"
        51 => "not", // "not"
        52 => "and", // "and"
        53 => "or", // "or"
        54 => "/", // "slash"
        55 => "%", // "percent"
        56 => "//", // "slash_slash"
        57 => "&", // "amp"
        58 => "^", // "caret"
        59 => "<<", // "lt_lt"
        60 => "~", // "tilde"
        61 => "is", // "is"
        62 => "lambda", // "anon_lambda"
        63 => "yield", // "anon_yield"
        64 => "ellipsis", // "ellipsis"
        65 => "escape_sequence", // "escape_sequence"
        66 => "\\", // "bslash"
        67 => "format_specifier_token1", // "format_specifier_token1"
        68 => "type_conversion", // "type_conversion"
        69 => "integer", // "integer"
        70 => "float", // "float"
        71 => "print", // "print"
        72 => "async", // "async"
        73 => "await", // "anon_await"
        74 => "true", // "true"
        75 => "false", // "false"
        76 => "none", // "none"
        77 => "comment", // "comment"
        78 => "line_continuation", // "line_continuation"
        79 => ";", // "semi"
        80 => "->", // "dash_gt"
        81 => "+=", // "plus_eq"
        82 => "-=", // "dash_eq"
        83 => "*=", // "star_eq"
        84 => "/=", // "slash_eq"
        85 => "@=", // "at_eq"
        86 => "//=", // "slash_slash_eq"
        87 => "%=", // "percent_eq"
        88 => "**=", // "star_star_eq"
        89 => ">>=", // "gt_gt_eq"
        90 => "<<=", // "lt_lt_eq"
        91 => "&=", // "amp_eq"
        92 => "^=", // "caret_eq"
        93 => "|=", // "pipe_eq"
        94 => "<", // "lt"
        95 => "<=", // "lt_eq"
        96 => "==", // "eq_eq"
        97 => "!=", // "bang_eq"
        98 => ">=", // "gt_eq"
        99 => ">", // "gt"
        100 => "<>", // "lt_gt"
        101 => "newline", // "_newline"
        102 => "_indent", // "_indent"
        103 => "_dedent", // "_dedent"
        104 => "string_start", // "string_start"
        105 => "string_fragment", // "_string_content"
        106 => "escape_interpolation", // "escape_interpolation"
        107 => "string_end", // "string_end"
        108 => "module", // "module"
        109 => "_statement", // "_statement"
        110 => "simple_statements", // "_simple_statements"
        111 => "import_statement", // "import_statement"
        112 => "import_prefix", // "import_prefix"
        113 => "relative_import", // "relative_import"
        114 => "future_import_statement", // "future_import_statement"
        115 => "import_from_statement", // "import_from_statement"
        116 => "import_list", // "_import_list"
        117 => "aliased_import", // "aliased_import"
        118 => "wildcard_import", // "wildcard_import"
        119 => "print_statement", // "print_statement"
        120 => "chevron", // "chevron"
        121 => "assert_statement", // "assert_statement"
        122 => "expression_statement", // "expression_statement"
        123 => "named_expression", // "named_expression"
        124 => "_named_expression_lhs", // "_named_expression_lhs"
        125 => "return_statement", // "return_statement"
        126 => "delete_statement", // "delete_statement"
        127 => "raise_statement", // "raise_statement"
        128 => "pass_statement", // "pass_statement"
        129 => "break_statement", // "break_statement"
        130 => "continue_statement", // "continue_statement"
        131 => "if_statement", // "if_statement"
        132 => "elif_clause", // "elif_clause"
        133 => "else_clause", // "else_clause"
        134 => "match_statement", // "match_statement"
        135 => "block", // "_match_block"
        136 => "case_clause", // "case_clause"
        137 => "for_statement", // "for_statement"
        138 => "while_statement", // "while_statement"
        139 => "try_statement", // "try_statement"
        140 => "except_clause", // "except_clause"
        141 => "finally_clause", // "finally_clause"
        142 => "with_statement", // "with_statement"
        143 => "with_clause", // "with_clause"
        144 => "with_item", // "with_item"
        145 => "function_definition", // "function_definition"
        146 => "parameters", // "parameters"
        147 => "lambda_parameters", // "lambda_parameters"
        148 => "list_splat", // "list_splat"
        149 => "dictionary_splat", // "dictionary_splat"
        150 => "global_statement", // "global_statement"
        151 => "nonlocal_statement", // "nonlocal_statement"
        152 => "exec_statement", // "exec_statement"
        153 => "type_alias_statement", // "type_alias_statement"
        154 => "class_definition", // "class_definition"
        155 => "type_parameter", // "type_parameter"
        156 => "parenthesized_list_splat", // "parenthesized_list_splat"
        157 => "argument_list", // "argument_list"
        158 => "decorated_definition", // "decorated_definition"
        159 => "decorator", // "decorator"
        160 => "block", // "block"
        161 => "expression_list", // "expression_list"
        162 => "dotted_name", // "dotted_name"
        163 => "case_pattern", // "case_pattern"
        164 => "_simple_pattern", // "_simple_pattern"
        165 => "union_pattern", // "union_pattern"
        166 => "dict_pattern", // "dict_pattern"
        167 => "key_value_pattern", // "_key_value_pattern"
        168 => "keyword_pattern", // "keyword_pattern"
        169 => "splat_pattern", // "splat_pattern"
        170 => "class_pattern", // "class_pattern"
        171 => "complex_pattern", // "complex_pattern"
        172 => "parameters_elements", // "_parameters"
        173 => "patterns", // "_patterns"
        174 => "parameter", // "parameter"
        175 => "pattern", // "pattern"
        176 => "tuple_pattern", // "tuple_pattern"
        177 => "list_pattern", // "list_pattern"
        178 => "default_parameter", // "default_parameter"
        179 => "typed_default_parameter", // "typed_default_parameter"
        180 => "list_splat_pattern", // "list_splat_pattern"
        181 => "dictionary_splat_pattern", // "dictionary_splat_pattern"
        182 => "as_pattern", // "as_pattern"
        183 => "_expression_within_for_in_clause", // "_expression_within_for_in_clause"
        184 => "expression", // "expression"
        185 => "primary_expression", // "primary_expression"
        186 => "not_operator", // "not_operator"
        187 => "boolean_operator", // "boolean_operator"
        188 => "binary_operator", // "binary_operator"
        189 => "unary_operator", // "unary_operator"
        190 => "not in", // "_not_in"
        191 => "is not", // "_is_not"
        192 => "comparison_operator", // "comparison_operator"
        193 => "lambda", // "lambda"
        194 => "lambda_within_for_in_clause", // "lambda_within_for_in_clause"
        195 => "assignment", // "assignment"
        196 => "augmented_assignment", // "augmented_assignment"
        197 => "pattern_list", // "pattern_list"
        198 => "_right_hand_side", // "_right_hand_side"
        199 => "yield", // "yield"
        200 => "attribute", // "attribute"
        201 => "subscript", // "subscript"
        202 => "slice", // "slice"
        203 => "call", // "call"
        204 => "typed_parameter", // "typed_parameter"
        205 => "type", // "type"
        206 => "splat_type", // "splat_type"
        207 => "generic_type", // "generic_type"
        208 => "union_type", // "union_type"
        209 => "constrained_type", // "constrained_type"
        210 => "member_type", // "member_type"
        211 => "keyword_argument", // "keyword_argument"
        212 => "list", // "list"
        213 => "set", // "set"
        214 => "tuple", // "tuple"
        215 => "dictionary", // "dictionary"
        216 => "pair", // "pair"
        217 => "list_comprehension", // "list_comprehension"
        218 => "dictionary_comprehension", // "dictionary_comprehension"
        219 => "set_comprehension", // "set_comprehension"
        220 => "generator_expression", // "generator_expression"
        221 => "parenthesized_expression", // "parenthesized_expression"
        222 => "collection_elements", // "_collection_elements"
        223 => "for_in_clause", // "for_in_clause"
        224 => "if_clause", // "if_clause"
        225 => "conditional_expression", // "conditional_expression"
        226 => "concatenated_string", // "concatenated_string"
        227 => "string", // "string"
        228 => "string_content", // "string_content"
        229 => "interpolation", // "interpolation"
        230 => "_f_expression", // "_f_expression"
        231 => "not_escape_sequence", // "_not_escape_sequence"
        232 => "format_specifier", // "format_specifier"
        233 => "await", // "await"
        234 => "positional_separator", // "positional_separator"
        235 => "keyword_separator", // "keyword_separator"
        236 => "_kw_async_marker", // "_kw_async_marker"
        237 => "simple_statements_elements", // "_simple_statements_elements"
        238 => "subjects", // "_subjects"
        239 => "case_patterns", // "_case_patterns"
        240 => "with_clause_with_items", // "_with_clause_with_items"
        241 => "types", // "_types"
        242 => "argument_list_elements", // "_argument_list_elements"
        243 => "expression_list_expressions", // "_expression_list_expressions"
        244 => "list_pattern_case_patterns", // "_list_pattern_case_patterns"
        245 => "dict_pattern_elements", // "_dict_pattern_elements"
        246 => "pattern_list_patterns", // "_pattern_list_patterns"
        247 => "subscripts", // "_subscripts"
        248 => "dictionary_elements", // "_dictionary_elements"
        249 => "future_import_statement_arm", // "_future_import_statement_arm"
        250 => "except_clause_arm", // "_except_clause_arm"
        251 => "slice_group", // "_slice_group"
        252 => "_augmented_assignment_operator", // "_augmented_assignment_operator"
        253 => "except_clause_as", // "_except_clause_as"
        254 => "case_tuple_pattern", // "case_tuple_pattern"
        255 => "case_list_pattern", // "case_list_pattern"
        256 => "case_as_pattern", // "case_as_pattern"
        257 => "comprehension_clauses", // "comprehension_clauses"
        258 => "print_arguments", // "_print_arguments"
        259 => "print_chevron_arguments", // "_print_chevron_arguments"
        260 => "print_statement_arm1", // "print_statement_arm1"
        261 => "print_statement_arm2", // "print_statement_arm2"
        262 => "wildcard_pattern", // "_wildcard_pattern"
        263 => "assignment_eq", // "_assignment_eq"
        264 => "assignment_type", // "_assignment_type"
        265 => "assignment_typed", // "_assignment_typed"
        266 => "expression_statement_tuple", // "_expression_statement_tuple"
        267 => "with_clause_bare", // "_with_clause_bare"
        268 => "with_clause_paren", // "_with_clause_paren"
        269 => "match_block_block", // "_match_block_block"
        270 => "suite_block_with_indent", // "_suite_block_with_indent"
        271 => "simple_pattern_negative", // "_simple_pattern_negative"
        272 => "except_clause_list", // "_except_clause_list"
        273 => "comparison_operator_comparator", // "_comparison_operator_comparator"
        274 => "yield_from_clause", // "_yield_from_clause"
        275 => "module_repeat1", // "module_repeat1"
        276 => "import_prefix_repeat1", // "import_prefix_repeat1"
        277 => "_import_list_repeat1", // "_import_list_repeat1"
        278 => "assert_statement_repeat1", // "assert_statement_repeat1"
        279 => "if_statement_repeat1", // "if_statement_repeat1"
        280 => "try_statement_repeat1", // "try_statement_repeat1"
        281 => "global_statement_repeat1", // "global_statement_repeat1"
        282 => "decorated_definition_repeat1", // "decorated_definition_repeat1"
        283 => "dotted_name_repeat1", // "dotted_name_repeat1"
        284 => "union_pattern_repeat1", // "union_pattern_repeat1"
        285 => "_parameters_repeat1", // "_parameters_repeat1"
        286 => "_patterns_repeat1", // "_patterns_repeat1"
        287 => "comparison_operator_repeat1", // "comparison_operator_repeat1"
        288 => "_collection_elements_repeat1", // "_collection_elements_repeat1"
        289 => "for_in_clause_repeat1", // "for_in_clause_repeat1"
        290 => "concatenated_string_repeat1", // "concatenated_string_repeat1"
        291 => "string_repeat1", // "string_repeat1"
        292 => "string_content_repeat1", // "string_content_repeat1"
        293 => "format_specifier_repeat1", // "format_specifier_repeat1"
        294 => "_simple_statements_elements_repeat1", // "_simple_statements_elements_repeat1"
        295 => "_subjects_repeat1", // "_subjects_repeat1"
        296 => "_case_patterns_repeat1", // "_case_patterns_repeat1"
        297 => "_with_clause_with_items_repeat1", // "_with_clause_with_items_repeat1"
        298 => "_exec_statement_optional1_repeat1", // "_exec_statement_optional1_repeat1"
        299 => "_types_repeat1", // "_types_repeat1"
        300 => "_argument_list_elements_repeat1", // "_argument_list_elements_repeat1"
        301 => "_expression_list_expressions_repeat1", // "_expression_list_expressions_repeat1"
        302 => "_dict_pattern_elements_repeat1", // "_dict_pattern_elements_repeat1"
        303 => "_pattern_list_patterns_repeat1", // "_pattern_list_patterns_repeat1"
        304 => "_subscripts_repeat1", // "_subscripts_repeat1"
        305 => "_dictionary_elements_repeat1", // "_dictionary_elements_repeat1"
        306 => "comprehension_clauses_repeat1", // "comprehension_clauses_repeat1"
        307 => "_print_arguments_repeat1", // "_print_arguments_repeat1"
        308 => "_match_block_block_repeat1", // "_match_block_block_repeat1"
        309 => "_except_clause_list_repeat1", // "_except_clause_list_repeat1"
        310 => "as_pattern_target", // "_as_pattern_target"
        311 => "format_expression", // "_format_expression"
        312 => "names", // "_names"
        _ => "<unknown>",
    }
}
