// Generated from bindings.scm and the vocabulary by `pnpm exec tsx packages/cli/src/cli.ts tool bindings-inventory --write`. Do not edit.
/// <reference path="../codegen/src/dsl/authoring-globals.d.ts" />
import { bindings, field, rename } from '../codegen/src/dsl/dsl-authoring.ts';

export default bindings({
	hash: "a08a26309870d778e7e8f40a2d7064779e380ce4e438b056fe15ed3b971585b6",
	patches: {
		_parameter_name: { "1/0": field("visibility"), "4": field("name") },
		abstract_class_declaration: { "1": field("abstract") },
		abstract_method_signature: { "0/0": field("visibility"), "1": field("abstract") },
		assignment_expression: { "0/0": field("disposable") },
		catch_clause: { "1/0": field("catch_clause_group") },
		decorator: { "1": field("content") },
		export_clause: { "1/0": field("export_specifiers") },
		for_in_statement: { "1/0": field("async") },
		generator_function: { "2": field("generator") },
		generator_function_declaration: { "2": field("generator") },
		interface_declaration: { "3/0": field("extends") },
		lexical_declaration: { "0": field("binding") },
		method_definition: { "0/0": field("visibility") },
		method_signature: { "0/0": field("visibility"), "5/0": field("accessor") },
		new_expression: { "1": field("function") },
		optional_parameter: { "1": field("optional") },
		property_signature: { "0/0": field("visibility") },
		public_field_definition: { "1/0/0/1/0": field("visibility"), "1/0/1/0": field("visibility") },
		try_statement: { "2/0": field("handlers") },
		tuple_type: { "1/0": field("tuple_type_members") },
		type_parameter: { "3": field("default") },
		variable_declarator_definite: { "1": field("definite") }
	},
	renames: [
		rename("program", "module"),
		rename("enum_assignment", "enum_member_declaration"),
		rename("method_definition", "method_declaration"),
		rename("method_signature", "signature_method_declaration"),
		rename("abstract_method_signature", "abstract_signature_method_declaration"),
		rename("property_signature", "signature_field_declaration"),
		rename("public_field_definition", "field_declaration"),
		rename("lexical_declaration", "variable_declaration"),
		rename("variable_declaration", "function_scoped_reassignable_variable_declaration"),
		rename("required_parameter", "parameter_declaration"),
		rename("optional_parameter", "optional_parameter_declaration"),
		rename("type_parameter", "type_parameter_declaration"),
		rename("ambient_declaration_module", "module_property_declaration"),
		rename("internal_module", "module_declaration"),
		rename("module", "external_module_declaration"),
		rename("class_static_block", "static_block_statement"),
		rename("function_signature", "signature_function_declaration"),
		rename("call_signature", "call_signature_declaration"),
		rename("construct_signature", "construct_signature_declaration"),
		rename("index_signature", "index_signature_declaration"),
		rename("statement_block", "block_statement"),
		rename("for_statement", "counted_loop_statement"),
		rename("for_in_statement", "for_loop_statement"),
		rename("while_statement", "while_loop_statement"),
		rename("do_statement", "do_while_loop_statement"),
		rename("with_statement", "scope_statement"),
		rename("switch_case", "case_clause"),
		rename("switch_default", "default_case_clause"),
		rename("extends_type_clause", "type_extends_clause"),
		rename("import_clause", "names_import_clause"),
		rename("import_require_clause", "require_import_clause"),
		rename("namespace_import", "namespace_import_clause"),
		rename("import_specifier", "specifier_import_clause"),
		rename("import_attribute", "attribute_import_clause"),
		rename("import_alias", "alias_import_clause"),
		rename("namespace_export", "namespace_export_clause"),
		rename("export_specifier", "specifier_export_clause"),
		rename("constraint", "constraint_clause"),
		rename("default_type", "default_clause"),
		rename("spread_element", "splat_element"),
		rename("pair", "pair_element"),
		rename("tuple_parameter", "member_tuple_element"),
		rename("optional_tuple_parameter", "optional_member_tuple_element"),
		rename("template_type", "substitution_template_element"),
		rename("call_expression_member", "member_call_expression"),
		rename("call_expression_template_call", "template_call_expression"),
		rename("new_expression", "new_call_expression"),
		rename("augmented_assignment_expression", "compound_assignment_expression"),
		rename("ternary_expression", "conditional_expression"),
		rename("arrow_function", "lambda_expression"),
		rename("generator_function", "generator_function_expression"),
		rename("yield_expression_delegate", "delegate_yield_expression"),
		rename("template_substitution", "interpolation_expression"),
		rename("object", "object_collection_expression"),
		rename("array", "list_collection_expression"),
		rename("as_expression", "as_cast_expression"),
		rename("satisfies_expression", "satisfies_cast_expression"),
		rename("non_null_expression", "non_null_cast_expression"),
		rename("type_assertion", "assertion_cast_expression"),
		rename("import", "import_call_expression"),
		rename("meta_property", "meta_expression"),
		rename("class", "class_expression"),
		rename("decorator_member_expression", "member_content_attribute"),
		rename("decorator_call_expression", "call_content_attribute"),
		rename("decorator_parenthesized_expression", "parenthesized_content_attribute"),
		rename("object_assignment_pattern", "assignment_object_pattern"),
		rename("pair_pattern", "pair_object_pattern"),
		rename("predefined_type", "primitive_type"),
		rename("constructor_type", "constructor_function_type"),
		rename("type_query", "query_type"),
		rename("type_predicate", "predicate_type"),
		rename("template_literal_type", "template_type"),
		rename("index_type_query", "index_query_type"),
		rename("asserts", "asserts_predicate_type"),
		rename("flow_maybe_type", "maybe_type"),
		rename("string", "string_literal"),
		rename("escape_sequence", "escape_string_literal"),
		rename("template_string", "template_literal"),
		rename("regex", "regex_literal"),
		rename("number", "number_literal"),
		rename("number_decimal", "integer_number_literal"),
		rename("number_hex", "hex_integer_number_literal"),
		rename("number_binary", "binary_integer_number_literal"),
		rename("number_octal", "octal_integer_number_literal"),
		rename("number_bigint_decimal", "big_integer_number_literal"),
		rename("number_bigint_hex", "hex_big_integer_number_literal"),
		rename("number_bigint_binary", "binary_big_integer_number_literal"),
		rename("number_bigint_octal", "octal_big_integer_number_literal"),
		rename("number_float_point", "float_number_literal"),
		rename("number_float_leading_point", "leading_point_float_number_literal"),
		rename("number_float_scientific", "scientific_float_number_literal"),
		rename("true", "true_boolean_literal"),
		rename("false", "false_boolean_literal"),
		rename("null", "null_literal"),
		rename("undefined", "undefined_null_literal"),
		rename("regex_pattern", "pattern_regex_literal"),
		rename("regex_flags", "flags_regex_literal"),
		rename("nested_type_identifier", "path_type"),
		rename("this", "self_identifier"),
		rename("super", "super_identifier"),
		rename("accessibility_modifier", "visibility_modifier"),
		rename("decorator", "decorator_attribute")
	],
	splits: []
});
