// Auto-generated by @sittir/codegen — DO NOT EDIT
//
// Derivation log for grammar 'typescript'.
//
// This file is a readable summary of every rule classification
// and field-name inference Link produced. It is NOT runnable —
// copy individual entries into your own overrides.ts to make
// the inference explicit in your grammar extension.
//
// Each entry is tagged [applied] (Link mutated the rule tree)
// or [held] (the `include` filter excluded it from the output).

// ---------------------------------------------------------------
// Summary
// ---------------------------------------------------------------
// Field inferences: 2  (2 applied, 0 held)
// Rule promotions:  33  (33 applied, 0 held)

// ---------------------------------------------------------------
// Rule promotions
// ---------------------------------------------------------------
//
// Link classified these rules based on their shape. The `promoted`
// source tag means "derived by Link" rather than "written by the
// grammar author". To make a promotion explicit, declare the rule
// with its concrete type in your grammar.js (e.g. add it to the
// `supertypes:` array).

// supertype (13)
//   [applied]  _module_export_name
//   [applied]  _expressions
//   [applied]  _jsx_element
//   [applied]  _jsx_child
//   [applied]  _jsx_identifier
//   [applied]  _jsx_element_name
//   [applied]  _jsx_attribute
//   [applied]  _jsx_attribute_name
//   [applied]  _jsx_attribute_value
//   [applied]  _formal_parameter
//   [applied]  _destructuring_pattern
//   [applied]  _identifier
//   [applied]  _tuple_type_member

// terminal (13)
//   [applied]  escape_sequence
//   [applied]  comment
//   [applied]  regex_pattern
//   [applied]  number
//   [applied]  identifier
//   [applied]  private_property_identifier
//   [applied]  meta_property
//   [applied]  _reserved_identifier
//   [applied]  predefined_type
//   [applied]  statement_identifier
//   [applied]  property_identifier
//   [applied]  string_fragment
//   [applied]  type_identifier

// polymorph (7)
//   [applied]  export_statement
//   [applied]  import_specifier
//   [applied]  statement
//   [applied]  parenthesized_expression
//   [applied]  arrow_function
//   [applied]  call_expression
//   [applied]  index_signature

// ---------------------------------------------------------------
// Field name inferences
// ---------------------------------------------------------------
//
// Each entry: the symbol being referenced, the inferred field name,
// the agreement ratio across all named parents, and a copy-paste
// `transform()` snippet for overrides.ts.
//
// To adopt a suggestion: copy the rule block into your overrides.ts
// rules map and pick a position index for the transform patch.

// statement_block → field('body')  [high, 100% agreement, 13 parents]
//   [applied]  statement
//
//   Override snippet (one per affected parent — pick a position):
//     statement: ($, original) => transform(original, {
//       N: field('body'),  // TODO: pick position N for $.statement_block
//     }),

// _type_identifier → field('name')  [medium, 90% agreement, 10 parents]
//   [applied]  primary_type
//
//   Override snippet (one per affected parent — pick a position):
//     primary_type: ($, original) => transform(original, {
//       N: field('name'),  // TODO: pick position N for $._type_identifier
//     }),
