import type { PortableCondition } from '@sittir/types';
import { WILDCARD } from '../../../bindings/facts.ts';
import type { GrammarRoutes, ReadEntry } from '../../../bindings/routes.ts';
import { aliasesOf, namespaceTree, type NamespaceNode } from './namespaces.ts';

export interface PortableSurfaceConfig {
	readonly routes: GrammarRoutes;
	readonly readTest: (entry: ReadEntry) => readonly PortableCondition[];
	readonly kindIdOf: (kind: string) => string;
	readonly fixedText: readonly (readonly [kindId: string, text: string])[];
}

const q = (text: string): string => JSON.stringify(text);

function descendantsOf(node: NamespaceNode): NamespaceNode[] {
	return [...node.children.values()].flatMap((child) => [child, ...descendantsOf(child)]);
}

export function emitPortableSurface({ routes, readTest, kindIdOf, fixedText }: PortableSurfaceConfig): string {
	const root = namespaceTree(routes.readEntries);
	const { aliases } = aliasesOf(root);
	const nodes = descendantsOf(root);
	const byPath = new Map([root, ...nodes].map((n) => [n.path, n]));
	const braces = (parts: readonly string[]): string => (parts.length === 0 ? '{}' : `{ ${parts.join('; ')} }`);
	const members = (under: string, at: string): string[] =>
		[
			...[...byPath.get(under)!.children].map(([name, child]) => [name, child.path] as const),
			...aliases.filter((a) => a.under === under).map((a) => [a.name, a.path] as const)
		]
			.map(([name, path]) => `readonly ${q(name)}: ${at}[${q(path)}]`);
	const under = (path: string, vocab: string): boolean => vocab === path || vocab.startsWith(`${path}.`);
	const exact = (n: NamespaceNode): boolean =>
		n.kinds.every((kind) => {
			const read = routes.readEntries.get(kind) ?? [];
			return (
				read.every((entry) => under(n.path, entry.vocab)) &&
				read.some((entry) => entry.claim.within.length === 0 && readTest(entry).length === 0)
			);
		});
	const entries = [...routes.readEntries].sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0));
	const entryRecord = (entry: ReadEntry): string => {
		const within = entry.claim.within.map((kind) => (kind === WILDCARD ? 'null' : kindIdOf(kind)));
		return `{ path: ${q(entry.vocab)}, within: [${within.join(', ')}], test: ${JSON.stringify(readTest(entry))} }`;
	};
	return [
		'// Auto-generated by @sittir/codegen — do not edit',
		'',
		"import type { PortableGuard, PortableTable } from '@sittir/types';",
		"import { portableSurface } from '@sittir/common/engine';",
		"import { TSKindId } from './types.js';",
		"import { querySlots } from './utils.js';",
		'',
		'export interface PortableIds {',
		...nodes.map((n) => `\t${q(n.path)}: ${n.kinds.map(kindIdOf).join(' | ')};`),
		'}',
		'',
		'export interface PortableKindsAt {',
		...nodes.map((n) => `\t${q(n.path)}: ${braces([`readonly $ids: readonly PortableIds[${q(n.path)}][]`, ...members(n.path, 'PortableKindsAt')])};`),
		'}',
		'',
		'export interface PortableIsAt {',
		...nodes.map((n) => `\t${q(n.path)}: PortableGuard<PortableIds[${q(n.path)}]> & ${braces(members(n.path, 'PortableIsAt'))};`),
		'}',
		'',
		`export interface PortableKinds ${braces(members('', 'PortableKindsAt'))}`,
		'',
		`export interface PortableIs ${braces(members('', 'PortableIsAt'))}`,
		'',
		'const table: PortableTable = {',
		'\tpaths: {',
		...nodes.map((n) => `\t\t${q(n.path)}: { ids: [${n.kinds.map(kindIdOf).join(', ')}], exact: ${exact(n)} },`),
		'\t},',
		`\taliases: [${aliases.map((a) => `[${q(a.under)}, ${q(a.name)}, ${q(a.path)}]`).join(', ')}],`,
		'\tentries: {',
		...entries.map(([kind, read]) => `\t\t[${kindIdOf(kind)}]: [${read.map(entryRecord).join(', ')}],`),
		'\t},',
		`\tfixedText: { ${fixedText.map(([id, text]) => `[${id}]: ${q(text)}`).join(', ')} },`,
		'};',
		'',
		'export const portable = portableSurface<PortableKinds, PortableIs>(table, querySlots);',
		''
	].join('\n');
}
