// @generated from packages/rust/node-model.json5 and packages/rust/templates/*.jinja — do not hand-edit.
// Regenerate via: npx tsx packages/codegen/src/cli.ts --grammar rust --all --output packages/rust/src
//
// render_dispatch match table — routes KindId to per-kind render functions
// in the sibling templates module.

#![allow(dead_code, unused_imports, non_snake_case, non_camel_case_types, unused_mut, unused_variables)]

use ::sittir_core::filters::{
    SingleNonterminalView, ListNonterminalView,
    OptionalNonterminalView,
};
use ::sittir_core::types::{
    NodeData, FieldValue, RenderableTransport, Source, Span, NodeTrivia, TransportTrivia,
};

#[cfg(feature = "napi-bindings")]
use ::napi_derive::napi;

use super::bridge::*;
use super::templates::*;

pub fn render_dispatch(node: &NodeData) -> Result<String, ::askama::Error> {
    if node.fields.is_none() && node.children.is_none() {
        if let Some(text) = &node.text {
            return Ok(text.to_owned());
        }
    }
    match node.type_.0 {
        322 => render_hidden_array_expression_list(node), // "_array_expression_list" | "array_expression_list"
        321 => render_hidden_array_expression_semi(node), // "_array_expression_semi" | "array_expression_semi"
        323 => render_hidden_closure_expression_block(node), // "_closure_expression_block" | "closure_expression_block"
        324 => render_hidden_closure_expression_expr(node), // "_closure_expression_expr" | "closure_expression_expr"
        381 => render_hidden_delim_token_tree_brace(node), // "_delim_token_tree_brace" | "delim_token_tree_brace"
        380 => render_hidden_delim_token_tree_bracket(node), // "_delim_token_tree_bracket" | "delim_token_tree_bracket"
        379 => render_hidden_delim_token_tree_paren(node), // "_delim_token_tree_paren" | "delim_token_tree_paren"
        366 => render_hidden_expression_statement_block_ending(node), // "_expression_statement_block_ending" | "expression_statement_block_ending"
        365 => render_hidden_expression_statement_with_semi(node), // "_expression_statement_with_semi" | "expression_statement_with_semi"
        414 => render_hidden_field_identifier(node), // "_field_identifier" | "field_identifier"
        326 => render_hidden_field_pattern_named(node), // "_field_pattern_named" | "field_pattern_named"
        325 => render_hidden_field_pattern_shorthand(node), // "_field_pattern_shorthand" | "field_pattern_shorthand"
        368 => render_hidden_foreign_mod_item_body(node), // "_foreign_mod_item_body" | "foreign_mod_item_body"
        328 => render_hidden_function_type_fn_form(node), // "_function_type_fn_form" | "function_type_fn_form"
        327 => render_hidden_function_type_trait_form(node), // "_function_type_trait_form" | "function_type_trait_form"
        329 => render_hidden_impl_item_body(node), // "_impl_item_body" | "impl_item_body"
        269 => render_hidden_let_chain(node), // "_let_chain"
        372 => render_hidden_line_comment_doc(node), // "_line_comment_doc" | "line_comment_doc"
        333 => render_hidden_macro_definition_brace(node), // "_macro_definition_brace" | "macro_definition_brace"
        332 => render_hidden_macro_definition_bracket(node), // "_macro_definition_bracket" | "macro_definition_bracket"
        331 => render_hidden_macro_definition_paren(node), // "_macro_definition_paren" | "macro_definition_paren"
        370 => render_hidden_match_arm_block_ending(node), // "_match_arm_block_ending" | "match_arm_block_ending"
        369 => render_hidden_match_arm_with_comma(node), // "_match_arm_with_comma" | "match_arm_with_comma"
        335 => render_hidden_mod_item_inline(node), // "_mod_item_inline" | "mod_item_inline"
        336 => render_hidden_or_pattern_binary(node), // "_or_pattern_binary" | "or_pattern_binary"
        337 => render_hidden_or_pattern_prefix(node), // "_or_pattern_prefix" | "or_pattern_prefix"
        359 => render_hidden_pointer_type_mut(node), // "_pointer_type_mut" | "pointer_type_mut"
        341 => render_hidden_range_expression_bare(node), // "_range_expression_bare" | "range_expression_bare"
        338 => render_hidden_range_expression_binary(node), // "_range_expression_binary" | "range_expression_binary"
        339 => render_hidden_range_expression_postfix(node), // "_range_expression_postfix" | "range_expression_postfix"
        340 => render_hidden_range_expression_prefix(node), // "_range_expression_prefix" | "range_expression_prefix"
        343 => render_hidden_range_pattern_left_with_right(node), // "_range_pattern_left_with_right" | "range_pattern_left_with_right"
        342 => render_hidden_range_pattern_prefix(node), // "_range_pattern_prefix" | "range_pattern_prefix"
        362 => render_hidden_reference_expression_raw_mut(node), // "_reference_expression_raw_mut" | "reference_expression_raw_mut"
        345 => render_hidden_struct_item_brace(node), // "_struct_item_brace" | "struct_item_brace"
        346 => render_hidden_struct_item_tuple(node), // "_struct_item_tuple" | "struct_item_tuple"
        378 => render_hidden_token_tree_brace(node), // "_token_tree_brace" | "token_tree_brace"
        377 => render_hidden_token_tree_bracket(node), // "_token_tree_bracket" | "token_tree_bracket"
        376 => render_hidden_token_tree_paren(node), // "_token_tree_paren" | "token_tree_paren"
        375 => render_hidden_token_tree_pattern_brace(node), // "_token_tree_pattern_brace" | "token_tree_pattern_brace"
        374 => render_hidden_token_tree_pattern_bracket(node), // "_token_tree_pattern_bracket" | "token_tree_pattern_bracket"
        373 => render_hidden_token_tree_pattern_paren(node), // "_token_tree_pattern_paren" | "token_tree_pattern_paren"
        417 => render_hidden_type_identifier(node), // "_type_identifier" | "type_identifier"
        348 => render_hidden_visibility_modifier_crate(node), // "_visibility_modifier_crate" | "visibility_modifier_crate"
        350 => render_hidden_visibility_modifier_in_path(node), // "_visibility_modifier_in_path" | "visibility_modifier_in_path"
        349 => render_hidden_visibility_modifier_pub(node), // "_visibility_modifier_pub" | "visibility_modifier_pub"
        235 => render_abstract_type(node), // "abstract_type"
        257 => render_arguments(node), // "arguments"
        258 => render_array_expression(node), // "array_expression"
        220 => render_array_type(node), // "array_type"
        251 => render_assignment_expression(node), // "assignment_expression"
        195 => render_associated_type(node), // "associated_type"
        290 => render_async_block(node), // "async_block"
        170 => render_attribute_item(node), // "attribute_item"
        172 => render_attribute(node), // "attribute"
        287 => render_await_expression(node), // "await_expression"
        266 => render_base_field_initializer(node), // "base_field_initializer"
        250 => render_binary_expression(node), // "binary_expression"
        318 => render_block_comment(node), // "block_comment"
        293 => render_block(node), // "block"
        228 => render_bounded_type(node), // "bounded_type"
        217 => render_bracketed_type(node), // "bracketed_type"
        284 => render_break_expression(node), // "break_expression"
        256 => render_call_expression(node), // "call_expression"
        305 => render_captured_pattern(node), // "captured_pattern"
        281 => render_closure_expression(node), // "closure_expression"
        282 => render_closure_parameters(node), // "closure_parameters"
        252 => render_compound_assignment_expr(node), // "compound_assignment_expr"
        280 => render_const_block(node), // "const_block"
        185 => render_const_item(node), // "const_item"
        200 => render_const_parameter(node), // "const_parameter"
        285 => render_continue_expression(node), // "continue_expression"
        175 => render_declaration_list(node), // "declaration_list"
        240 => render_delim_token_tree(node), // "delim_token_tree"
        236 => render_dynamic_type(node), // "dynamic_type"
        271 => render_else_clause(node), // "else_clause"
        178 => render_enum_item(node), // "enum_item"
        179 => render_enum_variant_list(node), // "enum_variant_list"
        180 => render_enum_variant(node), // "enum_variant"
        160 => render_expression_statement(node), // "expression_statement"
        184 => render_extern_crate_declaration(node), // "extern_crate_declaration"
        214 => render_extern_modifier(node), // "extern_modifier"
        181 => render_field_declaration_list(node), // "field_declaration_list"
        182 => render_field_declaration(node), // "field_declaration"
        288 => render_field_expression(node), // "field_expression"
        263 => render_field_initializer_list(node), // "field_initializer_list"
        265 => render_field_initializer(node), // "field_initializer"
        300 => render_field_pattern(node), // "field_pattern"
        279 => render_for_expression(node), // "for_expression"
        221 => render_for_lifetimes(node), // "for_lifetimes"
        174 => render_foreign_mod_item(node), // "foreign_mod_item"
        188 => render_function_item(node), // "function_item"
        190 => render_function_modifiers(node), // "function_modifiers"
        189 => render_function_signature_item(node), // "function_signature_item"
        222 => render_function_type(node), // "function_type"
        291 => render_gen_block(node), // "gen_block"
        225 => render_generic_function(node), // "generic_function"
        295 => render_generic_pattern(node), // "generic_pattern"
        227 => render_generic_type_with_turbofish(node), // "generic_type_with_turbofish"
        226 => render_generic_type(node), // "generic_type"
        197 => render_higher_ranked_trait_bound(node), // "higher_ranked_trait_bound"
        267 => render_if_expression(node), // "if_expression"
        193 => render_impl_item(node), // "impl_item"
        286 => render_index_expression(node), // "index_expression"
        171 => render_inner_attribute_item(node), // "inner_attribute_item"
        283 => render_label(node), // "label"
        275 => render_last_match_arm(node), // "last_match_arm"
        268 => render_let_condition(node), // "let_condition"
        203 => render_let_declaration(node), // "let_declaration"
        202 => render_lifetime_parameter(node), // "lifetime_parameter"
        219 => render_lifetime(node), // "lifetime"
        314 => render_line_comment(node), // "line_comment"
        278 => render_loop_expression(node), // "loop_expression"
        161 => render_macro_definition(node), // "macro_definition"
        239 => render_macro_invocation(node), // "macro_invocation"
        162 => render_macro_rule(node), // "macro_rule"
        274 => render_match_arm(node), // "match_arm"
        273 => render_match_block(node), // "match_block"
        272 => render_match_expression(node), // "match_expression"
        276 => render_match_pattern(node), // "match_pattern"
        173 => render_mod_item(node), // "mod_item"
        302 => render_mut_pattern(node), // "mut_pattern"
        310 => render_negative_literal(node), // "negative_literal"
        307 => render_or_pattern(node), // "or_pattern"
        183 => render_ordered_field_declaration_list(node), // "ordered_field_declaration_list"
        213 => render_parameter(node), // "parameter"
        210 => render_parameters(node), // "parameters"
        259 => render_parenthesized_expression(node), // "parenthesized_expression"
        233 => render_pointer_type(node), // "pointer_type"
        218 => render_qualified_type(node), // "qualified_type"
        246 => render_range_expression(node), // "range_expression"
        303 => render_range_pattern(node), // "range_pattern"
        312 => render_raw_string_literal(node), // "raw_string_literal"
        304 => render_ref_pattern(node), // "ref_pattern"
        249 => render_reference_expression(node), // "reference_expression"
        306 => render_reference_pattern(node), // "reference_pattern"
        232 => render_reference_type(node), // "reference_type"
        198 => render_removed_trait_bound(node), // "removed_trait_bound"
        254 => render_return_expression(node), // "return_expression"
        243 => render_scoped_identifier(node), // "scoped_identifier"
        244 => render_scoped_type_identifier_in_expression_position(node), // "scoped_type_identifier_in_expression_position"
        245 => render_scoped_type_identifier(node), // "scoped_type_identifier"
        206 => render_scoped_use_list(node), // "scoped_use_list"
        211 => render_self_parameter(node), // "self_parameter"
        264 => render_shorthand_field_initializer(node), // "shorthand_field_initializer"
        297 => render_slice_pattern(node), // "slice_pattern"
        157 => render_source_file(node), // "source_file"
        186 => render_static_item(node), // "static_item"
        311 => render_string_literal(node), // "string_literal"
        262 => render_struct_expression(node), // "struct_expression"
        176 => render_struct_item(node), // "struct_item"
        299 => render_struct_pattern(node), // "struct_pattern"
        165 => render_token_binding_pattern(node), // "token_binding_pattern"
        166 => render_token_repetition_pattern(node), // "token_repetition_pattern"
        169 => render_token_repetition(node), // "token_repetition"
        164 => render_token_tree_pattern(node), // "token_tree_pattern"
        168 => render_token_tree(node), // "token_tree"
        196 => render_trait_bounds(node), // "trait_bounds"
        194 => render_trait_item(node), // "trait_item"
        292 => render_try_block(node), // "try_block"
        248 => render_try_expression(node), // "try_expression"
        260 => render_tuple_expression(node), // "tuple_expression"
        296 => render_tuple_pattern(node), // "tuple_pattern"
        298 => render_tuple_struct_pattern(node), // "tuple_struct_pattern"
        223 => render_tuple_type(node), // "tuple_type"
        230 => render_type_arguments(node), // "type_arguments"
        231 => render_type_binding(node), // "type_binding"
        253 => render_type_cast_expression(node), // "type_cast_expression"
        187 => render_type_item(node), // "type_item"
        201 => render_type_parameter(node), // "type_parameter"
        199 => render_type_parameters(node), // "type_parameters"
        247 => render_unary_expression(node), // "unary_expression"
        177 => render_union_item(node), // "union_item"
        289 => render_unsafe_block(node), // "unsafe_block"
        208 => render_use_as_clause(node), // "use_as_clause"
        229 => render_use_bounds(node), // "use_bounds"
        204 => render_use_declaration(node), // "use_declaration"
        207 => render_use_list(node), // "use_list"
        209 => render_use_wildcard(node), // "use_wildcard"
        212 => render_variadic_parameter(node), // "variadic_parameter"
        215 => render_visibility_modifier(node), // "visibility_modifier"
        191 => render_where_clause(node), // "where_clause"
        192 => render_where_predicate(node), // "where_predicate"
        277 => render_while_expression(node), // "while_expression"
        255 => render_yield_expression(node), // "yield_expression"
        _ => token_shaped_fallback(node),
    }
}
