// @generated from packages/rust/.sittir/src/parser.c — do not hand-edit.
// Per-kind numeric ID constants matching the TS-side `TSKindId` enum.
//
// IDs come from `enum ts_symbol_identifiers` in parser.c (KindID
// runtime migration design, 2026-04-30). Use these constants when
// matching on `KindId` values; the inner u16 is the parser.c-derived
// symbol id.

use ::sittir_core::types::KindId;

pub const IDENTIFIER: KindId = KindId(1);
pub const SEMI: KindId = KindId(2);
pub const MACRO_RULES_BANG: KindId = KindId(3);
pub const EQ_GT: KindId = KindId(4);
pub const COLON: KindId = KindId(5);
pub const DOLLAR: KindId = KindId(6);
pub const LPAREN: KindId = KindId(7);
pub const RPAREN: KindId = KindId(8);
pub const TOKEN_REPETITION_PATTERN_TOKEN1: KindId = KindId(9);
pub const PLUS: KindId = KindId(10);
pub const STAR: KindId = KindId(11);
pub const QMARK: KindId = KindId(12);
pub const ANON_BLOCK: KindId = KindId(13);
pub const EXPR: KindId = KindId(14);
pub const EXPR2021: KindId = KindId(15);
pub const IDENT: KindId = KindId(16);
pub const ITEM: KindId = KindId(17);
pub const ANON_LIFETIME: KindId = KindId(18);
pub const LITERAL: KindId = KindId(19);
pub const META: KindId = KindId(20);
pub const PAT: KindId = KindId(21);
pub const PAT_PARAM: KindId = KindId(22);
pub const PATH: KindId = KindId(23);
pub const STMT: KindId = KindId(24);
pub const TT: KindId = KindId(25);
pub const TY: KindId = KindId(26);
pub const VIS: KindId = KindId(27);
pub const U8: KindId = KindId(28);
pub const I8: KindId = KindId(29);
pub const U16: KindId = KindId(30);
pub const I16: KindId = KindId(31);
pub const U32: KindId = KindId(32);
pub const I32: KindId = KindId(33);
pub const U64: KindId = KindId(34);
pub const I64: KindId = KindId(35);
pub const U128: KindId = KindId(36);
pub const I128: KindId = KindId(37);
pub const ISIZE: KindId = KindId(38);
pub const USIZE: KindId = KindId(39);
pub const F32: KindId = KindId(40);
pub const F64: KindId = KindId(41);
pub const BOOL: KindId = KindId(42);
pub const STR: KindId = KindId(43);
pub const CHAR: KindId = KindId(44);
pub const POUND: KindId = KindId(45);
pub const LBRACK: KindId = KindId(46);
pub const RBRACK: KindId = KindId(47);
pub const BANG: KindId = KindId(48);
pub const MOD: KindId = KindId(49);
pub const LBRACE: KindId = KindId(50);
pub const RBRACE: KindId = KindId(51);
pub const STRUCT: KindId = KindId(52);
pub const UNION: KindId = KindId(53);
pub const ENUM: KindId = KindId(54);
pub const EXTERN: KindId = KindId(55);
pub const CONST: KindId = KindId(56);
pub const STATIC: KindId = KindId(57);
pub const TYPE: KindId = KindId(58);
pub const EQ: KindId = KindId(59);
pub const FN: KindId = KindId(60);
pub const ASYNC: KindId = KindId(61);
pub const DEFAULT: KindId = KindId(62);
pub const UNSAFE: KindId = KindId(63);
pub const WHERE: KindId = KindId(64);
pub const IMPL: KindId = KindId(65);
pub const TRAIT: KindId = KindId(66);
pub const FOR: KindId = KindId(67);
pub const LT: KindId = KindId(68);
pub const GT: KindId = KindId(69);
pub const LET: KindId = KindId(70);
pub const USE: KindId = KindId(71);
pub const COLON_COLON: KindId = KindId(72);
pub const AS: KindId = KindId(73);
pub const DOT_DOT_DOT: KindId = KindId(74);
pub const SQUOTE: KindId = KindId(75);
pub const LT2: KindId = KindId(76);
pub const AMP: KindId = KindId(77);
pub const DYN: KindId = KindId(78);
pub const MUTABLE_SPECIFIER: KindId = KindId(79);
pub const DASH: KindId = KindId(80);
pub const AMP_AMP: KindId = KindId(81);
pub const PIPE_PIPE: KindId = KindId(82);
pub const PIPE: KindId = KindId(83);
pub const CARET: KindId = KindId(84);
pub const EQ_EQ: KindId = KindId(85);
pub const BANG_EQ: KindId = KindId(86);
pub const LT_EQ: KindId = KindId(87);
pub const GT_EQ: KindId = KindId(88);
pub const LT_LT: KindId = KindId(89);
pub const GT_GT: KindId = KindId(90);
pub const SLASH: KindId = KindId(91);
pub const PERCENT: KindId = KindId(92);
pub const PLUS_EQ: KindId = KindId(93);
pub const DASH_EQ: KindId = KindId(94);
pub const STAR_EQ: KindId = KindId(95);
pub const SLASH_EQ: KindId = KindId(96);
pub const PERCENT_EQ: KindId = KindId(97);
pub const AMP_EQ: KindId = KindId(98);
pub const PIPE_EQ: KindId = KindId(99);
pub const CARET_EQ: KindId = KindId(100);
pub const LT_LT_EQ: KindId = KindId(101);
pub const GT_GT_EQ: KindId = KindId(102);
pub const RETURN: KindId = KindId(103);
pub const YIELD: KindId = KindId(104);
pub const DOT_DOT: KindId = KindId(105);
pub const IF: KindId = KindId(106);
pub const ELSE: KindId = KindId(107);
pub const MATCH: KindId = KindId(108);
pub const WHILE: KindId = KindId(109);
pub const LOOP: KindId = KindId(110);
pub const IN: KindId = KindId(111);
pub const BREAK: KindId = KindId(112);
pub const CONTINUE: KindId = KindId(113);
pub const DOT: KindId = KindId(114);
pub const AWAIT: KindId = KindId(115);
pub const GEN: KindId = KindId(116);
pub const TRY: KindId = KindId(117);
pub const REF: KindId = KindId(118);
pub const AT: KindId = KindId(119);
pub const INTEGER_LITERAL: KindId = KindId(120);
pub const DQUOTE: KindId = KindId(121);
pub const CHAR_LITERAL: KindId = KindId(122);
pub const ESCAPE_SEQUENCE: KindId = KindId(123);
pub const TRUE: KindId = KindId(124);
pub const FALSE: KindId = KindId(125);
pub const SLASH_SLASH: KindId = KindId(126);
pub const BANG2: KindId = KindId(127);
pub const SLASH2: KindId = KindId(128);
pub const SLASH_STAR: KindId = KindId(129);
pub const STAR_SLASH: KindId = KindId(130);
pub const SHEBANG: KindId = KindId(131);
pub const SELF: KindId = KindId(132);
pub const SUPER: KindId = KindId(133);
pub const CRATE: KindId = KindId(134);
pub const METAVARIABLE: KindId = KindId(135);
pub const MOVE: KindId = KindId(136);
pub const COMMA: KindId = KindId(137);
pub const DASH_GT: KindId = KindId(138);
pub const _ANONYMOUS: KindId = KindId(139);
pub const DOT_DOT_EQ: KindId = KindId(140);
pub const PUB: KindId = KindId(141);
pub const _STRING_LITERAL_OPEN: KindId = KindId(142);
pub const RAW: KindId = KindId(143);
pub const _LINE_COMMENT_REGULAR_DSLASH_TOKEN1: KindId = KindId(144);
pub const _LINE_COMMENT_REGULAR_DSLASH_TOKEN2: KindId = KindId(145);
pub const _LINE_COMMENT_CONTENT: KindId = KindId(146);
pub const STRING_CONTENT: KindId = KindId(147);
pub const _RAW_STRING_LITERAL_START: KindId = KindId(148);
pub const RAW_STRING_LITERAL_CONTENT: KindId = KindId(149);
pub const _RAW_STRING_LITERAL_END: KindId = KindId(150);
pub const FLOAT_LITERAL: KindId = KindId(151);
pub const _OUTER_BLOCK_DOC_COMMENT_MARKER: KindId = KindId(152);
pub const _INNER_BLOCK_DOC_COMMENT_MARKER: KindId = KindId(153);
pub const _BLOCK_COMMENT_CONTENT: KindId = KindId(154);
pub const _LINE_DOC_CONTENT: KindId = KindId(155);
pub const _ERROR_SENTINEL: KindId = KindId(156);
pub const _TIGHT: KindId = KindId(157);
pub const _SPACE: KindId = KindId(158);
pub const _NEWLINE: KindId = KindId(159);
pub const SOURCE_FILE: KindId = KindId(160);
pub const _STATEMENT: KindId = KindId(161);
pub const EMPTY_STATEMENT: KindId = KindId(162);
pub const EXPRESSION_STATEMENT: KindId = KindId(163);
pub const MACRO_DEFINITION: KindId = KindId(164);
pub const MACRO_RULE: KindId = KindId(165);
pub const _TOKEN_PATTERN: KindId = KindId(166);
pub const TOKEN_TREE_PATTERN: KindId = KindId(167);
pub const TOKEN_BINDING_PATTERN: KindId = KindId(168);
pub const TOKEN_REPETITION_PATTERN: KindId = KindId(169);
pub const FRAGMENT_SPECIFIER: KindId = KindId(170);
pub const TOKEN_TREE: KindId = KindId(171);
pub const TOKEN_REPETITION: KindId = KindId(172);
pub const _NON_SPECIAL_TOKEN: KindId = KindId(173);
pub const ATTRIBUTE_ITEM: KindId = KindId(174);
pub const INNER_ATTRIBUTE_ITEM: KindId = KindId(175);
pub const ATTRIBUTE: KindId = KindId(176);
pub const MOD_ITEM: KindId = KindId(177);
pub const FOREIGN_MOD_ITEM: KindId = KindId(178);
pub const DECLARATION_LIST: KindId = KindId(179);
pub const STRUCT_ITEM: KindId = KindId(180);
pub const UNION_ITEM: KindId = KindId(181);
pub const ENUM_ITEM: KindId = KindId(182);
pub const ENUM_VARIANT_LIST: KindId = KindId(183);
pub const ENUM_VARIANT: KindId = KindId(184);
pub const FIELD_DECLARATION_LIST: KindId = KindId(185);
pub const FIELD_DECLARATION: KindId = KindId(186);
pub const ORDERED_FIELD_DECLARATION_LIST: KindId = KindId(187);
pub const EXTERN_CRATE_DECLARATION: KindId = KindId(188);
pub const CONST_ITEM: KindId = KindId(189);
pub const STATIC_ITEM: KindId = KindId(190);
pub const TYPE_ITEM: KindId = KindId(191);
pub const FUNCTION_ITEM: KindId = KindId(192);
pub const FUNCTION_SIGNATURE_ITEM: KindId = KindId(193);
pub const FUNCTION_MODIFIERS: KindId = KindId(194);
pub const WHERE_CLAUSE: KindId = KindId(195);
pub const WHERE_PREDICATE: KindId = KindId(196);
pub const IMPL_ITEM: KindId = KindId(197);
pub const TRAIT_ITEM: KindId = KindId(198);
pub const ASSOCIATED_TYPE: KindId = KindId(199);
pub const TRAIT_BOUNDS: KindId = KindId(200);
pub const HIGHER_RANKED_TRAIT_BOUND: KindId = KindId(201);
pub const REMOVED_TRAIT_BOUND: KindId = KindId(202);
pub const TYPE_PARAMETERS: KindId = KindId(203);
pub const CONST_PARAMETER: KindId = KindId(204);
pub const TYPE_PARAMETER: KindId = KindId(205);
pub const LIFETIME_PARAMETER: KindId = KindId(206);
pub const LET_DECLARATION: KindId = KindId(207);
pub const USE_DECLARATION: KindId = KindId(208);
pub const _USE_CLAUSE: KindId = KindId(209);
pub const SCOPED_USE_LIST: KindId = KindId(210);
pub const USE_LIST: KindId = KindId(211);
pub const USE_AS_CLAUSE: KindId = KindId(212);
pub const USE_WILDCARD: KindId = KindId(213);
pub const PARAMETERS: KindId = KindId(214);
pub const SELF_PARAMETER: KindId = KindId(215);
pub const VARIADIC_PARAMETER: KindId = KindId(216);
pub const PARAMETER: KindId = KindId(217);
pub const EXTERN_MODIFIER: KindId = KindId(218);
pub const VISIBILITY_MODIFIER: KindId = KindId(219);
pub const _TYPE: KindId = KindId(220);
pub const BRACKETED_TYPE: KindId = KindId(221);
pub const QUALIFIED_TYPE: KindId = KindId(222);
pub const LIFETIME: KindId = KindId(223);
pub const ARRAY_TYPE: KindId = KindId(224);
pub const FOR_LIFETIMES: KindId = KindId(225);
pub const FUNCTION_TYPE: KindId = KindId(226);
pub const TUPLE_TYPE: KindId = KindId(227);
pub const UNIT_TYPE: KindId = KindId(228);
pub const GENERIC_FUNCTION: KindId = KindId(229);
pub const GENERIC_TYPE: KindId = KindId(230);
pub const GENERIC_TYPE_WITH_TURBOFISH: KindId = KindId(231);
pub const BOUNDED_TYPE: KindId = KindId(232);
pub const USE_BOUNDS: KindId = KindId(233);
pub const TYPE_ARGUMENTS: KindId = KindId(234);
pub const TYPE_BINDING: KindId = KindId(235);
pub const REFERENCE_TYPE: KindId = KindId(236);
pub const POINTER_TYPE: KindId = KindId(237);
pub const NEVER_TYPE: KindId = KindId(238);
pub const ABSTRACT_TYPE: KindId = KindId(239);
pub const DYNAMIC_TYPE: KindId = KindId(240);
pub const _EXPRESSION_EXCEPT_RANGE: KindId = KindId(241);
pub const _EXPRESSION: KindId = KindId(242);
pub const MACRO_INVOCATION: KindId = KindId(243);
pub const DELIM_TOKEN_TREE: KindId = KindId(244);
pub const _DELIM_TOKENS: KindId = KindId(245);
pub const _NON_DELIM_TOKEN: KindId = KindId(246);
pub const SCOPED_IDENTIFIER: KindId = KindId(247);
pub const SCOPED_TYPE_IDENTIFIER_IN_EXPRESSION_POSITION: KindId = KindId(248);
pub const SCOPED_TYPE_IDENTIFIER: KindId = KindId(249);
pub const RANGE_EXPRESSION: KindId = KindId(250);
pub const UNARY_EXPRESSION: KindId = KindId(251);
pub const TRY_EXPRESSION: KindId = KindId(252);
pub const REFERENCE_EXPRESSION: KindId = KindId(253);
pub const BINARY_EXPRESSION: KindId = KindId(254);
pub const ASSIGNMENT_EXPRESSION: KindId = KindId(255);
pub const COMPOUND_ASSIGNMENT_EXPR: KindId = KindId(256);
pub const TYPE_CAST_EXPRESSION: KindId = KindId(257);
pub const RETURN_EXPRESSION: KindId = KindId(258);
pub const YIELD_EXPRESSION: KindId = KindId(259);
pub const CALL_EXPRESSION: KindId = KindId(260);
pub const ARGUMENTS: KindId = KindId(261);
pub const ARRAY_EXPRESSION: KindId = KindId(262);
pub const PARENTHESIZED_EXPRESSION: KindId = KindId(263);
pub const TUPLE_EXPRESSION: KindId = KindId(264);
pub const UNIT_EXPRESSION: KindId = KindId(265);
pub const STRUCT_EXPRESSION: KindId = KindId(266);
pub const FIELD_INITIALIZER_LIST: KindId = KindId(267);
pub const SHORTHAND_FIELD_INITIALIZER: KindId = KindId(268);
pub const FIELD_INITIALIZER: KindId = KindId(269);
pub const BASE_FIELD_INITIALIZER: KindId = KindId(270);
pub const IF_EXPRESSION: KindId = KindId(271);
pub const LET_CONDITION: KindId = KindId(272);
pub const _LET_CHAIN: KindId = KindId(273);
pub const _CONDITION: KindId = KindId(274);
pub const ELSE_CLAUSE: KindId = KindId(275);
pub const MATCH_EXPRESSION: KindId = KindId(276);
pub const MATCH_BLOCK: KindId = KindId(277);
pub const MATCH_ARM: KindId = KindId(278);
pub const LAST_MATCH_ARM: KindId = KindId(279);
pub const MATCH_PATTERN: KindId = KindId(280);
pub const WHILE_EXPRESSION: KindId = KindId(281);
pub const LOOP_EXPRESSION: KindId = KindId(282);
pub const FOR_EXPRESSION: KindId = KindId(283);
pub const CONST_BLOCK: KindId = KindId(284);
pub const CLOSURE_EXPRESSION: KindId = KindId(285);
pub const CLOSURE_PARAMETERS: KindId = KindId(286);
pub const LABEL: KindId = KindId(287);
pub const BREAK_EXPRESSION: KindId = KindId(288);
pub const CONTINUE_EXPRESSION: KindId = KindId(289);
pub const INDEX_EXPRESSION: KindId = KindId(290);
pub const AWAIT_EXPRESSION: KindId = KindId(291);
pub const FIELD_EXPRESSION: KindId = KindId(292);
pub const UNSAFE_BLOCK: KindId = KindId(293);
pub const ASYNC_BLOCK: KindId = KindId(294);
pub const GEN_BLOCK: KindId = KindId(295);
pub const TRY_BLOCK: KindId = KindId(296);
pub const BLOCK: KindId = KindId(297);
pub const _PATTERN: KindId = KindId(298);
pub const GENERIC_PATTERN: KindId = KindId(299);
pub const TUPLE_PATTERN: KindId = KindId(300);
pub const SLICE_PATTERN: KindId = KindId(301);
pub const TUPLE_STRUCT_PATTERN: KindId = KindId(302);
pub const STRUCT_PATTERN: KindId = KindId(303);
pub const FIELD_PATTERN: KindId = KindId(304);
pub const REMAINING_FIELD_PATTERN: KindId = KindId(305);
pub const MUT_PATTERN: KindId = KindId(306);
pub const RANGE_PATTERN: KindId = KindId(307);
pub const REF_PATTERN: KindId = KindId(308);
pub const CAPTURED_PATTERN: KindId = KindId(309);
pub const REFERENCE_PATTERN: KindId = KindId(310);
pub const OR_PATTERN: KindId = KindId(311);
pub const _LITERAL: KindId = KindId(312);
pub const _LITERAL_PATTERN: KindId = KindId(313);
pub const NEGATIVE_LITERAL: KindId = KindId(314);
pub const STRING_LITERAL: KindId = KindId(315);
pub const RAW_STRING_LITERAL: KindId = KindId(316);
pub const BOOLEAN_LITERAL: KindId = KindId(317);
pub const LINE_COMMENT: KindId = KindId(318);
pub const _INNER_LINE_DOC_COMMENT_MARKER: KindId = KindId(319);
pub const _OUTER_LINE_DOC_COMMENT_MARKER: KindId = KindId(320);
pub const BLOCK_COMMENT: KindId = KindId(321);
pub const _KW_REF_MARKER: KindId = KindId(322);
pub const _KW_UNSAFE_MARKER: KindId = KindId(323);
pub const _KW_STATIC_MARKER: KindId = KindId(324);
pub const _KW_ASYNC_MARKER: KindId = KindId(325);
pub const _KW_MOVE_MARKER: KindId = KindId(326);
pub const _MACRO_RULES: KindId = KindId(327);
pub const _ENUM_VARIANT_LIST_ELEMENTS: KindId = KindId(328);
pub const _FIELD_DECLARATION_LIST_ELEMENTS: KindId = KindId(329);
pub const _ORDERED_FIELD_DECLARATION_LIST_ELEMENTS: KindId = KindId(330);
pub const _WHERE_PREDICATES: KindId = KindId(331);
pub const _TYPE_PARAMETERS_ELEMENTS: KindId = KindId(332);
pub const _USE_CLAUSES: KindId = KindId(333);
pub const _PARAMETERS_ELEMENTS: KindId = KindId(334);
pub const _LIFETIMES: KindId = KindId(335);
pub const _USE_BOUNDS_ELEMENTS: KindId = KindId(336);
pub const _TYPE_ARGUMENTS_ELEMENTS: KindId = KindId(337);
pub const _ARGUMENTS_ELEMENTS: KindId = KindId(338);
pub const _FIELD_INITIALIZER_LIST_ELEMENTS: KindId = KindId(339);
pub const _TUPLE_PATTERN_ELEMENTS: KindId = KindId(340);
pub const _PATTERNS: KindId = KindId(341);
pub const _STRUCT_PATTERN_ELEMENTS: KindId = KindId(342);
pub const _VISIBILITY_MODIFIER_GROUP: KindId = KindId(343);
pub const _TUPLE_TYPE_ELEMENTS: KindId = KindId(344);
pub const _TUPLE_EXPRESSION_ELEMENTS: KindId = KindId(345);
pub const _TOKEN_TREE_PUNCTUATION: KindId = KindId(346);
pub const _TOKEN_KEYWORDS: KindId = KindId(347);
pub const _USE_WILDCARD_CLAUSE: KindId = KindId(348);
pub const _WILDCARD_PATTERN: KindId = KindId(349);
pub const _RANGE_EXPRESSION_BARE: KindId = KindId(350);
pub const _REFERENCE_EXPRESSION_RAW_CONST: KindId = KindId(351);
pub const _REFERENCE_EXPRESSION_RAW_MUT: KindId = KindId(352);
pub const _IMPL_ITEM_UNSAFE_MARKER: KindId = KindId(353);
pub const _IMPL_ITEM_BODY: KindId = KindId(354);
pub const _IMPL_ITEM_SEMI: KindId = KindId(355);
pub const _IMPL_ITEM_POSITIVE_CLAUSE: KindId = KindId(356);
pub const _IMPL_ITEM_NEGATIVE_CLAUSE: KindId = KindId(357);
pub const _ARRAY_EXPRESSION_SEMI: KindId = KindId(358);
pub const _ARRAY_EXPRESSION_LIST: KindId = KindId(359);
pub const _ATTRIBUTE_INPUT: KindId = KindId(360);
pub const _CLOSURE_EXPRESSION_BLOCK: KindId = KindId(361);
pub const _CLOSURE_EXPRESSION_EXPR: KindId = KindId(362);
pub const _VISIBILITY_MODIFIER_PUB: KindId = KindId(363);
pub const _VISIBILITY_MODIFIER_IN_PATH: KindId = KindId(364);
pub const _FUNCTION_TYPE_TRAIT_FORM: KindId = KindId(365);
pub const _FUNCTION_TYPE_FN_FORM: KindId = KindId(366);
pub const _MOD_ITEM_EXTERNAL: KindId = KindId(367);
pub const _OR_PATTERN_BINARY: KindId = KindId(368);
pub const _OR_PATTERN_PREFIX: KindId = KindId(369);
pub const _POINTER_TYPE_CONST: KindId = KindId(370);
pub const _RANGE_EXPRESSION_BINARY: KindId = KindId(371);
pub const _RANGE_EXPRESSION_POSTFIX: KindId = KindId(372);
pub const _RANGE_EXPRESSION_PREFIX: KindId = KindId(373);
pub const _EXPRESSION_STATEMENT_WITH_SEMI: KindId = KindId(374);
pub const _FOREIGN_MOD_ITEM_SEMI: KindId = KindId(375);
pub const _MATCH_ARM_WITH_COMMA: KindId = KindId(376);
pub const _LINE_COMMENT_REGULAR_DSLASH: KindId = KindId(377);
pub const _LINE_COMMENT_DOC_OUTER: KindId = KindId(378);
pub const _LINE_COMMENT_DOC_INNER: KindId = KindId(379);
pub const _BLOCK_COMMENT_DOC_OUTER: KindId = KindId(380);
pub const _BLOCK_COMMENT_DOC_INNER: KindId = KindId(381);
pub const _TOKEN_TREE_PATTERN_PAREN: KindId = KindId(382);
pub const _TOKEN_TREE_PATTERN_BRACKET: KindId = KindId(383);
pub const _TOKEN_TREE_PATTERN_BRACE: KindId = KindId(384);
pub const _TOKEN_TREE_PAREN: KindId = KindId(385);
pub const _TOKEN_TREE_BRACKET: KindId = KindId(386);
pub const _TOKEN_TREE_BRACE: KindId = KindId(387);
pub const _DELIM_TOKEN_TREE_PAREN: KindId = KindId(388);
pub const _DELIM_TOKEN_TREE_BRACKET: KindId = KindId(389);
pub const _DELIM_TOKEN_TREE_BRACE: KindId = KindId(390);
pub const _FIELD_PATTERN_NAMED: KindId = KindId(391);
pub const _MACRO_DEFINITION_PAREN: KindId = KindId(392);
pub const _MACRO_DEFINITION_BRACKET: KindId = KindId(393);
pub const _MACRO_DEFINITION_BRACE: KindId = KindId(394);
pub const _RANGE_PATTERN_PREFIX: KindId = KindId(395);
pub const _RANGE_PATTERN_LEFT_WITH_RIGHT: KindId = KindId(396);
pub const _RANGE_PATTERN_LEFT_BARE: KindId = KindId(397);
pub const _RANGE_PATTERN_WITH_LEFT: KindId = KindId(398);
pub const _STRUCT_ITEM_BRACE: KindId = KindId(399);
pub const _STRUCT_ITEM_TUPLE: KindId = KindId(400);
pub const _STRUCT_ITEM_UNIT: KindId = KindId(401);
pub const _ATTRIBUTED_FIELD_DECLARATION: KindId = KindId(402);
pub const _ATTRIBUTED_ENUM_VARIANT: KindId = KindId(403);
pub const _ATTRIBUTED_PARAMETER: KindId = KindId(404);
pub const _ATTRIBUTED_TYPE_PARAMETER: KindId = KindId(405);
pub const _ATTRIBUTED_ARGUMENT: KindId = KindId(406);
pub const _ATTRIBUTED_ORDERED_FIELD: KindId = KindId(407);
pub const _TYPE_ARGUMENT: KindId = KindId(408);
pub const _MATCH_BLOCK_ARMS: KindId = KindId(409);
pub const SOURCE_FILE_REPEAT1: KindId = KindId(410);
pub const TOKEN_REPETITION_PATTERN_REPEAT1: KindId = KindId(411);
pub const TOKEN_REPETITION_REPEAT1: KindId = KindId(412);
pub const DECLARATION_LIST_REPEAT1: KindId = KindId(413);
pub const FUNCTION_MODIFIERS_REPEAT1: KindId = KindId(414);
pub const TRAIT_BOUNDS_REPEAT1: KindId = KindId(415);
pub const TUPLE_EXPRESSION_REPEAT1: KindId = KindId(416);
pub const MATCH_ARM_REPEAT1: KindId = KindId(417);
pub const STRING_LITERAL_REPEAT1: KindId = KindId(418);
pub const _MACRO_RULES_REPEAT1: KindId = KindId(419);
pub const _ENUM_VARIANT_LIST_ELEMENTS_REPEAT1: KindId = KindId(420);
pub const _FIELD_DECLARATION_LIST_ELEMENTS_REPEAT1: KindId = KindId(421);
pub const _ORDERED_FIELD_DECLARATION_LIST_ELEMENTS_REPEAT1: KindId = KindId(422);
pub const _WHERE_PREDICATES_REPEAT1: KindId = KindId(423);
pub const _TYPE_PARAMETERS_ELEMENTS_REPEAT1: KindId = KindId(424);
pub const _USE_CLAUSES_REPEAT1: KindId = KindId(425);
pub const _PARAMETERS_ELEMENTS_REPEAT1: KindId = KindId(426);
pub const _LIFETIMES_REPEAT1: KindId = KindId(427);
pub const _USE_BOUNDS_ELEMENTS_REPEAT1: KindId = KindId(428);
pub const _TYPE_ARGUMENTS_ELEMENTS_REPEAT1: KindId = KindId(429);
pub const _ARGUMENTS_ELEMENTS_REPEAT1: KindId = KindId(430);
pub const _FIELD_INITIALIZER_LIST_ELEMENTS_REPEAT1: KindId = KindId(431);
pub const _CLOSURE_PARAMETERS_OPTIONAL1_REPEAT1: KindId = KindId(432);
pub const _TUPLE_PATTERN_ELEMENTS_REPEAT1: KindId = KindId(433);
pub const _PATTERNS_REPEAT1: KindId = KindId(434);
pub const _STRUCT_PATTERN_ELEMENTS_REPEAT1: KindId = KindId(435);
pub const _TUPLE_TYPE_ELEMENTS_REPEAT1: KindId = KindId(436);
pub const _TUPLE_EXPRESSION_ELEMENTS_REPEAT1: KindId = KindId(437);
pub const _DELIM_TOKEN_TREE_PAREN_REPEAT1: KindId = KindId(438);
pub const _MATCH_BLOCK_ARMS_REPEAT1: KindId = KindId(439);
pub const _FIELD_IDENTIFIER: KindId = KindId(440);
pub const _SHORTHAND_FIELD_IDENTIFIER: KindId = KindId(442);
pub const _TYPE_IDENTIFIER: KindId = KindId(443);

/// Map a `KindId` back to its grammar kind string for diagnostics.
/// Returns `"<unknown>"` for ids not in this grammar's symbol table.
pub fn kind_name_from_id(id: KindId) -> &'static str {
    match id.0 {
        1 => "identifier", // "identifier"
        2 => ";", // "semi"
        3 => "macro_rules!", // "macro_rules_bang"
        4 => "=>", // "eq_gt"
        5 => ":", // "colon"
        6 => "$", // "dollar"
        7 => "(", // "lparen"
        8 => ")", // "rparen"
        9 => "token_repetition_pattern_token1", // "token_repetition_pattern_token1"
        10 => "+", // "plus"
        11 => "*", // "star"
        12 => "?", // "qmark"
        13 => "block", // "anon_block"
        14 => "expr", // "expr"
        15 => "expr_2021", // "expr_2021"
        16 => "ident", // "ident"
        17 => "item", // "item"
        18 => "lifetime", // "anon_lifetime"
        19 => "literal", // "literal"
        20 => "meta", // "meta"
        21 => "pat", // "pat"
        22 => "pat_param", // "pat_param"
        23 => "path", // "path"
        24 => "stmt", // "stmt"
        25 => "tt", // "tt"
        26 => "ty", // "ty"
        27 => "vis", // "vis"
        28 => "primitive_type", // "u8"
        29 => "primitive_type", // "i8"
        30 => "primitive_type", // "u16"
        31 => "primitive_type", // "i16"
        32 => "primitive_type", // "u32"
        33 => "primitive_type", // "i32"
        34 => "primitive_type", // "u64"
        35 => "primitive_type", // "i64"
        36 => "primitive_type", // "u128"
        37 => "primitive_type", // "i128"
        38 => "primitive_type", // "isize"
        39 => "primitive_type", // "usize"
        40 => "primitive_type", // "f32"
        41 => "primitive_type", // "f64"
        42 => "primitive_type", // "bool"
        43 => "primitive_type", // "str"
        44 => "primitive_type", // "char"
        45 => "#", // "pound"
        46 => "[", // "lbrack"
        47 => "]", // "rbrack"
        48 => "!", // "bang"
        49 => "mod", // "mod"
        50 => "{", // "lbrace"
        51 => "}", // "rbrace"
        52 => "struct", // "struct"
        53 => "union", // "union"
        54 => "enum", // "enum"
        55 => "extern", // "extern"
        56 => "const", // "const"
        57 => "static", // "static"
        58 => "type", // "type"
        59 => "=", // "eq"
        60 => "fn", // "fn"
        61 => "async", // "async"
        62 => "default", // "default"
        63 => "unsafe", // "unsafe"
        64 => "where", // "where"
        65 => "impl", // "impl"
        66 => "trait", // "trait"
        67 => "for", // "for"
        68 => "<", // "lt"
        69 => ">", // "gt"
        70 => "let", // "let"
        71 => "use", // "use"
        72 => "::", // "colon_colon"
        73 => "as", // "as"
        74 => "...", // "dot_dot_dot"
        75 => "'", // "squote"
        76 => "<", // "lt2"
        77 => "&", // "amp"
        78 => "dyn", // "dyn"
        79 => "mutable_specifier", // "mutable_specifier"
        80 => "-", // "dash"
        81 => "&&", // "amp_amp"
        82 => "||", // "pipe_pipe"
        83 => "|", // "pipe"
        84 => "^", // "caret"
        85 => "==", // "eq_eq"
        86 => "!=", // "bang_eq"
        87 => "<=", // "lt_eq"
        88 => ">=", // "gt_eq"
        89 => "<<", // "lt_lt"
        90 => ">>", // "gt_gt"
        91 => "/", // "slash"
        92 => "%", // "percent"
        93 => "+=", // "plus_eq"
        94 => "-=", // "dash_eq"
        95 => "*=", // "star_eq"
        96 => "/=", // "slash_eq"
        97 => "%=", // "percent_eq"
        98 => "&=", // "amp_eq"
        99 => "|=", // "pipe_eq"
        100 => "^=", // "caret_eq"
        101 => "<<=", // "lt_lt_eq"
        102 => ">>=", // "gt_gt_eq"
        103 => "return", // "return"
        104 => "yield", // "yield"
        105 => "..", // "dot_dot"
        106 => "if", // "if"
        107 => "else", // "else"
        108 => "match", // "match"
        109 => "while", // "while"
        110 => "loop", // "loop"
        111 => "in", // "in"
        112 => "break", // "break"
        113 => "continue", // "continue"
        114 => ".", // "dot"
        115 => "await", // "await"
        116 => "gen", // "gen"
        117 => "try", // "try"
        118 => "ref", // "ref"
        119 => "@", // "at"
        120 => "integer_literal", // "integer_literal"
        121 => "\"", // "dquote"
        122 => "char_literal", // "char_literal"
        123 => "escape_sequence", // "escape_sequence"
        124 => "true", // "true"
        125 => "false", // "false"
        126 => "//", // "slash_slash"
        127 => "!", // "bang2"
        128 => "/", // "slash2"
        129 => "/*", // "slash_star"
        130 => "*/", // "star_slash"
        131 => "shebang", // "shebang"
        132 => "self", // "self"
        133 => "super", // "super"
        134 => "crate", // "crate"
        135 => "metavariable", // "metavariable"
        136 => "move", // "move"
        137 => ",", // "comma"
        138 => "->", // "dash_gt"
        139 => "_", // "_"
        140 => "..=", // "dot_dot_eq"
        141 => "pub", // "pub"
        142 => "string_open", // "_string_literal_open"
        143 => "raw", // "raw"
        144 => "_line_comment_regular_dslash_token1", // "_line_comment_regular_dslash_token1"
        145 => "_line_comment_regular_dslash_token2", // "_line_comment_regular_dslash_token2"
        146 => "line_comment_content", // "_line_comment_content"
        147 => "string_content", // "string_content"
        148 => "raw_string_literal_start", // "_raw_string_literal_start"
        149 => "string_content", // "raw_string_literal_content"
        150 => "raw_string_literal_end", // "_raw_string_literal_end"
        151 => "float_literal", // "float_literal"
        152 => "outer_doc_comment_marker", // "_outer_block_doc_comment_marker"
        153 => "inner_doc_comment_marker", // "_inner_block_doc_comment_marker"
        154 => "_block_comment_content", // "_block_comment_content"
        155 => "doc_comment", // "_line_doc_content"
        156 => "_error_sentinel", // "_error_sentinel"
        157 => "_tight", // "_tight"
        158 => "_space", // "_space"
        159 => "_newline", // "_newline"
        160 => "source_file", // "source_file"
        161 => "_statement", // "_statement"
        162 => "empty_statement", // "empty_statement"
        163 => "expression_statement", // "expression_statement"
        164 => "macro_definition", // "macro_definition"
        165 => "macro_rule", // "macro_rule"
        166 => "_token_pattern", // "_token_pattern"
        167 => "token_tree_pattern", // "token_tree_pattern"
        168 => "token_binding_pattern", // "token_binding_pattern"
        169 => "token_repetition_pattern", // "token_repetition_pattern"
        170 => "fragment_specifier", // "fragment_specifier"
        171 => "token_tree", // "token_tree"
        172 => "token_repetition", // "token_repetition"
        173 => "non_special_token", // "_non_special_token"
        174 => "attribute_item", // "attribute_item"
        175 => "inner_attribute_item", // "inner_attribute_item"
        176 => "attribute", // "attribute"
        177 => "mod_item", // "mod_item"
        178 => "foreign_mod_item", // "foreign_mod_item"
        179 => "declaration_list", // "declaration_list"
        180 => "struct_item", // "struct_item"
        181 => "union_item", // "union_item"
        182 => "enum_item", // "enum_item"
        183 => "enum_variant_list", // "enum_variant_list"
        184 => "enum_variant", // "enum_variant"
        185 => "field_declaration_list", // "field_declaration_list"
        186 => "field_declaration", // "field_declaration"
        187 => "ordered_field_declaration_list", // "ordered_field_declaration_list"
        188 => "extern_crate_declaration", // "extern_crate_declaration"
        189 => "const_item", // "const_item"
        190 => "static_item", // "static_item"
        191 => "type_item", // "type_item"
        192 => "function_item", // "function_item"
        193 => "function_signature_item", // "function_signature_item"
        194 => "function_modifiers", // "function_modifiers"
        195 => "where_clause", // "where_clause"
        196 => "where_predicate", // "where_predicate"
        197 => "impl_item", // "impl_item"
        198 => "trait_item", // "trait_item"
        199 => "associated_type", // "associated_type"
        200 => "trait_bounds", // "trait_bounds"
        201 => "higher_ranked_trait_bound", // "higher_ranked_trait_bound"
        202 => "removed_trait_bound", // "removed_trait_bound"
        203 => "type_parameters", // "type_parameters"
        204 => "const_parameter", // "const_parameter"
        205 => "type_parameter", // "type_parameter"
        206 => "lifetime_parameter", // "lifetime_parameter"
        207 => "let_declaration", // "let_declaration"
        208 => "use_declaration", // "use_declaration"
        209 => "_use_clause", // "_use_clause"
        210 => "scoped_use_list", // "scoped_use_list"
        211 => "use_list", // "use_list"
        212 => "use_as_clause", // "use_as_clause"
        213 => "use_wildcard", // "use_wildcard"
        214 => "parameters", // "parameters"
        215 => "self_parameter", // "self_parameter"
        216 => "variadic_parameter", // "variadic_parameter"
        217 => "parameter", // "parameter"
        218 => "extern_modifier", // "extern_modifier"
        219 => "visibility_modifier", // "visibility_modifier"
        220 => "_type", // "_type"
        221 => "bracketed_type", // "bracketed_type"
        222 => "qualified_type", // "qualified_type"
        223 => "lifetime", // "lifetime"
        224 => "array_type", // "array_type"
        225 => "for_lifetimes", // "for_lifetimes"
        226 => "function_type", // "function_type"
        227 => "tuple_type", // "tuple_type"
        228 => "unit_type", // "unit_type"
        229 => "generic_function", // "generic_function"
        230 => "generic_type", // "generic_type"
        231 => "generic_type_with_turbofish", // "generic_type_with_turbofish"
        232 => "bounded_type", // "bounded_type"
        233 => "use_bounds", // "use_bounds"
        234 => "type_arguments", // "type_arguments"
        235 => "type_binding", // "type_binding"
        236 => "reference_type", // "reference_type"
        237 => "pointer_type", // "pointer_type"
        238 => "never_type", // "never_type"
        239 => "abstract_type", // "abstract_type"
        240 => "dynamic_type", // "dynamic_type"
        241 => "_expression_except_range", // "_expression_except_range"
        242 => "_expression", // "_expression"
        243 => "macro_invocation", // "macro_invocation"
        244 => "token_tree", // "delim_token_tree"
        245 => "_delim_tokens", // "_delim_tokens"
        246 => "_non_delim_token", // "_non_delim_token"
        247 => "scoped_identifier", // "scoped_identifier"
        248 => "scoped_type_identifier", // "scoped_type_identifier_in_expression_position"
        249 => "scoped_type_identifier", // "scoped_type_identifier"
        250 => "range_expression", // "range_expression"
        251 => "unary_expression", // "unary_expression"
        252 => "try_expression", // "try_expression"
        253 => "reference_expression", // "reference_expression"
        254 => "binary_expression", // "binary_expression"
        255 => "assignment_expression", // "assignment_expression"
        256 => "compound_assignment_expr", // "compound_assignment_expr"
        257 => "type_cast_expression", // "type_cast_expression"
        258 => "return_expression", // "return_expression"
        259 => "yield_expression", // "yield_expression"
        260 => "call_expression", // "call_expression"
        261 => "arguments", // "arguments"
        262 => "array_expression", // "array_expression"
        263 => "parenthesized_expression", // "parenthesized_expression"
        264 => "tuple_expression", // "tuple_expression"
        265 => "unit_expression", // "unit_expression"
        266 => "struct_expression", // "struct_expression"
        267 => "field_initializer_list", // "field_initializer_list"
        268 => "shorthand_field_initializer", // "shorthand_field_initializer"
        269 => "field_initializer", // "field_initializer"
        270 => "base_field_initializer", // "base_field_initializer"
        271 => "if_expression", // "if_expression"
        272 => "let_condition", // "let_condition"
        273 => "let_chain", // "_let_chain"
        274 => "_condition", // "_condition"
        275 => "else_clause", // "else_clause"
        276 => "match_expression", // "match_expression"
        277 => "match_block", // "match_block"
        278 => "match_arm", // "match_arm"
        279 => "last_match_arm", // "last_match_arm"
        280 => "match_pattern", // "match_pattern"
        281 => "while_expression", // "while_expression"
        282 => "loop_expression", // "loop_expression"
        283 => "for_expression", // "for_expression"
        284 => "const_block", // "const_block"
        285 => "closure_expression", // "closure_expression"
        286 => "closure_parameters", // "closure_parameters"
        287 => "label", // "label"
        288 => "break_expression", // "break_expression"
        289 => "continue_expression", // "continue_expression"
        290 => "index_expression", // "index_expression"
        291 => "await_expression", // "await_expression"
        292 => "field_expression", // "field_expression"
        293 => "unsafe_block", // "unsafe_block"
        294 => "async_block", // "async_block"
        295 => "gen_block", // "gen_block"
        296 => "try_block", // "try_block"
        297 => "block", // "block"
        298 => "_pattern", // "_pattern"
        299 => "generic_pattern", // "generic_pattern"
        300 => "tuple_pattern", // "tuple_pattern"
        301 => "slice_pattern", // "slice_pattern"
        302 => "tuple_struct_pattern", // "tuple_struct_pattern"
        303 => "struct_pattern", // "struct_pattern"
        304 => "field_pattern", // "field_pattern"
        305 => "remaining_field_pattern", // "remaining_field_pattern"
        306 => "mut_pattern", // "mut_pattern"
        307 => "range_pattern", // "range_pattern"
        308 => "ref_pattern", // "ref_pattern"
        309 => "captured_pattern", // "captured_pattern"
        310 => "reference_pattern", // "reference_pattern"
        311 => "or_pattern", // "or_pattern"
        312 => "_literal", // "_literal"
        313 => "_literal_pattern", // "_literal_pattern"
        314 => "negative_literal", // "negative_literal"
        315 => "string_literal", // "string_literal"
        316 => "raw_string_literal", // "raw_string_literal"
        317 => "boolean_literal", // "boolean_literal"
        318 => "line_comment", // "line_comment"
        319 => "inner_doc_comment_marker", // "_inner_line_doc_comment_marker"
        320 => "outer_doc_comment_marker", // "_outer_line_doc_comment_marker"
        321 => "block_comment", // "block_comment"
        322 => "_kw_ref_marker", // "_kw_ref_marker"
        323 => "_kw_unsafe_marker", // "_kw_unsafe_marker"
        324 => "_kw_static_marker", // "_kw_static_marker"
        325 => "_kw_async_marker", // "_kw_async_marker"
        326 => "_kw_move_marker", // "_kw_move_marker"
        327 => "macro_rules", // "_macro_rules"
        328 => "enum_variant_list_elements", // "_enum_variant_list_elements"
        329 => "field_declaration_list_elements", // "_field_declaration_list_elements"
        330 => "ordered_field_declaration_list_elements", // "_ordered_field_declaration_list_elements"
        331 => "where_predicates", // "_where_predicates"
        332 => "type_parameters_elements", // "_type_parameters_elements"
        333 => "use_clauses", // "_use_clauses"
        334 => "parameters_elements", // "_parameters_elements"
        335 => "lifetimes", // "_lifetimes"
        336 => "use_bounds_elements", // "_use_bounds_elements"
        337 => "type_arguments_elements", // "_type_arguments_elements"
        338 => "arguments_elements", // "_arguments_elements"
        339 => "field_initializer_list_elements", // "_field_initializer_list_elements"
        340 => "tuple_pattern_elements", // "_tuple_pattern_elements"
        341 => "patterns", // "_patterns"
        342 => "struct_pattern_elements", // "_struct_pattern_elements"
        343 => "visibility_modifier_group", // "_visibility_modifier_group"
        344 => "tuple_type_elements", // "_tuple_type_elements"
        345 => "tuple_expression_elements", // "_tuple_expression_elements"
        346 => "token_tree_punctuation", // "_token_tree_punctuation"
        347 => "_token_keywords", // "_token_keywords"
        348 => "_use_wildcard_clause", // "_use_wildcard_clause"
        349 => "wildcard_pattern", // "_wildcard_pattern"
        350 => "range_expression_bare", // "_range_expression_bare"
        351 => "reference_expression_raw_const", // "_reference_expression_raw_const"
        352 => "reference_expression_raw_mut", // "_reference_expression_raw_mut"
        353 => "_impl_item_unsafe_marker", // "_impl_item_unsafe_marker"
        354 => "impl_item_body", // "_impl_item_body"
        355 => "impl_item_semi", // "_impl_item_semi"
        356 => "impl_item_positive_clause", // "_impl_item_positive_clause"
        357 => "impl_item_negative_clause", // "_impl_item_negative_clause"
        358 => "array_expression_semi", // "_array_expression_semi"
        359 => "array_expression_list", // "_array_expression_list"
        360 => "attribute_input", // "_attribute_input"
        361 => "closure_expression_block", // "_closure_expression_block"
        362 => "closure_expression_expr", // "_closure_expression_expr"
        363 => "visibility_modifier_pub", // "_visibility_modifier_pub"
        364 => "visibility_modifier_in_path", // "_visibility_modifier_in_path"
        365 => "function_type_trait_form", // "_function_type_trait_form"
        366 => "function_type_fn_form", // "_function_type_fn_form"
        367 => "mod_item_external", // "_mod_item_external"
        368 => "or_pattern_binary", // "_or_pattern_binary"
        369 => "or_pattern_prefix", // "_or_pattern_prefix"
        370 => "pointer_type_const", // "_pointer_type_const"
        371 => "range_expression_binary", // "_range_expression_binary"
        372 => "range_expression_postfix", // "_range_expression_postfix"
        373 => "range_expression_prefix", // "_range_expression_prefix"
        374 => "expression_statement_with_semi", // "_expression_statement_with_semi"
        375 => "foreign_mod_item_semi", // "_foreign_mod_item_semi"
        376 => "match_arm_with_comma", // "_match_arm_with_comma"
        377 => "line_comment_regular_dslash", // "_line_comment_regular_dslash"
        378 => "line_comment_doc_outer", // "_line_comment_doc_outer"
        379 => "line_comment_doc_inner", // "_line_comment_doc_inner"
        380 => "block_comment_doc_outer", // "_block_comment_doc_outer"
        381 => "block_comment_doc_inner", // "_block_comment_doc_inner"
        382 => "token_tree_pattern_paren", // "_token_tree_pattern_paren"
        383 => "token_tree_pattern_bracket", // "_token_tree_pattern_bracket"
        384 => "token_tree_pattern_brace", // "_token_tree_pattern_brace"
        385 => "token_tree_paren", // "_token_tree_paren"
        386 => "token_tree_bracket", // "_token_tree_bracket"
        387 => "token_tree_brace", // "_token_tree_brace"
        388 => "delim_token_tree_paren", // "_delim_token_tree_paren"
        389 => "delim_token_tree_bracket", // "_delim_token_tree_bracket"
        390 => "delim_token_tree_brace", // "_delim_token_tree_brace"
        391 => "field_pattern_named", // "_field_pattern_named"
        392 => "macro_definition_paren", // "_macro_definition_paren"
        393 => "macro_definition_bracket", // "_macro_definition_bracket"
        394 => "macro_definition_brace", // "_macro_definition_brace"
        395 => "range_pattern_prefix", // "_range_pattern_prefix"
        396 => "range_pattern_left_with_right", // "_range_pattern_left_with_right"
        397 => "range_pattern_left_bare", // "_range_pattern_left_bare"
        398 => "range_pattern_with_left", // "_range_pattern_with_left"
        399 => "struct_item_brace", // "_struct_item_brace"
        400 => "struct_item_tuple", // "_struct_item_tuple"
        401 => "struct_item_unit", // "_struct_item_unit"
        402 => "attributed_field_declaration", // "_attributed_field_declaration"
        403 => "attributed_enum_variant", // "_attributed_enum_variant"
        404 => "attributed_parameter", // "_attributed_parameter"
        405 => "attributed_type_parameter", // "_attributed_type_parameter"
        406 => "attributed_argument", // "_attributed_argument"
        407 => "attributed_ordered_field", // "_attributed_ordered_field"
        408 => "type_argument", // "_type_argument"
        409 => "match_block_arms", // "_match_block_arms"
        410 => "source_file_repeat1", // "source_file_repeat1"
        411 => "token_repetition_pattern_repeat1", // "token_repetition_pattern_repeat1"
        412 => "token_repetition_repeat1", // "token_repetition_repeat1"
        413 => "declaration_list_repeat1", // "declaration_list_repeat1"
        414 => "function_modifiers_repeat1", // "function_modifiers_repeat1"
        415 => "trait_bounds_repeat1", // "trait_bounds_repeat1"
        416 => "tuple_expression_repeat1", // "tuple_expression_repeat1"
        417 => "match_arm_repeat1", // "match_arm_repeat1"
        418 => "string_literal_repeat1", // "string_literal_repeat1"
        419 => "_macro_rules_repeat1", // "_macro_rules_repeat1"
        420 => "_enum_variant_list_elements_repeat1", // "_enum_variant_list_elements_repeat1"
        421 => "_field_declaration_list_elements_repeat1", // "_field_declaration_list_elements_repeat1"
        422 => "_ordered_field_declaration_list_elements_repeat1", // "_ordered_field_declaration_list_elements_repeat1"
        423 => "_where_predicates_repeat1", // "_where_predicates_repeat1"
        424 => "_type_parameters_elements_repeat1", // "_type_parameters_elements_repeat1"
        425 => "_use_clauses_repeat1", // "_use_clauses_repeat1"
        426 => "_parameters_elements_repeat1", // "_parameters_elements_repeat1"
        427 => "_lifetimes_repeat1", // "_lifetimes_repeat1"
        428 => "_use_bounds_elements_repeat1", // "_use_bounds_elements_repeat1"
        429 => "_type_arguments_elements_repeat1", // "_type_arguments_elements_repeat1"
        430 => "_arguments_elements_repeat1", // "_arguments_elements_repeat1"
        431 => "_field_initializer_list_elements_repeat1", // "_field_initializer_list_elements_repeat1"
        432 => "_closure_parameters_optional1_repeat1", // "_closure_parameters_optional1_repeat1"
        433 => "_tuple_pattern_elements_repeat1", // "_tuple_pattern_elements_repeat1"
        434 => "_patterns_repeat1", // "_patterns_repeat1"
        435 => "_struct_pattern_elements_repeat1", // "_struct_pattern_elements_repeat1"
        436 => "_tuple_type_elements_repeat1", // "_tuple_type_elements_repeat1"
        437 => "_tuple_expression_elements_repeat1", // "_tuple_expression_elements_repeat1"
        438 => "_delim_token_tree_paren_repeat1", // "_delim_token_tree_paren_repeat1"
        439 => "_match_block_arms_repeat1", // "_match_block_arms_repeat1"
        440 => "field_identifier", // "_field_identifier"
        442 => "shorthand_field_identifier", // "_shorthand_field_identifier"
        443 => "type_identifier", // "_type_identifier"
        _ => "<unknown>",
    }
}
