// @generated from packages/rust/.sittir/src/parser.c — do not hand-edit.
// Per-kind numeric ID constants matching the TS-side `TSKindId` enum.
//
// IDs come from `enum ts_symbol_identifiers` in parser.c (KindID
// runtime migration design, 2026-04-30). Use these constants when
// matching on `KindId` values; the inner u16 is the parser.c-derived
// symbol id.

use ::sittir_core::types::KindId;

pub const IDENTIFIER: KindId = KindId(1);
pub const SEMI: KindId = KindId(2);
pub const EQ_GT: KindId = KindId(3);
pub const COLON: KindId = KindId(4);
pub const DOLLAR: KindId = KindId(5);
pub const LPAREN: KindId = KindId(6);
pub const RPAREN: KindId = KindId(7);
pub const TOKEN_REPETITION_PATTERN_TOKEN1: KindId = KindId(8);
pub const PLUS: KindId = KindId(9);
pub const STAR: KindId = KindId(10);
pub const QMARK: KindId = KindId(11);
pub const BLOCK_KEYWORD: KindId = KindId(12);
pub const EXPR_KEYWORD: KindId = KindId(13);
pub const EXPR2021_KEYWORD: KindId = KindId(14);
pub const IDENT_KEYWORD: KindId = KindId(15);
pub const ITEM_KEYWORD: KindId = KindId(16);
pub const LIFETIME_KEYWORD: KindId = KindId(17);
pub const LITERAL_KEYWORD: KindId = KindId(18);
pub const META_KEYWORD: KindId = KindId(19);
pub const PAT_KEYWORD: KindId = KindId(20);
pub const PAT_PARAM_KEYWORD: KindId = KindId(21);
pub const PATH_KEYWORD: KindId = KindId(22);
pub const STMT_KEYWORD: KindId = KindId(23);
pub const TT_KEYWORD: KindId = KindId(24);
pub const TY_KEYWORD: KindId = KindId(25);
pub const VIS_KEYWORD: KindId = KindId(26);
pub const POUND: KindId = KindId(27);
pub const LBRACK: KindId = KindId(28);
pub const RBRACK: KindId = KindId(29);
pub const BANG: KindId = KindId(30);
pub const LBRACE: KindId = KindId(31);
pub const RBRACE: KindId = KindId(32);
pub const UNION_KEYWORD: KindId = KindId(33);
pub const ENUM_KEYWORD: KindId = KindId(34);
pub const EXTERN_KEYWORD: KindId = KindId(35);
pub const CONST_KEYWORD: KindId = KindId(36);
pub const STATIC_KEYWORD: KindId = KindId(37);
pub const TYPE_KEYWORD: KindId = KindId(38);
pub const EQ: KindId = KindId(39);
pub const FN_KEYWORD: KindId = KindId(40);
pub const WHERE_KEYWORD: KindId = KindId(41);
pub const TRAIT_KEYWORD: KindId = KindId(42);
pub const FOR_KEYWORD: KindId = KindId(43);
pub const LT: KindId = KindId(44);
pub const GT: KindId = KindId(45);
pub const LET_KEYWORD: KindId = KindId(46);
pub const USE_KEYWORD: KindId = KindId(47);
pub const COLON_COLON: KindId = KindId(48);
pub const AS_KEYWORD: KindId = KindId(49);
pub const DOT_DOT_DOT: KindId = KindId(50);
pub const SQUOTE: KindId = KindId(51);
pub const DEFAULT_KEYWORD: KindId = KindId(52);
pub const GEN_KEYWORD: KindId = KindId(53);
pub const LT2: KindId = KindId(54);
pub const AMP: KindId = KindId(55);
pub const IMPL_KEYWORD: KindId = KindId(56);
pub const DYN_KEYWORD: KindId = KindId(57);
pub const MUTABLE_SPECIFIER: KindId = KindId(58);
pub const U8_KEYWORD: KindId = KindId(59);
pub const I8_KEYWORD: KindId = KindId(60);
pub const U16_KEYWORD: KindId = KindId(61);
pub const I16_KEYWORD: KindId = KindId(62);
pub const U32_KEYWORD: KindId = KindId(63);
pub const I32_KEYWORD: KindId = KindId(64);
pub const U64_KEYWORD: KindId = KindId(65);
pub const I64_KEYWORD: KindId = KindId(66);
pub const U128_KEYWORD: KindId = KindId(67);
pub const I128_KEYWORD: KindId = KindId(68);
pub const ISIZE_KEYWORD: KindId = KindId(69);
pub const USIZE_KEYWORD: KindId = KindId(70);
pub const F32_KEYWORD: KindId = KindId(71);
pub const F64_KEYWORD: KindId = KindId(72);
pub const BOOL_KEYWORD: KindId = KindId(73);
pub const STR_KEYWORD: KindId = KindId(74);
pub const CHAR_KEYWORD: KindId = KindId(75);
pub const DASH: KindId = KindId(76);
pub const AMP_AMP: KindId = KindId(77);
pub const PIPE_PIPE: KindId = KindId(78);
pub const PIPE: KindId = KindId(79);
pub const CARET: KindId = KindId(80);
pub const EQ_EQ: KindId = KindId(81);
pub const BANG_EQ: KindId = KindId(82);
pub const LT_EQ: KindId = KindId(83);
pub const GT_EQ: KindId = KindId(84);
pub const LT_LT: KindId = KindId(85);
pub const GT_GT: KindId = KindId(86);
pub const SLASH: KindId = KindId(87);
pub const PERCENT: KindId = KindId(88);
pub const PLUS_EQ: KindId = KindId(89);
pub const DASH_EQ: KindId = KindId(90);
pub const STAR_EQ: KindId = KindId(91);
pub const SLASH_EQ: KindId = KindId(92);
pub const PERCENT_EQ: KindId = KindId(93);
pub const AMP_EQ: KindId = KindId(94);
pub const PIPE_EQ: KindId = KindId(95);
pub const CARET_EQ: KindId = KindId(96);
pub const LT_LT_EQ: KindId = KindId(97);
pub const GT_GT_EQ: KindId = KindId(98);
pub const RETURN_KEYWORD: KindId = KindId(99);
pub const YIELD_KEYWORD: KindId = KindId(100);
pub const DOT_DOT: KindId = KindId(101);
pub const IF_KEYWORD: KindId = KindId(102);
pub const ELSE_KEYWORD: KindId = KindId(103);
pub const MATCH_KEYWORD: KindId = KindId(104);
pub const WHILE_KEYWORD: KindId = KindId(105);
pub const LOOP_KEYWORD: KindId = KindId(106);
pub const IN_KEYWORD: KindId = KindId(107);
pub const BREAK_KEYWORD: KindId = KindId(108);
pub const CONTINUE_KEYWORD: KindId = KindId(109);
pub const DOT: KindId = KindId(110);
pub const AWAIT_KEYWORD: KindId = KindId(111);
pub const UNSAFE_KEYWORD: KindId = KindId(112);
pub const ASYNC_KEYWORD: KindId = KindId(113);
pub const TRY_KEYWORD: KindId = KindId(114);
pub const REF_KEYWORD: KindId = KindId(115);
pub const AT: KindId = KindId(116);
pub const DQUOTE: KindId = KindId(117);
pub const TRUE_KEYWORD: KindId = KindId(118);
pub const FALSE_KEYWORD: KindId = KindId(119);
pub const SLASH_SLASH: KindId = KindId(120);
pub const BANG2: KindId = KindId(121);
pub const SLASH2: KindId = KindId(122);
pub const SLASH_STAR: KindId = KindId(123);
pub const STAR_SLASH: KindId = KindId(124);
pub const SHEBANG: KindId = KindId(125);
pub const SELF: KindId = KindId(126);
pub const SUPER: KindId = KindId(127);
pub const CRATE: KindId = KindId(128);
pub const METAVARIABLE: KindId = KindId(129);
pub const MOVE_KEYWORD: KindId = KindId(130);
pub const COMMA: KindId = KindId(131);
pub const DASH_GT: KindId = KindId(132);
pub const UNDERSCORE: KindId = KindId(133);
pub const DOT_DOT_EQ: KindId = KindId(134);
pub const MOD_KEYWORD: KindId = KindId(135);
pub const PUB_KEYWORD: KindId = KindId(136);
pub const STRUCT_KEYWORD: KindId = KindId(137);
pub const INTEGER_LITERAL_DECIMAL: KindId = KindId(138);
pub const INTEGER_LITERAL_HEX: KindId = KindId(139);
pub const INTEGER_LITERAL_BINARY: KindId = KindId(140);
pub const INTEGER_LITERAL_OCTAL: KindId = KindId(141);
pub const CHAR_LITERAL_PLAIN: KindId = KindId(142);
pub const CHAR_LITERAL_EMPTY: KindId = KindId(143);
pub const CHAR_LITERAL_ESCAPED_SIMPLE: KindId = KindId(144);
pub const CHAR_LITERAL_ESCAPED_UNICODE_FIXED: KindId = KindId(145);
pub const CHAR_LITERAL_ESCAPED_UNICODE_BRACED: KindId = KindId(146);
pub const CHAR_LITERAL_ESCAPED_HEX: KindId = KindId(147);
pub const ESCAPE_SEQUENCE_SIMPLE: KindId = KindId(148);
pub const ESCAPE_SEQUENCE_UNICODE_FIXED: KindId = KindId(149);
pub const ESCAPE_SEQUENCE_UNICODE_BRACED: KindId = KindId(150);
pub const ESCAPE_SEQUENCE_HEX: KindId = KindId(151);
pub const RAW_KEYWORD: KindId = KindId(152);
pub const _STRING_OPEN: KindId = KindId(153);
pub const LINE_COMMENT_EXTRA_SLASHES_TOKEN1: KindId = KindId(154);
pub const LINE_COMMENT_EXTRA_SLASHES_TOKEN2: KindId = KindId(155);
pub const LINE_COMMENT_REGULAR: KindId = KindId(156);
pub const MACRO_RULES_BANG: KindId = KindId(157);
pub const STRING_CONTENT: KindId = KindId(158);
pub const _RAW_STRING_LITERAL_START: KindId = KindId(159);
pub const RAW_STRING_LITERAL_CONTENT: KindId = KindId(160);
pub const _RAW_STRING_LITERAL_END: KindId = KindId(161);
pub const FLOAT_LITERAL: KindId = KindId(162);
pub const _OUTER_DOC_COMMENT_MARKER: KindId = KindId(163);
pub const _INNER_DOC_COMMENT_MARKER: KindId = KindId(164);
pub const _BLOCK_COMMENT_CONTENT: KindId = KindId(165);
pub const _DOC_COMMENT: KindId = KindId(166);
pub const _ERROR_SENTINEL: KindId = KindId(167);
pub const _TIGHT: KindId = KindId(168);
pub const _SPACE: KindId = KindId(169);
pub const _TAB: KindId = KindId(170);
pub const _NEWLINE: KindId = KindId(171);
pub const _BLANKLINE: KindId = KindId(172);
pub const _DOUBLE_BLANKLINE: KindId = KindId(173);
pub const _INDENT: KindId = KindId(174);
pub const _DEDENT: KindId = KindId(175);
pub const SOURCE_FILE: KindId = KindId(176);
pub const _STATEMENT: KindId = KindId(177);
pub const EMPTY_STATEMENT: KindId = KindId(178);
pub const EXPRESSION_STATEMENT: KindId = KindId(179);
pub const MACRO_DEFINITION: KindId = KindId(180);
pub const MACRO_RULE: KindId = KindId(181);
pub const _TOKEN_PATTERN: KindId = KindId(182);
pub const TOKEN_TREE_PATTERN: KindId = KindId(183);
pub const TOKEN_BINDING_PATTERN: KindId = KindId(184);
pub const TOKEN_REPETITION_PATTERN: KindId = KindId(185);
pub const FRAGMENT_SPECIFIER: KindId = KindId(186);
pub const TOKEN_TREE: KindId = KindId(187);
pub const TOKEN_REPETITION: KindId = KindId(188);
pub const _NON_SPECIAL_TOKEN: KindId = KindId(189);
pub const ATTRIBUTE_ITEM: KindId = KindId(190);
pub const INNER_ATTRIBUTE_ITEM: KindId = KindId(191);
pub const ATTRIBUTE: KindId = KindId(192);
pub const MOD_ITEM: KindId = KindId(193);
pub const FOREIGN_MOD_ITEM: KindId = KindId(194);
pub const DECLARATION_LIST: KindId = KindId(195);
pub const STRUCT_ITEM: KindId = KindId(196);
pub const UNION_ITEM: KindId = KindId(197);
pub const ENUM_ITEM: KindId = KindId(198);
pub const ENUM_VARIANT_LIST: KindId = KindId(199);
pub const ENUM_VARIANT: KindId = KindId(200);
pub const FIELD_DECLARATION_LIST: KindId = KindId(201);
pub const FIELD_DECLARATION: KindId = KindId(202);
pub const ORDERED_FIELD_DECLARATION_LIST: KindId = KindId(203);
pub const EXTERN_CRATE_DECLARATION: KindId = KindId(204);
pub const CONST_ITEM: KindId = KindId(205);
pub const STATIC_ITEM: KindId = KindId(206);
pub const TYPE_ITEM: KindId = KindId(207);
pub const FUNCTION_ITEM: KindId = KindId(208);
pub const FUNCTION_SIGNATURE_ITEM: KindId = KindId(209);
pub const FUNCTION_MODIFIERS: KindId = KindId(210);
pub const WHERE_CLAUSE: KindId = KindId(211);
pub const WHERE_PREDICATE: KindId = KindId(212);
pub const IMPL_ITEM: KindId = KindId(213);
pub const TRAIT_ITEM: KindId = KindId(214);
pub const ASSOCIATED_TYPE: KindId = KindId(215);
pub const TRAIT_BOUNDS: KindId = KindId(216);
pub const HIGHER_RANKED_TRAIT_BOUND: KindId = KindId(217);
pub const REMOVED_TRAIT_BOUND: KindId = KindId(218);
pub const TYPE_PARAMETERS: KindId = KindId(219);
pub const CONST_PARAMETER: KindId = KindId(220);
pub const TYPE_PARAMETER: KindId = KindId(221);
pub const LIFETIME_PARAMETER: KindId = KindId(222);
pub const LET_DECLARATION: KindId = KindId(223);
pub const USE_DECLARATION: KindId = KindId(224);
pub const _USE_CLAUSE: KindId = KindId(225);
pub const SCOPED_USE_LIST: KindId = KindId(226);
pub const USE_LIST: KindId = KindId(227);
pub const USE_AS_CLAUSE: KindId = KindId(228);
pub const USE_WILDCARD: KindId = KindId(229);
pub const PARAMETERS: KindId = KindId(230);
pub const SELF_PARAMETER: KindId = KindId(231);
pub const VARIADIC_PARAMETER: KindId = KindId(232);
pub const PARAMETER: KindId = KindId(233);
pub const EXTERN_MODIFIER: KindId = KindId(234);
pub const VISIBILITY_MODIFIER: KindId = KindId(235);
pub const _TYPE: KindId = KindId(236);
pub const BRACKETED_TYPE: KindId = KindId(237);
pub const QUALIFIED_TYPE: KindId = KindId(238);
pub const LIFETIME: KindId = KindId(239);
pub const ARRAY_TYPE: KindId = KindId(240);
pub const FOR_LIFETIMES: KindId = KindId(241);
pub const FUNCTION_TYPE: KindId = KindId(242);
pub const TUPLE_TYPE: KindId = KindId(243);
pub const UNIT_TYPE: KindId = KindId(244);
pub const GENERIC_FUNCTION: KindId = KindId(245);
pub const GENERIC_TYPE: KindId = KindId(246);
pub const GENERIC_TYPE_WITH_TURBOFISH: KindId = KindId(247);
pub const BOUNDED_TYPE: KindId = KindId(248);
pub const USE_BOUNDS: KindId = KindId(249);
pub const TYPE_ARGUMENTS: KindId = KindId(250);
pub const TYPE_BINDING: KindId = KindId(251);
pub const REFERENCE_TYPE: KindId = KindId(252);
pub const POINTER_TYPE: KindId = KindId(253);
pub const NEVER_TYPE: KindId = KindId(254);
pub const ABSTRACT_TYPE: KindId = KindId(255);
pub const DYNAMIC_TYPE: KindId = KindId(256);
pub const _EXPRESSION_EXCEPT_RANGE: KindId = KindId(257);
pub const _EXPRESSION: KindId = KindId(258);
pub const MACRO_INVOCATION: KindId = KindId(259);
pub const DELIM_TOKEN_TREE: KindId = KindId(260);
pub const _DELIM_TOKENS: KindId = KindId(261);
pub const _NON_DELIM_TOKEN: KindId = KindId(262);
pub const SCOPED_IDENTIFIER: KindId = KindId(263);
pub const SCOPED_TYPE_IDENTIFIER_IN_EXPRESSION_POSITION: KindId = KindId(264);
pub const SCOPED_TYPE_IDENTIFIER: KindId = KindId(265);
pub const RANGE_EXPRESSION: KindId = KindId(266);
pub const UNARY_EXPRESSION: KindId = KindId(267);
pub const TRY_EXPRESSION: KindId = KindId(268);
pub const REFERENCE_EXPRESSION: KindId = KindId(269);
pub const BINARY_EXPRESSION: KindId = KindId(270);
pub const ASSIGNMENT_EXPRESSION: KindId = KindId(271);
pub const COMPOUND_ASSIGNMENT_EXPR: KindId = KindId(272);
pub const TYPE_CAST_EXPRESSION: KindId = KindId(273);
pub const RETURN_EXPRESSION: KindId = KindId(274);
pub const YIELD_EXPRESSION: KindId = KindId(275);
pub const CALL_EXPRESSION: KindId = KindId(276);
pub const ARGUMENTS: KindId = KindId(277);
pub const ARRAY_EXPRESSION: KindId = KindId(278);
pub const PARENTHESIZED_EXPRESSION: KindId = KindId(279);
pub const TUPLE_EXPRESSION: KindId = KindId(280);
pub const UNIT_EXPRESSION: KindId = KindId(281);
pub const STRUCT_EXPRESSION: KindId = KindId(282);
pub const FIELD_INITIALIZER_LIST: KindId = KindId(283);
pub const SHORTHAND_FIELD_INITIALIZER: KindId = KindId(284);
pub const FIELD_INITIALIZER: KindId = KindId(285);
pub const BASE_FIELD_INITIALIZER: KindId = KindId(286);
pub const IF_EXPRESSION: KindId = KindId(287);
pub const LET_CONDITION: KindId = KindId(288);
pub const _LET_CHAIN: KindId = KindId(289);
pub const _CONDITION: KindId = KindId(290);
pub const ELSE_CLAUSE: KindId = KindId(291);
pub const MATCH_EXPRESSION: KindId = KindId(292);
pub const MATCH_BLOCK: KindId = KindId(293);
pub const MATCH_ARM: KindId = KindId(294);
pub const LAST_MATCH_ARM: KindId = KindId(295);
pub const MATCH_PATTERN: KindId = KindId(296);
pub const WHILE_EXPRESSION: KindId = KindId(297);
pub const LOOP_EXPRESSION: KindId = KindId(298);
pub const FOR_EXPRESSION: KindId = KindId(299);
pub const CONST_BLOCK: KindId = KindId(300);
pub const CLOSURE_EXPRESSION: KindId = KindId(301);
pub const CLOSURE_PARAMETERS: KindId = KindId(302);
pub const LABEL: KindId = KindId(303);
pub const BREAK_EXPRESSION: KindId = KindId(304);
pub const CONTINUE_EXPRESSION: KindId = KindId(305);
pub const INDEX_EXPRESSION: KindId = KindId(306);
pub const AWAIT_EXPRESSION: KindId = KindId(307);
pub const FIELD_EXPRESSION: KindId = KindId(308);
pub const UNSAFE_BLOCK: KindId = KindId(309);
pub const ASYNC_BLOCK: KindId = KindId(310);
pub const GEN_BLOCK: KindId = KindId(311);
pub const TRY_BLOCK: KindId = KindId(312);
pub const BLOCK: KindId = KindId(313);
pub const _PATTERN: KindId = KindId(314);
pub const GENERIC_PATTERN: KindId = KindId(315);
pub const TUPLE_PATTERN: KindId = KindId(316);
pub const SLICE_PATTERN: KindId = KindId(317);
pub const TUPLE_STRUCT_PATTERN: KindId = KindId(318);
pub const STRUCT_PATTERN: KindId = KindId(319);
pub const FIELD_PATTERN: KindId = KindId(320);
pub const REMAINING_FIELD_PATTERN: KindId = KindId(321);
pub const MUT_PATTERN: KindId = KindId(322);
pub const RANGE_PATTERN: KindId = KindId(323);
pub const REF_PATTERN: KindId = KindId(324);
pub const CAPTURED_PATTERN: KindId = KindId(325);
pub const REFERENCE_PATTERN: KindId = KindId(326);
pub const OR_PATTERN: KindId = KindId(327);
pub const _LITERAL: KindId = KindId(328);
pub const _LITERAL_PATTERN: KindId = KindId(329);
pub const NEGATIVE_LITERAL: KindId = KindId(330);
pub const INTEGER_LITERAL: KindId = KindId(331);
pub const STRING_LITERAL: KindId = KindId(332);
pub const RAW_STRING_LITERAL: KindId = KindId(333);
pub const CHAR_LITERAL: KindId = KindId(334);
pub const ESCAPE_SEQUENCE: KindId = KindId(335);
pub const BOOLEAN_LITERAL: KindId = KindId(336);
pub const LINE_COMMENT: KindId = KindId(337);
pub const _INNER_LINE_DOC_COMMENT_MARKER: KindId = KindId(338);
pub const _OUTER_LINE_DOC_COMMENT_MARKER: KindId = KindId(339);
pub const BLOCK_COMMENT: KindId = KindId(340);
pub const _PRIMITIVE_TYPE: KindId = KindId(341);
pub const MACRO_RULES: KindId = KindId(342);
pub const ENUM_VARIANT_LIST_ELEMENTS: KindId = KindId(343);
pub const FIELD_DECLARATION_LIST_ELEMENTS: KindId = KindId(344);
pub const ORDERED_FIELD_DECLARATION_LIST_ELEMENTS: KindId = KindId(345);
pub const WHERE_PREDICATES: KindId = KindId(346);
pub const TYPE_PARAMETERS_ELEMENTS: KindId = KindId(347);
pub const USE_CLAUSES: KindId = KindId(348);
pub const PARAMETERS_ELEMENTS: KindId = KindId(349);
pub const LIFETIMES: KindId = KindId(350);
pub const USE_BOUNDS_ELEMENTS: KindId = KindId(351);
pub const TYPE_ARGUMENTS_ELEMENTS: KindId = KindId(352);
pub const ARGUMENTS_ELEMENTS: KindId = KindId(353);
pub const FIELD_INITIALIZER_LIST_ELEMENTS: KindId = KindId(354);
pub const TUPLE_PATTERN_ELEMENTS: KindId = KindId(355);
pub const PATTERNS: KindId = KindId(356);
pub const STRUCT_PATTERN_ELEMENTS: KindId = KindId(357);
pub const USE_WILDCARD_GROUP: KindId = KindId(358);
pub const _TUPLE_TYPE_ELEMENTS: KindId = KindId(359);
pub const _TUPLE_EXPRESSION_ELEMENTS: KindId = KindId(360);
pub const _TOKEN_TREE_PUNCTUATION: KindId = KindId(361);
pub const _TOKEN_KEYWORDS: KindId = KindId(362);
pub const _RANGE_EXPRESSION_BARE: KindId = KindId(363);
pub const _IMPL_ITEM_UNSAFE_MARKER: KindId = KindId(364);
pub const CHAR_LITERAL_ESCAPED: KindId = KindId(365);
pub const ARRAY_EXPRESSION_SEMI: KindId = KindId(366);
pub const ARRAY_EXPRESSION_LIST: KindId = KindId(367);
pub const ATTRIBUTE_INPUT: KindId = KindId(368);
pub const CLOSURE_EXPRESSION_BLOCK: KindId = KindId(369);
pub const CLOSURE_EXPRESSION_EXPR: KindId = KindId(370);
pub const REFERENCE_EXPRESSION_RAW_CONST: KindId = KindId(371);
pub const REFERENCE_EXPRESSION_RAW_MUT: KindId = KindId(372);
pub const REFERENCE_EXPRESSION_MUT: KindId = KindId(373);
pub const REFERENCE_EXPRESSION_BARE: KindId = KindId(374);
pub const IMPL_ITEM_POSITIVE_CLAUSE: KindId = KindId(375);
pub const IMPL_ITEM_NEGATIVE_CLAUSE: KindId = KindId(376);
pub const IMPL_ITEM_BODY: KindId = KindId(377);
pub const IMPL_ITEM_SEMI: KindId = KindId(378);
pub const VISIBILITY_MODIFIER_PUB_SCOPE_IN_PATH: KindId = KindId(379);
pub const VISIBILITY_MODIFIER_PUB_SCOPE: KindId = KindId(380);
pub const VISIBILITY_MODIFIER_PUB: KindId = KindId(381);
pub const FUNCTION_TYPE_TRAIT_FORM: KindId = KindId(382);
pub const FUNCTION_TYPE_FN_FORM: KindId = KindId(383);
pub const MOD_ITEM_EXTERNAL: KindId = KindId(384);
pub const MOD_ITEM_INLINE: KindId = KindId(385);
pub const OR_PATTERN_BINARY: KindId = KindId(386);
pub const OR_PATTERN_PREFIX: KindId = KindId(387);
pub const POINTER_TYPE_CONST: KindId = KindId(388);
pub const POINTER_TYPE_MUT: KindId = KindId(389);
pub const RANGE_EXPRESSION_BINARY: KindId = KindId(390);
pub const RANGE_EXPRESSION_POSTFIX: KindId = KindId(391);
pub const RANGE_EXPRESSION_PREFIX: KindId = KindId(392);
pub const EXPRESSION_STATEMENT_WITH_SEMI: KindId = KindId(393);
pub const FOREIGN_MOD_ITEM_SEMI: KindId = KindId(394);
pub const FOREIGN_MOD_ITEM_BODY: KindId = KindId(395);
pub const MATCH_ARM_WITH_COMMA: KindId = KindId(396);
pub const MATCH_ARM_BLOCK_ENDING: KindId = KindId(397);
pub const LINE_COMMENT_EXTRA_SLASHES: KindId = KindId(398);
pub const LINE_COMMENT_DOC_OUTER: KindId = KindId(399);
pub const LINE_COMMENT_DOC_INNER: KindId = KindId(400);
pub const BLOCK_COMMENT_DOC_OUTER: KindId = KindId(401);
pub const BLOCK_COMMENT_DOC_INNER: KindId = KindId(402);
pub const TOKEN_TREE_PATTERN_PAREN: KindId = KindId(403);
pub const TOKEN_TREE_PATTERN_BRACKET: KindId = KindId(404);
pub const TOKEN_TREE_PATTERN_BRACE: KindId = KindId(405);
pub const TOKEN_TREE_PAREN: KindId = KindId(406);
pub const TOKEN_TREE_BRACKET: KindId = KindId(407);
pub const TOKEN_TREE_BRACE: KindId = KindId(408);
pub const DELIM_TOKEN_TREE_PAREN: KindId = KindId(409);
pub const DELIM_TOKEN_TREE_BRACKET: KindId = KindId(410);
pub const DELIM_TOKEN_TREE_BRACE: KindId = KindId(411);
pub const FIELD_PATTERN_SHORTHAND: KindId = KindId(412);
pub const FIELD_PATTERN_NAMED: KindId = KindId(413);
pub const MACRO_DEFINITION_PAREN: KindId = KindId(414);
pub const MACRO_DEFINITION_BRACKET: KindId = KindId(415);
pub const MACRO_DEFINITION_BRACE: KindId = KindId(416);
pub const RANGE_PATTERN_PREFIX: KindId = KindId(417);
pub const RANGE_PATTERN_WITH_LEFT_WITH_RIGHT: KindId = KindId(418);
pub const RANGE_PATTERN_WITH_LEFT_BARE: KindId = KindId(419);
pub const RANGE_PATTERN_WITH_LEFT: KindId = KindId(420);
pub const STRUCT_ITEM_BRACE: KindId = KindId(421);
pub const STRUCT_ITEM_TUPLE: KindId = KindId(422);
pub const STRUCT_ITEM_UNIT: KindId = KindId(423);
pub const _WILDCARD_PATTERN: KindId = KindId(424);
pub const _ATTRIBUTED_FIELD_DECLARATION: KindId = KindId(425);
pub const _ATTRIBUTED_ENUM_VARIANT: KindId = KindId(426);
pub const _ATTRIBUTED_PARAMETER: KindId = KindId(427);
pub const _ATTRIBUTED_TYPE_PARAMETER: KindId = KindId(428);
pub const _ATTRIBUTED_ARGUMENT: KindId = KindId(429);
pub const _ATTRIBUTED_ORDERED_FIELD: KindId = KindId(430);
pub const _TYPE_ARGUMENT: KindId = KindId(431);
pub const _MATCH_BLOCK_ARMS: KindId = KindId(432);
pub const SOURCE_FILE_REPEAT1: KindId = KindId(433);
pub const TOKEN_REPETITION_PATTERN_REPEAT1: KindId = KindId(434);
pub const TOKEN_REPETITION_REPEAT1: KindId = KindId(435);
pub const DECLARATION_LIST_REPEAT1: KindId = KindId(436);
pub const FUNCTION_MODIFIERS_REPEAT1: KindId = KindId(437);
pub const TRAIT_BOUNDS_REPEAT1: KindId = KindId(438);
pub const TUPLE_EXPRESSION_REPEAT1: KindId = KindId(439);
pub const LAST_MATCH_ARM_REPEAT1: KindId = KindId(440);
pub const STRING_LITERAL_REPEAT1: KindId = KindId(441);
pub const MACRO_RULES_REPEAT1: KindId = KindId(442);
pub const ENUM_VARIANT_LIST_ELEMENTS_REPEAT1: KindId = KindId(443);
pub const FIELD_DECLARATION_LIST_ELEMENTS_REPEAT1: KindId = KindId(444);
pub const ORDERED_FIELD_DECLARATION_LIST_ELEMENTS_REPEAT1: KindId = KindId(445);
pub const WHERE_PREDICATES_REPEAT1: KindId = KindId(446);
pub const TYPE_PARAMETERS_ELEMENTS_REPEAT1: KindId = KindId(447);
pub const USE_CLAUSES_REPEAT1: KindId = KindId(448);
pub const PARAMETERS_ELEMENTS_REPEAT1: KindId = KindId(449);
pub const LIFETIMES_REPEAT1: KindId = KindId(450);
pub const USE_BOUNDS_ELEMENTS_REPEAT1: KindId = KindId(451);
pub const TYPE_ARGUMENTS_ELEMENTS_REPEAT1: KindId = KindId(452);
pub const ARGUMENTS_ELEMENTS_REPEAT1: KindId = KindId(453);
pub const FIELD_INITIALIZER_LIST_ELEMENTS_REPEAT1: KindId = KindId(454);
pub const _CLOSURE_PARAMETERS_OPTIONAL1_REPEAT1: KindId = KindId(455);
pub const TUPLE_PATTERN_ELEMENTS_REPEAT1: KindId = KindId(456);
pub const PATTERNS_REPEAT1: KindId = KindId(457);
pub const STRUCT_PATTERN_ELEMENTS_REPEAT1: KindId = KindId(458);
pub const _TUPLE_TYPE_ELEMENTS_REPEAT1: KindId = KindId(459);
pub const _TUPLE_EXPRESSION_ELEMENTS_REPEAT1: KindId = KindId(460);
pub const DELIM_TOKEN_TREE_PAREN_REPEAT1: KindId = KindId(461);
pub const _MATCH_BLOCK_ARMS_REPEAT1: KindId = KindId(462);
pub const _FIELD_IDENTIFIER: KindId = KindId(463);
pub const _SHORTHAND_FIELD_IDENTIFIER: KindId = KindId(465);
pub const _TYPE_IDENTIFIER: KindId = KindId(466);
pub const ERROR: KindId = KindId(65535);
const _: () = assert!(ERROR.0 == KindId::ERROR.0);

/// Map a `KindId` back to its grammar kind string for diagnostics.
/// Returns `"<unknown>"` for ids not in this grammar's symbol table.
pub fn kind_name_from_id(id: KindId) -> &'static str {
    match id.0 {
        1 => "identifier", // "identifier"
        2 => ";", // "semi"
        3 => "=>", // "eq_gt"
        4 => ":", // "colon"
        5 => "$", // "dollar"
        6 => "(", // "lparen"
        7 => ")", // "rparen"
        8 => "token_repetition_pattern_token1", // "token_repetition_pattern_token1"
        9 => "+", // "plus"
        10 => "*", // "star"
        11 => "?", // "qmark"
        12 => "block", // "block_keyword"
        13 => "expr", // "expr_keyword"
        14 => "expr_2021", // "expr_2021_keyword"
        15 => "ident", // "ident_keyword"
        16 => "item", // "item_keyword"
        17 => "lifetime", // "lifetime_keyword"
        18 => "literal", // "literal_keyword"
        19 => "meta", // "meta_keyword"
        20 => "pat", // "pat_keyword"
        21 => "pat_param", // "pat_param_keyword"
        22 => "path", // "path_keyword"
        23 => "stmt", // "stmt_keyword"
        24 => "tt", // "tt_keyword"
        25 => "ty", // "ty_keyword"
        26 => "vis", // "vis_keyword"
        27 => "#", // "pound"
        28 => "[", // "lbrack"
        29 => "]", // "rbrack"
        30 => "!", // "bang"
        31 => "{", // "lbrace"
        32 => "}", // "rbrace"
        33 => "union", // "union_keyword"
        34 => "enum", // "enum_keyword"
        35 => "extern", // "extern_keyword"
        36 => "const", // "const_keyword"
        37 => "static", // "static_keyword"
        38 => "type", // "type_keyword"
        39 => "=", // "eq"
        40 => "fn", // "fn_keyword"
        41 => "where", // "where_keyword"
        42 => "trait", // "trait_keyword"
        43 => "for", // "for_keyword"
        44 => "<", // "lt"
        45 => ">", // "gt"
        46 => "let", // "let_keyword"
        47 => "use", // "use_keyword"
        48 => "::", // "colon_colon"
        49 => "as", // "as_keyword"
        50 => "...", // "dot_dot_dot"
        51 => "'", // "squote"
        52 => "default", // "default_keyword"
        53 => "gen", // "gen_keyword"
        54 => "<", // "lt2"
        55 => "&", // "amp"
        56 => "impl", // "impl_keyword"
        57 => "dyn", // "dyn_keyword"
        58 => "mutable_specifier", // "mutable_specifier"
        59 => "u8", // "u8_keyword"
        60 => "i8", // "i8_keyword"
        61 => "u16", // "u16_keyword"
        62 => "i16", // "i16_keyword"
        63 => "u32", // "u32_keyword"
        64 => "i32", // "i32_keyword"
        65 => "u64", // "u64_keyword"
        66 => "i64", // "i64_keyword"
        67 => "u128", // "u128_keyword"
        68 => "i128", // "i128_keyword"
        69 => "isize", // "isize_keyword"
        70 => "usize", // "usize_keyword"
        71 => "f32", // "f32_keyword"
        72 => "f64", // "f64_keyword"
        73 => "bool", // "bool_keyword"
        74 => "str", // "str_keyword"
        75 => "char", // "char_keyword"
        76 => "-", // "dash"
        77 => "&&", // "amp_amp"
        78 => "||", // "pipe_pipe"
        79 => "|", // "pipe"
        80 => "^", // "caret"
        81 => "==", // "eq_eq"
        82 => "!=", // "bang_eq"
        83 => "<=", // "lt_eq"
        84 => ">=", // "gt_eq"
        85 => "<<", // "lt_lt"
        86 => ">>", // "gt_gt"
        87 => "/", // "slash"
        88 => "%", // "percent"
        89 => "+=", // "plus_eq"
        90 => "-=", // "dash_eq"
        91 => "*=", // "star_eq"
        92 => "/=", // "slash_eq"
        93 => "%=", // "percent_eq"
        94 => "&=", // "amp_eq"
        95 => "|=", // "pipe_eq"
        96 => "^=", // "caret_eq"
        97 => "<<=", // "lt_lt_eq"
        98 => ">>=", // "gt_gt_eq"
        99 => "return", // "return_keyword"
        100 => "yield", // "yield_keyword"
        101 => "..", // "dot_dot"
        102 => "if", // "if_keyword"
        103 => "else", // "else_keyword"
        104 => "match", // "match_keyword"
        105 => "while", // "while_keyword"
        106 => "loop", // "loop_keyword"
        107 => "in", // "in_keyword"
        108 => "break", // "break_keyword"
        109 => "continue", // "continue_keyword"
        110 => ".", // "dot"
        111 => "await", // "await_keyword"
        112 => "unsafe", // "unsafe_keyword"
        113 => "async", // "async_keyword"
        114 => "try", // "try_keyword"
        115 => "ref", // "ref_keyword"
        116 => "@", // "at"
        117 => "\"", // "dquote"
        118 => "true", // "true_keyword"
        119 => "false", // "false_keyword"
        120 => "//", // "slash_slash"
        121 => "!", // "bang2"
        122 => "/", // "slash2"
        123 => "/*", // "slash_star"
        124 => "*/", // "star_slash"
        125 => "shebang", // "shebang"
        126 => "self", // "self"
        127 => "super", // "super"
        128 => "crate", // "crate"
        129 => "metavariable", // "metavariable"
        130 => "move", // "move_keyword"
        131 => ",", // "comma"
        132 => "->", // "dash_gt"
        133 => "_", // "underscore"
        134 => "..=", // "dot_dot_eq"
        135 => "mod", // "mod_keyword"
        136 => "pub", // "pub_keyword"
        137 => "struct", // "struct_keyword"
        138 => "integer_literal_decimal", // "integer_literal_decimal"
        139 => "integer_literal_hex", // "integer_literal_hex"
        140 => "integer_literal_binary", // "integer_literal_binary"
        141 => "integer_literal_octal", // "integer_literal_octal"
        142 => "char_literal_plain", // "char_literal_plain"
        143 => "char_literal_empty", // "char_literal_empty"
        144 => "char_literal_escaped_simple", // "char_literal_escaped_simple"
        145 => "char_literal_escaped_unicode_fixed", // "char_literal_escaped_unicode_fixed"
        146 => "char_literal_escaped_unicode_braced", // "char_literal_escaped_unicode_braced"
        147 => "char_literal_escaped_hex", // "char_literal_escaped_hex"
        148 => "escape_sequence_simple", // "escape_sequence_simple"
        149 => "escape_sequence_unicode_fixed", // "escape_sequence_unicode_fixed"
        150 => "escape_sequence_unicode_braced", // "escape_sequence_unicode_braced"
        151 => "escape_sequence_hex", // "escape_sequence_hex"
        152 => "raw", // "raw_keyword"
        153 => "string_open", // "_string_open"
        154 => "line_comment_extra_slashes_token1", // "line_comment_extra_slashes_token1"
        155 => "line_comment_extra_slashes_token2", // "line_comment_extra_slashes_token2"
        156 => "line_comment_regular", // "line_comment_regular"
        157 => "macro_rules!", // "macro_rules_bang"
        158 => "string_content", // "string_content"
        159 => "raw_string_literal_start", // "_raw_string_literal_start"
        160 => "string_content", // "raw_string_literal_content"
        161 => "raw_string_literal_end", // "_raw_string_literal_end"
        162 => "float_literal", // "float_literal"
        163 => "outer_doc_comment_marker", // "_outer_block_doc_comment_marker"
        164 => "inner_doc_comment_marker", // "_inner_block_doc_comment_marker"
        165 => "_block_comment_content", // "_block_comment_content"
        166 => "doc_comment", // "_line_doc_content"
        167 => "_error_sentinel", // "_error_sentinel"
        168 => "_tight", // "_tight"
        169 => "_space", // "_space"
        170 => "_tab", // "_tab"
        171 => "_newline", // "_newline"
        172 => "_blankline", // "_blankline"
        173 => "_double_blankline", // "_double_blankline"
        174 => "_indent", // "_indent"
        175 => "_dedent", // "_dedent"
        176 => "source_file", // "source_file"
        177 => "_statement", // "_statement"
        178 => "empty_statement", // "empty_statement"
        179 => "expression_statement", // "expression_statement"
        180 => "macro_definition", // "macro_definition"
        181 => "macro_rule", // "macro_rule"
        182 => "_token_pattern", // "_token_pattern"
        183 => "token_tree_pattern", // "token_tree_pattern"
        184 => "token_binding_pattern", // "token_binding_pattern"
        185 => "token_repetition_pattern", // "token_repetition_pattern"
        186 => "fragment_specifier", // "fragment_specifier"
        187 => "token_tree", // "token_tree"
        188 => "token_repetition", // "token_repetition"
        189 => "non_special_token", // "_non_special_token"
        190 => "attribute_item", // "attribute_item"
        191 => "inner_attribute_item", // "inner_attribute_item"
        192 => "attribute", // "attribute"
        193 => "mod_item", // "mod_item"
        194 => "foreign_mod_item", // "foreign_mod_item"
        195 => "declaration_list", // "declaration_list"
        196 => "struct_item", // "struct_item"
        197 => "union_item", // "union_item"
        198 => "enum_item", // "enum_item"
        199 => "enum_variant_list", // "enum_variant_list"
        200 => "enum_variant", // "enum_variant"
        201 => "field_declaration_list", // "field_declaration_list"
        202 => "field_declaration", // "field_declaration"
        203 => "ordered_field_declaration_list", // "ordered_field_declaration_list"
        204 => "extern_crate_declaration", // "extern_crate_declaration"
        205 => "const_item", // "const_item"
        206 => "static_item", // "static_item"
        207 => "type_item", // "type_item"
        208 => "function_item", // "function_item"
        209 => "function_signature_item", // "function_signature_item"
        210 => "function_modifiers", // "function_modifiers"
        211 => "where_clause", // "where_clause"
        212 => "where_predicate", // "where_predicate"
        213 => "impl_item", // "impl_item"
        214 => "trait_item", // "trait_item"
        215 => "associated_type", // "associated_type"
        216 => "trait_bounds", // "trait_bounds"
        217 => "higher_ranked_trait_bound", // "higher_ranked_trait_bound"
        218 => "removed_trait_bound", // "removed_trait_bound"
        219 => "type_parameters", // "type_parameters"
        220 => "const_parameter", // "const_parameter"
        221 => "type_parameter", // "type_parameter"
        222 => "lifetime_parameter", // "lifetime_parameter"
        223 => "let_declaration", // "let_declaration"
        224 => "use_declaration", // "use_declaration"
        225 => "_use_clause", // "_use_clause"
        226 => "scoped_use_list", // "scoped_use_list"
        227 => "use_list", // "use_list"
        228 => "use_as_clause", // "use_as_clause"
        229 => "use_wildcard", // "use_wildcard"
        230 => "parameters", // "parameters"
        231 => "self_parameter", // "self_parameter"
        232 => "variadic_parameter", // "variadic_parameter"
        233 => "parameter", // "parameter"
        234 => "extern_modifier", // "extern_modifier"
        235 => "visibility_modifier", // "visibility_modifier"
        236 => "_type", // "_type"
        237 => "bracketed_type", // "bracketed_type"
        238 => "qualified_type", // "qualified_type"
        239 => "lifetime", // "lifetime"
        240 => "array_type", // "array_type"
        241 => "for_lifetimes", // "for_lifetimes"
        242 => "function_type", // "function_type"
        243 => "tuple_type", // "tuple_type"
        244 => "unit_type", // "unit_type"
        245 => "generic_function", // "generic_function"
        246 => "generic_type", // "generic_type"
        247 => "generic_type_with_turbofish", // "generic_type_with_turbofish"
        248 => "bounded_type", // "bounded_type"
        249 => "use_bounds", // "use_bounds"
        250 => "type_arguments", // "type_arguments"
        251 => "type_binding", // "type_binding"
        252 => "reference_type", // "reference_type"
        253 => "pointer_type", // "pointer_type"
        254 => "never_type", // "never_type"
        255 => "abstract_type", // "abstract_type"
        256 => "dynamic_type", // "dynamic_type"
        257 => "_expression_except_range", // "_expression_except_range"
        258 => "_expression", // "_expression"
        259 => "macro_invocation", // "macro_invocation"
        260 => "delim_token_tree", // "delim_token_tree"
        261 => "_delim_tokens", // "_delim_tokens"
        262 => "_non_delim_token", // "_non_delim_token"
        263 => "scoped_identifier", // "scoped_identifier"
        264 => "scoped_type_identifier_in_expression_position", // "scoped_type_identifier_in_expression_position"
        265 => "scoped_type_identifier", // "scoped_type_identifier"
        266 => "range_expression", // "range_expression"
        267 => "unary_expression", // "unary_expression"
        268 => "try_expression", // "try_expression"
        269 => "reference_expression", // "reference_expression"
        270 => "binary_expression", // "binary_expression"
        271 => "assignment_expression", // "assignment_expression"
        272 => "compound_assignment_expr", // "compound_assignment_expr"
        273 => "type_cast_expression", // "type_cast_expression"
        274 => "return_expression", // "return_expression"
        275 => "yield_expression", // "yield_expression"
        276 => "call_expression", // "call_expression"
        277 => "arguments", // "arguments"
        278 => "array_expression", // "array_expression"
        279 => "parenthesized_expression", // "parenthesized_expression"
        280 => "tuple_expression", // "tuple_expression"
        281 => "unit_expression", // "unit_expression"
        282 => "struct_expression", // "struct_expression"
        283 => "field_initializer_list", // "field_initializer_list"
        284 => "shorthand_field_initializer", // "shorthand_field_initializer"
        285 => "field_initializer", // "field_initializer"
        286 => "base_field_initializer", // "base_field_initializer"
        287 => "if_expression", // "if_expression"
        288 => "let_condition", // "let_condition"
        289 => "_let_chain", // "_let_chain"
        464 => "let_chain", // "_let_chain"
        290 => "_condition", // "_condition"
        291 => "else_clause", // "else_clause"
        292 => "match_expression", // "match_expression"
        293 => "match_block", // "match_block"
        294 => "match_arm", // "match_arm"
        295 => "last_match_arm", // "last_match_arm"
        296 => "match_pattern", // "match_pattern"
        297 => "while_expression", // "while_expression"
        298 => "loop_expression", // "loop_expression"
        299 => "for_expression", // "for_expression"
        300 => "const_block", // "const_block"
        301 => "closure_expression", // "closure_expression"
        302 => "closure_parameters", // "closure_parameters"
        303 => "label", // "label"
        304 => "break_expression", // "break_expression"
        305 => "continue_expression", // "continue_expression"
        306 => "index_expression", // "index_expression"
        307 => "await_expression", // "await_expression"
        308 => "field_expression", // "field_expression"
        309 => "unsafe_block", // "unsafe_block"
        310 => "async_block", // "async_block"
        311 => "gen_block", // "gen_block"
        312 => "try_block", // "try_block"
        313 => "block", // "block"
        314 => "_pattern", // "_pattern"
        315 => "generic_pattern", // "generic_pattern"
        316 => "tuple_pattern", // "tuple_pattern"
        317 => "slice_pattern", // "slice_pattern"
        318 => "tuple_struct_pattern", // "tuple_struct_pattern"
        319 => "struct_pattern", // "struct_pattern"
        320 => "field_pattern", // "field_pattern"
        321 => "remaining_field_pattern", // "remaining_field_pattern"
        322 => "mut_pattern", // "mut_pattern"
        323 => "range_pattern", // "range_pattern"
        324 => "ref_pattern", // "ref_pattern"
        325 => "captured_pattern", // "captured_pattern"
        326 => "reference_pattern", // "reference_pattern"
        327 => "or_pattern", // "or_pattern"
        328 => "_literal", // "_literal"
        329 => "_literal_pattern", // "_literal_pattern"
        330 => "negative_literal", // "negative_literal"
        331 => "integer_literal", // "integer_literal"
        332 => "string_literal", // "string_literal"
        333 => "raw_string_literal", // "raw_string_literal"
        334 => "char_literal", // "char_literal"
        335 => "escape_sequence", // "escape_sequence"
        336 => "boolean_literal", // "boolean_literal"
        337 => "line_comment", // "line_comment"
        338 => "inner_line_doc_comment_marker", // "_inner_line_doc_comment_marker"
        339 => "outer_line_doc_comment_marker", // "_outer_line_doc_comment_marker"
        340 => "block_comment", // "block_comment"
        341 => "primitive_type", // "_primitive_type"
        342 => "macro_rules", // "macro_rules"
        343 => "enum_variant_list_elements", // "enum_variant_list_elements"
        344 => "field_declaration_list_elements", // "field_declaration_list_elements"
        345 => "ordered_field_declaration_list_elements", // "ordered_field_declaration_list_elements"
        346 => "where_predicates", // "where_predicates"
        347 => "type_parameters_elements", // "type_parameters_elements"
        348 => "use_clauses", // "use_clauses"
        349 => "parameters_elements", // "parameters_elements"
        350 => "lifetimes", // "lifetimes"
        351 => "use_bounds_elements", // "use_bounds_elements"
        352 => "type_arguments_elements", // "type_arguments_elements"
        353 => "arguments_elements", // "arguments_elements"
        354 => "field_initializer_list_elements", // "field_initializer_list_elements"
        355 => "tuple_pattern_elements", // "tuple_pattern_elements"
        356 => "patterns", // "patterns"
        357 => "struct_pattern_elements", // "struct_pattern_elements"
        358 => "use_wildcard_group", // "use_wildcard_group"
        359 => "tuple_type_elements", // "_tuple_type_elements"
        360 => "tuple_expression_elements", // "_tuple_expression_elements"
        361 => "token_tree_punctuation", // "_token_tree_punctuation"
        362 => "_token_keywords", // "_token_keywords"
        363 => "range_expression_bare", // "_range_expression_bare"
        364 => "_impl_item_unsafe_marker", // "_impl_item_unsafe_marker"
        365 => "char_literal_escaped", // "char_literal_escaped"
        366 => "array_expression_semi", // "array_expression_semi"
        367 => "array_expression_list", // "array_expression_list"
        368 => "attribute_input", // "attribute_input"
        369 => "closure_expression_block", // "closure_expression_block"
        370 => "closure_expression_expr", // "closure_expression_expr"
        371 => "reference_expression_raw_const", // "reference_expression_raw_const"
        372 => "reference_expression_raw_mut", // "reference_expression_raw_mut"
        373 => "reference_expression_mut", // "reference_expression_mut"
        374 => "reference_expression_bare", // "reference_expression_bare"
        375 => "impl_item_positive_clause", // "impl_item_positive_clause"
        376 => "impl_item_negative_clause", // "impl_item_negative_clause"
        377 => "impl_item_body", // "impl_item_body"
        378 => "impl_item_semi", // "impl_item_semi"
        379 => "visibility_modifier_pub_scope_in_path", // "visibility_modifier_pub_scope_in_path"
        380 => "visibility_modifier_pub_scope", // "visibility_modifier_pub_scope"
        381 => "visibility_modifier_pub", // "visibility_modifier_pub"
        382 => "function_type_trait_form", // "function_type_trait_form"
        383 => "function_type_fn_form", // "function_type_fn_form"
        384 => "mod_item_external", // "mod_item_external"
        385 => "mod_item_inline", // "mod_item_inline"
        386 => "or_pattern_binary", // "or_pattern_binary"
        387 => "or_pattern_prefix", // "or_pattern_prefix"
        388 => "pointer_type_const", // "pointer_type_const"
        389 => "pointer_type_mut", // "pointer_type_mut"
        390 => "range_expression_binary", // "range_expression_binary"
        391 => "range_expression_postfix", // "range_expression_postfix"
        392 => "range_expression_prefix", // "range_expression_prefix"
        393 => "expression_statement_with_semi", // "expression_statement_with_semi"
        394 => "foreign_mod_item_semi", // "foreign_mod_item_semi"
        395 => "foreign_mod_item_body", // "foreign_mod_item_body"
        396 => "match_arm_with_comma", // "match_arm_with_comma"
        397 => "match_arm_block_ending", // "match_arm_block_ending"
        398 => "line_comment_extra_slashes", // "line_comment_extra_slashes"
        399 => "line_comment_doc_outer", // "line_comment_doc_outer"
        400 => "line_comment_doc_inner", // "line_comment_doc_inner"
        401 => "block_comment_doc_outer", // "block_comment_doc_outer"
        402 => "block_comment_doc_inner", // "block_comment_doc_inner"
        403 => "token_tree_pattern_paren", // "token_tree_pattern_paren"
        404 => "token_tree_pattern_bracket", // "token_tree_pattern_bracket"
        405 => "token_tree_pattern_brace", // "token_tree_pattern_brace"
        406 => "token_tree_paren", // "token_tree_paren"
        407 => "token_tree_bracket", // "token_tree_bracket"
        408 => "token_tree_brace", // "token_tree_brace"
        409 => "delim_token_tree_paren", // "delim_token_tree_paren"
        410 => "delim_token_tree_bracket", // "delim_token_tree_bracket"
        411 => "delim_token_tree_brace", // "delim_token_tree_brace"
        412 => "field_pattern_shorthand", // "field_pattern_shorthand"
        413 => "field_pattern_named", // "field_pattern_named"
        414 => "macro_definition_paren", // "macro_definition_paren"
        415 => "macro_definition_bracket", // "macro_definition_bracket"
        416 => "macro_definition_brace", // "macro_definition_brace"
        417 => "range_pattern_prefix", // "range_pattern_prefix"
        418 => "range_pattern_with_left_with_right", // "range_pattern_with_left_with_right"
        419 => "range_pattern_with_left_bare", // "range_pattern_with_left_bare"
        420 => "range_pattern_with_left", // "range_pattern_with_left"
        421 => "struct_item_brace", // "struct_item_brace"
        422 => "struct_item_tuple", // "struct_item_tuple"
        423 => "struct_item_unit", // "struct_item_unit"
        424 => "wildcard_pattern", // "_wildcard_pattern"
        425 => "attributed_field_declaration", // "_attributed_field_declaration"
        426 => "attributed_enum_variant", // "_attributed_enum_variant"
        427 => "attributed_parameter", // "_attributed_parameter"
        428 => "attributed_type_parameter", // "_attributed_type_parameter"
        429 => "attributed_argument", // "_attributed_argument"
        430 => "attributed_ordered_field", // "_attributed_ordered_field"
        431 => "type_argument", // "_type_argument"
        432 => "match_block_arms", // "_match_block_arms"
        433 => "source_file_repeat1", // "source_file_repeat1"
        434 => "token_repetition_pattern_repeat1", // "token_repetition_pattern_repeat1"
        435 => "token_repetition_repeat1", // "token_repetition_repeat1"
        436 => "declaration_list_repeat1", // "declaration_list_repeat1"
        437 => "function_modifiers_repeat1", // "function_modifiers_repeat1"
        438 => "trait_bounds_repeat1", // "trait_bounds_repeat1"
        439 => "tuple_expression_repeat1", // "tuple_expression_repeat1"
        440 => "last_match_arm_repeat1", // "last_match_arm_repeat1"
        441 => "string_literal_repeat1", // "string_literal_repeat1"
        442 => "macro_rules_repeat1", // "macro_rules_repeat1"
        443 => "enum_variant_list_elements_repeat1", // "enum_variant_list_elements_repeat1"
        444 => "field_declaration_list_elements_repeat1", // "field_declaration_list_elements_repeat1"
        445 => "ordered_field_declaration_list_elements_repeat1", // "ordered_field_declaration_list_elements_repeat1"
        446 => "where_predicates_repeat1", // "where_predicates_repeat1"
        447 => "type_parameters_elements_repeat1", // "type_parameters_elements_repeat1"
        448 => "use_clauses_repeat1", // "use_clauses_repeat1"
        449 => "parameters_elements_repeat1", // "parameters_elements_repeat1"
        450 => "lifetimes_repeat1", // "lifetimes_repeat1"
        451 => "use_bounds_elements_repeat1", // "use_bounds_elements_repeat1"
        452 => "type_arguments_elements_repeat1", // "type_arguments_elements_repeat1"
        453 => "arguments_elements_repeat1", // "arguments_elements_repeat1"
        454 => "field_initializer_list_elements_repeat1", // "field_initializer_list_elements_repeat1"
        455 => "_closure_parameters_optional1_repeat1", // "_closure_parameters_optional1_repeat1"
        456 => "tuple_pattern_elements_repeat1", // "tuple_pattern_elements_repeat1"
        457 => "patterns_repeat1", // "patterns_repeat1"
        458 => "struct_pattern_elements_repeat1", // "struct_pattern_elements_repeat1"
        459 => "_tuple_type_elements_repeat1", // "_tuple_type_elements_repeat1"
        460 => "_tuple_expression_elements_repeat1", // "_tuple_expression_elements_repeat1"
        461 => "delim_token_tree_paren_repeat1", // "delim_token_tree_paren_repeat1"
        462 => "_match_block_arms_repeat1", // "_match_block_arms_repeat1"
        463 => "field_identifier", // "_field_identifier"
        465 => "shorthand_field_identifier", // "_shorthand_field_identifier"
        466 => "type_identifier", // "_type_identifier"
        65535 => "ERROR", // "ERROR"
        _ => "<unknown>",
    }
}

/// Whether the reader captures a named node of this kind as text: its
/// template renders from that text, so the text is the node's content —
/// free text for a pattern kind, the literal it holds for an enum kind.
pub fn is_text_kind(kind: KindId) -> bool {
    matches!(kind.0, 1 | 125 | 129 | 138 | 139 | 140 | 141 | 142 | 143 | 144 | 145 | 146 | 147 | 148 | 149 | 150 | 151 | 153 | 156 | 158 | 159 | 160 | 161 | 162 | 165 | 166 | 167 | 186 | 336 | 341 | 361 | 362 | 398)
}

/// Whether this parse kind id is an alias envelope: the reader stamps the
/// grammar symbol beside it when the node is the storage node shown under
/// the alias, so the wrap layer can seat it as the envelope's content.
pub fn is_alias_envelope(kind: KindId) -> bool {
    matches!(kind.0, 463 | 465 | 466)
}

/// The model slot a child is stored under where its name differs from the
/// parser's key: a field-tagged child by (parent kind id, field), a named
/// child without a field by (parent kind id, the child's kind name).
/// `None` keeps the parser's key.
pub fn wire_slot(parent: KindId, field: Option<&str>, child: &str) -> Option<&'static str> {
    match (parent.0, field, child) {
        (179, None, "async_block") => Some("content"),
        (179, None, "block") => Some("content"),
        (179, None, "const_block") => Some("content"),
        (179, None, "expression_statement_with_semi") => Some("content"),
        (179, None, "for_expression") => Some("content"),
        (179, None, "gen_block") => Some("content"),
        (179, None, "if_expression") => Some("content"),
        (179, None, "loop_expression") => Some("content"),
        (179, None, "match_expression") => Some("content"),
        (179, None, "try_block") => Some("content"),
        (179, None, "unsafe_block") => Some("content"),
        (179, None, "while_expression") => Some("content"),
        (189, None, "boolean_literal") => Some("content"),
        (189, None, "char_literal_empty") => Some("content"),
        (189, None, "char_literal_escaped_hex") => Some("content"),
        (189, None, "char_literal_escaped_simple") => Some("content"),
        (189, None, "char_literal_escaped_unicode_braced") => Some("content"),
        (189, None, "char_literal_escaped_unicode_fixed") => Some("content"),
        (189, None, "char_literal_plain") => Some("content"),
        (189, None, "crate") => Some("content"),
        (189, None, "float_literal") => Some("content"),
        (189, None, "identifier") => Some("content"),
        (189, None, "integer_literal_binary") => Some("content"),
        (189, None, "integer_literal_decimal") => Some("content"),
        (189, None, "integer_literal_hex") => Some("content"),
        (189, None, "integer_literal_octal") => Some("content"),
        (189, None, "mutable_specifier") => Some("content"),
        (189, None, "primitive_type") => Some("content"),
        (189, None, "raw_string_literal") => Some("content"),
        (189, None, "self") => Some("content"),
        (189, None, "string_literal") => Some("content"),
        (189, None, "super") => Some("content"),
        (189, None, "token_keywords") => Some("content"),
        (189, None, "token_tree_punctuation") => Some("content"),
        (235, None, "crate") => Some("content"),
        (235, None, "visibility_modifier_pub") => Some("content"),
        (242, None, "function_type_fn_form") => Some("content"),
        (242, None, "function_type_trait_form") => Some("content"),
        (266, None, "range_expression_bare") => Some("content"),
        (266, None, "range_expression_binary") => Some("content"),
        (266, None, "range_expression_postfix") => Some("content"),
        (266, None, "range_expression_prefix") => Some("content"),
        (304, None, "array_expression_list") => Some("expression"),
        (304, None, "array_expression_semi") => Some("expression"),
        (304, None, "assignment_expression") => Some("expression"),
        (304, None, "async_block") => Some("expression"),
        (304, None, "await_expression") => Some("expression"),
        (304, None, "binary_expression") => Some("expression"),
        (304, None, "block") => Some("expression"),
        (304, None, "bool_keyword") => Some("expression"),
        (304, None, "boolean_literal") => Some("expression"),
        (304, None, "break_expression") => Some("expression"),
        (304, None, "call_expression") => Some("expression"),
        (304, None, "char_keyword") => Some("expression"),
        (304, None, "char_literal_empty") => Some("expression"),
        (304, None, "char_literal_escaped_hex") => Some("expression"),
        (304, None, "char_literal_escaped_simple") => Some("expression"),
        (304, None, "char_literal_escaped_unicode_braced") => Some("expression"),
        (304, None, "char_literal_escaped_unicode_fixed") => Some("expression"),
        (304, None, "char_literal_plain") => Some("expression"),
        (304, None, "closure_expression_block") => Some("expression"),
        (304, None, "closure_expression_expr") => Some("expression"),
        (304, None, "compound_assignment_expr") => Some("expression"),
        (304, None, "const_block") => Some("expression"),
        (304, None, "continue_expression") => Some("expression"),
        (304, None, "default_keyword") => Some("expression"),
        (304, None, "f32_keyword") => Some("expression"),
        (304, None, "f64_keyword") => Some("expression"),
        (304, None, "field_expression") => Some("expression"),
        (304, None, "float_literal") => Some("expression"),
        (304, None, "for_expression") => Some("expression"),
        (304, None, "gen_block") => Some("expression"),
        (304, None, "gen_keyword") => Some("expression"),
        (304, None, "generic_function") => Some("expression"),
        (304, None, "i128_keyword") => Some("expression"),
        (304, None, "i16_keyword") => Some("expression"),
        (304, None, "i32_keyword") => Some("expression"),
        (304, None, "i64_keyword") => Some("expression"),
        (304, None, "i8_keyword") => Some("expression"),
        (304, None, "identifier") => Some("expression"),
        (304, None, "if_expression") => Some("expression"),
        (304, None, "index_expression") => Some("expression"),
        (304, None, "integer_literal_binary") => Some("expression"),
        (304, None, "integer_literal_decimal") => Some("expression"),
        (304, None, "integer_literal_hex") => Some("expression"),
        (304, None, "integer_literal_octal") => Some("expression"),
        (304, None, "isize_keyword") => Some("expression"),
        (304, None, "loop_expression") => Some("expression"),
        (304, None, "macro_invocation") => Some("expression"),
        (304, None, "match_expression") => Some("expression"),
        (304, None, "metavariable") => Some("expression"),
        (304, None, "parenthesized_expression") => Some("expression"),
        (304, None, "range_expression") => Some("expression"),
        (304, None, "raw_string_literal") => Some("expression"),
        (304, None, "reference_expression_bare") => Some("expression"),
        (304, None, "reference_expression_mut") => Some("expression"),
        (304, None, "reference_expression_raw_const") => Some("expression"),
        (304, None, "reference_expression_raw_mut") => Some("expression"),
        (304, None, "return_expression") => Some("expression"),
        (304, None, "scoped_identifier") => Some("expression"),
        (304, None, "self") => Some("expression"),
        (304, None, "str_keyword") => Some("expression"),
        (304, None, "string_literal") => Some("expression"),
        (304, None, "struct_expression") => Some("expression"),
        (304, None, "try_block") => Some("expression"),
        (304, None, "try_expression") => Some("expression"),
        (304, None, "tuple_expression") => Some("expression"),
        (304, None, "type_cast_expression") => Some("expression"),
        (304, None, "u128_keyword") => Some("expression"),
        (304, None, "u16_keyword") => Some("expression"),
        (304, None, "u32_keyword") => Some("expression"),
        (304, None, "u64_keyword") => Some("expression"),
        (304, None, "u8_keyword") => Some("expression"),
        (304, None, "unary_expression") => Some("expression"),
        (304, None, "union_keyword") => Some("expression"),
        (304, None, "unit_expression") => Some("expression"),
        (304, None, "unsafe_block") => Some("expression"),
        (304, None, "usize_keyword") => Some("expression"),
        (304, None, "while_expression") => Some("expression"),
        (304, None, "yield_expression") => Some("expression"),
        (337, None, "line_comment_doc_inner") => Some("content"),
        (337, None, "line_comment_doc_outer") => Some("content"),
        (337, None, "line_comment_extra_slashes") => Some("content"),
        (337, None, "line_comment_regular") => Some("content"),
        (340, None, "block_comment_content") => Some("content"),
        (340, None, "block_comment_doc_inner") => Some("content"),
        (340, None, "block_comment_doc_outer") => Some("content"),
        (379, None, "bool_keyword") => Some("path"),
        (379, None, "char_keyword") => Some("path"),
        (379, None, "crate") => Some("path"),
        (379, None, "default_keyword") => Some("path"),
        (379, None, "f32_keyword") => Some("path"),
        (379, None, "f64_keyword") => Some("path"),
        (379, None, "gen_keyword") => Some("path"),
        (379, None, "i128_keyword") => Some("path"),
        (379, None, "i16_keyword") => Some("path"),
        (379, None, "i32_keyword") => Some("path"),
        (379, None, "i64_keyword") => Some("path"),
        (379, None, "i8_keyword") => Some("path"),
        (379, None, "identifier") => Some("path"),
        (379, None, "isize_keyword") => Some("path"),
        (379, None, "metavariable") => Some("path"),
        (379, None, "scoped_identifier") => Some("path"),
        (379, None, "self") => Some("path"),
        (379, None, "str_keyword") => Some("path"),
        (379, None, "super") => Some("path"),
        (379, None, "u128_keyword") => Some("path"),
        (379, None, "u16_keyword") => Some("path"),
        (379, None, "u32_keyword") => Some("path"),
        (379, None, "u64_keyword") => Some("path"),
        (379, None, "u8_keyword") => Some("path"),
        (379, None, "union_keyword") => Some("path"),
        (379, None, "usize_keyword") => Some("path"),
        (380, None, "crate") => Some("content"),
        (380, None, "self") => Some("content"),
        (380, None, "super") => Some("content"),
        (380, None, "visibility_modifier_pub_scope_in_path") => Some("content"),
        (417, None, "dot_dot") => Some("content"),
        (417, None, "dot_dot_eq") => Some("content"),
        (418, None, "dot_dot") => Some("content"),
        (418, None, "dot_dot_dot") => Some("content"),
        (418, None, "dot_dot_eq") => Some("content"),
        (420, None, "range_pattern_with_left_bare") => Some("content"),
        (420, None, "range_pattern_with_left_with_right") => Some("content"),
        (427, None, "abstract_type") => Some("content"),
        (427, None, "array_type") => Some("content"),
        (427, None, "bounded_type") => Some("content"),
        (427, None, "dynamic_type") => Some("content"),
        (427, None, "function_type") => Some("content"),
        (427, None, "generic_type") => Some("content"),
        (427, None, "macro_invocation") => Some("content"),
        (427, None, "metavariable") => Some("content"),
        (427, None, "never_type") => Some("content"),
        (427, None, "parameter") => Some("content"),
        (427, None, "pointer_type_const") => Some("content"),
        (427, None, "pointer_type_mut") => Some("content"),
        (427, None, "primitive_type") => Some("content"),
        (427, None, "reference_type") => Some("content"),
        (427, None, "removed_trait_bound") => Some("content"),
        (427, None, "scoped_type_identifier") => Some("content"),
        (427, None, "self_parameter") => Some("content"),
        (427, None, "tuple_type") => Some("content"),
        (427, None, "type_identifier") => Some("content"),
        (427, None, "underscore") => Some("content"),
        (427, None, "unit_type") => Some("content"),
        (427, None, "variadic_parameter") => Some("content"),
        (428, None, "const_parameter") => Some("content"),
        (428, None, "lifetime_parameter") => Some("content"),
        (428, None, "metavariable") => Some("content"),
        (428, None, "type_parameter") => Some("content"),
        (429, None, "array_expression_list") => Some("expression"),
        (429, None, "array_expression_semi") => Some("expression"),
        (429, None, "assignment_expression") => Some("expression"),
        (429, None, "async_block") => Some("expression"),
        (429, None, "await_expression") => Some("expression"),
        (429, None, "binary_expression") => Some("expression"),
        (429, None, "block") => Some("expression"),
        (429, None, "bool_keyword") => Some("expression"),
        (429, None, "boolean_literal") => Some("expression"),
        (429, None, "break_expression") => Some("expression"),
        (429, None, "call_expression") => Some("expression"),
        (429, None, "char_keyword") => Some("expression"),
        (429, None, "char_literal_empty") => Some("expression"),
        (429, None, "char_literal_escaped_hex") => Some("expression"),
        (429, None, "char_literal_escaped_simple") => Some("expression"),
        (429, None, "char_literal_escaped_unicode_braced") => Some("expression"),
        (429, None, "char_literal_escaped_unicode_fixed") => Some("expression"),
        (429, None, "char_literal_plain") => Some("expression"),
        (429, None, "closure_expression_block") => Some("expression"),
        (429, None, "closure_expression_expr") => Some("expression"),
        (429, None, "compound_assignment_expr") => Some("expression"),
        (429, None, "const_block") => Some("expression"),
        (429, None, "continue_expression") => Some("expression"),
        (429, None, "default_keyword") => Some("expression"),
        (429, None, "f32_keyword") => Some("expression"),
        (429, None, "f64_keyword") => Some("expression"),
        (429, None, "field_expression") => Some("expression"),
        (429, None, "float_literal") => Some("expression"),
        (429, None, "for_expression") => Some("expression"),
        (429, None, "gen_block") => Some("expression"),
        (429, None, "gen_keyword") => Some("expression"),
        (429, None, "generic_function") => Some("expression"),
        (429, None, "i128_keyword") => Some("expression"),
        (429, None, "i16_keyword") => Some("expression"),
        (429, None, "i32_keyword") => Some("expression"),
        (429, None, "i64_keyword") => Some("expression"),
        (429, None, "i8_keyword") => Some("expression"),
        (429, None, "identifier") => Some("expression"),
        (429, None, "if_expression") => Some("expression"),
        (429, None, "index_expression") => Some("expression"),
        (429, None, "integer_literal_binary") => Some("expression"),
        (429, None, "integer_literal_decimal") => Some("expression"),
        (429, None, "integer_literal_hex") => Some("expression"),
        (429, None, "integer_literal_octal") => Some("expression"),
        (429, None, "isize_keyword") => Some("expression"),
        (429, None, "loop_expression") => Some("expression"),
        (429, None, "macro_invocation") => Some("expression"),
        (429, None, "match_expression") => Some("expression"),
        (429, None, "metavariable") => Some("expression"),
        (429, None, "parenthesized_expression") => Some("expression"),
        (429, None, "range_expression") => Some("expression"),
        (429, None, "raw_string_literal") => Some("expression"),
        (429, None, "reference_expression_bare") => Some("expression"),
        (429, None, "reference_expression_mut") => Some("expression"),
        (429, None, "reference_expression_raw_const") => Some("expression"),
        (429, None, "reference_expression_raw_mut") => Some("expression"),
        (429, None, "return_expression") => Some("expression"),
        (429, None, "scoped_identifier") => Some("expression"),
        (429, None, "self") => Some("expression"),
        (429, None, "str_keyword") => Some("expression"),
        (429, None, "string_literal") => Some("expression"),
        (429, None, "struct_expression") => Some("expression"),
        (429, None, "try_block") => Some("expression"),
        (429, None, "try_expression") => Some("expression"),
        (429, None, "tuple_expression") => Some("expression"),
        (429, None, "type_cast_expression") => Some("expression"),
        (429, None, "u128_keyword") => Some("expression"),
        (429, None, "u16_keyword") => Some("expression"),
        (429, None, "u32_keyword") => Some("expression"),
        (429, None, "u64_keyword") => Some("expression"),
        (429, None, "u8_keyword") => Some("expression"),
        (429, None, "unary_expression") => Some("expression"),
        (429, None, "union_keyword") => Some("expression"),
        (429, None, "unit_expression") => Some("expression"),
        (429, None, "unsafe_block") => Some("expression"),
        (429, None, "usize_keyword") => Some("expression"),
        (429, None, "while_expression") => Some("expression"),
        (429, None, "yield_expression") => Some("expression"),
        (431, None, "abstract_type") => Some("content"),
        (431, None, "array_type") => Some("content"),
        (431, None, "block") => Some("content"),
        (431, None, "boolean_literal") => Some("content"),
        (431, None, "bounded_type") => Some("content"),
        (431, None, "char_literal_empty") => Some("content"),
        (431, None, "char_literal_escaped_hex") => Some("content"),
        (431, None, "char_literal_escaped_simple") => Some("content"),
        (431, None, "char_literal_escaped_unicode_braced") => Some("content"),
        (431, None, "char_literal_escaped_unicode_fixed") => Some("content"),
        (431, None, "char_literal_plain") => Some("content"),
        (431, None, "dynamic_type") => Some("content"),
        (431, None, "float_literal") => Some("content"),
        (431, None, "function_type") => Some("content"),
        (431, None, "generic_type") => Some("content"),
        (431, None, "integer_literal_binary") => Some("content"),
        (431, None, "integer_literal_decimal") => Some("content"),
        (431, None, "integer_literal_hex") => Some("content"),
        (431, None, "integer_literal_octal") => Some("content"),
        (431, None, "lifetime") => Some("content"),
        (431, None, "macro_invocation") => Some("content"),
        (431, None, "metavariable") => Some("content"),
        (431, None, "never_type") => Some("content"),
        (431, None, "pointer_type_const") => Some("content"),
        (431, None, "pointer_type_mut") => Some("content"),
        (431, None, "primitive_type") => Some("content"),
        (431, None, "raw_string_literal") => Some("content"),
        (431, None, "reference_type") => Some("content"),
        (431, None, "removed_trait_bound") => Some("content"),
        (431, None, "scoped_type_identifier") => Some("content"),
        (431, None, "string_literal") => Some("content"),
        (431, None, "tuple_type") => Some("content"),
        (431, None, "type_binding") => Some("content"),
        (431, None, "type_identifier") => Some("content"),
        (431, None, "unit_type") => Some("content"),
        (432, None, "match_arm_block_ending") => Some("match_arm"),
        (432, None, "match_arm_with_comma") => Some("match_arm"),
        _ => None,
    }
}

/// The gap an extra occupies inside a node with no named child to own it,
/// by (kind id, anonymous tokens before the extra): the model slot whose
/// position the gap holds. `None` when the model has no slot there.
pub fn inner_gap_key(kind: KindId, preceding_tokens: u16) -> Option<&'static str> {
    match (kind.0, preceding_tokens) {
        (176, 0) => Some("statements"),
        (195, 1) => Some("declarations"),
        (199, 1) => Some("enum_variant_list_elements"),
        (201, 1) => Some("field_declaration_list_elements"),
        (203, 1) => Some("attributes"),
        (227, 1) => Some("use_clauses"),
        (230, 1) => Some("parameters_elements"),
        (249, 2) => Some("bounds"),
        (277, 1) => Some("arguments_elements"),
        (283, 1) => Some("initializers"),
        (293, 1) => Some("match_block_arms"),
        (302, 1) => Some("parameters"),
        (313, 1) => Some("statements"),
        (316, 1) => Some("elements"),
        (317, 1) => Some("patterns"),
        (367, 1) => Some("attributes"),
        (403, 1) => Some("token_patterns"),
        (404, 1) => Some("token_patterns"),
        (405, 1) => Some("token_patterns"),
        (406, 1) => Some("tokens"),
        (407, 1) => Some("tokens"),
        (408, 1) => Some("tokens"),
        (409, 1) => Some("delim_tokens"),
        (410, 1) => Some("delim_tokens"),
        (411, 1) => Some("delim_tokens"),
        _ => None,
    }
}
/// Whether the model stores a `child` of a `parent` node, reached under the
/// parser field `field` (`None` for an untagged child), as a scalar: a
/// presence flag or a kind id rather than a node. Such a child keeps no
/// trivia, so the reader never makes it an owner.
pub fn stores_scalar(parent: KindId, field: Option<&str>, child: KindId) -> bool {
    match (parent.0, field) {
        (176, Some("statements")) => matches!(child.0, 178),
        (184, Some("type")) => matches!(child.0, 12 | 13 | 14 | 15 | 16 | 17 | 18 | 19 | 20 | 21 | 22 | 23 | 24 | 25 | 26),
        (185, Some("operator")) => matches!(child.0, 9 | 10 | 11),
        (188, Some("operator")) => matches!(child.0, 9 | 10 | 11),
        (189, None) => matches!(child.0, 2 | 3 | 4 | 9 | 10 | 11 | 27 | 30 | 33 | 34 | 36 | 37 | 38 | 39 | 40 | 41 | 42 | 43 | 44 | 45 | 46 | 47 | 48 | 49 | 50 | 51 | 52 | 53 | 55 | 56 | 58 | 59 | 60 | 61 | 62 | 63 | 64 | 65 | 66 | 67 | 68 | 69 | 70 | 71 | 72 | 73 | 74 | 75 | 76 | 77 | 78 | 79 | 80 | 81 | 82 | 83 | 84 | 85 | 86 | 87 | 88 | 89 | 90 | 91 | 92 | 93 | 94 | 95 | 96 | 97 | 98 | 99 | 101 | 102 | 104 | 105 | 106 | 108 | 109 | 110 | 111 | 112 | 113 | 116 | 118 | 119 | 126 | 127 | 128 | 131 | 132 | 133 | 134 | 135 | 136 | 137),
        (192, Some("path")) => matches!(child.0, 33 | 52 | 53 | 59 | 60 | 61 | 62 | 63 | 64 | 65 | 66 | 67 | 68 | 69 | 70 | 71 | 72 | 73 | 74 | 75 | 126 | 127 | 128),
        (195, Some("declarations")) => matches!(child.0, 178),
        (200, Some("value")) => matches!(child.0, 118 | 119 | 126),
        (202, Some("type")) => matches!(child.0, 59 | 60 | 61 | 62 | 63 | 64 | 65 | 66 | 67 | 68 | 69 | 70 | 71 | 72 | 73 | 74 | 75 | 254),
        (205, Some("type")) => matches!(child.0, 59 | 60 | 61 | 62 | 63 | 64 | 65 | 66 | 67 | 68 | 69 | 70 | 71 | 72 | 73 | 74 | 75 | 254),
        (205, Some("value")) => matches!(child.0, 118 | 119 | 126),
        (206, Some("type")) => matches!(child.0, 59 | 60 | 61 | 62 | 63 | 64 | 65 | 66 | 67 | 68 | 69 | 70 | 71 | 72 | 73 | 74 | 75 | 254),
        (206, Some("value")) => matches!(child.0, 118 | 119 | 126),
        (207, Some("type")) => matches!(child.0, 59 | 60 | 61 | 62 | 63 | 64 | 65 | 66 | 67 | 68 | 69 | 70 | 71 | 72 | 73 | 74 | 75 | 254),
        (208, Some("return_type")) => matches!(child.0, 59 | 60 | 61 | 62 | 63 | 64 | 65 | 66 | 67 | 68 | 69 | 70 | 71 | 72 | 73 | 74 | 75 | 254),
        (209, Some("return_type")) => matches!(child.0, 59 | 60 | 61 | 62 | 63 | 64 | 65 | 66 | 67 | 68 | 69 | 70 | 71 | 72 | 73 | 74 | 75 | 254),
        (210, Some("modifier")) => matches!(child.0, 36 | 52 | 112 | 113),
        (212, Some("left")) => matches!(child.0, 59 | 60 | 61 | 62 | 63 | 64 | 65 | 66 | 67 | 68 | 69 | 70 | 71 | 72 | 73 | 74 | 75),
        (216, Some("bounds")) => matches!(child.0, 59 | 60 | 61 | 62 | 63 | 64 | 65 | 66 | 67 | 68 | 69 | 70 | 71 | 72 | 73 | 74 | 75 | 254),
        (217, Some("type")) => matches!(child.0, 59 | 60 | 61 | 62 | 63 | 64 | 65 | 66 | 67 | 68 | 69 | 70 | 71 | 72 | 73 | 74 | 75 | 254),
        (218, Some("type")) => matches!(child.0, 59 | 60 | 61 | 62 | 63 | 64 | 65 | 66 | 67 | 68 | 69 | 70 | 71 | 72 | 73 | 74 | 75 | 254),
        (220, Some("type")) => matches!(child.0, 59 | 60 | 61 | 62 | 63 | 64 | 65 | 66 | 67 | 68 | 69 | 70 | 71 | 72 | 73 | 74 | 75 | 254),
        (220, Some("value")) => matches!(child.0, 118 | 119),
        (221, Some("default_type")) => matches!(child.0, 59 | 60 | 61 | 62 | 63 | 64 | 65 | 66 | 67 | 68 | 69 | 70 | 71 | 72 | 73 | 74 | 75 | 254),
        (223, Some("pattern")) => matches!(child.0, 118 | 119 | 321 | 424),
        (223, Some("type")) => matches!(child.0, 59 | 60 | 61 | 62 | 63 | 64 | 65 | 66 | 67 | 68 | 69 | 70 | 71 | 72 | 73 | 74 | 75 | 254),
        (223, Some("value")) => matches!(child.0, 118 | 119 | 126),
        (224, Some("argument")) => matches!(child.0, 33 | 52 | 53 | 59 | 60 | 61 | 62 | 63 | 64 | 65 | 66 | 67 | 68 | 69 | 70 | 71 | 72 | 73 | 74 | 75 | 126 | 127 | 128),
        (226, Some("path")) => matches!(child.0, 33 | 52 | 53 | 59 | 60 | 61 | 62 | 63 | 64 | 65 | 66 | 67 | 68 | 69 | 70 | 71 | 72 | 73 | 74 | 75 | 126 | 127 | 128),
        (228, Some("path")) => matches!(child.0, 33 | 52 | 53 | 59 | 60 | 61 | 62 | 63 | 64 | 65 | 66 | 67 | 68 | 69 | 70 | 71 | 72 | 73 | 74 | 75 | 126 | 127 | 128),
        (232, Some("pattern")) => matches!(child.0, 118 | 119 | 321 | 424),
        (233, Some("name")) => matches!(child.0, 118 | 119 | 126 | 321 | 424),
        (233, Some("type")) => matches!(child.0, 59 | 60 | 61 | 62 | 63 | 64 | 65 | 66 | 67 | 68 | 69 | 70 | 71 | 72 | 73 | 74 | 75 | 254),
        (235, None) => matches!(child.0, 128),
        (237, Some("type")) => matches!(child.0, 59 | 60 | 61 | 62 | 63 | 64 | 65 | 66 | 67 | 68 | 69 | 70 | 71 | 72 | 73 | 74 | 75 | 254),
        (238, Some("alias")) => matches!(child.0, 59 | 60 | 61 | 62 | 63 | 64 | 65 | 66 | 67 | 68 | 69 | 70 | 71 | 72 | 73 | 74 | 75 | 254),
        (238, Some("type")) => matches!(child.0, 59 | 60 | 61 | 62 | 63 | 64 | 65 | 66 | 67 | 68 | 69 | 70 | 71 | 72 | 73 | 74 | 75 | 254),
        (240, Some("element")) => matches!(child.0, 59 | 60 | 61 | 62 | 63 | 64 | 65 | 66 | 67 | 68 | 69 | 70 | 71 | 72 | 73 | 74 | 75 | 254),
        (240, Some("length")) => matches!(child.0, 118 | 119 | 126),
        (242, Some("return_type")) => matches!(child.0, 59 | 60 | 61 | 62 | 63 | 64 | 65 | 66 | 67 | 68 | 69 | 70 | 71 | 72 | 73 | 74 | 75 | 254),
        (246, Some("type")) => matches!(child.0, 33 | 52 | 53),
        (248, Some("left")) => matches!(child.0, 59 | 60 | 61 | 62 | 63 | 64 | 65 | 66 | 67 | 68 | 69 | 70 | 71 | 72 | 73 | 74 | 75 | 254),
        (248, Some("right")) => matches!(child.0, 59 | 60 | 61 | 62 | 63 | 64 | 65 | 66 | 67 | 68 | 69 | 70 | 71 | 72 | 73 | 74 | 75 | 254),
        (251, Some("type")) => matches!(child.0, 59 | 60 | 61 | 62 | 63 | 64 | 65 | 66 | 67 | 68 | 69 | 70 | 71 | 72 | 73 | 74 | 75 | 254),
        (252, Some("type")) => matches!(child.0, 59 | 60 | 61 | 62 | 63 | 64 | 65 | 66 | 67 | 68 | 69 | 70 | 71 | 72 | 73 | 74 | 75 | 254),
        (259, Some("macro")) => matches!(child.0, 33 | 52 | 53),
        (263, Some("name")) => matches!(child.0, 127),
        (263, Some("path")) => matches!(child.0, 33 | 52 | 53 | 59 | 60 | 61 | 62 | 63 | 64 | 65 | 66 | 67 | 68 | 69 | 70 | 71 | 72 | 73 | 74 | 75 | 126 | 127 | 128),
        (264, Some("path")) => matches!(child.0, 33 | 52 | 53 | 59 | 60 | 61 | 62 | 63 | 64 | 65 | 66 | 67 | 68 | 69 | 70 | 71 | 72 | 73 | 74 | 75 | 126 | 127 | 128),
        (265, Some("path")) => matches!(child.0, 33 | 52 | 53 | 59 | 60 | 61 | 62 | 63 | 64 | 65 | 66 | 67 | 68 | 69 | 70 | 71 | 72 | 73 | 74 | 75 | 126 | 127 | 128),
        (266, None) => matches!(child.0, 363),
        (267, Some("operand")) => matches!(child.0, 118 | 119 | 126),
        (267, Some("operator")) => matches!(child.0, 10 | 30 | 76),
        (268, Some("value")) => matches!(child.0, 118 | 119 | 126),
        (270, Some("left")) => matches!(child.0, 118 | 119 | 126),
        (270, Some("operator")) => matches!(child.0, 9 | 10 | 44 | 45 | 55 | 76 | 77 | 78 | 79 | 80 | 81 | 82 | 83 | 84 | 85 | 86 | 87 | 88),
        (270, Some("right")) => matches!(child.0, 118 | 119 | 126),
        (271, Some("left")) => matches!(child.0, 118 | 119 | 126),
        (271, Some("right")) => matches!(child.0, 118 | 119 | 126),
        (272, Some("left")) => matches!(child.0, 118 | 119 | 126),
        (272, Some("operator")) => matches!(child.0, 89 | 90 | 91 | 92 | 93 | 94 | 95 | 96 | 97 | 98),
        (272, Some("right")) => matches!(child.0, 118 | 119 | 126),
        (273, Some("type")) => matches!(child.0, 59 | 60 | 61 | 62 | 63 | 64 | 65 | 66 | 67 | 68 | 69 | 70 | 71 | 72 | 73 | 74 | 75 | 254),
        (273, Some("value")) => matches!(child.0, 118 | 119 | 126),
        (274, Some("expression")) => matches!(child.0, 118 | 119 | 126),
        (275, Some("expression")) => matches!(child.0, 118 | 119 | 126),
        (276, Some("function")) => matches!(child.0, 33 | 52 | 53 | 59 | 60 | 61 | 62 | 63 | 64 | 65 | 66 | 67 | 68 | 69 | 70 | 71 | 72 | 73 | 74 | 75 | 118 | 119 | 126 | 281),
        (279, Some("expression")) => matches!(child.0, 118 | 119 | 126),
        (285, Some("value")) => matches!(child.0, 118 | 119 | 126),
        (286, Some("value")) => matches!(child.0, 118 | 119 | 126),
        (287, Some("condition")) => matches!(child.0, 118 | 119 | 126),
        (288, Some("pattern")) => matches!(child.0, 118 | 119 | 321 | 424),
        (288, Some("value")) => matches!(child.0, 118 | 119 | 126),
        (289, Some("left")) => matches!(child.0, 118 | 119 | 126),
        (289, Some("right")) => matches!(child.0, 118 | 119 | 126),
        (292, Some("value")) => matches!(child.0, 118 | 119 | 126),
        (295, Some("value")) => matches!(child.0, 118 | 119 | 126),
        (296, Some("condition")) => matches!(child.0, 118 | 119 | 126),
        (296, Some("pattern")) => matches!(child.0, 118 | 119 | 321 | 424),
        (297, Some("condition")) => matches!(child.0, 118 | 119 | 126),
        (299, Some("pattern")) => matches!(child.0, 118 | 119 | 321 | 424),
        (299, Some("value")) => matches!(child.0, 118 | 119 | 126),
        (302, Some("parameters")) => matches!(child.0, 118 | 119 | 321 | 424),
        (304, None) => matches!(child.0, 118 | 119 | 126),
        (306, Some("index")) => matches!(child.0, 118 | 119 | 126),
        (306, Some("object")) => matches!(child.0, 118 | 119 | 126),
        (307, Some("expression")) => matches!(child.0, 118 | 119 | 126),
        (308, Some("value")) => matches!(child.0, 118 | 119 | 126),
        (313, Some("statements")) => matches!(child.0, 178),
        (313, Some("trailing_expression")) => matches!(child.0, 118 | 119 | 126),
        (322, Some("pattern")) => matches!(child.0, 118 | 119 | 321 | 424),
        (324, Some("pattern")) => matches!(child.0, 118 | 119 | 321 | 424),
        (325, Some("pattern")) => matches!(child.0, 118 | 119 | 321 | 424),
        (326, Some("pattern")) => matches!(child.0, 118 | 119 | 321 | 424),
        (348, Some("use_clause")) => matches!(child.0, 33 | 52 | 53 | 59 | 60 | 61 | 62 | 63 | 64 | 65 | 66 | 67 | 68 | 69 | 70 | 71 | 72 | 73 | 74 | 75 | 126 | 127 | 128),
        (355, Some("element")) => matches!(child.0, 118 | 119 | 321 | 424),
        (356, Some("pattern")) => matches!(child.0, 118 | 119 | 321 | 424),
        (357, Some("element")) => matches!(child.0, 321),
        (358, Some("path")) => matches!(child.0, 33 | 52 | 53 | 59 | 60 | 61 | 62 | 63 | 64 | 65 | 66 | 67 | 68 | 69 | 70 | 71 | 72 | 73 | 74 | 75 | 126 | 127 | 128),
        (359, Some("type")) => matches!(child.0, 59 | 60 | 61 | 62 | 63 | 64 | 65 | 66 | 67 | 68 | 69 | 70 | 71 | 72 | 73 | 74 | 75 | 254),
        (360, Some("element")) => matches!(child.0, 118 | 119 | 126),
        (366, Some("element")) => matches!(child.0, 118 | 119 | 126),
        (366, Some("length")) => matches!(child.0, 118 | 119 | 126),
        (368, Some("value")) => matches!(child.0, 118 | 119 | 126),
        (369, Some("return_type")) => matches!(child.0, 59 | 60 | 61 | 62 | 63 | 64 | 65 | 66 | 67 | 68 | 69 | 70 | 71 | 72 | 73 | 74 | 75 | 254),
        (370, Some("body")) => matches!(child.0, 118 | 119 | 126 | 133),
        (371, Some("value")) => matches!(child.0, 118 | 119 | 126),
        (372, Some("value")) => matches!(child.0, 118 | 119 | 126),
        (373, Some("value")) => matches!(child.0, 118 | 119 | 126),
        (374, Some("value")) => matches!(child.0, 118 | 119 | 126),
        (377, Some("type")) => matches!(child.0, 59 | 60 | 61 | 62 | 63 | 64 | 65 | 66 | 67 | 68 | 69 | 70 | 71 | 72 | 73 | 74 | 75 | 254),
        (378, Some("type")) => matches!(child.0, 59 | 60 | 61 | 62 | 63 | 64 | 65 | 66 | 67 | 68 | 69 | 70 | 71 | 72 | 73 | 74 | 75 | 254),
        (379, None) => matches!(child.0, 33 | 52 | 53 | 59 | 60 | 61 | 62 | 63 | 64 | 65 | 66 | 67 | 68 | 69 | 70 | 71 | 72 | 73 | 74 | 75 | 126 | 127 | 128),
        (380, None) => matches!(child.0, 126 | 127 | 128),
        (386, Some("left")) => matches!(child.0, 118 | 119 | 321 | 424),
        (386, Some("right")) => matches!(child.0, 118 | 119 | 321 | 424),
        (387, Some("right")) => matches!(child.0, 118 | 119 | 321 | 424),
        (388, Some("type")) => matches!(child.0, 59 | 60 | 61 | 62 | 63 | 64 | 65 | 66 | 67 | 68 | 69 | 70 | 71 | 72 | 73 | 74 | 75 | 254),
        (389, Some("type")) => matches!(child.0, 59 | 60 | 61 | 62 | 63 | 64 | 65 | 66 | 67 | 68 | 69 | 70 | 71 | 72 | 73 | 74 | 75 | 254),
        (390, Some("end")) => matches!(child.0, 118 | 119 | 126),
        (390, Some("operator")) => matches!(child.0, 50 | 101 | 134),
        (390, Some("start")) => matches!(child.0, 118 | 119 | 126),
        (391, Some("start")) => matches!(child.0, 118 | 119 | 126),
        (392, Some("end")) => matches!(child.0, 118 | 119 | 126),
        (393, Some("expression")) => matches!(child.0, 118 | 119 | 126),
        (396, Some("value")) => matches!(child.0, 118 | 119 | 126),
        (409, Some("delim_tokens")) => matches!(child.0, 5),
        (410, Some("delim_tokens")) => matches!(child.0, 5),
        (411, Some("delim_tokens")) => matches!(child.0, 5),
        (413, Some("pattern")) => matches!(child.0, 118 | 119 | 321 | 424),
        (414, Some("name")) => matches!(child.0, 33 | 52 | 53),
        (415, Some("name")) => matches!(child.0, 33 | 52 | 53),
        (416, Some("name")) => matches!(child.0, 33 | 52 | 53),
        (417, None) => matches!(child.0, 101 | 134),
        (417, Some("right")) => matches!(child.0, 33 | 52 | 53 | 59 | 60 | 61 | 62 | 63 | 64 | 65 | 66 | 67 | 68 | 69 | 70 | 71 | 72 | 73 | 74 | 75 | 118 | 119 | 126 | 127 | 128),
        (418, None) => matches!(child.0, 50 | 101 | 134),
        (418, Some("right")) => matches!(child.0, 33 | 52 | 53 | 59 | 60 | 61 | 62 | 63 | 64 | 65 | 66 | 67 | 68 | 69 | 70 | 71 | 72 | 73 | 74 | 75 | 118 | 119 | 126 | 127 | 128),
        (420, None) => matches!(child.0, 419),
        (420, Some("left")) => matches!(child.0, 33 | 52 | 53 | 59 | 60 | 61 | 62 | 63 | 64 | 65 | 66 | 67 | 68 | 69 | 70 | 71 | 72 | 73 | 74 | 75 | 118 | 119 | 126 | 127 | 128),
        (427, None) => matches!(child.0, 59 | 60 | 61 | 62 | 63 | 64 | 65 | 66 | 67 | 68 | 69 | 70 | 71 | 72 | 73 | 74 | 75 | 133 | 254),
        (429, None) => matches!(child.0, 118 | 119 | 126),
        (430, Some("type")) => matches!(child.0, 59 | 60 | 61 | 62 | 63 | 64 | 65 | 66 | 67 | 68 | 69 | 70 | 71 | 72 | 73 | 74 | 75 | 254),
        (431, None) => matches!(child.0, 59 | 60 | 61 | 62 | 63 | 64 | 65 | 66 | 67 | 68 | 69 | 70 | 71 | 72 | 73 | 74 | 75 | 118 | 119 | 254),
        _ => false,
    }
}
