export const PAYLOAD_CEILING_BYTES = 256;

export const BOXED_PAYLOADS: Readonly<Record<string, readonly string[]>> = {
	rust: ['AttributeItemTransport', 'AttributeTransport', 'AttributedEnumVariantTransport', 'AttributedFieldDeclarationTransport', 'AttributedOrderedFieldTransport', 'AttributedParameterTransport', 'ConstItemTransport', 'ConstParameterTransport', 'EnumItemTransport', 'EnumVariantTransport', 'FieldDeclarationTransport', 'FieldInitializerTransport', 'FunctionItemTransport', 'FunctionSignatureItemTransport', 'ImplItemBodyTransport', 'ImplItemSemiTransport', 'InnerAttributeItemTransport', 'LetDeclarationTransport', 'MatchArmBlockEndingTransport', 'MatchArmWithCommaTransport', 'ParameterTransport', 'StaticItemTransport', 'StructItemBraceTransport', 'StructItemTupleTransport', 'TraitItemTransport', 'TypeBindingTransport', 'TypeItemTransport', 'TypeParameterTransport', 'UnionItemTransport', 'UseDeclarationTransport'],
	typescript: ['AbstractClassDeclarationTransport', 'AbstractMethodSignatureTransport', 'AddingTypeAnnotationTransport', 'AmbientDeclarationModuleTransport', 'ArrowFunctionTransport', 'AsExpressionTransport', 'AssignmentPatternTransport', 'CatchClauseGroupTransport', 'CatchClauseTransport', 'ClassBodyMemberMethodSigTransport', 'ClassBodyMemberMethodTransport', 'ClassDeclarationTransport', 'ClassTransport', 'ConstraintTransport', 'ConstructSignatureTransport', 'DefaultTypeTransport', 'EnumAssignmentTransport', 'ExportStatementDefaultDeclarationTransport', 'ForHeaderLetConstKindTransport', 'ForHeaderLhsTransport', 'ForHeaderVarKindTransport', 'ForStatementTransport', 'FunctionDeclarationTransport', 'FunctionExpressionTransport', 'FunctionSignatureTransport', 'GeneratorFunctionDeclarationTransport', 'GeneratorFunctionTransport', 'ImportStatementTransport', 'IndexSignatureColonTransport', 'IndexSignatureMappedTypeClauseTransport', 'InterfaceDeclarationTransport', 'MappedTypeClauseTransport', 'MethodDefinitionTransport', 'MethodSignatureTransport', 'OmittingTypeAnnotationTransport', 'OptingTypeAnnotationTransport', 'OptionalParameterTransport', 'OptionalTupleParameterTransport', 'OptionalTypeTransport', 'PairPatternTransport', 'PairTransport', 'ParenthesizedExpressionTypedTransport', 'PropertySignatureTransport', 'PublicFieldDefinitionTransport', 'RequiredParameterTransport', 'RestTypeTransport', 'SatisfiesExpressionTransport', 'TemplateTypeTransport', 'TryStatementTransport', 'TupleParameterTransport', 'TypeAliasDeclarationTransport', 'TypeAnnotationTransport', 'TypeParameterTransport', 'VariableDeclaratorDefiniteTransport', 'VariableDeclaratorPlainTransport'],
	python: ['CaseClauseTransport', 'ComplexPatternTransport', 'DecoratedDefinitionTransport', 'ExceptClauseExceptionAsTransport', 'ForStatementTransport', 'FunctionDefinitionTransport', 'RaiseStatementTransport', 'SliceTransport', 'WhileStatementTransport'],
	scm: [],
	regex: ['ClassRangeTransport', 'TermGroupTransport']
};
