export const PAYLOAD_CEILING_BYTES = 256;

export const BOXED_PAYLOADS: Readonly<Record<string, readonly string[]>> = {
	rust: ['AttributeInputTransport', 'AttributeItemTransport', 'AttributeTransport', 'AttributedArgumentTransport', 'AttributedEnumVariantTransport', 'AttributedFieldDeclarationTransport', 'AttributedOrderedFieldTransport', 'AttributedParameterTransport', 'ConstItemTransport', 'ConstParameterTransport', 'DeclarationStatementTransport', 'EnumItemTransport', 'EnumVariantTransport', 'ExternCrateDeclarationTransport', 'FieldDeclarationTransport', 'FieldInitializerTransport', 'ForeignModItemBodyTransport', 'FunctionItemTransport', 'FunctionSignatureItemTransport', 'ImplItemBodyTransport', 'ImplItemSemiTransport', 'InnerAttributeItemTransport', 'LetDeclarationTransport', 'MatchArmBlockEndingTransport', 'MatchArmWithCommaTransport', 'ModItemInlineTransport', 'ParameterTransport', 'StaticItemTransport', 'StructItemBraceTransport', 'StructItemTupleTransport', 'StructItemUnitTransport', 'TraitItemTransport', 'TypeArgumentTransport', 'TypeBindingTransport', 'TypeItemTransport', 'TypeParameterTransport', 'UnionItemTransport', 'UseDeclarationTransport'],
	typescript: ['AbstractClassDeclarationTransport', 'AbstractMethodSignatureTransport', 'AmbientDeclarationModuleTransport', 'AsExpressionTransport', 'AssignmentPatternTransport', 'CallSignatureTransport', 'CatchClauseGroupTransport', 'CatchClauseTransport', 'ClassBodyMemberMethodSigTransport', 'ClassBodyMemberMethodTransport', 'ClassDeclarationTransport', 'ClassTransport', 'ConstraintTransport', 'ConstructSignatureTransport', 'DecoratorParenthesizedExpressionTransport', 'DecoratorTransport', 'EnumAssignmentTransport', 'ExportStatementDefaultDeclarationDefaultKwValueTransport', 'ExportStatementDefaultDeclarationTransport', 'ExportStatementEqualsExportTransport', 'ExpressionStatementTransport', 'ExtendsClauseSingleTransport', 'ForHeaderLetConstKindTransport', 'ForHeaderLhsTransport', 'ForHeaderVarKindTransport', 'ForStatementTransport', 'FunctionDeclarationTransport', 'FunctionExpressionTransport', 'FunctionSignatureTransport', 'GeneratorFunctionDeclarationTransport', 'GeneratorFunctionTransport', 'GenericTypeTransport', 'ImportStatementTransport', 'IndexSignatureColonTransport', 'IndexSignatureMappedTypeClauseTransport', 'InterfaceDeclarationTransport', 'MappedTypeClauseTransport', 'MethodDefinitionTransport', 'MethodSignatureTransport', 'ObjectAssignmentPatternTransport', 'OptionalParameterTransport', 'OptionalTupleParameterTransport', 'PairPatternTransport', 'PairTransport', 'ParenthesizedExpressionTypedTransport', 'PropertySignatureTransport', 'PublicFieldDefinitionTransport', 'RequiredParameterTransport', 'ReturnStatementTransport', 'SatisfiesExpressionTransport', 'SwitchCaseTransport', 'ThrowStatementTransport', 'TryStatementTransport', 'TupleParameterTransport', 'TypeAliasDeclarationTransport', 'TypeParameterTransport', 'TypeQueryInstantiationExpressionTransport', 'VariableDeclaratorDefiniteTransport', 'VariableDeclaratorPlainTransport'],
	python: ['CaseClauseTransport', 'ClassDefinitionTransport', 'ComplexPatternTransport', 'ElifClauseTransport', 'ExceptClauseExceptionAsTransport', 'ExpressionStatementTransport', 'ForStatementTransport', 'FormatExpressionTransport', 'FunctionDefinitionTransport', 'IfStatementTransport', 'InterpolationTransport', 'PrintStatementTransport', 'RaiseStatementTransport', 'SliceTransport', 'TryStatementTransport', 'TypedDefaultParameterTransport', 'WhileStatementTransport'],
	scm: [],
	regex: ['ClassRangeTransport', 'TermGroupTransport']
};
