/**
 * Emits consts.ts — discoverable arrays and maps from the grammar.
 *
 * Consumes NodeMap directly. No imports from node-model.ts or naming.ts.
 */

import type { NodeMap, AssembledNode, AssembledBranch, AssembledContainer } from '../compiler/rule.ts'

export interface EmitConstsFromNodeMapConfig {
    grammar: string
    nodeMap: NodeMap
}

export function emitConstsFromNodeMap(config: EmitConstsFromNodeMapConfig): string {
    const { nodeMap } = config

    const nodeKinds: string[] = []      // branch + container + polymorph
    const leafKinds: string[] = []      // leaf + keyword + enum
    const keywords: string[] = []       // keyword model type (alphabetic tokens)
    const operators: string[] = []      // token model type (non-alphabetic)
    const enumEntries: { kind: string; values: string[] }[] = []

    for (const [kind, node] of nodeMap.nodes) {
        switch (node.modelType) {
            case 'branch':
            case 'container':
            case 'polymorph':
                nodeKinds.push(kind)
                break
            case 'leaf':
            case 'enum':
                leafKinds.push(kind)
                if (node.modelType === 'enum') {
                    enumEntries.push({ kind, values: node.values })
                }
                break
            case 'keyword':
                leafKinds.push(kind)
                keywords.push(kind)
                break
            case 'token':
                if (/^[a-z_]+$/i.test(kind)) {
                    keywords.push(kind)
                } else {
                    operators.push(kind)
                }
                break
            // supertype, group — not in any public const array
        }
    }

    const lines: string[] = [
        '// Auto-generated by @sittir/codegen — do not edit',
        '',
    ]

    // NODE_KINDS
    lines.push('/** All branch (non-leaf) node kind strings. */')
    lines.push('export const NODE_KINDS = [')
    for (const kind of nodeKinds.sort()) {
        lines.push(`  '${kind}',`)
    }
    lines.push('] as const;')
    lines.push('')

    // LEAF_KINDS
    lines.push('/** All leaf/terminal node kind strings. */')
    lines.push('export const LEAF_KINDS = [')
    for (const kind of leafKinds.sort()) {
        lines.push(`  '${kind}',`)
    }
    lines.push('] as const;')
    lines.push('')

    // ALL_KINDS
    lines.push('/** All node kind strings (branch + leaf). */')
    lines.push('export const ALL_KINDS = [...NODE_KINDS, ...LEAF_KINDS] as const;')
    lines.push('')

    // KEYWORDS
    lines.push('/** Language keywords (alphabetic anonymous tokens). */')
    lines.push('export const KEYWORDS = [')
    for (const kw of keywords.sort()) {
        lines.push(`  '${kw}',`)
    }
    lines.push('] as const;')
    lines.push('')

    // OPERATORS
    lines.push('/** Operator/punctuation tokens. */')
    lines.push('export const OPERATORS = [')
    for (const op of operators.sort()) {
        lines.push(`  '${op.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}',`)
    }
    lines.push('] as const;')
    lines.push('')

    // Type aliases
    lines.push('export type NodeKind = (typeof NODE_KINDS)[number];')
    lines.push('export type LeafKind = (typeof LEAF_KINDS)[number];')
    lines.push('export type AnyKind = (typeof ALL_KINDS)[number];')
    lines.push('export type Keyword = (typeof KEYWORDS)[number];')
    lines.push('export type Operator = (typeof OPERATORS)[number];')
    lines.push('')

    // FIELD_MAP
    lines.push('/** Per-node-kind field metadata. */')
    lines.push('export const FIELD_MAP: Record<NodeKind, ReadonlyArray<{')
    lines.push('  name: string;')
    lines.push('  required: boolean;')
    lines.push('  multiple: boolean;')
    lines.push('}>> = {')

    for (const kind of nodeKinds.sort()) {
        const node = nodeMap.nodes.get(kind)!
        lines.push(`  '${kind}': [`)
        const fields = getFields(node)
        for (const f of fields) {
            lines.push(`    { name: '${f.propertyName}', required: ${f.required}, multiple: ${f.multiple} },`)
        }
        lines.push('  ],')
    }
    lines.push('};')
    lines.push('')

    // Enum values
    for (const ek of enumEntries.sort((a, b) => a.kind.localeCompare(b.kind))) {
        const constName = ek.kind.toUpperCase() + 'S'
        const typeName = ek.kind.split('_').map(w => w.charAt(0).toUpperCase() + w.slice(1)).join('') + 'Value'

        lines.push(`/** Valid values for \`${ek.kind}\` nodes. */`)
        lines.push(`export const ${constName} = [`)
        for (const v of ek.values) {
            lines.push(`  '${v.replace(/'/g, "\\'")}',`)
        }
        lines.push('] as const;')
        lines.push(`export type ${typeName} = (typeof ${constName})[number];`)
        lines.push('')
    }

    return lines.join('\n')
}

function getFields(node: AssembledNode) {
    switch (node.modelType) {
        case 'branch': return node.fields
        case 'polymorph': {
            // Union of all form fields
            const seen = new Set<string>()
            const fields: typeof node.forms[0]['fields'] = []
            for (const form of node.forms) {
                for (const f of form.fields) {
                    if (!seen.has(f.name)) {
                        seen.add(f.name)
                        fields.push(f)
                    }
                }
            }
            return fields
        }
        default: return []
    }
}
