/**
 * Emits from.ts — the .from() API with inlined resolution per factory.
 *
 * Resolution logic is generated per-field based on known accepted types.
 * Each .from() directly calls sibling factories, and validation happens
 * automatically through the leaf factory functions.
 *
 * Separated from factories.ts for tree-shaking: users who only use the
 * regular API never load .from() resolution code.
 *
 * Note: @sittir/core also exports a generic FromContext/resolveFromInput
 * for non-codegen consumers. The generated code does NOT use it — all
 * resolution is inlined here for performance and tree-shaking.
 */

import type { KindMeta, FieldMeta, SupertypeInfo } from '../grammar-reader.ts';
import { extractLeafPattern } from '../grammar-reader.ts';
import { toTypeName, toFactoryName, toFieldName } from '../naming.ts';
import { selectConstructorField, escapeString } from './utils.ts';

export interface EmitFromConfig {
	grammar: string;
	nodes: KindMeta[];
	leafKinds: string[];
	keywordKinds: Map<string, string>;
	/** leaf kind → list of valid string values (enum-like) */
	leafValues?: Map<string, string[]>;
	/** Supertype info — for expanding _expression etc. to concrete subtypes */
	supertypes?: SupertypeInfo[];
}

/**
 * Emit the from.ts file containing .from() functions for all branch node kinds.
 */
export function emitFrom(config: EmitFromConfig): string {
	const { nodes, leafKinds, keywordKinds, leafValues, supertypes = [] } = config;
	const leafSet = new Set(leafKinds);
	const leafValueMap = leafValues ?? new Map<string, string[]>();

	// Build supertype → concrete subtypes map for expanding _expression etc.
	const supertypeMap = new Map<string, string[]>();
	for (const st of supertypes) {
		supertypeMap.set(st.name, st.subtypes);
	}

	const lines: string[] = [];
	lines.push('// Auto-generated by @sittir/codegen — do not edit');
	lines.push('// .from() API — ergonomic resolution with inlined per-field logic');
	lines.push('');

	// Type-only imports — named interfaces + *Tree interfaces for overload signatures
	const baseTypeImports = nodes.map(n => toTypeName(n.kind)).sort();
	const treeTypeImports = nodes.map(n => toTypeName(n.kind) + 'Tree').sort();
	lines.push(`import type { NodeData, ${[...baseTypeImports, ...treeTypeImports].join(', ')} } from './types.js';`);
	lines.push("import { isNodeData, isTreeNode, _inferBranch } from './utils.js';");
	lines.push('');

	// Import factory functions — only the ones actually referenced by .from() resolution
	const referencedFactories = collectReferencedFactories(nodes, leafSet, leafValueMap, keywordKinds);
	if (referencedFactories.size > 0) {
		const imports = [...referencedFactories].sort().join(', ');
		lines.push(`import { ${imports} } from './factories.js';`);
	}

	// Import assign functions for SgNode dispatch
	const assignImports = nodes.map(n => `assign${toTypeName(n.kind)}`).sort().join(', ');
	lines.push(`import { ${assignImports} } from './assign.js';`);

	// Import FromInput types from types.ts
	const fromInputImports: string[] = [];
	for (const node of nodes) {
		fromInputImports.push(`${toTypeName(node.kind)}FromInput`);
	}
	lines.push(`import type { ${fromInputImports.join(', ')} } from './types.js';`);

	// Import FromNode types from factories.ts
	const fromNodeImports: string[] = [];
	for (const node of nodes) {
		fromNodeImports.push(`${toTypeName(node.kind)}FromNode`);
	}
	lines.push(`import type { ${fromNodeImports.join(', ')} } from './factories.js';`);

	lines.push('');

	// _resolveByKind stays in from.ts — it references all *From functions
	lines.push('function _resolveByKind(kind: string, rest) {');
	lines.push('  switch (kind) {');
	for (const node of nodes) {
		const fromFn = `${toFactoryName(node.kind)}From`;
		lines.push(`    case '${node.kind}': return ${fromFn}(rest);`);
	}
	lines.push(`    default: throw new Error(\`Unknown kind for .from(): '\${kind}'\`);`);
	lines.push('  }');
	lines.push('}');
	lines.push('');

	// Per-kind .from() functions
	for (const node of nodes) {
		lines.push(emitFromFunction(node, leafSet, leafValueMap, keywordKinds, nodes, config.grammar, supertypeMap));
		lines.push('');
	}

	return lines.join('\n');
}

/**
 * Generate the ergonomic setter replacement lines for a node kind.
 * Shared between the plain-object resolution path and the SgNode dispatch path.
 */
function emitErgonomicSetters(
	node: KindMeta,
	ctorField: FieldMeta | null,
	baseVar: string,
	leafSet: Set<string>,
	leafValueMap: Map<string, string[]>,
	keywordKinds: Map<string, string>,
	allNodes: KindMeta[],
	grammar?: string,
	supertypeMap?: Map<string, string[]>,
): string[] {
	const lines: string[] = [];

	for (const field of node.fields) {
		if (field === ctorField) continue;
		const camel = toFieldName(field.name);
		const setterName = camel === 'type' ? 'typeField' : camel;
		if (field.multiple) {
			lines.push(`  ${baseVar}.${setterName} = (...v) => {`);
			lines.push(`    const arr = v.length === 1 && Array.isArray(v[0]) ? v[0] : v;`);
			lines.push(`    ${baseVar}.fields['${field.name}'] = arr.map((e) => ${emitResolveExpr('e', field, leafSet, leafValueMap, keywordKinds, allNodes, grammar, supertypeMap)});`);
			lines.push(`    return ${baseVar};`);
			lines.push(`  };`);
		} else {
			lines.push(`  ${baseVar}.${setterName} = (v) => { ${baseVar}.fields['${field.name}'] = ${emitResolveExpr('v', field, leafSet, leafValueMap, keywordKinds, allNodes, grammar, supertypeMap)}; return ${baseVar}; };`);
		}
	}

	if (node.hasChildren && node.children) {
		const childField: FieldMeta = {
			name: 'children',
			required: node.children.required,
			multiple: true,
			types: node.children.types,
			namedTypes: node.children.namedTypes,
		};
		lines.push(`  ${baseVar}.children = (...v) => {`);
		lines.push(`    const arr = v.length === 1 && Array.isArray(v[0]) ? v[0] : v;`);
		lines.push(`    ${baseVar}.fields.children = arr.map((e) => ${emitResolveExpr('e', childField, leafSet, leafValueMap, keywordKinds, allNodes, grammar, supertypeMap)});`);
		lines.push(`    return ${baseVar};`);
		lines.push(`  };`);
	}

	return lines;
}

/**
 * Emit a single .from() function for a branch node kind.
 *
 * Three input paths, all merging onto shared wiring:
 *   1. TreeNode (SgNode) → assign*() → wiring
 *   2. NodeData → pass through → wiring
 *   3. FromInput object → resolve fields → factory → wiring
 */
function emitFromFunction(
	node: KindMeta,
	leafSet: Set<string>,
	leafValueMap: Map<string, string[]>,
	keywordKinds: Map<string, string>,
	allNodes: KindMeta[],
	grammar?: string,
	supertypeMap?: Map<string, string[]>,
): string {
	const typeName = toTypeName(node.kind);
	const factoryName = toFactoryName(node.kind);
	const ctorField = selectConstructorField(node);

	const lines: string[] = [];

	// Function overloads for strict typing
	const exportName = `${factoryName}From`;
	lines.push(`export function ${exportName}(input: ${typeName}Tree): ${typeName}FromNode;`);
	lines.push(`export function ${exportName}(input: ${typeName}): ${typeName}FromNode;`);
	lines.push(`export function ${exportName}(input: ${typeName}FromInput & {readonly kind?: '${node.kind}'}): ${typeName}FromNode;`);
	// Implementation signature
	lines.push(`export function ${exportName}(input: ${typeName}Tree | ${typeName} | (${typeName}FromInput & {readonly kind?: '${node.kind}'})): ${typeName}FromNode {`);

	// --- Path 1: TreeNode → assign ---
	lines.push(`  let base;`);
	lines.push(`  if (isTreeNode(input)) {`);
	lines.push(`    base = assign${typeName}(input);`);

	// --- Path 2: NodeData → pass through ---
	lines.push(`  } else if (isNodeData(input)) {`);
	lines.push(`    base = ${factoryName}(input.fields);`);

	// --- Path 3: FromInput → resolve ---
	lines.push(`  } else {`);
	if (node.hasChildren) {
		lines.push(`    const obj = Array.isArray(input) ? { children: input } : input;`);
	} else {
		lines.push(`    const obj = input;`);
	}
	lines.push(`    const resolved = {};`);
	for (const field of node.fields) {
		lines.push(`    if (obj['${field.name}'] !== undefined) {`);
		if (field.multiple) {
			lines.push(`      const raw = obj['${field.name}'];`);
			lines.push(`      const arr = Array.isArray(raw) ? raw : [raw];`);
			lines.push(`      resolved['${field.name}'] = arr.map((v) => ${emitResolveExpr('v', field, leafSet, leafValueMap, keywordKinds, allNodes, grammar, supertypeMap)});`);
		} else {
			lines.push(`      resolved['${field.name}'] = ${emitResolveExpr(`obj['${field.name}']`, field, leafSet, leafValueMap, keywordKinds, allNodes, grammar, supertypeMap)};`);
		}
		if (field.multiple && field.required) {
			lines.push(`    } else {`);
			lines.push(`      resolved['${field.name}'] = [];`);
		}
		lines.push(`    }`);
	}
	if (node.hasChildren && node.children) {
		lines.push(`    if (obj['children'] !== undefined) {`);
		lines.push(`      const arr = Array.isArray(obj['children']) ? obj['children'] : [obj['children']];`);
		const childField: FieldMeta = {
			name: 'children',
			required: node.children.required,
			multiple: true,
			types: node.children.types,
			namedTypes: node.children.namedTypes,
		};
		lines.push(`      resolved['children'] = arr.map((v) => ${emitResolveExpr('v', childField, leafSet, leafValueMap, keywordKinds, allNodes, grammar, supertypeMap)});`);
		if (node.children.required) {
			lines.push(`    } else {`);
			lines.push(`      resolved['children'] = [];`);
		}
		lines.push(`    }`);
	}
	lines.push(`    base = ${factoryName}(resolved);`);
	lines.push(`  }`);
	lines.push('');

	// --- Shared wiring step: replace fluent setters with ergonomic ones ---
	lines.push(...emitErgonomicSetters(node, ctorField, 'base', leafSet, leafValueMap, keywordKinds, allNodes, grammar, supertypeMap));

	lines.push(`  return base;`);
	lines.push(`}`);

	return lines.join('\n');
}

/**
 * Emit an inline expression that resolves a value for a specific field.
 * The expression takes a variable name and returns resolved NodeData.
 *
 * This is the core of inlined resolution — no generic dispatcher needed.
 */
function emitResolveExpr(
	varName: string,
	field: FieldMeta,
	leafSet: Set<string>,
	leafValueMap: Map<string, string[]>,
	keywordKinds: Map<string, string>,
	allNodes: KindMeta[],
	grammar?: string,
	supertypeMap?: Map<string, string[]>,
): string {
	const leafTypes = field.namedTypes.filter(t => leafSet.has(t));
	// Expand supertypes (_expression etc.) to concrete subtypes, skip bare _
	const branchNodeSet = new Set(allNodes.map(n => n.kind));
	const rawBranch = field.namedTypes.filter(t => !leafSet.has(t) && t !== '_');
	const branchTypes: string[] = [];
	for (const t of rawBranch) {
		if (t.startsWith('_') && supertypeMap?.has(t)) {
			// Expand supertype to concrete subtypes (only branch kinds that have *From functions)
			for (const sub of supertypeMap.get(t)!) {
				if (branchNodeSet.has(sub) && !branchTypes.includes(sub)) branchTypes.push(sub);
			}
		} else if (!t.startsWith('_') && branchNodeSet.has(t)) {
			if (!branchTypes.includes(t)) branchTypes.push(t);
		}
	}
	const anonTokens = field.types.filter(t => !field.namedTypes.includes(t) && !t.startsWith('_'));

	// Simple case: single leaf type, no branches, no anon tokens
	if (leafTypes.length === 1 && branchTypes.length === 0 && anonTokens.length === 0) {
		const lt = leafTypes[0]!;
		if (keywordKinds.has(lt)) {
			// Keyword — 0-arg factory, match exact text
			const text = keywordKinds.get(lt)!;
			return `(isNodeData(${varName}) ? ${varName} : typeof ${varName} === 'string' && ${varName} === '${escapeString(text)}' ? ${toFactoryName(lt)}() : ${varName})`;
		}
		const factory = toFactoryName(lt);
		return `(isNodeData(${varName}) ? ${varName} : typeof ${varName} === 'string' || typeof ${varName} === 'number' || typeof ${varName} === 'boolean' ? ${factory}(String(${varName})) : ${varName})`;
	}

	// Simple case: single branch type, no leaves
	if (branchTypes.length === 1 && leafTypes.length === 0 && anonTokens.length === 0) {
		const factory = toFactoryName(branchTypes[0]!);
		const fromFn = `${factory}From`;
		return `(isNodeData(${varName}) ? ${varName} : Array.isArray(${varName}) ? ${fromFn}(${varName}) : typeof ${varName} === 'object' ? ${fromFn}(${varName}) : ${varName})`;
	}

	// Complex case: use inline IIFE for multi-type resolution
	return `((v => {${emitResolveBody('v', leafTypes, branchTypes, anonTokens, leafSet, leafValueMap, keywordKinds, allNodes, grammar)}})(${varName}))`;
}

/**
 * Emit the body of a resolve function (inside an IIFE or named function).
 * Handles all value types: NodeData passthrough, boolean, number, string, array, object.
 */
function emitResolveBody(
	v: string,
	leafTypes: string[],
	branchTypes: string[],
	anonTokens: string[],
	leafSet: Set<string>,
	leafValueMap: Map<string, string[]>,
	keywordKinds: Map<string, string>,
	allNodes: KindMeta[],
	grammar?: string,
): string {
	const parts: string[] = [];

	// NodeData passthrough
	parts.push(`if(isNodeData(${v}))return ${v};`);

	// Boolean → boolean_literal (if accepted, or fallback when field has no leaf types but grammar has the kind)
	if (leafTypes.includes('boolean_literal') || (leafTypes.length === 0 && leafSet.has('boolean_literal'))) {
		parts.push(`if(typeof ${v}==='boolean')return booleanLiteral(String(${v}));`);
	}

	// Number → integer_literal or float_literal
	const hasInt = leafTypes.includes('integer_literal') || (leafTypes.length === 0 && leafSet.has('integer_literal'));
	const hasFloat = leafTypes.includes('float_literal') || (leafTypes.length === 0 && leafSet.has('float_literal'));
	if (hasInt && hasFloat) {
		parts.push(`if(typeof ${v}==='number')return Number.isInteger(${v})?integerLiteral(String(${v})):floatLiteral(String(${v}));`);
	} else if (hasInt) {
		parts.push(`if(typeof ${v}==='number')return integerLiteral(String(${v}));`);
	} else if (hasFloat) {
		parts.push(`if(typeof ${v}==='number')return floatLiteral(String(${v}));`);
	}

	// String resolution
	parts.push(`if(typeof ${v}==='string'){${emitStringResolve(v, leafTypes, anonTokens, leafSet, leafValueMap, keywordKinds, grammar)}}`);

	// Array → wrap in single branch type as children
	if (branchTypes.length > 0) {
		if (branchTypes.length === 1) {
			const fromFn = `${toFactoryName(branchTypes[0]!)}From`;
			parts.push(`if(Array.isArray(${v}))return ${fromFn}(${v});`);
		} else {
			// Multiple branch types — can't auto-resolve arrays without kind
			parts.push(`if(Array.isArray(${v}))throw new Error('Array value with ambiguous branch types — use {kind} to disambiguate');`);
		}
	}

	// Object resolution
	parts.push(`if(typeof ${v}==='object'&&${v}!==null){${emitObjectResolve(v, branchTypes, allNodes)}}`);

	// Fallback error with diagnostic context
	parts.push(`throw new Error(\`Cannot resolve .from() value: got \${typeof ${v}}\`);`);

	return parts.join('');
}

/**
 * Emit string resolution logic for a specific field.
 */
function emitStringResolve(
	v: string,
	leafTypes: string[],
	anonTokens: string[],
	_leafSet: Set<string>,
	leafValueMap: Map<string, string[]>,
	keywordKinds: Map<string, string>,
	grammar?: string,
): string {
	const parts: string[] = [];

	// Helper: emit factory call — keyword factories take 0 args, text factories take 1
	const callLeaf = (kind: string, textVar: string) => {
		if (keywordKinds.has(kind)) {
			const expectedText = keywordKinds.get(kind)!;
			return `(${textVar}==='${escapeString(expectedText)}'?${toFactoryName(kind)}():(()=>{throw new Error(\`Expected '${escapeString(expectedText)}' for ${kind}, got '\${${textVar}}'\`)})())`;
		}
		return `${toFactoryName(kind)}(${textVar})`;
	};

	// Exactly one leaf type → use directly
	if (leafTypes.length === 1) {
		parts.push(`return ${callLeaf(leafTypes[0]!, v)};`);
		return parts.join('');
	}

	// Multiple leaf types → check enum values first
	if (leafTypes.length > 1) {
		for (const lt of leafTypes) {
			const vals = leafValueMap.get(lt);
			if (vals && vals.length > 0) {
				const valSet = vals.map(val => `'${escapeString(val)}'`).join(',');
				parts.push(`if([${valSet}].includes(${v}))return ${callLeaf(lt, v)};`);
			}
		}
	}

	// Anonymous tokens (operators)
	if (anonTokens.length > 0) {
		const tokenSet = anonTokens.map(t => `'${escapeString(t)}'`).join(',');
		parts.push(`if([${tokenSet}].includes(${v}))return{type:${v},fields:{},text:${v}};`);
	}

	// Pattern matching: for leaf types with grammar-derived regex patterns,
	// try each pattern and pick the first match. This ensures e.g.
	// 'hello' → string_content (not escape_sequence) when both are accepted.
	// Types without patterns and identifier-like types fall through to the
	// existing priority logic below.
	if (leafTypes.length > 1 && grammar) {
		const identKinds = new Set(['identifier', 'type_identifier', 'field_identifier', 'shorthand_field_identifier']);

		for (const lt of leafTypes) {
			if (identKinds.has(lt)) continue; // handled by priority logic below
			const vals = leafValueMap.get(lt);
			if (vals && vals.length > 0) continue; // already handled by enum check above
			const pattern = extractLeafPattern(grammar, lt);
			if (pattern && !pattern.includes('//') && !pattern.includes('/*') && !pattern.includes('\\x')) {
				try {
					const flags = pattern.includes('\\p{') ? 'u' : '';
					new RegExp(`^${pattern}$`, flags);
					parts.push(`if(/^${pattern.replace(/`/g, '\\`')}$/${flags}.test(${v}))return ${callLeaf(lt, v)};`);
				} catch {
					// Pattern not safe for JS — skip
				}
			}
		}
	}

	// Prefer identifier-like types
	const hasTypeIdent = leafTypes.includes('type_identifier');
	const hasIdent = leafTypes.includes('identifier');
	if (hasTypeIdent && hasIdent) {
		parts.push(`return ${callLeaf('type_identifier', v)};`);
		return parts.join('');
	}

	const identPriority = ['identifier', 'type_identifier', 'field_identifier', 'shorthand_field_identifier'];
	for (const ik of identPriority) {
		if (leafTypes.includes(ik)) {
			parts.push(`return ${callLeaf(ik, v)};`);
			return parts.join('');
		}
	}

	// Fallback: prefer leaf types without a grammar pattern (they accept any string)
	if (leafTypes.length > 0 && grammar) {
		const noPatternKind = leafTypes.find(lt => !extractLeafPattern(grammar, lt));
		if (noPatternKind) {
			parts.push(`return ${callLeaf(noPatternKind, v)};`);
			return parts.join('');
		}
	}
	// Last resort: first leaf type
	if (leafTypes.length > 0) {
		parts.push(`return ${callLeaf(leafTypes[0]!, v)};`);
		return parts.join('');
	}

	// No leaf types — cannot resolve string
	parts.push(`throw new Error(\`Cannot resolve string value: no leaf types accepted for this field\`);`);
	return parts.join('');
}

/**
 * Emit object resolution logic for a specific field.
 */
function emitObjectResolve(
	v: string,
	branchTypes: string[],
	allNodes: KindMeta[],
): string {
	const parts: string[] = [];

	// Explicit kind → dispatch to the right .from()
	parts.push(`if('kind' in ${v}&&typeof ${v}.kind==='string'){`);
	// Build dispatch table for known branch types
	parts.push(`const{kind:k,...rest}=${v};`);
	if (branchTypes.length > 0) {
		parts.push(`switch(k){`);
		for (const bt of branchTypes) {
			parts.push(`case '${bt}':return ${toFactoryName(bt)}From(rest);`);
		}
		// Also allow any valid kind for flexibility
		parts.push(`}`);
	}
	// General dispatch for any kind (handles kinds not in branchTypes)
	parts.push(`return _resolveByKind(k,rest);`);
	parts.push(`}`);

	// Single branch type → use directly
	if (branchTypes.length === 1) {
		parts.push(`return ${toFactoryName(branchTypes[0]!)}From(${v});`);
	} else if (branchTypes.length > 1) {
		// Multiple → score by field matching, then dispatch
		parts.push(`const _k=_inferBranch(${v},${JSON.stringify(branchTypes)});`);
		parts.push(`if(_k)return _resolveByKind(_k,${v});`);
		parts.push(`throw new Error(\`Cannot infer kind for object with keys: \${Object.keys(${v}).join(', ')}. Candidates: ${branchTypes.join(', ')}. Use { kind: '...' } to disambiguate.\`);`);
	} else {
		parts.push(`throw new Error('No branch types accepted for object value');`);
	}

	return parts.join('');
}

/**
 * Collect all factory function names referenced by .from() resolution.
 */
function collectReferencedFactories(
	nodes: KindMeta[],
	leafSet: Set<string>,
	leafValueMap: Map<string, string[]>,
	keywordKinds: Map<string, string>,
): Set<string> {
	const refs = new Set<string>();

	// All branch factories (for regular factory calls and .from() dispatch)
	for (const node of nodes) {
		refs.add(toFactoryName(node.kind));
	}

	// Leaf factories referenced by field resolution
	for (const node of nodes) {
		for (const field of [...node.fields, ...(node.children ? [{ name: 'children', required: node.children.required, multiple: true, types: node.children.types, namedTypes: node.children.namedTypes } satisfies FieldMeta] : [])]) {
			for (const t of field.namedTypes) {
				if (leafSet.has(t)) {
					refs.add(toFactoryName(t));
				}
			}
		}
		// Boolean/number always potentially needed
		if (leafSet.has('boolean_literal')) refs.add(toFactoryName('boolean_literal'));
		if (leafSet.has('integer_literal')) refs.add(toFactoryName('integer_literal'));
		if (leafSet.has('float_literal')) refs.add(toFactoryName('float_literal'));
	}

	return refs;
}

