/**
 * YAML render template emitter.
 *
 * Walks the raw grammar rule tree to produce ast-grep-style $VARIABLE templates.
 * Detects CHOICE+BLANK patterns to synthesize clauses for optional token+field groups.
 * Emits per-rule joinBy from separator metadata.
 */

import { stringify as yamlStringify } from 'yaml';
import type { GrammarRule } from '../grammar.ts';
import { loadGrammar } from '../grammar.ts';
import type { HydratedNodeModel, HydratedChildrenModel } from '../node-model.ts';
import { isTupleChildren, eachChildSlot } from '../node-model.ts';
import { type StructuralNode, structuralNodes, fieldsOf, childSlotNames } from './utils.ts';
import { buildProjectionContext, projectKinds } from './kind-projections.ts';
import type { RulesConfig, TemplateRule } from '@sittir/types';

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

export interface EmitRulesYamlConfig {
	grammar: string;
	nodes: HydratedNodeModel[];
	grammarSha: string;
	treeSitterVersion?: string;
}

/**
 * Emit the full templates.yaml content for a grammar.
 */
export function emitTemplatesYaml(config: EmitRulesYamlConfig): string {
	const { grammar, nodes, grammarSha, treeSitterVersion } = config;
	const grammarRules = loadGrammar(grammar).rules;

	const extensions = grammarExtensions(grammar);
	const rulesConfig: RulesConfig = {
		language: grammar,
		extensions,
		expandoChar: null,
		metadata: {
			grammarSha,
			...(treeSitterVersion ? { treeSitterVersion } : {}),
		},
		rules: {},
	};

	const ctx = buildProjectionContext(new Map(nodes.map(n => [n.kind, n])));
	for (const node of structuralNodes(nodes)) {
		const rule = emitRuleForNode(node, grammarRules, ctx);
		rulesConfig.rules[node.kind] = rule;
	}

	return `# Auto-generated by @sittir/codegen — do not edit\n${yamlStringify(rulesConfig, { lineWidth: 0 })}`;
}

// ---------------------------------------------------------------------------
// Per-node rule emission
// ---------------------------------------------------------------------------

interface ClauseEntry {
	name: string;       // e.g. "return_type_clause"
	template: string;   // e.g. "-> $RETURN_TYPE "
}

function emitRuleForNode(node: StructuralNode, grammarRules: Record<string, GrammarRule>, ctx: ReturnType<typeof buildProjectionContext>): TemplateRule {
	const nodeFields = fieldsOf(node);

	// Build field metadata maps
	const fieldRequired = new Map<string, boolean>();
	const fieldMultiple = new Map<string, boolean>();
	const fieldSeparators = new Map<string, string>();

	for (const f of nodeFields) {
		fieldRequired.set(f.name, f.required);
		fieldMultiple.set(f.name, f.multiple);
		if (f.multiple && 'separator' in f && f.separator) {
			fieldSeparators.set(f.name, f.separator);
		}
	}

	// Get separator data from enriched rule (only branch/container rules have separators)
	const enrichedRule = node.rule;
	if (enrichedRule && ('separators' in enrichedRule) && enrichedRule.separators) {
		for (const [key, sep] of enrichedRule.separators) {
			if (!fieldSeparators.has(key)) {
				fieldSeparators.set(key, sep);
			}
		}
	}

	// Build child slot mapping: grammar kind → { varName, multiple }
	// For tuple children, each slot has specific kinds. For single children, all kinds map to CHILDREN.
	const childSlotMap = buildChildSlotMap(node, ctx);

	// Walk the grammar rule tree
	const rawRule = node.rule?.rule;
	const seen = new Set<string>();
	const clauses: ClauseEntry[] = [];
	const parts = rawRule
		? ruleToTemplate(rawRule, false, seen, fieldRequired, fieldMultiple, grammarRules, clauses, false, childSlotMap)
		: [];

	// Append missing fields the walker didn't reach
	for (const f of nodeFields) {
		if (!seen.has(f.name)) {
			const varName = f.name.toUpperCase();
			parts.push(f.multiple ? ` $$$${varName}` : ` $${varName}`);
			seen.add(f.name);
		}
	}

	// Append missing child slots the walker didn't reach
	const hasChildren = node.children != null;
	if (hasChildren) {
		const slotNames = childSlotNames(node.children!, ctx);
		if (isTupleChildren(node.children!)) {
			eachChildSlot(node.children!, (slot, i) => {
				const slotName = slotNames[i]!;
				if (!seen.has(`child:${slotName}`)) {
					const varName = slotName.toUpperCase().replace(/[a-z]/g, (c) => c.toUpperCase());
					parts.push(slot.multiple ? ` $$$${toSnakeUpper(slotName)}` : ` $${toSnakeUpper(slotName)}`);
				}
			});
		} else if (!seen.has('children')) {
			parts.push(' $$$CHILDREN');
		}
	}

	const templateStr = parts.join('').replace(/\s+/g, ' ').trim();

	// Build joinBy
	const joinBy = buildJoinBy(fieldMultiple, fieldSeparators, node);

	// Determine if we need object form
	if (clauses.length === 0 && joinBy === undefined) {
		return templateStr;
	}

	const ruleObj: Record<string, unknown> = { template: templateStr };
	for (const c of clauses) {
		ruleObj[c.name] = c.template;
	}
	if (joinBy !== undefined) {
		ruleObj['joinBy'] = joinBy;
	}

	return ruleObj as unknown as TemplateRule;
}

/** Convert camelCase to UPPER_SNAKE for template variable names. */
function toSnakeUpper(camel: string): string {
	return camel.replace(/[A-Z]/g, c => `_${c}`).toUpperCase();
}

interface ChildSlotInfo {
	varName: string;  // UPPER_SNAKE variable name
	multiple: boolean;
	slotName: string; // camelCase slot name (for tracking in seen set)
}

/** Build a mapping from grammar kind → child slot variable info. */
function buildChildSlotMap(node: StructuralNode, ctx: ReturnType<typeof buildProjectionContext>): Map<string, ChildSlotInfo> {
	const map = new Map<string, ChildSlotInfo>();
	if (!node.children) return map;

	const slotNames = childSlotNames(node.children, ctx);

	if (isTupleChildren(node.children)) {
		eachChildSlot(node.children, (slot, i) => {
			const slotName = slotNames[i]!;
			const varName = toSnakeUpper(slotName);
			for (const k of slot.kinds) {
				map.set(k.kind, { varName, multiple: slot.multiple, slotName });
			}
		});
	} else {
		// Single children slot — all kinds map to CHILDREN
		const slot = Array.isArray(node.children) ? node.children[0]! : node.children;
		for (const k of slot.kinds) {
			map.set(k.kind, { varName: 'CHILDREN', multiple: slot.multiple, slotName: 'children' });
		}
	}

	return map;
}

// ---------------------------------------------------------------------------
// Grammar rule tree walker
// ---------------------------------------------------------------------------

function ruleToTemplate(
	rule: GrammarRule,
	optional: boolean,
	seen: Set<string>,
	fieldRequired: Map<string, boolean>,
	fieldMultiple: Map<string, boolean>,
	gr: Record<string, GrammarRule>,
	clauses: ClauseEntry[],
	immediate: boolean,
	childSlotMap: Map<string, ChildSlotInfo>,
): string[] {
	switch (rule.type) {
		case 'SEQ': {
			const parts: string[] = [];
			for (let i = 0; i < rule.members.length; i++) {
				const member = rule.members[i]!;
				const isFirst = i === 0;
				const memberParts = ruleToTemplate(member, optional, seen, fieldRequired, fieldMultiple, gr, clauses, immediate, childSlotMap);
				if (!isFirst && memberParts.length > 0 && parts.length > 0) {
					// Add space between parts unless immediate
					const lastPart = parts[parts.length - 1]!;
					const nextPart = memberParts[0]!;
					if (!immediate && !isAttached(lastPart, nextPart)) {
						parts.push(' ');
					}
				}
				parts.push(...memberParts);
			}
			return parts;
		}

		case 'STRING':
			if (optional) return [];
			return [rule.value];

		case 'FIELD': {
			if (seen.has(rule.name)) return [];
			seen.add(rule.name);
			const multi = fieldMultiple.get(rule.name) ?? false;
			const varName = rule.name.toUpperCase();
			return [multi ? `$$$${varName}` : `$${varName}`];
		}

		case 'SYMBOL': {
			// Inline _-prefixed (hidden/abstract) rules that contain fields
			if (rule.name.startsWith('_') && gr[rule.name]) {
				const inlineSeen = new Set(seen);
				const inlined = ruleToTemplate(gr[rule.name]!, optional, inlineSeen, fieldRequired, fieldMultiple, gr, clauses, immediate, childSlotMap);
				// Filter to only parts with fields that belong to this node
				const hasRelevantFields = [...inlineSeen].some(f => !seen.has(f) && fieldRequired.has(f));
				if (hasRelevantFields) {
					for (const f of inlineSeen) {
						if (fieldRequired.has(f)) seen.add(f);
					}
					return inlined;
				}
			}
			// Check if this symbol maps to a named child slot
			const childSlot = childSlotMap.get(rule.name);
			if (childSlot) {
				if (seen.has(`child:${childSlot.slotName}`)) return [];
				seen.add(`child:${childSlot.slotName}`);
				return [childSlot.multiple ? `$$$${childSlot.varName}` : `$${childSlot.varName}`];
			}
			// Unknown symbol — generic children
			if (seen.has('children')) return [];
			seen.add('children');
			return ['$$$CHILDREN'];
		}

		case 'CHOICE': {
			const hasBlank = rule.members.some(m => m.type === 'BLANK');
			if (hasBlank) {
				// Optional group — check if we should synthesize a clause
				const nonBlank = rule.members.filter(m => m.type !== 'BLANK');
				if (nonBlank.length === 1) {
					const inner = nonBlank[0]!;
					const clauseResult = tryClause(inner, seen, fieldRequired, fieldMultiple, gr, clauses, immediate);
					if (clauseResult) return clauseResult;
				}

				// No clause — mark fields as optional
				const parts: string[] = [];
				for (const m of rule.members) {
					if (m.type === 'BLANK') continue;
					parts.push(...ruleToTemplate(m, true, seen, fieldRequired, fieldMultiple, gr, clauses, immediate, childSlotMap));
				}
				return parts;
			}

			// No BLANK — pick the branch with the most field coverage
			let best: string[] = [];
			let bestCount = -1;
			let bestSeen = new Set<string>();
			for (const m of rule.members) {
				const branchSeen = new Set(seen);
				const branchClauses: ClauseEntry[] = [];
				const branchParts = ruleToTemplate(m, optional, branchSeen, fieldRequired, fieldMultiple, gr, branchClauses, immediate, childSlotMap);
				const fieldCount = [...branchSeen].filter(f => !seen.has(f)).length;
				if (fieldCount > bestCount) {
					bestCount = fieldCount;
					best = branchParts;
					bestSeen = branchSeen;
					clauses.push(...branchClauses);
				}
			}
			for (const f of bestSeen) seen.add(f);
			return best;
		}

		case 'REPEAT':
		case 'REPEAT1':
			return ruleToTemplate(rule.content, optional, seen, fieldRequired, fieldMultiple, gr, clauses, immediate, childSlotMap);

		case 'PREC':
		case 'PREC_LEFT':
		case 'PREC_RIGHT':
		case 'PREC_DYNAMIC':
			return ruleToTemplate(rule.content, optional, seen, fieldRequired, fieldMultiple, gr, clauses, immediate, childSlotMap);

		case 'TOKEN':
			return ruleToTemplate(rule.content, optional, seen, fieldRequired, fieldMultiple, gr, clauses, false, childSlotMap);

		case 'IMMEDIATE_TOKEN': {
			let inner: GrammarRule = rule.content;
			while (inner.type === 'PREC' || inner.type === 'PREC_LEFT' || inner.type === 'PREC_RIGHT' || inner.type === 'PREC_DYNAMIC') {
				inner = inner.content;
			}
			if (inner.type === 'STRING') {
				if (optional) return [];
				return [inner.value]; // no leading space — immediate
			}
			return ruleToTemplate(rule.content, optional, seen, fieldRequired, fieldMultiple, gr, clauses, true, childSlotMap);
		}

		case 'ALIAS':
			if (rule.named) {
				// Named alias — treat like a symbol
				const aliasSlot = childSlotMap.get(rule.value ?? '');
				if (aliasSlot) {
					if (seen.has(`child:${aliasSlot.slotName}`)) return [];
					seen.add(`child:${aliasSlot.slotName}`);
					return [aliasSlot.multiple ? `$$$${aliasSlot.varName}` : `$${aliasSlot.varName}`];
				}
				if (seen.has('children')) return [];
				seen.add('children');
				return ['$$$CHILDREN'];
			}
			if (rule.value) {
				if (optional) return [];
				return [rule.value];
			}
			return ruleToTemplate(rule.content, optional, seen, fieldRequired, fieldMultiple, gr, clauses, immediate, childSlotMap);

		case 'BLANK':
		case 'PATTERN':
			return [];
	}
}

// ---------------------------------------------------------------------------
// Clause synthesis
// ---------------------------------------------------------------------------

/**
 * Try to synthesize a clause from a CHOICE branch.
 * A clause bundles anonymous tokens with a non-required field:
 *   CHOICE([SEQ(STRING("->"), FIELD(return_type)), BLANK])
 *   → return_type_clause: "-> $RETURN_TYPE "
 */
function tryClause(
	rule: GrammarRule,
	seen: Set<string>,
	fieldRequired: Map<string, boolean>,
	fieldMultiple: Map<string, boolean>,
	gr: Record<string, GrammarRule>,
	clauses: ClauseEntry[],
	immediate: boolean,
): string[] | null {
	// Must be a SEQ with at least one STRING and one FIELD
	const members = rule.type === 'SEQ' ? rule.members : [rule];

	const tokens: string[] = [];
	const fields: { name: string; multi: boolean }[] = [];

	for (const m of members) {
		const unwrapped = unwrapPrec(m);
		if (unwrapped.type === 'STRING') {
			tokens.push(unwrapped.value);
		} else if (unwrapped.type === 'FIELD') {
			fields.push({ name: unwrapped.name, multi: fieldMultiple.get(unwrapped.name) ?? false });
		} else if (unwrapped.type === 'SYMBOL' && !unwrapped.name.startsWith('_')) {
			// Named symbol in optional context — treat as field-like
			fields.push({ name: unwrapped.name, multi: false });
		} else {
			// Complex structure — don't clausify
			return null;
		}
	}

	// Need at least one token and one field to form a clause
	if (tokens.length === 0 || fields.length === 0) return null;

	// Only clausify if the primary field is non-required
	const primaryField = fields[0]!;
	if (fieldRequired.get(primaryField.name) === true) return null;

	// Build clause template
	const clauseParts: string[] = [];
	for (const m of members) {
		const unwrapped = unwrapPrec(m);
		if (unwrapped.type === 'STRING') {
			clauseParts.push(unwrapped.value);
		} else if (unwrapped.type === 'FIELD') {
			const varName = unwrapped.name.toUpperCase();
			const multi = fieldMultiple.get(unwrapped.name) ?? false;
			clauseParts.push(multi ? `$$$${varName}` : `$${varName}`);
			seen.add(unwrapped.name);
		}
	}

	const clauseName = `${primaryField.name}_clause`;
	const clauseTemplate = clauseParts.join(' ');
	clauses.push({ name: clauseName, template: clauseTemplate });

	// Return a reference to the clause in the parent template
	return [`$${clauseName.toUpperCase()}`];
}

function unwrapPrec(rule: GrammarRule): GrammarRule {
	while (rule.type === 'PREC' || rule.type === 'PREC_LEFT' || rule.type === 'PREC_RIGHT' || rule.type === 'PREC_DYNAMIC') {
		rule = rule.content;
	}
	return rule;
}

// ---------------------------------------------------------------------------
// joinBy construction
// ---------------------------------------------------------------------------

/** Format raw separator token with conventional spacing. */
function formatSeparator(sep: string): string {
	// Comma and semicolon conventionally have a trailing space
	if (sep === ',') return ', ';
	if (sep === ';') return '; ';
	return sep;
}

function buildJoinBy(
	fieldMultiple: Map<string, boolean>,
	fieldSeparators: Map<string, string>,
	node: StructuralNode,
): string | Record<string, string> | undefined {
	// Collect all multi-fields that have separators
	const seps: Record<string, string> = {};
	let count = 0;

	for (const [fieldName, sep] of fieldSeparators) {
		if (fieldMultiple.get(fieldName)) {
			seps[fieldName.toUpperCase()] = formatSeparator(sep);
			count++;
		}
	}

	// Also check children separator
	if (node.children) {
		const childArr = Array.isArray(node.children) ? node.children : [node.children];
		for (const child of childArr) {
			if (child.multiple && 'separator' in child && child.separator) {
				seps['CHILDREN'] = formatSeparator(child.separator);
				count++;
			}
		}
	}

	if (count === 0) return undefined;

	// If all separators are the same, use string form
	const values = Object.values(seps);
	const allSame = values.every(v => v === values[0]);
	if (allSame && count > 0) return values[0];

	return seps;
}

// ---------------------------------------------------------------------------
// Formatting helpers
// ---------------------------------------------------------------------------

/** Check if two template parts should be attached (no space between). */
function isAttached(prev: string, next: string): boolean {
	// Opening delimiters attach to preceding content
	if (next === '(' || next === '[' || next === '<' || next === '{') return true;
	// Closing delimiters attach to preceding content
	if (prev === '(' || prev === '[' || prev === '<' || prev === '{') return true;
	if (next === ')' || next === ']' || next === '>' || next === '}') return true;
	// Dot accessor
	if (prev === '.' || next === '.') return true;
	// Double colon
	if (prev === '::' || next === '::') return true;
	// $ variable after delimiter
	if (prev.endsWith('(') || prev.endsWith('[') || prev.endsWith('<') || prev.endsWith('{')) return true;
	return false;
}

// ---------------------------------------------------------------------------
// Grammar metadata helpers
// ---------------------------------------------------------------------------

function grammarExtensions(grammar: string): string[] {
	switch (grammar) {
		case 'rust': return ['rs'];
		case 'typescript': return ['ts', 'tsx'];
		case 'python': return ['py'];
		case 'javascript': return ['js', 'jsx'];
		case 'go': return ['go'];
		case 'java': return ['java'];
		case 'c': return ['c', 'h'];
		case 'cpp': return ['cpp', 'cc', 'cxx', 'hpp', 'hxx', 'h'];
		default: return [];
	}
}
