/**
 * Test scaffold emitter (new architecture).
 *
 * Generates per-node tests that verify:
 *   1. Factory produces NodeData with correct kind
 *   2. render(node, rules) returns non-empty string
 *   3. Rendered output contains required tokens from grammar
 *
 * Also generates terminal/keyword tests.
 */

import type { HydratedNodeModel } from '../node-model.ts';
import { eachChildSlot } from '../node-model.ts';
import { collectRequiredTokens } from '../grammar-reader.ts';
import { toFieldName, toIrKey, toFactoryName } from '../naming.ts';
import { type StructuralNode, structuralNodes, fieldsOf, leafKindsOf, keywordKindsOf, leafValuesOf, childSlotNames } from './utils.ts';
import { buildProjectionContext, projectKinds, type ProjectionContext } from './kind-projections.ts';

export interface EmitTestsConfig {
	grammar: string;
	nodes: HydratedNodeModel[];
}

/**
 * Emit a single test file covering all node kinds for a grammar.
 */
export function emitTests(config: EmitTestsConfig): string {
	const { grammar } = config;
	const nodes = structuralNodes(config.nodes);
	const leafKinds = leafKindsOf(config.nodes);
	const keywordKinds = keywordKindsOf(config.nodes);
	const leafSet = new Set(leafKinds);
	const keywordKindMap = keywordKinds;
	const leafValueMap = leafValuesOf(config.nodes);
	const ctx = buildProjectionContext(new Map(config.nodes.map(n => [n.kind, n])));

	// Build ir key map with same collision resolution as ir-namespace
	const irKeyMap = new Map<string, string>(); // kind → resolved ir key
	const usedKeys = new Map<string, string>(); // irKey → kind
	for (const node of nodes) {
		irKeyMap.set(node.kind, resolveIrKey(node.kind, usedKeys));
	}
	for (const [kind] of keywordKinds) {
		irKeyMap.set(kind, resolveIrKey(kind, usedKeys));
	}
	for (const kind of leafKinds) {
		if (keywordKinds.has(kind)) continue;
		irKeyMap.set(kind, resolveIrKey(kind, usedKeys));
	}

	// Build node-by-kind map for fallback factory lookups
	const nodeByKind = new Map<string, StructuralNode>();
	for (const node of nodes) nodeByKind.set(node.kind, node);

	const dc: DummyCtx = { ctx, leafSet, keywordKinds: keywordKindMap, leafValueMap, irKeyMap, nodeByKind, visiting: new Set() };

	const lines: string[] = [];
	lines.push('// Auto-generated by @sittir/codegen — do not edit');
	lines.push("import { describe, it, expect } from 'vitest';");
	lines.push("import { ir } from '../src/ir.js';");
	lines.push("import { createRenderer } from '@sittir/core';");
	lines.push("import { join, dirname } from 'node:path';");
	lines.push("import { fileURLToPath } from 'node:url';");
	lines.push('');
	lines.push('const __dirname = dirname(fileURLToPath(import.meta.url));');
	lines.push("const { render } = createRenderer(join(__dirname, '..', 'templates.yaml'));");
	lines.push('');

	// Branch node tests
	for (const node of nodes) {
		const irKey = irKeyMap.get(node.kind)!;
		const requiredTokens = collectRequiredTokens(grammar, node.kind);

		lines.push(`describe('${node.kind}', () => {`);

		// Test 1: factory produces correct kind
		lines.push(`  it('factory produces NodeData with kind', () => {`);
		lines.push(`    const node = ir.${irKey}(${minimalArgs(node, dc)});`);
		lines.push(`    expect(node.type).toBe('${node.kind}');`);
		lines.push(`  });`);

		// Test 2: render produces non-empty string (skip for all-optional nodes with no tokens)
		const hasRequiredContent = requiredTokens.length > 0 ||
			minimalArgs(node, dc) !== '';
		if (hasRequiredContent) {
			lines.push(`  it('renders to non-empty string', () => {`);
			lines.push(`    const node = ir.${irKey}(${minimalArgs(node, dc)});`);
			lines.push(`    const source = render(node);`);
			lines.push(`    expect(source.length).toBeGreaterThan(0);`);
			lines.push(`  });`);
		}

		// Test 3: rendered output contains required tokens
		if (requiredTokens.length > 0) {
			lines.push(`  it('contains required tokens', () => {`);
			lines.push(`    const node = ir.${irKey}(${minimalArgs(node, dc)});`);
			lines.push(`    const source = render(node);`);
			for (const token of requiredTokens) {
				lines.push(`    expect(source).toContain('${escapeString(token)}');`);
			}
			lines.push(`  });`);
		}

		// Test 4: node.render() method works
		lines.push(`  it('node.render() works', () => {`);
		lines.push(`    const node = ir.${irKey}(${minimalArgs(node, dc)});`);
		lines.push(`    expect(typeof node.render).toBe('function');`);
		lines.push(`    expect(node.render()).toBe(render(node));`);
		lines.push(`  });`);

		// Test 5: render with all fields (optional + required) produces non-empty string
		const full = fullArgs(node, dc);
		const fullHasContent = full !== '' && !full.includes("type: 'unknown'") && (hasRequiredContent || fullHasScalarValues(node, dc));
		if (fullHasContent) {
			lines.push(`  it('renders with optional fields', () => {`);
			lines.push(`    const node = ir.${irKey}(${full});`);
			lines.push(`    const source = render(node);`);
			lines.push(`    expect(source.length).toBeGreaterThan(0);`);
			lines.push(`  });`);
		}

		lines.push(`});`);
		lines.push('');
	}

	// Terminal/keyword tests
	lines.push("describe('terminal factories', () => {");

	// Keyword tests
	for (const [kind, text] of keywordKinds) {
		const irKey = irKeyMap.get(kind)!;
		lines.push(`  it('${kind} produces fixed text', () => {`);
		lines.push(`    const node = ir.${irKey}();`);
		lines.push(`    expect(node.type).toBe('${kind}');`);
		lines.push(`    expect(node.text).toBe('${escapeString(text)}');`);
		lines.push(`  });`);
	}

	// Leaf tests (non-keyword)
	for (const kind of leafKinds) {
		if (keywordKinds.has(kind)) continue;
		const irKey = irKeyMap.get(kind)!;
		// Use a value that satisfies template literal / enum constraints
		const enumVals = leafValuesOf(config.nodes).get(kind) ?? [];
		const knownExpr = leafTestExpr(kind);
		let valueExpr: string; // Full JS expression including quotes
		if (enumVals.length > 0) {
			valueExpr = `'${escapeString(enumVals[0]!)}'`;
		} else if (knownExpr) {
			valueExpr = knownExpr;
		} else {
			valueExpr = "'test_value'";
		}
		lines.push(`  it('${kind} accepts text', () => {`);
		lines.push(`    const node = ir.${irKey}(${valueExpr});`);
		lines.push(`    expect(node.type).toBe('${kind}');`);
		lines.push(`    expect(node.text).toBe(${valueExpr});`);
		lines.push(`  });`);
	}

	lines.push('});');

	return lines.join('\n');
}

/** Shared context bag for test value generation, avoids threading many params. */
interface DummyCtx {
	ctx: ProjectionContext;
	leafSet: Set<string>;
	keywordKinds: Map<string, string>;
	leafValueMap: Map<string, string[]>;
	irKeyMap: Map<string, string>;
	nodeByKind: Map<string, StructuralNode>;
	visiting: Set<string>;
}

/**
 * Generate minimal factory arguments for a node kind.
 * Provides all required fields and children as a declarative config object.
 */
function minimalArgs(node: StructuralNode, dc: DummyCtx): string {
	const requiredFields = fieldsOf(node).filter(f => f.required);
	const requiredChildren: { name: string; kinds: readonly HydratedNodeModel[]; multiple: boolean }[] = [];

	if (node.children != null) {
		const slotNames = childSlotNames(node.children, dc.ctx);
		eachChildSlot(node.children, (slot, i) => {
			if (slot.required) {
				requiredChildren.push({ name: slotNames[i]!, kinds: slot.kinds, multiple: slot.multiple });
			}
		});
	}

	// Skip children whose names overlap with field property names (override-promoted fields)
	const fieldKeys = new Set(requiredFields.map(f => f.propertyName ?? toFieldName(f.name)));
	const allRequired = [
		...requiredFields.map(f => ({ key: f.propertyName ?? toFieldName(f.name), field: f })),
		...requiredChildren.filter(c => !fieldKeys.has(c.name)).map(c => ({ key: c.name, field: c })),
	];

	if (allRequired.length === 0) return '';

	const entries = allRequired.map(({ key, field }) => `${key}: ${dummyValue(field, dc)}`);
	return `{ ${entries.join(', ')} }`;
}

/**
 * Generate all-fields factory arguments (required + optional) for testing optional field rendering.
 * Returns '' if there are no optional fields beyond the required ones.
 */
function fullArgs(node: StructuralNode, dc: DummyCtx): string {
	const allFields = fieldsOf(node);
	const optionalFields = allFields.filter(f => !f.required);
	const allChildren: { name: string; kinds: readonly HydratedNodeModel[]; multiple: boolean; required: boolean }[] = [];

	if (node.children != null) {
		const slotNames = childSlotNames(node.children, dc.ctx);
		eachChildSlot(node.children, (slot, i) => {
			allChildren.push({ name: slotNames[i]!, kinds: slot.kinds, multiple: slot.multiple, required: slot.required });
		});
	}
	// Skip children whose names overlap with field property names (override-promoted fields)
	const fieldKeys = new Set(allFields.map(f => f.propertyName ?? toFieldName(f.name)));
	const optionalChildren = allChildren.filter(c => !c.required && !fieldKeys.has(c.name));

	if (optionalFields.length === 0 && optionalChildren.length === 0) return '';

	const entries = [
		...allFields.map(f => ({ key: f.propertyName ?? toFieldName(f.name), field: f })),
		...allChildren.filter(c => !fieldKeys.has(c.name)).map(c => ({ key: c.name, field: c })),
	];

	const parts = entries.map(({ key, field }) => `${key}: ${dummyValue(field, dc)}`);
	return `{ ${parts.join(', ')} }`;
}

/**
 * Check if fullArgs would produce at least one scalar (non-empty-array) value.
 * Nodes with only optional multiple children produce only `[]` entries, which render to nothing.
 */
function fullHasScalarValues(node: StructuralNode, dc: DummyCtx): boolean {
	const allFields = fieldsOf(node);
	if (allFields.some(f => !f.required && !f.multiple)) return true; // optional scalar fields produce values
	if (node.children != null) {
		let hasNonMultipleOptional = false;
		eachChildSlot(node.children, (slot) => {
			if (!slot.required && !slot.multiple) hasNonMultipleOptional = true;
		});
		if (hasNonMultipleOptional) return true;
	}
	return false;
}

/** Generate a dummy value for a field based on its types. */
function dummyValue(
	field: { name: string; kinds: readonly HydratedNodeModel[]; multiple?: boolean },
	dc: DummyCtx,
): string {
	const proj = projectKinds(field.kinds, dc.ctx);
	const named = proj.expandedAll;
	const concrete = expandForTests(named, dc.ctx);

	if (concrete.includes('type_identifier')) {
		return wrapMultiple(field.multiple, `ir.typeIdentifier('Test${capitalize(field.name)}') as any`);
	}
	if (concrete.includes('field_identifier')) {
		return wrapMultiple(field.multiple, `ir.fieldIdentifier('test_${field.name}') as any`);
	}
	if (concrete.includes('identifier')) {
		return wrapMultiple(field.multiple, `ir.identifier('test_${field.name}') as any`);
	}

	if (field.multiple) {
		return '[]';
	}

	for (const kind of concrete) {
		if (dc.leafSet.has(kind)) {
			const fixedText = dc.keywordKinds.get(kind);
			const irKey = dc.irKeyMap.get(kind)!;
			if (fixedText !== undefined) {
				return `ir.${irKey}() as any`;
			}
			const enumVals = dc.leafValueMap.get(kind);
			if (enumVals && enumVals.length > 0) {
				return `ir.${irKey}('${escapeString(enumVals[0]!)}') as any`;
			}
			const knownExpr = leafTestExpr(kind);
			if (knownExpr) {
				return `ir.${irKey}(${knownExpr}) as any`;
			}
			return `ir.${irKey}('test') as any`;
		}
	}

	if (proj.anonTokens.length > 0) {
		return `'${escapeString(proj.anonTokens[0]!)}' as any`;
	}

	// Fallback: use factory call if available — avoids raw objects that may lack required fields
	const kind = concrete[0];
	if (kind) {
		if (!dc.visiting.has(kind)) {
			const irKey = dc.irKeyMap.get(kind);
			const target = dc.nodeByKind.get(kind);
			if (irKey && target) {
				dc.visiting.add(kind);
				const args = minimalArgs(target, dc);
				dc.visiting.delete(kind);
				return `ir.${irKey}(${args}) as any`;
			}
		}
		return `{ type: '${kind}', fields: {} } as any`;
	}
	return `{ type: 'unknown', fields: {} } as any`;
}

/** Expand supertype names to concrete subtypes for test value generation. */
function expandForTests(kinds: string[], ctx: ProjectionContext): string[] {
	const result = new Set<string>();
	for (const k of kinds) {
		const subs = ctx.expandedSupertypes.get(k);
		if (subs) {
			for (const s of subs) result.add(s);
		} else {
			result.add(k);
		}
	}
	return [...result].sort();
}

function wrapMultiple(multiple: boolean | undefined, value: string): string {
	return multiple ? `[${value}]` : value;
}

function capitalize(s: string): string {
	return s.charAt(0).toUpperCase() + s.slice(1);
}

/**
 * Returns the JS source expression (including quotes) for a valid test value for a leaf kind.
 * Returns undefined to use the default `'test_value'` string literal.
 */
const LEAF_TEST_EXPRS: Record<string, string> = {
	// Rust
	escape_sequence: "'\\\\n'",
	integer_literal: "'42'",
	float_literal: "'3.14'",
	char_literal: "\"'a'\"",
	metavariable: "'$test'",
	shebang: "'#!/bin/sh\\n'",
	string_content: "'hello'",
	doc_comment: "'/// doc'",
	raw_string_literal: "'r\"test\"'",
	// Python
	float: "'3.14e0'",
	integer: "'42'",
	comment: "'# test'",
	import_prefix: "'.'",
	type_conversion: "'!r'",
	format_specifier: "'>10'",
	line_continuation: "'\\\\\\n'",
	// TypeScript
	number: "'42'",
	hash_bang_line: "'#!/usr/bin/env node'",
	meta_property: "'new.target'",
	regex_flags: "'gi'",
	regex_pattern: "'test'",
	private_property_identifier: "'#foo'",
};

function leafTestExpr(kind: string): string | undefined {
	return LEAF_TEST_EXPRS[kind];
}

function escapeString(s: string): string {
	return s.replace(/\\/g, '\\\\').replace(/'/g, "\\'");
}

function resolveIrKey(kind: string, usedKeys: Map<string, string>): string {
	const short = toIrKey(kind);
	if (!usedKeys.has(short)) {
		usedKeys.set(short, kind);
		return short;
	}
	const full = toFactoryName(kind);
	usedKeys.set(full, kind);
	return full;
}
