/**
 * Type-level test emitter — consumes NodeMap directly.
 * Generates compile-time assertions verifying generated types are well-formed.
 */

import type { NodeMap } from '../compiler/types.ts'
import { referencedKinds, resolveHiddenKeywordLiteral } from './shared.ts'

export interface EmitTypeTestsConfig {
    nodeMap: NodeMap
}

export function emitTypeTests(config: EmitTypeTestsConfig): string {
    const { nodeMap } = config

    const structuralKinds: { kind: string; typeName: string; hasVariants: boolean }[] = []
    const leafKinds: { kind: string; typeName: string }[] = []

    // Mirror the T073 liveness check from types: a terminal is only emitted
    // when it has a factory OR is referenced by another structural node.
    // Shared derivation — `shared.ts::referencedKinds` — so types.ts and
    // type-test.ts stay in lockstep.
    const referenced = referencedKinds(nodeMap)

    for (const [kind, node] of nodeMap.nodes) {
        switch (node.modelType) {
            case 'branch':
            case 'container':
                structuralKinds.push({ kind, typeName: node.typeName, hasVariants: false })
                break
            case 'polymorph':
                structuralKinds.push({ kind, typeName: node.typeName, hasVariants: node.forms.length > 1 })
                break
            case 'leaf':
            case 'keyword':
            case 'enum':
                // Only test leaves that actually made it into types.ts.
                if (!node.rawFactoryName && !referenced.has(kind)) continue
                // Hidden `_kw_*` keywords are dropped from types.ts (the
                // factory inlines their literal), so skip them here too —
                // emitting `_Type_KwAsync` tests an identifier that
                // types.ts never exports. Lockstep with
                // `emitLeafTerminalAliases` in types.ts.
                if (resolveHiddenKeywordLiteral(kind, nodeMap) !== undefined) continue
                leafKinds.push({ kind, typeName: node.typeName })
                break
        }
    }

    const lines: string[] = [
        '// Auto-generated by @sittir/codegen — do not edit',
        '// Type-level test: verifies generated types are well-formed',
        '',
    ]

    // Build the assertion body first, tracking which type names we
    // actually reference. Then emit imports for exactly those names —
    // nothing more. Avoids hundreds of `no-unused-vars` warnings from
    // the prior "kitchen-sink" import list.
    const typeImports = new Set<string>()
    const body: string[] = []

    // Dedup by typeName — two distinct kinds (e.g. python's `'True'` string
    // literal vs a supertype/keyword with the same PascalCase name) can
    // normalise to the same typeName, producing duplicate `_Type_X` /
    // `_Config_X` / `_Tree_X` identifiers. The assertions are equivalent,
    // so keep the first occurrence and skip the rest.
    const seenType = new Set<string>()
    const seenTree = new Set<string>()

    body.push('// --- Concrete interface `type` literal ---')
    // Hidden-source structural kinds (`_foo`) surface at parse time via
    // `alias(_foo, 'foo')`, so types.ts emits `$type: 'foo'` (no leading
    // underscore) for the structural interface. Leaf terminal aliases keep
    // their underscore. Strip on the structural-interface side only — using
    // the raw `s.kind` produced a constant `false` assertion for every
    // hidden structural kind.
    const stripHidden = (k: string): string => k.replace(/^_+/, '')
    for (const s of structuralKinds) {
        if (seenType.has(s.typeName)) continue
        seenType.add(s.typeName)
        typeImports.add(s.typeName)
        body.push(`export type _Type_${s.typeName} = _TypeAssert<_TypeExtends<${s.typeName}['$type'], '${stripHidden(s.kind)}'>>;`)
    }
    for (const l of leafKinds) {
        if (seenType.has(l.typeName)) continue
        seenType.add(l.typeName)
        typeImports.add(l.typeName)
        body.push(`export type _Type_${l.typeName} = _TypeAssert<_TypeExtends<${l.typeName}['$type'], '${l.kind}'>>;`)
    }
    body.push('')

    // Config assertion dropped — base-kind `${TypeName}Config` aliases are
    // no longer emitted (spec 008 US7 landing). `X.Config` (namespace sugar)
    // and `ConfigOf<X>` resolve to the same type by construction; the old
    // test was a tautology.

    body.push('// --- TreeNode types have correct `type` ---')
    for (const s of structuralKinds) {
        if (seenTree.has(s.typeName)) continue
        seenTree.add(s.typeName)
        typeImports.add(`${s.typeName}Tree`)
        body.push(`export type _Tree_${s.typeName} = _TypeAssert<_TypeExtends<${s.typeName}Tree['type'], '${s.kind}'>>;`)
    }
    for (const l of leafKinds) {
        if (seenTree.has(l.typeName)) continue
        seenTree.add(l.typeName)
        typeImports.add(`${l.typeName}Tree`)
        body.push(`export type _Tree_${l.typeName} = _TypeAssert<_TypeExtends<${l.typeName}Tree['type'], '${l.kind}'>>;`)
    }
    body.push('')

    // Imports — now emitted from the narrowed set.
    lines.push(`import type { ${[...typeImports].sort().join(', ')} } from './types.js';`)
    lines.push('')
    lines.push('type _TypeExtends<A, B> = A extends B ? true : false;')
    lines.push('type _TypeAssert<T extends true> = T;')
    lines.push('')
    lines.push(...body)

    return lines.join('\n')
}
