/**
 * Type-level test emitter — consumes NodeMap directly.
 * Generates compile-time assertions verifying generated types are well-formed.
 */

import type { NodeMap } from '../compiler/rule.ts'

export interface EmitTypeTestsFromNodeMapConfig {
    nodeMap: NodeMap
}

export function emitTypeTestsFromNodeMap(config: EmitTypeTestsFromNodeMapConfig): string {
    const { nodeMap } = config

    const structuralKinds: { kind: string; typeName: string; hasVariants: boolean }[] = []
    const leafKinds: { kind: string; typeName: string }[] = []

    // Mirror the T073 liveness check from types-v2: a terminal is
    // only emitted when it has a factory OR is referenced by another
    // structural node. Anything type-test would reference but
    // types-v2 skipped becomes a dangling import, so filter here too.
    const referenced = new Set<string>()
    for (const [, n] of nodeMap.nodes) {
        if (n.modelType === 'branch' || n.modelType === 'group') {
            for (const f of n.fields) for (const t of f.contentTypes) referenced.add(t)
            for (const c of (n.children ?? [])) for (const t of c.contentTypes) referenced.add(t)
        } else if (n.modelType === 'container') {
            for (const c of n.children) for (const t of c.contentTypes) referenced.add(t)
        } else if (n.modelType === 'polymorph') {
            for (const form of n.forms) {
                for (const f of form.fields) for (const t of f.contentTypes) referenced.add(t)
                for (const c of form.children) for (const t of c.contentTypes) referenced.add(t)
            }
        } else if (n.modelType === 'supertype') {
            for (const t of n.subtypes) referenced.add(t)
        }
    }

    for (const [kind, node] of nodeMap.nodes) {
        switch (node.modelType) {
            case 'branch':
            case 'container':
                structuralKinds.push({ kind, typeName: node.typeName, hasVariants: false })
                break
            case 'polymorph':
                structuralKinds.push({ kind, typeName: node.typeName, hasVariants: node.forms.length > 1 })
                break
            case 'leaf':
            case 'keyword':
            case 'enum':
                // Only test leaves that actually made it into types.ts.
                if (!node.rawFactoryName && !referenced.has(kind)) continue
                leafKinds.push({ kind, typeName: node.typeName })
                break
        }
    }

    const lines: string[] = [
        '// Auto-generated by @sittir/codegen — do not edit',
        '// Type-level test: verifies generated types are well-formed',
        '',
    ]

    // Imports
    const typeImports = new Set<string>()
    for (const s of structuralKinds) {
        typeImports.add(s.typeName)
        typeImports.add(`${s.typeName}Config`)
        typeImports.add(`${s.typeName}Tree`)
        typeImports.add(`Loose${s.typeName}`)
    }
    for (const l of leafKinds) {
        typeImports.add(l.typeName)
        typeImports.add(`${l.typeName}Tree`)
    }
    lines.push(`import type { ${[...typeImports].sort().join(', ')} } from './types.js';`)
    lines.push("import type { ConfigOf } from '@sittir/types';")
    lines.push('')

    // Helpers
    lines.push('type _TypeExtends<A, B> = A extends B ? true : false;')
    lines.push('type _TypeAssert<T extends true> = T;')
    lines.push('')

    // Dedup by typeName — two distinct kinds (e.g. python's `'True'` string
    // literal vs a supertype/keyword with the same PascalCase name) can
    // normalise to the same typeName, producing duplicate `_Type_X` /
    // `_Config_X` / `_Tree_X` identifiers. The assertions are equivalent,
    // so keep the first occurrence and skip the rest.
    const seenType = new Set<string>()
    const seenConfig = new Set<string>()
    const seenTree = new Set<string>()

    // 1. type literal checks
    lines.push('// --- Concrete interface `type` literal ---')
    for (const s of structuralKinds) {
        if (seenType.has(s.typeName)) continue
        seenType.add(s.typeName)
        lines.push(`export type _Type_${s.typeName} = _TypeAssert<_TypeExtends<${s.typeName}['type'], '${s.kind}'>>;`)
    }
    for (const l of leafKinds) {
        if (seenType.has(l.typeName)) continue
        seenType.add(l.typeName)
        lines.push(`export type _Type_${l.typeName} = _TypeAssert<_TypeExtends<${l.typeName}['type'], '${l.kind}'>>;`)
    }
    lines.push('')

    // 2. ConfigOf checks (skip polymorphs with variants)
    lines.push('// --- ConfigOf<T> assignable to *Config ---')
    for (const s of structuralKinds) {
        if (s.hasVariants) continue
        if (seenConfig.has(s.typeName)) continue
        seenConfig.add(s.typeName)
        lines.push(`export type _Config_${s.typeName} = _TypeAssert<_TypeExtends<ConfigOf<${s.typeName}>, ${s.typeName}Config>>;`)
    }
    lines.push('')

    // 3. TreeNode type literal checks
    lines.push('// --- TreeNode types have correct `type` ---')
    for (const s of structuralKinds) {
        if (seenTree.has(s.typeName)) continue
        seenTree.add(s.typeName)
        lines.push(`export type _Tree_${s.typeName} = _TypeAssert<_TypeExtends<${s.typeName}Tree['type'], '${s.kind}'>>;`)
    }
    for (const l of leafKinds) {
        if (seenTree.has(l.typeName)) continue
        seenTree.add(l.typeName)
        lines.push(`export type _Tree_${l.typeName} = _TypeAssert<_TypeExtends<${l.typeName}Tree['type'], '${l.kind}'>>;`)
    }
    lines.push('')

    return lines.join('\n')
}
