// @generated from packages/typescript/node-model.json5 and packages/typescript/templates/*.jinja — do not hand-edit.
// Regenerate via: npx tsx packages/codegen/src/cli.ts --grammar typescript --all --output packages/typescript/src
//
// render_dispatch match table — routes KindId to per-kind render functions
// in the sibling templates module.

#![allow(dead_code, unused_imports, non_snake_case, non_camel_case_types, unused_mut, unused_variables)]

use ::sittir_core::filters::{
    SingleNonterminalView, ListNonterminalView,
    OptionalNonterminalView,
};
use ::sittir_core::types::{
    NodeData, FieldValue, RenderableTransport, Source, Span, NodeTrivia, TransportTrivia,
};

#[cfg(feature = "napi-bindings")]
use ::napi_derive::napi;

use super::bridge::*;
use super::templates::*;

pub fn render_dispatch(node: &NodeData) -> Result<String, ::askama::Error> {
    if node.fields.is_none() && node.children.is_none() {
        if let Some(text) = &node.text {
            return Ok(text.to_owned());
        }
    }
    match node.type_.0 {
        357 => render_hidden_arrow_function_call_signature(node), // "_arrow_function__call_signature" | "arrow_function__call_signature"
        356 => render_hidden_arrow_function_parameter(node), // "_arrow_function_parameter" | "arrow_function_parameter"
        387 => render_hidden_call_expression_call(node), // "_call_expression_call" | "call_expression_call"
        389 => render_hidden_call_expression_member(node), // "_call_expression_member" | "call_expression_member"
        388 => render_hidden_call_expression_template_call(node), // "_call_expression_template_call" | "call_expression_template_call"
        373 => render_hidden_class_body_member(node), // "_class_body_member" | "class_body_member"
        372 => render_hidden_class_body_method_sig(node), // "_class_body_method_sig" | "class_body_method_sig"
        371 => render_hidden_class_body_method(node), // "_class_body_method" | "class_body_method"
        358 => render_hidden_class_heritage_extends_clause(node), // "_class_heritage_extends_clause" | "class_heritage_extends_clause"
        359 => render_hidden_class_heritage_implements_clause(node), // "_class_heritage_implements_clause" | "class_heritage_implements_clause"
        370 => render_hidden_export_statement_default_decl_arm_default_kw_value(node), // "_export_statement_default_decl_arm_default_kw_value" | "export_statement_default_decl_arm_default_kw_value"
        355 => render_hidden_export_statement_default_decl_arm_default_kw(node), // "_export_statement_default_decl_arm_default_kw" | "export_statement_default_decl_arm_default_kw"
        354 => render_hidden_export_statement_default_decl_arm(node), // "_export_statement_default_decl_arm" | "export_statement_default_decl_arm"
        369 => render_hidden_export_statement_default_from_arm_clause_from(node), // "_export_statement_default_from_arm_clause_from" | "export_statement_default_from_arm_clause_from"
        368 => render_hidden_export_statement_default_from_arm_ns_from(node), // "_export_statement_default_from_arm_ns_from" | "export_statement_default_from_arm_ns_from"
        367 => render_hidden_export_statement_default_from_arm_star_from(node), // "_export_statement_default_from_arm_star_from" | "export_statement_default_from_arm_star_from"
        353 => render_hidden_export_statement_default_from_arm(node), // "_export_statement_default_from_arm" | "export_statement_default_from_arm"
        385 => render_hidden_export_statement_equals_export(node), // "_export_statement_equals_export" | "export_statement_equals_export"
        386 => render_hidden_export_statement_namespace_export(node), // "_export_statement_namespace_export" | "export_statement_namespace_export"
        384 => render_hidden_export_statement_type_export(node), // "_export_statement_type_export" | "export_statement_type_export"
        376 => render_hidden_for_header_let_const_kind(node), // "_for_header_let_const_kind" | "for_header_let_const_kind"
        374 => render_hidden_for_header_lhs(node), // "_for_header_lhs" | "for_header_lhs"
        375 => render_hidden_for_header_var_kind(node), // "_for_header_var_kind" | "for_header_var_kind"
        362 => render_hidden_import_clause_default_import(node), // "_import_clause_default_import" | "import_clause_default_import"
        361 => render_hidden_import_clause_named_imports(node), // "_import_clause_named_imports" | "import_clause_named_imports"
        360 => render_hidden_import_clause_namespace_import(node), // "_import_clause_namespace_import" | "import_clause_namespace_import"
        364 => render_hidden_import_specifier_as(node), // "_import_specifier_as" | "import_specifier_as"
        363 => render_hidden_import_specifier_name(node), // "_import_specifier_name" | "import_specifier_name"
        365 => render_hidden_index_signature_colon(node), // "_index_signature_colon" | "index_signature_colon"
        366 => render_hidden_index_signature_mapped_type_clause(node), // "_index_signature_mapped_type_clause" | "index_signature_mapped_type_clause"
        239 => render_hidden_initializer(node), // "_initializer"
        331 | 103 => render_hidden_number(node), // "_number" | "number"
        383 => render_hidden_parenthesized_expression_sequence(node), // "_parenthesized_expression_sequence" | "parenthesized_expression_sequence"
        382 => render_hidden_parenthesized_expression_typed(node), // "_parenthesized_expression_typed" | "parenthesized_expression_typed"
        420 => render_hidden_public_field_definition_abstract_first(node), // "_public_field_definition_abstract_first" | "public_field_definition_abstract_first"
        421 => render_hidden_public_field_definition_access_first(node), // "_public_field_definition_access_first" | "public_field_definition_access_first"
        422 => render_hidden_public_field_definition_accessor_opt(node), // "_public_field_definition_accessor_opt" | "public_field_definition_accessor_opt"
        423 => render_hidden_public_field_definition_declare_first(node), // "_public_field_definition_declare_first" | "public_field_definition_declare_first"
        424 => render_hidden_public_field_definition_readonly_first(node), // "_public_field_definition_readonly_first" | "public_field_definition_readonly_first"
        425 => render_hidden_public_field_definition_static_mods(node), // "_public_field_definition_static_mods" | "public_field_definition_static_mods"
        390 => render_hidden_string_double(node), // "_string_double" | "string_double"
        391 => render_hidden_string_single(node), // "_string_single" | "string_single"
        430 => render_hidden_type_identifier(node), // "_type_identifier" | "type_identifier"
        304 => render_hidden_type_query_call_expression_in_type_annotation(node), // "_type_query_call_expression_in_type_annotation"
        324 => render_hidden_type_query_call_expression(node), // "_type_query_call_expression"
        325 => render_hidden_type_query_instantiation_expression(node), // "_type_query_instantiation_expression"
        303 => render_hidden_type_query_member_expression_in_type_annotation(node), // "_type_query_member_expression_in_type_annotation"
        322 => render_hidden_type_query_member_expression(node), // "_type_query_member_expression"
        323 => render_hidden_type_query_subscript_expression(node), // "_type_query_subscript_expression"
        392 => render_hidden_update_expression_postfix(node), // "_update_expression_postfix" | "update_expression_postfix"
        393 => render_hidden_update_expression_prefix(node), // "_update_expression_prefix" | "update_expression_prefix"
        282 => render_abstract_class_declaration(node), // "abstract_class_declaration"
        270 => render_abstract_method_signature(node), // "abstract_method_signature"
        300 => render_adding_type_annotation(node), // "adding_type_annotation"
        281 => render_ambient_declaration(node), // "ambient_declaration"
        252 => render_arguments(node), // "arguments"
        218 => render_array_pattern(node), // "array_pattern"
        346 => render_array_type(node), // "array_type"
        217 => render_array(node), // "array"
        227 => render_arrow_function(node), // "arrow_function"
        274 => render_as_expression(node), // "as_expression"
        306 => render_asserts_annotation(node), // "asserts_annotation"
        305 => render_asserts(node), // "asserts"
        236 => render_assignment_expression(node), // "assignment_expression"
        215 => render_assignment_pattern(node), // "assignment_pattern"
        238 => render_augmented_assignment_expression(node), // "augmented_assignment_expression"
        233 => render_await_expression(node), // "await_expression"
        243 => render_binary_expression(node), // "binary_expression"
        197 => render_break_statement(node), // "break_statement"
        231 => render_call_expression(node), // "call_expression"
        338 => render_call_signature(node), // "call_signature"
        207 => render_catch_clause(node), // "catch_clause"
        256 => render_class_body(node), // "class_body"
        221 => render_class_declaration(node), // "class_declaration"
        222 => render_class_heritage(node), // "class_heritage"
        258 => render_class_static_block(node), // "class_static_block"
        220 => render_class(node), // "class"
        265 => render_computed_property_name(node), // "computed_property_name"
        318 => render_conditional_type(node), // "conditional_type"
        343 => render_constraint(node), // "constraint"
        344 => render_construct_signature(node), // "construct_signature"
        313 => render_constructor_type(node), // "constructor_type"
        198 => render_continue_statement(node), // "continue_statement"
        199 => render_debugger_statement(node), // "debugger_statement"
        255 => render_decorator_call_expression(node), // "decorator_call_expression"
        254 => render_decorator_member_expression(node), // "decorator_member_expression"
        272 => render_decorator_parenthesized_expression(node), // "decorator_parenthesized_expression"
        253 => render_decorator(node), // "decorator"
        342 => render_default_type(node), // "default_type"
        194 => render_do_statement(node), // "do_statement"
        187 => render_else_clause(node), // "else_clause"
        292 => render_enum_assignment(node), // "enum_assignment"
        291 => render_enum_body(node), // "enum_body"
        290 => render_enum_declaration(node), // "enum_declaration"
        169 => render_export_clause(node), // "export_clause"
        170 => render_export_specifier(node), // "export_specifier"
        167 => render_export_statement(node), // "export_statement"
        182 => render_expression_statement(node), // "expression_statement"
        278 => render_extends_clause(node), // "extends_clause"
        289 => render_extends_type_clause(node), // "extends_type_clause"
        208 => render_finally_clause(node), // "finally_clause"
        333 => render_flow_maybe_type(node), // "flow_maybe_type"
        191 => render_for_in_statement(node), // "for_in_statement"
        190 => render_for_statement(node), // "for_statement"
        257 => render_formal_parameters(node), // "formal_parameters"
        224 => render_function_declaration(node), // "function_declaration"
        223 => render_function_expression(node), // "function_expression"
        271 => render_function_signature(node), // "function_signature"
        351 => render_function_type(node), // "function_type"
        226 => render_generator_function_declaration(node), // "generator_function_declaration"
        225 => render_generator_function(node), // "generator_function"
        319 => render_generic_type(node), // "generic_type"
        188 => render_if_statement(node), // "if_statement"
        280 => render_implements_clause(node), // "implements_clause"
        286 => render_import_alias(node), // "import_alias"
        180 => render_import_attribute(node), // "import_attribute"
        175 => render_import_clause(node), // "import_clause"
        277 => render_import_require_clause(node), // "import_require_clause"
        179 => render_import_specifier(node), // "import_specifier"
        174 => render_import_statement(node), // "import_statement"
        345 => render_index_signature(node), // "index_signature"
        327 => render_index_type_query(node), // "index_type_query"
        317 => render_infer_type(node), // "infer_type"
        276 => render_instantiation_expression(node), // "instantiation_expression"
        288 => render_interface_declaration(node), // "interface_declaration"
        284 => render_internal_module(node), // "internal_module"
        350 => render_intersection_type(node), // "intersection_type"
        203 => render_labeled_statement(node), // "labeled_statement"
        184 => render_lexical_declaration(node), // "lexical_declaration"
        330 => render_literal_type(node), // "literal_type"
        328 => render_lookup_type(node), // "lookup_type"
        329 => render_mapped_type_clause(node), // "mapped_type_clause"
        234 => render_member_expression(node), // "member_expression"
        261 => render_method_definition(node), // "method_definition"
        269 => render_method_signature(node), // "method_signature"
        283 => render_module(node), // "module"
        178 => render_named_imports(node), // "named_imports"
        168 => render_namespace_export(node), // "namespace_export"
        177 => render_namespace_import(node), // "namespace_import"
        219 => render_nested_identifier(node), // "nested_identifier"
        287 => render_nested_type_identifier(node), // "nested_type_identifier"
        232 => render_new_expression(node), // "new_expression"
        268 => render_non_null_expression(node), // "non_null_expression"
        216 => render_object_assignment_pattern(node), // "object_assignment_pattern"
        214 => render_object_pattern(node), // "object_pattern"
        337 => render_object_type(node), // "object_type"
        213 => render_object(node), // "object"
        299 => render_omitting_type_annotation(node), // "omitting_type_annotation"
        301 => render_opting_type_annotation(node), // "opting_type_annotation"
        297 => render_optional_parameter(node), // "optional_parameter"
        309 => render_optional_tuple_parameter(node), // "optional_tuple_parameter"
        310 => render_optional_type(node), // "optional_type"
        263 => render_pair_pattern(node), // "pair_pattern"
        262 => render_pair(node), // "pair"
        209 => render_parenthesized_expression(node), // "parenthesized_expression"
        334 => render_parenthesized_type(node), // "parenthesized_type"
        166 => render_program(node), // "program"
        339 => render_property_signature(node), // "property_signature"
        266 => render_public_field_definition(node), // "public_field_definition"
        348 => render_readonly_type(node), // "readonly_type"
        250 => render_regex(node), // "regex"
        296 => render_required_parameter(node), // "required_parameter"
        260 => render_rest_pattern(node), // "rest_pattern"
        311 => render_rest_type(node), // "rest_type"
        200 => render_return_statement(node), // "return_statement"
        275 => render_satisfies_expression(node), // "satisfies_expression"
        246 => render_sequence_expression(node), // "sequence_expression"
        241 => render_spread_element(node), // "spread_element"
        186 => render_statement_block(node), // "statement_block"
        247 => render_string(node), // "string"
        235 => render_subscript_expression(node), // "subscript_expression"
        204 => render_switch_body(node), // "switch_body"
        205 => render_switch_case(node), // "switch_case"
        206 => render_switch_default(node), // "switch_default"
        189 => render_switch_statement(node), // "switch_statement"
        316 => render_template_literal_type(node), // "template_literal_type"
        248 => render_template_string(node), // "template_string"
        249 => render_template_substitution(node), // "template_substitution"
        315 => render_template_type(node), // "template_type"
        242 => render_ternary_expression(node), // "ternary_expression"
        201 => render_throw_statement(node), // "throw_statement"
        195 => render_try_statement(node), // "try_statement"
        308 => render_tuple_parameter(node), // "tuple_parameter"
        347 => render_tuple_type(node), // "tuple_type"
        293 => render_type_alias_declaration(node), // "type_alias_declaration"
        302 => render_type_annotation(node), // "type_annotation"
        336 => render_type_arguments(node), // "type_arguments"
        273 => render_type_assertion(node), // "type_assertion"
        341 => render_type_parameter(node), // "type_parameter"
        340 => render_type_parameters(node), // "type_parameters"
        321 => render_type_predicate_annotation(node), // "type_predicate_annotation"
        320 => render_type_predicate(node), // "type_predicate"
        326 => render_type_query(node), // "type_query"
        244 => render_unary_expression(node), // "unary_expression"
        349 => render_union_type(node), // "union_type"
        245 => render_update_expression(node), // "update_expression"
        183 => render_variable_declaration(node), // "variable_declaration"
        185 => render_variable_declarator(node), // "variable_declarator"
        193 => render_while_statement(node), // "while_statement"
        196 => render_with_statement(node), // "with_statement"
        212 => render_yield_expression(node), // "yield_expression"
        _ => token_shaped_fallback(node),
    }
}
