// @generated from packages/typescript/.sittir/src/parser.c — do not hand-edit.
// Per-kind numeric ID constants matching the TS-side `TSKindId` enum.
//
// IDs come from `enum ts_symbol_identifiers` in parser.c (KindID
// runtime migration design, 2026-04-30). Use these constants when
// matching on `KindId` values; the inner u16 is the parser.c-derived
// symbol id.

use ::sittir_core::types::KindId;

pub const IDENTIFIER: KindId = KindId(1);
pub const HASH_BANG_LINE: KindId = KindId(2);
pub const STAR: KindId = KindId(3);
pub const AS: KindId = KindId(4);
pub const LBRACE: KindId = KindId(5);
pub const RBRACE: KindId = KindId(6);
pub const ANON_TYPE: KindId = KindId(7);
pub const TYPEOF: KindId = KindId(8);
pub const ANON_IMPORT: KindId = KindId(9);
pub const FROM: KindId = KindId(10);
pub const WITH: KindId = KindId(11);
pub const ASSERT: KindId = KindId(12);
pub const VAR: KindId = KindId(13);
pub const COMMA: KindId = KindId(14);
pub const ELSE: KindId = KindId(15);
pub const IF: KindId = KindId(16);
pub const SWITCH: KindId = KindId(17);
pub const FOR: KindId = KindId(18);
pub const LPAREN: KindId = KindId(19);
pub const SEMI: KindId = KindId(20);
pub const RPAREN: KindId = KindId(21);
pub const WHILE: KindId = KindId(22);
pub const DO: KindId = KindId(23);
pub const TRY: KindId = KindId(24);
pub const BREAK: KindId = KindId(25);
pub const CONTINUE: KindId = KindId(26);
pub const DEBUGGER: KindId = KindId(27);
pub const RETURN: KindId = KindId(28);
pub const THROW: KindId = KindId(29);
pub const COLON: KindId = KindId(30);
pub const CASE: KindId = KindId(31);
pub const DEFAULT: KindId = KindId(32);
pub const CATCH: KindId = KindId(33);
pub const FINALLY: KindId = KindId(34);
pub const YIELD: KindId = KindId(35);
pub const EQ: KindId = KindId(36);
pub const LBRACK: KindId = KindId(37);
pub const RBRACK: KindId = KindId(38);
pub const DOT: KindId = KindId(39);
pub const ANON_CLASS: KindId = KindId(40);
pub const FUNCTION: KindId = KindId(41);
pub const EQ_GT: KindId = KindId(42);
pub const QMARK_DOT: KindId = KindId(43);
pub const NEW: KindId = KindId(44);
pub const AWAIT: KindId = KindId(45);
pub const PLUS_EQ: KindId = KindId(46);
pub const DASH_EQ: KindId = KindId(47);
pub const STAR_EQ: KindId = KindId(48);
pub const SLASH_EQ: KindId = KindId(49);
pub const PERCENT_EQ: KindId = KindId(50);
pub const CARET_EQ: KindId = KindId(51);
pub const AMP_EQ: KindId = KindId(52);
pub const PIPE_EQ: KindId = KindId(53);
pub const GT_GT_EQ: KindId = KindId(54);
pub const GT_GT_GT_EQ: KindId = KindId(55);
pub const LT_LT_EQ: KindId = KindId(56);
pub const STAR_STAR_EQ: KindId = KindId(57);
pub const AMP_AMP_EQ: KindId = KindId(58);
pub const PIPE_PIPE_EQ: KindId = KindId(59);
pub const QMARK_QMARK_EQ: KindId = KindId(60);
pub const DOT_DOT_DOT: KindId = KindId(61);
pub const AMP_AMP: KindId = KindId(62);
pub const PIPE_PIPE: KindId = KindId(63);
pub const GT_GT: KindId = KindId(64);
pub const GT_GT_GT: KindId = KindId(65);
pub const LT_LT: KindId = KindId(66);
pub const AMP: KindId = KindId(67);
pub const CARET: KindId = KindId(68);
pub const PIPE: KindId = KindId(69);
pub const PLUS: KindId = KindId(70);
pub const DASH: KindId = KindId(71);
pub const SLASH: KindId = KindId(72);
pub const PERCENT: KindId = KindId(73);
pub const STAR_STAR: KindId = KindId(74);
pub const LT: KindId = KindId(75);
pub const LT_EQ: KindId = KindId(76);
pub const EQ_EQ: KindId = KindId(77);
pub const EQ_EQ_EQ: KindId = KindId(78);
pub const BANG_EQ: KindId = KindId(79);
pub const BANG_EQ_EQ: KindId = KindId(80);
pub const GT_EQ: KindId = KindId(81);
pub const GT: KindId = KindId(82);
pub const QMARK_QMARK: KindId = KindId(83);
pub const INSTANCEOF: KindId = KindId(84);
pub const BANG: KindId = KindId(85);
pub const TILDE: KindId = KindId(86);
pub const VOID: KindId = KindId(87);
pub const DELETE: KindId = KindId(88);
pub const UNESCAPED_DOUBLE_STRING_FRAGMENT: KindId = KindId(89);
pub const UNESCAPED_SINGLE_STRING_FRAGMENT: KindId = KindId(90);
pub const ESCAPE_SEQUENCE: KindId = KindId(91);
pub const COMMENT: KindId = KindId(92);
pub const BQUOTE: KindId = KindId(93);
pub const DOLLAR_LBRACE: KindId = KindId(94);
pub const SLASH2: KindId = KindId(95);
pub const REGEX_PATTERN: KindId = KindId(96);
pub const REGEX_FLAGS: KindId = KindId(97);
pub const NUMBER: KindId = KindId(98);
pub const PRIVATE_PROPERTY_IDENTIFIER: KindId = KindId(99);
pub const THIS: KindId = KindId(100);
pub const SUPER: KindId = KindId(101);
pub const TRUE: KindId = KindId(102);
pub const FALSE: KindId = KindId(103);
pub const NULL: KindId = KindId(104);
pub const UNDEFINED: KindId = KindId(105);
pub const AT: KindId = KindId(106);
pub const STATIC: KindId = KindId(107);
pub const GET: KindId = KindId(108);
pub const SET: KindId = KindId(109);
pub const DECLARE: KindId = KindId(110);
pub const NAMESPACE: KindId = KindId(111);
pub const PUBLIC: KindId = KindId(112);
pub const PRIVATE: KindId = KindId(113);
pub const PROTECTED: KindId = KindId(114);
pub const OVERRIDE: KindId = KindId(115);
pub const READONLY: KindId = KindId(116);
pub const ANON_MODULE: KindId = KindId(117);
pub const ANY: KindId = KindId(118);
pub const ANON_NUMBER: KindId = KindId(119);
pub const BOOLEAN: KindId = KindId(120);
pub const ANON_STRING: KindId = KindId(121);
pub const SYMBOL: KindId = KindId(122);
pub const EXPORT: KindId = KindId(123);
pub const ANON_OBJECT: KindId = KindId(124);
pub const ASYNC: KindId = KindId(125);
pub const LET: KindId = KindId(126);
pub const QMARK: KindId = KindId(127);
pub const ABSTRACT: KindId = KindId(128);
pub const CONST: KindId = KindId(129);
pub const SATISFIES: KindId = KindId(130);
pub const REQUIRE: KindId = KindId(131);
pub const EXTENDS: KindId = KindId(132);
pub const IMPLEMENTS: KindId = KindId(133);
pub const INTERFACE: KindId = KindId(134);
pub const ENUM: KindId = KindId(135);
pub const DASH_QMARK_COLON: KindId = KindId(136);
pub const PLUS_QMARK_COLON: KindId = KindId(137);
pub const QMARK_COLON: KindId = KindId(138);
pub const ANON_ASSERTS: KindId = KindId(139);
pub const DOLLAR_LBRACE2: KindId = KindId(140);
pub const INFER: KindId = KindId(141);
pub const IS: KindId = KindId(142);
pub const KEYOF: KindId = KindId(143);
pub const IN: KindId = KindId(144);
pub const UNIQUE: KindId = KindId(145);
pub const UNKNOWN: KindId = KindId(146);
pub const NEVER: KindId = KindId(147);
pub const LBRACE_PIPE: KindId = KindId(148);
pub const PIPE_RBRACE: KindId = KindId(149);
pub const USING: KindId = KindId(150);
pub const ACCESSOR: KindId = KindId(151);
pub const OF: KindId = KindId(152);
pub const GLOBAL: KindId = KindId(153);
pub const DQUOTE: KindId = KindId(154);
pub const SQUOTE: KindId = KindId(155);
pub const PLUS_PLUS: KindId = KindId(156);
pub const DASH_DASH: KindId = KindId(157);
pub const TARGET: KindId = KindId(158);
pub const META: KindId = KindId(159);
pub const _AUTOMATIC_SEMICOLON: KindId = KindId(160);
pub const _TEMPLATE_CHARS: KindId = KindId(161);
pub const _TERNARY_QMARK: KindId = KindId(162);
pub const HTML_COMMENT: KindId = KindId(163);
pub const JSX_TEXT: KindId = KindId(164);
pub const _FUNCTION_SIGNATURE_AUTOMATIC_SEMICOLON: KindId = KindId(165);
pub const __ERROR_RECOVERY: KindId = KindId(166);
pub const PROGRAM: KindId = KindId(167);
pub const EXPORT_STATEMENT: KindId = KindId(168);
pub const NAMESPACE_EXPORT: KindId = KindId(169);
pub const EXPORT_CLAUSE: KindId = KindId(170);
pub const EXPORT_SPECIFIER: KindId = KindId(171);
pub const _MODULE_EXPORT_NAME: KindId = KindId(172);
pub const DECLARATION: KindId = KindId(173);
pub const IMPORT: KindId = KindId(174);
pub const IMPORT_STATEMENT: KindId = KindId(175);
pub const IMPORT_CLAUSE: KindId = KindId(176);
pub const _FROM_CLAUSE: KindId = KindId(177);
pub const NAMESPACE_IMPORT: KindId = KindId(178);
pub const NAMED_IMPORTS: KindId = KindId(179);
pub const IMPORT_SPECIFIER: KindId = KindId(180);
pub const IMPORT_ATTRIBUTE: KindId = KindId(181);
pub const STATEMENT: KindId = KindId(182);
pub const EXPRESSION_STATEMENT: KindId = KindId(183);
pub const VARIABLE_DECLARATION: KindId = KindId(184);
pub const LEXICAL_DECLARATION: KindId = KindId(185);
pub const VARIABLE_DECLARATOR: KindId = KindId(186);
pub const STATEMENT_BLOCK: KindId = KindId(187);
pub const ELSE_CLAUSE: KindId = KindId(188);
pub const IF_STATEMENT: KindId = KindId(189);
pub const SWITCH_STATEMENT: KindId = KindId(190);
pub const FOR_STATEMENT: KindId = KindId(191);
pub const FOR_IN_STATEMENT: KindId = KindId(192);
pub const _FOR_HEADER: KindId = KindId(193);
pub const WHILE_STATEMENT: KindId = KindId(194);
pub const DO_STATEMENT: KindId = KindId(195);
pub const TRY_STATEMENT: KindId = KindId(196);
pub const WITH_STATEMENT: KindId = KindId(197);
pub const BREAK_STATEMENT: KindId = KindId(198);
pub const CONTINUE_STATEMENT: KindId = KindId(199);
pub const DEBUGGER_STATEMENT: KindId = KindId(200);
pub const RETURN_STATEMENT: KindId = KindId(201);
pub const THROW_STATEMENT: KindId = KindId(202);
pub const EMPTY_STATEMENT: KindId = KindId(203);
pub const LABELED_STATEMENT: KindId = KindId(204);
pub const SWITCH_BODY: KindId = KindId(205);
pub const SWITCH_CASE: KindId = KindId(206);
pub const SWITCH_DEFAULT: KindId = KindId(207);
pub const CATCH_CLAUSE: KindId = KindId(208);
pub const FINALLY_CLAUSE: KindId = KindId(209);
pub const PARENTHESIZED_EXPRESSION: KindId = KindId(210);
pub const EXPRESSION: KindId = KindId(211);
pub const PRIMARY_EXPRESSION: KindId = KindId(212);
pub const YIELD_EXPRESSION: KindId = KindId(213);
pub const OBJECT: KindId = KindId(214);
pub const OBJECT_PATTERN: KindId = KindId(215);
pub const ASSIGNMENT_PATTERN: KindId = KindId(216);
pub const OBJECT_ASSIGNMENT_PATTERN: KindId = KindId(217);
pub const ARRAY: KindId = KindId(218);
pub const ARRAY_PATTERN: KindId = KindId(219);
pub const NESTED_IDENTIFIER: KindId = KindId(220);
pub const CLASS: KindId = KindId(221);
pub const CLASS_DECLARATION: KindId = KindId(222);
pub const CLASS_HERITAGE: KindId = KindId(223);
pub const FUNCTION_EXPRESSION: KindId = KindId(224);
pub const FUNCTION_DECLARATION: KindId = KindId(225);
pub const GENERATOR_FUNCTION: KindId = KindId(226);
pub const GENERATOR_FUNCTION_DECLARATION: KindId = KindId(227);
pub const ARROW_FUNCTION: KindId = KindId(228);
pub const _CALL_SIGNATURE: KindId = KindId(229);
pub const _FORMAL_PARAMETER: KindId = KindId(230);
pub const OPTIONAL_CHAIN: KindId = KindId(231);
pub const CALL_EXPRESSION: KindId = KindId(232);
pub const NEW_EXPRESSION: KindId = KindId(233);
pub const AWAIT_EXPRESSION: KindId = KindId(234);
pub const MEMBER_EXPRESSION: KindId = KindId(235);
pub const SUBSCRIPT_EXPRESSION: KindId = KindId(236);
pub const _LHS_EXPRESSION: KindId = KindId(237);
pub const ASSIGNMENT_EXPRESSION: KindId = KindId(238);
pub const _AUGMENTED_ASSIGNMENT_LHS: KindId = KindId(239);
pub const AUGMENTED_ASSIGNMENT_EXPRESSION: KindId = KindId(240);
pub const _INITIALIZER: KindId = KindId(241);
pub const _DESTRUCTURING_PATTERN: KindId = KindId(242);
pub const SPREAD_ELEMENT: KindId = KindId(243);
pub const TERNARY_EXPRESSION: KindId = KindId(244);
pub const BINARY_EXPRESSION: KindId = KindId(245);
pub const UNARY_EXPRESSION: KindId = KindId(246);
pub const UPDATE_EXPRESSION: KindId = KindId(247);
pub const SEQUENCE_EXPRESSION: KindId = KindId(248);
pub const STRING: KindId = KindId(249);
pub const TEMPLATE_STRING: KindId = KindId(250);
pub const TEMPLATE_SUBSTITUTION: KindId = KindId(251);
pub const REGEX: KindId = KindId(252);
pub const META_PROPERTY: KindId = KindId(253);
pub const ARGUMENTS: KindId = KindId(254);
pub const DECORATOR: KindId = KindId(255);
pub const DECORATOR_MEMBER_EXPRESSION: KindId = KindId(256);
pub const DECORATOR_CALL_EXPRESSION: KindId = KindId(257);
pub const CLASS_BODY: KindId = KindId(258);
pub const FORMAL_PARAMETERS: KindId = KindId(259);
pub const CLASS_STATIC_BLOCK: KindId = KindId(260);
pub const PATTERN: KindId = KindId(261);
pub const REST_PATTERN: KindId = KindId(262);
pub const METHOD_DEFINITION: KindId = KindId(263);
pub const PAIR: KindId = KindId(264);
pub const PAIR_PATTERN: KindId = KindId(265);
pub const _PROPERTY_NAME: KindId = KindId(266);
pub const COMPUTED_PROPERTY_NAME: KindId = KindId(267);
pub const PUBLIC_FIELD_DEFINITION: KindId = KindId(268);
pub const _IMPORT_IDENTIFIER: KindId = KindId(269);
pub const NON_NULL_EXPRESSION: KindId = KindId(270);
pub const METHOD_SIGNATURE: KindId = KindId(271);
pub const ABSTRACT_METHOD_SIGNATURE: KindId = KindId(272);
pub const FUNCTION_SIGNATURE: KindId = KindId(273);
pub const DECORATOR_PARENTHESIZED_EXPRESSION: KindId = KindId(274);
pub const TYPE_ASSERTION: KindId = KindId(275);
pub const AS_EXPRESSION: KindId = KindId(276);
pub const SATISFIES_EXPRESSION: KindId = KindId(277);
pub const INSTANTIATION_EXPRESSION: KindId = KindId(278);
pub const IMPORT_REQUIRE_CLAUSE: KindId = KindId(279);
pub const EXTENDS_CLAUSE: KindId = KindId(280);
pub const _EXTENDS_CLAUSE_SINGLE: KindId = KindId(281);
pub const IMPLEMENTS_CLAUSE: KindId = KindId(282);
pub const AMBIENT_DECLARATION: KindId = KindId(283);
pub const ABSTRACT_CLASS_DECLARATION: KindId = KindId(284);
pub const MODULE: KindId = KindId(285);
pub const INTERNAL_MODULE: KindId = KindId(286);
pub const _MODULE: KindId = KindId(287);
pub const IMPORT_ALIAS: KindId = KindId(288);
pub const NESTED_TYPE_IDENTIFIER: KindId = KindId(289);
pub const INTERFACE_DECLARATION: KindId = KindId(290);
pub const EXTENDS_TYPE_CLAUSE: KindId = KindId(291);
pub const ENUM_DECLARATION: KindId = KindId(292);
pub const ENUM_BODY: KindId = KindId(293);
pub const ENUM_ASSIGNMENT: KindId = KindId(294);
pub const TYPE_ALIAS_DECLARATION: KindId = KindId(295);
pub const ACCESSIBILITY_MODIFIER: KindId = KindId(296);
pub const OVERRIDE_MODIFIER: KindId = KindId(297);
pub const REQUIRED_PARAMETER: KindId = KindId(298);
pub const OPTIONAL_PARAMETER: KindId = KindId(299);
pub const _PARAMETER_NAME: KindId = KindId(300);
pub const OMITTING_TYPE_ANNOTATION: KindId = KindId(301);
pub const ADDING_TYPE_ANNOTATION: KindId = KindId(302);
pub const OPTING_TYPE_ANNOTATION: KindId = KindId(303);
pub const TYPE_ANNOTATION: KindId = KindId(304);
pub const _TYPE_QUERY_MEMBER_EXPRESSION_IN_TYPE_ANNOTATION: KindId = KindId(305);
pub const _TYPE_QUERY_CALL_EXPRESSION_IN_TYPE_ANNOTATION: KindId = KindId(306);
pub const ASSERTS: KindId = KindId(307);
pub const ASSERTS_ANNOTATION: KindId = KindId(308);
pub const TYPE: KindId = KindId(309);
pub const TUPLE_PARAMETER: KindId = KindId(310);
pub const OPTIONAL_TUPLE_PARAMETER: KindId = KindId(311);
pub const OPTIONAL_TYPE: KindId = KindId(312);
pub const REST_TYPE: KindId = KindId(313);
pub const _TUPLE_TYPE_MEMBER: KindId = KindId(314);
pub const CONSTRUCTOR_TYPE: KindId = KindId(315);
pub const PRIMARY_TYPE: KindId = KindId(316);
pub const TEMPLATE_TYPE: KindId = KindId(317);
pub const TEMPLATE_LITERAL_TYPE: KindId = KindId(318);
pub const INFER_TYPE: KindId = KindId(319);
pub const CONDITIONAL_TYPE: KindId = KindId(320);
pub const GENERIC_TYPE: KindId = KindId(321);
pub const TYPE_PREDICATE: KindId = KindId(322);
pub const TYPE_PREDICATE_ANNOTATION: KindId = KindId(323);
pub const _TYPE_QUERY_MEMBER_EXPRESSION: KindId = KindId(324);
pub const _TYPE_QUERY_SUBSCRIPT_EXPRESSION: KindId = KindId(325);
pub const _TYPE_QUERY_CALL_EXPRESSION: KindId = KindId(326);
pub const _TYPE_QUERY_INSTANTIATION_EXPRESSION: KindId = KindId(327);
pub const TYPE_QUERY: KindId = KindId(328);
pub const INDEX_TYPE_QUERY: KindId = KindId(329);
pub const LOOKUP_TYPE: KindId = KindId(330);
pub const MAPPED_TYPE_CLAUSE: KindId = KindId(331);
pub const LITERAL_TYPE: KindId = KindId(332);
pub const _NUMBER: KindId = KindId(333);
pub const EXISTENTIAL_TYPE: KindId = KindId(334);
pub const FLOW_MAYBE_TYPE: KindId = KindId(335);
pub const PARENTHESIZED_TYPE: KindId = KindId(336);
pub const PREDEFINED_TYPE: KindId = KindId(337);
pub const TYPE_ARGUMENTS: KindId = KindId(338);
pub const OBJECT_TYPE: KindId = KindId(339);
pub const CALL_SIGNATURE: KindId = KindId(340);
pub const PROPERTY_SIGNATURE: KindId = KindId(341);
pub const TYPE_PARAMETERS: KindId = KindId(342);
pub const TYPE_PARAMETER: KindId = KindId(343);
pub const DEFAULT_TYPE: KindId = KindId(344);
pub const CONSTRAINT: KindId = KindId(345);
pub const CONSTRUCT_SIGNATURE: KindId = KindId(346);
pub const INDEX_SIGNATURE: KindId = KindId(347);
pub const ARRAY_TYPE: KindId = KindId(348);
pub const TUPLE_TYPE: KindId = KindId(349);
pub const READONLY_TYPE: KindId = KindId(350);
pub const UNION_TYPE: KindId = KindId(351);
pub const INTERSECTION_TYPE: KindId = KindId(352);
pub const FUNCTION_TYPE: KindId = KindId(353);
pub const _KW_AWAIT_MARKER: KindId = KindId(354);
pub const _KW_ASYNC_MARKER: KindId = KindId(355);
pub const _KW_USING_MARKER: KindId = KindId(356);
pub const _KW_STATIC_MARKER: KindId = KindId(357);
pub const _KW_DECLARE_MARKER: KindId = KindId(358);
pub const _KW_ABSTRACT_MARKER: KindId = KindId(359);
pub const _KW_ACCESSOR_MARKER: KindId = KindId(360);
pub const _KW_CONST_MARKER: KindId = KindId(361);
pub const _EXPORT_SPECIFIERS: KindId = KindId(362);
pub const _IMPORT_SPECIFIERS: KindId = KindId(363);
pub const _FORMAL_PARAMETERS_ELEMENTS: KindId = KindId(364);
pub const _ENUM_BODY_ELEMENTS: KindId = KindId(365);
pub const _TYPES: KindId = KindId(366);
pub const _TYPE_PARAMETERS_ELEMENTS: KindId = KindId(367);
pub const _TUPLE_TYPE_MEMBERS: KindId = KindId(368);
pub const _IMPORT_CLAUSE_GROUP: KindId = KindId(369);
pub const _CATCH_CLAUSE_GROUP: KindId = KindId(370);
pub const _KIND: KindId = KindId(371);
pub const __FOR_HEADER_OPERATOR: KindId = KindId(372);
pub const _AMBIENT_DECLARATION_GLOBAL: KindId = KindId(373);
pub const _AMBIENT_DECLARATION_MODULE: KindId = KindId(374);
pub const OBJECT_TYPE_CONTENT: KindId = KindId(375);
pub const _EXPORT_STATEMENT_DEFAULT: KindId = KindId(376);
pub const _EXPORT_STATEMENT_NAMESPACE_EXPORT: KindId = KindId(377);
pub const _EXPORT_STATEMENT_TYPE_EXPORT: KindId = KindId(378);
pub const _EXPORT_STATEMENT_EQUALS_EXPORT: KindId = KindId(379);
pub const _BINARY_EXPRESSION_IN: KindId = KindId(380);
pub const _CLASS_BODY_METHOD: KindId = KindId(381);
pub const _CLASS_BODY_METHOD_SIG: KindId = KindId(382);
pub const _CLASS_BODY_MEMBER: KindId = KindId(383);
pub const _INDEX_SIGNATURE_COLON: KindId = KindId(384);
pub const _IMPORT_STATEMENT_CLAUSE_FROM: KindId = KindId(385);
pub const _IMPORT_SPECIFIER_AS: KindId = KindId(386);
pub const _PARENTHESIZED_EXPRESSION_TYPED: KindId = KindId(387);
pub const _CALL_EXPRESSION_CALL: KindId = KindId(388);
pub const _CALL_EXPRESSION_TEMPLATE_CALL: KindId = KindId(389);
pub const _CALL_EXPRESSION_MEMBER: KindId = KindId(390);
pub const _STRING_DOUBLE: KindId = KindId(391);
pub const _STRING_SINGLE: KindId = KindId(392);
pub const _UPDATE_EXPRESSION_POSTFIX: KindId = KindId(393);
pub const _UPDATE_EXPRESSION_PREFIX: KindId = KindId(394);
pub const _ARROW_FUNCTION_PARAMETER: KindId = KindId(395);
pub const _CLASS_HERITAGE_EXTENDS_CLAUSE: KindId = KindId(396);
pub const _IMPORT_CLAUSE_DEFAULT_IMPORT: KindId = KindId(397);
pub const _EXPORT_STATEMENT_DEFAULT_FROM: KindId = KindId(398);
pub const _EXPORT_STATEMENT_DEFAULT_DECLARATION: KindId = KindId(399);
pub const _EXPORT_STATEMENT_DEFAULT_STAR_FROM: KindId = KindId(400);
pub const _EXPORT_STATEMENT_DEFAULT_NS_FROM: KindId = KindId(401);
pub const _EXPORT_STATEMENT_DEFAULT_CLAUSE_FROM: KindId = KindId(402);
pub const _EXPORT_STATEMENT_DEFAULT_DEFAULT_KW: KindId = KindId(403);
pub const _EXPORT_STATEMENT_DEFAULT_VALUE: KindId = KindId(404);
pub const _VARIABLE_DECLARATOR_PLAIN: KindId = KindId(405);
pub const _VARIABLE_DECLARATOR_DEFINITE: KindId = KindId(406);
pub const _META_PROPERTY_NEW_TARGET: KindId = KindId(407);
pub const _META_PROPERTY_IMPORT_META: KindId = KindId(408);
pub const _FOR_HEADER_LHS: KindId = KindId(409);
pub const _FOR_HEADER_VAR_KIND: KindId = KindId(410);
pub const _FOR_HEADER_LET_CONST_KIND: KindId = KindId(411);
pub const PROGRAM_REPEAT1: KindId = KindId(412);
pub const VARIABLE_DECLARATION_REPEAT1: KindId = KindId(413);
pub const SWITCH_BODY_REPEAT1: KindId = KindId(414);
pub const OBJECT_REPEAT1: KindId = KindId(415);
pub const OBJECT_PATTERN_REPEAT1: KindId = KindId(416);
pub const ARRAY_REPEAT1: KindId = KindId(417);
pub const ARRAY_PATTERN_REPEAT1: KindId = KindId(418);
pub const CLASS_REPEAT1: KindId = KindId(419);
pub const SEQUENCE_EXPRESSION_REPEAT1: KindId = KindId(420);
pub const TEMPLATE_STRING_REPEAT1: KindId = KindId(421);
pub const CLASS_BODY_REPEAT1: KindId = KindId(422);
pub const EXTENDS_CLAUSE_REPEAT1: KindId = KindId(423);
pub const IMPLEMENTS_CLAUSE_REPEAT1: KindId = KindId(424);
pub const EXTENDS_TYPE_CLAUSE_REPEAT1: KindId = KindId(425);
pub const TEMPLATE_LITERAL_TYPE_REPEAT1: KindId = KindId(426);
pub const _EXPORT_SPECIFIERS_REPEAT1: KindId = KindId(427);
pub const _IMPORT_SPECIFIERS_REPEAT1: KindId = KindId(428);
pub const _FORMAL_PARAMETERS_ELEMENTS_REPEAT1: KindId = KindId(429);
pub const _ENUM_BODY_ELEMENTS_REPEAT1: KindId = KindId(430);
pub const _TYPE_PARAMETERS_ELEMENTS_REPEAT1: KindId = KindId(431);
pub const _TUPLE_TYPE_MEMBERS_REPEAT1: KindId = KindId(432);
pub const OBJECT_TYPE_CONTENT_REPEAT1: KindId = KindId(433);
pub const _STRING_DOUBLE_REPEAT1: KindId = KindId(434);
pub const _STRING_SINGLE_REPEAT1: KindId = KindId(435);
pub const _INTERFACE_BODY: KindId = KindId(436);
pub const _PROPERTY_IDENTIFIER: KindId = KindId(438);
pub const _RESERVED_IDENTIFIER: KindId = KindId(439);
pub const _SEMICOLON: KindId = KindId(440);
pub const _SHORTHAND_PROPERTY_IDENTIFIER: KindId = KindId(441);
pub const _SHORTHAND_PROPERTY_IDENTIFIER_PATTERN: KindId = KindId(442);
pub const _STATEMENT_IDENTIFIER: KindId = KindId(443);
pub const _THIS_TYPE: KindId = KindId(444);
pub const _TYPE_IDENTIFIER: KindId = KindId(445);

/// Map a `KindId` back to its grammar kind string for diagnostics.
/// Returns `"<unknown>"` for ids not in this grammar's symbol table.
pub fn kind_name_from_id(id: KindId) -> &'static str {
    match id.0 {
        1 => "identifier", // "identifier"
        2 => "hash_bang_line", // "hash_bang_line"
        3 => "*", // "star"
        4 => "as", // "as"
        5 => "{", // "lbrace"
        6 => "}", // "rbrace"
        7 => "type", // "anon_type"
        8 => "typeof", // "typeof"
        9 => "import", // "anon_import"
        10 => "from", // "from"
        11 => "with", // "with"
        12 => "assert", // "assert"
        13 => "var", // "var"
        14 => ",", // "comma"
        15 => "else", // "else"
        16 => "if", // "if"
        17 => "switch", // "switch"
        18 => "for", // "for"
        19 => "(", // "lparen"
        20 => ";", // "semi"
        21 => ")", // "rparen"
        22 => "while", // "while"
        23 => "do", // "do"
        24 => "try", // "try"
        25 => "break", // "break"
        26 => "continue", // "continue"
        27 => "debugger", // "debugger"
        28 => "return", // "return"
        29 => "throw", // "throw"
        30 => ":", // "colon"
        31 => "case", // "case"
        32 => "default", // "default"
        33 => "catch", // "catch"
        34 => "finally", // "finally"
        35 => "yield", // "yield"
        36 => "=", // "eq"
        37 => "[", // "lbrack"
        38 => "]", // "rbrack"
        39 => ".", // "dot"
        40 => "class", // "anon_class"
        41 => "function", // "function"
        42 => "=>", // "eq_gt"
        43 => "?.", // "qmark_dot"
        44 => "new", // "new"
        45 => "await", // "await"
        46 => "+=", // "plus_eq"
        47 => "-=", // "dash_eq"
        48 => "*=", // "star_eq"
        49 => "/=", // "slash_eq"
        50 => "%=", // "percent_eq"
        51 => "^=", // "caret_eq"
        52 => "&=", // "amp_eq"
        53 => "|=", // "pipe_eq"
        54 => ">>=", // "gt_gt_eq"
        55 => ">>>=", // "gt_gt_gt_eq"
        56 => "<<=", // "lt_lt_eq"
        57 => "**=", // "star_star_eq"
        58 => "&&=", // "amp_amp_eq"
        59 => "||=", // "pipe_pipe_eq"
        60 => "??=", // "qmark_qmark_eq"
        61 => "...", // "dot_dot_dot"
        62 => "&&", // "amp_amp"
        63 => "||", // "pipe_pipe"
        64 => ">>", // "gt_gt"
        65 => ">>>", // "gt_gt_gt"
        66 => "<<", // "lt_lt"
        67 => "&", // "amp"
        68 => "^", // "caret"
        69 => "|", // "pipe"
        70 => "+", // "plus"
        71 => "-", // "dash"
        72 => "/", // "slash"
        73 => "%", // "percent"
        74 => "**", // "star_star"
        75 => "<", // "lt"
        76 => "<=", // "lt_eq"
        77 => "==", // "eq_eq"
        78 => "===", // "eq_eq_eq"
        79 => "!=", // "bang_eq"
        80 => "!==", // "bang_eq_eq"
        81 => ">=", // "gt_eq"
        82 => ">", // "gt"
        83 => "??", // "qmark_qmark"
        84 => "instanceof", // "instanceof"
        85 => "!", // "bang"
        86 => "~", // "tilde"
        87 => "void", // "void"
        88 => "delete", // "delete"
        89 => "unescaped_double_string_fragment", // "unescaped_double_string_fragment"
        90 => "unescaped_single_string_fragment", // "unescaped_single_string_fragment"
        91 => "escape_sequence", // "escape_sequence"
        92 => "comment", // "comment"
        93 => "`", // "bquote"
        94 => "${", // "dollar_lbrace"
        95 => "/", // "slash2"
        96 => "regex_pattern", // "regex_pattern"
        97 => "regex_flags", // "regex_flags"
        98 => "number", // "number"
        99 => "private_property_identifier", // "private_property_identifier"
        100 => "this", // "this"
        101 => "super", // "super"
        102 => "true", // "true"
        103 => "false", // "false"
        104 => "null", // "null"
        105 => "undefined", // "undefined"
        106 => "@", // "at"
        107 => "static", // "static"
        108 => "get", // "get"
        109 => "set", // "set"
        110 => "declare", // "declare"
        111 => "namespace", // "namespace"
        112 => "public", // "public"
        113 => "private", // "private"
        114 => "protected", // "protected"
        115 => "override", // "override"
        116 => "readonly", // "readonly"
        117 => "module", // "anon_module"
        118 => "any", // "any"
        119 => "number", // "anon_number"
        120 => "boolean", // "boolean"
        121 => "string", // "anon_string"
        122 => "symbol", // "symbol"
        123 => "export", // "export"
        124 => "object", // "anon_object"
        125 => "async", // "async"
        126 => "let", // "let"
        127 => "?", // "qmark"
        128 => "abstract", // "abstract"
        129 => "const", // "const"
        130 => "satisfies", // "satisfies"
        131 => "require", // "require"
        132 => "extends", // "extends"
        133 => "implements", // "implements"
        134 => "interface", // "interface"
        135 => "enum", // "enum"
        136 => "-?:", // "dash_qmark_colon"
        137 => "+?:", // "plus_qmark_colon"
        138 => "?:", // "qmark_colon"
        139 => "asserts", // "anon_asserts"
        140 => "${", // "dollar_lbrace2"
        141 => "infer", // "infer"
        142 => "is", // "is"
        143 => "keyof", // "keyof"
        144 => "in", // "in"
        145 => "unique symbol", // "unique"
        146 => "unknown", // "unknown"
        147 => "never", // "never"
        148 => "{|", // "lbrace_pipe"
        149 => "|}", // "pipe_rbrace"
        150 => "using", // "using"
        151 => "accessor", // "accessor"
        152 => "of", // "of"
        153 => "global", // "global"
        154 => "\"", // "dquote"
        155 => "'", // "squote"
        156 => "++", // "plus_plus"
        157 => "--", // "dash_dash"
        158 => "target", // "target"
        159 => "meta", // "meta"
        160 => "automatic_semicolon", // "_automatic_semicolon"
        161 => "string_fragment", // "_template_chars"
        162 => "?", // "_ternary_qmark"
        163 => "html_comment", // "html_comment"
        164 => "jsx_text", // "jsx_text"
        165 => "function_signature_automatic_semicolon", // "_function_signature_automatic_semicolon"
        166 => "__error_recovery", // "__error_recovery"
        167 => "program", // "program"
        168 => "export_statement", // "export_statement"
        169 => "namespace_export", // "namespace_export"
        170 => "export_clause", // "export_clause"
        171 => "export_specifier", // "export_specifier"
        172 => "_module_export_name", // "_module_export_name"
        173 => "declaration", // "declaration"
        174 => "import", // "import"
        175 => "import_statement", // "import_statement"
        176 => "import_clause", // "import_clause"
        177 => "_from_clause", // "_from_clause"
        178 => "namespace_import", // "namespace_import"
        179 => "named_imports", // "named_imports"
        180 => "import_specifier", // "import_specifier"
        181 => "import_attribute", // "import_attribute"
        182 => "statement", // "statement"
        183 => "expression_statement", // "expression_statement"
        184 => "variable_declaration", // "variable_declaration"
        185 => "lexical_declaration", // "lexical_declaration"
        186 => "variable_declarator", // "variable_declarator"
        187 => "statement_block", // "statement_block"
        188 => "else_clause", // "else_clause"
        189 => "if_statement", // "if_statement"
        190 => "switch_statement", // "switch_statement"
        191 => "for_statement", // "for_statement"
        192 => "for_in_statement", // "for_in_statement"
        193 => "_for_header", // "_for_header"
        194 => "while_statement", // "while_statement"
        195 => "do_statement", // "do_statement"
        196 => "try_statement", // "try_statement"
        197 => "with_statement", // "with_statement"
        198 => "break_statement", // "break_statement"
        199 => "continue_statement", // "continue_statement"
        200 => "debugger_statement", // "debugger_statement"
        201 => "return_statement", // "return_statement"
        202 => "throw_statement", // "throw_statement"
        203 => "empty_statement", // "empty_statement"
        204 => "labeled_statement", // "labeled_statement"
        205 => "switch_body", // "switch_body"
        206 => "switch_case", // "switch_case"
        207 => "switch_default", // "switch_default"
        208 => "catch_clause", // "catch_clause"
        209 => "finally_clause", // "finally_clause"
        210 => "parenthesized_expression", // "parenthesized_expression"
        211 => "expression", // "expression"
        212 => "primary_expression", // "primary_expression"
        213 => "yield_expression", // "yield_expression"
        214 => "object", // "object"
        215 => "object_pattern", // "object_pattern"
        216 => "assignment_pattern", // "assignment_pattern"
        217 => "object_assignment_pattern", // "object_assignment_pattern"
        218 => "array", // "array"
        219 => "array_pattern", // "array_pattern"
        220 => "nested_identifier", // "nested_identifier"
        221 => "class", // "class"
        222 => "class_declaration", // "class_declaration"
        223 => "class_heritage", // "class_heritage"
        224 => "function_expression", // "function_expression"
        225 => "function_declaration", // "function_declaration"
        226 => "generator_function", // "generator_function"
        227 => "generator_function_declaration", // "generator_function_declaration"
        228 => "arrow_function", // "arrow_function"
        229 => "_call_signature", // "_call_signature"
        230 => "_formal_parameter", // "_formal_parameter"
        231 => "optional_chain", // "optional_chain"
        232 => "call_expression", // "call_expression"
        233 => "new_expression", // "new_expression"
        234 => "await_expression", // "await_expression"
        235 => "member_expression", // "member_expression"
        236 => "subscript_expression", // "subscript_expression"
        237 => "lhs_expression", // "_lhs_expression"
        238 => "assignment_expression", // "assignment_expression"
        239 => "_augmented_assignment_lhs", // "_augmented_assignment_lhs"
        240 => "augmented_assignment_expression", // "augmented_assignment_expression"
        241 => "_initializer", // "_initializer"
        242 => "_destructuring_pattern", // "_destructuring_pattern"
        243 => "spread_element", // "spread_element"
        244 => "ternary_expression", // "ternary_expression"
        245 => "binary_expression", // "binary_expression"
        246 => "unary_expression", // "unary_expression"
        247 => "update_expression", // "update_expression"
        248 => "sequence_expression", // "sequence_expression"
        249 => "string", // "string"
        250 => "template_string", // "template_string"
        251 => "template_substitution", // "template_substitution"
        252 => "regex", // "regex"
        253 => "meta_property", // "meta_property"
        254 => "arguments", // "arguments"
        255 => "decorator", // "decorator"
        256 => "member_expression", // "decorator_member_expression"
        257 => "call_expression", // "decorator_call_expression"
        258 => "class_body", // "class_body"
        259 => "formal_parameters", // "formal_parameters"
        260 => "class_static_block", // "class_static_block"
        261 => "pattern", // "pattern"
        262 => "rest_pattern", // "rest_pattern"
        263 => "method_definition", // "method_definition"
        264 => "pair", // "pair"
        265 => "pair_pattern", // "pair_pattern"
        266 => "_property_name", // "_property_name"
        267 => "computed_property_name", // "computed_property_name"
        268 => "public_field_definition", // "public_field_definition"
        269 => "_import_identifier", // "_import_identifier"
        270 => "non_null_expression", // "non_null_expression"
        271 => "method_signature", // "method_signature"
        272 => "abstract_method_signature", // "abstract_method_signature"
        273 => "function_signature", // "function_signature"
        274 => "parenthesized_expression", // "decorator_parenthesized_expression"
        275 => "type_assertion", // "type_assertion"
        276 => "as_expression", // "as_expression"
        277 => "satisfies_expression", // "satisfies_expression"
        278 => "instantiation_expression", // "instantiation_expression"
        279 => "import_require_clause", // "import_require_clause"
        280 => "extends_clause", // "extends_clause"
        281 => "extends_clause_single", // "_extends_clause_single"
        282 => "implements_clause", // "implements_clause"
        283 => "ambient_declaration", // "ambient_declaration"
        284 => "abstract_class_declaration", // "abstract_class_declaration"
        285 => "module", // "module"
        286 => "internal_module", // "internal_module"
        287 => "_module", // "_module"
        288 => "import_alias", // "import_alias"
        289 => "nested_type_identifier", // "nested_type_identifier"
        290 => "interface_declaration", // "interface_declaration"
        291 => "extends_type_clause", // "extends_type_clause"
        292 => "enum_declaration", // "enum_declaration"
        293 => "enum_body", // "enum_body"
        294 => "enum_assignment", // "enum_assignment"
        295 => "type_alias_declaration", // "type_alias_declaration"
        296 => "accessibility_modifier", // "accessibility_modifier"
        297 => "override_modifier", // "override_modifier"
        298 => "required_parameter", // "required_parameter"
        299 => "optional_parameter", // "optional_parameter"
        300 => "_parameter_name", // "_parameter_name"
        301 => "omitting_type_annotation", // "omitting_type_annotation"
        302 => "adding_type_annotation", // "adding_type_annotation"
        303 => "opting_type_annotation", // "opting_type_annotation"
        304 => "type_annotation", // "type_annotation"
        305 => "member_expression", // "_type_query_member_expression_in_type_annotation"
        306 => "call_expression", // "_type_query_call_expression_in_type_annotation"
        307 => "asserts", // "asserts"
        308 => "asserts_annotation", // "asserts_annotation"
        309 => "type", // "type"
        310 => "required_parameter", // "tuple_parameter"
        311 => "optional_parameter", // "optional_tuple_parameter"
        312 => "optional_type", // "optional_type"
        313 => "rest_type", // "rest_type"
        314 => "_tuple_type_member", // "_tuple_type_member"
        315 => "constructor_type", // "constructor_type"
        316 => "primary_type", // "primary_type"
        317 => "template_type", // "template_type"
        318 => "template_literal_type", // "template_literal_type"
        319 => "infer_type", // "infer_type"
        320 => "conditional_type", // "conditional_type"
        321 => "generic_type", // "generic_type"
        322 => "type_predicate", // "type_predicate"
        323 => "type_predicate_annotation", // "type_predicate_annotation"
        324 => "member_expression", // "_type_query_member_expression"
        325 => "subscript_expression", // "_type_query_subscript_expression"
        326 => "call_expression", // "_type_query_call_expression"
        327 => "instantiation_expression", // "_type_query_instantiation_expression"
        328 => "type_query", // "type_query"
        329 => "index_type_query", // "index_type_query"
        330 => "lookup_type", // "lookup_type"
        331 => "mapped_type_clause", // "mapped_type_clause"
        332 => "literal_type", // "literal_type"
        333 => "unary_expression", // "_number"
        334 => "existential_type", // "existential_type"
        335 => "flow_maybe_type", // "flow_maybe_type"
        336 => "parenthesized_type", // "parenthesized_type"
        337 => "predefined_type", // "predefined_type"
        338 => "type_arguments", // "type_arguments"
        339 => "object_type", // "object_type"
        340 => "call_signature", // "call_signature"
        341 => "property_signature", // "property_signature"
        342 => "type_parameters", // "type_parameters"
        343 => "type_parameter", // "type_parameter"
        344 => "default_type", // "default_type"
        345 => "constraint", // "constraint"
        346 => "construct_signature", // "construct_signature"
        347 => "index_signature", // "index_signature"
        348 => "array_type", // "array_type"
        349 => "tuple_type", // "tuple_type"
        350 => "readonly_type", // "readonly_type"
        351 => "union_type", // "union_type"
        352 => "intersection_type", // "intersection_type"
        353 => "function_type", // "function_type"
        354 => "_kw_await_marker", // "_kw_await_marker"
        355 => "_kw_async_marker", // "_kw_async_marker"
        356 => "_kw_using_marker", // "_kw_using_marker"
        357 => "_kw_static_marker", // "_kw_static_marker"
        358 => "_kw_declare_marker", // "_kw_declare_marker"
        359 => "_kw_abstract_marker", // "_kw_abstract_marker"
        360 => "_kw_accessor_marker", // "_kw_accessor_marker"
        361 => "_kw_const_marker", // "_kw_const_marker"
        362 => "export_specifiers", // "_export_specifiers"
        363 => "import_specifiers", // "_import_specifiers"
        364 => "formal_parameters_elements", // "_formal_parameters_elements"
        365 => "enum_body_elements", // "_enum_body_elements"
        366 => "types", // "_types"
        367 => "type_parameters_elements", // "_type_parameters_elements"
        368 => "tuple_type_members", // "_tuple_type_members"
        369 => "import_clause_group", // "_import_clause_group"
        370 => "catch_clause_group", // "_catch_clause_group"
        371 => "_kind", // "_kind"
        372 => "__for_header_operator", // "__for_header_operator"
        373 => "ambient_declaration_global", // "_ambient_declaration_global"
        374 => "ambient_declaration_module", // "_ambient_declaration_module"
        375 => "object_type_content", // "object_type_content"
        376 => "export_statement_default", // "_export_statement_default"
        377 => "export_statement_namespace_export", // "_export_statement_namespace_export"
        378 => "export_statement_type_export", // "_export_statement_type_export"
        379 => "export_statement_equals_export", // "_export_statement_equals_export"
        380 => "binary_expression_in", // "_binary_expression_in"
        381 => "class_body_method", // "_class_body_method"
        382 => "class_body_method_sig", // "_class_body_method_sig"
        383 => "class_body_member", // "_class_body_member"
        384 => "index_signature_colon", // "_index_signature_colon"
        385 => "import_statement_clause_from", // "_import_statement_clause_from"
        386 => "import_specifier_as", // "_import_specifier_as"
        387 => "parenthesized_expression_typed", // "_parenthesized_expression_typed"
        388 => "call_expression_call", // "_call_expression_call"
        389 => "call_expression_template_call", // "_call_expression_template_call"
        390 => "call_expression_member", // "_call_expression_member"
        391 => "string_double", // "_string_double"
        392 => "string_single", // "_string_single"
        393 => "update_expression_postfix", // "_update_expression_postfix"
        394 => "update_expression_prefix", // "_update_expression_prefix"
        395 => "arrow_function_parameter", // "_arrow_function_parameter"
        396 => "class_heritage_extends_clause", // "_class_heritage_extends_clause"
        397 => "import_clause_default_import", // "_import_clause_default_import"
        398 => "export_statement_default_from", // "_export_statement_default_from"
        399 => "export_statement_default_declaration", // "_export_statement_default_declaration"
        400 => "export_statement_default_star_from", // "_export_statement_default_star_from"
        401 => "export_statement_default_ns_from", // "_export_statement_default_ns_from"
        402 => "export_statement_default_clause_from", // "_export_statement_default_clause_from"
        403 => "export_statement_default_default_kw", // "_export_statement_default_default_kw"
        404 => "export_statement_default_value", // "_export_statement_default_value"
        405 => "variable_declarator_plain", // "_variable_declarator_plain"
        406 => "variable_declarator_definite", // "_variable_declarator_definite"
        407 => "meta_property_new_target", // "_meta_property_new_target"
        408 => "meta_property_import_meta", // "_meta_property_import_meta"
        409 => "for_header_lhs", // "_for_header_lhs"
        410 => "for_header_var_kind", // "_for_header_var_kind"
        411 => "for_header_let_const_kind", // "_for_header_let_const_kind"
        412 => "program_repeat1", // "program_repeat1"
        413 => "variable_declaration_repeat1", // "variable_declaration_repeat1"
        414 => "switch_body_repeat1", // "switch_body_repeat1"
        415 => "object_repeat1", // "object_repeat1"
        416 => "object_pattern_repeat1", // "object_pattern_repeat1"
        417 => "array_repeat1", // "array_repeat1"
        418 => "array_pattern_repeat1", // "array_pattern_repeat1"
        419 => "class_repeat1", // "class_repeat1"
        420 => "sequence_expression_repeat1", // "sequence_expression_repeat1"
        421 => "template_string_repeat1", // "template_string_repeat1"
        422 => "class_body_repeat1", // "class_body_repeat1"
        423 => "extends_clause_repeat1", // "extends_clause_repeat1"
        424 => "implements_clause_repeat1", // "implements_clause_repeat1"
        425 => "extends_type_clause_repeat1", // "extends_type_clause_repeat1"
        426 => "template_literal_type_repeat1", // "template_literal_type_repeat1"
        427 => "_export_specifiers_repeat1", // "_export_specifiers_repeat1"
        428 => "_import_specifiers_repeat1", // "_import_specifiers_repeat1"
        429 => "_formal_parameters_elements_repeat1", // "_formal_parameters_elements_repeat1"
        430 => "_enum_body_elements_repeat1", // "_enum_body_elements_repeat1"
        431 => "_type_parameters_elements_repeat1", // "_type_parameters_elements_repeat1"
        432 => "_tuple_type_members_repeat1", // "_tuple_type_members_repeat1"
        433 => "object_type_content_repeat1", // "object_type_content_repeat1"
        434 => "_string_double_repeat1", // "_string_double_repeat1"
        435 => "_string_single_repeat1", // "_string_single_repeat1"
        436 => "interface_body", // "_interface_body"
        438 => "property_identifier", // "_property_identifier"
        439 => "reserved_identifier", // "_reserved_identifier"
        440 => "semicolon", // "_semicolon"
        441 => "shorthand_property_identifier", // "_shorthand_property_identifier"
        442 => "shorthand_property_identifier_pattern", // "_shorthand_property_identifier_pattern"
        443 => "statement_identifier", // "_statement_identifier"
        444 => "this_type", // "_this_type"
        445 => "type_identifier", // "_type_identifier"
        _ => "<unknown>",
    }
}
