// @generated from packages/typescript/.sittir/src/parser.c — do not hand-edit.
// Per-kind numeric ID constants matching the TS-side `TSKindId` enum.
//
// IDs come from `enum ts_symbol_identifiers` in parser.c (KindID
// runtime migration design, 2026-04-30). Use these constants when
// matching on `KindId` values; the inner u16 is the parser.c-derived
// symbol id.

use ::sittir_core::types::KindId;

pub const IDENTIFIER: KindId = KindId(1);
pub const HASH_BANG_LINE: KindId = KindId(2);
pub const STAR: KindId = KindId(3);
pub const AS_KEYWORD: KindId = KindId(4);
pub const LBRACE: KindId = KindId(5);
pub const RBRACE: KindId = KindId(6);
pub const TYPE_KEYWORD: KindId = KindId(7);
pub const TYPEOF_KEYWORD: KindId = KindId(8);
pub const IMPORT_KEYWORD: KindId = KindId(9);
pub const FROM_KEYWORD: KindId = KindId(10);
pub const WITH_KEYWORD: KindId = KindId(11);
pub const ASSERT_KEYWORD: KindId = KindId(12);
pub const VAR_KEYWORD: KindId = KindId(13);
pub const COMMA: KindId = KindId(14);
pub const ELSE_KEYWORD: KindId = KindId(15);
pub const IF_KEYWORD: KindId = KindId(16);
pub const SWITCH_KEYWORD: KindId = KindId(17);
pub const FOR_KEYWORD: KindId = KindId(18);
pub const LPAREN: KindId = KindId(19);
pub const SEMI: KindId = KindId(20);
pub const RPAREN: KindId = KindId(21);
pub const WHILE_KEYWORD: KindId = KindId(22);
pub const DO_KEYWORD: KindId = KindId(23);
pub const TRY_KEYWORD: KindId = KindId(24);
pub const BREAK_KEYWORD: KindId = KindId(25);
pub const CONTINUE_KEYWORD: KindId = KindId(26);
pub const DEBUGGER_KEYWORD: KindId = KindId(27);
pub const RETURN_KEYWORD: KindId = KindId(28);
pub const THROW_KEYWORD: KindId = KindId(29);
pub const DECLARE_KEYWORD: KindId = KindId(30);
pub const NAMESPACE_KEYWORD: KindId = KindId(31);
pub const PUBLIC_KEYWORD: KindId = KindId(32);
pub const PRIVATE_KEYWORD: KindId = KindId(33);
pub const PROTECTED_KEYWORD: KindId = KindId(34);
pub const OVERRIDE_KEYWORD: KindId = KindId(35);
pub const READONLY_KEYWORD: KindId = KindId(36);
pub const MODULE_KEYWORD: KindId = KindId(37);
pub const ANY_KEYWORD: KindId = KindId(38);
pub const NUMBER_KEYWORD: KindId = KindId(39);
pub const BOOLEAN_KEYWORD: KindId = KindId(40);
pub const STRING_KEYWORD: KindId = KindId(41);
pub const SYMBOL_KEYWORD: KindId = KindId(42);
pub const EXPORT_KEYWORD: KindId = KindId(43);
pub const OBJECT_KEYWORD: KindId = KindId(44);
pub const NEW_KEYWORD: KindId = KindId(45);
pub const GET_KEYWORD: KindId = KindId(46);
pub const SET_KEYWORD: KindId = KindId(47);
pub const ASYNC_KEYWORD: KindId = KindId(48);
pub const STATIC_KEYWORD: KindId = KindId(49);
pub const LET_KEYWORD: KindId = KindId(50);
pub const COLON: KindId = KindId(51);
pub const CASE_KEYWORD: KindId = KindId(52);
pub const DEFAULT_KEYWORD: KindId = KindId(53);
pub const CATCH_KEYWORD: KindId = KindId(54);
pub const FINALLY_KEYWORD: KindId = KindId(55);
pub const YIELD_KEYWORD: KindId = KindId(56);
pub const EQ: KindId = KindId(57);
pub const LBRACK: KindId = KindId(58);
pub const RBRACK: KindId = KindId(59);
pub const DOT: KindId = KindId(60);
pub const CLASS_KEYWORD: KindId = KindId(61);
pub const FUNCTION_KEYWORD: KindId = KindId(62);
pub const EQ_GT: KindId = KindId(63);
pub const QMARK_DOT: KindId = KindId(64);
pub const AWAIT_KEYWORD: KindId = KindId(65);
pub const PLUS_EQ: KindId = KindId(66);
pub const DASH_EQ: KindId = KindId(67);
pub const STAR_EQ: KindId = KindId(68);
pub const SLASH_EQ: KindId = KindId(69);
pub const PERCENT_EQ: KindId = KindId(70);
pub const CARET_EQ: KindId = KindId(71);
pub const AMP_EQ: KindId = KindId(72);
pub const PIPE_EQ: KindId = KindId(73);
pub const GT_GT_EQ: KindId = KindId(74);
pub const GT_GT_GT_EQ: KindId = KindId(75);
pub const LT_LT_EQ: KindId = KindId(76);
pub const STAR_STAR_EQ: KindId = KindId(77);
pub const AMP_AMP_EQ: KindId = KindId(78);
pub const PIPE_PIPE_EQ: KindId = KindId(79);
pub const QMARK_QMARK_EQ: KindId = KindId(80);
pub const DOT_DOT_DOT: KindId = KindId(81);
pub const AMP_AMP: KindId = KindId(82);
pub const PIPE_PIPE: KindId = KindId(83);
pub const GT_GT: KindId = KindId(84);
pub const GT_GT_GT: KindId = KindId(85);
pub const LT_LT: KindId = KindId(86);
pub const AMP: KindId = KindId(87);
pub const CARET: KindId = KindId(88);
pub const PIPE: KindId = KindId(89);
pub const PLUS: KindId = KindId(90);
pub const DASH: KindId = KindId(91);
pub const SLASH: KindId = KindId(92);
pub const PERCENT: KindId = KindId(93);
pub const STAR_STAR: KindId = KindId(94);
pub const LT: KindId = KindId(95);
pub const LT_EQ: KindId = KindId(96);
pub const EQ_EQ: KindId = KindId(97);
pub const EQ_EQ_EQ: KindId = KindId(98);
pub const BANG_EQ: KindId = KindId(99);
pub const BANG_EQ_EQ: KindId = KindId(100);
pub const GT_EQ: KindId = KindId(101);
pub const GT: KindId = KindId(102);
pub const QMARK_QMARK: KindId = KindId(103);
pub const INSTANCEOF_KEYWORD: KindId = KindId(104);
pub const BANG: KindId = KindId(105);
pub const TILDE: KindId = KindId(106);
pub const VOID_KEYWORD: KindId = KindId(107);
pub const DELETE_KEYWORD: KindId = KindId(108);
pub const UNESCAPED_DOUBLE_STRING_FRAGMENT: KindId = KindId(109);
pub const UNESCAPED_SINGLE_STRING_FRAGMENT: KindId = KindId(110);
pub const ESCAPE_SEQUENCE: KindId = KindId(111);
pub const BQUOTE: KindId = KindId(112);
pub const BQUOTE2: KindId = KindId(113);
pub const DOLLAR_LBRACE: KindId = KindId(114);
pub const SLASH2: KindId = KindId(115);
pub const REGEX_PATTERN: KindId = KindId(116);
pub const REGEX_FLAGS: KindId = KindId(117);
pub const PRIVATE_PROPERTY_IDENTIFIER: KindId = KindId(118);
pub const THIS: KindId = KindId(119);
pub const SUPER: KindId = KindId(120);
pub const TRUE: KindId = KindId(121);
pub const FALSE: KindId = KindId(122);
pub const NULL: KindId = KindId(123);
pub const UNDEFINED: KindId = KindId(124);
pub const AT: KindId = KindId(125);
pub const QMARK: KindId = KindId(126);
pub const ABSTRACT_KEYWORD: KindId = KindId(127);
pub const CONST_KEYWORD: KindId = KindId(128);
pub const SATISFIES_KEYWORD: KindId = KindId(129);
pub const REQUIRE_KEYWORD: KindId = KindId(130);
pub const EXTENDS_KEYWORD: KindId = KindId(131);
pub const IMPLEMENTS_KEYWORD: KindId = KindId(132);
pub const INTERFACE_KEYWORD: KindId = KindId(133);
pub const ENUM_KEYWORD: KindId = KindId(134);
pub const DASH_QMARK_COLON: KindId = KindId(135);
pub const PLUS_QMARK_COLON: KindId = KindId(136);
pub const QMARK_COLON: KindId = KindId(137);
pub const ASSERTS_KEYWORD: KindId = KindId(138);
pub const INFER_KEYWORD: KindId = KindId(139);
pub const IS_KEYWORD: KindId = KindId(140);
pub const KEYOF_KEYWORD: KindId = KindId(141);
pub const IN_KEYWORD: KindId = KindId(142);
pub const UNIQUE: KindId = KindId(143);
pub const UNKNOWN_KEYWORD: KindId = KindId(144);
pub const NEVER_KEYWORD: KindId = KindId(145);
pub const LBRACE_PIPE: KindId = KindId(146);
pub const PIPE_RBRACE: KindId = KindId(147);
pub const USING_KEYWORD: KindId = KindId(148);
pub const ACCESSOR_KEYWORD: KindId = KindId(149);
pub const OF_KEYWORD: KindId = KindId(150);
pub const GLOBAL_KEYWORD: KindId = KindId(151);
pub const COMMENT_LINE: KindId = KindId(152);
pub const COMMENT_BLOCK: KindId = KindId(153);
pub const NUMBER_HEX: KindId = KindId(154);
pub const NUMBER_FLOAT_POINT: KindId = KindId(155);
pub const NUMBER_FLOAT_LEADING_POINT: KindId = KindId(156);
pub const NUMBER_FLOAT_SCIENTIFIC: KindId = KindId(157);
pub const NUMBER_DECIMAL: KindId = KindId(158);
pub const NUMBER_BINARY: KindId = KindId(159);
pub const NUMBER_OCTAL: KindId = KindId(160);
pub const NUMBER_BIGINT: KindId = KindId(161);
pub const DQUOTE: KindId = KindId(162);
pub const DQUOTE2: KindId = KindId(163);
pub const SQUOTE: KindId = KindId(164);
pub const SQUOTE2: KindId = KindId(165);
pub const PLUS_PLUS: KindId = KindId(166);
pub const DASH_DASH: KindId = KindId(167);
pub const TARGET_KEYWORD: KindId = KindId(168);
pub const META_KEYWORD: KindId = KindId(169);
pub const _AUTOMATIC_SEMICOLON: KindId = KindId(170);
pub const _TEMPLATE_CHARS: KindId = KindId(171);
pub const _TERNARY_QMARK: KindId = KindId(172);
pub const HTML_COMMENT: KindId = KindId(173);
pub const JSX_TEXT: KindId = KindId(174);
pub const _FUNCTION_SIGNATURE_AUTOMATIC_SEMICOLON: KindId = KindId(175);
pub const __ERROR_RECOVERY: KindId = KindId(176);
pub const _TIGHT: KindId = KindId(177);
pub const _SPACE: KindId = KindId(178);
pub const _NEWLINE: KindId = KindId(179);
pub const _BLANKLINE: KindId = KindId(180);
pub const _DOUBLE_BLANKLINE: KindId = KindId(181);
pub const _INDENT: KindId = KindId(182);
pub const _DEDENT: KindId = KindId(183);
pub const PROGRAM: KindId = KindId(184);
pub const EXPORT_STATEMENT: KindId = KindId(185);
pub const NAMESPACE_EXPORT: KindId = KindId(186);
pub const EXPORT_CLAUSE: KindId = KindId(187);
pub const EXPORT_SPECIFIER: KindId = KindId(188);
pub const _MODULE_EXPORT_NAME: KindId = KindId(189);
pub const DECLARATION: KindId = KindId(190);
pub const IMPORT: KindId = KindId(191);
pub const IMPORT_STATEMENT: KindId = KindId(192);
pub const IMPORT_CLAUSE: KindId = KindId(193);
pub const _FROM_CLAUSE: KindId = KindId(194);
pub const NAMESPACE_IMPORT: KindId = KindId(195);
pub const NAMED_IMPORTS: KindId = KindId(196);
pub const IMPORT_SPECIFIER: KindId = KindId(197);
pub const IMPORT_ATTRIBUTE: KindId = KindId(198);
pub const STATEMENT: KindId = KindId(199);
pub const EXPRESSION_STATEMENT: KindId = KindId(200);
pub const VARIABLE_DECLARATION: KindId = KindId(201);
pub const LEXICAL_DECLARATION: KindId = KindId(202);
pub const VARIABLE_DECLARATOR: KindId = KindId(203);
pub const STATEMENT_BLOCK: KindId = KindId(204);
pub const ELSE_CLAUSE: KindId = KindId(205);
pub const IF_STATEMENT: KindId = KindId(206);
pub const SWITCH_STATEMENT: KindId = KindId(207);
pub const FOR_STATEMENT: KindId = KindId(208);
pub const FOR_IN_STATEMENT: KindId = KindId(209);
pub const _FOR_HEADER: KindId = KindId(210);
pub const WHILE_STATEMENT: KindId = KindId(211);
pub const DO_STATEMENT: KindId = KindId(212);
pub const TRY_STATEMENT: KindId = KindId(213);
pub const WITH_STATEMENT: KindId = KindId(214);
pub const BREAK_STATEMENT: KindId = KindId(215);
pub const CONTINUE_STATEMENT: KindId = KindId(216);
pub const DEBUGGER_STATEMENT: KindId = KindId(217);
pub const RETURN_STATEMENT: KindId = KindId(218);
pub const THROW_STATEMENT: KindId = KindId(219);
pub const EMPTY_STATEMENT: KindId = KindId(220);
pub const LABELED_STATEMENT: KindId = KindId(221);
pub const SWITCH_BODY: KindId = KindId(222);
pub const SWITCH_CASE: KindId = KindId(223);
pub const SWITCH_DEFAULT: KindId = KindId(224);
pub const CATCH_CLAUSE: KindId = KindId(225);
pub const FINALLY_CLAUSE: KindId = KindId(226);
pub const PARENTHESIZED_EXPRESSION: KindId = KindId(227);
pub const EXPRESSION: KindId = KindId(228);
pub const PRIMARY_EXPRESSION: KindId = KindId(229);
pub const YIELD_EXPRESSION: KindId = KindId(230);
pub const OBJECT: KindId = KindId(231);
pub const OBJECT_PATTERN: KindId = KindId(232);
pub const ASSIGNMENT_PATTERN: KindId = KindId(233);
pub const OBJECT_ASSIGNMENT_PATTERN: KindId = KindId(234);
pub const ARRAY: KindId = KindId(235);
pub const ARRAY_PATTERN: KindId = KindId(236);
pub const NESTED_IDENTIFIER: KindId = KindId(237);
pub const CLASS: KindId = KindId(238);
pub const CLASS_DECLARATION: KindId = KindId(239);
pub const CLASS_HERITAGE: KindId = KindId(240);
pub const FUNCTION_EXPRESSION: KindId = KindId(241);
pub const FUNCTION_DECLARATION: KindId = KindId(242);
pub const GENERATOR_FUNCTION: KindId = KindId(243);
pub const GENERATOR_FUNCTION_DECLARATION: KindId = KindId(244);
pub const ARROW_FUNCTION: KindId = KindId(245);
pub const _CALL_SIGNATURE: KindId = KindId(246);
pub const _FORMAL_PARAMETER: KindId = KindId(247);
pub const OPTIONAL_CHAIN: KindId = KindId(248);
pub const CALL_EXPRESSION: KindId = KindId(249);
pub const NEW_EXPRESSION: KindId = KindId(250);
pub const AWAIT_EXPRESSION: KindId = KindId(251);
pub const MEMBER_EXPRESSION: KindId = KindId(252);
pub const SUBSCRIPT_EXPRESSION: KindId = KindId(253);
pub const _LHS_EXPRESSION: KindId = KindId(254);
pub const ASSIGNMENT_EXPRESSION: KindId = KindId(255);
pub const _AUGMENTED_ASSIGNMENT_LHS: KindId = KindId(256);
pub const AUGMENTED_ASSIGNMENT_EXPRESSION: KindId = KindId(257);
pub const _INITIALIZER: KindId = KindId(258);
pub const _DESTRUCTURING_PATTERN: KindId = KindId(259);
pub const SPREAD_ELEMENT: KindId = KindId(260);
pub const TERNARY_EXPRESSION: KindId = KindId(261);
pub const BINARY_EXPRESSION: KindId = KindId(262);
pub const UNARY_EXPRESSION: KindId = KindId(263);
pub const UPDATE_EXPRESSION: KindId = KindId(264);
pub const SEQUENCE_EXPRESSION: KindId = KindId(265);
pub const STRING: KindId = KindId(266);
pub const TEMPLATE_STRING: KindId = KindId(267);
pub const TEMPLATE_SUBSTITUTION: KindId = KindId(268);
pub const REGEX: KindId = KindId(269);
pub const NUMBER: KindId = KindId(270);
pub const META_PROPERTY: KindId = KindId(271);
pub const ARGUMENTS: KindId = KindId(272);
pub const DECORATOR: KindId = KindId(273);
pub const DECORATOR_MEMBER_EXPRESSION: KindId = KindId(274);
pub const DECORATOR_CALL_EXPRESSION: KindId = KindId(275);
pub const CLASS_BODY: KindId = KindId(276);
pub const FORMAL_PARAMETERS: KindId = KindId(277);
pub const CLASS_STATIC_BLOCK: KindId = KindId(278);
pub const PATTERN: KindId = KindId(279);
pub const REST_PATTERN: KindId = KindId(280);
pub const METHOD_DEFINITION: KindId = KindId(281);
pub const PAIR: KindId = KindId(282);
pub const PAIR_PATTERN: KindId = KindId(283);
pub const _PROPERTY_NAME: KindId = KindId(284);
pub const COMPUTED_PROPERTY_NAME: KindId = KindId(285);
pub const PUBLIC_FIELD_DEFINITION: KindId = KindId(286);
pub const _IMPORT_IDENTIFIER: KindId = KindId(287);
pub const NON_NULL_EXPRESSION: KindId = KindId(288);
pub const METHOD_SIGNATURE: KindId = KindId(289);
pub const ABSTRACT_METHOD_SIGNATURE: KindId = KindId(290);
pub const FUNCTION_SIGNATURE: KindId = KindId(291);
pub const DECORATOR_PARENTHESIZED_EXPRESSION: KindId = KindId(292);
pub const TYPE_ASSERTION: KindId = KindId(293);
pub const AS_EXPRESSION: KindId = KindId(294);
pub const SATISFIES_EXPRESSION: KindId = KindId(295);
pub const INSTANTIATION_EXPRESSION: KindId = KindId(296);
pub const IMPORT_REQUIRE_CLAUSE: KindId = KindId(297);
pub const EXTENDS_CLAUSE: KindId = KindId(298);
pub const _EXTENDS_CLAUSE_SINGLE: KindId = KindId(299);
pub const IMPLEMENTS_CLAUSE: KindId = KindId(300);
pub const AMBIENT_DECLARATION: KindId = KindId(301);
pub const ABSTRACT_CLASS_DECLARATION: KindId = KindId(302);
pub const MODULE: KindId = KindId(303);
pub const INTERNAL_MODULE: KindId = KindId(304);
pub const _MODULE: KindId = KindId(305);
pub const IMPORT_ALIAS: KindId = KindId(306);
pub const NESTED_TYPE_IDENTIFIER: KindId = KindId(307);
pub const INTERFACE_DECLARATION: KindId = KindId(308);
pub const EXTENDS_TYPE_CLAUSE: KindId = KindId(309);
pub const ENUM_DECLARATION: KindId = KindId(310);
pub const ENUM_BODY: KindId = KindId(311);
pub const ENUM_ASSIGNMENT: KindId = KindId(312);
pub const TYPE_ALIAS_DECLARATION: KindId = KindId(313);
pub const ACCESSIBILITY_MODIFIER: KindId = KindId(314);
pub const OVERRIDE_MODIFIER: KindId = KindId(315);
pub const REQUIRED_PARAMETER: KindId = KindId(316);
pub const OPTIONAL_PARAMETER: KindId = KindId(317);
pub const _PARAMETER_NAME: KindId = KindId(318);
pub const OMITTING_TYPE_ANNOTATION: KindId = KindId(319);
pub const ADDING_TYPE_ANNOTATION: KindId = KindId(320);
pub const OPTING_TYPE_ANNOTATION: KindId = KindId(321);
pub const TYPE_ANNOTATION: KindId = KindId(322);
pub const _TYPE_QUERY_MEMBER_EXPRESSION_IN_TYPE_ANNOTATION: KindId = KindId(323);
pub const _TYPE_QUERY_CALL_EXPRESSION_IN_TYPE_ANNOTATION: KindId = KindId(324);
pub const ASSERTS: KindId = KindId(325);
pub const ASSERTS_ANNOTATION: KindId = KindId(326);
pub const TYPE: KindId = KindId(327);
pub const TUPLE_PARAMETER: KindId = KindId(328);
pub const OPTIONAL_TUPLE_PARAMETER: KindId = KindId(329);
pub const OPTIONAL_TYPE: KindId = KindId(330);
pub const REST_TYPE: KindId = KindId(331);
pub const _TUPLE_TYPE_MEMBER: KindId = KindId(332);
pub const CONSTRUCTOR_TYPE: KindId = KindId(333);
pub const PRIMARY_TYPE: KindId = KindId(334);
pub const TEMPLATE_TYPE: KindId = KindId(335);
pub const TEMPLATE_LITERAL_TYPE: KindId = KindId(336);
pub const INFER_TYPE: KindId = KindId(337);
pub const CONDITIONAL_TYPE: KindId = KindId(338);
pub const GENERIC_TYPE: KindId = KindId(339);
pub const TYPE_PREDICATE: KindId = KindId(340);
pub const TYPE_PREDICATE_ANNOTATION: KindId = KindId(341);
pub const _TYPE_QUERY_MEMBER_EXPRESSION: KindId = KindId(342);
pub const _TYPE_QUERY_SUBSCRIPT_EXPRESSION: KindId = KindId(343);
pub const _TYPE_QUERY_CALL_EXPRESSION: KindId = KindId(344);
pub const _TYPE_QUERY_INSTANTIATION_EXPRESSION: KindId = KindId(345);
pub const TYPE_QUERY: KindId = KindId(346);
pub const INDEX_TYPE_QUERY: KindId = KindId(347);
pub const LOOKUP_TYPE: KindId = KindId(348);
pub const MAPPED_TYPE_CLAUSE: KindId = KindId(349);
pub const LITERAL_TYPE: KindId = KindId(350);
pub const _NUMBER: KindId = KindId(351);
pub const EXISTENTIAL_TYPE: KindId = KindId(352);
pub const FLOW_MAYBE_TYPE: KindId = KindId(353);
pub const PARENTHESIZED_TYPE: KindId = KindId(354);
pub const PREDEFINED_TYPE: KindId = KindId(355);
pub const TYPE_ARGUMENTS: KindId = KindId(356);
pub const OBJECT_TYPE: KindId = KindId(357);
pub const CALL_SIGNATURE: KindId = KindId(358);
pub const PROPERTY_SIGNATURE: KindId = KindId(359);
pub const TYPE_PARAMETERS: KindId = KindId(360);
pub const TYPE_PARAMETER: KindId = KindId(361);
pub const DEFAULT_TYPE: KindId = KindId(362);
pub const CONSTRAINT: KindId = KindId(363);
pub const CONSTRUCT_SIGNATURE: KindId = KindId(364);
pub const INDEX_SIGNATURE: KindId = KindId(365);
pub const ARRAY_TYPE: KindId = KindId(366);
pub const TUPLE_TYPE: KindId = KindId(367);
pub const READONLY_TYPE: KindId = KindId(368);
pub const UNION_TYPE: KindId = KindId(369);
pub const INTERSECTION_TYPE: KindId = KindId(370);
pub const FUNCTION_TYPE: KindId = KindId(371);
pub const _KW_AWAIT_MARKER: KindId = KindId(372);
pub const _KW_ASYNC_MARKER: KindId = KindId(373);
pub const _KW_USING_MARKER: KindId = KindId(374);
pub const _KW_STATIC_MARKER: KindId = KindId(375);
pub const _KW_DECLARE_MARKER: KindId = KindId(376);
pub const _KW_ABSTRACT_MARKER: KindId = KindId(377);
pub const _KW_ACCESSOR_MARKER: KindId = KindId(378);
pub const _KW_CONST_MARKER: KindId = KindId(379);
pub const EXPORT_SPECIFIERS: KindId = KindId(380);
pub const IMPORT_SPECIFIERS: KindId = KindId(381);
pub const FORMAL_PARAMETERS_ELEMENTS: KindId = KindId(382);
pub const ENUM_BODY_ELEMENTS: KindId = KindId(383);
pub const TYPES: KindId = KindId(384);
pub const TYPE_PARAMETERS_ELEMENTS: KindId = KindId(385);
pub const TUPLE_TYPE_MEMBERS: KindId = KindId(386);
pub const IMPORT_CLAUSE_GROUP: KindId = KindId(387);
pub const CATCH_CLAUSE_GROUP: KindId = KindId(388);
pub const _KIND: KindId = KindId(389);
pub const __FOR_HEADER_OPERATOR: KindId = KindId(390);
pub const AMBIENT_DECLARATION_GLOBAL: KindId = KindId(391);
pub const AMBIENT_DECLARATION_MODULE: KindId = KindId(392);
pub const OBJECT_TYPE_CONTENT: KindId = KindId(393);
pub const EXPORT_STATEMENT_DEFAULT: KindId = KindId(394);
pub const EXPORT_STATEMENT_NAMESPACE_EXPORT: KindId = KindId(395);
pub const EXPORT_STATEMENT_TYPE_EXPORT: KindId = KindId(396);
pub const EXPORT_STATEMENT_EQUALS_EXPORT: KindId = KindId(397);
pub const LITERAL_TYPE_NEGATIVE_NUMBER: KindId = KindId(398);
pub const BINARY_EXPRESSION_IN: KindId = KindId(399);
pub const _EMPTY_MEMBER: KindId = KindId(400);
pub const CLASS_BODY_METHOD: KindId = KindId(401);
pub const CLASS_BODY_METHOD_SIG: KindId = KindId(402);
pub const CLASS_BODY_MEMBER: KindId = KindId(403);
pub const INDEX_SIGNATURE_COLON: KindId = KindId(404);
pub const INDEX_SIGNATURE_MAPPED_TYPE_CLAUSE: KindId = KindId(405);
pub const IMPORT_STATEMENT_CLAUSE_FROM: KindId = KindId(406);
pub const IMPORT_SPECIFIER_NAME: KindId = KindId(407);
pub const IMPORT_SPECIFIER_AS: KindId = KindId(408);
pub const PARENTHESIZED_EXPRESSION_TYPED: KindId = KindId(409);
pub const PARENTHESIZED_EXPRESSION_SEQUENCE: KindId = KindId(410);
pub const CALL_EXPRESSION_CALL: KindId = KindId(411);
pub const CALL_EXPRESSION_TEMPLATE_CALL: KindId = KindId(412);
pub const CALL_EXPRESSION_MEMBER: KindId = KindId(413);
pub const STRING_DOUBLE: KindId = KindId(414);
pub const STRING_SINGLE: KindId = KindId(415);
pub const UPDATE_EXPRESSION_POSTFIX: KindId = KindId(416);
pub const UPDATE_EXPRESSION_PREFIX: KindId = KindId(417);
pub const ARROW_FUNCTION_PARAMETER: KindId = KindId(418);
pub const CLASS_HERITAGE_EXTENDS_CLAUSE: KindId = KindId(419);
pub const IMPORT_CLAUSE_DEFAULT_IMPORT: KindId = KindId(420);
pub const EXPORT_STATEMENT_DEFAULT_FROM: KindId = KindId(421);
pub const EXPORT_STATEMENT_DEFAULT_DECLARATION: KindId = KindId(422);
pub const EXPORT_STATEMENT_DEFAULT_FROM_STAR_FROM: KindId = KindId(423);
pub const EXPORT_STATEMENT_DEFAULT_FROM_NS_FROM: KindId = KindId(424);
pub const EXPORT_STATEMENT_DEFAULT_FROM_CLAUSE_FROM: KindId = KindId(425);
pub const EXPORT_STATEMENT_DEFAULT_DECLARATION_DEFAULT_KW: KindId = KindId(426);
pub const EXPORT_STATEMENT_DEFAULT_DECLARATION_DEFAULT_KW_VALUE: KindId = KindId(427);
pub const VARIABLE_DECLARATOR_PLAIN: KindId = KindId(428);
pub const VARIABLE_DECLARATOR_DEFINITE: KindId = KindId(429);
pub const META_PROPERTY_NEW_TARGET: KindId = KindId(430);
pub const META_PROPERTY_IMPORT_META: KindId = KindId(431);
pub const FOR_HEADER_LHS: KindId = KindId(432);
pub const FOR_HEADER_VAR_KIND: KindId = KindId(433);
pub const FOR_HEADER_LET_CONST_KIND: KindId = KindId(434);
pub const PROGRAM_REPEAT1: KindId = KindId(435);
pub const VARIABLE_DECLARATION_REPEAT1: KindId = KindId(436);
pub const SWITCH_BODY_REPEAT1: KindId = KindId(437);
pub const OBJECT_REPEAT1: KindId = KindId(438);
pub const OBJECT_PATTERN_REPEAT1: KindId = KindId(439);
pub const ARRAY_REPEAT1: KindId = KindId(440);
pub const ARRAY_PATTERN_REPEAT1: KindId = KindId(441);
pub const CLASS_REPEAT1: KindId = KindId(442);
pub const SEQUENCE_EXPRESSION_REPEAT1: KindId = KindId(443);
pub const TEMPLATE_STRING_REPEAT1: KindId = KindId(444);
pub const CLASS_BODY_REPEAT1: KindId = KindId(445);
pub const EXTENDS_CLAUSE_REPEAT1: KindId = KindId(446);
pub const IMPLEMENTS_CLAUSE_REPEAT1: KindId = KindId(447);
pub const EXTENDS_TYPE_CLAUSE_REPEAT1: KindId = KindId(448);
pub const TEMPLATE_LITERAL_TYPE_REPEAT1: KindId = KindId(449);
pub const EXPORT_SPECIFIERS_REPEAT1: KindId = KindId(450);
pub const IMPORT_SPECIFIERS_REPEAT1: KindId = KindId(451);
pub const FORMAL_PARAMETERS_ELEMENTS_REPEAT1: KindId = KindId(452);
pub const ENUM_BODY_ELEMENTS_REPEAT1: KindId = KindId(453);
pub const TYPE_PARAMETERS_ELEMENTS_REPEAT1: KindId = KindId(454);
pub const TUPLE_TYPE_MEMBERS_REPEAT1: KindId = KindId(455);
pub const OBJECT_TYPE_CONTENT_REPEAT1: KindId = KindId(456);
pub const STRING_DOUBLE_REPEAT1: KindId = KindId(457);
pub const STRING_SINGLE_REPEAT1: KindId = KindId(458);
pub const _INTERFACE_BODY: KindId = KindId(459);
pub const _PROPERTY_IDENTIFIER: KindId = KindId(461);
pub const _SHORTHAND_PROPERTY_IDENTIFIER: KindId = KindId(462);
pub const _SHORTHAND_PROPERTY_IDENTIFIER_PATTERN: KindId = KindId(463);
pub const _STATEMENT_IDENTIFIER: KindId = KindId(464);
pub const _THIS_TYPE: KindId = KindId(465);
pub const _TYPE_IDENTIFIER: KindId = KindId(466);

/// Map a `KindId` back to its grammar kind string for diagnostics.
/// Returns `"<unknown>"` for ids not in this grammar's symbol table.
pub fn kind_name_from_id(id: KindId) -> &'static str {
    match id.0 {
        1 => "identifier", // "identifier"
        2 => "hash_bang_line", // "hash_bang_line"
        3 => "*", // "star"
        4 => "as", // "as_keyword"
        5 => "{", // "lbrace"
        6 => "}", // "rbrace"
        7 => "type", // "type_keyword"
        8 => "typeof", // "typeof_keyword"
        9 => "import", // "import_keyword"
        10 => "from", // "from_keyword"
        11 => "with", // "with_keyword"
        12 => "assert", // "assert_keyword"
        13 => "var", // "var_keyword"
        14 => ",", // "comma"
        15 => "else", // "else_keyword"
        16 => "if", // "if_keyword"
        17 => "switch", // "switch_keyword"
        18 => "for", // "for_keyword"
        19 => "(", // "lparen"
        20 => ";", // "semi"
        21 => ")", // "rparen"
        22 => "while", // "while_keyword"
        23 => "do", // "do_keyword"
        24 => "try", // "try_keyword"
        25 => "break", // "break_keyword"
        26 => "continue", // "continue_keyword"
        27 => "debugger", // "debugger_keyword"
        28 => "return", // "return_keyword"
        29 => "throw", // "throw_keyword"
        30 => "declare", // "declare_keyword"
        31 => "namespace", // "namespace_keyword"
        32 => "public", // "public_keyword"
        33 => "private", // "private_keyword"
        34 => "protected", // "protected_keyword"
        35 => "override", // "override_keyword"
        36 => "readonly", // "readonly_keyword"
        37 => "module", // "module_keyword"
        38 => "any", // "any_keyword"
        39 => "number", // "number_keyword"
        40 => "boolean", // "boolean_keyword"
        41 => "string", // "string_keyword"
        42 => "symbol", // "symbol_keyword"
        43 => "export", // "export_keyword"
        44 => "object", // "object_keyword"
        45 => "new", // "new_keyword"
        46 => "get", // "get_keyword"
        47 => "set", // "set_keyword"
        48 => "async", // "async_keyword"
        49 => "static", // "static_keyword"
        50 => "let", // "let_keyword"
        51 => ":", // "colon"
        52 => "case", // "case_keyword"
        53 => "default", // "default_keyword"
        54 => "catch", // "catch_keyword"
        55 => "finally", // "finally_keyword"
        56 => "yield", // "yield_keyword"
        57 => "=", // "eq"
        58 => "[", // "lbrack"
        59 => "]", // "rbrack"
        60 => ".", // "dot"
        61 => "class", // "class_keyword"
        62 => "function", // "function_keyword"
        63 => "=>", // "eq_gt"
        64 => "?.", // "qmark_dot"
        65 => "await", // "await_keyword"
        66 => "+=", // "plus_eq"
        67 => "-=", // "dash_eq"
        68 => "*=", // "star_eq"
        69 => "/=", // "slash_eq"
        70 => "%=", // "percent_eq"
        71 => "^=", // "caret_eq"
        72 => "&=", // "amp_eq"
        73 => "|=", // "pipe_eq"
        74 => ">>=", // "gt_gt_eq"
        75 => ">>>=", // "gt_gt_gt_eq"
        76 => "<<=", // "lt_lt_eq"
        77 => "**=", // "star_star_eq"
        78 => "&&=", // "amp_amp_eq"
        79 => "||=", // "pipe_pipe_eq"
        80 => "??=", // "qmark_qmark_eq"
        81 => "...", // "dot_dot_dot"
        82 => "&&", // "amp_amp"
        83 => "||", // "pipe_pipe"
        84 => ">>", // "gt_gt"
        85 => ">>>", // "gt_gt_gt"
        86 => "<<", // "lt_lt"
        87 => "&", // "amp"
        88 => "^", // "caret"
        89 => "|", // "pipe"
        90 => "+", // "plus"
        91 => "-", // "dash"
        92 => "/", // "slash"
        93 => "%", // "percent"
        94 => "**", // "star_star"
        95 => "<", // "lt"
        96 => "<=", // "lt_eq"
        97 => "==", // "eq_eq"
        98 => "===", // "eq_eq_eq"
        99 => "!=", // "bang_eq"
        100 => "!==", // "bang_eq_eq"
        101 => ">=", // "gt_eq"
        102 => ">", // "gt"
        103 => "??", // "qmark_qmark"
        104 => "instanceof", // "instanceof_keyword"
        105 => "!", // "bang"
        106 => "~", // "tilde"
        107 => "void", // "void_keyword"
        108 => "delete", // "delete_keyword"
        109 => "string_fragment", // "unescaped_double_string_fragment"
        110 => "string_fragment", // "unescaped_single_string_fragment"
        111 => "escape_sequence", // "escape_sequence"
        112 => "`", // "bquote"
        113 => "`", // "bquote2"
        114 => "${", // "dollar_lbrace"
        115 => "/", // "slash2"
        116 => "regex_pattern", // "regex_pattern"
        117 => "regex_flags", // "regex_flags"
        118 => "private_property_identifier", // "private_property_identifier"
        119 => "this", // "this"
        120 => "super", // "super"
        121 => "true", // "true"
        122 => "false", // "false"
        123 => "null", // "null"
        124 => "undefined", // "undefined"
        125 => "@", // "at"
        126 => "?", // "qmark"
        127 => "abstract", // "abstract_keyword"
        128 => "const", // "const_keyword"
        129 => "satisfies", // "satisfies_keyword"
        130 => "require", // "require_keyword"
        131 => "extends", // "extends_keyword"
        132 => "implements", // "implements_keyword"
        133 => "interface", // "interface_keyword"
        134 => "enum", // "enum_keyword"
        135 => "-?:", // "dash_qmark_colon"
        136 => "+?:", // "plus_qmark_colon"
        137 => "?:", // "qmark_colon"
        138 => "asserts", // "asserts_keyword"
        139 => "infer", // "infer_keyword"
        140 => "is", // "is_keyword"
        141 => "keyof", // "keyof_keyword"
        142 => "in", // "in_keyword"
        143 => "unique symbol", // "unique"
        144 => "unknown", // "unknown_keyword"
        145 => "never", // "never_keyword"
        146 => "{|", // "lbrace_pipe"
        147 => "|}", // "pipe_rbrace"
        148 => "using", // "using_keyword"
        149 => "accessor", // "accessor_keyword"
        150 => "of", // "of_keyword"
        151 => "global", // "global_keyword"
        152 => "comment_line", // "comment_line"
        153 => "comment_block", // "comment_block"
        154 => "number_hex", // "number_hex"
        155 => "number_float_point", // "number_float_point"
        156 => "number_float_leading_point", // "number_float_leading_point"
        157 => "number_float_scientific", // "number_float_scientific"
        158 => "number_decimal", // "number_decimal"
        159 => "number_binary", // "number_binary"
        160 => "number_octal", // "number_octal"
        161 => "number_bigint", // "number_bigint"
        162 => "\"", // "dquote"
        163 => "\"", // "dquote2"
        164 => "'", // "squote"
        165 => "'", // "squote2"
        166 => "++", // "plus_plus"
        167 => "--", // "dash_dash"
        168 => "target", // "target_keyword"
        169 => "meta", // "meta_keyword"
        170 => "automatic_semicolon", // "_automatic_semicolon"
        171 => "string_fragment", // "_template_chars"
        172 => "?", // "_ternary_qmark"
        173 => "html_comment", // "html_comment"
        174 => "jsx_text", // "jsx_text"
        175 => "function_signature_automatic_semicolon", // "_function_signature_automatic_semicolon"
        176 => "__error_recovery", // "__error_recovery"
        177 => "_tight", // "_tight"
        178 => "_space", // "_space"
        179 => "_newline", // "_newline"
        180 => "_blankline", // "_blankline"
        181 => "_double_blankline", // "_double_blankline"
        182 => "_indent", // "_indent"
        183 => "_dedent", // "_dedent"
        184 => "program", // "program"
        185 => "export_statement", // "export_statement"
        186 => "namespace_export", // "namespace_export"
        187 => "export_clause", // "export_clause"
        188 => "export_specifier", // "export_specifier"
        189 => "_module_export_name", // "_module_export_name"
        190 => "declaration", // "declaration"
        191 => "import", // "import"
        192 => "import_statement", // "import_statement"
        193 => "import_clause", // "import_clause"
        194 => "_from_clause", // "_from_clause"
        195 => "namespace_import", // "namespace_import"
        196 => "named_imports", // "named_imports"
        197 => "import_specifier", // "import_specifier"
        198 => "import_attribute", // "import_attribute"
        199 => "statement", // "statement"
        200 => "expression_statement", // "expression_statement"
        201 => "variable_declaration", // "variable_declaration"
        202 => "lexical_declaration", // "lexical_declaration"
        203 => "variable_declarator", // "variable_declarator"
        204 => "statement_block", // "statement_block"
        205 => "else_clause", // "else_clause"
        206 => "if_statement", // "if_statement"
        207 => "switch_statement", // "switch_statement"
        208 => "for_statement", // "for_statement"
        209 => "for_in_statement", // "for_in_statement"
        210 => "_for_header", // "_for_header"
        211 => "while_statement", // "while_statement"
        212 => "do_statement", // "do_statement"
        213 => "try_statement", // "try_statement"
        214 => "with_statement", // "with_statement"
        215 => "break_statement", // "break_statement"
        216 => "continue_statement", // "continue_statement"
        217 => "debugger_statement", // "debugger_statement"
        218 => "return_statement", // "return_statement"
        219 => "throw_statement", // "throw_statement"
        220 => "empty_statement", // "empty_statement"
        221 => "labeled_statement", // "labeled_statement"
        222 => "switch_body", // "switch_body"
        223 => "switch_case", // "switch_case"
        224 => "switch_default", // "switch_default"
        225 => "catch_clause", // "catch_clause"
        226 => "finally_clause", // "finally_clause"
        227 => "parenthesized_expression", // "parenthesized_expression"
        228 => "expression", // "expression"
        229 => "primary_expression", // "primary_expression"
        230 => "yield_expression", // "yield_expression"
        231 => "object", // "object"
        232 => "object_pattern", // "object_pattern"
        233 => "assignment_pattern", // "assignment_pattern"
        234 => "object_assignment_pattern", // "object_assignment_pattern"
        235 => "array", // "array"
        236 => "array_pattern", // "array_pattern"
        237 => "nested_identifier", // "nested_identifier"
        238 => "class", // "class"
        239 => "class_declaration", // "class_declaration"
        240 => "class_heritage", // "class_heritage"
        241 => "function_expression", // "function_expression"
        242 => "function_declaration", // "function_declaration"
        243 => "generator_function", // "generator_function"
        244 => "generator_function_declaration", // "generator_function_declaration"
        245 => "arrow_function", // "arrow_function"
        246 => "_call_signature", // "_call_signature"
        247 => "_formal_parameter", // "_formal_parameter"
        248 => "optional_chain", // "optional_chain"
        249 => "call_expression", // "call_expression"
        250 => "new_expression", // "new_expression"
        251 => "await_expression", // "await_expression"
        252 => "member_expression", // "member_expression"
        253 => "subscript_expression", // "subscript_expression"
        254 => "_lhs_expression", // "_lhs_expression"
        460 => "lhs_expression", // "_lhs_expression"
        255 => "assignment_expression", // "assignment_expression"
        256 => "_augmented_assignment_lhs", // "_augmented_assignment_lhs"
        257 => "augmented_assignment_expression", // "augmented_assignment_expression"
        258 => "_initializer", // "_initializer"
        259 => "_destructuring_pattern", // "_destructuring_pattern"
        260 => "spread_element", // "spread_element"
        261 => "ternary_expression", // "ternary_expression"
        262 => "binary_expression", // "binary_expression"
        263 => "unary_expression", // "unary_expression"
        264 => "update_expression", // "update_expression"
        265 => "sequence_expression", // "sequence_expression"
        266 => "string", // "string"
        267 => "template_string", // "template_string"
        268 => "template_substitution", // "template_substitution"
        269 => "regex", // "regex"
        270 => "number", // "number"
        271 => "meta_property", // "meta_property"
        272 => "arguments", // "arguments"
        273 => "decorator", // "decorator"
        274 => "decorator_member_expression", // "decorator_member_expression"
        275 => "decorator_call_expression", // "decorator_call_expression"
        276 => "class_body", // "class_body"
        277 => "formal_parameters", // "formal_parameters"
        278 => "class_static_block", // "class_static_block"
        279 => "pattern", // "pattern"
        280 => "rest_pattern", // "rest_pattern"
        281 => "method_definition", // "method_definition"
        282 => "pair", // "pair"
        283 => "pair_pattern", // "pair_pattern"
        284 => "_property_name", // "_property_name"
        285 => "computed_property_name", // "computed_property_name"
        286 => "public_field_definition", // "public_field_definition"
        287 => "_import_identifier", // "_import_identifier"
        288 => "non_null_expression", // "non_null_expression"
        289 => "method_signature", // "method_signature"
        290 => "abstract_method_signature", // "abstract_method_signature"
        291 => "function_signature", // "function_signature"
        292 => "decorator_parenthesized_expression", // "decorator_parenthesized_expression"
        293 => "type_assertion", // "type_assertion"
        294 => "as_expression", // "as_expression"
        295 => "satisfies_expression", // "satisfies_expression"
        296 => "instantiation_expression", // "instantiation_expression"
        297 => "import_require_clause", // "import_require_clause"
        298 => "extends_clause", // "extends_clause"
        299 => "extends_clause_single", // "_extends_clause_single"
        300 => "implements_clause", // "implements_clause"
        301 => "ambient_declaration", // "ambient_declaration"
        302 => "abstract_class_declaration", // "abstract_class_declaration"
        303 => "module", // "module"
        304 => "internal_module", // "internal_module"
        305 => "_module", // "_module"
        306 => "import_alias", // "import_alias"
        307 => "nested_type_identifier", // "nested_type_identifier"
        308 => "interface_declaration", // "interface_declaration"
        309 => "extends_type_clause", // "extends_type_clause"
        310 => "enum_declaration", // "enum_declaration"
        311 => "enum_body", // "enum_body"
        312 => "enum_assignment", // "enum_assignment"
        313 => "type_alias_declaration", // "type_alias_declaration"
        314 => "accessibility_modifier", // "accessibility_modifier"
        315 => "override_modifier", // "override_modifier"
        316 => "required_parameter", // "required_parameter"
        317 => "optional_parameter", // "optional_parameter"
        318 => "_parameter_name", // "_parameter_name"
        319 => "omitting_type_annotation", // "omitting_type_annotation"
        320 => "adding_type_annotation", // "adding_type_annotation"
        321 => "opting_type_annotation", // "opting_type_annotation"
        322 => "type_annotation", // "type_annotation"
        323 => "type_query_member_expression_in_type_annotation", // "_type_query_member_expression_in_type_annotation"
        324 => "type_query_call_expression_in_type_annotation", // "_type_query_call_expression_in_type_annotation"
        325 => "asserts", // "asserts"
        326 => "asserts_annotation", // "asserts_annotation"
        327 => "type", // "type"
        328 => "tuple_parameter", // "tuple_parameter"
        329 => "optional_tuple_parameter", // "optional_tuple_parameter"
        330 => "optional_type", // "optional_type"
        331 => "rest_type", // "rest_type"
        332 => "_tuple_type_member", // "_tuple_type_member"
        333 => "constructor_type", // "constructor_type"
        334 => "primary_type", // "primary_type"
        335 => "template_type", // "template_type"
        336 => "template_literal_type", // "template_literal_type"
        337 => "infer_type", // "infer_type"
        338 => "conditional_type", // "conditional_type"
        339 => "generic_type", // "generic_type"
        340 => "type_predicate", // "type_predicate"
        341 => "type_predicate_annotation", // "type_predicate_annotation"
        342 => "type_query_member_expression", // "_type_query_member_expression"
        343 => "type_query_subscript_expression", // "_type_query_subscript_expression"
        344 => "type_query_call_expression", // "_type_query_call_expression"
        345 => "type_query_instantiation_expression", // "_type_query_instantiation_expression"
        346 => "type_query", // "type_query"
        347 => "index_type_query", // "index_type_query"
        348 => "lookup_type", // "lookup_type"
        349 => "mapped_type_clause", // "mapped_type_clause"
        350 => "literal_type", // "literal_type"
        351 => "_number", // "_number"
        352 => "existential_type", // "existential_type"
        353 => "flow_maybe_type", // "flow_maybe_type"
        354 => "parenthesized_type", // "parenthesized_type"
        355 => "predefined_type", // "predefined_type"
        356 => "type_arguments", // "type_arguments"
        357 => "object_type", // "object_type"
        358 => "call_signature", // "call_signature"
        359 => "property_signature", // "property_signature"
        360 => "type_parameters", // "type_parameters"
        361 => "type_parameter", // "type_parameter"
        362 => "default_type", // "default_type"
        363 => "constraint", // "constraint"
        364 => "construct_signature", // "construct_signature"
        365 => "index_signature", // "index_signature"
        366 => "array_type", // "array_type"
        367 => "tuple_type", // "tuple_type"
        368 => "readonly_type", // "readonly_type"
        369 => "union_type", // "union_type"
        370 => "intersection_type", // "intersection_type"
        371 => "function_type", // "function_type"
        372 => "_kw_await_marker", // "_kw_await_marker"
        373 => "_kw_async_marker", // "_kw_async_marker"
        374 => "_kw_using_marker", // "_kw_using_marker"
        375 => "_kw_static_marker", // "_kw_static_marker"
        376 => "_kw_declare_marker", // "_kw_declare_marker"
        377 => "_kw_abstract_marker", // "_kw_abstract_marker"
        378 => "_kw_accessor_marker", // "_kw_accessor_marker"
        379 => "_kw_const_marker", // "_kw_const_marker"
        380 => "export_specifiers", // "export_specifiers"
        381 => "import_specifiers", // "import_specifiers"
        382 => "formal_parameters_elements", // "formal_parameters_elements"
        383 => "enum_body_elements", // "enum_body_elements"
        384 => "types", // "types"
        385 => "type_parameters_elements", // "type_parameters_elements"
        386 => "tuple_type_members", // "tuple_type_members"
        387 => "import_clause_group", // "import_clause_group"
        388 => "catch_clause_group", // "catch_clause_group"
        389 => "_kind", // "_kind"
        390 => "__for_header_operator", // "__for_header_operator"
        391 => "ambient_declaration_global", // "ambient_declaration_global"
        392 => "ambient_declaration_module", // "ambient_declaration_module"
        393 => "object_type_content", // "object_type_content"
        394 => "export_statement_default", // "export_statement_default"
        395 => "export_statement_namespace_export", // "export_statement_namespace_export"
        396 => "export_statement_type_export", // "export_statement_type_export"
        397 => "export_statement_equals_export", // "export_statement_equals_export"
        398 => "literal_type_negative_number", // "literal_type_negative_number"
        399 => "binary_expression_in", // "binary_expression_in"
        400 => "empty_member", // "_empty_member"
        401 => "class_body_method", // "class_body_method"
        402 => "class_body_method_sig", // "class_body_method_sig"
        403 => "class_body_member", // "class_body_member"
        404 => "index_signature_colon", // "index_signature_colon"
        405 => "index_signature_mapped_type_clause", // "index_signature_mapped_type_clause"
        406 => "import_statement_clause_from", // "import_statement_clause_from"
        407 => "import_specifier_name", // "import_specifier_name"
        408 => "import_specifier_as", // "import_specifier_as"
        409 => "parenthesized_expression_typed", // "parenthesized_expression_typed"
        410 => "parenthesized_expression_sequence", // "parenthesized_expression_sequence"
        411 => "call_expression_call", // "call_expression_call"
        412 => "call_expression_template_call", // "call_expression_template_call"
        413 => "call_expression_member", // "call_expression_member"
        414 => "string_double", // "string_double"
        415 => "string_single", // "string_single"
        416 => "update_expression_postfix", // "update_expression_postfix"
        417 => "update_expression_prefix", // "update_expression_prefix"
        418 => "arrow_function_parameter", // "arrow_function_parameter"
        419 => "class_heritage_extends_clause", // "class_heritage_extends_clause"
        420 => "import_clause_default_import", // "import_clause_default_import"
        421 => "export_statement_default_from", // "export_statement_default_from"
        422 => "export_statement_default_declaration", // "export_statement_default_declaration"
        423 => "export_statement_default_from_star_from", // "export_statement_default_from_star_from"
        424 => "export_statement_default_from_ns_from", // "export_statement_default_from_ns_from"
        425 => "export_statement_default_from_clause_from", // "export_statement_default_from_clause_from"
        426 => "export_statement_default_declaration_default_kw", // "export_statement_default_declaration_default_kw"
        427 => "export_statement_default_declaration_default_kw_value", // "export_statement_default_declaration_default_kw_value"
        428 => "variable_declarator_plain", // "variable_declarator_plain"
        429 => "variable_declarator_definite", // "variable_declarator_definite"
        430 => "meta_property_new_target", // "meta_property_new_target"
        431 => "meta_property_import_meta", // "meta_property_import_meta"
        432 => "for_header_lhs", // "for_header_lhs"
        433 => "for_header_var_kind", // "for_header_var_kind"
        434 => "for_header_let_const_kind", // "for_header_let_const_kind"
        435 => "program_repeat1", // "program_repeat1"
        436 => "variable_declaration_repeat1", // "variable_declaration_repeat1"
        437 => "switch_body_repeat1", // "switch_body_repeat1"
        438 => "object_repeat1", // "object_repeat1"
        439 => "object_pattern_repeat1", // "object_pattern_repeat1"
        440 => "array_repeat1", // "array_repeat1"
        441 => "array_pattern_repeat1", // "array_pattern_repeat1"
        442 => "class_repeat1", // "class_repeat1"
        443 => "sequence_expression_repeat1", // "sequence_expression_repeat1"
        444 => "template_string_repeat1", // "template_string_repeat1"
        445 => "class_body_repeat1", // "class_body_repeat1"
        446 => "extends_clause_repeat1", // "extends_clause_repeat1"
        447 => "implements_clause_repeat1", // "implements_clause_repeat1"
        448 => "extends_type_clause_repeat1", // "extends_type_clause_repeat1"
        449 => "template_literal_type_repeat1", // "template_literal_type_repeat1"
        450 => "export_specifiers_repeat1", // "export_specifiers_repeat1"
        451 => "import_specifiers_repeat1", // "import_specifiers_repeat1"
        452 => "formal_parameters_elements_repeat1", // "formal_parameters_elements_repeat1"
        453 => "enum_body_elements_repeat1", // "enum_body_elements_repeat1"
        454 => "type_parameters_elements_repeat1", // "type_parameters_elements_repeat1"
        455 => "tuple_type_members_repeat1", // "tuple_type_members_repeat1"
        456 => "object_type_content_repeat1", // "object_type_content_repeat1"
        457 => "string_double_repeat1", // "string_double_repeat1"
        458 => "string_single_repeat1", // "string_single_repeat1"
        459 => "interface_body", // "_interface_body"
        461 => "property_identifier", // "_property_identifier"
        462 => "shorthand_property_identifier", // "_shorthand_property_identifier"
        463 => "shorthand_property_identifier_pattern", // "_shorthand_property_identifier_pattern"
        464 => "statement_identifier", // "_statement_identifier"
        465 => "this_type", // "_this_type"
        466 => "type_identifier", // "_type_identifier"
        _ => "<unknown>",
    }
}

/// Whether the reader captures a named node of this kind as text: its
/// template renders from that text, so the text is the node's content —
/// free text for a pattern kind, the literal it holds for an enum kind.
pub fn is_text_kind(kind: KindId) -> bool {
    matches!(kind.0, 1 | 2 | 109 | 110 | 111 | 116 | 117 | 118 | 152 | 153 | 154 | 155 | 156 | 157 | 158 | 159 | 160 | 161 | 171 | 172 | 173 | 174 | 176 | 314 | 355 | 389 | 390)
}

/// Whether this parse kind id is an alias envelope: the reader stamps the
/// grammar symbol beside it when the node is the storage node shown under
/// the alias, so the wrap layer can seat it as the envelope's content.
pub fn is_alias_envelope(kind: KindId) -> bool {
    matches!(kind.0, 459 | 461 | 462 | 463 | 464 | 466)
}

/// Whether a node of this kind keeps its anonymous children as `$other`
/// when it has no named child: an unnamed slot of the kind stores terminal
/// kinds, and the wrap layer reclaims that slot's value from `$other`.
pub fn keeps_anonymous_children(kind: KindId) -> bool {
    matches!(kind.0, 254 | 280 | 316 | 317 | 342 | 350 | 363 | 383 | 409 | 420 | 421 | 427)
}

/// The model slot a child is stored under where its name differs from the
/// parser's key: a field-tagged child by (parent kind id, field), a named
/// child without a field by (parent kind id, the child's kind name).
/// `None` keeps the parser's key.
pub fn wire_slot(parent: KindId, field: Option<&str>, child: &str) -> Option<&'static str> {
    match (parent.0, field, child) {
        (186, None, "identifier") => Some("module_export_name"),
        (186, None, "string_double") => Some("module_export_name"),
        (186, None, "string_single") => Some("module_export_name"),
        (193, None, "import_clause_default_import") => Some("content"),
        (193, None, "named_imports") => Some("content"),
        (193, None, "namespace_import") => Some("content"),
        (209, None, "for_header_let_const_kind") => Some("for_header"),
        (209, None, "for_header_lhs") => Some("for_header"),
        (209, None, "for_header_var_kind") => Some("for_header"),
        (240, None, "class_heritage_extends_clause") => Some("content"),
        (240, None, "implements_clause") => Some("content"),
        (245, None, "arrow_function_parameter") => Some("content"),
        (245, None, "call_signature") => Some("content"),
        (254, None, "any_keyword") => Some("content"),
        (254, None, "array_pattern") => Some("content"),
        (254, None, "async_keyword") => Some("content"),
        (254, None, "boolean_keyword") => Some("content"),
        (254, None, "declare_keyword") => Some("content"),
        (254, None, "export_keyword") => Some("content"),
        (254, None, "get_keyword") => Some("content"),
        (254, None, "identifier") => Some("content"),
        (254, None, "let_keyword") => Some("content"),
        (254, None, "member_expression") => Some("content"),
        (254, None, "module_keyword") => Some("content"),
        (254, None, "namespace_keyword") => Some("content"),
        (254, None, "new_keyword") => Some("content"),
        (254, None, "non_null_expression") => Some("content"),
        (254, None, "number_keyword") => Some("content"),
        (254, None, "object_keyword") => Some("content"),
        (254, None, "object_pattern") => Some("content"),
        (254, None, "override_keyword") => Some("content"),
        (254, None, "private_keyword") => Some("content"),
        (254, None, "protected_keyword") => Some("content"),
        (254, None, "public_keyword") => Some("content"),
        (254, None, "readonly_keyword") => Some("content"),
        (254, None, "set_keyword") => Some("content"),
        (254, None, "static_keyword") => Some("content"),
        (254, None, "string_keyword") => Some("content"),
        (254, None, "subscript_expression") => Some("content"),
        (254, None, "symbol_keyword") => Some("content"),
        (254, None, "type_keyword") => Some("content"),
        (254, None, "undefined") => Some("content"),
        (280, None, "any_keyword") => Some("lhs_expression"),
        (280, None, "array_pattern") => Some("lhs_expression"),
        (280, None, "async_keyword") => Some("lhs_expression"),
        (280, None, "boolean_keyword") => Some("lhs_expression"),
        (280, None, "declare_keyword") => Some("lhs_expression"),
        (280, None, "export_keyword") => Some("lhs_expression"),
        (280, None, "get_keyword") => Some("lhs_expression"),
        (280, None, "identifier") => Some("lhs_expression"),
        (280, None, "let_keyword") => Some("lhs_expression"),
        (280, None, "member_expression") => Some("lhs_expression"),
        (280, None, "module_keyword") => Some("lhs_expression"),
        (280, None, "namespace_keyword") => Some("lhs_expression"),
        (280, None, "new_keyword") => Some("lhs_expression"),
        (280, None, "non_null_expression") => Some("lhs_expression"),
        (280, None, "number_keyword") => Some("lhs_expression"),
        (280, None, "object_keyword") => Some("lhs_expression"),
        (280, None, "object_pattern") => Some("lhs_expression"),
        (280, None, "override_keyword") => Some("lhs_expression"),
        (280, None, "private_keyword") => Some("lhs_expression"),
        (280, None, "protected_keyword") => Some("lhs_expression"),
        (280, None, "public_keyword") => Some("lhs_expression"),
        (280, None, "readonly_keyword") => Some("lhs_expression"),
        (280, None, "set_keyword") => Some("lhs_expression"),
        (280, None, "static_keyword") => Some("lhs_expression"),
        (280, None, "string_keyword") => Some("lhs_expression"),
        (280, None, "subscript_expression") => Some("lhs_expression"),
        (280, None, "symbol_keyword") => Some("lhs_expression"),
        (280, None, "type_keyword") => Some("lhs_expression"),
        (280, None, "undefined") => Some("lhs_expression"),
        (301, None, "abstract_class_declaration") => Some("content"),
        (301, None, "ambient_declaration") => Some("content"),
        (301, None, "ambient_declaration_global") => Some("content"),
        (301, None, "ambient_declaration_module") => Some("content"),
        (301, None, "class_declaration") => Some("content"),
        (301, None, "enum_declaration") => Some("content"),
        (301, None, "function_declaration") => Some("content"),
        (301, None, "function_signature") => Some("content"),
        (301, None, "generator_function_declaration") => Some("content"),
        (301, None, "import_alias") => Some("content"),
        (301, None, "interface_declaration") => Some("content"),
        (301, None, "internal_module") => Some("content"),
        (301, None, "lexical_declaration") => Some("content"),
        (301, None, "module") => Some("content"),
        (301, None, "type_alias_declaration") => Some("content"),
        (301, None, "variable_declaration") => Some("content"),
        (342, None, "dot") => Some("content"),
        (342, None, "qmark_dot") => Some("content"),
        (350, None, "false") => Some("content"),
        (350, None, "literal_type_negative_number") => Some("content"),
        (350, None, "null") => Some("content"),
        (350, None, "number_bigint") => Some("content"),
        (350, None, "number_binary") => Some("content"),
        (350, None, "number_decimal") => Some("content"),
        (350, None, "number_float_leading_point") => Some("content"),
        (350, None, "number_float_point") => Some("content"),
        (350, None, "number_float_scientific") => Some("content"),
        (350, None, "number_hex") => Some("content"),
        (350, None, "number_octal") => Some("content"),
        (350, None, "string_double") => Some("content"),
        (350, None, "string_single") => Some("content"),
        (350, None, "true") => Some("content"),
        (350, None, "undefined") => Some("content"),
        (363, None, "colon") => Some("content"),
        (363, None, "extends_keyword") => Some("content"),
        (383, None, "computed_property_name") => Some("content"),
        (383, None, "enum_assignment") => Some("content"),
        (383, None, "number_bigint") => Some("content"),
        (383, None, "number_binary") => Some("content"),
        (383, None, "number_decimal") => Some("content"),
        (383, None, "number_float_leading_point") => Some("content"),
        (383, None, "number_float_point") => Some("content"),
        (383, None, "number_float_scientific") => Some("content"),
        (383, None, "number_hex") => Some("content"),
        (383, None, "number_octal") => Some("content"),
        (383, None, "private_property_identifier") => Some("content"),
        (383, None, "property_identifier") => Some("content"),
        (383, None, "string_double") => Some("content"),
        (383, None, "string_single") => Some("content"),
        (383, Some("name"), _) => Some("content"),
        (387, None, "named_imports") => Some("content"),
        (387, None, "namespace_import") => Some("content"),
        (409, None, "any_keyword") => Some("expression"),
        (409, None, "array") => Some("expression"),
        (409, None, "arrow_function") => Some("expression"),
        (409, None, "as_expression") => Some("expression"),
        (409, None, "assignment_expression") => Some("expression"),
        (409, None, "async_keyword") => Some("expression"),
        (409, None, "augmented_assignment_expression") => Some("expression"),
        (409, None, "await_expression") => Some("expression"),
        (409, None, "binary_expression") => Some("expression"),
        (409, None, "boolean_keyword") => Some("expression"),
        (409, None, "call_expression_call") => Some("expression"),
        (409, None, "call_expression_member") => Some("expression"),
        (409, None, "call_expression_template_call") => Some("expression"),
        (409, None, "class") => Some("expression"),
        (409, None, "declare_keyword") => Some("expression"),
        (409, None, "export_keyword") => Some("expression"),
        (409, None, "false") => Some("expression"),
        (409, None, "function_expression") => Some("expression"),
        (409, None, "generator_function") => Some("expression"),
        (409, None, "get_keyword") => Some("expression"),
        (409, None, "identifier") => Some("expression"),
        (409, None, "instantiation_expression") => Some("expression"),
        (409, None, "internal_module") => Some("expression"),
        (409, None, "let_keyword") => Some("expression"),
        (409, None, "member_expression") => Some("expression"),
        (409, None, "meta_property_import_meta") => Some("expression"),
        (409, None, "meta_property_new_target") => Some("expression"),
        (409, None, "module_keyword") => Some("expression"),
        (409, None, "namespace_keyword") => Some("expression"),
        (409, None, "new_expression") => Some("expression"),
        (409, None, "new_keyword") => Some("expression"),
        (409, None, "non_null_expression") => Some("expression"),
        (409, None, "null") => Some("expression"),
        (409, None, "number_bigint") => Some("expression"),
        (409, None, "number_binary") => Some("expression"),
        (409, None, "number_decimal") => Some("expression"),
        (409, None, "number_float_leading_point") => Some("expression"),
        (409, None, "number_float_point") => Some("expression"),
        (409, None, "number_float_scientific") => Some("expression"),
        (409, None, "number_hex") => Some("expression"),
        (409, None, "number_keyword") => Some("expression"),
        (409, None, "number_octal") => Some("expression"),
        (409, None, "object") => Some("expression"),
        (409, None, "object_keyword") => Some("expression"),
        (409, None, "override_keyword") => Some("expression"),
        (409, None, "parenthesized_expression_sequence") => Some("expression"),
        (409, None, "parenthesized_expression_typed") => Some("expression"),
        (409, None, "private_keyword") => Some("expression"),
        (409, None, "protected_keyword") => Some("expression"),
        (409, None, "public_keyword") => Some("expression"),
        (409, None, "readonly_keyword") => Some("expression"),
        (409, None, "regex") => Some("expression"),
        (409, None, "satisfies_expression") => Some("expression"),
        (409, None, "set_keyword") => Some("expression"),
        (409, None, "static_keyword") => Some("expression"),
        (409, None, "string_double") => Some("expression"),
        (409, None, "string_keyword") => Some("expression"),
        (409, None, "string_single") => Some("expression"),
        (409, None, "subscript_expression") => Some("expression"),
        (409, None, "super") => Some("expression"),
        (409, None, "symbol_keyword") => Some("expression"),
        (409, None, "template_string") => Some("expression"),
        (409, None, "ternary_expression") => Some("expression"),
        (409, None, "this") => Some("expression"),
        (409, None, "true") => Some("expression"),
        (409, None, "type_assertion") => Some("expression"),
        (409, None, "type_keyword") => Some("expression"),
        (409, None, "unary_expression") => Some("expression"),
        (409, None, "undefined") => Some("expression"),
        (409, None, "update_expression_postfix") => Some("expression"),
        (409, None, "update_expression_prefix") => Some("expression"),
        (409, None, "yield_expression") => Some("expression"),
        (420, None, "type_keyword") => Some("identifier"),
        (421, None, "export_clause") => Some("content"),
        (421, None, "export_statement_default_from_clause_from") => Some("content"),
        (421, None, "export_statement_default_from_ns_from") => Some("content"),
        (421, None, "export_statement_default_from_star_from") => Some("content"),
        (421, None, "semi") => Some("automatic_semicolon"),
        (422, None, "export_statement_default_declaration_default_kw") => Some("content"),
        (422, Some("declaration"), _) => Some("content"),
        (426, None, "export_statement_default_declaration_default_kw_value") => Some("content"),
        (426, Some("declaration"), _) => Some("content"),
        (427, None, "semi") => Some("automatic_semicolon"),
        _ => None,
    }
}

/// The gap an extra occupies inside a node with no named child to own it,
/// by (kind id, anonymous tokens before the extra): the model slot whose
/// position the gap holds. `None` when the model has no slot there.
pub fn inner_gap_key(kind: KindId, preceding_tokens: u16) -> Option<&'static str> {
    match (kind.0, preceding_tokens) {
        (184, 0) => Some("statements"),
        (187, 1) => Some("export_specifiers"),
        (196, 1) => Some("import_specifiers"),
        (204, 1) => Some("statements"),
        (222, 1) => Some("cases"),
        (231, 1) => Some("properties"),
        (232, 1) => Some("properties"),
        (235, 1) => Some("elements"),
        (236, 1) => Some("elements"),
        (272, 1) => Some("elements"),
        (276, 1) => Some("content"),
        (277, 1) => Some("formal_parameters_elements"),
        (311, 1) => Some("enum_body_elements"),
        (367, 1) => Some("tuple_type_members"),
        _ => None,
    }
}

/// (parent kind id, tree-sitter field name, punctuation kind ids) for every
/// slot the parser field-tags a literal into: the separator of a repeated
/// slot, or a literal a rule puts beside a singular slot under the same
/// field. The template prints such a token itself, so the reader drops the
/// child instead of seating it, and a native read and a wrapped read hand
/// back the same slot contents.
static SLOT_SEPARATORS: &[(u16, &str, &[u16])] = &[
    (201, "declarators", &[14]),
    (202, "declarators", &[14]),
    (208, "condition", &[20]),
    (230, "expression", &[3]),
    (265, "expression", &[14]),
    (300, "type", &[14]),
    (309, "type", &[14]),
    (380, "export_specifier", &[14]),
    (381, "import_specifier", &[14]),
    (382, "formal_parameter", &[14]),
    (384, "type", &[14]),
    (385, "type_parameter", &[14]),
    (386, "tuple_type_member", &[14]),
];

pub fn is_slot_separator(parent: KindId, field: &str, child: KindId) -> bool {
    SLOT_SEPARATORS
        .iter()
        .any(|(p, f, seps)| *p == parent.0 && *f == field && seps.contains(&child.0))
}

/// Whether the model stores a `child` of a `parent` node, reached under the
/// parser field `field` (`None` for an untagged child), as a scalar: a
/// presence flag or a kind id rather than a node. Such a child keeps no
/// trivia, so the reader never makes it an owner.
pub fn stores_scalar(parent: KindId, field: Option<&str>, child: KindId) -> bool {
    match (parent.0, field) {
        (184, Some("statements")) => matches!(child.0, 220),
        (188, Some("export_kind")) => matches!(child.0, 7 | 8),
        (192, Some("import_clause")) => matches!(child.0, 7 | 8),
        (192, Some("terminator")) => matches!(child.0, 20 | 170),
        (198, Some("attribute_kind")) => matches!(child.0, 11 | 12),
        (200, Some("expression")) => matches!(child.0, 119 | 120 | 121 | 122 | 123 | 124),
        (200, Some("terminator")) => matches!(child.0, 20 | 170),
        (201, Some("terminator")) => matches!(child.0, 20 | 170),
        (202, Some("kind")) => matches!(child.0, 50 | 128),
        (202, Some("terminator")) => matches!(child.0, 20 | 170),
        (204, Some("statements")) => matches!(child.0, 220),
        (205, Some("body")) => matches!(child.0, 220),
        (206, Some("consequence")) => matches!(child.0, 220),
        (208, Some("body")) => matches!(child.0, 220),
        (208, Some("condition")) => matches!(child.0, 119 | 120 | 121 | 122 | 123 | 124 | 220),
        (208, Some("increment")) => matches!(child.0, 119 | 120 | 121 | 122 | 123 | 124),
        (208, Some("initializer")) => matches!(child.0, 119 | 120 | 121 | 122 | 123 | 124 | 220),
        (209, Some("body")) => matches!(child.0, 220),
        (211, Some("body")) => matches!(child.0, 220),
        (212, Some("body")) => matches!(child.0, 220),
        (212, Some("terminator")) => matches!(child.0, 20 | 170),
        (214, Some("body")) => matches!(child.0, 220),
        (215, Some("terminator")) => matches!(child.0, 20 | 170),
        (216, Some("terminator")) => matches!(child.0, 20 | 170),
        (217, Some("terminator")) => matches!(child.0, 20 | 170),
        (218, Some("expression")) => matches!(child.0, 119 | 120 | 121 | 122 | 123 | 124),
        (218, Some("terminator")) => matches!(child.0, 20 | 170),
        (219, Some("expression")) => matches!(child.0, 119 | 120 | 121 | 122 | 123 | 124),
        (219, Some("terminator")) => matches!(child.0, 20 | 170),
        (221, Some("body")) => matches!(child.0, 220),
        (221, Some("label")) => matches!(child.0, 7 | 30 | 31 | 32 | 33 | 34 | 35 | 36 | 37 | 38 | 39 | 40 | 41 | 42 | 43 | 44 | 45 | 46 | 47 | 48 | 49 | 50),
        (223, Some("body")) => matches!(child.0, 220),
        (223, Some("value")) => matches!(child.0, 119 | 120 | 121 | 122 | 123 | 124),
        (224, Some("body")) => matches!(child.0, 220),
        (230, Some("expression")) => matches!(child.0, 119 | 120 | 121 | 122 | 123 | 124),
        (231, Some("properties")) => matches!(child.0, 7 | 30 | 31 | 32 | 33 | 34 | 35 | 36 | 37 | 38 | 39 | 40 | 41 | 42 | 43 | 44 | 45 | 46 | 47 | 48 | 49 | 50),
        (232, Some("properties")) => matches!(child.0, 7 | 30 | 31 | 32 | 33 | 34 | 35 | 36 | 37 | 38 | 39 | 40 | 41 | 42 | 43 | 44 | 45 | 46 | 47 | 48 | 49 | 50),
        (233, Some("right")) => matches!(child.0, 119 | 120 | 121 | 122 | 123 | 124),
        (234, Some("left")) => matches!(child.0, 7 | 30 | 31 | 32 | 33 | 34 | 35 | 36 | 37 | 38 | 39 | 40 | 41 | 42 | 43 | 44 | 45 | 46 | 47 | 48 | 49 | 50),
        (234, Some("right")) => matches!(child.0, 119 | 120 | 121 | 122 | 123 | 124),
        (235, Some("elements")) => matches!(child.0, 119 | 120 | 121 | 122 | 123 | 124),
        (245, Some("body")) => matches!(child.0, 119 | 120 | 121 | 122 | 123 | 124),
        (250, Some("constructor")) => matches!(child.0, 119 | 120 | 121 | 122 | 123 | 124),
        (251, Some("expression")) => matches!(child.0, 119 | 120 | 121 | 122 | 123 | 124),
        (252, Some("object")) => matches!(child.0, 119 | 120 | 121 | 122 | 123 | 124 | 191),
        (252, Some("separator")) => matches!(child.0, 60 | 248),
        (253, Some("index")) => matches!(child.0, 119 | 120 | 121 | 122 | 123 | 124),
        (253, Some("object")) => matches!(child.0, 119 | 120 | 121 | 122 | 123 | 124),
        (254, None) => matches!(child.0, 7 | 30 | 31 | 32 | 33 | 34 | 35 | 36 | 37 | 38 | 39 | 40 | 41 | 42 | 43 | 44 | 45 | 46 | 47 | 48 | 49 | 50 | 124),
        (255, Some("right")) => matches!(child.0, 119 | 120 | 121 | 122 | 123 | 124),
        (257, Some("left")) => matches!(child.0, 7 | 30 | 31 | 32 | 33 | 34 | 35 | 36 | 37 | 38 | 39 | 40 | 41 | 42 | 43 | 44 | 45 | 46 | 47 | 48 | 49 | 50),
        (257, Some("operator")) => matches!(child.0, 66 | 67 | 68 | 69 | 70 | 71 | 72 | 73 | 74 | 75 | 76 | 77 | 78 | 79 | 80),
        (257, Some("right")) => matches!(child.0, 119 | 120 | 121 | 122 | 123 | 124),
        (260, Some("expression")) => matches!(child.0, 119 | 120 | 121 | 122 | 123 | 124),
        (261, Some("alternative")) => matches!(child.0, 119 | 120 | 121 | 122 | 123 | 124),
        (261, Some("condition")) => matches!(child.0, 119 | 120 | 121 | 122 | 123 | 124),
        (261, Some("consequence")) => matches!(child.0, 119 | 120 | 121 | 122 | 123 | 124),
        (262, Some("left")) => matches!(child.0, 119 | 120 | 121 | 122 | 123 | 124),
        (262, Some("operator")) => matches!(child.0, 3 | 82 | 83 | 84 | 85 | 86 | 87 | 88 | 89 | 90 | 91 | 92 | 93 | 94 | 95 | 96 | 97 | 98 | 99 | 100 | 101 | 102 | 103 | 104),
        (262, Some("right")) => matches!(child.0, 119 | 120 | 121 | 122 | 123 | 124),
        (263, Some("argument")) => matches!(child.0, 119 | 120 | 121 | 122 | 123 | 124),
        (263, Some("operator")) => matches!(child.0, 8 | 90 | 91 | 105 | 106 | 107 | 108),
        (265, Some("expression")) => matches!(child.0, 119 | 120 | 121 | 122 | 123 | 124),
        (268, Some("expression")) => matches!(child.0, 119 | 120 | 121 | 122 | 123 | 124),
        (272, Some("elements")) => matches!(child.0, 119 | 120 | 121 | 122 | 123 | 124),
        (276, Some("content")) => matches!(child.0, 400),
        (280, None) => matches!(child.0, 7 | 30 | 31 | 32 | 33 | 34 | 35 | 36 | 37 | 38 | 39 | 40 | 41 | 42 | 43 | 44 | 45 | 46 | 47 | 48 | 49 | 50 | 124),
        (281, Some("accessibility_modifier")) => matches!(child.0, 32 | 33 | 34),
        (281, Some("accessor_kind")) => matches!(child.0, 3 | 46 | 47),
        (281, Some("name")) => matches!(child.0, 7 | 30 | 31 | 32 | 33 | 34 | 35 | 36 | 37 | 38 | 39 | 40 | 41 | 42 | 43 | 44 | 45 | 46 | 47 | 48 | 49 | 50),
        (282, Some("key")) => matches!(child.0, 7 | 30 | 31 | 32 | 33 | 34 | 35 | 36 | 37 | 38 | 39 | 40 | 41 | 42 | 43 | 44 | 45 | 46 | 47 | 48 | 49 | 50),
        (282, Some("value")) => matches!(child.0, 119 | 120 | 121 | 122 | 123 | 124),
        (283, Some("key")) => matches!(child.0, 7 | 30 | 31 | 32 | 33 | 34 | 35 | 36 | 37 | 38 | 39 | 40 | 41 | 42 | 43 | 44 | 45 | 46 | 47 | 48 | 49 | 50),
        (285, Some("expression")) => matches!(child.0, 119 | 120 | 121 | 122 | 123 | 124),
        (286, Some("accessibility_modifier")) => matches!(child.0, 32 | 33 | 34),
        (286, Some("name")) => matches!(child.0, 7 | 30 | 31 | 32 | 33 | 34 | 35 | 36 | 37 | 38 | 39 | 40 | 41 | 42 | 43 | 44 | 45 | 46 | 47 | 48 | 49 | 50),
        (286, Some("optionality_marker")) => matches!(child.0, 105 | 126),
        (286, Some("value")) => matches!(child.0, 119 | 120 | 121 | 122 | 123 | 124),
        (288, Some("expression")) => matches!(child.0, 119 | 120 | 121 | 122 | 123 | 124),
        (289, Some("accessibility_modifier")) => matches!(child.0, 32 | 33 | 34),
        (289, Some("accessor_kind")) => matches!(child.0, 3 | 46 | 47),
        (289, Some("name")) => matches!(child.0, 7 | 30 | 31 | 32 | 33 | 34 | 35 | 36 | 37 | 38 | 39 | 40 | 41 | 42 | 43 | 44 | 45 | 46 | 47 | 48 | 49 | 50),
        (290, Some("accessibility_modifier")) => matches!(child.0, 32 | 33 | 34),
        (290, Some("accessor_kind")) => matches!(child.0, 3 | 46 | 47),
        (290, Some("name")) => matches!(child.0, 7 | 30 | 31 | 32 | 33 | 34 | 35 | 36 | 37 | 38 | 39 | 40 | 41 | 42 | 43 | 44 | 45 | 46 | 47 | 48 | 49 | 50),
        (291, Some("terminator")) => matches!(child.0, 20 | 170 | 175),
        (293, Some("expression")) => matches!(child.0, 119 | 120 | 121 | 122 | 123 | 124),
        (294, Some("expression")) => matches!(child.0, 119 | 120 | 121 | 122 | 123 | 124),
        (294, Some("type_annotation")) => matches!(child.0, 38 | 39 | 40 | 41 | 42 | 44 | 107 | 128 | 143 | 144 | 145 | 352),
        (295, Some("expression")) => matches!(child.0, 119 | 120 | 121 | 122 | 123 | 124),
        (295, Some("type_annotation")) => matches!(child.0, 38 | 39 | 40 | 41 | 42 | 44 | 107 | 143 | 144 | 145 | 352),
        (296, Some("expression")) => matches!(child.0, 119 | 120 | 121 | 122 | 123 | 124),
        (299, Some("value")) => matches!(child.0, 119 | 120 | 121 | 122 | 123 | 124),
        (300, Some("type")) => matches!(child.0, 38 | 39 | 40 | 41 | 42 | 44 | 107 | 143 | 144 | 145 | 352),
        (306, Some("terminator")) => matches!(child.0, 20 | 170),
        (312, Some("name")) => matches!(child.0, 7 | 30 | 31 | 32 | 33 | 34 | 35 | 36 | 37 | 38 | 39 | 40 | 41 | 42 | 43 | 44 | 45 | 46 | 47 | 48 | 49 | 50),
        (312, Some("value")) => matches!(child.0, 119 | 120 | 121 | 122 | 123 | 124),
        (313, Some("terminator")) => matches!(child.0, 20 | 170),
        (313, Some("value")) => matches!(child.0, 38 | 39 | 40 | 41 | 42 | 44 | 107 | 143 | 144 | 145 | 352),
        (316, None) => matches!(child.0, 32 | 33 | 34),
        (316, Some("pattern")) => matches!(child.0, 119),
        (316, Some("value")) => matches!(child.0, 119 | 120 | 121 | 122 | 123 | 124),
        (317, None) => matches!(child.0, 32 | 33 | 34),
        (317, Some("pattern")) => matches!(child.0, 119),
        (317, Some("value")) => matches!(child.0, 119 | 120 | 121 | 122 | 123 | 124),
        (319, Some("type")) => matches!(child.0, 38 | 39 | 40 | 41 | 42 | 44 | 107 | 143 | 144 | 145 | 352),
        (320, Some("type")) => matches!(child.0, 38 | 39 | 40 | 41 | 42 | 44 | 107 | 143 | 144 | 145 | 352),
        (321, Some("type")) => matches!(child.0, 38 | 39 | 40 | 41 | 42 | 44 | 107 | 143 | 144 | 145 | 352),
        (322, Some("type")) => matches!(child.0, 38 | 39 | 40 | 41 | 42 | 44 | 107 | 143 | 144 | 145 | 352),
        (323, Some("object")) => matches!(child.0, 191),
        (324, Some("function")) => matches!(child.0, 191),
        (325, Some("value")) => matches!(child.0, 119),
        (330, Some("type")) => matches!(child.0, 38 | 39 | 40 | 41 | 42 | 44 | 107 | 143 | 144 | 145 | 352),
        (331, Some("type")) => matches!(child.0, 38 | 39 | 40 | 41 | 42 | 44 | 107 | 143 | 144 | 145 | 352),
        (333, Some("type")) => matches!(child.0, 38 | 39 | 40 | 41 | 42 | 44 | 107 | 143 | 144 | 145 | 352),
        (335, Some("type")) => matches!(child.0, 38 | 39 | 40 | 41 | 42 | 44 | 107 | 143 | 144 | 145 | 352),
        (337, Some("type")) => matches!(child.0, 38 | 39 | 40 | 41 | 42 | 44 | 107 | 143 | 144 | 145 | 352),
        (338, Some("alternative")) => matches!(child.0, 38 | 39 | 40 | 41 | 42 | 44 | 107 | 143 | 144 | 145 | 352),
        (338, Some("consequence")) => matches!(child.0, 38 | 39 | 40 | 41 | 42 | 44 | 107 | 143 | 144 | 145 | 352),
        (338, Some("left")) => matches!(child.0, 38 | 39 | 40 | 41 | 42 | 44 | 107 | 143 | 144 | 145 | 352),
        (338, Some("right")) => matches!(child.0, 38 | 39 | 40 | 41 | 42 | 44 | 107 | 143 | 144 | 145 | 352),
        (340, Some("name")) => matches!(child.0, 38 | 39 | 40 | 41 | 42 | 44 | 107 | 119 | 143 | 144 | 145),
        (340, Some("type")) => matches!(child.0, 38 | 39 | 40 | 41 | 42 | 44 | 107 | 143 | 144 | 145 | 352),
        (342, None) => matches!(child.0, 60 | 64),
        (342, Some("object")) => matches!(child.0, 119),
        (343, Some("index")) => matches!(child.0, 38 | 39 | 40 | 41 | 42 | 44 | 107 | 143 | 144 | 145),
        (343, Some("object")) => matches!(child.0, 119),
        (344, Some("function")) => matches!(child.0, 191),
        (345, Some("function")) => matches!(child.0, 191),
        (346, Some("expression")) => matches!(child.0, 119),
        (347, Some("type")) => matches!(child.0, 38 | 39 | 40 | 41 | 42 | 44 | 107 | 143 | 144 | 145 | 352),
        (348, Some("index_type")) => matches!(child.0, 38 | 39 | 40 | 41 | 42 | 44 | 107 | 143 | 144 | 145 | 352),
        (348, Some("type")) => matches!(child.0, 38 | 39 | 40 | 41 | 42 | 44 | 107 | 143 | 144 | 145 | 352),
        (349, Some("alias")) => matches!(child.0, 38 | 39 | 40 | 41 | 42 | 44 | 107 | 143 | 144 | 145 | 352),
        (349, Some("type")) => matches!(child.0, 38 | 39 | 40 | 41 | 42 | 44 | 107 | 143 | 144 | 145 | 352),
        (350, None) => matches!(child.0, 121 | 122 | 123 | 124),
        (353, Some("type")) => matches!(child.0, 38 | 39 | 40 | 41 | 42 | 44 | 107 | 143 | 144 | 145 | 352),
        (354, Some("type")) => matches!(child.0, 38 | 39 | 40 | 41 | 42 | 44 | 107 | 143 | 144 | 145 | 352),
        (357, Some("closing")) => matches!(child.0, 6 | 147),
        (357, Some("opening")) => matches!(child.0, 5 | 146),
        (359, Some("accessibility_modifier")) => matches!(child.0, 32 | 33 | 34),
        (359, Some("name")) => matches!(child.0, 7 | 30 | 31 | 32 | 33 | 34 | 35 | 36 | 37 | 38 | 39 | 40 | 41 | 42 | 43 | 44 | 45 | 46 | 47 | 48 | 49 | 50),
        (362, Some("type")) => matches!(child.0, 38 | 39 | 40 | 41 | 42 | 44 | 107 | 143 | 144 | 145 | 352),
        (363, None) => matches!(child.0, 51 | 131),
        (363, Some("type")) => matches!(child.0, 38 | 39 | 40 | 41 | 42 | 44 | 107 | 143 | 144 | 145 | 352),
        (366, Some("type")) => matches!(child.0, 38 | 39 | 40 | 41 | 42 | 44 | 107 | 143 | 144 | 145 | 352),
        (368, Some("type")) => matches!(child.0, 38 | 39 | 40 | 41 | 42 | 44 | 107 | 143 | 144 | 145 | 352),
        (369, Some("left")) => matches!(child.0, 38 | 39 | 40 | 41 | 42 | 44 | 107 | 143 | 144 | 145 | 352),
        (369, Some("right")) => matches!(child.0, 38 | 39 | 40 | 41 | 42 | 44 | 107 | 143 | 144 | 145 | 352),
        (370, Some("left")) => matches!(child.0, 38 | 39 | 40 | 41 | 42 | 44 | 107 | 143 | 144 | 145 | 352),
        (370, Some("right")) => matches!(child.0, 38 | 39 | 40 | 41 | 42 | 44 | 107 | 143 | 144 | 145 | 352),
        (371, Some("return_type")) => matches!(child.0, 38 | 39 | 40 | 41 | 42 | 44 | 107 | 143 | 144 | 145 | 352),
        (383, None) => matches!(child.0, 7 | 30 | 31 | 32 | 33 | 34 | 35 | 36 | 37 | 38 | 39 | 40 | 41 | 42 | 43 | 44 | 45 | 46 | 47 | 48 | 49 | 50),
        (384, Some("type")) => matches!(child.0, 38 | 39 | 40 | 41 | 42 | 44 | 107 | 143 | 144 | 145 | 352),
        (386, Some("tuple_type_member")) => matches!(child.0, 38 | 39 | 40 | 41 | 42 | 44 | 107 | 143 | 144 | 145 | 352),
        (392, Some("terminator")) => matches!(child.0, 20 | 170),
        (392, Some("type")) => matches!(child.0, 38 | 39 | 40 | 41 | 42 | 44 | 107 | 143 | 144 | 145 | 352),
        (395, Some("terminator")) => matches!(child.0, 20 | 170),
        (396, Some("terminator")) => matches!(child.0, 20 | 170),
        (397, Some("expression")) => matches!(child.0, 119 | 120 | 121 | 122 | 123 | 124),
        (397, Some("terminator")) => matches!(child.0, 20 | 170),
        (398, Some("operator")) => matches!(child.0, 90 | 91),
        (399, Some("left")) => matches!(child.0, 119 | 120 | 121 | 122 | 123 | 124),
        (399, Some("right")) => matches!(child.0, 119 | 120 | 121 | 122 | 123 | 124),
        (401, Some("terminator")) => matches!(child.0, 20 | 170),
        (402, Some("terminator")) => matches!(child.0, 14 | 175),
        (403, Some("terminator")) => matches!(child.0, 14 | 20 | 170),
        (404, Some("index_type")) => matches!(child.0, 38 | 39 | 40 | 41 | 42 | 44 | 107 | 143 | 144 | 145 | 352),
        (404, Some("name")) => matches!(child.0, 7 | 30 | 31 | 32 | 33 | 34 | 35 | 36 | 37 | 38 | 39 | 40 | 41 | 42 | 43 | 44 | 45 | 46 | 47 | 48 | 49 | 50),
        (404, Some("sign")) => matches!(child.0, 90 | 91),
        (405, Some("sign")) => matches!(child.0, 90 | 91),
        (407, Some("import_kind")) => matches!(child.0, 7 | 8),
        (407, Some("name")) => matches!(child.0, 7),
        (408, Some("alias")) => matches!(child.0, 7),
        (408, Some("import_kind")) => matches!(child.0, 7 | 8),
        (408, Some("name")) => matches!(child.0, 7),
        (409, None) => matches!(child.0, 119 | 120 | 121 | 122 | 123 | 124),
        (411, Some("function")) => matches!(child.0, 119 | 120 | 121 | 122 | 123 | 124 | 191),
        (412, Some("function")) => matches!(child.0, 119 | 120 | 121 | 122 | 123 | 124),
        (413, Some("function")) => matches!(child.0, 119 | 120 | 121 | 122 | 123 | 124),
        (416, Some("argument")) => matches!(child.0, 119 | 120 | 121 | 122 | 123 | 124),
        (416, Some("operator")) => matches!(child.0, 166 | 167),
        (417, Some("argument")) => matches!(child.0, 119 | 120 | 121 | 122 | 123 | 124),
        (417, Some("operator")) => matches!(child.0, 166 | 167),
        (418, Some("parameter")) => matches!(child.0, 7 | 30 | 31 | 32 | 33 | 34 | 35 | 36 | 37 | 38 | 39 | 40 | 41 | 42 | 43 | 44 | 45 | 46 | 47 | 48 | 49 | 50),
        (420, None) => matches!(child.0, 7),
        (421, None) => matches!(child.0, 20 | 170),
        (427, None) => matches!(child.0, 20 | 170),
        (427, Some("value")) => matches!(child.0, 119 | 120 | 121 | 122 | 123 | 124),
        (428, Some("value")) => matches!(child.0, 119 | 120 | 121 | 122 | 123 | 124),
        (432, Some("operator")) => matches!(child.0, 142 | 150),
        (432, Some("right")) => matches!(child.0, 119 | 120 | 121 | 122 | 123 | 124),
        (433, Some("operator")) => matches!(child.0, 142 | 150),
        (433, Some("right")) => matches!(child.0, 119 | 120 | 121 | 122 | 123 | 124),
        (433, Some("value")) => matches!(child.0, 119 | 120 | 121 | 122 | 123 | 124),
        (434, Some("kind")) => matches!(child.0, 50 | 128),
        (434, Some("operator")) => matches!(child.0, 142 | 150),
        (434, Some("right")) => matches!(child.0, 119 | 120 | 121 | 122 | 123 | 124),
        (461, Some("content")) => matches!(child.0, 7 | 30 | 31 | 32 | 33 | 34 | 35 | 36 | 37 | 38 | 39 | 40 | 41 | 42 | 43 | 44 | 45 | 46 | 47 | 48 | 49 | 50),
        (462, Some("content")) => matches!(child.0, 7 | 30 | 31 | 32 | 33 | 34 | 35 | 36 | 37 | 38 | 39 | 40 | 41 | 42 | 43 | 44 | 45 | 46 | 47 | 48 | 49 | 50),
        (463, Some("content")) => matches!(child.0, 7 | 30 | 31 | 32 | 33 | 34 | 35 | 36 | 37 | 38 | 39 | 40 | 41 | 42 | 43 | 44 | 45 | 46 | 47 | 48 | 49 | 50),
        (464, Some("content")) => matches!(child.0, 7 | 30 | 31 | 32 | 33 | 34 | 35 | 36 | 37 | 38 | 39 | 40 | 41 | 42 | 43 | 44 | 45 | 46 | 47 | 48 | 49 | 50),
        _ => false,
    }
}
