/**
 * Orchestrator: 12-step pipeline → GrammarModel
 *
 * Runs the full pipeline from grammar name to hydrated, optimized GrammarModel.
 */

import { loadGrammar, type Grammar } from './grammar.ts';
import { loadNodeTypes } from './node-types.ts';
import { classifyRules, collectConcreteTypes } from './enriched-grammar.ts';
import {
	initializeModels,
	reconcile,
	refineAllModelTypes,
	isBranch,
	isContainer,
	eachChildSlot,
	type GrammarModel,
	type NodeModel,
	type HiddenModel,
} from './node-model.ts';
import { inferTokenAliases, applyTokenAliases } from './semantic-aliases.ts';
import { applyNaming } from './naming.ts';
import { optimize } from './optimization.ts';
import { hydrate } from './hydration.ts';
import { loadOverrides, validateOverrides, mergeOverrides, detectOverrideCandidates } from './overrides.ts';

function stripChildSignatures(children: any): any {
	if (Array.isArray(children)) {
		return children.map((c: any) => {
			const { childSignature, ...rest } = c;
			return rest;
		});
	}
	const { childSignature, ...rest } = children;
	return rest;
}

// ---------------------------------------------------------------------------
// JSON5 serialization (preserved from grammar-model.ts)
// ---------------------------------------------------------------------------

function toJson5(value: unknown, indent: number = 0): string {
	const pad = '  '.repeat(indent);
	const pad1 = '  '.repeat(indent + 1);

	if (value === null || value === undefined) return 'null';
	if (typeof value === 'boolean' || typeof value === 'number') return String(value);
	if (typeof value === 'string') return JSON.stringify(value);

	if (Array.isArray(value)) {
		if (value.length === 0) return '[]';
		if (value.every(v => typeof v === 'string' || typeof v === 'number' || typeof v === 'boolean')) {
			const inner = value.map(v => JSON.stringify(v)).join(', ');
			if (inner.length < 80) return `[${inner}]`;
		}
		const items = value.map(v => `${pad1}${toJson5(v, indent + 1)},`);
		return `[\n${items.join('\n')}\n${pad}]`;
	}

	if (typeof value === 'object') {
		const obj = value as Record<string, unknown>;
		// Skip Map and other non-plain objects
		if (value instanceof Map || value instanceof Set) return '{}';
		const entries = Object.entries(obj);
		if (entries.length === 0) return '{}';
		const lines = entries.map(([k, v]) => {
			const key = /^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(k) ? k : JSON.stringify(k);
			return `${pad1}${key}: ${toJson5(v, indent + 1)},`;
		});
		return `{\n${lines.join('\n')}\n${pad}}`;
	}

	return String(value);
}

function serializeToJson5(nodes: Map<string, NodeModel>): string {
	const serializable: Record<string, unknown> = {};
	for (const [k, v] of nodes) {
		// Strip runtime-only properties (rule, signatures, naming)
		if (v.modelType === 'branch') {
			const { rule, typeName, factoryName, ...branchRest } = v;
			const fields = branchRest.fields.map(f => {
				const { fieldSignature: _fs, propertyName: _pn, ...fieldRest } = f;
				return fieldRest;
			});
			const children = branchRest.children ? stripChildSignatures(branchRest.children) : undefined;
			serializable[k] = { ...branchRest, fields, ...(children ? { children } : {}) };
		} else if (v.modelType === 'container') {
			const { rule, typeName, factoryName, ...containerRest } = v;
			const children = stripChildSignatures(containerRest.children);
			serializable[k] = { ...containerRest, children };
		} else if (v.modelType === 'leaf' || v.modelType === 'enum') {
			const { rule, typeName, factoryName, ...leafRest } = v;
			serializable[k] = leafRest;
		} else if (v.modelType === 'keyword') {
			const { rule, typeName, factoryName, ...kwRest } = v;
			serializable[k] = kwRest;
		} else if (v.modelType === 'token') {
			const { rule, typeName, factoryName, ...tokenRest } = v;
			serializable[k] = tokenRest;
		} else if (v.modelType === 'supertype') {
			const { rule, typeName, factoryName, ...stRest } = v;
			serializable[k] = stRest;
		} else if (v.modelType === 'hidden') {
			// Internal only — skip serialization
		}
	}
	return `// Auto-generated by @sittir/codegen — do not edit\n${toJson5(serializable)}\n`;
}

// ---------------------------------------------------------------------------
// Hidden model creation — resolve hidden rules to concrete subtypes
// ---------------------------------------------------------------------------

/**
 * Scan all branch/container children for hidden rule kinds (starting with `_`)
 * that aren't in the models map. Create HiddenModel entries for them by
 * resolving their concrete subtypes from the grammar.
 */
function createHiddenModels(models: Map<string, NodeModel>, grammar: Grammar): void {
	// Collect all hidden kinds referenced in child slots
	const hiddenKinds = new Set<string>();
	for (const model of models.values()) {
		if (isBranch(model) && model.children) {
			eachChildSlot(model.children, (child) => {
				for (const k of child.kinds) {
					if (typeof k === 'string' && k.startsWith('_') && !models.has(k)) {
						hiddenKinds.add(k);
					}
				}
			});
		}
		if (isContainer(model)) {
			eachChildSlot(model.children, (child) => {
				for (const k of child.kinds) {
					if (typeof k === 'string' && k.startsWith('_') && !models.has(k)) {
						hiddenKinds.add(k);
					}
				}
			});
		}
	}

	// Also check field kinds (some hidden rules appear as field types)
	for (const model of models.values()) {
		if (isBranch(model)) {
			for (const field of model.fields) {
				for (const k of field.kinds) {
					if (typeof k === 'string' && k.startsWith('_') && !models.has(k)) {
						hiddenKinds.add(k);
					}
				}
			}
		}
	}

	// Create HiddenModel for each
	for (const kind of hiddenKinds) {
		const rule = grammar.rules[kind];
		if (!rule) continue;

		const subtypes: string[] = [];
		collectConcreteTypes(rule, grammar, subtypes, new Set());

		// Only create HiddenModel if it resolves to concrete types that exist as models
		const validSubtypes = new Set(subtypes.filter(s => models.has(s)));
		if (validSubtypes.size === 0) continue;

		const hidden: HiddenModel = {
			modelType: 'hidden',
			kind,
			subtypes: validSubtypes,
			rule: null,
		};
		models.set(kind, hidden);
	}
}

// ---------------------------------------------------------------------------
// buildModel — 13-step orchestrator
// ---------------------------------------------------------------------------

export function buildModel(grammarName: string): { grammarModel: GrammarModel; serialized: string } {
	// Steps 1-2: Load sources
	const grammar = loadGrammar(grammarName);
	const nodeTypes = loadNodeTypes(grammarName);

	// Step 3: Classify grammar rules
	const enrichedRules = classifyRules(grammar);

	// Step 4: Initialize from NodeTypes
	const models = initializeModels(nodeTypes);

	// Step 4b: Load and merge overrides (FR-022)
	const overrides = loadOverrides(grammarName);
	if (Object.keys(overrides).length > 0) {
		const overrideErrors = validateOverrides(overrides, models, grammar);
		if (overrideErrors.length > 0) {
			for (const err of overrideErrors) {
				console.warn(`[overrides] ${err.kind}${err.field ? `.${err.field}` : ''}: ${err.message}`);
			}
		}
		mergeOverrides(models, overrides);
		detectOverrideCandidates(models, grammar);
	}

	// Step 5: Reconcile
	reconcile(models, enrichedRules, grammarName);

	// Step 6: Refine model types
	refineAllModelTypes(models);

	// Step 7-8: Semantic aliases
	const aliases = inferTokenAliases(models, grammar);
	applyTokenAliases(models, aliases);

	// Step 8b: Create HiddenModel entries for hidden rules referenced in child slots
	createHiddenModels(models, grammar);

	// Step 9: Naming
	applyNaming(models);

	// Serialize before optimization (matches current behavior)
	const serialized = serializeToJson5(models);

	// Step 10: Optimize
	const signatures = optimize(models);

	// Step 11: Hydrate
	const hydratedModels = hydrate(models);

	// Step 12: Return
	return {
		grammarModel: {
			name: grammarName,
			models: hydratedModels,
			signatures,
		},
		serialized,
	};
}
