// Generated from bindings.scm and the vocabulary by `pnpm exec tsx packages/cli/src/cli.ts tool bindings-inventory --write`. Do not edit.
/// <reference path="../codegen/src/dsl/authoring-globals.d.ts" />
import { bindings, field, rename, split } from '../codegen/src/dsl/dsl-authoring.ts';

export default bindings({
	hash: "7697676fd12b9bb573d8035dfbd5978e4bfc3a121350412214192ea5d79e1fd1",
	patches: {
		attribute_item: { "2": field("content") },
		field_expression: { "0": field("object"), "2": field("property") },
		field_initializer: { "0/0": field("attributes") },
		for_expression: { "2": field("left"), "4": field("right") },
		for_lifetimes: { "2": field("lifetimes") },
		inner_attribute_item: { "3": field("content") },
		let_declaration: { "2": field("name") },
		macro_invocation: { "0": field("function") },
		match_expression: { "1": field("subject") },
		pointer_type_mut: { "1": field("writable") },
		reference_expression_mut: { "1": field("exclusive") },
		reference_expression_raw_const: { "1/0": field("raw") },
		reference_expression_raw_mut: { "1/0": field("raw"), "1/1": field("writable") },
		reference_pattern: { "1/0": field("exclusive") },
		reference_type: { "2/0": field("exclusive") },
		shorthand_field_initializer: { "1": field("field") },
		slice_pattern: { "1/0": field("patterns") },
		static_item: { "2/0": field("by_reference") },
		trait_item: { "5": field("extends") },
		try_expression: { "0": field("argument") },
		tuple_expression: { "2": field("expressions") },
		tuple_struct_pattern: { "2/0": field("patterns") },
		tuple_type: { "1": field("types") },
		type_item: { "6": field("value") },
		type_parameter: { "1/0": field("constraint"), "2/0/1": field("default") },
		unary_expression: { "1": field("argument") },
		use_list: { "1/0": field("use_clauses") },
		use_wildcard: { "0/0": field("use_wildcard_group") },
		visibility_modifier_pub: { "1/0": field("scope") },
		where_clause: { "1/0": field("where_predicates") }
	},
	renames: [
		rename("source_file", "module"),
		rename("function_item", "function_declaration"),
		rename("function_signature_item", "signature_function_declaration"),
		rename("impl_item_body", "extension_declaration"),
		rename("trait_item", "trait_interface_declaration"),
		rename("struct_item", "struct_declaration"),
		rename("enum_item", "enum_declaration"),
		rename("enum_variant", "enum_member_declaration"),
		rename("union_item", "union_declaration"),
		rename("type_item", "type_alias_declaration"),
		rename("associated_type", "associated_type_alias_declaration"),
		rename("mod_item", "module_declaration"),
		rename("foreign_mod_item", "foreign_module_declaration"),
		rename("extern_crate_declaration", "crate_import_statement"),
		rename("const_item", "constant_declaration"),
		rename("static_item", "static_variable_declaration"),
		rename("let_declaration", "variable_declaration"),
		rename("macro_definition", "macro_declaration"),
		rename("parameter", "parameter_declaration"),
		rename("self_parameter", "self_parameter_declaration"),
		rename("variadic_parameter", "variadic_parameter_declaration"),
		rename("type_parameter", "type_parameter_declaration"),
		rename("const_parameter", "const_type_parameter_declaration"),
		rename("lifetime_parameter", "lifetime_type_parameter_declaration"),
		rename("block", "block_statement"),
		rename("if_expression", "if_statement"),
		rename("loop_expression", "loop_statement"),
		rename("while_expression", "while_loop_statement"),
		rename("for_expression", "for_loop_statement"),
		rename("return_expression", "return_statement"),
		rename("match_expression", "match_statement"),
		rename("use_declaration", "import_statement"),
		rename("break_expression", "break_statement"),
		rename("continue_expression", "continue_statement"),
		rename("where_predicate", "predicate_where_clause"),
		rename("let_condition", "let_clause"),
		rename("match_arm", "arm_match_clause"),
		rename("last_match_arm", "last_arm_match_clause"),
		rename("use_as_clause", "as_import_clause"),
		rename("use_list", "list_import_clause"),
		rename("scoped_use_list", "scoped_list_import_clause"),
		rename("use_wildcard", "wildcard_import_clause"),
		rename("macro_rule", "rule_macro_clause"),
		rename("trait_bounds", "bounds_clause"),
		rename("higher_ranked_trait_bound", "higher_ranked_bounds_clause"),
		rename("removed_trait_bound", "removed_bounds_clause"),
		rename("use_bounds", "use_bounds_clause"),
		rename("for_lifetimes", "lifetimes_clause"),
		rename("field_initializer", "field_struct_element"),
		rename("base_field_initializer", "base_struct_element"),
		rename("type_binding", "type_binding_element"),
		rename("token_tree", "token_tree_macro_element"),
		rename("delim_token_tree", "delimited_token_tree_macro_element"),
		rename("token_tree_pattern", "pattern_token_tree_macro_element"),
		rename("token_binding_pattern", "token_binding_macro_element"),
		rename("token_repetition", "token_repetition_macro_element"),
		rename("token_repetition_pattern", "pattern_token_repetition_macro_element"),
		rename("fragment_specifier", "fragment_macro_element"),
		rename("macro_invocation", "macro_call_expression"),
		rename("compound_assignment_expr", "compound_assignment_expression"),
		rename("field_expression", "member_expression"),
		rename("index_expression", "subscript_expression"),
		rename("closure_expression", "lambda_expression"),
		rename("type_cast_expression", "as_cast_expression"),
		rename("tuple_expression", "tuple_collection_expression"),
		rename("array_expression", "list_collection_expression"),
		rename("struct_expression", "struct_collection_expression"),
		rename("unsafe_block", "unsafe_block_expression"),
		rename("async_block", "async_block_expression"),
		rename("const_block", "const_block_expression"),
		rename("try_block", "try_block_expression"),
		rename("gen_block", "gen_block_expression"),
		rename("generic_function", "instantiation_expression"),
		rename("tuple_struct_pattern", "struct_tuple_pattern"),
		rename("field_pattern", "field_struct_pattern"),
		rename("remaining_field_pattern", "rest_struct_pattern"),
		rename("ref_pattern", "reference_pattern"),
		rename("reference_pattern", "value_reference_pattern"),
		rename("mut_pattern", "mutable_pattern"),
		rename("generic_type_with_turbofish", "turbofish_generic_type"),
		rename("never_type", "never_primitive_type"),
		rename("scoped_type_identifier", "path_type"),
		rename("scoped_type_identifier_in_expression_position", "expression_path_type"),
		rename("escape_sequence", "escape_string_literal"),
		rename("string_content", "text_string_literal"),
		rename("integer_literal_decimal", "integer_number_literal"),
		rename("integer_literal_hex", "hex_integer_number_literal"),
		rename("integer_literal_binary", "binary_integer_number_literal"),
		rename("integer_literal_octal", "octal_integer_number_literal"),
		rename("float_literal", "float_number_literal"),
		rename("negative_literal", "negative_number_literal"),
		rename("metavariable", "metavariable_identifier"),
		rename("lifetime", "lifetime_identifier"),
		rename("label", "label_identifier"),
		rename("self", "self_identifier"),
		rename("super", "super_identifier"),
		rename("crate", "crate_identifier"),
		rename("visibility_modifier_pub", "public_visibility_modifier"),
		rename("attribute_item", "attribute"),
		rename("inner_attribute_item", "inner_attribute"),
		rename("attribute", "content_attribute")
	],
	splits: [
		split("function_signature_item", "signature_method_declaration", { within: ["declaration_list", "trait_item"], containers: [{ name: "trait_interface_declaration_body", field: "body" }] }),
		split("function_item", "method_declaration", { within: ["declaration_list", "trait_item"], containers: [{ name: "trait_interface_declaration_body", field: "body" }] })
	]
});
