// Auto-generated by @sittir/codegen — DO NOT EDIT
//
// Derivation log for grammar 'rust' — copy-pasteable
// grammar extension snippets plus the raw data arrays they
// came from. Every `suggestedRules` entry is a real
// `transform(...)` or `choice(...)` expression; paste the
// ones you want into your own overrides.ts.

// @ts-nocheck — the DSL globals (grammar, transform, field,
// choice, $) are injected by @sittir/codegen's evaluator at
// runtime. This file is documentation / copy-paste source,
// not a standalone module; it isn't imported at build time.

// ---------------------------------------------------------------
// Summary
// ---------------------------------------------------------------
// Field inferences:  15  (0 applied, 15 held)
// Rule promotions:   41  (40 applied, 1 held)
// Repeated shapes:   5  (advisory — suggested supertypes/groups)
// Round-trip fails: 33  (26 parse errors, 7 AST mismatches)

// ---------------------------------------------------------------
// Round-trip failures — corpus cases that didn't survive
// parse → readNode → render → reparse. Each entry shows the
// input and rendered text so you can spot what the renderer
// dropped. Common causes:
//   - Repeated slot missing a `joinBy` separator (renders only
//     the first occurrence of a multi-valued field)
//   - Missing `transform()` patch wrapping an anonymous token
//     that should be a named field
//   - Template gap — rule content has no renderable slot for
//     some structural position
// ---------------------------------------------------------------
export const roundTripFailures: Array<{
  readonly entry: string;
  readonly kind: string;
  readonly category: "parse-error" | "ast-mismatch";
  readonly input?: string;
  readonly rendered?: string;
  readonly message: string;
}> = [
  // --- if_expression (8) ---
  {
    entry: "Let declarations with if expressions as the value",
    kind: "if_expression",
    category: "parse-error",
    input:    "if b {\n    c\n} else {\n    d\n}",
    rendered: "b {\n    c\n} else {\n    d\n}",
    message: "kind not found at rendered offset 18",
  },
  {
    entry: "If expressions",
    kind: "if_expression",
    category: "parse-error",
    input:    "if n == 1 {\n  } else if n == 2 {\n  } else {\n  }",
    rendered: "n == 1 {\n  } else if n == 2 {\n  } else {\n  }",
    message: "re-parse error: \"n == 1 {\n  } else if n == 2 {\n  } else {\n  }\"",
  },
  {
    entry: "Basic if let expressions",
    kind: "if_expression",
    category: "parse-error",
    input:    "if let Some(a) = b\n    && c\n    && d\n    && let Some(e) = f\n{\n}",
    rendered: "let Some(a) = b\n     && c\n     && d\n     && let Some(e) = f {\n}",
    message: "re-parse error: \"let Some(a) = b\n     && c\n     && d\n     && let Some(e) = f {\n}\"",
  },
  {
    entry: "If let expressions",
    kind: "if_expression",
    category: "parse-error",
    input:    "if let (\"Bacon\", b) = dish {\n}",
    rendered: "let (\"Bacon\", b) = dish {\n}",
    message: "kind not found at rendered offset 18",
  },
  {
    entry: "Match expressions",
    kind: "if_expression",
    category: "parse-error",
    input:    "if a {\n        \"200 (but this is not very stylish)\"\n      }",
    rendered: "a {\n        \"200 (but this is not very stylish)\"\n      }",
    message: "re-parse error: \"a {\n        \"200 (but this is not very stylish)\"\n      }\"",
  },
  {
    entry: "For expressions",
    kind: "if_expression",
    category: "parse-error",
    input:    "if x % 2 == 0 { continue 'outer; }",
    rendered: "x % 2 == 0 { continue 'outer; }",
    message: "re-parse error: \"x % 2 == 0 { continue 'outer; }\"",
  },
  {
    entry: "Inline const or Const blocks as expression",
    kind: "if_expression",
    category: "parse-error",
    input:    "if *x < 0 { const { &4i32.pow(4) } } else { x }",
    rendered: "*x < 0 { const { &4i32.pow(4) } } else { x }",
    message: "re-parse error: \"*x < 0 { const { &4i32.pow(4) } } else { x }\"",
  },
  {
    entry: "Or patterns",
    kind: "if_expression",
    category: "parse-error",
    input:    "if let A(x) | B(x) = expr {\n    do_stuff_with(x);\n}",
    rendered: "let A(x) | B(x) = expr {\n    do_stuff_with(x);\n}",
    message: "re-parse error: \"let A(x) | B(x) = expr {\n    do_stuff_with(x);\n}\"",
  },
  // --- struct_item (4) ---
  {
    entry: "Structs",
    kind: "struct_item",
    category: "parse-error",
    input:    "struct Proton;",
    rendered: "struct Proton",
    message: "re-parse error: \"struct Proton\"",
  },
  {
    entry: "Attributes",
    kind: "struct_item",
    category: "parse-error",
    input:    "struct Baz;",
    rendered: "struct Baz",
    message: "re-parse error: \"struct Baz\"",
  },
  {
    entry: "Crate visibility",
    kind: "struct_item",
    category: "parse-error",
    input:    "crate struct Foo(crate crate::Bar);",
    rendered: "crate struct Foo (crate crate::Bar)",
    message: "re-parse error: \"crate struct Foo (crate crate::Bar)\"",
  },
  {
    entry: "Const generics with default",
    kind: "struct_item",
    category: "parse-error",
    input:    "pub struct Loaf<T: Sized, const N: usize = 1>([T; N]);",
    rendered: "pub struct Loaf <T: Sized, const N: usize = 1> ([T; N])",
    message: "re-parse error: \"pub struct Loaf <T: Sized, const N: usize = 1> ([T; N])\"",
  },
  // --- tuple_expression (3) ---
  {
    entry: "Attributes and Expressions",
    kind: "tuple_expression",
    category: "parse-error",
    input:    "(#[hello] 2, 7, 8)",
    rendered: "(#[hello] ,,, 8)",
    message: "re-parse error: \"(#[hello] ,,, 8)\"",
  },
  {
    entry: "Tuple expressions",
    kind: "tuple_expression",
    category: "parse-error",
    input:    "(0,)",
    rendered: "( ,, )",
    message: "re-parse error: \"( ,, )\"",
  },
  {
    entry: "Struct patterns",
    kind: "tuple_expression",
    category: "parse-error",
    input:    "(\"toddler\", name)",
    rendered: "( ,, name)",
    message: "re-parse error: \"( ,, name)\"",
  },
  // --- impl_item (2) ---
  {
    entry: "Trait impl signature",
    kind: "impl_item",
    category: "parse-error",
    input:    "impl<K: Debug + Ord> Debug for OccupiedError<K>;",
    rendered: "impl <K: Debug + Ord> Debug for OccupiedError<K>",
    message: "re-parse error: \"impl <K: Debug + Ord> Debug for OccupiedError<K>\"",
  },
  {
    entry: "Disable automatically derived trait impls",
    kind: "impl_item",
    category: "ast-mismatch",
    input:    "impl !Send for Foo {}",
    rendered: "impl Send for Foo {}",
    message: "impl_item: childCount 6 ≠ 5 [\"impl\",\"!\",type_identifier,\"for\",type_identifier,declaration_list] vs [\"impl\",type_identifier,\"for\",type_identifier,declaration_lis",
  },
  // --- block (1) ---
  {
    entry: "Impls with default functions",
    kind: "block",
    category: "parse-error",
    input:    "{\n    // Make 'default' still works as an identifier\n    default.bar();\n  }",
    rendered: "{// Make 'default' still works as an identifier default.bar();}",
    message: "re-parse error: \"{// Make 'default' still works as an identifier default.bar();}\"",
  },
  // --- loop_expression (1) ---
  {
    entry: "Loop expressions",
    kind: "loop_expression",
    category: "parse-error",
    input:    "'outer: loop {\n  'inner: loop {\n    break 'outer;\n    break true;\n  }\n}",
    rendered: ":: loop {\n  'inner: loop {\n    break 'outer;\n    break true;\n  }\n}",
    message: "re-parse error: \":: loop {\n  'inner: loop {\n    break 'outer;\n    break true;\n  }\n}\"",
  },
  // --- mut_pattern (2) ---
  {
    entry: "Closures",
    kind: "mut_pattern",
    category: "parse-error",
    input:    "mut e",
    rendered: "mut e",
    message: "kind not found at rendered offset 14",
  },
  {
    entry: "Reference patterns",
    kind: "mut_pattern",
    category: "parse-error",
    input:    "mut y",
    rendered: "mut y",
    message: "kind not found at rendered offset 14",
  },
  // --- raw_string_literal (3) ---
  {
    entry: "Raw string literals",
    kind: "raw_string_literal",
    category: "parse-error",
    input:    "r#\"abc\"#",
    rendered: "abc",
    message: "kind not found at rendered offset 18",
  },
  {
    entry: "Raw byte string literals",
    kind: "raw_string_literal",
    category: "parse-error",
    input:    "br#\"abc\"#",
    rendered: "abc",
    message: "kind not found at rendered offset 18",
  },
  {
    entry: "Raw C string literals",
    kind: "raw_string_literal",
    category: "parse-error",
    input:    "cr#\"abc\"#",
    rendered: "abc",
    message: "kind not found at rendered offset 18",
  },
  // --- macro_definition (1) ---
  {
    entry: "Macro definition",
    kind: "macro_definition",
    category: "parse-error",
    input:    "macro_rules! say_hello {\n    () => (\n        println!(\"Hello!\");\n    )\n}",
    rendered: "macro_rules!say_hello }",
    message: "re-parse error: \"macro_rules!say_hello }\"",
  },
  // --- function_type (2) ---
  {
    entry: "Function types",
    kind: "function_type",
    category: "parse-error",
    input:    "fn(i32)",
    rendered: "(i32)",
    message: "kind not found at rendered offset 10",
  },
  {
    entry: "Unsafe and extern function types",
    kind: "function_type",
    category: "parse-error",
    input:    "extern \"C\" fn(*mut c_void)",
    rendered: "(*mut c_void)",
    message: "kind not found at rendered offset 10",
  },
  // --- struct_pattern (1) ---
  {
    entry: "Let-else Statements",
    kind: "struct_pattern",
    category: "ast-mismatch",
    input:    "Foo::Bar {\n    texts,\n    values,\n}",
    rendered: "Foo::Bar{texts,values}",
    message: "struct_pattern: childCount 7 ≠ 6 [scoped_type_identifier,\"{\",field_pattern,\",\",field_pattern,\",\",\"}\"] vs [scoped_type_identifier,\"{\",field_pattern,\",\",field_pat",
  },
  // --- mod_item (1) ---
  {
    entry: "Inner attributes",
    kind: "mod_item",
    category: "ast-mismatch",
    input:    "mod macos_only {\n  #![cfg(target_os = \"macos\")]\n}",
    rendered: "mod macos_only;{\n  #![cfg(target_os = \"macos\")]\n}",
    message: "mod_item[2]: named flag true ≠ false",
  },
  // --- array_expression (2) ---
  {
    entry: "Attributes and Expressions",
    kind: "array_expression",
    category: "ast-mismatch",
    input:    "[#[hello] 2, 7, 8]",
    rendered: "[#[hello] 8]",
    message: "array_expression: childCount 8 ≠ 4 [\"[\",attribute_item,integer_literal,\",\",integer_literal,\",\",integer_literal,\"]\"] vs [\"[\",attribute_item,integer_literal,\"]\"]",
  },
  {
    entry: "Index expressions",
    kind: "array_expression",
    category: "ast-mismatch",
    input:    "[1, 2, 3, 4]",
    rendered: "[ 4]",
    message: "array_expression: childCount 9 ≠ 3 [\"[\",integer_literal,\",\",integer_literal,\",\",integer_literal,\",\",integer_literal,\"]\"] vs [\"[\",integer_literal,\"]\"]",
  },
  // --- generic_type (1) ---
  {
    entry: "Scoped functions",
    kind: "generic_type",
    category: "ast-mismatch",
    input:    "C::<D>",
    rendered: "C <D>",
    message: "generic_type: childCount 3 ≠ 2 [type_identifier,\"::\",type_arguments] vs [type_identifier,type_arguments]",
  },
  // --- tuple_struct_pattern (1) ---
  {
    entry: "Captured patterns",
    kind: "tuple_struct_pattern",
    category: "ast-mismatch",
    input:    "A(_)",
    rendered: "A()",
    message: "tuple_struct_pattern: childCount 4 ≠ 3 [identifier,\"(\",\"_\",\")\"] vs [identifier,\"(\",\")\"]",
  },
];

// ---------------------------------------------------------------
// suggestedRules — drop entries into your overrides.ts rules map.
// Each key is a rule kind; each value is a transform/choice call
// that mirrors the shape you'd hand-write yourself.
// ---------------------------------------------------------------
export const suggestedRules = {
  // _non_special_token: 1 inferred field(s)
  // [held] "_non_special_token" field 'mutable_specifier' on $.mutable_specifier — 91% agreement, 11 parents. Parent rule is not a top-level SEQ so transform() can't target a position; inference is applied inside Link's applyInferredFields pass (tree rewrite) rather than via overrides.ts.

  // arguments: 1 inferred field(s)
  // [held] "arguments" field 'attributes' on $.attribute_item — 80% agreement, 5 parents. Parent rule is not a top-level SEQ so transform() can't target a position; inference is applied inside Link's applyInferredFields pass (tree rewrite) rather than via overrides.ts.

  // enum_variant_list: 1 inferred field(s)
  // [held] "enum_variant_list" field 'attributes' on $.attribute_item — 80% agreement, 5 parents. Parent rule is not a top-level SEQ so transform() can't target a position; inference is applied inside Link's applyInferredFields pass (tree rewrite) rather than via overrides.ts.

  // field_declaration_list: 1 inferred field(s)
  // [held] "field_declaration_list" field 'attributes' on $.attribute_item — 80% agreement, 5 parents. Parent rule is not a top-level SEQ so transform() can't target a position; inference is applied inside Link's applyInferredFields pass (tree rewrite) rather than via overrides.ts.

  // field_initializer: 1 inferred field(s)
  // [held] "field_initializer" field 'attributes' on $.attribute_item — 80% agreement, 5 parents. Parent rule is not a top-level SEQ so transform() can't target a position; inference is applied inside Link's applyInferredFields pass (tree rewrite) rather than via overrides.ts.

  // impl_item: 1 inferred field(s)
  "impl_item": ($, original) => transform(original, {
    // [held] 86% agreement, 7 parents
    5: field("where_clause"),  // $.where_clause
  }),

  // last_match_arm: 1 inferred field(s)
  // [held] "last_match_arm" field 'attributes' on $.attribute_item — 80% agreement, 5 parents. Parent rule is not a top-level SEQ so transform() can't target a position; inference is applied inside Link's applyInferredFields pass (tree rewrite) rather than via overrides.ts.

  // match_arm: 1 inferred field(s)
  // [held] "match_arm" field 'attributes' on $.attribute_item — 80% agreement, 5 parents. Parent rule is not a top-level SEQ so transform() can't target a position; inference is applied inside Link's applyInferredFields pass (tree rewrite) rather than via overrides.ts.

  // parameters: 1 inferred field(s)
  // [held] "parameters" field 'attributes' on $.attribute_item — 80% agreement, 5 parents. Parent rule is not a top-level SEQ so transform() can't target a position; inference is applied inside Link's applyInferredFields pass (tree rewrite) rather than via overrides.ts.

  // static_item: 1 inferred field(s)
  "static_item": ($, original) => transform(original, {
    // [held] 91% agreement, 11 parents
    3: field("mutable_specifier"),  // $.mutable_specifier
  }),

  // struct_item: 2 inferred field(s)
  // [held] "struct_item" field 'where_clause' on $.where_clause — 86% agreement, 7 parents. Parent rule is not a top-level SEQ so transform() can't target a position; inference is applied inside Link's applyInferredFields pass (tree rewrite) rather than via overrides.ts.
  // [held] "struct_item" field 'where_clause' on $.where_clause — 86% agreement, 7 parents. Parent rule is not a top-level SEQ so transform() can't target a position; inference is applied inside Link's applyInferredFields pass (tree rewrite) rather than via overrides.ts.

  // trait_item: 1 inferred field(s)
  "trait_item": ($, original) => transform(original, {
    // [held] 86% agreement, 7 parents
    6: field("where_clause"),  // $.where_clause
  }),

  // type_arguments: 1 inferred field(s)
  // [held] "type_arguments" field 'bounds' on $.trait_bounds — 100% agreement, 5 parents. Parent rule is not a top-level SEQ so transform() can't target a position; inference is applied inside Link's applyInferredFields pass (tree rewrite) rather than via overrides.ts.

  // type_parameters: 1 inferred field(s)
  // [held] "type_parameters" field 'attributes' on $.attribute_item — 80% agreement, 5 parents. Parent rule is not a top-level SEQ so transform() can't target a position; inference is applied inside Link's applyInferredFields pass (tree rewrite) rather than via overrides.ts.

  // --- Promoted supertypes (add matching names to grammar.supertypes) ---
  // [applied] promoted supertype
  "_statement": $ => choice($.expression_statement, $.const_item, $.macro_invocation, $.macro_definition, $.empty_statement, $.attribute_item, $.inner_attribute_item, $.mod_item, $.foreign_mod_item, $.struct_item, $.union_item, $.enum_item, $.type_item, $.function_item, $.function_signature_item, $.impl_item, $.trait_item, $.associated_type, $.let_declaration, $.use_declaration, $.extern_crate_declaration, $.static_item),

  // [applied] promoted supertype
  "_declaration_statement": $ => choice($.const_item, $.macro_invocation, $.macro_definition, $.empty_statement, $.attribute_item, $.inner_attribute_item, $.mod_item, $.foreign_mod_item, $.struct_item, $.union_item, $.enum_item, $.type_item, $.function_item, $.function_signature_item, $.impl_item, $.trait_item, $.associated_type, $.let_declaration, $.use_declaration, $.extern_crate_declaration, $.static_item),

  // [applied] promoted supertype
  "_token_pattern": $ => choice($.token_tree_pattern, $.token_repetition_pattern, $.token_binding_pattern, $.metavariable, $.string_literal, $.raw_string_literal, $.char_literal, $.boolean_literal, $.integer_literal, $.float_literal, $.identifier, $.mutable_specifier, $.self, $.super, $.crate, $.primitive_type),

  // [applied] promoted supertype
  "_tokens": $ => choice($.token_tree, $.token_repetition, $.metavariable, $.string_literal, $.raw_string_literal, $.char_literal, $.boolean_literal, $.integer_literal, $.float_literal, $.identifier, $.mutable_specifier, $.self, $.super, $.crate, $.primitive_type),

  // [applied] promoted supertype
  "_use_clause": $ => choice($.self, $.identifier, $.metavariable, $.super, $.crate, $.scoped_identifier, $.use_as_clause, $.use_list, $.scoped_use_list, $.use_wildcard),

  // [applied] promoted supertype
  "_type": $ => choice($.abstract_type, $.reference_type, $.metavariable, $.pointer_type, $.generic_type, $.scoped_type_identifier, $.tuple_type, $.unit_type, $.array_type, $.function_type, $.type_identifier, $.macro_invocation, $.never_type, $.dynamic_type, $.bounded_type, $.removed_trait_bound, $.primitive_type),

  // [applied] promoted supertype
  "_expression_except_range": $ => choice($.unary_expression, $.reference_expression, $.try_expression, $.binary_expression, $.assignment_expression, $.compound_assignment_expr, $.type_cast_expression, $.call_expression, $.return_expression, $.yield_expression, $.string_literal, $.raw_string_literal, $.char_literal, $.boolean_literal, $.integer_literal, $.float_literal, $.identifier, $.self, $.scoped_identifier, $.generic_function, $.await_expression, $.field_expression, $.array_expression, $.tuple_expression, $.macro_invocation, $.unit_expression, $.break_expression, $.continue_expression, $.index_expression, $.metavariable, $.closure_expression, $.parenthesized_expression, $.struct_expression, $.unsafe_block, $.async_block, $.gen_block, $.try_block, $.block, $.if_expression, $.match_expression, $.while_expression, $.loop_expression, $.for_expression, $.const_block),

  // [applied] promoted supertype
  "_expression": $ => choice($.unary_expression, $.reference_expression, $.try_expression, $.binary_expression, $.assignment_expression, $.compound_assignment_expr, $.type_cast_expression, $.call_expression, $.return_expression, $.yield_expression, $.string_literal, $.raw_string_literal, $.char_literal, $.boolean_literal, $.integer_literal, $.float_literal, $.identifier, $.self, $.scoped_identifier, $.generic_function, $.await_expression, $.field_expression, $.array_expression, $.tuple_expression, $.macro_invocation, $.unit_expression, $.break_expression, $.continue_expression, $.index_expression, $.metavariable, $.closure_expression, $.parenthesized_expression, $.struct_expression, $.unsafe_block, $.async_block, $.gen_block, $.try_block, $.block, $.if_expression, $.match_expression, $.while_expression, $.loop_expression, $.for_expression, $.const_block, $.range_expression),

  // [applied] promoted supertype
  "_expression_ending_with_block": $ => choice($.unsafe_block, $.async_block, $.gen_block, $.try_block, $.block, $.if_expression, $.match_expression, $.while_expression, $.loop_expression, $.for_expression, $.const_block),

  // [applied] promoted supertype
  "_delim_tokens": $ => choice($.string_literal, $.raw_string_literal, $.char_literal, $.boolean_literal, $.integer_literal, $.float_literal, $.identifier, $.mutable_specifier, $.self, $.super, $.crate, $.primitive_type, $.token_tree),

  // [applied] promoted supertype
  "_non_delim_token": $ => choice($.string_literal, $.raw_string_literal, $.char_literal, $.boolean_literal, $.integer_literal, $.float_literal, $.identifier, $.mutable_specifier, $.self, $.super, $.crate, $.primitive_type),

  // [applied] promoted supertype
  "_condition": $ => choice($.unary_expression, $.reference_expression, $.try_expression, $.binary_expression, $.assignment_expression, $.compound_assignment_expr, $.type_cast_expression, $.call_expression, $.return_expression, $.yield_expression, $.string_literal, $.raw_string_literal, $.char_literal, $.boolean_literal, $.integer_literal, $.float_literal, $.identifier, $.self, $.scoped_identifier, $.generic_function, $.await_expression, $.field_expression, $.array_expression, $.tuple_expression, $.macro_invocation, $.unit_expression, $.break_expression, $.continue_expression, $.index_expression, $.metavariable, $.closure_expression, $.parenthesized_expression, $.struct_expression, $.unsafe_block, $.async_block, $.gen_block, $.try_block, $.block, $.if_expression, $.match_expression, $.while_expression, $.loop_expression, $.for_expression, $.const_block, $.range_expression, $.let_condition, $.let_chain),

  // [applied] promoted supertype
  "_pattern": $ => choice($.string_literal, $.raw_string_literal, $.char_literal, $.boolean_literal, $.integer_literal, $.float_literal, $.negative_literal, $.identifier, $.scoped_identifier, $.generic_pattern, $.tuple_pattern, $.tuple_struct_pattern, $.struct_pattern, $.ref_pattern, $.slice_pattern, $.captured_pattern, $.reference_pattern, $.remaining_field_pattern, $.mut_pattern, $.range_pattern, $.or_pattern, $.const_block, $.macro_invocation),

  // [applied] promoted supertype
  "_literal": $ => choice($.string_literal, $.raw_string_literal, $.char_literal, $.boolean_literal, $.integer_literal, $.float_literal),

  // [applied] promoted supertype
  "_literal_pattern": $ => choice($.string_literal, $.raw_string_literal, $.char_literal, $.boolean_literal, $.integer_literal, $.float_literal, $.negative_literal),

  // [applied] promoted supertype
  "_path": $ => choice($.self, $.identifier, $.metavariable, $.super, $.crate, $.scoped_identifier),

  // --- Repeated-shape candidates (reused across ≥2 parents) ---
  // parents: _range_pattern_left, _range_pattern_prefix, range_pattern_left, range_pattern_prefix
  "_shared_2": $ => choice($._literal_pattern, $._path),

  // parents: function_type, struct_pattern
  "_type_identifier": $ => choice($._type_identifier, $.scoped_type_identifier),

  // parents: scoped_identifier, scoped_type_identifier
  "_shared_3": $ => choice($._path, $.bracketed_type, $.generic_type),

};

// ---------------------------------------------------------------
// Raw derivation data — typed arrays for tooling
// ---------------------------------------------------------------
export interface PromotedRule {
  readonly kind: string;
  readonly classification: 'enum' | 'supertype' | 'terminal' | 'polymorph';
  readonly applied: boolean;
}
export const promotedRules: readonly PromotedRule[] = [
  { kind: "_condition", classification: "supertype", applied: true },
  { kind: "_declaration_statement", classification: "supertype", applied: true },
  { kind: "_delim_tokens", classification: "supertype", applied: true },
  { kind: "_expression", classification: "supertype", applied: true },
  { kind: "_expression_ending_with_block", classification: "supertype", applied: true },
  { kind: "_expression_except_range", classification: "supertype", applied: true },
  { kind: "_literal", classification: "supertype", applied: true },
  { kind: "_literal_pattern", classification: "supertype", applied: true },
  { kind: "_non_delim_token", classification: "supertype", applied: true },
  { kind: "_path", classification: "supertype", applied: true },
  { kind: "_pattern", classification: "supertype", applied: true },
  { kind: "_statement", classification: "supertype", applied: true },
  { kind: "_token_pattern", classification: "supertype", applied: true },
  { kind: "_tokens", classification: "supertype", applied: true },
  { kind: "_type", classification: "supertype", applied: true },
  { kind: "_use_clause", classification: "supertype", applied: true },
  { kind: "char_literal", classification: "terminal", applied: true },
  { kind: "escape_sequence", classification: "terminal", applied: true },
  { kind: "inner_doc_comment_marker", classification: "terminal", applied: true },
  { kind: "integer_literal", classification: "terminal", applied: true },
  { kind: "outer_doc_comment_marker", classification: "terminal", applied: true },
  { kind: "unit_expression", classification: "terminal", applied: true },
  { kind: "unit_type", classification: "terminal", applied: true },
  { kind: "closure_expression", classification: "polymorph", applied: true },
  { kind: "closure_expression_block", classification: "polymorph", applied: true },
  { kind: "closure_expression_expr", classification: "polymorph", applied: true },
  { kind: "field_pattern", classification: "polymorph", applied: true },
  { kind: "field_pattern_named", classification: "polymorph", applied: true },
  { kind: "field_pattern_shorthand", classification: "polymorph", applied: true },
  { kind: "or_pattern", classification: "polymorph", applied: true },
  { kind: "or_pattern_binary", classification: "polymorph", applied: true },
  { kind: "or_pattern_prefix", classification: "polymorph", applied: true },
  { kind: "range_expression", classification: "polymorph", applied: true },
  { kind: "range_expression_bare", classification: "polymorph", applied: true },
  { kind: "range_expression_binary", classification: "polymorph", applied: true },
  { kind: "range_expression_postfix", classification: "polymorph", applied: true },
  { kind: "range_expression_prefix", classification: "polymorph", applied: true },
  { kind: "range_pattern", classification: "polymorph", applied: true },
  { kind: "range_pattern_left", classification: "polymorph", applied: true },
  { kind: "range_pattern_prefix", classification: "polymorph", applied: true },
  { kind: "visibility_modifier", classification: "polymorph", applied: false },
];

export interface InferredField {
  readonly kind: string;
  readonly fieldName: string;
  readonly targetSymbol: string;
  readonly confidence: 'high' | 'medium' | 'low';
  readonly agreement: number;
  readonly sampleSize: number;
  readonly applied: boolean;
}
export const inferredFields: readonly InferredField[] = [
  { kind: "_non_special_token", fieldName: "mutable_specifier", targetSymbol: "mutable_specifier", confidence: "medium", agreement: 0.909, sampleSize: 11, applied: false },
  { kind: "static_item", fieldName: "mutable_specifier", targetSymbol: "mutable_specifier", confidence: "medium", agreement: 0.909, sampleSize: 11, applied: false },
  { kind: "impl_item", fieldName: "where_clause", targetSymbol: "where_clause", confidence: "medium", agreement: 0.857, sampleSize: 7, applied: false },
  { kind: "struct_item", fieldName: "where_clause", targetSymbol: "where_clause", confidence: "medium", agreement: 0.857, sampleSize: 7, applied: false },
  { kind: "struct_item", fieldName: "where_clause", targetSymbol: "where_clause", confidence: "medium", agreement: 0.857, sampleSize: 7, applied: false },
  { kind: "trait_item", fieldName: "where_clause", targetSymbol: "where_clause", confidence: "medium", agreement: 0.857, sampleSize: 7, applied: false },
  { kind: "type_arguments", fieldName: "bounds", targetSymbol: "trait_bounds", confidence: "high", agreement: 1.000, sampleSize: 5, applied: false },
  { kind: "arguments", fieldName: "attributes", targetSymbol: "attribute_item", confidence: "low", agreement: 0.800, sampleSize: 5, applied: false },
  { kind: "enum_variant_list", fieldName: "attributes", targetSymbol: "attribute_item", confidence: "low", agreement: 0.800, sampleSize: 5, applied: false },
  { kind: "field_declaration_list", fieldName: "attributes", targetSymbol: "attribute_item", confidence: "low", agreement: 0.800, sampleSize: 5, applied: false },
  { kind: "field_initializer", fieldName: "attributes", targetSymbol: "attribute_item", confidence: "low", agreement: 0.800, sampleSize: 5, applied: false },
  { kind: "last_match_arm", fieldName: "attributes", targetSymbol: "attribute_item", confidence: "low", agreement: 0.800, sampleSize: 5, applied: false },
  { kind: "match_arm", fieldName: "attributes", targetSymbol: "attribute_item", confidence: "low", agreement: 0.800, sampleSize: 5, applied: false },
  { kind: "parameters", fieldName: "attributes", targetSymbol: "attribute_item", confidence: "low", agreement: 0.800, sampleSize: 5, applied: false },
  { kind: "type_parameters", fieldName: "attributes", targetSymbol: "attribute_item", confidence: "low", agreement: 0.800, sampleSize: 5, applied: false },
];

export interface RepeatedShape {
  readonly suggestedName: string;
  readonly kinds: readonly string[];
  readonly parents: readonly string[];
  readonly shape: 'supertype' | 'group';
}
export const repeatedShapes: readonly RepeatedShape[] = [
  { suggestedName: "_shared_2", kinds: ["_literal_pattern","_path"], parents: ["_range_pattern_left","_range_pattern_prefix","range_pattern_left","range_pattern_prefix"], shape: "supertype" },
  { suggestedName: "_shared_2", kinds: ["identifier","metavariable"], parents: ["function_item","function_signature_item"], shape: "supertype" },
  { suggestedName: "_type_identifier", kinds: ["_type_identifier","scoped_type_identifier"], parents: ["function_type","struct_pattern"], shape: "supertype" },
  { suggestedName: "_shared_2", kinds: ["_field_identifier","integer_literal"], parents: ["field_expression","field_initializer"], shape: "supertype" },
  { suggestedName: "_shared_3", kinds: ["_path","bracketed_type","generic_type"], parents: ["scoped_identifier","scoped_type_identifier"], shape: "supertype" },
];
