// Auto-generated by @sittir/codegen — do not edit

import type * as T from '../types-internal.js';
import { TSKindId } from '../types.js';
import type { AdmitBound } from '@sittir/types';
import {
	withAccessors,
	describeValue,
	restItems,
	admitAliasContent,
	coerceBooleanKeywordStorage,
	coerceKindEnumStorage,
	coerceMixedEnumStorage,
	numberText,
	orDefault,
	rejectBareText,
	unaffixed
} from '@sittir/common/utils';
import { withMethods } from '../utils.js';

function _assertNonEmpty<T>(arr: readonly T[], label: string): asserts arr is readonly [T, ...(readonly T[])] {
	if (arr.length === 0) {
		throw new Error(`${label}: requires at least one element`);
	}
}

const _leafRe_buildPatternCharacter = /^(?:(?:[^^$\\.*+?()[\]|\r?\n]))$/u;
const _leafRe_buildPosixClassName = /^(?:(?:[a-zA-Z]+))$/u;
const _leafRe_buildClassCharacter = /^(?:(?:[^\\\]-]))$/u;
const _leafRe_buildFlags = /^(?:(?:[a-zA-Z]+))$/u;
const _leafRe_buildZeroOrMore = /^(?:\*(?:\?)?)$/u;
const _leafRe_buildOneOrMore = /^(?:\+(?:\?)?)$/u;
const _leafRe_buildOptional = /^(?:\?(?:\?)?)$/u;
const _leafRe_buildDecimalEscape = /^(?:(?:\\[1-9][0-9]*))$/u;
const _leafRe_buildUnicodeCharacterEscape = /^(?:(?:(?:\\u[0-9a-fA-F]{4})|(?:\\u\{[0-9a-fA-F]{1,6}\})))$/u;
const _leafRe_buildUnicodePropertyValue = /^(?:(?:[a-zA-Z_0-9]+))$/u;
const _leafRe_buildControlEscape = /^(?:(?:(?:\\[bfnrtv0])|(?:\\x[0-9a-fA-F]{2})))$/u;
const _leafRe_buildControlLetterEscape = /^(?:(?:\\c[a-zA-Z]))$/u;
const _leafRe_buildGroupName = /^(?:(?:[A-Za-z_][A-Za-z0-9_]*))$/u;
const _leafRe_buildDecimalDigits = /^(?:(?:\d+))$/u;
const _leafRe_buildCharacterClassEscapeText1 = /^(?:(?:\\[dDsSwW]))$/u;
const _leafRe_buildCharacterClassEscapeText2 = /^(?:(?:\\[pP]))$/u;
export const _slotRe_buildIdentityEscape_content = /^(?:(?:[^kdDsSpPwWbfnrtv0-9]))$/u;

export function buildPattern(value: AdmitBound<T.Alternation | T.Term, T.AdmittedNodes>): T.Pattern.Bound {
	const _content = rejectBareText(value, 'Pattern.content', 'a built Alternation / Term');
	return withMethods(
		withAccessors(
			{
				$type: TSKindId.Pattern as const,
				$source: 2 as const,
				$named: true as const,
				_content,
				$with: {
					content: (value: T.Alternation | T.Term) => buildPattern(value)
				}
			},
			{
				content: () => _content
			}
		)
	) as unknown as T.Pattern.Bound;
}

export function buildAlternation(...children: AdmitBound<T.Term[], T.AdmittedNodes>): T.Alternation.Bound {
	_assertNonEmpty(children, 'alternation.children');
	const _terms = rejectBareText(children, 'Alternation.terms', 'a built Term');
	return withMethods(
		withAccessors(
			{
				$type: TSKindId.Alternation as const,
				$source: 2 as const,
				$named: true as const,
				_terms,
				$with: { terms: (...vs: T.Term[]) => buildAlternation(...restItems('terms', vs)) }
			},
			{
				terms: () => _terms
			}
		)
	) as unknown as T.Alternation.Bound;
}

export function buildTerm(...children: AdmitBound<T.TermGroup[], T.AdmittedNodes>): T.Term.Bound {
	_assertNonEmpty(children, 'term.children');
	const _term_group = rejectBareText(children, 'Term.termGroup', 'a built TermGroup');
	return withMethods(
		withAccessors(
			{
				$type: TSKindId.Term as const,
				$source: 2 as const,
				$named: true as const,
				_term_group,
				$with: { termGroups: (...vs: T.TermGroup[]) => buildTerm(...restItems('termGroups', vs)) }
			},
			{
				termGroups: () => _term_group
			}
		)
	) as unknown as T.Term.Bound;
}

export const buildAnyCharacter: TSKindId.AnyCharacter = TSKindId.AnyCharacter;

export const buildStartAssertion: TSKindId.StartAssertion = TSKindId.StartAssertion;

export const buildEndAssertion: TSKindId.EndAssertion = TSKindId.EndAssertion;

export const buildBoundaryAssertion: TSKindId.BoundaryAssertion = TSKindId.BoundaryAssertion;

export const buildNonBoundaryAssertion: TSKindId.NonBoundaryAssertion = TSKindId.NonBoundaryAssertion;

export function buildLookaroundAssertion(
	value: AdmitBound<T.LookaheadAssertion | T.LookbehindAssertion, T.AdmittedNodes>
): T.LookaroundAssertion.Bound {
	const _content = rejectBareText(
		value,
		'LookaroundAssertion.content',
		'a built LookaheadAssertion / LookbehindAssertion'
	);
	return withMethods(
		withAccessors(
			{
				$type: TSKindId.LookaroundAssertion as const,
				$source: 2 as const,
				$named: true as const,
				_content,
				$with: {
					content: (value: T.LookaheadAssertion | T.LookbehindAssertion) => buildLookaroundAssertion(value)
				}
			},
			{
				content: () => _content
			}
		)
	) as unknown as T.LookaroundAssertion.Bound;
}

export function buildLookaheadAssertion(config: T.LookaheadAssertion.Config): T.LookaheadAssertion.Bound {
	const _content = coerceKindEnumStorage<NonNullable<T.LookaheadAssertion['_content']>>(config.content, [
		['=', TSKindId.Eq] as const,
		['!', TSKindId.Bang] as const
	]);
	const _pattern = rejectBareText(config.pattern, 'LookaheadAssertion.pattern', 'a built Pattern');
	return withMethods(
		withAccessors(
			{
				$type: TSKindId.LookaheadAssertion as const,
				$source: 2 as const,
				$named: true as const,
				_content,
				_pattern,
				$with: {
					content: (value: NonNullable<T.LookaheadAssertion.Config>['content']) =>
						buildLookaheadAssertion({ ...config, content: value }),
					pattern: (value: T.Pattern) => buildLookaheadAssertion({ ...config, pattern: value })
				}
			},
			{
				content: () => _content,
				pattern: () => _pattern
			}
		)
	) as unknown as T.LookaheadAssertion.Bound;
}

export function buildLookbehindAssertion(config: T.LookbehindAssertion.Config): T.LookbehindAssertion.Bound {
	const _content = coerceKindEnumStorage<NonNullable<T.LookbehindAssertion['_content']>>(config.content, [
		['=', TSKindId.Eq] as const,
		['!', TSKindId.Bang] as const
	]);
	const _pattern = rejectBareText(config.pattern, 'LookbehindAssertion.pattern', 'a built Pattern');
	return withMethods(
		withAccessors(
			{
				$type: TSKindId.LookbehindAssertion as const,
				$source: 2 as const,
				$named: true as const,
				_content,
				_pattern,
				$with: {
					content: (value: NonNullable<T.LookbehindAssertion.Config>['content']) =>
						buildLookbehindAssertion({ ...config, content: value }),
					pattern: (value: T.Pattern) => buildLookbehindAssertion({ ...config, pattern: value })
				}
			},
			{
				content: () => _content,
				pattern: () => _pattern
			}
		)
	) as unknown as T.LookbehindAssertion.Bound;
}

export function buildPatternCharacter(text: string): T.PatternCharacter.Bound {
	if (text.length === 0) throw new Error(`pattern_character: text must be non-empty`);
	if (!_leafRe_buildPatternCharacter.test(text))
		throw new Error(`pattern_character: text does not match pattern: ${describeValue(text)}`);
	return withMethods({
		$type: TSKindId.PatternCharacter as const,
		$source: 2 as const,
		$named: true as const,
		$text: text
	});
}

export function buildCharacterClass(): T.EmptyCharacterClass;
export function buildCharacterClass(config?: Partial<T.CharacterClass.Config>): T.CharacterClass.Bound;
export function buildCharacterClass(config: Partial<T.CharacterClass.Config> = {}): T.CharacterClass.Bound {
	const _negation = coerceBooleanKeywordStorage(config.negation);
	const _leading = coerceBooleanKeywordStorage(config.leading);
	const _class_atoms = rejectBareText(
		coerceMixedEnumStorage<NonNullable<T.CharacterClass['_class_atoms']>>(config.classAtoms ?? [], [
			['\\-', TSKindId.BslashDash] as const
		]),
		'CharacterClass.classAtoms',
		'buildClassCharacter(…) / buildControlEscape(…) / buildControlLetterEscape(…)'
	);
	const _trailing = coerceBooleanKeywordStorage(config.trailing);
	return withMethods(
		withAccessors(
			{
				$type: TSKindId.CharacterClass as const,
				$source: 2 as const,
				$named: true as const,
				_negation,
				_leading,
				_class_atoms,
				_trailing,
				$with: {
					negation: (value?: NonNullable<T.CharacterClass.Config>['negation']) =>
						buildCharacterClass({ ...config, negation: value }),
					leading: (value?: NonNullable<T.CharacterClass.Config>['leading']) =>
						buildCharacterClass({ ...config, leading: value }),
					classAtoms: (...values: NonNullable<NonNullable<T.CharacterClass.Config>['classAtoms']>[number][]) =>
						buildCharacterClass({ ...config, classAtoms: restItems('classAtoms', values) }),
					trailing: (value?: NonNullable<T.CharacterClass.Config>['trailing']) =>
						buildCharacterClass({ ...config, trailing: value })
				}
			},
			{
				negation: () => _negation,
				leading: () => _leading,
				classAtoms: () => _class_atoms,
				trailing: () => _trailing
			}
		)
	) as unknown as T.CharacterClass.Bound;
}

export function buildPosixCharacterClass(
	value: AdmitBound<T.PosixClassName, T.AdmittedNodes>
): ReturnType<typeof _buildPosixCharacterClass>;
export function buildPosixCharacterClass(text: string): ReturnType<typeof _buildPosixCharacterClass>;
export function buildPosixCharacterClass(...args: unknown[]) {
	if (args.length === 0 || (args.length === 1 && args[0] === undefined)) {
		return _buildPosixCharacterClass(args[0] as T.PosixClassName);
	}
	const prebuilt =
		args.length === 1 &&
		typeof args[0] === 'object' &&
		args[0] !== null &&
		(args[0] as { $type?: unknown }).$type === (TSKindId.PosixClassName as const);
	return prebuilt
		? _buildPosixCharacterClass(args[0] as T.PosixClassName)
		: _buildPosixCharacterClass((buildPosixClassName as (...a: unknown[]) => unknown)(...args) as T.PosixClassName);
}
function _buildPosixCharacterClass(value: AdmitBound<T.PosixClassName, T.AdmittedNodes>): T.PosixCharacterClass.Bound {
	const _posix_class_name = rejectBareText(value, 'PosixCharacterClass.posixClassName', 'buildPosixClassName(…)');
	return withMethods(
		withAccessors(
			{
				$type: TSKindId.PosixCharacterClass as const,
				$source: 2 as const,
				$named: true as const,
				_posix_class_name,
				$with: {
					posixClassName: (value: T.PosixClassName) => _buildPosixCharacterClass(value)
				}
			},
			{
				posixClassName: () => _posix_class_name
			}
		)
	) as unknown as T.PosixCharacterClass.Bound;
}

export function buildPosixClassName(text: string): T.PosixClassName.Bound {
	if (text.length === 0) throw new Error(`posix_class_name: text must be non-empty`);
	if (!_leafRe_buildPosixClassName.test(text))
		throw new Error(`posix_class_name: text does not match pattern: ${describeValue(text)}`);
	return withMethods({
		$type: TSKindId.PosixClassName as const,
		$source: 2 as const,
		$named: true as const,
		$text: text
	});
}

export function buildClassRange(config: T.ClassRange.Config): T.ClassRange.Bound {
	const _start = rejectBareText(
		coerceMixedEnumStorage<NonNullable<T.ClassRange['_start']>>(config.start, [['-', TSKindId.Dash] as const]),
		'ClassRange.start',
		'buildClassCharacter(…) / buildControlEscape(…)'
	);
	const _end = rejectBareText(
		coerceMixedEnumStorage<NonNullable<T.ClassRange['_end']>>(config.end, [['-', TSKindId.Dash] as const]),
		'ClassRange.end',
		'buildClassCharacter(…) / buildControlEscape(…)'
	);
	return withMethods(
		withAccessors(
			{
				$type: TSKindId.ClassRange as const,
				$source: 2 as const,
				$named: true as const,
				_start,
				_end,
				$with: {
					start: (value: NonNullable<T.ClassRange.Config>['start']) => buildClassRange({ ...config, start: value }),
					end: (value: NonNullable<T.ClassRange.Config>['end']) => buildClassRange({ ...config, end: value })
				}
			},
			{
				start: () => _start,
				end: () => _end
			}
		)
	) as unknown as T.ClassRange.Bound;
}

export function buildClassCharacter(text: string): T.ClassCharacter.Bound {
	if (text.length === 0) throw new Error(`class_character: text must be non-empty`);
	if (!_leafRe_buildClassCharacter.test(text))
		throw new Error(`class_character: text does not match pattern: ${describeValue(text)}`);
	return withMethods({
		$type: TSKindId.ClassCharacter as const,
		$source: 2 as const,
		$named: true as const,
		$text: text
	});
}

export function buildAnonymousCapturingGroup(
	value: AdmitBound<T.Pattern, T.AdmittedNodes>
): ReturnType<typeof _buildAnonymousCapturingGroup>;
export function buildAnonymousCapturingGroup(
	value: AdmitBound<T.Alternation | T.Term, T.AdmittedNodes>
): ReturnType<typeof _buildAnonymousCapturingGroup>;
export function buildAnonymousCapturingGroup(...args: unknown[]) {
	if (args.length === 0 || (args.length === 1 && args[0] === undefined)) {
		return _buildAnonymousCapturingGroup(args[0] as T.Pattern);
	}
	const prebuilt =
		args.length === 1 &&
		typeof args[0] === 'object' &&
		args[0] !== null &&
		(args[0] as { $type?: unknown }).$type === (TSKindId.Pattern as const);
	return prebuilt
		? _buildAnonymousCapturingGroup(args[0] as T.Pattern)
		: _buildAnonymousCapturingGroup((buildPattern as (...a: unknown[]) => unknown)(...args) as T.Pattern);
}
function _buildAnonymousCapturingGroup(value: AdmitBound<T.Pattern, T.AdmittedNodes>): T.AnonymousCapturingGroup.Bound {
	const _pattern = rejectBareText(value, 'AnonymousCapturingGroup.pattern', 'a built Pattern');
	return withMethods(
		withAccessors(
			{
				$type: TSKindId.AnonymousCapturingGroup as const,
				$source: 2 as const,
				$named: true as const,
				_pattern,
				$with: {
					pattern: (value: T.Pattern) => _buildAnonymousCapturingGroup(value)
				}
			},
			{
				pattern: () => _pattern
			}
		)
	) as unknown as T.AnonymousCapturingGroup.Bound;
}

export function buildNamedCapturingGroup(config: T.NamedCapturingGroup.Config): T.NamedCapturingGroup.Bound {
	const _content = coerceKindEnumStorage<NonNullable<T.NamedCapturingGroup['_content']>>(config.content, [
		['(?<', TSKindId.LparenQmarkLt] as const,
		['(?P<', TSKindId.LparenQmarkPLt] as const
	]);
	const _group_name = rejectBareText(config.groupName, 'NamedCapturingGroup.groupName', 'buildGroupName(…)');
	const _pattern = rejectBareText(config.pattern, 'NamedCapturingGroup.pattern', 'a built Pattern');
	return withMethods(
		withAccessors(
			{
				$type: TSKindId.NamedCapturingGroup as const,
				$source: 2 as const,
				$named: true as const,
				_content,
				_group_name,
				_pattern,
				$with: {
					content: (value: NonNullable<T.NamedCapturingGroup.Config>['content']) =>
						buildNamedCapturingGroup({ ...config, content: value }),
					groupName: (value: T.GroupName) => buildNamedCapturingGroup({ ...config, groupName: value }),
					pattern: (value: T.Pattern) => buildNamedCapturingGroup({ ...config, pattern: value })
				}
			},
			{
				content: () => _content,
				groupName: () => _group_name,
				pattern: () => _pattern
			}
		)
	) as unknown as T.NamedCapturingGroup.Bound;
}

export function buildNonCapturingGroup(
	value: AdmitBound<T.Pattern, T.AdmittedNodes>
): ReturnType<typeof _buildNonCapturingGroup>;
export function buildNonCapturingGroup(
	value: AdmitBound<T.Alternation | T.Term, T.AdmittedNodes>
): ReturnType<typeof _buildNonCapturingGroup>;
export function buildNonCapturingGroup(...args: unknown[]) {
	if (args.length === 0 || (args.length === 1 && args[0] === undefined)) {
		return _buildNonCapturingGroup(args[0] as T.Pattern);
	}
	const prebuilt =
		args.length === 1 &&
		typeof args[0] === 'object' &&
		args[0] !== null &&
		(args[0] as { $type?: unknown }).$type === (TSKindId.Pattern as const);
	return prebuilt
		? _buildNonCapturingGroup(args[0] as T.Pattern)
		: _buildNonCapturingGroup((buildPattern as (...a: unknown[]) => unknown)(...args) as T.Pattern);
}
function _buildNonCapturingGroup(value: AdmitBound<T.Pattern, T.AdmittedNodes>): T.NonCapturingGroup.Bound {
	const _pattern = rejectBareText(value, 'NonCapturingGroup.pattern', 'a built Pattern');
	return withMethods(
		withAccessors(
			{
				$type: TSKindId.NonCapturingGroup as const,
				$source: 2 as const,
				$named: true as const,
				_pattern,
				$with: {
					pattern: (value: T.Pattern) => _buildNonCapturingGroup(value)
				}
			},
			{
				pattern: () => _pattern
			}
		)
	) as unknown as T.NonCapturingGroup.Bound;
}

export function buildFlags(text: string): T.Flags.Bound {
	if (text.length === 0) throw new Error(`flags: text must be non-empty`);
	if (!_leafRe_buildFlags.test(text)) throw new Error(`flags: text does not match pattern: ${describeValue(text)}`);
	return withMethods({
		$type: TSKindId.Flags as const,
		$source: 2 as const,
		$named: true as const,
		$text: text
	});
}

export function buildZeroOrMore(text: string): T.ZeroOrMore.Bound {
	if (text.length === 0) throw new Error(`zero_or_more: text must be non-empty`);
	if (!_leafRe_buildZeroOrMore.test(text))
		throw new Error(`zero_or_more: text does not match pattern: ${describeValue(text)}`);
	return withMethods({
		$type: TSKindId.ZeroOrMore as const,
		$source: 2 as const,
		$named: true as const,
		$text: text
	});
}

export function buildOneOrMore(text: string): T.OneOrMore.Bound {
	if (text.length === 0) throw new Error(`one_or_more: text must be non-empty`);
	if (!_leafRe_buildOneOrMore.test(text))
		throw new Error(`one_or_more: text does not match pattern: ${describeValue(text)}`);
	return withMethods({
		$type: TSKindId.OneOrMore as const,
		$source: 2 as const,
		$named: true as const,
		$text: text
	});
}

export function buildOptional(text: string): T.Optional.Bound {
	if (text.length === 0) throw new Error(`optional: text must be non-empty`);
	if (!_leafRe_buildOptional.test(text))
		throw new Error(`optional: text does not match pattern: ${describeValue(text)}`);
	return withMethods({
		$type: TSKindId.Optional as const,
		$source: 2 as const,
		$named: true as const,
		$text: text
	});
}

export function buildCountQuantifier(config: T.CountQuantifier.Config): T.CountQuantifier.Bound {
	const _content = rejectBareText(config.content, 'CountQuantifier.content', 'buildDecimalDigits(…)');
	const _lazy = coerceBooleanKeywordStorage(config.lazy);
	return withMethods(
		withAccessors(
			{
				$type: TSKindId.CountQuantifier as const,
				$source: 2 as const,
				$named: true as const,
				_content,
				_lazy,
				$with: {
					content: (value: T.CountQuantifierArm | T.DecimalDigits) =>
						buildCountQuantifier({ ...config, content: value }),
					lazy: (value?: NonNullable<T.CountQuantifier.Config>['lazy']) =>
						buildCountQuantifier({ ...config, lazy: value })
				}
			},
			{
				content: () => _content,
				lazy: () => _lazy
			}
		)
	) as unknown as T.CountQuantifier.Bound;
}

export function buildBackreferenceEscape(
	value: AdmitBound<T.GroupName, T.AdmittedNodes>
): ReturnType<typeof _buildBackreferenceEscape>;
export function buildBackreferenceEscape(text: string): ReturnType<typeof _buildBackreferenceEscape>;
export function buildBackreferenceEscape(...args: unknown[]) {
	if (args.length === 0 || (args.length === 1 && args[0] === undefined)) {
		return _buildBackreferenceEscape(args[0] as T.GroupName);
	}
	const prebuilt =
		args.length === 1 &&
		typeof args[0] === 'object' &&
		args[0] !== null &&
		(args[0] as { $type?: unknown }).$type === (TSKindId.GroupName as const);
	return prebuilt
		? _buildBackreferenceEscape(args[0] as T.GroupName)
		: _buildBackreferenceEscape((buildGroupName as (...a: unknown[]) => unknown)(...args) as T.GroupName);
}
function _buildBackreferenceEscape(value: AdmitBound<T.GroupName, T.AdmittedNodes>): T.BackreferenceEscape.Bound {
	const _group_name = rejectBareText(value, 'BackreferenceEscape.groupName', 'buildGroupName(…)');
	return withMethods(
		withAccessors(
			{
				$type: TSKindId.BackreferenceEscape as const,
				$source: 2 as const,
				$named: true as const,
				_group_name,
				$with: {
					groupName: (value: T.GroupName) => _buildBackreferenceEscape(value)
				}
			},
			{
				groupName: () => _group_name
			}
		)
	) as unknown as T.BackreferenceEscape.Bound;
}

export function buildNamedGroupBackreference(
	value: AdmitBound<T.GroupName, T.AdmittedNodes>
): ReturnType<typeof _buildNamedGroupBackreference>;
export function buildNamedGroupBackreference(text: string): ReturnType<typeof _buildNamedGroupBackreference>;
export function buildNamedGroupBackreference(...args: unknown[]) {
	if (args.length === 0 || (args.length === 1 && args[0] === undefined)) {
		return _buildNamedGroupBackreference(args[0] as T.GroupName);
	}
	const prebuilt =
		args.length === 1 &&
		typeof args[0] === 'object' &&
		args[0] !== null &&
		(args[0] as { $type?: unknown }).$type === (TSKindId.GroupName as const);
	return prebuilt
		? _buildNamedGroupBackreference(args[0] as T.GroupName)
		: _buildNamedGroupBackreference((buildGroupName as (...a: unknown[]) => unknown)(...args) as T.GroupName);
}
function _buildNamedGroupBackreference(
	value: AdmitBound<T.GroupName, T.AdmittedNodes>
): T.NamedGroupBackreference.Bound {
	const _group_name = rejectBareText(value, 'NamedGroupBackreference.groupName', 'buildGroupName(…)');
	return withMethods(
		withAccessors(
			{
				$type: TSKindId.NamedGroupBackreference as const,
				$source: 2 as const,
				$named: true as const,
				_group_name,
				$with: {
					groupName: (value: T.GroupName) => _buildNamedGroupBackreference(value)
				}
			},
			{
				groupName: () => _group_name
			}
		)
	) as unknown as T.NamedGroupBackreference.Bound;
}

export function buildDecimalEscape(text: string): T.DecimalEscape.Bound {
	if (text.length === 0) throw new Error(`decimal_escape: text must be non-empty`);
	if (!_leafRe_buildDecimalEscape.test(text))
		throw new Error(`decimal_escape: text does not match pattern: ${describeValue(text)}`);
	return withMethods({
		$type: TSKindId.DecimalEscape as const,
		$source: 2 as const,
		$named: true as const,
		$text: text
	});
}

export function buildCharacterClassEscape(
	value: AdmitBound<T.CharacterClassEscapeText1 | T.CharacterClassEscapeArm | T.UnicodeCharacterEscape, T.AdmittedNodes>
): T.CharacterClassEscape.Bound {
	const _content = rejectBareText(
		value,
		'CharacterClassEscape.content',
		'buildCharacterClassEscapeText1(…) / buildUnicodeCharacterEscape(…)'
	);
	return withMethods(
		withAccessors(
			{
				$type: TSKindId.CharacterClassEscape as const,
				$source: 2 as const,
				$named: true as const,
				_content,
				$with: {
					content: (value: T.CharacterClassEscapeText1 | T.CharacterClassEscapeArm | T.UnicodeCharacterEscape) =>
						buildCharacterClassEscape(value)
				}
			},
			{
				content: () => _content
			}
		)
	) as unknown as T.CharacterClassEscape.Bound;
}

export function buildUnicodeCharacterEscape(text: string): T.UnicodeCharacterEscape.Bound {
	if (text.length === 0) throw new Error(`unicode_character_escape: text must be non-empty`);
	if (!_leafRe_buildUnicodeCharacterEscape.test(text))
		throw new Error(`unicode_character_escape: text does not match pattern: ${describeValue(text)}`);
	return withMethods({
		$type: TSKindId.UnicodeCharacterEscape as const,
		$source: 2 as const,
		$named: true as const,
		$text: text
	});
}

export function buildUnicodePropertyValueExpression(
	config: T.UnicodePropertyValueExpression.Config
): T.UnicodePropertyValueExpression.Bound {
	const _unicode_property_value_expression_group = rejectBareText(
		config.unicodePropertyValueExpressionGroup,
		'UnicodePropertyValueExpression.unicodePropertyValueExpressionGroup',
		'a built UnicodePropertyValueExpressionGroup'
	);
	const _unicode_property_value = rejectBareText(
		config.unicodePropertyValue,
		'UnicodePropertyValueExpression.unicodePropertyValue',
		'buildUnicodePropertyValue(…)'
	);
	return withMethods(
		withAccessors(
			{
				$type: TSKindId.UnicodePropertyValueExpression as const,
				$source: 2 as const,
				$named: true as const,
				_unicode_property_value_expression_group,
				_unicode_property_value,
				$with: {
					unicodePropertyValueExpressionGroup: (value?: T.UnicodePropertyValueExpressionGroup) =>
						buildUnicodePropertyValueExpression({ ...config, unicodePropertyValueExpressionGroup: value }),
					unicodePropertyValue: (value: T.UnicodePropertyValue) =>
						buildUnicodePropertyValueExpression({ ...config, unicodePropertyValue: value })
				}
			},
			{
				unicodePropertyValueExpressionGroup: () => _unicode_property_value_expression_group,
				unicodePropertyValue: () => _unicode_property_value
			}
		)
	) as unknown as T.UnicodePropertyValueExpression.Bound;
}

export function buildUnicodePropertyValue(text: string): T.UnicodePropertyValue.Bound {
	if (text.length === 0) throw new Error(`unicode_property_value: text must be non-empty`);
	if (!_leafRe_buildUnicodePropertyValue.test(text))
		throw new Error(`unicode_property_value: text does not match pattern: ${describeValue(text)}`);
	return withMethods({
		$type: TSKindId.UnicodePropertyValue as const,
		$source: 2 as const,
		$named: true as const,
		$text: text
	});
}

export function buildControlEscape(text: string): T.ControlEscape.Bound {
	if (text.length === 0) throw new Error(`control_escape: text must be non-empty`);
	if (!_leafRe_buildControlEscape.test(text))
		throw new Error(`control_escape: text does not match pattern: ${describeValue(text)}`);
	return withMethods({
		$type: TSKindId.ControlEscape as const,
		$source: 2 as const,
		$named: true as const,
		$text: text
	});
}

export function buildControlLetterEscape(text: string): T.ControlLetterEscape.Bound {
	if (text.length === 0) throw new Error(`control_letter_escape: text must be non-empty`);
	if (!_leafRe_buildControlLetterEscape.test(text))
		throw new Error(`control_letter_escape: text does not match pattern: ${describeValue(text)}`);
	return withMethods({
		$type: TSKindId.ControlLetterEscape as const,
		$source: 2 as const,
		$named: true as const,
		$text: text
	});
}

export function buildIdentityEscape(content: string, affix?: true): T.IdentityEscape.Bound;
export function buildIdentityEscape(text: `\\${string}`, affix: false): T.IdentityEscape.Bound;
export function buildIdentityEscape(input: string, affix: boolean = true): T.IdentityEscape.Bound {
	const value = affix ? input : unaffixed(String(input), '\\', '', 'identity_escape');
	const _content = value;
	if (!_slotRe_buildIdentityEscape_content.test(_content))
		throw new Error(`identity_escape.content: text does not match pattern: ${describeValue(_content)}`);
	return withMethods(
		withAccessors(
			{
				$type: TSKindId.IdentityEscape as const,
				$source: 2 as const,
				$named: true as const,
				_content,
				$with: {
					content: (value: string) => buildIdentityEscape(value)
				}
			},
			{
				content: () => _content
			}
		)
	) as unknown as T.IdentityEscape.Bound;
}

export function buildGroupName(text: string): T.GroupName.Bound {
	if (text.length === 0) throw new Error(`group_name: text must be non-empty`);
	if (!_leafRe_buildGroupName.test(text))
		throw new Error(`group_name: text does not match pattern: ${describeValue(text)}`);
	return withMethods({
		$type: TSKindId.GroupName as const,
		$source: 2 as const,
		$named: true as const,
		$text: text
	});
}

export function buildDecimalDigits(text: string | number | bigint): T.DecimalDigits.Bound {
	text = numberText(10, '', text);
	if (text.length === 0) throw new Error(`decimal_digits: text must be non-empty`);
	if (!_leafRe_buildDecimalDigits.test(text))
		throw new Error(`decimal_digits: text does not match pattern: ${describeValue(text)}`);
	return withMethods({
		$type: TSKindId.DecimalDigits as const,
		$source: 2 as const,
		$named: true as const,
		$text: text
	});
}

export function buildTermGroup(config: T.TermGroup.Config): T.TermGroup.Bound {
	const _content = rejectBareText(
		coerceMixedEnumStorage<NonNullable<T.TermGroup['_content']>>(config.content, [
			['^', TSKindId.StartAssertion] as const,
			['$', TSKindId.EndAssertion] as const,
			['\\b', TSKindId.BoundaryAssertion] as const,
			['\\B', TSKindId.NonBoundaryAssertion] as const,
			['.', TSKindId.AnyCharacter] as const
		]),
		'TermGroup.content',
		'buildPatternCharacter(…) / buildDecimalEscape(…) / buildControlEscape(…) / buildControlLetterEscape(…)'
	);
	const _quantifier = rejectBareText(
		config.quantifier,
		'TermGroup.quantifier',
		'buildZeroOrMore(…) / buildOneOrMore(…) / buildOptional(…)'
	);
	return withMethods(
		withAccessors(
			{
				$type: TSKindId.TermGroup as const,
				$source: 2 as const,
				$named: true as const,
				_content,
				_quantifier,
				$with: {
					content: (value: NonNullable<T.TermGroup.Config>['content']) => buildTermGroup({ ...config, content: value }),
					quantifier: (value?: T.ZeroOrMore | T.OneOrMore | T.Optional | T.CountQuantifier) =>
						buildTermGroup({ ...config, quantifier: value })
				}
			},
			{
				content: () => _content,
				quantifier: () => _quantifier
			}
		)
	) as unknown as T.TermGroup.Bound;
}

export function buildCountQuantifierGroup(
	value?: AdmitBound<T.DecimalDigits, T.AdmittedNodes>
): ReturnType<typeof _buildCountQuantifierGroup>;
export function buildCountQuantifierGroup(
	text: string | number | bigint
): ReturnType<typeof _buildCountQuantifierGroup>;
export function buildCountQuantifierGroup(...args: unknown[]) {
	if (args.length === 0 || (args.length === 1 && args[0] === undefined)) {
		return _buildCountQuantifierGroup(args[0] as T.DecimalDigits);
	}
	const prebuilt =
		args.length === 1 &&
		typeof args[0] === 'object' &&
		args[0] !== null &&
		(args[0] as { $type?: unknown }).$type === (TSKindId.DecimalDigits as const);
	return prebuilt
		? _buildCountQuantifierGroup(args[0] as T.DecimalDigits)
		: _buildCountQuantifierGroup((buildDecimalDigits as (...a: unknown[]) => unknown)(...args) as T.DecimalDigits);
}
function _buildCountQuantifierGroup(
	value?: AdmitBound<T.DecimalDigits, T.AdmittedNodes>
): T.CountQuantifierGroup.Bound {
	const _decimal_digits = rejectBareText(value, 'CountQuantifierGroup.decimalDigits', 'buildDecimalDigits(…)');
	return withMethods(
		withAccessors(
			{
				$type: TSKindId.CountQuantifierGroup as const,
				$source: 2 as const,
				$named: true as const,
				_decimal_digits,
				$with: {
					decimalDigits: (value?: T.DecimalDigits) => _buildCountQuantifierGroup(value)
				}
			},
			{
				decimalDigits: () => _decimal_digits
			}
		)
	) as unknown as T.CountQuantifierGroup.Bound;
}

export function buildCountQuantifierArm(config: T.CountQuantifierArm.Config): T.CountQuantifierArm.Bound {
	const _decimal_digits = rejectBareText(
		config.decimalDigits,
		'CountQuantifierArm.decimalDigits',
		'buildDecimalDigits(…)'
	);
	const _count_quantifier_group = rejectBareText(
		config.countQuantifierGroup,
		'CountQuantifierArm.countQuantifierGroup',
		'a built CountQuantifierGroup'
	);
	return withMethods(
		withAccessors(
			{
				$type: TSKindId.CountQuantifierArm as const,
				$source: 2 as const,
				$named: true as const,
				_decimal_digits,
				_count_quantifier_group,
				$with: {
					decimalDigits: (value: T.DecimalDigits) => buildCountQuantifierArm({ ...config, decimalDigits: value }),
					countQuantifierGroup: (value?: T.CountQuantifierGroup) =>
						buildCountQuantifierArm({ ...config, countQuantifierGroup: value })
				}
			},
			{
				decimalDigits: () => _decimal_digits,
				countQuantifierGroup: () => _count_quantifier_group
			}
		)
	) as unknown as T.CountQuantifierArm.Bound;
}

export function buildCharacterClassEscapeArm(
	config: T.CharacterClassEscapeArm.Config
): T.CharacterClassEscapeArm.Bound {
	const _character_class_escape_text2 = rejectBareText(
		config.characterClassEscapeText2,
		'CharacterClassEscapeArm.characterClassEscapeText2',
		'buildCharacterClassEscapeText2(…)'
	);
	const _unicode_property_value_expression = rejectBareText(
		config.unicodePropertyValueExpression,
		'CharacterClassEscapeArm.unicodePropertyValueExpression',
		'a built UnicodePropertyValueExpression'
	);
	return withMethods(
		withAccessors(
			{
				$type: TSKindId.CharacterClassEscapeArm as const,
				$source: 2 as const,
				$named: true as const,
				_character_class_escape_text2,
				_unicode_property_value_expression,
				$with: {
					characterClassEscapeText2: (value: T.CharacterClassEscapeText2) =>
						buildCharacterClassEscapeArm({ ...config, characterClassEscapeText2: value }),
					unicodePropertyValueExpression: (value: T.UnicodePropertyValueExpression) =>
						buildCharacterClassEscapeArm({ ...config, unicodePropertyValueExpression: value })
				}
			},
			{
				characterClassEscapeText2: () => _character_class_escape_text2,
				unicodePropertyValueExpression: () => _unicode_property_value_expression
			}
		)
	) as unknown as T.CharacterClassEscapeArm.Bound;
}

export function buildUnicodePropertyValueExpressionGroup(
	value: AdmitBound<T.UnicodePropertyName | T.UnicodePropertyName.Types, T.AdmittedNodes>
): ReturnType<typeof _buildUnicodePropertyValueExpressionGroup>;
export function buildUnicodePropertyValueExpressionGroup(
	value: AdmitBound<T.UnicodePropertyValue, T.AdmittedNodes>
): ReturnType<typeof _buildUnicodePropertyValueExpressionGroup>;
export function buildUnicodePropertyValueExpressionGroup(...args: unknown[]) {
	if (args.length === 0 || (args.length === 1 && args[0] === undefined)) {
		return _buildUnicodePropertyValueExpressionGroup(args[0] as T.UnicodePropertyName | T.UnicodePropertyName.Types);
	}
	const prebuilt =
		args.length === 1 &&
		typeof args[0] === 'object' &&
		args[0] !== null &&
		(args[0] as { $type?: unknown }).$type === (TSKindId.UnicodePropertyName as const);
	return prebuilt
		? _buildUnicodePropertyValueExpressionGroup(args[0] as T.UnicodePropertyName | T.UnicodePropertyName.Types)
		: _buildUnicodePropertyValueExpressionGroup(
				(buildUnicodePropertyName as (...a: unknown[]) => unknown)(...args) as
					| T.UnicodePropertyName
					| T.UnicodePropertyName.Types
			);
}
function _buildUnicodePropertyValueExpressionGroup(
	value: AdmitBound<T.UnicodePropertyName | T.UnicodePropertyName.Types, T.AdmittedNodes>
): T.UnicodePropertyValueExpressionGroup.Bound {
	const _unicode_property_name = admitAliasContent<
		NonNullable<T.UnicodePropertyValueExpressionGroup['_unicode_property_name']>
	>(rejectBareText(value, 'UnicodePropertyValueExpressionGroup.unicodePropertyName', 'a built UnicodePropertyName'), [
		[[35], (v: unknown) => buildUnicodePropertyName(v as never)]
	]);
	return withMethods(
		withAccessors(
			{
				$type: TSKindId.UnicodePropertyValueExpressionGroup as const,
				$source: 2 as const,
				$named: true as const,
				_unicode_property_name,
				$with: {
					unicodePropertyName: (value: T.UnicodePropertyName | T.UnicodePropertyName.Types) =>
						_buildUnicodePropertyValueExpressionGroup(value)
				}
			},
			{
				unicodePropertyName: () => _unicode_property_name
			}
		)
	) as unknown as T.UnicodePropertyValueExpressionGroup.Bound;
}

export function buildCharacterClassEscapeText1(text: string): T.CharacterClassEscapeText1.Bound {
	if (text.length === 0) throw new Error(`character_class_escape_text1: text must be non-empty`);
	if (!_leafRe_buildCharacterClassEscapeText1.test(text))
		throw new Error(`character_class_escape_text1: text does not match pattern: ${describeValue(text)}`);
	return withMethods({
		$type: TSKindId.CharacterClassEscapeText1 as const,
		$source: 2 as const,
		$named: true as const,
		$text: text
	});
}

export function buildCharacterClassEscapeText2(text: string): T.CharacterClassEscapeText2.Bound {
	if (text.length === 0) throw new Error(`character_class_escape_text2: text must be non-empty`);
	if (!_leafRe_buildCharacterClassEscapeText2.test(text))
		throw new Error(`character_class_escape_text2: text does not match pattern: ${describeValue(text)}`);
	return withMethods({
		$type: TSKindId.CharacterClassEscapeText2 as const,
		$source: 2 as const,
		$named: true as const,
		$text: text
	});
}

export const buildNegation: TSKindId.Negation = TSKindId.Negation;

export function buildInlineFlagsGroupEnable(config: T.InlineFlagsGroupEnable.Config): T.InlineFlagsGroupEnable.Bound {
	const _enabled = rejectBareText(config.enabled, 'InlineFlagsGroupEnable.enabled', 'buildFlags(…)');
	const _pattern = rejectBareText(config.pattern, 'InlineFlagsGroupEnable.pattern', 'a built Pattern');
	return withMethods(
		withAccessors(
			{
				$type: TSKindId.InlineFlagsGroupEnable as const,
				$source: 2 as const,
				$named: true as const,
				_enabled,
				_pattern,
				$with: {
					enabled: (value: T.Flags) => buildInlineFlagsGroupEnable({ ...config, enabled: value }),
					pattern: (value?: T.Pattern) => buildInlineFlagsGroupEnable({ ...config, pattern: value })
				}
			},
			{
				enabled: () => _enabled,
				pattern: () => _pattern
			}
		)
	) as unknown as T.InlineFlagsGroupEnable.Bound;
}

export function buildInlineFlagsGroupToggle(config: T.InlineFlagsGroupToggle.Config): T.InlineFlagsGroupToggle.Bound {
	const _enabled = rejectBareText(config.enabled, 'InlineFlagsGroupToggle.enabled', 'buildFlags(…)');
	const _disabled = rejectBareText(config.disabled, 'InlineFlagsGroupToggle.disabled', 'buildFlags(…)');
	const _pattern = rejectBareText(config.pattern, 'InlineFlagsGroupToggle.pattern', 'a built Pattern');
	return withMethods(
		withAccessors(
			{
				$type: TSKindId.InlineFlagsGroupToggle as const,
				$source: 2 as const,
				$named: true as const,
				_enabled,
				_disabled,
				_pattern,
				$with: {
					enabled: (value: T.Flags) => buildInlineFlagsGroupToggle({ ...config, enabled: value }),
					disabled: (value: T.Flags) => buildInlineFlagsGroupToggle({ ...config, disabled: value }),
					pattern: (value?: T.Pattern) => buildInlineFlagsGroupToggle({ ...config, pattern: value })
				}
			},
			{
				enabled: () => _enabled,
				disabled: () => _disabled,
				pattern: () => _pattern
			}
		)
	) as unknown as T.InlineFlagsGroupToggle.Bound;
}

export function buildInlineFlagsGroupDisable(
	config: T.InlineFlagsGroupDisable.Config
): T.InlineFlagsGroupDisable.Bound {
	const _disabled = rejectBareText(config.disabled, 'InlineFlagsGroupDisable.disabled', 'buildFlags(…)');
	const _pattern = rejectBareText(config.pattern, 'InlineFlagsGroupDisable.pattern', 'a built Pattern');
	return withMethods(
		withAccessors(
			{
				$type: TSKindId.InlineFlagsGroupDisable as const,
				$source: 2 as const,
				$named: true as const,
				_disabled,
				_pattern,
				$with: {
					disabled: (value: T.Flags) => buildInlineFlagsGroupDisable({ ...config, disabled: value }),
					pattern: (value?: T.Pattern) => buildInlineFlagsGroupDisable({ ...config, pattern: value })
				}
			},
			{
				disabled: () => _disabled,
				pattern: () => _pattern
			}
		)
	) as unknown as T.InlineFlagsGroupDisable.Bound;
}

export const buildTight: TSKindId.Tight = TSKindId.Tight;

export const buildNewline: TSKindId.Newline = TSKindId.Newline;

export const buildBlankline: TSKindId.Blankline = TSKindId.Blankline;

export const buildDoubleBlankline: TSKindId.DoubleBlankline = TSKindId.DoubleBlankline;

export function buildLazy(value?: AdmitBound<TSKindId.Qmark, T.AdmittedNodes>): T.Lazy.Bound {
	const _content = coerceKindEnumStorage<NonNullable<T.Lazy['_content']>>(
		orDefault(value, () => TSKindId.Qmark as const),
		[['?', TSKindId.Qmark] as const]
	);
	return withMethods(
		withAccessors(
			{
				$type: TSKindId.Lazy as const,
				$source: 2 as const,
				$named: true as const,
				_content,
				$with: {
					content: (value: NonNullable<TSKindId.Qmark>) => buildLazy(value)
				}
			},
			{
				content: () => _content
			}
		)
	) as unknown as T.Lazy.Bound;
}

export function buildUnicodePropertyName(
	value: AdmitBound<T.UnicodePropertyValue, T.AdmittedNodes>
): T.UnicodePropertyName.Bound {
	const _content = rejectBareText(value, 'UnicodePropertyName.content', 'buildUnicodePropertyValue(…)');
	return withMethods(
		withAccessors(
			{
				$type: TSKindId.UnicodePropertyName as const,
				$source: 2 as const,
				$named: true as const,
				_content,
				$with: {
					content: (value: T.UnicodePropertyValue) => buildUnicodePropertyName(value)
				}
			},
			{
				content: () => _content
			}
		)
	) as unknown as T.UnicodePropertyName.Bound;
}

export type FluentKindMap = {
	pattern: T.Pattern.Bound;
	alternation: T.Alternation.Bound;
	term: T.Term.Bound;
	any_character: T.AnyCharacter;
	start_assertion: T.StartAssertion;
	end_assertion: T.EndAssertion;
	boundary_assertion: T.BoundaryAssertion;
	non_boundary_assertion: T.NonBoundaryAssertion;
	lookaround_assertion: T.LookaroundAssertion.Bound;
	lookahead_assertion: T.LookaheadAssertion.Bound;
	lookbehind_assertion: T.LookbehindAssertion.Bound;
	pattern_character: T.PatternCharacter;
	character_class: T.CharacterClass.Bound;
	posix_character_class: T.PosixCharacterClass.Bound;
	posix_class_name: T.PosixClassName;
	class_range: T.ClassRange.Bound;
	class_character: T.ClassCharacter;
	anonymous_capturing_group: T.AnonymousCapturingGroup.Bound;
	named_capturing_group: T.NamedCapturingGroup.Bound;
	non_capturing_group: T.NonCapturingGroup.Bound;
	flags: T.Flags;
	zero_or_more: T.ZeroOrMore;
	one_or_more: T.OneOrMore;
	optional: T.Optional;
	count_quantifier: T.CountQuantifier.Bound;
	backreference_escape: T.BackreferenceEscape.Bound;
	named_group_backreference: T.NamedGroupBackreference.Bound;
	decimal_escape: T.DecimalEscape;
	character_class_escape: T.CharacterClassEscape.Bound;
	unicode_character_escape: T.UnicodeCharacterEscape;
	unicode_property_value_expression: T.UnicodePropertyValueExpression.Bound;
	unicode_property_value: T.UnicodePropertyValue;
	control_escape: T.ControlEscape;
	control_letter_escape: T.ControlLetterEscape;
	identity_escape: T.IdentityEscape.Bound;
	group_name: T.GroupName;
	decimal_digits: T.DecimalDigits;
	term_group: T.TermGroup.Bound;
	count_quantifier_group: T.CountQuantifierGroup.Bound;
	count_quantifier_arm: T.CountQuantifierArm.Bound;
	character_class_escape_arm: T.CharacterClassEscapeArm.Bound;
	unicode_property_value_expression_group: T.UnicodePropertyValueExpressionGroup.Bound;
	character_class_escape_text1: T.CharacterClassEscapeText1;
	character_class_escape_text2: T.CharacterClassEscapeText2;
	negation: T.Negation;
	inline_flags_group_enable: T.InlineFlagsGroupEnable.Bound;
	inline_flags_group_toggle: T.InlineFlagsGroupToggle.Bound;
	inline_flags_group_disable: T.InlineFlagsGroupDisable.Bound;
	_tight: T.Tight;
	_newline: T.Newline;
	_blankline: T.Blankline;
	_double_blankline: T.DoubleBlankline;
	lazy: T.Lazy.Bound;
	unicode_property_name: T.UnicodePropertyName.Bound;
};

export const _factoryMap = {
	pattern: buildPattern,
	alternation: buildAlternation,
	term: buildTerm,
	any_character: buildAnyCharacter,
	start_assertion: buildStartAssertion,
	end_assertion: buildEndAssertion,
	boundary_assertion: buildBoundaryAssertion,
	non_boundary_assertion: buildNonBoundaryAssertion,
	lookaround_assertion: buildLookaroundAssertion,
	lookahead_assertion: buildLookaheadAssertion,
	lookbehind_assertion: buildLookbehindAssertion,
	pattern_character: buildPatternCharacter,
	character_class: buildCharacterClass,
	posix_character_class: buildPosixCharacterClass,
	posix_class_name: buildPosixClassName,
	class_range: buildClassRange,
	class_character: buildClassCharacter,
	anonymous_capturing_group: buildAnonymousCapturingGroup,
	named_capturing_group: buildNamedCapturingGroup,
	non_capturing_group: buildNonCapturingGroup,
	flags: buildFlags,
	zero_or_more: buildZeroOrMore,
	one_or_more: buildOneOrMore,
	optional: buildOptional,
	count_quantifier: buildCountQuantifier,
	backreference_escape: buildBackreferenceEscape,
	named_group_backreference: buildNamedGroupBackreference,
	decimal_escape: buildDecimalEscape,
	character_class_escape: buildCharacterClassEscape,
	unicode_character_escape: buildUnicodeCharacterEscape,
	unicode_property_value_expression: buildUnicodePropertyValueExpression,
	unicode_property_value: buildUnicodePropertyValue,
	control_escape: buildControlEscape,
	control_letter_escape: buildControlLetterEscape,
	identity_escape: buildIdentityEscape,
	group_name: buildGroupName,
	decimal_digits: buildDecimalDigits,
	term_group: buildTermGroup,
	count_quantifier_group: buildCountQuantifierGroup,
	count_quantifier_arm: buildCountQuantifierArm,
	character_class_escape_arm: buildCharacterClassEscapeArm,
	unicode_property_value_expression_group: buildUnicodePropertyValueExpressionGroup,
	character_class_escape_text1: buildCharacterClassEscapeText1,
	character_class_escape_text2: buildCharacterClassEscapeText2,
	negation: buildNegation,
	inline_flags_group_enable: buildInlineFlagsGroupEnable,
	inline_flags_group_toggle: buildInlineFlagsGroupToggle,
	inline_flags_group_disable: buildInlineFlagsGroupDisable,
	_tight: buildTight,
	_newline: buildNewline,
	_blankline: buildBlankline,
	_double_blankline: buildDoubleBlankline,
	lazy: buildLazy,
	unicode_property_name: buildUnicodePropertyName
} as const;
export type _FactoryMap = typeof _factoryMap;
