# Extension Workflows Configuration
# Uncomment workflows you want to enable
# Comment out a line to disable that workflow extension

# Extension Workflows

baseline
bugfix
cleanup
deprecate
enhance
hotfix
incorporate
modify
phasestoissues
refactor
review
