import type {
	AbstractClasses,
	Accessors,
	AlgebraicDataTypes,
	AmbientDeclarations,
	ArbitraryPrecisionIntegers,
	AssociatedTypes,
	AsyncAwait,
	AsyncBlocks,
	Attributes,
	BoundedQuantification,
	ByteStrings,
	Characters,
	CoerciveEquality,
	CompileTimeEvaluation,
	ComplexNumbers,
	Comprehensions,
	ComputedKeys,
	ConditionalExpressions,
	ConstGenerics,
	Coroutines,
	CountedLoops,
	Decorators,
	DefaultArguments,
	Destructuring,
	Encapsulation,
	Enumerations,
	ErrorPropagation,
	Exceptions,
	ExplicitOverrides,
	ForeignFunctionInterface,
	Generators,
	HigherRankPolymorphism,
	InterfaceConformance,
	Interfaces,
	LabeledControlFlow,
	Lifetimes,
	ManifestTyping,
	MatchExpressions,
	Methods,
	ModuleDeclarations,
	Modules,
	MultipleInheritance,
	MultiwayBranch,
	NamedArguments,
	NonNullAssertions,
	NullableTypes,
	OperatorOverloading,
	OptionalChaining,
	OptionalMembers,
	Overloading,
	PostTestLoops,
	RangeExpressions,
	RawStrings,
	ReadonlyMembers,
	References,
	RegularExpressions,
	ResourceManagement,
	SingleInheritance,
	SliceExpressions,
	StringInterpolation,
	StructuralConformance,
	Structs,
	SyntacticMetaprogramming,
	Tuples,
	TypeAliases,
	TypeAnnotations,
	Typeclasses,
	UnsafeCode,
	UntaggedUnions,
	Visibility,
} from './features/index.ts';

/** JavaScript's features. TypeScript is these and its typing features. */
export interface JavaScriptFeatures
	extends AsyncAwait,
		Generators,
		SingleInheritance,
		Accessors,
		Encapsulation,
		ComputedKeys,
		CoerciveEquality,
		ArbitraryPrecisionIntegers,
		RegularExpressions,
		StringInterpolation,
		Exceptions,
		ResourceManagement,
		Destructuring,
		LabeledControlFlow,
		Modules,
		Decorators,
		DefaultArguments,
		MultiwayBranch,
		CountedLoops,
		PostTestLoops,
		ConditionalExpressions,
		OptionalChaining {}

/** Python's features, those it spells by content included: visibility, accessors and operators by naming convention. */
export interface PythonFeatures
	extends AsyncAwait,
		Generators,
		MultipleInheritance,
		AbstractClasses,
		ExplicitOverrides,
		Accessors,
		Visibility,
		OperatorOverloading,
		TypeAnnotations,
		NullableTypes,
		TypeAliases,
		BoundedQuantification,
		ArbitraryPrecisionIntegers,
		ComplexNumbers,
		ByteStrings,
		RawStrings,
		StringInterpolation,
		Exceptions,
		ResourceManagement,
		MatchExpressions,
		Destructuring,
		Decorators,
		Modules,
		NamedArguments,
		DefaultArguments,
		Comprehensions,
		ConditionalExpressions,
		Tuples,
		SliceExpressions {}

/** Rust's features, operator overloading through its traits included. */
export interface RustFeatures
	extends AsyncBlocks,
		Coroutines,
		Methods,
		Structs,
		UntaggedUnions,
		Interfaces,
		AssociatedTypes,
		AlgebraicDataTypes,
		Typeclasses,
		OperatorOverloading,
		ManifestTyping,
		HigherRankPolymorphism,
		ConstGenerics,
		Lifetimes,
		Visibility,
		Characters,
		ByteStrings,
		RawStrings,
		ErrorPropagation,
		MatchExpressions,
		Destructuring,
		References,
		SyntacticMetaprogramming,
		Attributes,
		LabeledControlFlow,
		ModuleDeclarations,
		ForeignFunctionInterface,
		UnsafeCode,
		CompileTimeEvaluation,
		Tuples,
		RangeExpressions {}

export interface TypeScriptFeatures
	extends JavaScriptFeatures,
		TypeAnnotations,
		NonNullAssertions,
		OptionalMembers,
		ReadonlyMembers,
		AmbientDeclarations,
		StructuralConformance,
		BoundedQuantification,
		Interfaces,
		InterfaceConformance,
		TypeAliases,
		Enumerations,
		Visibility,
		AbstractClasses,
		ExplicitOverrides,
		Overloading,
		ModuleDeclarations {}
