// Auto-generated by @sittir/codegen — do not edit

import * as F from './factories.js';
import type * as T from './types.js';
import type { AnyNodeData } from '@sittir/types';
import { isNodeData } from './utils.js';

/** Closed union of every shape a loose-from() field value can hold. */
type _FromFieldInput =
  | AnyNodeData
  | string
  | number
  | boolean
  | null
  | undefined
  | { readonly [key: string]: _FromFieldInput }
  | readonly _FromFieldInput[];

export const _fromMap = {
  "module": moduleFrom,
  "import_statement": importStatementFrom,
  "import_prefix": importPrefixFrom,
  "relative_import": relativeImportFrom,
  "future_import_statement": futureImportStatementFrom,
  "import_from_statement": importFromStatementFrom,
  "aliased_import": aliasedImportFrom,
  "print_statement": printStatementFrom,
  "chevron": chevronFrom,
  "assert_statement": assertStatementFrom,
  "expression_statement": expressionStatementFrom,
  "named_expression": namedExpressionFrom,
  "return_statement": returnStatementFrom,
  "delete_statement": deleteStatementFrom,
  "raise_statement": raiseStatementFrom,
  "pass_statement": passStatementFrom,
  "break_statement": breakStatementFrom,
  "continue_statement": continueStatementFrom,
  "if_statement": ifStatementFrom,
  "elif_clause": elifClauseFrom,
  "else_clause": elseClauseFrom,
  "match_statement": matchStatementFrom,
  "case_clause": caseClauseFrom,
  "for_statement": forStatementFrom,
  "while_statement": whileStatementFrom,
  "try_statement": tryStatementFrom,
  "except_clause": exceptClauseFrom,
  "finally_clause": finallyClauseFrom,
  "with_statement": withStatementFrom,
  "with_clause": withClauseFrom,
  "with_item": withItemFrom,
  "function_definition": functionDefinitionFrom,
  "parameters": parametersFrom,
  "lambda_parameters": lambdaParametersFrom,
  "list_splat": listSplatFrom,
  "dictionary_splat": dictionarySplatFrom,
  "global_statement": globalStatementFrom,
  "nonlocal_statement": nonlocalStatementFrom,
  "exec_statement": execStatementFrom,
  "type_alias_statement": typeAliasStatementFrom,
  "class_definition": classDefinitionFrom,
  "type_parameter": typeParameterFrom,
  "parenthesized_list_splat": parenthesizedListSplatFrom,
  "argument_list": argumentListFrom,
  "decorated_definition": decoratedDefinitionFrom,
  "decorator": decoratorFrom,
  "block": blockFrom,
  "expression_list": expressionListFrom,
  "dotted_name": dottedNameFrom,
  "case_pattern": casePatternFrom,
  "union_pattern": unionPatternFrom,
  "dict_pattern": dictPatternFrom,
  "keyword_pattern": keywordPatternFrom,
  "splat_pattern": splatPatternFrom,
  "class_pattern": classPatternFrom,
  "complex_pattern": complexPatternFrom,
  "tuple_pattern": tuplePatternFrom,
  "list_pattern": listPatternFrom,
  "default_parameter": defaultParameterFrom,
  "typed_default_parameter": typedDefaultParameterFrom,
  "list_splat_pattern": listSplatPatternFrom,
  "dictionary_splat_pattern": dictionarySplatPatternFrom,
  "as_pattern": asPatternFrom,
  "not_operator": notOperatorFrom,
  "boolean_operator": booleanOperatorFrom,
  "binary_operator": binaryOperatorFrom,
  "unary_operator": unaryOperatorFrom,
  "comparison_operator": comparisonOperatorFrom,
  "lambda": lambdaFrom,
  "lambda_within_for_in_clause": lambdaWithinForInClauseFrom,
  "assignment": assignmentFrom,
  "augmented_assignment": augmentedAssignmentFrom,
  "pattern_list": patternListFrom,
  "yield": yield_From,
  "attribute": attributeFrom,
  "subscript": subscriptFrom,
  "slice": sliceFrom,
  "call": callFrom,
  "typed_parameter": typedParameterFrom,
  "type": typeFrom,
  "splat_type": splatTypeFrom,
  "generic_type": genericTypeFrom,
  "union_type": unionTypeFrom,
  "constrained_type": constrainedTypeFrom,
  "member_type": memberTypeFrom,
  "keyword_argument": keywordArgumentFrom,
  "list": listFrom,
  "set": setFrom,
  "tuple": tupleFrom,
  "dictionary": dictionaryFrom,
  "pair": pairFrom,
  "list_comprehension": listComprehensionFrom,
  "dictionary_comprehension": dictionaryComprehensionFrom,
  "set_comprehension": setComprehensionFrom,
  "generator_expression": generatorExpressionFrom,
  "parenthesized_expression": parenthesizedExpressionFrom,
  "for_in_clause": forInClauseFrom,
  "if_clause": ifClauseFrom,
  "conditional_expression": conditionalExpressionFrom,
  "concatenated_string": concatenatedStringFrom,
  "string": stringFrom,
  "string_content": stringContentFrom,
  "interpolation": interpolationFrom,
  "escape_sequence": escapeSequenceFrom,
  "format_specifier": formatSpecifierFrom,
  "type_conversion": typeConversionFrom,
  "integer": integerFrom,
  "float": floatFrom,
  "identifier": identifierFrom,
  "true": true_From,
  "false": false_From,
  "none": noneFrom,
  "await": await_From,
  "comment": commentFrom,
  "line_continuation": lineContinuationFrom,
  "string_start": stringStartFrom,
  "escape_interpolation": escapeInterpolationFrom,
  "string_end": stringEndFrom,
  "]": closeBracketFrom,
  ")": closeParenFrom,
  "}": closeBraceFrom,
  "except": exceptFrom,
  "as_pattern_target": asPatternTargetFrom,
  "assignment_eq": assignmentEqFrom,
  "assignment_type": assignmentTypeFrom,
  "assignment_typed": assignmentTypedFrom,
  "format_expression": formatExpressionFrom,
} as const;
export type _FromMap = typeof _fromMap;

// --- Loose-input resolver helpers (see C6-prereq) ---
interface _LeafEntry {
  readonly values?: readonly string[];
  readonly pattern?: RegExp;
  readonly factory: (text: string) => AnyNodeData;
}
const _leafRegistry: { readonly [kind: string]: _LeafEntry } = {
  "import_prefix": { factory: F.importPrefix },
  "pass_statement": { values: ["pass"], factory: () => F.passStatement() },
  "break_statement": { values: ["break"], factory: () => F.breakStatement() },
  "continue_statement": { values: ["continue"], factory: () => F.continueStatement() },
  "escape_sequence": { factory: F.escapeSequence },
  "type_conversion": { factory: F.typeConversion },
  "integer": { factory: F.integer },
  "float": { factory: F.float },
  "identifier": { factory: F.identifier },
  "true": { values: ["True"], factory: () => F.true_() },
  "false": { values: ["False"], factory: () => F.false_() },
  "none": { values: ["None"], factory: () => F.none() },
  "comment": { factory: F.comment },
  "line_continuation": { factory: F.lineContinuation },
  "string_start": { factory: F.stringStart },
  "escape_interpolation": { factory: F.escapeInterpolation },
  "string_end": { factory: F.stringEnd },
  "]": { factory: F.closeBracket },
  ")": { factory: F.closeParen },
  "}": { factory: F.closeBrace },
  "except": { factory: F.except },
};

function _resolveLeafString(v: string, kinds: readonly string[]): AnyNodeData | undefined {
  for (const kind of kinds) {
    const entry = _leafRegistry[kind];
    if (!entry) continue;
    if (entry.values && entry.values.includes(v)) return entry.factory(v);
    if (entry.pattern && entry.pattern.test(v)) return entry.factory(v);
  }
  for (const kind of kinds) {
    const entry = _leafRegistry[kind];
    if (entry && !entry.values && !entry.pattern) return entry.factory(v);
  }
  return undefined;
}

function _resolveByKind<K extends keyof _FromMap>(
  kind: K,
  rest: _FromFieldInput,
): ReturnType<_FromMap[K]> {
  const fn = _fromMap[kind];
  return (fn as (input?: _FromFieldInput) => ReturnType<_FromMap[K]>)(rest);
}

function _resolveScalar(v: boolean | number): AnyNodeData | undefined {
  if (typeof v === "number") {
    if (Number.isInteger(v)) {
      const e = _leafRegistry["integer"];
      return e ? e.factory(String(v)) : undefined;
    }
    const e = _leafRegistry["float"];
    return e ? e.factory(String(v)) : undefined;
  }
  return undefined;
}

function _resolveOne<T>(
  v: _FromFieldInput,
  leafKinds: readonly string[],
  branchKinds: readonly string[],
): T {
  if (v === undefined || v === null) return v as T;
  if (isNodeData(v)) return v as T;
  if (typeof v === "boolean" || typeof v === "number") {
    const scalar = _resolveScalar(v);
    if (scalar !== undefined) return scalar as T;
  }
  if (typeof v === "string" && leafKinds.length > 0) {
    const leaf = _resolveLeafString(v, leafKinds);
    if (leaf !== undefined) return leaf as T;
  }
  if (typeof v === "object" && !Array.isArray(v) && "kind" in v) {
    const { kind, ...rest } = v;
    if (typeof kind === "string" && kind in _fromMap) return _resolveByKind(kind as keyof _FromMap, rest) as T;
  }
  if (branchKinds.length === 1 && typeof v === "object" && !Array.isArray(v)) {
    const bk = branchKinds[0]!;
    if (bk in _fromMap) return _resolveByKind(bk as keyof _FromMap, v) as T;
  }
  return v as T;
}

function _resolveMany<T>(
  v: _FromFieldInput,
  leafKinds: readonly string[],
  branchKinds: readonly string[],
): readonly T[] {
  if (v === undefined || v === null) return [];
  const arr: readonly _FromFieldInput[] = Array.isArray(v) ? v : [v];
  return arr.map(e => _resolveOne<T>(e, leafKinds, branchKinds));
}

function _resolveOneLeaf<T>(v: _FromFieldInput, kind: string): T {
  if (v === undefined || v === null) return v as T;
  if (isNodeData(v)) return v as T;
  if (typeof v === "boolean" || typeof v === "number") {
    const scalar = _resolveScalar(v);
    if (scalar !== undefined) return scalar as T;
  }
  if (typeof v === "string") {
    const e = _leafRegistry[kind];
    if (e !== undefined) return e.factory(v) as T;
  }
  if (typeof v === "object" && !Array.isArray(v) && "kind" in v) {
    const { kind: k, ...rest } = v;
    if (typeof k === "string" && k in _fromMap) return _resolveByKind(k as keyof _FromMap, rest) as T;
  }
  return v as T;
}

function _resolveOneBranch<T>(v: _FromFieldInput, kind: string): T {
  if (v === undefined || v === null) return v as T;
  if (isNodeData(v)) return v as T;
  if (typeof v === "object" && !Array.isArray(v)) {
    if ("kind" in v) {
      const { kind: k, ...rest } = v;
      if (typeof k === "string" && k in _fromMap) return _resolveByKind(k as keyof _FromMap, rest) as T;
    }
    if (kind in _fromMap) return _resolveByKind(kind as keyof _FromMap, v) as T;
  }
  return v as T;
}

function _resolveManyLeaf<T>(v: _FromFieldInput, kind: string): readonly T[] {
  if (v === undefined || v === null) return [];
  const arr: readonly _FromFieldInput[] = Array.isArray(v) ? v : [v];
  return arr.map(e => _resolveOneLeaf<T>(e, kind));
}

function _resolveManyBranch<T>(v: _FromFieldInput, kind: string): readonly T[] {
  if (v === undefined || v === null) return [];
  const arr: readonly _FromFieldInput[] = Array.isArray(v) ? v : [v];
  return arr.map(e => _resolveOneBranch<T>(e, kind));
}

function _assertNonEmpty<T>(
  arr: readonly T[],
  label: string,
): asserts arr is readonly [T, ...(readonly T[])] {
  if (arr.length === 0) {
    throw new Error(`${label}: requires at least one element`);
  }
}

// Interned resolver kind lists (T042i dedup)
const _super_expression: readonly string[] = ["comparison_operator","not_operator","boolean_operator","lambda","primary_expression","conditional_expression","named_expression","as_pattern"];
const _super_keyword_identifier: readonly string[] = ["identifier"];
const _super_expressions: readonly string[] = ["expression","expression_list"];
const _super_left_hand_side: readonly string[] = ["pattern","pattern_list"];
const _super_expression_within_for_in_clause: readonly string[] = ["expression","lambda"];
const _super_right_hand_side: readonly string[] = ["expression","expression_list","assignment","augmented_assignment","pattern_list","yield"];
const _super_f_expression: readonly string[] = ["expression","expression_list","pattern_list","yield"];
const _K0: readonly string[] = [];
const _K1: readonly string[] = ["dotted_name","aliased_import"];
const _K2: readonly string[] = ["relative_import","dotted_name"];
const _K3: readonly string[] = ["keyword_identifier"];
const _K4: readonly string[] = ["elif_clause","else_clause"];
const _K5: readonly string[] = ["string"];
const _K6: readonly string[] = ["class_definition","function_definition"];
const _K7: readonly string[] = ["integer","float"];
const _K8: readonly string[] = ["tuple_pattern"];
const _K9: readonly string[] = ["identifier","integer","float","true","false","none"];
const _K10: readonly string[] = ["await","binary_operator","keyword_identifier","string","concatenated_string","unary_operator","attribute","subscript","call","list","list_comprehension","dictionary","dictionary_comprehension","set","set_comprehension","tuple","parenthesized_expression","generator_expression","list_splat"];
const _K11: readonly string[] = ["_not_in","_is_not"];
const _K12: readonly string[] = ["keyword_identifier","subscript","attribute","list_splat_pattern","tuple_pattern","list_pattern"];
const _K13: readonly string[] = ["comparison_operator","not_operator","boolean_operator","lambda","primary_expression","conditional_expression","named_expression","as_pattern","slice"];
const _K14: readonly string[] = ["generator_expression","argument_list"];
const _K15: readonly string[] = ["list_splat_pattern","dictionary_splat_pattern"];
const _K16: readonly string[] = ["for_in_clause","if_clause"];
const _K17: readonly string[] = ["interpolation","string_content"];

export function moduleFrom(...input: readonly (NonNullable<T.Module.Config['children']>[number] | T.Module)[]) {
  if (input.length === 1 && isNodeData(input[0]) && input[0].$type === 'module') {
    const data = input[0];
    return F.module(...(data.$children ?? []));
  }
  return F.module(...input);
}

export function importStatementFrom(input: T.ImportStatement | T.ImportStatement.Loose): ReturnType<typeof F.importStatement> {
  if (isNodeData(input)) return input;
  const _ne_name = _resolveMany<NonNullable<T.ImportStatement.Config['name']>[number]>(input.name, _K0, _K1);
  _assertNonEmpty(_ne_name, 'import_statement.name');
  return F.importStatement({
    name: _ne_name,
  });
}

export function importPrefixFrom(input: string | T.ImportPrefix) {
  if (isNodeData(input)) return input;
  return F.importPrefix(input);
}

export function relativeImportFrom(input: T.RelativeImport | T.RelativeImport.Loose): ReturnType<typeof F.relativeImport> {
  if (isNodeData(input)) return input;
  return F.relativeImport({
    importPrefix: _resolveOneLeaf<NonNullable<T.RelativeImport.Config['importPrefix']>>(input.importPrefix, "import_prefix"),
    dottedName: _resolveOneBranch<NonNullable<T.RelativeImport.Config['dottedName']>>(input.dottedName, "dotted_name"),
  });
}

export function futureImportStatementFrom(input: T.FutureImportStatement | T.FutureImportStatement.Loose): ReturnType<typeof F.futureImportStatement> {
  if (isNodeData(input)) return input;
  const _ne_name = _resolveMany<NonNullable<T.FutureImportStatement.Config['name']>[number]>(input.name, _K0, _K1);
  _assertNonEmpty(_ne_name, 'future_import_statement.name');
  return F.futureImportStatement({
    name: _ne_name,
  });
}

export function importFromStatementFrom(input: T.ImportFromStatement | T.ImportFromStatement.Loose): ReturnType<typeof F.importFromStatement> {
  if (isNodeData(input)) return input;
  const _ne_wildcardImport = _resolveMany<NonNullable<T.ImportFromStatement.Config['wildcardImport']>[number]>(input.wildcardImport, _K0, _K1);
  _assertNonEmpty(_ne_wildcardImport, 'import_from_statement.wildcardImport');
  return F.importFromStatement({
    moduleName: _resolveOne<NonNullable<T.ImportFromStatement.Config['moduleName']>>(input.moduleName, _K0, _K2),
    wildcardImport: _ne_wildcardImport,
    name: _resolveMany<NonNullable<T.ImportFromStatement.Config['name']>[number]>(input.name, _K0, _K1),
  });
}

export function aliasedImportFrom(input: T.AliasedImport | T.AliasedImport.Loose): ReturnType<typeof F.aliasedImport> {
  if (isNodeData(input)) return input;
  return F.aliasedImport({
    name: _resolveOneBranch<NonNullable<T.AliasedImport.Config['name']>>(input.name, "dotted_name"),
    alias: _resolveOneLeaf<NonNullable<T.AliasedImport.Config['alias']>>(input.alias, "identifier"),
  });
}

export function printStatementFrom(input: T.PrintStatement | T.PrintStatement.Loose): ReturnType<typeof F.printStatement> {
  if (isNodeData(input)) return input;
  return F.printStatement({
    argument: _resolveMany<NonNullable<T.PrintStatement.Config['argument']>[number]>(input.argument, _K0, _super_expression),
    children: _resolveOneBranch<NonNullable<T.PrintStatement.Config['children']>>(input.children, "chevron"),
  });
}

export function chevronFrom(input: T.Chevron | T.Chevron.Loose): ReturnType<typeof F.chevron> {
  if (isNodeData(input)) return input;
  return F.chevron({
    expression: _resolveOne<NonNullable<T.Chevron.Config['expression']>>(input.expression, _K0, _super_expression),
  });
}

export function assertStatementFrom(...input: readonly (NonNullable<T.AssertStatement.Config['children']>[number] | T.AssertStatement)[]) {
  if (input.length === 1 && isNodeData(input[0]) && input[0].$type === 'assert_statement') {
    const data = input[0];
    return F.assertStatement(...(data.$children ?? []));
  }
  return F.assertStatement(...input);
}

export function expressionStatementFrom(input?: NonNullable<T.ExpressionStatement.Config['children']>[number] | T.ExpressionStatement) {
  if (isNodeData(input) && input.$type === 'expression_statement') {
    const data = input;
    const child = data.$children ? data.$children[0] : undefined;
    return F.expressionStatement(child);
  }
  return F.expressionStatement(input);
}

export function namedExpressionFrom(input: T.NamedExpression | T.NamedExpression.Loose): ReturnType<typeof F.namedExpression> {
  if (isNodeData(input)) return input;
  return F.namedExpression({
    name: _resolveOne<NonNullable<T.NamedExpression.Config['name']>>(input.name, _super_keyword_identifier, _K3),
    value: _resolveOne<NonNullable<T.NamedExpression.Config['value']>>(input.value, _K0, _super_expression),
  });
}

export function returnStatementFrom(input?: NonNullable<T.ReturnStatement.Config['children']>[number] | T.ReturnStatement) {
  if (isNodeData(input) && input.$type === 'return_statement') {
    const data = input;
    const child = data.$children ? data.$children[0] : undefined;
    return F.returnStatement(child);
  }
  return F.returnStatement(input);
}

export function deleteStatementFrom(input?: NonNullable<T.DeleteStatement.Config['children']>[number] | T.DeleteStatement) {
  if (isNodeData(input) && input.$type === 'delete_statement') {
    const data = input;
    const child = data.$children ? data.$children[0] : undefined;
    return F.deleteStatement(child);
  }
  return F.deleteStatement(input);
}

export function raiseStatementFrom(input?: T.RaiseStatement | T.RaiseStatement.Loose): ReturnType<typeof F.raiseStatement> {
  if (input !== undefined && isNodeData(input)) return input;
  return F.raiseStatement({
    cause: _resolveOne<NonNullable<T.RaiseStatement.Config['cause']>>(input?.cause, _K0, _super_expression),
    children: _resolveOne<NonNullable<T.RaiseStatement.Config['children']>>(input?.children, _K0, _super_expressions),
  });
}

export function passStatementFrom(input?: T.PassStatement) {
  if (isNodeData(input)) return input;
  return F.passStatement();
}

export function breakStatementFrom(input?: T.BreakStatement) {
  if (isNodeData(input)) return input;
  return F.breakStatement();
}

export function continueStatementFrom(input?: T.ContinueStatement) {
  if (isNodeData(input)) return input;
  return F.continueStatement();
}

export function ifStatementFrom(input: T.IfStatement | T.IfStatement.Loose): ReturnType<typeof F.ifStatement> {
  if (isNodeData(input)) return input;
  return F.ifStatement({
    condition: _resolveOne<NonNullable<T.IfStatement.Config['condition']>>(input.condition, _K0, _super_expression),
    consequence: _resolveOneBranch<NonNullable<T.IfStatement.Config['consequence']>>(input.consequence, "_suite"),
    alternative: _resolveMany<NonNullable<T.IfStatement.Config['alternative']>[number]>(input.alternative, _K0, _K4),
  });
}

export function elifClauseFrom(input: T.ElifClause | T.ElifClause.Loose): ReturnType<typeof F.elifClause> {
  if (isNodeData(input)) return input;
  return F.elifClause({
    condition: _resolveOne<NonNullable<T.ElifClause.Config['condition']>>(input.condition, _K0, _super_expression),
    consequence: _resolveOneBranch<NonNullable<T.ElifClause.Config['consequence']>>(input.consequence, "_suite"),
  });
}

export function elseClauseFrom(input: T.ElseClause | T.ElseClause.Loose): ReturnType<typeof F.elseClause> {
  if (isNodeData(input)) return input;
  return F.elseClause({
    body: _resolveOneBranch<NonNullable<T.ElseClause.Config['body']>>(input.body, "_suite"),
  });
}

export function matchStatementFrom(input: T.MatchStatement | T.MatchStatement.Loose): ReturnType<typeof F.matchStatement> {
  if (isNodeData(input)) return input;
  const _ne_subject = _resolveMany<NonNullable<T.MatchStatement.Config['subject']>[number]>(input.subject, _K0, _super_expression);
  _assertNonEmpty(_ne_subject, 'match_statement.subject');
  return F.matchStatement({
    subject: _ne_subject,
    body: _resolveOneBranch<NonNullable<T.MatchStatement.Config['body']>>(input.body, "block"),
  });
}

export function caseClauseFrom(input: T.CaseClause | T.CaseClause.Loose): ReturnType<typeof F.caseClause> {
  if (isNodeData(input)) return input;
  const _ne_children = _resolveManyBranch<NonNullable<T.CaseClause.Config['children']>[number]>(input.children, "case_pattern");
  _assertNonEmpty(_ne_children, 'case_clause.children');
  return F.caseClause({
    guard: _resolveOneBranch<NonNullable<T.CaseClause.Config['guard']>>(input.guard, "if_clause"),
    consequence: _resolveOneBranch<NonNullable<T.CaseClause.Config['consequence']>>(input.consequence, "_suite"),
    children: _ne_children,
  });
}

export function forStatementFrom(input: T.ForStatement | T.ForStatement.Loose): ReturnType<typeof F.forStatement> {
  if (isNodeData(input)) return input;
  return F.forStatement({
    async: _resolveOneLeaf<NonNullable<T.ForStatement.Config['async']>>(input.async, "_kw_async"),
    left: _resolveOne<NonNullable<T.ForStatement.Config['left']>>(input.left, _K0, _super_left_hand_side),
    right: _resolveOne<NonNullable<T.ForStatement.Config['right']>>(input.right, _K0, _super_expressions),
    body: _resolveOneBranch<NonNullable<T.ForStatement.Config['body']>>(input.body, "_suite"),
    alternative: _resolveOneBranch<NonNullable<T.ForStatement.Config['alternative']>>(input.alternative, "else_clause"),
  });
}

export function whileStatementFrom(input: T.WhileStatement | T.WhileStatement.Loose): ReturnType<typeof F.whileStatement> {
  if (isNodeData(input)) return input;
  return F.whileStatement({
    condition: _resolveOne<NonNullable<T.WhileStatement.Config['condition']>>(input.condition, _K0, _super_expression),
    body: _resolveOneBranch<NonNullable<T.WhileStatement.Config['body']>>(input.body, "_suite"),
    alternative: _resolveOneBranch<NonNullable<T.WhileStatement.Config['alternative']>>(input.alternative, "else_clause"),
  });
}

export function tryStatementFrom(input: T.TryStatement | T.TryStatement.Loose): ReturnType<typeof F.tryStatement> {
  if (isNodeData(input)) return input;
  return F.tryStatement({
    body: _resolveOneBranch<NonNullable<T.TryStatement.Config['body']>>(input.body, "_suite"),
    exceptClauses: _resolveManyBranch<NonNullable<T.TryStatement.Config['exceptClauses']>[number]>(input.exceptClauses, "except_clause"),
    elseClause: _resolveOneBranch<NonNullable<T.TryStatement.Config['elseClause']>>(input.elseClause, "else_clause"),
    finallyClause: _resolveOneBranch<NonNullable<T.TryStatement.Config['finallyClause']>>(input.finallyClause, "finally_clause"),
  });
}

export function exceptClauseFrom(input: T.ExceptClause | T.ExceptClause.Loose): ReturnType<typeof F.exceptClause> {
  if (isNodeData(input)) return input;
  return F.exceptClause({
    value: _resolveOne<NonNullable<T.ExceptClause.Config['value']>>(input.value, _K0, _super_expression),
    alias: _resolveOne<NonNullable<T.ExceptClause.Config['alias']>>(input.alias, _K0, _super_expression),
    children: _resolveOneBranch<NonNullable<T.ExceptClause.Config['children']>>(input.children, "_suite"),
  });
}

export function finallyClauseFrom(input: T.FinallyClause | T.FinallyClause.Loose): ReturnType<typeof F.finallyClause> {
  if (isNodeData(input)) return input;
  return F.finallyClause({
    block: _resolveOneBranch<NonNullable<T.FinallyClause.Config['block']>>(input.block, "_suite"),
  });
}

export function withStatementFrom(input: T.WithStatement | T.WithStatement.Loose): ReturnType<typeof F.withStatement> {
  if (isNodeData(input)) return input;
  return F.withStatement({
    async: _resolveOneLeaf<NonNullable<T.WithStatement.Config['async']>>(input.async, "_kw_async"),
    withClause: _resolveOneBranch<NonNullable<T.WithStatement.Config['withClause']>>(input.withClause, "with_clause"),
    body: _resolveOneBranch<NonNullable<T.WithStatement.Config['body']>>(input.body, "_suite"),
  });
}

export function withClauseFrom(...input: readonly (NonNullable<T.WithClause.Config['children']>[number] | T.WithClause)[]) {
  if (input.length === 1 && isNodeData(input[0]) && input[0].$type === 'with_clause') {
    const data = input[0];
    return F.withClause(...(data.$children ?? []));
  }
  return F.withClause(...input);
}

export function withItemFrom(input: T.WithItem | T.WithItem.Loose): ReturnType<typeof F.withItem> {
  if (isNodeData(input)) return input;
  return F.withItem({
    value: _resolveOne<NonNullable<T.WithItem.Config['value']>>(input.value, _K0, _super_expression),
  });
}

export function functionDefinitionFrom(input: T.FunctionDefinition | T.FunctionDefinition.Loose): ReturnType<typeof F.functionDefinition> {
  if (isNodeData(input)) return input;
  return F.functionDefinition({
    async: _resolveOneLeaf<NonNullable<T.FunctionDefinition.Config['async']>>(input.async, "_kw_async"),
    name: _resolveOneLeaf<NonNullable<T.FunctionDefinition.Config['name']>>(input.name, "identifier"),
    typeParameters: _resolveOneBranch<NonNullable<T.FunctionDefinition.Config['typeParameters']>>(input.typeParameters, "type_parameter"),
    parameters: _resolveOneBranch<NonNullable<T.FunctionDefinition.Config['parameters']>>(input.parameters, "parameters"),
    returnType: _resolveOneBranch<NonNullable<T.FunctionDefinition.Config['returnType']>>(input.returnType, "type"),
    body: _resolveOneBranch<NonNullable<T.FunctionDefinition.Config['body']>>(input.body, "_suite"),
  });
}

export function parametersFrom(...input: readonly (NonNullable<T.Parameters.Config['children']>[number] | T.Parameters)[]) {
  if (input.length === 1 && isNodeData(input[0]) && input[0].$type === 'parameters') {
    const data = input[0];
    return F.parameters(...(data.$children ?? []));
  }
  return F.parameters(...input);
}

export function lambdaParametersFrom(...input: readonly (NonNullable<T.LambdaParameters.Config['children']>[number] | T.LambdaParameters)[]) {
  if (input.length === 1 && isNodeData(input[0]) && input[0].$type === 'lambda_parameters') {
    const data = input[0];
    return F.lambdaParameters(...(data.$children ?? []));
  }
  return F.lambdaParameters(...input);
}

export function listSplatFrom(input: T.ListSplat | T.ListSplat.Loose): ReturnType<typeof F.listSplat> {
  if (isNodeData(input)) return input;
  return F.listSplat({
    expression: _resolveOne<NonNullable<T.ListSplat.Config['expression']>>(input.expression, _K0, _super_expression),
  });
}

export function dictionarySplatFrom(input: T.DictionarySplat | T.DictionarySplat.Loose): ReturnType<typeof F.dictionarySplat> {
  if (isNodeData(input)) return input;
  return F.dictionarySplat({
    expression: _resolveOne<NonNullable<T.DictionarySplat.Config['expression']>>(input.expression, _K0, _super_expression),
  });
}

export function globalStatementFrom(...input: readonly (NonNullable<T.GlobalStatement.Config['children']>[number] | T.GlobalStatement)[]) {
  if (input.length === 1 && isNodeData(input[0]) && input[0].$type === 'global_statement') {
    const data = input[0];
    return F.globalStatement(...(data.$children ?? []));
  }
  return F.globalStatement(...input);
}

export function nonlocalStatementFrom(...input: readonly (NonNullable<T.NonlocalStatement.Config['children']>[number] | T.NonlocalStatement)[]) {
  if (input.length === 1 && isNodeData(input[0]) && input[0].$type === 'nonlocal_statement') {
    const data = input[0];
    return F.nonlocalStatement(...(data.$children ?? []));
  }
  return F.nonlocalStatement(...input);
}

export function execStatementFrom(input: T.ExecStatement | T.ExecStatement.Loose): ReturnType<typeof F.execStatement> {
  if (isNodeData(input)) return input;
  const _ne_inClause = _resolveMany<NonNullable<T.ExecStatement.Config['inClause']>[number]>(input.inClause, _K0, _super_expression);
  _assertNonEmpty(_ne_inClause, 'exec_statement.inClause');
  return F.execStatement({
    code: _resolveOne<NonNullable<T.ExecStatement.Config['code']>>(input.code, _super_keyword_identifier, _K5),
    inClause: _ne_inClause,
  });
}

export function typeAliasStatementFrom(input: T.TypeAliasStatement | T.TypeAliasStatement.Loose): ReturnType<typeof F.typeAliasStatement> {
  if (isNodeData(input)) return input;
  return F.typeAliasStatement({
    left: _resolveOneBranch<NonNullable<T.TypeAliasStatement.Config['left']>>(input.left, "type"),
    right: _resolveOneBranch<NonNullable<T.TypeAliasStatement.Config['right']>>(input.right, "type"),
  });
}

export function classDefinitionFrom(input: T.ClassDefinition | T.ClassDefinition.Loose): ReturnType<typeof F.classDefinition> {
  if (isNodeData(input)) return input;
  return F.classDefinition({
    name: _resolveOneLeaf<NonNullable<T.ClassDefinition.Config['name']>>(input.name, "identifier"),
    typeParameters: _resolveOneBranch<NonNullable<T.ClassDefinition.Config['typeParameters']>>(input.typeParameters, "type_parameter"),
    superclasses: _resolveOneBranch<NonNullable<T.ClassDefinition.Config['superclasses']>>(input.superclasses, "argument_list"),
    body: _resolveOneBranch<NonNullable<T.ClassDefinition.Config['body']>>(input.body, "_suite"),
  });
}

export function typeParameterFrom(...input: readonly (NonNullable<T.TypeParameter.Config['children']>[number] | T.TypeParameter)[]) {
  if (input.length === 1 && isNodeData(input[0]) && input[0].$type === 'type_parameter') {
    const data = input[0];
    return F.typeParameter(...(data.$children ?? []));
  }
  return F.typeParameter(...input);
}

export function parenthesizedListSplatFrom(input?: NonNullable<T.ParenthesizedListSplat.Config['children']>[number] | T.ParenthesizedListSplat) {
  if (isNodeData(input) && input.$type === 'parenthesized_list_splat') {
    const data = input;
    const child = data.$children ? data.$children[0] : undefined;
    return F.parenthesizedListSplat(child);
  }
  return F.parenthesizedListSplat(input);
}

export function argumentListFrom(...input: readonly (NonNullable<T.ArgumentList.Config['children']>[number] | T.ArgumentList)[]) {
  if (input.length === 1 && isNodeData(input[0]) && input[0].$type === 'argument_list') {
    const data = input[0];
    return F.argumentList(...(data.$children ?? []));
  }
  return F.argumentList(...input);
}

export function decoratedDefinitionFrom(input: T.DecoratedDefinition | T.DecoratedDefinition.Loose): ReturnType<typeof F.decoratedDefinition> {
  if (isNodeData(input)) return input;
  const _ne_children = _resolveManyBranch<NonNullable<T.DecoratedDefinition.Config['children']>[number]>(input.children, "decorator");
  _assertNonEmpty(_ne_children, 'decorated_definition.children');
  return F.decoratedDefinition({
    definition: _resolveOne<NonNullable<T.DecoratedDefinition.Config['definition']>>(input.definition, _K0, _K6),
    children: _ne_children,
  });
}

export function decoratorFrom(input: T.Decorator | T.Decorator.Loose): ReturnType<typeof F.decorator> {
  if (isNodeData(input)) return input;
  return F.decorator({
    expression: _resolveOne<NonNullable<T.Decorator.Config['expression']>>(input.expression, _K0, _super_expression),
    newline: _resolveOne<NonNullable<T.Decorator.Config['newline']>>(input.newline, _K0, _K0),
  });
}

export function blockFrom(...input: readonly (NonNullable<T.Block.Config['children']>[number] | T.Block)[]) {
  if (input.length === 1 && isNodeData(input[0]) && input[0].$type === 'block') {
    const data = input[0];
    return F.block(...(data.$children ?? []));
  }
  return F.block(...input);
}

export function expressionListFrom(input: T.ExpressionList | T.ExpressionList.Loose): ReturnType<typeof F.expressionList> {
  if (isNodeData(input)) return input;
  return F.expressionList({
    expression: _resolveOne<NonNullable<T.ExpressionList.Config['expression']>>(input.expression, _K0, _super_expression),
    children: _resolveMany<NonNullable<T.ExpressionList.Config['children']>[number]>(input.children, _K0, _super_expression),
  });
}

export function dottedNameFrom(...input: readonly (NonNullable<T.DottedName.Config['children']>[number] | T.DottedName)[]) {
  if (input.length === 1 && isNodeData(input[0]) && input[0].$type === 'dotted_name') {
    const data = input[0];
    return F.dottedName(...(data.$children ?? []));
  }
  return F.dottedName(...input);
}

export function casePatternFrom(input?: NonNullable<T.CasePattern.Config['children']>[number] | T.CasePattern) {
  if (isNodeData(input) && input.$type === 'case_pattern') {
    const data = input;
    const child = data.$children ? data.$children[0] : undefined;
    return F.casePattern(child);
  }
  return F.casePattern(input);
}

export function unionPatternFrom(...input: readonly (NonNullable<T.UnionPattern.Config['children']>[number] | T.UnionPattern)[]) {
  if (input.length === 1 && isNodeData(input[0]) && input[0].$type === 'union_pattern') {
    const data = input[0];
    return F.unionPattern(...(data.$children ?? []));
  }
  return F.unionPattern(...input);
}

export function dictPatternFrom(input: T.DictPattern | T.DictPattern.Loose): ReturnType<typeof F.dictPattern> {
  if (isNodeData(input)) return input;
  return F.dictPattern({
    key: _resolveManyBranch<NonNullable<T.DictPattern.Config['key']>[number]>(input.key, "_simple_pattern"),
    value: _resolveManyBranch<NonNullable<T.DictPattern.Config['value']>[number]>(input.value, "case_pattern"),
    children: _resolveManyBranch<NonNullable<T.DictPattern.Config['children']>[number]>(input.children, "splat_pattern"),
  });
}

export function keywordPatternFrom(input: T.KeywordPattern | T.KeywordPattern.Loose): ReturnType<typeof F.keywordPattern> {
  if (isNodeData(input)) return input;
  return F.keywordPattern({
    identifier: _resolveOneLeaf<NonNullable<T.KeywordPattern.Config['identifier']>>(input.identifier, "identifier"),
    simplePattern: _resolveOneBranch<NonNullable<T.KeywordPattern.Config['simplePattern']>>(input.simplePattern, "_simple_pattern"),
  });
}

export function splatPatternFrom(input: T.SplatPattern | T.SplatPattern.Loose): ReturnType<typeof F.splatPattern> {
  if (isNodeData(input)) return input;
  return F.splatPattern({
    identifier: _resolveOne<NonNullable<T.SplatPattern.Config['identifier']>>(input.identifier, _K0, _K0),
    children: _resolveOneLeaf<NonNullable<T.SplatPattern.Config['children']>>(input.children, "identifier"),
  });
}

export function classPatternFrom(input: T.ClassPattern | T.ClassPattern.Loose): ReturnType<typeof F.classPattern> {
  if (isNodeData(input)) return input;
  const _ne_arguments = _resolveManyBranch<NonNullable<T.ClassPattern.Config['arguments']>[number]>(input.arguments, "case_pattern");
  _assertNonEmpty(_ne_arguments, 'class_pattern.arguments');
  return F.classPattern({
    dottedName: _resolveOneBranch<NonNullable<T.ClassPattern.Config['dottedName']>>(input.dottedName, "dotted_name"),
    arguments: _ne_arguments,
  });
}

export function complexPatternFrom(input: T.ComplexPattern | T.ComplexPattern.Loose): ReturnType<typeof F.complexPattern> {
  if (isNodeData(input)) return input;
  return F.complexPattern({
    real: _resolveOne<NonNullable<T.ComplexPattern.Config['real']>>(input.real, _K0, _K0),
    imaginary: _resolveOne<NonNullable<T.ComplexPattern.Config['imaginary']>>(input.imaginary, _K7, _K0),
    children: _resolveOne<NonNullable<T.ComplexPattern.Config['children']>>(input.children, _K7, _K0),
  });
}

export function tuplePatternFrom(...input: readonly (NonNullable<T.TuplePattern.Config['children']>[number] | T.TuplePattern)[]) {
  if (input.length === 1 && isNodeData(input[0]) && input[0].$type === 'tuple_pattern') {
    const data = input[0];
    return F.tuplePattern(...(data.$children ?? []));
  }
  return F.tuplePattern(...input);
}

export function listPatternFrom(...input: readonly (NonNullable<T.ListPattern.Config['children']>[number] | T.ListPattern)[]) {
  if (input.length === 1 && isNodeData(input[0]) && input[0].$type === 'list_pattern') {
    const data = input[0];
    return F.listPattern(...(data.$children ?? []));
  }
  return F.listPattern(...input);
}

export function defaultParameterFrom(input: T.DefaultParameter | T.DefaultParameter.Loose): ReturnType<typeof F.defaultParameter> {
  if (isNodeData(input)) return input;
  return F.defaultParameter({
    name: _resolveOne<NonNullable<T.DefaultParameter.Config['name']>>(input.name, _super_keyword_identifier, _K8),
    value: _resolveOne<NonNullable<T.DefaultParameter.Config['value']>>(input.value, _K0, _super_expression),
  });
}

export function typedDefaultParameterFrom(input: T.TypedDefaultParameter | T.TypedDefaultParameter.Loose): ReturnType<typeof F.typedDefaultParameter> {
  if (isNodeData(input)) return input;
  return F.typedDefaultParameter({
    name: _resolveOneLeaf<NonNullable<T.TypedDefaultParameter.Config['name']>>(input.name, "identifier"),
    type: _resolveOneBranch<NonNullable<T.TypedDefaultParameter.Config['type']>>(input.type, "type"),
    value: _resolveOne<NonNullable<T.TypedDefaultParameter.Config['value']>>(input.value, _K0, _super_expression),
  });
}

export function listSplatPatternFrom(input?: NonNullable<T.ListSplatPattern.Config['children']>[number] | T.ListSplatPattern) {
  if (isNodeData(input) && input.$type === 'list_splat_pattern') {
    const data = input;
    const child = data.$children ? data.$children[0] : undefined;
    return F.listSplatPattern(child);
  }
  return F.listSplatPattern(input);
}

export function dictionarySplatPatternFrom(input?: NonNullable<T.DictionarySplatPattern.Config['children']>[number] | T.DictionarySplatPattern) {
  if (isNodeData(input) && input.$type === 'dictionary_splat_pattern') {
    const data = input;
    const child = data.$children ? data.$children[0] : undefined;
    return F.dictionarySplatPattern(child);
  }
  return F.dictionarySplatPattern(input);
}

export function asPatternFrom(input: T.AsPattern | T.AsPattern.Loose): ReturnType<typeof F.asPattern> {
  if (isNodeData(input)) return input;
  return F.asPattern({
    expression: _resolveOne<NonNullable<T.AsPattern.Config['expression']>>(input.expression, _K0, _super_expression),
    alias: _resolveOneBranch<NonNullable<T.AsPattern.Config['alias']>>(input.alias, "as_pattern_target"),
  });
}

export function notOperatorFrom(input: T.NotOperator | T.NotOperator.Loose): ReturnType<typeof F.notOperator> {
  if (isNodeData(input)) return input;
  return F.notOperator({
    argument: _resolveOne<NonNullable<T.NotOperator.Config['argument']>>(input.argument, _K0, _super_expression),
  });
}

export function booleanOperatorFrom(input: T.BooleanOperator | T.BooleanOperator.Loose): ReturnType<typeof F.booleanOperator> {
  if (isNodeData(input)) return input;
  return F.booleanOperator({
    left: _resolveOne<NonNullable<T.BooleanOperator.Config['left']>>(input.left, _K0, _super_expression),
    right: _resolveOne<NonNullable<T.BooleanOperator.Config['right']>>(input.right, _K0, _super_expression),
  });
}

export function binaryOperatorFrom(input: T.BinaryOperator | T.BinaryOperator.Loose): ReturnType<typeof F.binaryOperator> {
  if (isNodeData(input)) return input;
  return F.binaryOperator({
    left: _resolveOne<NonNullable<T.BinaryOperator.Config['left']>>(input.left, _K9, _K10),
    right: _resolveOne<NonNullable<T.BinaryOperator.Config['right']>>(input.right, _K9, _K10),
  });
}

export function unaryOperatorFrom(input: T.UnaryOperator | T.UnaryOperator.Loose): ReturnType<typeof F.unaryOperator> {
  if (isNodeData(input)) return input;
  return F.unaryOperator({
    operator: _resolveOne<NonNullable<T.UnaryOperator.Config['operator']>>(input.operator, _K0, _K0),
    argument: _resolveOne<NonNullable<T.UnaryOperator.Config['argument']>>(input.argument, _K9, _K10),
  });
}

export function comparisonOperatorFrom(input: T.ComparisonOperator | T.ComparisonOperator.Loose): ReturnType<typeof F.comparisonOperator> {
  if (isNodeData(input)) return input;
  const _ne_operators = _resolveMany<NonNullable<T.ComparisonOperator.Config['operators']>[number]>(input.operators, _K11, _K0);
  _assertNonEmpty(_ne_operators, 'comparison_operator.operators');
  return F.comparisonOperator({
    left: _resolveOne<NonNullable<T.ComparisonOperator.Config['left']>>(input.left, _K9, _K10),
    operators: _ne_operators,
  });
}

export function lambdaFrom(input: T.Lambda | T.Lambda.Loose): ReturnType<typeof F.lambda> {
  if (isNodeData(input)) return input;
  return F.lambda({
    parameters: _resolveOneBranch<NonNullable<T.Lambda.Config['parameters']>>(input.parameters, "lambda_parameters"),
    body: _resolveOne<NonNullable<T.Lambda.Config['body']>>(input.body, _K0, _super_expression),
  });
}

export function lambdaWithinForInClauseFrom(input: T.LambdaWithinForInClause | T.LambdaWithinForInClause.Loose): ReturnType<typeof F.lambdaWithinForInClause> {
  if (isNodeData(input)) return input;
  return F.lambdaWithinForInClause({
    parameters: _resolveOneBranch<NonNullable<T.LambdaWithinForInClause.Config['parameters']>>(input.parameters, "lambda_parameters"),
    body: _resolveOne<NonNullable<T.LambdaWithinForInClause.Config['body']>>(input.body, _K0, _super_expression_within_for_in_clause),
  });
}

export function assignmentFrom(input?: T.Assignment | T.Assignment.Loose): ReturnType<typeof F.assignment> {
  if (input !== undefined && isNodeData(input)) return input;
  return F.assignment(input);
}

export function assignmentUFormEqFrom(input: T.AssignmentUFormEqConfig) {
  return F.assignmentUFormEq({
    left: _resolveOne<NonNullable<T.AssignmentUFormEqConfig['left']>>(input.left, _K0, _super_left_hand_side),
  });
}

export function assignmentUFormTypeFrom(input: T.AssignmentUFormTypeConfig) {
  return F.assignmentUFormType({
    left: _resolveOne<NonNullable<T.AssignmentUFormTypeConfig['left']>>(input.left, _K0, _super_left_hand_side),
  });
}

export function assignmentUFormTypedFrom(input: T.AssignmentUFormTypedConfig) {
  return F.assignmentUFormTyped({
    left: _resolveOne<NonNullable<T.AssignmentUFormTypedConfig['left']>>(input.left, _K0, _super_left_hand_side),
  });
}

export function augmentedAssignmentFrom(input: T.AugmentedAssignment | T.AugmentedAssignment.Loose): ReturnType<typeof F.augmentedAssignment> {
  if (isNodeData(input)) return input;
  return F.augmentedAssignment({
    left: _resolveOne<NonNullable<T.AugmentedAssignment.Config['left']>>(input.left, _K0, _super_left_hand_side),
    operator: _resolveOne<NonNullable<T.AugmentedAssignment.Config['operator']>>(input.operator, _K0, _K0),
    right: _resolveOne<NonNullable<T.AugmentedAssignment.Config['right']>>(input.right, _K0, _super_right_hand_side),
  });
}

export function patternListFrom(input: T.PatternList | T.PatternList.Loose): ReturnType<typeof F.patternList> {
  if (isNodeData(input)) return input;
  return F.patternList({
    pattern: _resolveOne<NonNullable<T.PatternList.Config['pattern']>>(input.pattern, _super_keyword_identifier, _K12),
    children: _resolveMany<NonNullable<T.PatternList.Config['children']>[number]>(input.children, _super_keyword_identifier, _K12),
  });
}

export function yield_From(input?: NonNullable<T.Yield.Config['children']>[number] | T.Yield) {
  if (isNodeData(input) && input.$type === 'yield') {
    const data = input;
    const child = data.$children ? data.$children[0] : undefined;
    return F.yield_(child);
  }
  return F.yield_(input);
}

export function attributeFrom(input: T.Attribute | T.Attribute.Loose): ReturnType<typeof F.attribute> {
  if (isNodeData(input)) return input;
  return F.attribute({
    object: _resolveOne<NonNullable<T.Attribute.Config['object']>>(input.object, _K9, _K10),
    attribute: _resolveOneLeaf<NonNullable<T.Attribute.Config['attribute']>>(input.attribute, "identifier"),
  });
}

export function subscriptFrom(input: T.Subscript | T.Subscript.Loose): ReturnType<typeof F.subscript> {
  if (isNodeData(input)) return input;
  const _ne_subscript = _resolveMany<NonNullable<T.Subscript.Config['subscript']>[number]>(input.subscript, _K0, _K13);
  _assertNonEmpty(_ne_subscript, 'subscript.subscript');
  return F.subscript({
    value: _resolveOne<NonNullable<T.Subscript.Config['value']>>(input.value, _K9, _K10),
    subscript: _ne_subscript,
  });
}

export function sliceFrom(input?: T.Slice | T.Slice.Loose): ReturnType<typeof F.slice> {
  if (input !== undefined && isNodeData(input)) return input;
  return F.slice({
    start: _resolveOne<NonNullable<T.Slice.Config['start']>>(input?.start, _K0, _super_expression),
    stop: _resolveOne<NonNullable<T.Slice.Config['stop']>>(input?.stop, _K0, _super_expression),
    step: _resolveOne<NonNullable<T.Slice.Config['step']>>(input?.step, _K0, _super_expression),
  });
}

export function callFrom(input: T.Call | T.Call.Loose): ReturnType<typeof F.call> {
  if (isNodeData(input)) return input;
  return F.call({
    function: _resolveOne<NonNullable<T.Call.Config['function']>>(input.function, _K9, _K10),
    arguments: _resolveOne<NonNullable<T.Call.Config['arguments']>>(input.arguments, _K0, _K14),
  });
}

export function typedParameterFrom(input: T.TypedParameter | T.TypedParameter.Loose): ReturnType<typeof F.typedParameter> {
  if (isNodeData(input)) return input;
  return F.typedParameter({
    type: _resolveOneBranch<NonNullable<T.TypedParameter.Config['type']>>(input.type, "type"),
    children: _resolveOne<NonNullable<T.TypedParameter.Config['children']>>(input.children, _super_keyword_identifier, _K15),
  });
}

export function typeFrom(input?: NonNullable<T.Type.Config['children']>[number] | T.Type) {
  if (isNodeData(input) && input.$type === 'type') {
    const data = input;
    const child = data.$children ? data.$children[0] : undefined;
    return F.type(child);
  }
  return F.type(input);
}

export function splatTypeFrom(input: T.SplatType | T.SplatType.Loose): ReturnType<typeof F.splatType> {
  if (isNodeData(input)) return input;
  return F.splatType({
    identifier: _resolveOneLeaf<NonNullable<T.SplatType.Config['identifier']>>(input.identifier, "identifier"),
  });
}

export function genericTypeFrom(input: T.GenericType | T.GenericType.Loose): ReturnType<typeof F.genericType> {
  if (isNodeData(input)) return input;
  return F.genericType({
    identifier: _resolveOneLeaf<NonNullable<T.GenericType.Config['identifier']>>(input.identifier, "identifier"),
    typeParameter: _resolveOneBranch<NonNullable<T.GenericType.Config['typeParameter']>>(input.typeParameter, "type_parameter"),
  });
}

export function unionTypeFrom(input: T.UnionType | T.UnionType.Loose): ReturnType<typeof F.unionType> {
  if (isNodeData(input)) return input;
  return F.unionType({
    left: _resolveOneBranch<NonNullable<T.UnionType.Config['left']>>(input.left, "type"),
    right: _resolveOneBranch<NonNullable<T.UnionType.Config['right']>>(input.right, "type"),
  });
}

export function constrainedTypeFrom(input: T.ConstrainedType | T.ConstrainedType.Loose): ReturnType<typeof F.constrainedType> {
  if (isNodeData(input)) return input;
  return F.constrainedType({
    baseType: _resolveOneBranch<NonNullable<T.ConstrainedType.Config['baseType']>>(input.baseType, "type"),
    constraint: _resolveOneBranch<NonNullable<T.ConstrainedType.Config['constraint']>>(input.constraint, "type"),
  });
}

export function memberTypeFrom(input: T.MemberType | T.MemberType.Loose): ReturnType<typeof F.memberType> {
  if (isNodeData(input)) return input;
  return F.memberType({
    baseType: _resolveOneBranch<NonNullable<T.MemberType.Config['baseType']>>(input.baseType, "type"),
    identifier: _resolveOneLeaf<NonNullable<T.MemberType.Config['identifier']>>(input.identifier, "identifier"),
  });
}

export function keywordArgumentFrom(input: T.KeywordArgument | T.KeywordArgument.Loose): ReturnType<typeof F.keywordArgument> {
  if (isNodeData(input)) return input;
  return F.keywordArgument({
    name: _resolveOneLeaf<NonNullable<T.KeywordArgument.Config['name']>>(input.name, "identifier"),
    value: _resolveOne<NonNullable<T.KeywordArgument.Config['value']>>(input.value, _K0, _super_expression),
  });
}

export function listFrom(...input: readonly (NonNullable<T.List.Config['children']>[number] | T.List)[]) {
  if (input.length === 1 && isNodeData(input[0]) && input[0].$type === 'list') {
    const data = input[0];
    return F.list(...(data.$children ?? []));
  }
  return F.list(...input);
}

export function setFrom(...input: readonly (NonNullable<T.Set.Config['children']>[number] | T.Set)[]) {
  if (input.length === 1 && isNodeData(input[0]) && input[0].$type === 'set') {
    const data = input[0];
    return F.set(...(data.$children ?? []));
  }
  return F.set(...input);
}

export function tupleFrom(...input: readonly (NonNullable<T.Tuple.Config['children']>[number] | T.Tuple)[]) {
  if (input.length === 1 && isNodeData(input[0]) && input[0].$type === 'tuple') {
    const data = input[0];
    return F.tuple(...(data.$children ?? []));
  }
  return F.tuple(...input);
}

export function dictionaryFrom(...input: readonly (NonNullable<T.Dictionary.Config['children']>[number] | T.Dictionary)[]) {
  if (input.length === 1 && isNodeData(input[0]) && input[0].$type === 'dictionary') {
    const data = input[0];
    return F.dictionary(...(data.$children ?? []));
  }
  return F.dictionary(...input);
}

export function pairFrom(input: T.Pair | T.Pair.Loose): ReturnType<typeof F.pair> {
  if (isNodeData(input)) return input;
  return F.pair({
    key: _resolveOne<NonNullable<T.Pair.Config['key']>>(input.key, _K0, _super_expression),
    value: _resolveOne<NonNullable<T.Pair.Config['value']>>(input.value, _K0, _super_expression),
  });
}

export function listComprehensionFrom(input: T.ListComprehension | T.ListComprehension.Loose): ReturnType<typeof F.listComprehension> {
  if (isNodeData(input)) return input;
  return F.listComprehension({
    body: _resolveOne<NonNullable<T.ListComprehension.Config['body']>>(input.body, _K0, _super_expression),
    forInClause: _resolveOneBranch<NonNullable<T.ListComprehension.Config['forInClause']>>(input.forInClause, "for_in_clause"),
    children: _resolveMany<NonNullable<T.ListComprehension.Config['children']>[number]>(input.children, _K0, _K16),
  });
}

export function dictionaryComprehensionFrom(input: T.DictionaryComprehension | T.DictionaryComprehension.Loose): ReturnType<typeof F.dictionaryComprehension> {
  if (isNodeData(input)) return input;
  return F.dictionaryComprehension({
    body: _resolveOneBranch<NonNullable<T.DictionaryComprehension.Config['body']>>(input.body, "pair"),
    forInClause: _resolveOneBranch<NonNullable<T.DictionaryComprehension.Config['forInClause']>>(input.forInClause, "for_in_clause"),
    children: _resolveMany<NonNullable<T.DictionaryComprehension.Config['children']>[number]>(input.children, _K0, _K16),
  });
}

export function setComprehensionFrom(input: T.SetComprehension | T.SetComprehension.Loose): ReturnType<typeof F.setComprehension> {
  if (isNodeData(input)) return input;
  return F.setComprehension({
    body: _resolveOne<NonNullable<T.SetComprehension.Config['body']>>(input.body, _K0, _super_expression),
    forInClause: _resolveOneBranch<NonNullable<T.SetComprehension.Config['forInClause']>>(input.forInClause, "for_in_clause"),
    children: _resolveMany<NonNullable<T.SetComprehension.Config['children']>[number]>(input.children, _K0, _K16),
  });
}

export function generatorExpressionFrom(input: T.GeneratorExpression | T.GeneratorExpression.Loose): ReturnType<typeof F.generatorExpression> {
  if (isNodeData(input)) return input;
  return F.generatorExpression({
    body: _resolveOne<NonNullable<T.GeneratorExpression.Config['body']>>(input.body, _K0, _super_expression),
    forInClause: _resolveOneBranch<NonNullable<T.GeneratorExpression.Config['forInClause']>>(input.forInClause, "for_in_clause"),
    children: _resolveMany<NonNullable<T.GeneratorExpression.Config['children']>[number]>(input.children, _K0, _K16),
  });
}

export function parenthesizedExpressionFrom(input?: NonNullable<T.ParenthesizedExpression.Config['children']>[number] | T.ParenthesizedExpression) {
  if (isNodeData(input) && input.$type === 'parenthesized_expression') {
    const data = input;
    const child = data.$children ? data.$children[0] : undefined;
    return F.parenthesizedExpression(child);
  }
  return F.parenthesizedExpression(input);
}

export function forInClauseFrom(input: T.ForInClause | T.ForInClause.Loose): ReturnType<typeof F.forInClause> {
  if (isNodeData(input)) return input;
  const _ne_right = _resolveMany<NonNullable<T.ForInClause.Config['right']>[number]>(input.right, _K0, _super_expression_within_for_in_clause);
  _assertNonEmpty(_ne_right, 'for_in_clause.right');
  return F.forInClause({
    async: _resolveOneLeaf<NonNullable<T.ForInClause.Config['async']>>(input.async, "_kw_async"),
    left: _resolveOne<NonNullable<T.ForInClause.Config['left']>>(input.left, _K0, _super_left_hand_side),
    right: _ne_right,
  });
}

export function ifClauseFrom(input: T.IfClause | T.IfClause.Loose): ReturnType<typeof F.ifClause> {
  if (isNodeData(input)) return input;
  return F.ifClause({
    expression: _resolveOne<NonNullable<T.IfClause.Config['expression']>>(input.expression, _K0, _super_expression),
  });
}

export function conditionalExpressionFrom(input: T.ConditionalExpression | T.ConditionalExpression.Loose): ReturnType<typeof F.conditionalExpression> {
  if (isNodeData(input)) return input;
  return F.conditionalExpression({
    body: _resolveOne<NonNullable<T.ConditionalExpression.Config['body']>>(input.body, _K0, _super_expression),
    condition: _resolveOne<NonNullable<T.ConditionalExpression.Config['condition']>>(input.condition, _K0, _super_expression),
    alternative: _resolveOne<NonNullable<T.ConditionalExpression.Config['alternative']>>(input.alternative, _K0, _super_expression),
  });
}

export function concatenatedStringFrom(input: T.ConcatenatedString | T.ConcatenatedString.Loose): ReturnType<typeof F.concatenatedString> {
  if (isNodeData(input)) return input;
  const _ne_children = _resolveManyBranch<NonNullable<T.ConcatenatedString.Config['children']>[number]>(input.children, "string");
  _assertNonEmpty(_ne_children, 'concatenated_string.children');
  return F.concatenatedString({
    string: _resolveOneBranch<NonNullable<T.ConcatenatedString.Config['string']>>(input.string, "string"),
    children: _ne_children,
  });
}

export function stringFrom(input: T.String | T.String.Loose): ReturnType<typeof F.string> {
  if (isNodeData(input)) return input;
  return F.string({
    stringStart: _resolveOneLeaf<NonNullable<T.String.Config['stringStart']>>(input.stringStart, "string_start"),
    content: _resolveMany<NonNullable<T.String.Config['content']>[number]>(input.content, _K0, _K17),
    stringEnd: _resolveOneLeaf<NonNullable<T.String.Config['stringEnd']>>(input.stringEnd, "string_end"),
  });
}

export function stringContentFrom(...input: readonly (NonNullable<T.StringContent.Config['children']>[number] | T.StringContent)[]) {
  if (input.length === 1 && isNodeData(input[0]) && input[0].$type === 'string_content') {
    const data = input[0];
    return F.stringContent(...(data.$children ?? []));
  }
  return F.stringContent(...input);
}

export function interpolationFrom(input: T.Interpolation | T.Interpolation.Loose): ReturnType<typeof F.interpolation> {
  if (isNodeData(input)) return input;
  return F.interpolation({
    expression: _resolveOne<NonNullable<T.Interpolation.Config['expression']>>(input.expression, _K0, _super_f_expression),
    typeConversion: _resolveOneLeaf<NonNullable<T.Interpolation.Config['typeConversion']>>(input.typeConversion, "type_conversion"),
    formatSpecifier: _resolveOneBranch<NonNullable<T.Interpolation.Config['formatSpecifier']>>(input.formatSpecifier, "format_specifier"),
  });
}

export function escapeSequenceFrom(input: string | T.EscapeSequence) {
  if (isNodeData(input)) return input;
  return F.escapeSequence(input);
}

export function formatSpecifierFrom(...input: readonly (NonNullable<T.FormatSpecifier.Config['children']>[number] | T.FormatSpecifier)[]) {
  if (input.length === 1 && isNodeData(input[0]) && input[0].$type === 'format_specifier') {
    const data = input[0];
    return F.formatSpecifier(...(data.$children ?? []));
  }
  return F.formatSpecifier(...input);
}

export function typeConversionFrom(input: string | T.TypeConversion) {
  if (isNodeData(input)) return input;
  return F.typeConversion(input);
}

export function integerFrom(input: string | T.Integer) {
  if (isNodeData(input)) return input;
  return F.integer(input);
}

export function floatFrom(input: string | T.Float) {
  if (isNodeData(input)) return input;
  return F.float(input);
}

export function identifierFrom(input: string | T.Identifier) {
  if (isNodeData(input)) return input;
  return F.identifier(input);
}

export function true_From(input?: T.True) {
  if (isNodeData(input)) return input;
  return F.true_();
}

export function false_From(input?: T.False) {
  if (isNodeData(input)) return input;
  return F.false_();
}

export function noneFrom(input?: T.None) {
  if (isNodeData(input)) return input;
  return F.none();
}

export function await_From(input: T.Await | T.Await.Loose): ReturnType<typeof F.await_> {
  if (isNodeData(input)) return input;
  return F.await_({
    primaryExpression: _resolveOne<NonNullable<T.Await.Config['primaryExpression']>>(input.primaryExpression, _K9, _K10),
  });
}

export function commentFrom(input: string | T.Comment) {
  if (isNodeData(input)) return input;
  return F.comment(input);
}

export function lineContinuationFrom(input: string | T.LineContinuation) {
  if (isNodeData(input)) return input;
  return F.lineContinuation(input);
}

export function stringStartFrom(input: string | T.StringStart) {
  if (isNodeData(input)) return input;
  return F.stringStart(input);
}

export function escapeInterpolationFrom(input: string | T.EscapeInterpolation) {
  if (isNodeData(input)) return input;
  return F.escapeInterpolation(input);
}

export function stringEndFrom(input: string | T.StringEnd) {
  if (isNodeData(input)) return input;
  return F.stringEnd(input);
}

export function closeBracketFrom(input: string | T.CloseBracket) {
  if (isNodeData(input)) return input;
  return F.closeBracket(input);
}

export function closeParenFrom(input: string | T.CloseParen) {
  if (isNodeData(input)) return input;
  return F.closeParen(input);
}

export function closeBraceFrom(input: string | T.CloseBrace) {
  if (isNodeData(input)) return input;
  return F.closeBrace(input);
}

export function exceptFrom(input: string | T.Except) {
  if (isNodeData(input)) return input;
  return F.except(input);
}

export function asPatternTargetFrom(input?: NonNullable<T.AsPatternTarget.Config['children']>[number] | T.AsPatternTarget) {
  if (isNodeData(input) && input.$type === 'as_pattern_target') {
    const data = input;
    const child = data.$children ? data.$children[0] : undefined;
    return F.asPatternTarget(child);
  }
  return F.asPatternTarget(input);
}

export function assignmentEqFrom(input: T.AssignmentEq | T.AssignmentEq.Loose): ReturnType<typeof F.assignmentEq> {
  if (isNodeData(input)) return input;
  return F.assignmentEq({
    right: _resolveOne<NonNullable<T.AssignmentEq.Config['right']>>(input.right, _K0, _super_right_hand_side),
  });
}

export function assignmentTypeFrom(input: T.AssignmentType | T.AssignmentType.Loose): ReturnType<typeof F.assignmentType> {
  if (isNodeData(input)) return input;
  return F.assignmentType({
    type: _resolveOneBranch<NonNullable<T.AssignmentType.Config['type']>>(input.type, "type"),
  });
}

export function assignmentTypedFrom(input: T.AssignmentTyped | T.AssignmentTyped.Loose): ReturnType<typeof F.assignmentTyped> {
  if (isNodeData(input)) return input;
  return F.assignmentTyped({
    type: _resolveOneBranch<NonNullable<T.AssignmentTyped.Config['type']>>(input.type, "type"),
    right: _resolveOne<NonNullable<T.AssignmentTyped.Config['right']>>(input.right, _K0, _super_right_hand_side),
  });
}

export function formatExpressionFrom(input: T.FormatExpression | T.FormatExpression.Loose): ReturnType<typeof F.formatExpression> {
  if (isNodeData(input)) return input;
  return F.formatExpression({
    expression: _resolveOne<NonNullable<T.FormatExpression.Config['expression']>>(input.expression, _K0, _super_f_expression),
    typeConversion: _resolveOneLeaf<NonNullable<T.FormatExpression.Config['typeConversion']>>(input.typeConversion, "type_conversion"),
    formatSpecifier: _resolveOneBranch<NonNullable<T.FormatExpression.Config['formatSpecifier']>>(input.formatSpecifier, "format_specifier"),
  });
}
