// Auto-generated by @sittir/codegen — do not edit

import type { Language } from '@sittir/types';
import type { PythonAPI } from './api.js';

export type { PythonAPI } from './api.js';

const python: Language<PythonAPI> = {
	name: 'python',
	fileTypes: ['py'],
	load: () => import('./api.js').then((m) => m.hooks),
	createEngine: (options) => import('@sittir/common').then((m) => m.createEngine(python, options))
};
export default python;

export type * from './types.js';
export type * from './options.js';
export type { IsGuards } from './is.js';
export type { CSTNode } from '@sittir/types';
