// Auto-generated by @sittir/codegen — do not edit
// Lazy view layer over readNode output — shape A surface.

import { readNode as readNodeJs } from '@sittir/common';
import type { TreeHandle } from '@sittir/common';
// Import _NodeData (== AnyNodeData) from @sittir/types
// instead of re-declaring locally. Single source of truth.
import type { AnyNodeData as _NodeData, AnyNodeData, NonEmptyArray } from '@sittir/types';
import { TSKindId } from './types.js';
import type * as T from './types.js';
import { withMethods, coerceBooleanKeywordStorage, coerceBitflagStorage } from './utils.js';
import * as _factories from './factories.js';

// Drill-in helpers — call back through `readTreeNode` so the same
// per-handle dispatch + wrap pipeline runs at every level. Layering:
//   readTreeNode (public entry)
//     → readNode (handle-driven — tree.read for native, JS walker otherwise)
//       → wrapNode (dispatches on $type)
//         → drillIn / drillAs → readTreeNode (recurse)
function drillIn<T>(entry: T, tree: TreeHandle): T {
  if (!entry) return undefined as unknown as T;
  const e = entry as unknown as _NodeData;
  if (e.$nodeHandle != null && e.$childIndex != null) return readTreeNode(tree, e.$nodeHandle, e.$childIndex) as unknown as T;
  return entry;
}
function drillInAll<T>(entries: readonly T[] | undefined, tree: TreeHandle): T[] {
  if (!entries) return [];
  const arr = Array.isArray(entries) ? entries : [entries];
  return arr.map(e => drillIn(e, tree));
}
// drillAs — field-site unalias for grammar `alias($.source, $.target)`
// declarations. The `asType` override rewrites $type from
// tree-sitter's alias target back to the codegen-canonical source
// name between the read and the wrap. Conditional rewrite: only
// fires when the child's actual $type matches `fromType`; mixed-
// union fields (e.g. Path | BracketedType | GenericTypeWithTurbofish)
// pass through unchanged when the child arrived as a non-alias kind.
function drillAs<T>(entry: unknown, tree: TreeHandle, fromType: string, toType: string): T {
  if (!entry) return undefined as unknown as T;
  const e = entry as _NodeData;
  if (e.$nodeHandle == null || e.$childIndex == null) return entry as unknown as T;
  return readTreeNode(tree, e.$nodeHandle, e.$childIndex, { from: fromType, to: toType }) as unknown as T;
}
function projectKindEnumStorage<T>(value: T): T {
  if (!value) return value;
  if (Array.isArray(value)) return value.map(entry => projectKindEnumStorage(entry)) as unknown as T;
  const entry = value as unknown as _NodeData;
  return typeof entry.$type === "number" ? (entry.$type as T) : value;
}

export function wrap_AsPattern(data: T._AsPattern, tree: TreeHandle) {
  const _node = withMethods({
    ...data,
    $type: TSKindId._AsPattern as const,
    $children: data.$children,

    $with: { $child: (v: (T.CasePattern | T.Identifier)) => wrap_AsPattern({ ...data, $children: [v] }, tree) },
  });
  return _node;
}

export function wrapComprehensionClauses(data: T.ComprehensionClauses, tree: TreeHandle) {
  const _node = withMethods({
    ...data,
    $type: TSKindId.ComprehensionClauses as const,
    $children: data.$children,

    $with: { $children: (...vs: ((T.ForInClause | T.IfClause))[]) => wrapComprehensionClauses({ ...data, $children: vs }, tree) },
  });
  return _node;
}

export function wrap_ListPattern(data: T._ListPattern, tree: TreeHandle) {
  const _node = withMethods({
    ...data,
    $type: TSKindId._ListPattern as const,
    $children: data.$children,

    $with: { $children: (...vs: T.CasePattern[]) => wrap_ListPattern({ ...data, $children: vs }, tree) },
  });
  return _node;
}

export function wrapMatchBlock(data: T.MatchBlock, tree: TreeHandle) {
  const _node = withMethods({
    ...data,
    $type: TSKindId.MatchBlock as const,
    $children: data.$children,

    $with: { $child: (v: T.MatchBlockBlock) => wrapMatchBlock({ ...data, $children: [v] }, tree) },
  });
  return _node;
}

export function wrapSimplePatternNegative(data: T.SimplePatternNegative, tree: TreeHandle) {
  const _node = withMethods({
    ...data,
    $type: TSKindId.SimplePatternNegative as const,
    $children: data.$children,

    $with: { $child: (v: (T.Integer | T.Float)) => wrapSimplePatternNegative({ ...data, $children: [v] }, tree) },
  });
  return _node;
}

export function wrapSimpleStatements(data: T.SimpleStatements, tree: TreeHandle) {
  const _node = withMethods({
    ...data,
    $type: TSKindId.SimpleStatements as const,
    $children: data.$children,

    $with: { $children: (...vs: NonEmptyArray<T.SimpleStatement>) => wrapSimpleStatements({ ...data, $children: vs }, tree) },
  });
  return _node;
}

export function wrap_TuplePattern(data: T._TuplePattern, tree: TreeHandle) {
  const _node = withMethods({
    ...data,
    $type: TSKindId._TuplePattern as const,
    $children: data.$children,

    $with: { $children: (...vs: T.CasePattern[]) => wrap_TuplePattern({ ...data, $children: vs }, tree) },
  });
  return _node;
}

export function wrap_WithClauseParen(data: T._WithClauseParen, tree: TreeHandle) {
  const _node = withMethods({
    ...data,
    $type: TSKindId._WithClauseParen as const,
    $children: data.$children,

    $with: { $children: (...vs: NonEmptyArray<T.WithItem>) => wrap_WithClauseParen({ ...data, $children: vs }, tree) },
  });
  return _node;
}

export function wrapAliasedImport(data: T.AliasedImport, tree: TreeHandle) {
  const _node = withMethods({
    ...data,
    $type: TSKindId.AliasedImport as const,
    _name: data._name,
    _alias: data._alias,

    name() { return drillIn<T.DottedName>(this._name, tree); },
    alias() { return drillIn<T.Identifier>(this._alias, tree); },
    $with: {
      name: (v: NonNullable<T.AliasedImport['_name']>) => wrapAliasedImport({ ...data, _name: v }, tree),
      alias: (v: NonNullable<T.AliasedImport['_alias']>) => wrapAliasedImport({ ...data, _alias: v }, tree),
    },
  });
  return _node;
}

export function wrapArgumentList(data: T.ArgumentList, tree: TreeHandle) {
  const _node = withMethods({
    ...data,
    $type: TSKindId.ArgumentList as const,
    $children: data.$children,

    $with: { $children: (...vs: ((T.Expression | T.ListSplat | T.DictionarySplat | T.ParenthesizedListSplat | T.KeywordArgument))[]) => wrapArgumentList({ ...data, $children: vs }, tree) },
  });
  return _node;
}

export function wrapAsPattern(data: T.AsPattern, tree: TreeHandle) {
  const _node = withMethods({
    ...data,
    $type: TSKindId.AsPattern as const,
    _expression: data._expression,
    _alias: data._alias,

    expression() { return drillIn<T.Expression>(this._expression, tree); },
    alias() { return drillIn<T.AsPatternTarget>(this._alias, tree); },
    $with: {
      expression: (v: NonNullable<T.AsPattern['_expression']>) => wrapAsPattern({ ...data, _expression: v }, tree),
      alias: (v: NonNullable<T.AsPattern['_alias']>) => wrapAsPattern({ ...data, _alias: v }, tree),
    },
  });
  return _node;
}

export function wrapAssertStatement(data: T.AssertStatement, tree: TreeHandle) {
  const _node = withMethods({
    ...data,
    $type: TSKindId.AssertStatement as const,
    $children: data.$children,

    $with: { $children: (...vs: NonEmptyArray<T.Expression>) => wrapAssertStatement({ ...data, $children: vs }, tree) },
  });
  return _node;
}

export function wrapAssignment(data: T.Assignment, tree: TreeHandle) {
  const _node = withMethods({
    ...data,
    $type: TSKindId.Assignment as const,
    _left: (data as any)._left,
    $children: (data as any).$children,

    left() { return drillIn<T.LeftHandSide>(this._left, tree); },
    $with: {
      left: (v: T.LeftHandSide) => wrapAssignment({ ...(data as any), _left: v }, tree),
      children: (...items: readonly [((T.AssignmentEq | T.AssignmentType | T.AssignmentTyped))]) => wrapAssignment({ ...(data as any), $children: items }, tree),
    },
  });
  return _node;
}

export function wrapAttribute(data: T.Attribute, tree: TreeHandle) {
  const _node = withMethods({
    ...data,
    $type: TSKindId.Attribute as const,
    _object: data._object,
    _attribute: data._attribute,

    object() { return drillIn<T.PrimaryExpression>(this._object, tree); },
    attribute() { return drillIn<T.Identifier>(this._attribute, tree); },
    $with: {
      object: (v: NonNullable<T.Attribute['_object']>) => wrapAttribute({ ...data, _object: v }, tree),
      attribute: (v: NonNullable<T.Attribute['_attribute']>) => wrapAttribute({ ...data, _attribute: v }, tree),
    },
  });
  return _node;
}

export function wrapAugmentedAssignment(data: T.AugmentedAssignment, tree: TreeHandle) {
  const _node = withMethods({
    ...data,
    $type: TSKindId.AugmentedAssignment as const,
    _left: data._left,
    _operator: projectKindEnumStorage(data._operator),
    _right: data._right,

    left() { return drillIn<T.LeftHandSide>(this._left, tree); },
    operator() { return this._operator; },
    right() { return drillIn<T.RightHandSide>(this._right, tree); },
    $with: {
      left: (v: NonNullable<T.AugmentedAssignment['_left']>) => wrapAugmentedAssignment({ ...data, _left: v }, tree),
      operator: (v: NonNullable<T.AugmentedAssignment['_operator']>) => wrapAugmentedAssignment({ ...data, _operator: v }, tree),
      right: (v: NonNullable<T.AugmentedAssignment['_right']>) => wrapAugmentedAssignment({ ...data, _right: v }, tree),
    },
  });
  return _node;
}

export function wrapAwait(data: T.Await, tree: TreeHandle) {
  const _node = withMethods({
    ...data,
    $type: TSKindId.Await as const,
    _primary_expression: data._primary_expression,

    primaryExpression() { return drillIn<T.PrimaryExpression>(this._primary_expression, tree); },
    $with: {
      primaryExpression: (v: NonNullable<T.Await['_primary_expression']>) => wrapAwait({ ...data, _primary_expression: v }, tree),
    },
  });
  return _node;
}

export function wrapBinaryOperator(data: T.BinaryOperator, tree: TreeHandle) {
  const _node = withMethods({
    ...data,
    $type: TSKindId.BinaryOperator as const,
    _left: data._left,
    _operator: data._operator,
    _right: data._right,

    left() { return drillIn<T.PrimaryExpression>(this._left, tree); },
    operator() { return drillIn<"+">(this._operator, tree); },
    right() { return drillIn<T.PrimaryExpression>(this._right, tree); },
    $with: {
      left: (v: NonNullable<T.BinaryOperator['_left']>) => wrapBinaryOperator({ ...data, _left: v }, tree),
      operator: (v: NonNullable<T.BinaryOperator['_operator']>) => wrapBinaryOperator({ ...data, _operator: v }, tree),
      right: (v: NonNullable<T.BinaryOperator['_right']>) => wrapBinaryOperator({ ...data, _right: v }, tree),
    },
  });
  return _node;
}

export function wrapBlock(data: T.Block, tree: TreeHandle) {
  const _node = withMethods({
    ...data,
    $type: TSKindId.Block as const,
    $children: data.$children,

    $with: { $children: (...vs: T.Statement[]) => wrapBlock({ ...data, $children: vs }, tree) },
  });
  return _node;
}

export function wrapBooleanOperator(data: T.BooleanOperator, tree: TreeHandle) {
  const _node = withMethods({
    ...data,
    $type: TSKindId.BooleanOperator as const,
    _left: data._left,
    _operator: data._operator,
    _right: data._right,

    left() { return drillIn<T.Expression>(this._left, tree); },
    operator() { return drillIn<"and">(this._operator, tree); },
    right() { return drillIn<T.Expression>(this._right, tree); },
    $with: {
      left: (v: NonNullable<T.BooleanOperator['_left']>) => wrapBooleanOperator({ ...data, _left: v }, tree),
      operator: (v: NonNullable<T.BooleanOperator['_operator']>) => wrapBooleanOperator({ ...data, _operator: v }, tree),
      right: (v: NonNullable<T.BooleanOperator['_right']>) => wrapBooleanOperator({ ...data, _right: v }, tree),
    },
  });
  return _node;
}

export function wrapCall(data: T.Call, tree: TreeHandle) {
  const _node = withMethods({
    ...data,
    $type: TSKindId.Call as const,
    _function: data._function,
    _arguments: data._arguments,

    function() { return drillIn<T.PrimaryExpression>(this._function, tree); },
    arguments() { return drillIn<T.GeneratorExpression | T.ArgumentList>(this._arguments, tree); },
    $with: {
      function: (v: NonNullable<T.Call['_function']>) => wrapCall({ ...data, _function: v }, tree),
      arguments: (v: NonNullable<T.Call['_arguments']>) => wrapCall({ ...data, _arguments: v }, tree),
    },
  });
  return _node;
}

export function wrapCaseClause(data: T.CaseClause, tree: TreeHandle) {
  const _node = withMethods({
    ...data,
    $type: TSKindId.CaseClause as const,
    _guard: data._guard,
    _consequence: data._consequence,
    $children: data.$children,

    guard() { return drillIn<T.IfClause | undefined>(this._guard, tree); },
    consequence() { return drillIn<T.Suite>(this._consequence, tree); },
    $with: {
      guard: (v: NonNullable<T.CaseClause['_guard']>) => wrapCaseClause({ ...data, _guard: v }, tree),
      consequence: (v: NonNullable<T.CaseClause['_consequence']>) => wrapCaseClause({ ...data, _consequence: v }, tree),
      children: (...items: NonEmptyArray<T.CasePattern>) => wrapCaseClause({ ...data, $children: items }, tree),
    },
  });
  return _node;
}

export function wrapCasePattern(data: T.CasePattern, tree: TreeHandle) {
  const _node = withMethods({
    ...data,
    $type: TSKindId.CasePattern as const,
    $children: data.$children,

    $with: { $child: (v: (T._AsPattern | T.KeywordPattern | T.SimplePattern)) => wrapCasePattern({ ...data, $children: [v] }, tree) },
  });
  return _node;
}

export function wrapChevron(data: T.Chevron, tree: TreeHandle) {
  const _node = withMethods({
    ...data,
    $type: TSKindId.Chevron as const,
    _expression: data._expression,

    expression() { return drillIn<T.Expression>(this._expression, tree); },
    $with: {
      expression: (v: NonNullable<T.Chevron['_expression']>) => wrapChevron({ ...data, _expression: v }, tree),
    },
  });
  return _node;
}

export function wrapClassDefinition(data: T.ClassDefinition, tree: TreeHandle) {
  const _node = withMethods({
    ...data,
    $type: TSKindId.ClassDefinition as const,
    _name: data._name,
    _type_parameters: data._type_parameters,
    _superclasses: data._superclasses,
    _body: data._body,

    name() { return drillIn<T.Identifier>(this._name, tree); },
    typeParameters() { return drillIn<T.TypeParameter | undefined>(this._type_parameters, tree); },
    superclasses() { return drillIn<T.ArgumentList | undefined>(this._superclasses, tree); },
    body() { return drillIn<T.Suite>(this._body, tree); },
    $with: {
      name: (v: NonNullable<T.ClassDefinition['_name']>) => wrapClassDefinition({ ...data, _name: v }, tree),
      typeParameters: (v: NonNullable<T.ClassDefinition['_type_parameters']>) => wrapClassDefinition({ ...data, _type_parameters: v }, tree),
      superclasses: (v: NonNullable<T.ClassDefinition['_superclasses']>) => wrapClassDefinition({ ...data, _superclasses: v }, tree),
      body: (v: NonNullable<T.ClassDefinition['_body']>) => wrapClassDefinition({ ...data, _body: v }, tree),
    },
  });
  return _node;
}

export function wrapClassPattern(data: T.ClassPattern, tree: TreeHandle) {
  const _node = withMethods({
    ...data,
    $type: TSKindId.ClassPattern as const,
    _dotted_name: data._dotted_name,
    _arguments: data._arguments,

    dottedName() { return drillIn<T.DottedName>(this._dotted_name, tree); },
    arguments() { return drillInAll<T.CasePattern>(this._arguments, tree); },
    $with: {
      dottedName: (v: NonNullable<T.ClassPattern['_dotted_name']>) => wrapClassPattern({ ...data, _dotted_name: v }, tree),
      arguments: (...v: NonNullable<T.ClassPattern['_arguments']>[number][]) => wrapClassPattern({ ...data, _arguments: v }, tree),
    },
  });
  return _node;
}

export function wrapComparisonOperator(data: T.ComparisonOperator, tree: TreeHandle) {
  const _node = withMethods({
    ...data,
    $type: TSKindId.ComparisonOperator as const,
    _left: data._left,
    _operators: coerceBitflagStorage(data._operators, ["<", "<=", "==", "!=", ">=", ">", "<>", "in", "not in", "is", "is not"]),
    $children: data.$children,

    left() { return drillIn<T.PrimaryExpression>(this._left, tree); },
    operators() { return this._operators; },
    $with: {
      left: (v: NonNullable<T.ComparisonOperator['_left']>) => wrapComparisonOperator({ ...data, _left: v }, tree),
      operators: (v: NonNullable<T.ComparisonOperator['_operators']>) => wrapComparisonOperator({ ...data, _operators: v }, tree),
      children: (...items: NonEmptyArray<T.PrimaryExpression>) => wrapComparisonOperator({ ...data, $children: items }, tree),
    },
  });
  return _node;
}

export function wrapComplexPattern(data: T.ComplexPattern, tree: TreeHandle) {
  const _node = withMethods({
    ...data,
    $type: TSKindId.ComplexPattern as const,
    _real: coerceBooleanKeywordStorage(data._real),
    _imaginary: data._imaginary,
    $children: data.$children,

    real() { return this._real; },
    imaginary() { return drillIn<T.Integer | T.Float>(this._imaginary, tree); },
    $with: {
      real: (v: NonNullable<T.ComplexPattern['_real']>) => wrapComplexPattern({ ...data, _real: v }, tree),
      imaginary: (v: NonNullable<T.ComplexPattern['_imaginary']>) => wrapComplexPattern({ ...data, _imaginary: v }, tree),
      children: (...items: readonly [((T.Integer | T.Float))]) => wrapComplexPattern({ ...data, $children: items }, tree),
    },
  });
  return _node;
}

export function wrapConcatenatedString(data: T.ConcatenatedString, tree: TreeHandle) {
  const _node = withMethods({
    ...data,
    $type: TSKindId.ConcatenatedString as const,
    $children: data.$children,

    $with: { $children: (...vs: NonEmptyArray<T.String>) => wrapConcatenatedString({ ...data, $children: vs }, tree) },
  });
  return _node;
}

export function wrapConditionalExpression(data: T.ConditionalExpression, tree: TreeHandle) {
  const _node = withMethods({
    ...data,
    $type: TSKindId.ConditionalExpression as const,
    _body: data._body,
    _condition: data._condition,
    _alternative: data._alternative,

    body() { return drillIn<T.Expression>(this._body, tree); },
    condition() { return drillIn<T.Expression>(this._condition, tree); },
    alternative() { return drillIn<T.Expression>(this._alternative, tree); },
    $with: {
      body: (v: NonNullable<T.ConditionalExpression['_body']>) => wrapConditionalExpression({ ...data, _body: v }, tree),
      condition: (v: NonNullable<T.ConditionalExpression['_condition']>) => wrapConditionalExpression({ ...data, _condition: v }, tree),
      alternative: (v: NonNullable<T.ConditionalExpression['_alternative']>) => wrapConditionalExpression({ ...data, _alternative: v }, tree),
    },
  });
  return _node;
}

export function wrapConstrainedType(data: T.ConstrainedType, tree: TreeHandle) {
  const _node = withMethods({
    ...data,
    $type: TSKindId.ConstrainedType as const,
    _base_type: data._base_type,
    _constraint: data._constraint,

    baseType() { return drillIn<T.Type>(this._base_type, tree); },
    constraint() { return drillIn<T.Type>(this._constraint, tree); },
    $with: {
      baseType: (v: NonNullable<T.ConstrainedType['_base_type']>) => wrapConstrainedType({ ...data, _base_type: v }, tree),
      constraint: (v: NonNullable<T.ConstrainedType['_constraint']>) => wrapConstrainedType({ ...data, _constraint: v }, tree),
    },
  });
  return _node;
}

export function wrapDecoratedDefinition(data: T.DecoratedDefinition, tree: TreeHandle) {
  const _node = withMethods({
    ...data,
    $type: TSKindId.DecoratedDefinition as const,
    _definition: data._definition,
    $children: data.$children,

    definition() { return drillIn<T.ClassDefinition | T.FunctionDefinition>(this._definition, tree); },
    $with: {
      definition: (v: NonNullable<T.DecoratedDefinition['_definition']>) => wrapDecoratedDefinition({ ...data, _definition: v }, tree),
      children: (...items: NonEmptyArray<T.Decorator>) => wrapDecoratedDefinition({ ...data, $children: items }, tree),
    },
  });
  return _node;
}

export function wrapDecorator(data: T.Decorator, tree: TreeHandle) {
  const _node = withMethods({
    ...data,
    $type: TSKindId.Decorator as const,
    _expression: data._expression,
    _newline: data._newline,

    expression() { return drillIn<T.Expression>(this._expression, tree); },
    newline() { return drillIn<string | undefined>(this._newline, tree); },
    $with: {
      expression: (v: NonNullable<T.Decorator['_expression']>) => wrapDecorator({ ...data, _expression: v }, tree),
      newline: (v: NonNullable<T.Decorator['_newline']>) => wrapDecorator({ ...data, _newline: v }, tree),
    },
  });
  return _node;
}

export function wrapDefaultParameter(data: T.DefaultParameter, tree: TreeHandle) {
  const _node = withMethods({
    ...data,
    $type: TSKindId.DefaultParameter as const,
    _name: data._name,
    _value: data._value,

    name() { return drillIn<T.Identifier | T.TuplePattern>(this._name, tree); },
    value() { return drillIn<T.Expression>(this._value, tree); },
    $with: {
      name: (v: NonNullable<T.DefaultParameter['_name']>) => wrapDefaultParameter({ ...data, _name: v }, tree),
      value: (v: NonNullable<T.DefaultParameter['_value']>) => wrapDefaultParameter({ ...data, _value: v }, tree),
    },
  });
  return _node;
}

export function wrapDeleteStatement(data: T.DeleteStatement, tree: TreeHandle) {
  const _node = withMethods({
    ...data,
    $type: TSKindId.DeleteStatement as const,
    $children: data.$children,

    $with: { $child: (v: T.Expressions) => wrapDeleteStatement({ ...data, $children: [v] }, tree) },
  });
  return _node;
}

export function wrapDictPattern(data: T.DictPattern, tree: TreeHandle) {
  const _node = withMethods({
    ...data,
    $type: TSKindId.DictPattern as const,
    $children: data.$children,

    $with: { $children: (...vs: T.DictPatternKv[]) => wrapDictPattern({ ...data, $children: vs }, tree) },
  });
  return _node;
}

export function wrapDictionary(data: T.Dictionary, tree: TreeHandle) {
  const _node = withMethods({
    ...data,
    $type: TSKindId.Dictionary as const,
    $children: data.$children,

    $with: { $children: (...vs: ((T.Pair | T.DictionarySplat))[]) => wrapDictionary({ ...data, $children: vs }, tree) },
  });
  return _node;
}

export function wrapDictionaryComprehension(data: T.DictionaryComprehension, tree: TreeHandle) {
  const _node = withMethods({
    ...data,
    $type: TSKindId.DictionaryComprehension as const,
    _body: data._body,
    $children: data.$children,

    body() { return drillIn<T.Pair>(this._body, tree); },
    $with: {
      body: (v: NonNullable<T.DictionaryComprehension['_body']>) => wrapDictionaryComprehension({ ...data, _body: v }, tree),
      children: (...items: readonly [T.ComprehensionClauses]) => wrapDictionaryComprehension({ ...data, $children: items }, tree),
    },
  });
  return _node;
}

export function wrapDictionarySplat(data: T.DictionarySplat, tree: TreeHandle) {
  const _node = withMethods({
    ...data,
    $type: TSKindId.DictionarySplat as const,
    _expression: data._expression,

    expression() { return drillIn<T.Expression>(this._expression, tree); },
    $with: {
      expression: (v: NonNullable<T.DictionarySplat['_expression']>) => wrapDictionarySplat({ ...data, _expression: v }, tree),
    },
  });
  return _node;
}

export function wrapDictionarySplatPattern(data: T.DictionarySplatPattern, tree: TreeHandle) {
  const _node = withMethods({
    ...data,
    $type: TSKindId.DictionarySplatPattern as const,
    $children: data.$children,

    $with: { $child: (v: (T.Identifier | T.KeywordIdentifier | T.Subscript | T.Attribute)) => wrapDictionarySplatPattern({ ...data, $children: [v] }, tree) },
  });
  return _node;
}

export function wrapDottedName(data: T.DottedName, tree: TreeHandle) {
  const _node = withMethods({
    ...data,
    $type: TSKindId.DottedName as const,
    $children: data.$children,

    $with: { $children: (...vs: NonEmptyArray<T.Identifier>) => wrapDottedName({ ...data, $children: vs }, tree) },
  });
  return _node;
}

export function wrapElifClause(data: T.ElifClause, tree: TreeHandle) {
  const _node = withMethods({
    ...data,
    $type: TSKindId.ElifClause as const,
    _condition: data._condition,
    _consequence: data._consequence,

    condition() { return drillIn<T.Expression>(this._condition, tree); },
    consequence() { return drillIn<T.Suite>(this._consequence, tree); },
    $with: {
      condition: (v: NonNullable<T.ElifClause['_condition']>) => wrapElifClause({ ...data, _condition: v }, tree),
      consequence: (v: NonNullable<T.ElifClause['_consequence']>) => wrapElifClause({ ...data, _consequence: v }, tree),
    },
  });
  return _node;
}

export function wrapElseClause(data: T.ElseClause, tree: TreeHandle) {
  const _node = withMethods({
    ...data,
    $type: TSKindId.ElseClause as const,
    _body: data._body,

    body() { return drillIn<T.Suite>(this._body, tree); },
    $with: {
      body: (v: NonNullable<T.ElseClause['_body']>) => wrapElseClause({ ...data, _body: v }, tree),
    },
  });
  return _node;
}

export function wrapExceptClause(data: T.ExceptClause, tree: TreeHandle) {
  const _node = withMethods({
    ...data,
    $type: TSKindId.ExceptClause as const,
    _value: data._value,
    _alias: data._alias,
    $children: data.$children,

    values() { return drillInAll<T.Expression>(this._value, tree); },
    alias() { return drillIn<T.Expression | undefined>(this._alias, tree); },
    $with: {
      values: (...v: NonEmptyArray<NonNullable<T.ExceptClause['_value']>[number]>) => wrapExceptClause({ ...data, _value: v }, tree),
      alias: (v: NonNullable<T.ExceptClause['_alias']>) => wrapExceptClause({ ...data, _alias: v }, tree),
      children: (...items: readonly [T.Suite]) => wrapExceptClause({ ...data, $children: items }, tree),
    },
  });
  return _node;
}

export function wrapExecStatement(data: T.ExecStatement, tree: TreeHandle) {
  const _node = withMethods({
    ...data,
    $type: TSKindId.ExecStatement as const,
    _code: data._code,
    _in_clause: data._in_clause,

    code() { return drillIn<T.String | T.Identifier>(this._code, tree); },
    inClauses() { return drillInAll<"in" | T.Expression>(this._in_clause, tree); },
    $with: {
      code: (v: NonNullable<T.ExecStatement['_code']>) => wrapExecStatement({ ...data, _code: v }, tree),
      inClauses: (...v: NonEmptyArray<NonNullable<T.ExecStatement['_in_clause']>[number]>) => wrapExecStatement({ ...data, _in_clause: v }, tree),
    },
  });
  return _node;
}

export function wrapExpressionList(data: T.ExpressionList, tree: TreeHandle) {
  const _node = withMethods({
    ...data,
    $type: TSKindId.ExpressionList as const,
    $children: data.$children,

    $with: { $children: (...vs: NonEmptyArray<T.Expression>) => wrapExpressionList({ ...data, $children: vs }, tree) },
  });
  return _node;
}

export function wrapExpressionStatementTuple(data: T.ExpressionStatementTuple, tree: TreeHandle) {
  const _node = withMethods({
    ...data,
    $children: data.$children,

    $with: { $children: (...vs: NonEmptyArray<T.Expression>) => wrapExpressionStatementTuple({ ...data, $children: vs }, tree) },
  });
  return _node;
}

export function wrapExpressionStatement(data: T.ExpressionStatement, tree: TreeHandle) {
  const _node = withMethods({
    ...data,
    $type: TSKindId.ExpressionStatement as const,
    $children: (data as any).$children,

    $with: {
      children: (...items: readonly [((T.Expression | T.ExpressionStatementTuple | T.Assignment | T.AugmentedAssignment | T.Yield))]) => wrapExpressionStatement({ ...(data as any), $children: items }, tree),
    },
  });
  return _node;
}

export function wrapFinallyClause(data: T.FinallyClause, tree: TreeHandle) {
  const _node = withMethods({
    ...data,
    $type: TSKindId.FinallyClause as const,
    _block: data._block,

    block() { return drillIn<T.Suite>(this._block, tree); },
    $with: {
      block: (v: NonNullable<T.FinallyClause['_block']>) => wrapFinallyClause({ ...data, _block: v }, tree),
    },
  });
  return _node;
}

export function wrapForInClause(data: T.ForInClause, tree: TreeHandle) {
  const _node = withMethods({
    ...data,
    $type: TSKindId.ForInClause as const,
    _async_marker: coerceBooleanKeywordStorage(data._async_marker),
    _left: data._left,
    _right: data._right,

    asyncMarker() { return this._async_marker; },
    left() { return drillIn<T.LeftHandSide>(this._left, tree); },
    rights() { return drillInAll<T.ExpressionWithinForInClause>(this._right, tree); },
    $with: {
      asyncMarker: (v: NonNullable<T.ForInClause['_async_marker']>) => wrapForInClause({ ...data, _async_marker: v }, tree),
      left: (v: NonNullable<T.ForInClause['_left']>) => wrapForInClause({ ...data, _left: v }, tree),
      rights: (...v: NonEmptyArray<NonNullable<T.ForInClause['_right']>[number]>) => wrapForInClause({ ...data, _right: v }, tree),
    },
  });
  return _node;
}

export function wrapForStatement(data: T.ForStatement, tree: TreeHandle) {
  const _node = withMethods({
    ...data,
    $type: TSKindId.ForStatement as const,
    _async_marker: coerceBooleanKeywordStorage(data._async_marker),
    _left: data._left,
    _right: data._right,
    _body: data._body,
    _alternative: data._alternative,

    asyncMarker() { return this._async_marker; },
    left() { return drillIn<T.LeftHandSide>(this._left, tree); },
    right() { return drillIn<T.Expressions>(this._right, tree); },
    body() { return drillIn<T.Suite>(this._body, tree); },
    alternative() { return drillIn<T.ElseClause | undefined>(this._alternative, tree); },
    $with: {
      asyncMarker: (v: NonNullable<T.ForStatement['_async_marker']>) => wrapForStatement({ ...data, _async_marker: v }, tree),
      left: (v: NonNullable<T.ForStatement['_left']>) => wrapForStatement({ ...data, _left: v }, tree),
      right: (v: NonNullable<T.ForStatement['_right']>) => wrapForStatement({ ...data, _right: v }, tree),
      body: (v: NonNullable<T.ForStatement['_body']>) => wrapForStatement({ ...data, _body: v }, tree),
      alternative: (v: NonNullable<T.ForStatement['_alternative']>) => wrapForStatement({ ...data, _alternative: v }, tree),
    },
  });
  return _node;
}

export function wrapFormatSpecifier(data: T.FormatSpecifier, tree: TreeHandle) {
  const _node = withMethods({
    ...data,
    $type: TSKindId.FormatSpecifier as const,
    $children: data.$children,

    $with: { $children: (...vs: T.Interpolation[]) => wrapFormatSpecifier({ ...data, $children: vs }, tree) },
  });
  return _node;
}

export function wrapFunctionDefinition(data: T.FunctionDefinition, tree: TreeHandle) {
  const _node = withMethods({
    ...data,
    $type: TSKindId.FunctionDefinition as const,
    _async_marker: coerceBooleanKeywordStorage(data._async_marker),
    _name: data._name,
    _type_parameters: data._type_parameters,
    _parameters: data._parameters,
    _return_type: data._return_type,
    _body: data._body,

    asyncMarker() { return this._async_marker; },
    name() { return drillIn<T.Identifier>(this._name, tree); },
    typeParameters() { return drillIn<T.TypeParameter | undefined>(this._type_parameters, tree); },
    parameters() { return drillIn<T.Parameters>(this._parameters, tree); },
    returnType() { return drillIn<T.Type | undefined>(this._return_type, tree); },
    body() { return drillIn<T.Suite>(this._body, tree); },
    $with: {
      asyncMarker: (v: NonNullable<T.FunctionDefinition['_async_marker']>) => wrapFunctionDefinition({ ...data, _async_marker: v }, tree),
      name: (v: NonNullable<T.FunctionDefinition['_name']>) => wrapFunctionDefinition({ ...data, _name: v }, tree),
      typeParameters: (v: NonNullable<T.FunctionDefinition['_type_parameters']>) => wrapFunctionDefinition({ ...data, _type_parameters: v }, tree),
      parameters: (v: NonNullable<T.FunctionDefinition['_parameters']>) => wrapFunctionDefinition({ ...data, _parameters: v }, tree),
      returnType: (v: NonNullable<T.FunctionDefinition['_return_type']>) => wrapFunctionDefinition({ ...data, _return_type: v }, tree),
      body: (v: NonNullable<T.FunctionDefinition['_body']>) => wrapFunctionDefinition({ ...data, _body: v }, tree),
    },
  });
  return _node;
}

export function wrapFutureImportStatement(data: T.FutureImportStatement, tree: TreeHandle) {
  const _node = withMethods({
    ...data,
    $type: TSKindId.FutureImportStatement as const,
    _name: data._name,

    names() { return drillInAll<T.DottedName | T.AliasedImport>(this._name, tree); },
    $with: {
      names: (...v: NonEmptyArray<NonNullable<T.FutureImportStatement['_name']>[number]>) => wrapFutureImportStatement({ ...data, _name: v }, tree),
    },
  });
  return _node;
}

export function wrapGeneratorExpression(data: T.GeneratorExpression, tree: TreeHandle) {
  const _node = withMethods({
    ...data,
    $type: TSKindId.GeneratorExpression as const,
    _body: data._body,
    $children: data.$children,

    body() { return drillIn<T.Expression>(this._body, tree); },
    $with: {
      body: (v: NonNullable<T.GeneratorExpression['_body']>) => wrapGeneratorExpression({ ...data, _body: v }, tree),
      children: (...items: readonly [T.ComprehensionClauses]) => wrapGeneratorExpression({ ...data, $children: items }, tree),
    },
  });
  return _node;
}

export function wrapGenericType(data: T.GenericType, tree: TreeHandle) {
  const _node = withMethods({
    ...data,
    $type: TSKindId.GenericType as const,
    _identifier: data._identifier,
    _type_parameter: data._type_parameter,

    identifier() { return drillIn<T.Identifier>(this._identifier, tree); },
    typeParameter() { return drillIn<T.TypeParameter>(this._type_parameter, tree); },
    $with: {
      identifier: (v: NonNullable<T.GenericType['_identifier']>) => wrapGenericType({ ...data, _identifier: v }, tree),
      typeParameter: (v: NonNullable<T.GenericType['_type_parameter']>) => wrapGenericType({ ...data, _type_parameter: v }, tree),
    },
  });
  return _node;
}

export function wrapGlobalStatement(data: T.GlobalStatement, tree: TreeHandle) {
  const _node = withMethods({
    ...data,
    $type: TSKindId.GlobalStatement as const,
    $children: data.$children,

    $with: { $children: (...vs: NonEmptyArray<T.Identifier>) => wrapGlobalStatement({ ...data, $children: vs }, tree) },
  });
  return _node;
}

export function wrapIfClause(data: T.IfClause, tree: TreeHandle) {
  const _node = withMethods({
    ...data,
    $type: TSKindId.IfClause as const,
    _expression: data._expression,

    expression() { return drillIn<T.Expression>(this._expression, tree); },
    $with: {
      expression: (v: NonNullable<T.IfClause['_expression']>) => wrapIfClause({ ...data, _expression: v }, tree),
    },
  });
  return _node;
}

export function wrapIfStatement(data: T.IfStatement, tree: TreeHandle) {
  const _node = withMethods({
    ...data,
    $type: TSKindId.IfStatement as const,
    _condition: data._condition,
    _consequence: data._consequence,
    _alternative: data._alternative,

    condition() { return drillIn<T.Expression>(this._condition, tree); },
    consequence() { return drillIn<T.Suite>(this._consequence, tree); },
    alternatives() { return drillInAll<T.ElifClause | T.ElseClause>(this._alternative, tree); },
    $with: {
      condition: (v: NonNullable<T.IfStatement['_condition']>) => wrapIfStatement({ ...data, _condition: v }, tree),
      consequence: (v: NonNullable<T.IfStatement['_consequence']>) => wrapIfStatement({ ...data, _consequence: v }, tree),
      alternatives: (...v: NonNullable<T.IfStatement['_alternative']>[number][]) => wrapIfStatement({ ...data, _alternative: v }, tree),
    },
  });
  return _node;
}

export function wrapImportFromStatement(data: T.ImportFromStatement, tree: TreeHandle) {
  const _node = withMethods({
    ...data,
    $type: TSKindId.ImportFromStatement as const,
    _module_name: data._module_name,
    $children: data.$children,

    moduleName() { return drillIn<T.RelativeImport | T.DottedName>(this._module_name, tree); },
    $with: {
      moduleName: (v: NonNullable<T.ImportFromStatement['_module_name']>) => wrapImportFromStatement({ ...data, _module_name: v }, tree),
      children: (...items: NonEmptyArray<(T.WildcardImport | T.DottedName | T.AliasedImport)>) => wrapImportFromStatement({ ...data, $children: items }, tree),
    },
  });
  return _node;
}

export function wrapImportStatement(data: T.ImportStatement, tree: TreeHandle) {
  const _node = withMethods({
    ...data,
    $type: TSKindId.ImportStatement as const,
    _name: data._name,

    names() { return drillInAll<T.DottedName | T.AliasedImport>(this._name, tree); },
    $with: {
      names: (...v: NonEmptyArray<NonNullable<T.ImportStatement['_name']>[number]>) => wrapImportStatement({ ...data, _name: v }, tree),
    },
  });
  return _node;
}

export function wrapInterpolation(data: T.Interpolation, tree: TreeHandle) {
  const _node = withMethods({
    ...data,
    $type: TSKindId.Interpolation as const,
    _expression: data._expression,
    _type_conversion: data._type_conversion,
    _format_specifier: data._format_specifier,

    expression() { return drillIn<T.FExpression>(this._expression, tree); },
    typeConversion() { return drillIn<T.TypeConversion | undefined>(this._type_conversion, tree); },
    formatSpecifier() { return drillIn<T.FormatSpecifier | undefined>(this._format_specifier, tree); },
    $with: {
      expression: (v: NonNullable<T.Interpolation['_expression']>) => wrapInterpolation({ ...data, _expression: v }, tree),
      typeConversion: (v: NonNullable<T.Interpolation['_type_conversion']>) => wrapInterpolation({ ...data, _type_conversion: v }, tree),
      formatSpecifier: (v: NonNullable<T.Interpolation['_format_specifier']>) => wrapInterpolation({ ...data, _format_specifier: v }, tree),
    },
  });
  return _node;
}

export function wrapKeywordArgument(data: T.KeywordArgument, tree: TreeHandle) {
  const _node = withMethods({
    ...data,
    $type: TSKindId.KeywordArgument as const,
    _name: data._name,
    _value: data._value,

    name() { return drillIn<T.Identifier | T.KeywordIdentifier>(this._name, tree); },
    value() { return drillIn<T.Expression>(this._value, tree); },
    $with: {
      name: (v: NonNullable<T.KeywordArgument['_name']>) => wrapKeywordArgument({ ...data, _name: v }, tree),
      value: (v: NonNullable<T.KeywordArgument['_value']>) => wrapKeywordArgument({ ...data, _value: v }, tree),
    },
  });
  return _node;
}

export function wrapKeywordPattern(data: T.KeywordPattern, tree: TreeHandle) {
  const _node = withMethods({
    ...data,
    $type: TSKindId.KeywordPattern as const,
    _identifier: data._identifier,
    _simple_pattern: data._simple_pattern,

    identifier() { return drillIn<T.Identifier>(this._identifier, tree); },
    simplePattern() { return drillIn<T.SimplePattern>(this._simple_pattern, tree); },
    $with: {
      identifier: (v: NonNullable<T.KeywordPattern['_identifier']>) => wrapKeywordPattern({ ...data, _identifier: v }, tree),
      simplePattern: (v: NonNullable<T.KeywordPattern['_simple_pattern']>) => wrapKeywordPattern({ ...data, _simple_pattern: v }, tree),
    },
  });
  return _node;
}

export function wrapLambda(data: T.Lambda, tree: TreeHandle) {
  const _node = withMethods({
    ...data,
    $type: TSKindId.Lambda as const,
    _parameters: data._parameters,
    _body: data._body,

    parameters() { return drillIn<T.LambdaParameters | undefined>(this._parameters, tree); },
    body() { return drillIn<T.Expression>(this._body, tree); },
    $with: {
      parameters: (v: NonNullable<T.Lambda['_parameters']>) => wrapLambda({ ...data, _parameters: v }, tree),
      body: (v: NonNullable<T.Lambda['_body']>) => wrapLambda({ ...data, _body: v }, tree),
    },
  });
  return _node;
}

export function wrapLambdaParameters(data: T.LambdaParameters, tree: TreeHandle) {
  const _node = withMethods({
    ...data,
    $type: TSKindId.LambdaParameters as const,
    $children: data.$children,

    $with: { $children: (...vs: NonEmptyArray<T.Parameter>) => wrapLambdaParameters({ ...data, $children: vs }, tree) },
  });
  return _node;
}

export function wrapLambdaWithinForInClause(data: T.LambdaWithinForInClause, tree: TreeHandle) {
  const _node = withMethods({
    ...data,
    $type: TSKindId.LambdaWithinForInClause as const,
    _parameters: data._parameters,
    _body: data._body,

    parameters() { return drillIn<T.LambdaParameters | undefined>(this._parameters, tree); },
    body() { return drillIn<T.ExpressionWithinForInClause>(this._body, tree); },
    $with: {
      parameters: (v: NonNullable<T.LambdaWithinForInClause['_parameters']>) => wrapLambdaWithinForInClause({ ...data, _parameters: v }, tree),
      body: (v: NonNullable<T.LambdaWithinForInClause['_body']>) => wrapLambdaWithinForInClause({ ...data, _body: v }, tree),
    },
  });
  return _node;
}

export function wrapList(data: T.List, tree: TreeHandle) {
  const _node = withMethods({
    ...data,
    $type: TSKindId.List as const,
    $children: data.$children,

    $with: { $children: (...vs: ((T.Expression | T.Yield | T.ListSplat | T.ParenthesizedListSplat))[]) => wrapList({ ...data, $children: vs }, tree) },
  });
  return _node;
}

export function wrapListComprehension(data: T.ListComprehension, tree: TreeHandle) {
  const _node = withMethods({
    ...data,
    $type: TSKindId.ListComprehension as const,
    _body: data._body,
    $children: data.$children,

    body() { return drillIn<T.Expression>(this._body, tree); },
    $with: {
      body: (v: NonNullable<T.ListComprehension['_body']>) => wrapListComprehension({ ...data, _body: v }, tree),
      children: (...items: readonly [T.ComprehensionClauses]) => wrapListComprehension({ ...data, $children: items }, tree),
    },
  });
  return _node;
}

export function wrapListPattern(data: T.ListPattern, tree: TreeHandle) {
  const _node = withMethods({
    ...data,
    $type: TSKindId.ListPattern as const,
    $children: data.$children,

    $with: { $children: (...vs: T.Pattern[]) => wrapListPattern({ ...data, $children: vs }, tree) },
  });
  return _node;
}

export function wrapListSplat(data: T.ListSplat, tree: TreeHandle) {
  const _node = withMethods({
    ...data,
    $type: TSKindId.ListSplat as const,
    _expression: data._expression,

    expression() { return drillIn<T.Expression>(this._expression, tree); },
    $with: {
      expression: (v: NonNullable<T.ListSplat['_expression']>) => wrapListSplat({ ...data, _expression: v }, tree),
    },
  });
  return _node;
}

export function wrapListSplatPattern(data: T.ListSplatPattern, tree: TreeHandle) {
  const _node = withMethods({
    ...data,
    $type: TSKindId.ListSplatPattern as const,
    $children: data.$children,

    $with: { $child: (v: (T.Identifier | T.KeywordIdentifier | T.Subscript | T.Attribute)) => wrapListSplatPattern({ ...data, $children: [v] }, tree) },
  });
  return _node;
}

export function wrapMatchStatement(data: T.MatchStatement, tree: TreeHandle) {
  const _node = withMethods({
    ...data,
    $type: TSKindId.MatchStatement as const,
    _subject: data._subject,
    _body: data._body,

    subjects() { return drillInAll<T.Expression>(this._subject, tree); },
    body() { return drillAs<T.MatchBlock>(this._body, tree, "block", "_match_block"); },
    $with: {
      subjects: (...v: NonEmptyArray<NonNullable<T.MatchStatement['_subject']>[number]>) => wrapMatchStatement({ ...data, _subject: v }, tree),
      body: (v: NonNullable<T.MatchStatement['_body']>) => wrapMatchStatement({ ...data, _body: v }, tree),
    },
  });
  return _node;
}

export function wrapMemberType(data: T.MemberType, tree: TreeHandle) {
  const _node = withMethods({
    ...data,
    $type: TSKindId.MemberType as const,
    _base_type: data._base_type,
    _identifier: data._identifier,

    baseType() { return drillIn<T.Type>(this._base_type, tree); },
    identifier() { return drillIn<T.Identifier>(this._identifier, tree); },
    $with: {
      baseType: (v: NonNullable<T.MemberType['_base_type']>) => wrapMemberType({ ...data, _base_type: v }, tree),
      identifier: (v: NonNullable<T.MemberType['_identifier']>) => wrapMemberType({ ...data, _identifier: v }, tree),
    },
  });
  return _node;
}

export function wrapModule(data: T.Module, tree: TreeHandle) {
  const _node = withMethods({
    ...data,
    $type: TSKindId.Module as const,
    $children: data.$children,

    $with: { $children: (...vs: T.Statement[]) => wrapModule({ ...data, $children: vs }, tree) },
  });
  return _node;
}

export function wrapNamedExpression(data: T.NamedExpression, tree: TreeHandle) {
  const _node = withMethods({
    ...data,
    $type: TSKindId.NamedExpression as const,
    _name: data._name,
    _value: data._value,

    name() { return drillIn<T.NamedExpressionLhs>(this._name, tree); },
    value() { return drillIn<T.Expression>(this._value, tree); },
    $with: {
      name: (v: NonNullable<T.NamedExpression['_name']>) => wrapNamedExpression({ ...data, _name: v }, tree),
      value: (v: NonNullable<T.NamedExpression['_value']>) => wrapNamedExpression({ ...data, _value: v }, tree),
    },
  });
  return _node;
}

export function wrapNonlocalStatement(data: T.NonlocalStatement, tree: TreeHandle) {
  const _node = withMethods({
    ...data,
    $type: TSKindId.NonlocalStatement as const,
    $children: data.$children,

    $with: { $children: (...vs: NonEmptyArray<T.Identifier>) => wrapNonlocalStatement({ ...data, $children: vs }, tree) },
  });
  return _node;
}

export function wrapNotOperator(data: T.NotOperator, tree: TreeHandle) {
  const _node = withMethods({
    ...data,
    $type: TSKindId.NotOperator as const,
    _argument: data._argument,

    argument() { return drillIn<T.Expression>(this._argument, tree); },
    $with: {
      argument: (v: NonNullable<T.NotOperator['_argument']>) => wrapNotOperator({ ...data, _argument: v }, tree),
    },
  });
  return _node;
}

export function wrapPair(data: T.Pair, tree: TreeHandle) {
  const _node = withMethods({
    ...data,
    $type: TSKindId.Pair as const,
    _key: data._key,
    _value: data._value,

    key() { return drillIn<T.Expression>(this._key, tree); },
    value() { return drillIn<T.Expression>(this._value, tree); },
    $with: {
      key: (v: NonNullable<T.Pair['_key']>) => wrapPair({ ...data, _key: v }, tree),
      value: (v: NonNullable<T.Pair['_value']>) => wrapPair({ ...data, _value: v }, tree),
    },
  });
  return _node;
}

export function wrapParameters(data: T.Parameters, tree: TreeHandle) {
  const _node = withMethods({
    ...data,
    $type: TSKindId.Parameters as const,
    $children: data.$children,

    $with: { $children: (...vs: T.Parameter[]) => wrapParameters({ ...data, $children: vs }, tree) },
  });
  return _node;
}

export function wrapParenthesizedExpression(data: T.ParenthesizedExpression, tree: TreeHandle) {
  const _node = withMethods({
    ...data,
    $type: TSKindId.ParenthesizedExpression as const,
    $children: data.$children,

    $with: { $child: (v: (T.Expression | T.Yield)) => wrapParenthesizedExpression({ ...data, $children: [v] }, tree) },
  });
  return _node;
}

export function wrapParenthesizedListSplat(data: T.ParenthesizedListSplat, tree: TreeHandle) {
  const _node = withMethods({
    ...data,
    $type: TSKindId.ParenthesizedListSplat as const,
    $children: data.$children,

    $with: { $child: (v: (T.ParenthesizedListSplat | T.ListSplat)) => wrapParenthesizedListSplat({ ...data, $children: [v] }, tree) },
  });
  return _node;
}

export function wrapPatternList(data: T.PatternList, tree: TreeHandle) {
  const _node = withMethods({
    ...data,
    $type: TSKindId.PatternList as const,
    $children: data.$children,

    $with: { $children: (...vs: NonEmptyArray<T.Pattern>) => wrapPatternList({ ...data, $children: vs }, tree) },
  });
  return _node;
}

export function wrapPrintStatement(data: T.PrintStatement, tree: TreeHandle) {
  const _node = withMethods({
    ...data,
    $type: TSKindId.PrintStatement as const,
    _argument: data._argument,
    $children: data.$children,

    arguments() { return drillInAll<T.Expression>(this._argument, tree); },
    $with: {
      arguments: (...v: NonNullable<T.PrintStatement['_argument']>[number][]) => wrapPrintStatement({ ...data, _argument: v }, tree),
      children: (...items: readonly [T.Chevron]) => wrapPrintStatement({ ...data, $children: items }, tree),
    },
  });
  return _node;
}

export function wrapRaiseStatement(data: T.RaiseStatement, tree: TreeHandle) {
  const _node = withMethods({
    ...data,
    $type: TSKindId.RaiseStatement as const,
    _cause: data._cause,
    $children: data.$children,

    cause() { return drillIn<T.Expression | undefined>(this._cause, tree); },
    $with: {
      cause: (v: NonNullable<T.RaiseStatement['_cause']>) => wrapRaiseStatement({ ...data, _cause: v }, tree),
      children: (...items: readonly [T.Expressions]) => wrapRaiseStatement({ ...data, $children: items }, tree),
    },
  });
  return _node;
}

export function wrapRelativeImport(data: T.RelativeImport, tree: TreeHandle) {
  const _node = withMethods({
    ...data,
    $type: TSKindId.RelativeImport as const,
    _import_prefix: data._import_prefix,
    _dotted_name: data._dotted_name,

    importPrefix() { return drillIn<T.ImportPrefix>(this._import_prefix, tree); },
    dottedName() { return drillIn<T.DottedName | undefined>(this._dotted_name, tree); },
    $with: {
      importPrefix: (v: NonNullable<T.RelativeImport['_import_prefix']>) => wrapRelativeImport({ ...data, _import_prefix: v }, tree),
      dottedName: (v: NonNullable<T.RelativeImport['_dotted_name']>) => wrapRelativeImport({ ...data, _dotted_name: v }, tree),
    },
  });
  return _node;
}

export function wrapReturnStatement(data: T.ReturnStatement, tree: TreeHandle) {
  const _node = withMethods({
    ...data,
    $type: TSKindId.ReturnStatement as const,
    $children: data.$children,

    $with: { $child: (v: T.Expressions) => wrapReturnStatement({ ...data, $children: [v] }, tree) },
  });
  return _node;
}

export function wrapSet(data: T.Set, tree: TreeHandle) {
  const _node = withMethods({
    ...data,
    $type: TSKindId.Set as const,
    $children: data.$children,

    $with: { $children: (...vs: NonEmptyArray<(T.Expression | T.Yield | T.ListSplat | T.ParenthesizedListSplat)>) => wrapSet({ ...data, $children: vs }, tree) },
  });
  return _node;
}

export function wrapSetComprehension(data: T.SetComprehension, tree: TreeHandle) {
  const _node = withMethods({
    ...data,
    $type: TSKindId.SetComprehension as const,
    _body: data._body,
    $children: data.$children,

    body() { return drillIn<T.Expression>(this._body, tree); },
    $with: {
      body: (v: NonNullable<T.SetComprehension['_body']>) => wrapSetComprehension({ ...data, _body: v }, tree),
      children: (...items: readonly [T.ComprehensionClauses]) => wrapSetComprehension({ ...data, $children: items }, tree),
    },
  });
  return _node;
}

export function wrapSlice(data: T.Slice, tree: TreeHandle) {
  const _node = withMethods({
    ...data,
    $type: TSKindId.Slice as const,
    _start: data._start,
    _stop: data._stop,
    _step: data._step,

    start() { return drillIn<T.Expression | undefined>(this._start, tree); },
    stop() { return drillIn<T.Expression | undefined>(this._stop, tree); },
    step() { return drillIn<T.Expression | undefined>(this._step, tree); },
    $with: {
      start: (v: NonNullable<T.Slice['_start']>) => wrapSlice({ ...data, _start: v }, tree),
      stop: (v: NonNullable<T.Slice['_stop']>) => wrapSlice({ ...data, _stop: v }, tree),
      step: (v: NonNullable<T.Slice['_step']>) => wrapSlice({ ...data, _step: v }, tree),
    },
  });
  return _node;
}

export function wrapSplatPattern(data: T.SplatPattern, tree: TreeHandle) {
  const _node = withMethods({
    ...data,
    $type: TSKindId.SplatPattern as const,
    _identifier: data._identifier,

    identifier() { return drillIn<T._Identifier | T.Identifier | "_">(this._identifier, tree); },
    $with: {
      identifier: (v: NonNullable<T.SplatPattern['_identifier']>) => wrapSplatPattern({ ...data, _identifier: v }, tree),
    },
  });
  return _node;
}

export function wrapSplatType(data: T.SplatType, tree: TreeHandle) {
  const _node = withMethods({
    ...data,
    $type: TSKindId.SplatType as const,
    _identifier: data._identifier,

    identifier() { return drillIn<T._Identifier | T.Identifier>(this._identifier, tree); },
    $with: {
      identifier: (v: NonNullable<T.SplatType['_identifier']>) => wrapSplatType({ ...data, _identifier: v }, tree),
    },
  });
  return _node;
}

export function wrapString(data: T.String, tree: TreeHandle) {
  const _node = withMethods({
    ...data,
    $type: TSKindId.String as const,
    _string_start: data._string_start,
    _content: data._content,
    _string_end: data._string_end,

    stringStart() { return drillIn<T.StringStart>(this._string_start, tree); },
    contents() { return drillInAll<T.Interpolation | T.StringContent>(this._content, tree); },
    stringEnd() { return drillIn<T.StringEnd>(this._string_end, tree); },
    $with: {
      stringStart: (v: NonNullable<T.String['_string_start']>) => wrapString({ ...data, _string_start: v }, tree),
      contents: (...v: NonNullable<T.String['_content']>[number][]) => wrapString({ ...data, _content: v }, tree),
      stringEnd: (v: NonNullable<T.String['_string_end']>) => wrapString({ ...data, _string_end: v }, tree),
    },
  });
  return _node;
}

export function wrapStringContent(data: T.StringContent, tree: TreeHandle) {
  const _node = withMethods({
    ...data,
    $type: TSKindId.StringContent as const,
    $children: data.$children,

    $with: { $children: (...vs: NonEmptyArray<(T.EscapeInterpolation | T.EscapeSequence | "\\" | T._StringContent)>) => wrapStringContent({ ...data, $children: vs }, tree) },
  });
  return _node;
}

export function wrapSubscript(data: T.Subscript, tree: TreeHandle) {
  const _node = withMethods({
    ...data,
    $type: TSKindId.Subscript as const,
    _value: data._value,
    _subscript: data._subscript,

    value() { return drillIn<T.PrimaryExpression>(this._value, tree); },
    subscripts() { return drillInAll<T.Expression | T.Slice>(this._subscript, tree); },
    $with: {
      value: (v: NonNullable<T.Subscript['_value']>) => wrapSubscript({ ...data, _value: v }, tree),
      subscripts: (...v: NonEmptyArray<NonNullable<T.Subscript['_subscript']>[number]>) => wrapSubscript({ ...data, _subscript: v }, tree),
    },
  });
  return _node;
}

export function wrapTryStatement(data: T.TryStatement, tree: TreeHandle) {
  const _node = withMethods({
    ...data,
    $type: TSKindId.TryStatement as const,
    _body: data._body,
    _except_clauses: data._except_clauses,
    _else_clause: data._else_clause,
    _finally_clause: data._finally_clause,

    body() { return drillIn<T.Suite>(this._body, tree); },
    exceptClauses() { return drillInAll<T.ExceptClause>(this._except_clauses, tree); },
    elseClause() { return drillIn<T.ElseClause | undefined>(this._else_clause, tree); },
    finallyClause() { return drillIn<T.FinallyClause | undefined>(this._finally_clause, tree); },
    $with: {
      body: (v: NonNullable<T.TryStatement['_body']>) => wrapTryStatement({ ...data, _body: v }, tree),
      exceptClauses: (...v: NonNullable<T.TryStatement['_except_clauses']>[number][]) => wrapTryStatement({ ...data, _except_clauses: v }, tree),
      elseClause: (v: NonNullable<T.TryStatement['_else_clause']>) => wrapTryStatement({ ...data, _else_clause: v }, tree),
      finallyClause: (v: NonNullable<T.TryStatement['_finally_clause']>) => wrapTryStatement({ ...data, _finally_clause: v }, tree),
    },
  });
  return _node;
}

export function wrapTuple(data: T.Tuple, tree: TreeHandle) {
  const _node = withMethods({
    ...data,
    $type: TSKindId.Tuple as const,
    $children: data.$children,

    $with: { $children: (...vs: ((T.Expression | T.Yield | T.ListSplat | T.ParenthesizedListSplat))[]) => wrapTuple({ ...data, $children: vs }, tree) },
  });
  return _node;
}

export function wrapTuplePattern(data: T.TuplePattern, tree: TreeHandle) {
  const _node = withMethods({
    ...data,
    $type: TSKindId.TuplePattern as const,
    $children: data.$children,

    $with: { $children: (...vs: T.Pattern[]) => wrapTuplePattern({ ...data, $children: vs }, tree) },
  });
  return _node;
}

export function wrapType(data: T.Type, tree: TreeHandle) {
  const _node = withMethods({
    ...data,
    $type: TSKindId.Type as const,
    $children: data.$children,

    $with: { $child: (v: (T.Expression | T.SplatType | T.GenericType | T.UnionType | T.ConstrainedType | T.MemberType)) => wrapType({ ...data, $children: [v] }, tree) },
  });
  return _node;
}

export function wrapTypeAliasStatement(data: T.TypeAliasStatement, tree: TreeHandle) {
  const _node = withMethods({
    ...data,
    $type: TSKindId.TypeAliasStatement as const,
    _type: data._type,
    _left: data._left,
    _right: data._right,

    type() { return drillIn<"type">(this._type, tree); },
    left() { return drillIn<T.Type>(this._left, tree); },
    right() { return drillIn<T.Type>(this._right, tree); },
    $with: {
      type: (v: NonNullable<T.TypeAliasStatement['_type']>) => wrapTypeAliasStatement({ ...data, _type: v }, tree),
      left: (v: NonNullable<T.TypeAliasStatement['_left']>) => wrapTypeAliasStatement({ ...data, _left: v }, tree),
      right: (v: NonNullable<T.TypeAliasStatement['_right']>) => wrapTypeAliasStatement({ ...data, _right: v }, tree),
    },
  });
  return _node;
}

export function wrapTypeParameter(data: T.TypeParameter, tree: TreeHandle) {
  const _node = withMethods({
    ...data,
    $type: TSKindId.TypeParameter as const,
    $children: data.$children,

    $with: { $children: (...vs: NonEmptyArray<T.Type>) => wrapTypeParameter({ ...data, $children: vs }, tree) },
  });
  return _node;
}

export function wrapTypedDefaultParameter(data: T.TypedDefaultParameter, tree: TreeHandle) {
  const _node = withMethods({
    ...data,
    $type: TSKindId.TypedDefaultParameter as const,
    _name: data._name,
    _type: data._type,
    _value: data._value,

    name() { return drillIn<T.Identifier>(this._name, tree); },
    type() { return drillIn<T.Type>(this._type, tree); },
    value() { return drillIn<T.Expression>(this._value, tree); },
    $with: {
      name: (v: NonNullable<T.TypedDefaultParameter['_name']>) => wrapTypedDefaultParameter({ ...data, _name: v }, tree),
      type: (v: NonNullable<T.TypedDefaultParameter['_type']>) => wrapTypedDefaultParameter({ ...data, _type: v }, tree),
      value: (v: NonNullable<T.TypedDefaultParameter['_value']>) => wrapTypedDefaultParameter({ ...data, _value: v }, tree),
    },
  });
  return _node;
}

export function wrapTypedParameter(data: T.TypedParameter, tree: TreeHandle) {
  const _node = withMethods({
    ...data,
    $type: TSKindId.TypedParameter as const,
    _type: data._type,
    $children: data.$children,

    type() { return drillIn<T.Type>(this._type, tree); },
    $with: {
      type: (v: NonNullable<T.TypedParameter['_type']>) => wrapTypedParameter({ ...data, _type: v }, tree),
      children: (...items: readonly [((T.Identifier | T.ListSplatPattern | T.DictionarySplatPattern))]) => wrapTypedParameter({ ...data, $children: items }, tree),
    },
  });
  return _node;
}

export function wrapUnaryOperator(data: T.UnaryOperator, tree: TreeHandle) {
  const _node = withMethods({
    ...data,
    $type: TSKindId.UnaryOperator as const,
    _operator: projectKindEnumStorage(data._operator),
    _argument: data._argument,

    operator() { return this._operator; },
    argument() { return drillIn<T.PrimaryExpression>(this._argument, tree); },
    $with: {
      operator: (v: NonNullable<T.UnaryOperator['_operator']>) => wrapUnaryOperator({ ...data, _operator: v }, tree),
      argument: (v: NonNullable<T.UnaryOperator['_argument']>) => wrapUnaryOperator({ ...data, _argument: v }, tree),
    },
  });
  return _node;
}

export function wrapUnionPattern(data: T.UnionPattern, tree: TreeHandle) {
  const _node = withMethods({
    ...data,
    $type: TSKindId.UnionPattern as const,
    $children: data.$children,

    $with: { $children: (...vs: NonEmptyArray<T.SimplePattern>) => wrapUnionPattern({ ...data, $children: vs }, tree) },
  });
  return _node;
}

export function wrapUnionType(data: T.UnionType, tree: TreeHandle) {
  const _node = withMethods({
    ...data,
    $type: TSKindId.UnionType as const,
    _left: data._left,
    _right: data._right,

    left() { return drillIn<T.Type>(this._left, tree); },
    right() { return drillIn<T.Type>(this._right, tree); },
    $with: {
      left: (v: NonNullable<T.UnionType['_left']>) => wrapUnionType({ ...data, _left: v }, tree),
      right: (v: NonNullable<T.UnionType['_right']>) => wrapUnionType({ ...data, _right: v }, tree),
    },
  });
  return _node;
}

export function wrapWhileStatement(data: T.WhileStatement, tree: TreeHandle) {
  const _node = withMethods({
    ...data,
    $type: TSKindId.WhileStatement as const,
    _condition: data._condition,
    _body: data._body,
    _alternative: data._alternative,

    condition() { return drillIn<T.Expression>(this._condition, tree); },
    body() { return drillIn<T.Suite>(this._body, tree); },
    alternative() { return drillIn<T.ElseClause | undefined>(this._alternative, tree); },
    $with: {
      condition: (v: NonNullable<T.WhileStatement['_condition']>) => wrapWhileStatement({ ...data, _condition: v }, tree),
      body: (v: NonNullable<T.WhileStatement['_body']>) => wrapWhileStatement({ ...data, _body: v }, tree),
      alternative: (v: NonNullable<T.WhileStatement['_alternative']>) => wrapWhileStatement({ ...data, _alternative: v }, tree),
    },
  });
  return _node;
}

export function wrapWithClauseBare(data: T.WithClauseBare, tree: TreeHandle) {
  const _node = withMethods({
    ...data,
    $children: data.$children,

    $with: { $children: (...vs: NonEmptyArray<T.WithItem>) => wrapWithClauseBare({ ...data, $children: vs }, tree) },
  });
  return _node;
}

export function wrapWithClauseParen(data: T.WithClauseParen, tree: TreeHandle) {
  const _node = withMethods({
    ...data,
    $children: data.$children,

    $with: { $children: (...vs: NonEmptyArray<T.WithItem>) => wrapWithClauseParen({ ...data, $children: vs }, tree) },
  });
  return _node;
}

export function wrapWithClause(data: T.WithClause, tree: TreeHandle) {
  const _node = withMethods({
    ...data,
    $type: TSKindId.WithClause as const,
    $children: (data as any).$children,

    $with: {
      children: (...items: readonly [((T.WithClauseBare | T._WithClauseParen))]) => wrapWithClause({ ...(data as any), $children: items }, tree),
    },
  });
  return _node;
}

export function wrapWithItem(data: T.WithItem, tree: TreeHandle) {
  const _node = withMethods({
    ...data,
    $type: TSKindId.WithItem as const,
    _value: data._value,

    value() { return drillIn<T.Expression>(this._value, tree); },
    $with: {
      value: (v: NonNullable<T.WithItem['_value']>) => wrapWithItem({ ...data, _value: v }, tree),
    },
  });
  return _node;
}

export function wrapWithStatement(data: T.WithStatement, tree: TreeHandle) {
  const _node = withMethods({
    ...data,
    $type: TSKindId.WithStatement as const,
    _async_marker: coerceBooleanKeywordStorage(data._async_marker),
    _with_clause: data._with_clause,
    _body: data._body,

    asyncMarker() { return this._async_marker; },
    withClause() { return drillIn<T.WithClause>(this._with_clause, tree); },
    body() { return drillIn<T.Suite>(this._body, tree); },
    $with: {
      asyncMarker: (v: NonNullable<T.WithStatement['_async_marker']>) => wrapWithStatement({ ...data, _async_marker: v }, tree),
      withClause: (v: NonNullable<T.WithStatement['_with_clause']>) => wrapWithStatement({ ...data, _with_clause: v }, tree),
      body: (v: NonNullable<T.WithStatement['_body']>) => wrapWithStatement({ ...data, _body: v }, tree),
    },
  });
  return _node;
}

export function wrapYield(data: T.Yield, tree: TreeHandle) {
  const _node = withMethods({
    ...data,
    $type: TSKindId.Yield as const,
    $children: data.$children,

    $with: { $child: (v: (T.Expression | T.Expressions)) => wrapYield({ ...data, $children: [v] }, tree) },
  });
  return _node;
}

const _wrapTable: Record<string, (data: _NodeData, tree: TreeHandle) => unknown> = {
  '_as_pattern': (d, t) => wrap_AsPattern(d as T._AsPattern, t),
  '_comprehension_clauses': (d, t) => wrapComprehensionClauses(d as T.ComprehensionClauses, t),
  '_is_not': (d) => ({ ...d, $type: TSKindId.IsNot as const }),
  '_kw_async_marker': (d) => ({ ...d, $type: TSKindId.KwAsyncMarker as const }),
  '_kw_type': (d) => ({ ...d, $type: TSKindId.KwType as const }),
  '_list_pattern': (d, t) => wrap_ListPattern(d as T._ListPattern, t),
  '_match_block': (d, t) => wrapMatchBlock(d as T.MatchBlock, t),
  '_not_in': (d) => ({ ...d, $type: TSKindId.NotIn as const }),
  '_simple_pattern_negative': (d, t) => wrapSimplePatternNegative(d as T.SimplePatternNegative, t),
  '_simple_statements': (d, t) => wrapSimpleStatements(d as T.SimpleStatements, t),
  '_tuple_pattern': (d, t) => wrap_TuplePattern(d as T._TuplePattern, t),
  '_with_clause_paren': (d, t) => wrap_WithClauseParen(d as T._WithClauseParen, t),
  'aliased_import': (d, t) => wrapAliasedImport(d as T.AliasedImport, t),
  'argument_list': (d, t) => wrapArgumentList(d as T.ArgumentList, t),
  'as_pattern': (d, t) => wrapAsPattern(d as T.AsPattern, t),
  'assert_statement': (d, t) => wrapAssertStatement(d as T.AssertStatement, t),
  'assignment': (d, t) => wrapAssignment(d as T.Assignment, t),
  'attribute': (d, t) => wrapAttribute(d as T.Attribute, t),
  'augmented_assignment': (d, t) => wrapAugmentedAssignment(d as T.AugmentedAssignment, t),
  'await': (d, t) => wrapAwait(d as T.Await, t),
  'binary_operator': (d, t) => wrapBinaryOperator(d as T.BinaryOperator, t),
  'block': (d, t) => wrapBlock(d as T.Block, t),
  'boolean_operator': (d, t) => wrapBooleanOperator(d as T.BooleanOperator, t),
  'break_statement': (d) => ({ ...d, $type: TSKindId.BreakStatement as const }),
  'call': (d, t) => wrapCall(d as T.Call, t),
  'case_clause': (d, t) => wrapCaseClause(d as T.CaseClause, t),
  'case_pattern': (d, t) => wrapCasePattern(d as T.CasePattern, t),
  'chevron': (d, t) => wrapChevron(d as T.Chevron, t),
  'class_definition': (d, t) => wrapClassDefinition(d as T.ClassDefinition, t),
  'class_pattern': (d, t) => wrapClassPattern(d as T.ClassPattern, t),
  'comment': (d) => ({ ...d, $type: TSKindId.Comment as const }),
  'comparison_operator': (d, t) => wrapComparisonOperator(d as T.ComparisonOperator, t),
  'complex_pattern': (d, t) => wrapComplexPattern(d as T.ComplexPattern, t),
  'concatenated_string': (d, t) => wrapConcatenatedString(d as T.ConcatenatedString, t),
  'conditional_expression': (d, t) => wrapConditionalExpression(d as T.ConditionalExpression, t),
  'constrained_type': (d, t) => wrapConstrainedType(d as T.ConstrainedType, t),
  'continue_statement': (d) => ({ ...d, $type: TSKindId.ContinueStatement as const }),
  'decorated_definition': (d, t) => wrapDecoratedDefinition(d as T.DecoratedDefinition, t),
  'decorator': (d, t) => wrapDecorator(d as T.Decorator, t),
  'default_parameter': (d, t) => wrapDefaultParameter(d as T.DefaultParameter, t),
  'delete_statement': (d, t) => wrapDeleteStatement(d as T.DeleteStatement, t),
  'dict_pattern': (d, t) => wrapDictPattern(d as T.DictPattern, t),
  'dictionary': (d, t) => wrapDictionary(d as T.Dictionary, t),
  'dictionary_comprehension': (d, t) => wrapDictionaryComprehension(d as T.DictionaryComprehension, t),
  'dictionary_splat': (d, t) => wrapDictionarySplat(d as T.DictionarySplat, t),
  'dictionary_splat_pattern': (d, t) => wrapDictionarySplatPattern(d as T.DictionarySplatPattern, t),
  'dotted_name': (d, t) => wrapDottedName(d as T.DottedName, t),
  'elif_clause': (d, t) => wrapElifClause(d as T.ElifClause, t),
  'else_clause': (d, t) => wrapElseClause(d as T.ElseClause, t),
  'escape_sequence': (d) => ({ ...d, $type: TSKindId.EscapeSequence as const }),
  'except_clause': (d, t) => wrapExceptClause(d as T.ExceptClause, t),
  'exec_statement': (d, t) => wrapExecStatement(d as T.ExecStatement, t),
  'expression_list': (d, t) => wrapExpressionList(d as T.ExpressionList, t),
  'expression_statement_tuple': (d, t) => wrapExpressionStatementTuple(d as T.ExpressionStatementTuple, t),
  'expression_statement': (d, t) => wrapExpressionStatement(d as T.ExpressionStatement, t),
  'false': (d) => ({ ...d, $type: TSKindId.False as const }),
  'finally_clause': (d, t) => wrapFinallyClause(d as T.FinallyClause, t),
  'float': (d) => ({ ...d, $type: TSKindId.Float as const }),
  'for_in_clause': (d, t) => wrapForInClause(d as T.ForInClause, t),
  'for_statement': (d, t) => wrapForStatement(d as T.ForStatement, t),
  'format_specifier': (d, t) => wrapFormatSpecifier(d as T.FormatSpecifier, t),
  'function_definition': (d, t) => wrapFunctionDefinition(d as T.FunctionDefinition, t),
  'future_import_statement': (d, t) => wrapFutureImportStatement(d as T.FutureImportStatement, t),
  'generator_expression': (d, t) => wrapGeneratorExpression(d as T.GeneratorExpression, t),
  'generic_type': (d, t) => wrapGenericType(d as T.GenericType, t),
  'global_statement': (d, t) => wrapGlobalStatement(d as T.GlobalStatement, t),
  'identifier': (d) => ({ ...d, $type: TSKindId.Identifier as const }),
  'if_clause': (d, t) => wrapIfClause(d as T.IfClause, t),
  'if_statement': (d, t) => wrapIfStatement(d as T.IfStatement, t),
  'import_from_statement': (d, t) => wrapImportFromStatement(d as T.ImportFromStatement, t),
  'import_prefix': (d) => ({ ...d, $type: TSKindId.ImportPrefix as const }),
  'import_statement': (d, t) => wrapImportStatement(d as T.ImportStatement, t),
  'integer': (d) => ({ ...d, $type: TSKindId.Integer as const }),
  'interpolation': (d, t) => wrapInterpolation(d as T.Interpolation, t),
  'keyword_argument': (d, t) => wrapKeywordArgument(d as T.KeywordArgument, t),
  'keyword_pattern': (d, t) => wrapKeywordPattern(d as T.KeywordPattern, t),
  'lambda': (d, t) => wrapLambda(d as T.Lambda, t),
  'lambda_parameters': (d, t) => wrapLambdaParameters(d as T.LambdaParameters, t),
  'lambda_within_for_in_clause': (d, t) => wrapLambdaWithinForInClause(d as T.LambdaWithinForInClause, t),
  'line_continuation': (d) => ({ ...d, $type: TSKindId.LineContinuation as const }),
  'list': (d, t) => wrapList(d as T.List, t),
  'list_comprehension': (d, t) => wrapListComprehension(d as T.ListComprehension, t),
  'list_pattern': (d, t) => wrapListPattern(d as T.ListPattern, t),
  'list_splat': (d, t) => wrapListSplat(d as T.ListSplat, t),
  'list_splat_pattern': (d, t) => wrapListSplatPattern(d as T.ListSplatPattern, t),
  'match_statement': (d, t) => wrapMatchStatement(d as T.MatchStatement, t),
  'member_type': (d, t) => wrapMemberType(d as T.MemberType, t),
  'module': (d, t) => wrapModule(d as T.Module, t),
  'named_expression': (d, t) => wrapNamedExpression(d as T.NamedExpression, t),
  'none': (d) => ({ ...d, $type: TSKindId.None as const }),
  'nonlocal_statement': (d, t) => wrapNonlocalStatement(d as T.NonlocalStatement, t),
  'not_operator': (d, t) => wrapNotOperator(d as T.NotOperator, t),
  'pair': (d, t) => wrapPair(d as T.Pair, t),
  'parameters': (d, t) => wrapParameters(d as T.Parameters, t),
  'parenthesized_expression': (d, t) => wrapParenthesizedExpression(d as T.ParenthesizedExpression, t),
  'parenthesized_list_splat': (d, t) => wrapParenthesizedListSplat(d as T.ParenthesizedListSplat, t),
  'pass_statement': (d) => ({ ...d, $type: TSKindId.PassStatement as const }),
  'pattern_list': (d, t) => wrapPatternList(d as T.PatternList, t),
  'print_statement': (d, t) => wrapPrintStatement(d as T.PrintStatement, t),
  'raise_statement': (d, t) => wrapRaiseStatement(d as T.RaiseStatement, t),
  'relative_import': (d, t) => wrapRelativeImport(d as T.RelativeImport, t),
  'return_statement': (d, t) => wrapReturnStatement(d as T.ReturnStatement, t),
  'set': (d, t) => wrapSet(d as T.Set, t),
  'set_comprehension': (d, t) => wrapSetComprehension(d as T.SetComprehension, t),
  'slice': (d, t) => wrapSlice(d as T.Slice, t),
  'splat_pattern': (d, t) => wrapSplatPattern(d as T.SplatPattern, t),
  'splat_type': (d, t) => wrapSplatType(d as T.SplatType, t),
  'string': (d, t) => wrapString(d as T.String, t),
  'string_content': (d, t) => wrapStringContent(d as T.StringContent, t),
  'subscript': (d, t) => wrapSubscript(d as T.Subscript, t),
  'true': (d) => ({ ...d, $type: TSKindId.True as const }),
  'try_statement': (d, t) => wrapTryStatement(d as T.TryStatement, t),
  'tuple': (d, t) => wrapTuple(d as T.Tuple, t),
  'tuple_pattern': (d, t) => wrapTuplePattern(d as T.TuplePattern, t),
  'type': (d, t) => wrapType(d as T.Type, t),
  'type_alias_statement': (d, t) => wrapTypeAliasStatement(d as T.TypeAliasStatement, t),
  'type_conversion': (d) => ({ ...d, $type: TSKindId.TypeConversion as const }),
  'type_parameter': (d, t) => wrapTypeParameter(d as T.TypeParameter, t),
  'typed_default_parameter': (d, t) => wrapTypedDefaultParameter(d as T.TypedDefaultParameter, t),
  'typed_parameter': (d, t) => wrapTypedParameter(d as T.TypedParameter, t),
  'unary_operator': (d, t) => wrapUnaryOperator(d as T.UnaryOperator, t),
  'union_pattern': (d, t) => wrapUnionPattern(d as T.UnionPattern, t),
  'union_type': (d, t) => wrapUnionType(d as T.UnionType, t),
  'while_statement': (d, t) => wrapWhileStatement(d as T.WhileStatement, t),
  'with_clause_bare': (d, t) => wrapWithClauseBare(d as T.WithClauseBare, t),
  'with_clause_paren': (d, t) => wrapWithClauseParen(d as T.WithClauseParen, t),
  'with_clause': (d, t) => wrapWithClause(d as T.WithClause, t),
  'with_item': (d, t) => wrapWithItem(d as T.WithItem, t),
  'with_statement': (d, t) => wrapWithStatement(d as T.WithStatement, t),
  'yield': (d, t) => wrapYield(d as T.Yield, t),
  '_newline': (d) => ({ ...d, $type: TSKindId.Newline as const }),
  '_indent': (d) => ({ ...d, $type: TSKindId.Indent as const }),
  '_dedent': (d) => ({ ...d, $type: TSKindId.Dedent as const }),
  'string_start': (d) => ({ ...d, $type: TSKindId.StringStart as const }),
  '_string_content': (d) => ({ ...d, $type: TSKindId._StringContent as const }),
  'escape_interpolation': (d) => ({ ...d, $type: TSKindId.EscapeInterpolation as const }),
  'string_end': (d) => ({ ...d, $type: TSKindId.StringEnd as const }),
  ']': (d) => d,
  ')': (d) => d,
  '}': (d) => d,
  'except': (d) => ({ ...d, $type: TSKindId.Except as const }),
};

const _aliasTargetToSource: Record<string, string> = {
  'assignment_eq': '_assignment_eq',
  'assignment_type': '_assignment_type',
  'assignment_typed': '_assignment_typed',
  'async_marker': '_async_marker',
  'augmented_assignment_operator': '_augmented_assignment_operator',
  'comprehension_clauses': '_comprehension_clauses',
  'dict_pattern_kv': '_dict_pattern_kv',
  'expression_within_for_in_clause': '_expression_within_for_in_clause',
  'expressions': '_expressions',
  'f_expression': '_f_expression',
  'left_hand_side': '_left_hand_side',
  'match_block': '_match_block',
  'match_block_block': '_match_block_block',
  'named_expression_lhs': '_named_expression_lhs',
  'newline': '_newline',
  'right_hand_side': '_right_hand_side',
  'simple_pattern': '_simple_pattern',
  'simple_pattern_negative': '_simple_pattern_negative',
  'simple_statement': '_simple_statement',
  'simple_statements': '_simple_statements',
  'statement': '_statement',
  'suite': '_suite',
  'unary_operator_operator': '_unary_operator_operator',
};

import { KIND_NAMES } from './types.js';
/** Wrap a NodeData into its lazy read-only view. */
export function wrapNode(data: _NodeData, tree: TreeHandle): unknown {
  // The native path now returns numeric $type
  // (KindId) from Rust; the JS wasm path still returns string $type.
  // Resolve to a kind-name string for the string-keyed dispatch tables,
  // then per-kind wrap functions stamp the numeric TSKindId.$type on output.
  const rawType = typeof data.$type === "number"
    ? KIND_NAMES.get(data.$type as never) ?? String(data.$type)
    : (data.$type as unknown as string);
  // Canonical-hidden remap (Option Y): parser-output `$type`
  // is the visible alias target (e.g. `range_pattern_left_with_right`);
  // remap to the hidden alias source (`_range_pattern_left_with_right`)
  // so dispatch + downstream consumers see the canonical form.
  const canonical = _aliasTargetToSource[rawType];
  if (canonical !== undefined) {
    data = { ...data, $type: canonical as unknown as number };
  }
  const fn = _wrapTable[canonical ?? rawType];
  if (!fn) return data; // unknown kind — return as-is
  return fn(data, tree);
}

/**
 * Per-handle dispatching `readNode` — the architectural seam where
 * the engine choice (JS vs native) lives. `readTreeNode`,
 * `drillIn` and `drillAs` all read through THIS function so the
 * wrap layer is engine-agnostic. tree-sitter `Node::id()` is
 * documented as "unique within a given syntax tree" and is a
 * raw pointer cast — different parses yield different ids — so
 * the engine that parsed the tree is the only thing that can
 * dereference its ids. Native handles set `tree.read` to a
 * closure that routes through napi; wasm/JS handles leave it
 * absent and fall back to `readNodeJs` (the in-process walker).
 */
function readNode(tree: TreeHandle, handle?: number, childIndex?: number): AnyNodeData {
  // Per-handle dispatch: native-engine handles carry a `read`
  // closure that routes through napi (engine owns the tree;
  // Navigation via handle + childIndex replaces nodeId).
  // Wasm/JS handles leave `read` absent and fall
  // back to the in-process JS walker.
  return tree.read ? tree.read(handle, childIndex) : readNodeJs(tree, handle, childIndex);
}

/**
 * Read a parsed tree node into a lazily-wrapped NodeData.
 * One level deep — getters drill into subtrees on demand by
 * recursing back through this same function.
 *
 * Optional `asType: { from, to }` rewrites `$type` between the read
 * and the wrap when the node's actual `$type === from`. Used by
 * `drillAs` for alias-target → alias-source rewrites at
 * declared field sites.
 */
export function readTreeNode(
  tree: TreeHandle,
  handle?: number,
  childIndex?: number,
  asType?: { from: string; to: string },
): unknown {
  let data = readNode(tree, handle, childIndex);
  // asType comparison must handle both string and numeric $type.
  // When numeric (native path), convert to kind-name first for comparison.
  if (asType) {
    const currentType = typeof data.$type === "number"
      ? KIND_NAMES.get(data.$type as never) ?? String(data.$type)
      : (data.$type as unknown as string);
    if (currentType === asType.from) {
      data = { ...data, $type: asType.to as unknown as number };
    }
  }
  return wrapNode(data, tree);
}
