// Auto-generated by @sittir/codegen — do not edit

import type { AnyUntypedNode, QuerySlots, TriviaFacts } from '@sittir/types';
import { bindRuntime } from '@sittir/common/utils';
import { KIND_NAMES, type TypescriptTypeMap } from './types.js';
import { INNER_GAPS } from './consts.js';

export const triviaFacts = Object.freeze({
	kindName: (type: AnyUntypedNode['$type']) => (typeof type === 'number' ? KIND_NAMES.get(type) : type),
	kinds: new Set<string>([
		'_blankline',
		'_double_blankline',
		'_newline',
		'_space',
		'_tab',
		'comment',
		'comment_block',
		'comment_line',
		'html_comment'
	]),
	innerGaps: INNER_GAPS,
	rebuildWrappers: new Set<number>([
		152, 153, 154, 155, 156, 157, 159, 160, 161, 162, 163, 164, 376, 377, 379, 380, 382, 383, 384, 385, 386, 387, 395,
		397, 399, 400, 401, 402, 403, 404, 405, 407, 408, 409, 410, 411, 412, 413, 414, 415, 416, 417, 418, 419, 420, 421,
		422, 423, 424, 425, 426, 427, 428, 429, 432, 433, 434, 460, 462, 463, 464, 465, 467
	]),
	listKinds: new Set<number>([376, 377, 379, 382, 383, 384, 385, 390]),
	whitespace: Object.freeze({
		run: /^(?:(?:(?:[\s\p{Zs}\uFEFF\u2028\u2029\u2060\u200B]))+)$/u,
		kindIdByText: Object.freeze({ ' ': 181, '\t': 182, '\n': 183, '\n\n': 184, '\n\n\n': 185 })
	})
} satisfies TriviaFacts);

export const querySlots: QuerySlots = Object.freeze({
	2: [['content', { fields: ['content'], kinds: [] }]],
	111: [['content', { fields: ['content'], kinds: [] }]],
	118: [['content', { fields: ['content'], kinds: [] }]],
	152: [['content', { fields: ['content'], kinds: [] }]],
	153: [['content', { fields: ['content'], kinds: [] }]],
	154: [
		['prefix', { fields: ['prefix'], kinds: [] }],
		['content', { fields: ['content'], kinds: [] }]
	],
	155: [
		['integer', { fields: ['integer'], kinds: [] }],
		['fraction', { fields: ['fraction'], kinds: [] }],
		['marker', { fields: ['marker'], kinds: [] }],
		['sign', { fields: ['sign'], kinds: [] }],
		['exponent', { fields: ['exponent'], kinds: [] }]
	],
	156: [
		['fraction', { fields: ['fraction'], kinds: [] }],
		['marker', { fields: ['marker'], kinds: [] }],
		['sign', { fields: ['sign'], kinds: [] }],
		['exponent', { fields: ['exponent'], kinds: [] }]
	],
	157: [
		['integer', { fields: ['integer'], kinds: [] }],
		['marker', { fields: ['marker'], kinds: [] }],
		['sign', { fields: ['sign'], kinds: [] }],
		['exponent', { fields: ['exponent'], kinds: [] }]
	],
	159: [
		['prefix', { fields: ['prefix'], kinds: [] }],
		['content', { fields: ['content'], kinds: [] }]
	],
	160: [
		['prefix', { fields: ['prefix'], kinds: [] }],
		['content', { fields: ['content'], kinds: [] }]
	],
	161: [['content', { fields: ['content'], kinds: [] }]],
	162: [['content', { fields: ['content'], kinds: [] }]],
	163: [['content', { fields: ['content'], kinds: [] }]],
	164: [['content', { fields: ['content'], kinds: [] }]],
	188: [
		['hashBangLine', { fields: ['hash_bang_line'], kinds: [] }],
		['statements', { fields: ['statements'], kinds: [] }]
	],
	190: [['moduleExportName', { fields: [], kinds: ['identifier', 'string_double', 'string_single'] }]],
	191: [['exportSpecifiers', { fields: [], kinds: ['export_specifiers'] }]],
	192: [
		['exportKind', { fields: ['export_kind'], kinds: [] }],
		['name', { fields: ['name'], kinds: [] }],
		['alias', { fields: ['alias'], kinds: [] }]
	],
	196: [
		['importClause', { fields: ['import_clause'], kinds: [] }],
		['fromClause', { fields: ['from_clause'], kinds: [] }],
		['importAttribute', { fields: ['import_attribute'], kinds: [] }],
		['terminator', { fields: ['terminator'], kinds: [] }]
	],
	197: [['content', { fields: [], kinds: ['namespace_import', 'named_imports', 'import_clause_default_import'] }]],
	199: [['name', { fields: ['name'], kinds: [] }]],
	200: [['importSpecifiers', { fields: [], kinds: ['import_specifiers'] }]],
	202: [
		['attributeKind', { fields: ['attribute_kind'], kinds: [] }],
		['object', { fields: ['object'], kinds: [] }]
	],
	204: [
		['expression', { fields: ['expression'], kinds: [] }],
		['terminator', { fields: ['terminator'], kinds: [] }]
	],
	205: [
		['declarators', { fields: ['declarators'], kinds: [] }],
		['terminator', { fields: ['terminator'], kinds: [] }]
	],
	206: [
		['kind', { fields: ['kind'], kinds: [] }],
		['declarators', { fields: ['declarators'], kinds: [] }],
		['terminator', { fields: ['terminator'], kinds: [] }]
	],
	208: [
		['statements', { fields: ['statements'], kinds: [] }],
		['automaticSemicolon', { fields: ['automatic_semicolon'], kinds: [] }]
	],
	209: [['body', { fields: ['body'], kinds: [] }]],
	210: [
		['condition', { fields: ['condition'], kinds: [] }],
		['consequence', { fields: ['consequence'], kinds: [] }],
		['alternative', { fields: ['alternative'], kinds: [] }]
	],
	211: [
		['value', { fields: ['value'], kinds: [] }],
		['body', { fields: ['body'], kinds: [] }]
	],
	212: [
		['initializer', { fields: ['initializer'], kinds: [] }],
		['condition', { fields: ['condition'], kinds: [] }],
		['increment', { fields: ['increment'], kinds: [] }],
		['body', { fields: ['body'], kinds: [] }]
	],
	213: [
		['await', { fields: ['await'], kinds: [] }],
		['forHeader', { fields: [], kinds: ['for_header_lhs', 'for_header_var_kind', 'for_header_let_const_kind'] }],
		['body', { fields: ['body'], kinds: [] }]
	],
	215: [
		['condition', { fields: ['condition'], kinds: [] }],
		['body', { fields: ['body'], kinds: [] }]
	],
	216: [
		['body', { fields: ['body'], kinds: [] }],
		['condition', { fields: ['condition'], kinds: [] }],
		['terminator', { fields: ['terminator'], kinds: [] }]
	],
	217: [
		['body', { fields: ['body'], kinds: [] }],
		['handler', { fields: ['handler'], kinds: [] }],
		['finalizer', { fields: ['finalizer'], kinds: [] }]
	],
	218: [
		['object', { fields: ['object'], kinds: [] }],
		['body', { fields: ['body'], kinds: [] }]
	],
	219: [
		['label', { fields: ['label'], kinds: [] }],
		['terminator', { fields: ['terminator'], kinds: [] }]
	],
	220: [
		['label', { fields: ['label'], kinds: [] }],
		['terminator', { fields: ['terminator'], kinds: [] }]
	],
	221: [['terminator', { fields: ['terminator'], kinds: [] }]],
	222: [
		['expression', { fields: ['expression'], kinds: [] }],
		['terminator', { fields: ['terminator'], kinds: [] }]
	],
	223: [
		['expression', { fields: ['expression'], kinds: [] }],
		['terminator', { fields: ['terminator'], kinds: [] }]
	],
	225: [
		['label', { fields: ['label'], kinds: [] }],
		['body', { fields: ['body'], kinds: [] }]
	],
	226: [['cases', { fields: ['cases'], kinds: [] }]],
	227: [
		['value', { fields: ['value'], kinds: [] }],
		['bodies', { fields: ['body'], kinds: [] }]
	],
	228: [['bodies', { fields: ['body'], kinds: [] }]],
	229: [
		['catchClauseGroup', { fields: [], kinds: ['catch_clause_group'] }],
		['body', { fields: ['body'], kinds: [] }]
	],
	230: [['body', { fields: ['body'], kinds: [] }]],
	234: [['expression', { fields: ['expression'], kinds: [] }]],
	235: [['properties', { fields: ['properties'], kinds: [] }]],
	236: [['properties', { fields: ['properties'], kinds: [] }]],
	237: [
		['left', { fields: ['left'], kinds: [] }],
		['right', { fields: ['right'], kinds: [] }]
	],
	238: [
		['left', { fields: ['left'], kinds: [] }],
		['right', { fields: ['right'], kinds: [] }]
	],
	239: [['elements', { fields: ['elements'], kinds: [] }]],
	240: [['elements', { fields: ['elements'], kinds: [] }]],
	241: [
		['object', { fields: ['object'], kinds: [] }],
		['property', { fields: ['property'], kinds: [] }]
	],
	242: [
		['decorators', { fields: ['decorator'], kinds: [] }],
		['name', { fields: ['name'], kinds: [] }],
		['typeParameters', { fields: ['type_parameters'], kinds: [] }],
		['heritage', { fields: ['heritage'], kinds: [] }],
		['body', { fields: ['body'], kinds: [] }]
	],
	243: [
		['decorators', { fields: ['decorator'], kinds: [] }],
		['name', { fields: ['name'], kinds: [] }],
		['typeParameters', { fields: ['type_parameters'], kinds: [] }],
		['heritage', { fields: ['heritage'], kinds: [] }],
		['body', { fields: ['body'], kinds: [] }],
		['automaticSemicolon', { fields: ['automatic_semicolon'], kinds: [] }]
	],
	244: [['content', { fields: [], kinds: ['class_heritage_extends_clause', 'implements_clause'] }]],
	245: [
		['async', { fields: ['async'], kinds: [] }],
		['name', { fields: ['name'], kinds: [] }],
		['typeParameters', { fields: ['type_parameters'], kinds: [] }],
		['parameters', { fields: ['parameters'], kinds: [] }],
		['returnType', { fields: ['return_type'], kinds: [] }],
		['body', { fields: ['body'], kinds: [] }]
	],
	246: [
		['async', { fields: ['async'], kinds: [] }],
		['name', { fields: ['name'], kinds: [] }],
		['typeParameters', { fields: ['type_parameters'], kinds: [] }],
		['parameters', { fields: ['parameters'], kinds: [] }],
		['returnType', { fields: ['return_type'], kinds: [] }],
		['body', { fields: ['body'], kinds: [] }],
		['automaticSemicolon', { fields: [], kinds: ['automatic_semicolon'] }]
	],
	247: [
		['async', { fields: ['async'], kinds: [] }],
		['name', { fields: ['name'], kinds: [] }],
		['typeParameters', { fields: ['type_parameters'], kinds: [] }],
		['parameters', { fields: ['parameters'], kinds: [] }],
		['returnType', { fields: ['return_type'], kinds: [] }],
		['body', { fields: ['body'], kinds: [] }]
	],
	248: [
		['async', { fields: ['async'], kinds: [] }],
		['name', { fields: ['name'], kinds: [] }],
		['typeParameters', { fields: ['type_parameters'], kinds: [] }],
		['parameters', { fields: ['parameters'], kinds: [] }],
		['returnType', { fields: ['return_type'], kinds: [] }],
		['body', { fields: ['body'], kinds: [] }],
		['automaticSemicolon', { fields: [], kinds: ['automatic_semicolon'] }]
	],
	249: [
		['async', { fields: ['async'], kinds: [] }],
		['content', { fields: [], kinds: ['arrow_function_parameter', 'call_signature'] }],
		['body', { fields: ['body'], kinds: [] }]
	],
	254: [
		['constructor_', { fields: ['constructor'], kinds: [] }],
		['typeArguments', { fields: ['type_arguments'], kinds: [] }],
		['arguments', { fields: ['arguments'], kinds: [] }]
	],
	255: [['expression', { fields: ['expression'], kinds: [] }]],
	256: [
		['object', { fields: ['object'], kinds: [] }],
		['separator', { fields: ['separator'], kinds: [] }],
		['property', { fields: ['property'], kinds: [] }]
	],
	257: [
		['object', { fields: ['object'], kinds: [] }],
		['optionalChain', { fields: ['optional_chain'], kinds: [] }],
		['index', { fields: ['index'], kinds: [] }]
	],
	258: [
		[
			'content',
			{
				fields: [],
				kinds: [
					'member_expression',
					'subscript_expression',
					'undefined',
					'identifier',
					'declare_keyword',
					'namespace_keyword',
					'type_keyword',
					'public_keyword',
					'private_keyword',
					'protected_keyword',
					'override_keyword',
					'readonly_keyword',
					'module_keyword',
					'any_keyword',
					'number_keyword',
					'boolean_keyword',
					'string_keyword',
					'symbol_keyword',
					'export_keyword',
					'object_keyword',
					'new_keyword',
					'get_keyword',
					'set_keyword',
					'async_keyword',
					'static_keyword',
					'let_keyword',
					'object_pattern',
					'array_pattern',
					'non_null_expression'
				]
			}
		]
	],
	259: [
		['using', { fields: ['using'], kinds: [] }],
		['left', { fields: ['left'], kinds: [] }],
		['right', { fields: ['right'], kinds: [] }]
	],
	261: [
		['left', { fields: ['left'], kinds: [] }],
		['operator', { fields: ['operator'], kinds: [] }],
		['right', { fields: ['right'], kinds: [] }]
	],
	264: [['expression', { fields: ['expression'], kinds: [] }]],
	265: [
		['condition', { fields: ['condition'], kinds: [] }],
		['consequence', { fields: ['consequence'], kinds: [] }],
		['alternative', { fields: ['alternative'], kinds: [] }]
	],
	266: [
		['left', { fields: ['left'], kinds: [] }],
		['operator', { fields: ['operator'], kinds: [] }],
		['right', { fields: ['right'], kinds: [] }],
		['binaryExpressionIn', { fields: [], kinds: ['binary_expression_in'] }]
	],
	267: [
		['operator', { fields: ['operator'], kinds: [] }],
		['argument', { fields: ['argument'], kinds: [] }]
	],
	269: [['expressions', { fields: ['expression'], kinds: [] }]],
	271: [['elements', { fields: ['elements'], kinds: [] }]],
	272: [['expression', { fields: ['expression'], kinds: [] }]],
	273: [
		['pattern', { fields: ['pattern'], kinds: [] }],
		['flags', { fields: ['flags'], kinds: [] }]
	],
	276: [['elements', { fields: ['elements'], kinds: [] }]],
	277: [['expression', { fields: ['expression'], kinds: [] }]],
	278: [
		['object', { fields: ['object'], kinds: [] }],
		['property', { fields: ['property'], kinds: [] }]
	],
	279: [
		['function', { fields: ['function'], kinds: [] }],
		['typeArguments', { fields: ['type_arguments'], kinds: [] }],
		['arguments', { fields: ['arguments'], kinds: [] }]
	],
	280: [['members', { fields: ['members'], kinds: [] }]],
	281: [['elements', { fields: ['elements'], kinds: [] }]],
	282: [
		['automaticSemicolon', { fields: [], kinds: ['automatic_semicolon'] }],
		['body', { fields: ['body'], kinds: [] }]
	],
	284: [
		[
			'lhsExpression',
			{
				fields: [],
				kinds: [
					'member_expression',
					'subscript_expression',
					'undefined',
					'identifier',
					'declare_keyword',
					'namespace_keyword',
					'type_keyword',
					'public_keyword',
					'private_keyword',
					'protected_keyword',
					'override_keyword',
					'readonly_keyword',
					'module_keyword',
					'any_keyword',
					'number_keyword',
					'boolean_keyword',
					'string_keyword',
					'symbol_keyword',
					'export_keyword',
					'object_keyword',
					'new_keyword',
					'get_keyword',
					'set_keyword',
					'async_keyword',
					'static_keyword',
					'let_keyword',
					'object_pattern',
					'array_pattern',
					'non_null_expression'
				]
			}
		]
	],
	285: [
		['accessibilityModifier', { fields: ['accessibility_modifier'], kinds: [] }],
		['static', { fields: ['static'], kinds: [] }],
		['override', { fields: ['override'], kinds: [] }],
		['readonly', { fields: ['readonly'], kinds: [] }],
		['async', { fields: ['async'], kinds: [] }],
		['accessorKind', { fields: ['accessor_kind'], kinds: [] }],
		['name', { fields: ['name'], kinds: [] }],
		['optional', { fields: ['optional'], kinds: [] }],
		['typeParameters', { fields: ['type_parameters'], kinds: [] }],
		['parameters', { fields: ['parameters'], kinds: [] }],
		['returnType', { fields: ['return_type'], kinds: [] }],
		['body', { fields: ['body'], kinds: [] }]
	],
	286: [
		['key', { fields: ['key'], kinds: [] }],
		['value', { fields: ['value'], kinds: [] }]
	],
	287: [
		['key', { fields: ['key'], kinds: [] }],
		['value', { fields: ['value'], kinds: [] }]
	],
	289: [['expression', { fields: ['expression'], kinds: [] }]],
	290: [
		['decorators', { fields: ['decorator'], kinds: [] }],
		['declare', { fields: ['declare'], kinds: [] }],
		['accessibilityModifier', { fields: ['accessibility_modifier'], kinds: [] }],
		['static', { fields: ['static'], kinds: [] }],
		['override', { fields: ['override'], kinds: [] }],
		['readonly', { fields: ['readonly'], kinds: [] }],
		['abstract', { fields: ['abstract'], kinds: [] }],
		['accessor', { fields: ['accessor'], kinds: [] }],
		['name', { fields: ['name'], kinds: [] }],
		['optionality', { fields: ['optionality'], kinds: [] }],
		['type', { fields: ['type'], kinds: [] }],
		['value', { fields: ['value'], kinds: [] }]
	],
	292: [['expression', { fields: ['expression'], kinds: [] }]],
	293: [
		['accessibilityModifier', { fields: ['accessibility_modifier'], kinds: [] }],
		['static', { fields: ['static'], kinds: [] }],
		['override', { fields: ['override'], kinds: [] }],
		['readonly', { fields: ['readonly'], kinds: [] }],
		['async', { fields: ['async'], kinds: [] }],
		['accessorKind', { fields: ['accessor_kind'], kinds: [] }],
		['name', { fields: ['name'], kinds: [] }],
		['optional', { fields: ['optional'], kinds: [] }],
		['typeParameters', { fields: ['type_parameters'], kinds: [] }],
		['parameters', { fields: ['parameters'], kinds: [] }],
		['returnType', { fields: ['return_type'], kinds: [] }]
	],
	294: [
		['accessibilityModifier', { fields: ['accessibility_modifier'], kinds: [] }],
		['override', { fields: ['override'], kinds: [] }],
		['accessorKind', { fields: ['accessor_kind'], kinds: [] }],
		['name', { fields: ['name'], kinds: [] }],
		['optional', { fields: ['optional'], kinds: [] }],
		['typeParameters', { fields: ['type_parameters'], kinds: [] }],
		['parameters', { fields: ['parameters'], kinds: [] }],
		['returnType', { fields: ['return_type'], kinds: [] }]
	],
	295: [
		['async', { fields: ['async'], kinds: [] }],
		['name', { fields: ['name'], kinds: [] }],
		['typeParameters', { fields: ['type_parameters'], kinds: [] }],
		['parameters', { fields: ['parameters'], kinds: [] }],
		['returnType', { fields: ['return_type'], kinds: [] }],
		['terminator', { fields: ['terminator'], kinds: [] }]
	],
	296: [['expression', { fields: ['expression'], kinds: [] }]],
	297: [
		['typeArguments', { fields: ['type_arguments'], kinds: [] }],
		['expression', { fields: ['expression'], kinds: [] }]
	],
	298: [
		['expression', { fields: ['expression'], kinds: [] }],
		['typeAnnotation', { fields: ['type_annotation'], kinds: [] }]
	],
	299: [
		['expression', { fields: ['expression'], kinds: [] }],
		['typeAnnotation', { fields: ['type_annotation'], kinds: [] }]
	],
	300: [
		['expression', { fields: ['expression'], kinds: [] }],
		['typeArguments', { fields: ['type_arguments'], kinds: [] }]
	],
	301: [
		['name', { fields: ['name'], kinds: [] }],
		['source', { fields: ['source'], kinds: [] }]
	],
	302: [['extendsClauseSingles', { fields: [], kinds: ['extends_clause_single'] }]],
	303: [
		['value', { fields: ['value'], kinds: [] }],
		['typeArguments', { fields: ['type_arguments'], kinds: [] }]
	],
	304: [['types', { fields: ['type'], kinds: [] }]],
	305: [
		[
			'content',
			{
				fields: [],
				kinds: [
					'function_declaration',
					'generator_function_declaration',
					'class_declaration',
					'lexical_declaration',
					'variable_declaration',
					'function_signature',
					'abstract_class_declaration',
					'module',
					'internal_module',
					'type_alias_declaration',
					'enum_declaration',
					'interface_declaration',
					'import_alias',
					'ambient_declaration',
					'ambient_declaration_global',
					'ambient_declaration_module'
				]
			}
		]
	],
	306: [
		['decorators', { fields: ['decorator'], kinds: [] }],
		['name', { fields: ['name'], kinds: [] }],
		['typeParameters', { fields: ['type_parameters'], kinds: [] }],
		['heritage', { fields: ['heritage'], kinds: [] }],
		['body', { fields: ['body'], kinds: [] }]
	],
	307: [
		['name', { fields: ['name'], kinds: [] }],
		['body', { fields: ['body'], kinds: [] }]
	],
	308: [
		['name', { fields: ['name'], kinds: [] }],
		['body', { fields: ['body'], kinds: [] }]
	],
	310: [
		['name', { fields: ['name'], kinds: [] }],
		['value', { fields: ['value'], kinds: [] }],
		['terminator', { fields: ['terminator'], kinds: [] }]
	],
	311: [
		['module', { fields: ['module'], kinds: [] }],
		['name', { fields: ['name'], kinds: [] }]
	],
	312: [
		['name', { fields: ['name'], kinds: [] }],
		['typeParameters', { fields: ['type_parameters'], kinds: [] }],
		['extendsTypeClause', { fields: ['extends_type_clause'], kinds: [] }],
		['body', { fields: ['body'], kinds: [] }]
	],
	313: [['types', { fields: ['type'], kinds: [] }]],
	314: [
		['const', { fields: ['const'], kinds: [] }],
		['name', { fields: ['name'], kinds: [] }],
		['body', { fields: ['body'], kinds: [] }]
	],
	315: [['elements', { fields: ['elements'], kinds: [] }]],
	316: [
		['name', { fields: ['name'], kinds: [] }],
		['value', { fields: ['value'], kinds: [] }]
	],
	317: [
		['name', { fields: ['name'], kinds: [] }],
		['typeParameters', { fields: ['type_parameters'], kinds: [] }],
		['value', { fields: ['value'], kinds: [] }],
		['terminator', { fields: ['terminator'], kinds: [] }]
	],
	320: [
		['decorators', { fields: ['decorator'], kinds: [] }],
		['accessibilityModifier', { fields: [], kinds: ['accessibility_modifier'] }],
		['override', { fields: ['override'], kinds: [] }],
		['readonly', { fields: ['readonly'], kinds: [] }],
		['pattern', { fields: ['pattern'], kinds: [] }],
		['type', { fields: ['type'], kinds: [] }],
		['value', { fields: ['value'], kinds: [] }]
	],
	321: [
		['decorators', { fields: ['decorator'], kinds: [] }],
		['accessibilityModifier', { fields: [], kinds: ['accessibility_modifier'] }],
		['override', { fields: ['override'], kinds: [] }],
		['readonly', { fields: ['readonly'], kinds: [] }],
		['pattern', { fields: ['pattern'], kinds: [] }],
		['type', { fields: ['type'], kinds: [] }],
		['value', { fields: ['value'], kinds: [] }]
	],
	323: [['type', { fields: ['type'], kinds: [] }]],
	324: [['type', { fields: ['type'], kinds: [] }]],
	325: [['type', { fields: ['type'], kinds: [] }]],
	326: [['type', { fields: ['type'], kinds: [] }]],
	327: [
		['object', { fields: ['object'], kinds: [] }],
		['property', { fields: ['property'], kinds: [] }]
	],
	328: [
		['function', { fields: ['function'], kinds: [] }],
		['arguments', { fields: ['arguments'], kinds: [] }]
	],
	329: [['value', { fields: ['value'], kinds: [] }]],
	330: [['asserts', { fields: [], kinds: ['asserts'] }]],
	332: [
		['name', { fields: ['name'], kinds: [] }],
		['type', { fields: ['type'], kinds: [] }]
	],
	333: [
		['name', { fields: ['name'], kinds: [] }],
		['type', { fields: ['type'], kinds: [] }]
	],
	334: [['type', { fields: ['type'], kinds: [] }]],
	335: [['type', { fields: ['type'], kinds: [] }]],
	337: [
		['abstract', { fields: ['abstract'], kinds: [] }],
		['typeParameters', { fields: ['type_parameters'], kinds: [] }],
		['parameters', { fields: ['parameters'], kinds: [] }],
		['type', { fields: ['type'], kinds: [] }]
	],
	339: [['type', { fields: ['type'], kinds: [] }]],
	340: [['elements', { fields: ['elements'], kinds: [] }]],
	341: [
		['name', { fields: ['name'], kinds: [] }],
		['type', { fields: ['type'], kinds: [] }]
	],
	342: [
		['left', { fields: ['left'], kinds: [] }],
		['right', { fields: ['right'], kinds: [] }],
		['consequence', { fields: ['consequence'], kinds: [] }],
		['alternative', { fields: ['alternative'], kinds: [] }]
	],
	343: [
		['name', { fields: ['name'], kinds: [] }],
		['typeArguments', { fields: ['type_arguments'], kinds: [] }]
	],
	344: [
		['name', { fields: ['name'], kinds: [] }],
		['type', { fields: ['type'], kinds: [] }]
	],
	345: [['typePredicate', { fields: [], kinds: ['type_predicate'] }]],
	346: [
		['object', { fields: ['object'], kinds: [] }],
		['content', { fields: [], kinds: ['dot', 'qmark_dot'] }],
		['property', { fields: ['property'], kinds: [] }]
	],
	347: [
		['object', { fields: ['object'], kinds: [] }],
		['optionalChain', { fields: ['optional_chain'], kinds: [] }],
		['index', { fields: ['index'], kinds: [] }]
	],
	348: [
		['function', { fields: ['function'], kinds: [] }],
		['arguments', { fields: ['arguments'], kinds: [] }]
	],
	349: [
		['function', { fields: ['function'], kinds: [] }],
		['typeArguments', { fields: ['type_arguments'], kinds: [] }]
	],
	350: [['expression', { fields: ['expression'], kinds: [] }]],
	351: [['type', { fields: ['type'], kinds: [] }]],
	352: [
		['type', { fields: ['type'], kinds: [] }],
		['indexType', { fields: ['index_type'], kinds: [] }]
	],
	353: [
		['name', { fields: ['name'], kinds: [] }],
		['type', { fields: ['type'], kinds: [] }],
		['alias', { fields: ['alias'], kinds: [] }]
	],
	354: [
		[
			'content',
			{
				fields: [],
				kinds: [
					'literal_type_negative_number',
					'number_hex',
					'number_float_point',
					'number_float_leading_point',
					'number_float_scientific',
					'number_decimal',
					'number_binary',
					'number_octal',
					'number_bigint_hex',
					'number_bigint_binary',
					'number_bigint_octal',
					'number_bigint_decimal',
					'string_double',
					'string_single',
					'true',
					'false',
					'null',
					'undefined'
				]
			}
		]
	],
	357: [['type', { fields: ['type'], kinds: [] }]],
	358: [['type', { fields: ['type'], kinds: [] }]],
	360: [['types', { fields: [], kinds: ['types'] }]],
	361: [
		['opening', { fields: ['opening'], kinds: [] }],
		['members', { fields: ['members'], kinds: [] }],
		['closing', { fields: ['closing'], kinds: [] }]
	],
	362: [
		['typeParameters', { fields: ['type_parameters'], kinds: [] }],
		['parameters', { fields: ['parameters'], kinds: [] }],
		['returnType', { fields: ['return_type'], kinds: [] }]
	],
	363: [
		['accessibilityModifier', { fields: ['accessibility_modifier'], kinds: [] }],
		['static', { fields: ['static'], kinds: [] }],
		['override', { fields: ['override'], kinds: [] }],
		['readonly', { fields: ['readonly'], kinds: [] }],
		['name', { fields: ['name'], kinds: [] }],
		['optional', { fields: ['optional'], kinds: [] }],
		['type', { fields: ['type'], kinds: [] }]
	],
	364: [['elements', { fields: ['elements'], kinds: [] }]],
	365: [
		['const', { fields: ['const'], kinds: [] }],
		['name', { fields: ['name'], kinds: [] }],
		['constraint', { fields: ['constraint'], kinds: [] }],
		['value', { fields: ['value'], kinds: [] }]
	],
	366: [['type', { fields: ['type'], kinds: [] }]],
	367: [
		['content', { fields: [], kinds: ['extends_keyword', 'colon'] }],
		['type', { fields: ['type'], kinds: [] }]
	],
	368: [
		['abstract', { fields: ['abstract'], kinds: [] }],
		['typeParameters', { fields: ['type_parameters'], kinds: [] }],
		['parameters', { fields: ['parameters'], kinds: [] }],
		['type', { fields: ['type'], kinds: [] }]
	],
	370: [['type', { fields: ['type'], kinds: [] }]],
	371: [['tupleTypeMembers', { fields: [], kinds: ['tuple_type_members'] }]],
	372: [['type', { fields: ['type'], kinds: [] }]],
	373: [
		['left', { fields: ['left'], kinds: [] }],
		['right', { fields: ['right'], kinds: [] }]
	],
	374: [
		['left', { fields: ['left'], kinds: [] }],
		['right', { fields: ['right'], kinds: [] }]
	],
	375: [
		['typeParameters', { fields: ['type_parameters'], kinds: [] }],
		['parameters', { fields: ['parameters'], kinds: [] }],
		['returnType', { fields: ['return_type'], kinds: [] }]
	],
	376: [['items', { fields: ['item'], kinds: [] }]],
	377: [['items', { fields: ['item'], kinds: [] }]],
	379: [['items', { fields: ['item'], kinds: [] }]],
	380: [['name', { fields: ['name'], kinds: [] }]],
	382: [['items', { fields: ['item'], kinds: [] }]],
	383: [['items', { fields: ['item'], kinds: [] }]],
	384: [['items', { fields: ['item'], kinds: [] }]],
	385: [['items', { fields: ['item'], kinds: [] }]],
	386: [['content', { fields: [], kinds: ['namespace_import', 'named_imports'] }]],
	387: [
		['parameter', { fields: ['parameter'], kinds: [] }],
		['type', { fields: ['type'], kinds: [] }]
	],
	388: [['body', { fields: ['body'], kinds: [] }]],
	389: [
		['name', { fields: ['name'], kinds: [] }],
		['type', { fields: ['type'], kinds: [] }],
		['terminator', { fields: ['terminator'], kinds: [] }]
	],
	390: [['items', { fields: ['item'], kinds: [] }]],
	392: [
		['name', { fields: ['name'], kinds: [] }],
		['terminator', { fields: ['terminator'], kinds: [] }]
	],
	393: [
		['exportClause', { fields: ['export_clause'], kinds: [] }],
		['source', { fields: ['source'], kinds: [] }],
		['terminator', { fields: ['terminator'], kinds: [] }]
	],
	394: [
		['expression', { fields: ['expression'], kinds: [] }],
		['terminator', { fields: ['terminator'], kinds: [] }]
	],
	395: [
		['operator', { fields: ['operator'], kinds: [] }],
		['argument', { fields: ['argument'], kinds: [] }]
	],
	397: [
		['left', { fields: ['left'], kinds: [] }],
		['right', { fields: ['right'], kinds: [] }]
	],
	399: [
		['decorators', { fields: ['decorator'], kinds: [] }],
		['methodDefinition', { fields: [], kinds: ['method_definition'] }],
		['terminator', { fields: ['terminator'], kinds: [] }]
	],
	400: [
		['methodSignature', { fields: [], kinds: ['method_signature'] }],
		['terminator', { fields: ['terminator'], kinds: [] }]
	],
	401: [
		['member', { fields: ['member'], kinds: [] }],
		['terminator', { fields: ['terminator'], kinds: [] }]
	],
	402: [
		['sign', { fields: ['sign'], kinds: [] }],
		['readonly', { fields: ['readonly'], kinds: [] }],
		['name', { fields: ['name'], kinds: [] }],
		['indexType', { fields: ['index_type'], kinds: [] }],
		['type', { fields: ['type'], kinds: [] }]
	],
	403: [
		['sign', { fields: ['sign'], kinds: [] }],
		['readonly', { fields: ['readonly'], kinds: [] }],
		['mappedTypeClause', { fields: [], kinds: ['mapped_type_clause'] }],
		['type', { fields: ['type'], kinds: [] }]
	],
	404: [
		['importClause', { fields: [], kinds: ['import_clause'] }],
		['source', { fields: ['source'], kinds: [] }]
	],
	405: [
		[
			'expression',
			{
				fields: [],
				kinds: [
					'as_expression',
					'satisfies_expression',
					'instantiation_expression',
					'internal_module',
					'type_assertion',
					'identifier',
					'subscript_expression',
					'member_expression',
					'parenthesized_expression_typed',
					'parenthesized_expression_sequence',
					'undefined',
					'declare_keyword',
					'namespace_keyword',
					'type_keyword',
					'public_keyword',
					'private_keyword',
					'protected_keyword',
					'override_keyword',
					'readonly_keyword',
					'module_keyword',
					'any_keyword',
					'number_keyword',
					'boolean_keyword',
					'string_keyword',
					'symbol_keyword',
					'export_keyword',
					'object_keyword',
					'new_keyword',
					'get_keyword',
					'set_keyword',
					'async_keyword',
					'static_keyword',
					'let_keyword',
					'this',
					'super',
					'number_hex',
					'number_float_point',
					'number_float_leading_point',
					'number_float_scientific',
					'number_decimal',
					'number_binary',
					'number_octal',
					'number_bigint_hex',
					'number_bigint_binary',
					'number_bigint_octal',
					'number_bigint_decimal',
					'string_double',
					'string_single',
					'template_string',
					'regex',
					'true',
					'false',
					'null',
					'object',
					'array',
					'function_expression',
					'arrow_function',
					'generator_function',
					'class',
					'meta_property_new_target',
					'meta_property_import_meta',
					'call_expression_call',
					'call_expression_template_call',
					'call_expression_member',
					'non_null_expression',
					'assignment_expression',
					'augmented_assignment_expression',
					'await_expression',
					'unary_expression',
					'binary_expression',
					'ternary_expression',
					'update_expression_postfix',
					'update_expression_prefix',
					'new_expression',
					'yield_expression'
				]
			}
		]
	],
	407: [
		['importKind', { fields: ['import_kind'], kinds: [] }],
		['name', { fields: ['name'], kinds: [] }]
	],
	408: [
		['importKind', { fields: ['import_kind'], kinds: [] }],
		['name', { fields: ['name'], kinds: [] }],
		['alias', { fields: ['alias'], kinds: [] }]
	],
	409: [
		[
			'expression',
			{
				fields: [],
				kinds: [
					'as_expression',
					'satisfies_expression',
					'instantiation_expression',
					'internal_module',
					'type_assertion',
					'identifier',
					'subscript_expression',
					'member_expression',
					'parenthesized_expression_typed',
					'parenthesized_expression_sequence',
					'undefined',
					'declare_keyword',
					'namespace_keyword',
					'type_keyword',
					'public_keyword',
					'private_keyword',
					'protected_keyword',
					'override_keyword',
					'readonly_keyword',
					'module_keyword',
					'any_keyword',
					'number_keyword',
					'boolean_keyword',
					'string_keyword',
					'symbol_keyword',
					'export_keyword',
					'object_keyword',
					'new_keyword',
					'get_keyword',
					'set_keyword',
					'async_keyword',
					'static_keyword',
					'let_keyword',
					'this',
					'super',
					'number_hex',
					'number_float_point',
					'number_float_leading_point',
					'number_float_scientific',
					'number_decimal',
					'number_binary',
					'number_octal',
					'number_bigint_hex',
					'number_bigint_binary',
					'number_bigint_octal',
					'number_bigint_decimal',
					'string_double',
					'string_single',
					'template_string',
					'regex',
					'true',
					'false',
					'null',
					'object',
					'array',
					'function_expression',
					'arrow_function',
					'generator_function',
					'class',
					'meta_property_new_target',
					'meta_property_import_meta',
					'call_expression_call',
					'call_expression_template_call',
					'call_expression_member',
					'non_null_expression',
					'assignment_expression',
					'augmented_assignment_expression',
					'await_expression',
					'unary_expression',
					'binary_expression',
					'ternary_expression',
					'update_expression_postfix',
					'update_expression_prefix',
					'new_expression',
					'yield_expression'
				]
			}
		],
		['type', { fields: ['type'], kinds: [] }]
	],
	410: [['sequenceExpression', { fields: [], kinds: ['sequence_expression'] }]],
	411: [
		['function', { fields: ['function'], kinds: [] }],
		['typeArguments', { fields: ['type_arguments'], kinds: [] }],
		['arguments', { fields: ['arguments'], kinds: [] }]
	],
	412: [
		['function', { fields: ['function'], kinds: [] }],
		['arguments', { fields: ['arguments'], kinds: [] }]
	],
	413: [
		['function', { fields: ['function'], kinds: [] }],
		['typeArguments', { fields: ['type_arguments'], kinds: [] }],
		['arguments', { fields: ['arguments'], kinds: [] }]
	],
	414: [['elements', { fields: ['elements'], kinds: [] }]],
	415: [['elements', { fields: ['elements'], kinds: [] }]],
	416: [
		['argument', { fields: ['argument'], kinds: [] }],
		['operator', { fields: ['operator'], kinds: [] }]
	],
	417: [
		['operator', { fields: ['operator'], kinds: [] }],
		['argument', { fields: ['argument'], kinds: [] }]
	],
	418: [['parameter', { fields: ['parameter'], kinds: [] }]],
	419: [
		['extendsClause', { fields: ['extends_clause'], kinds: [] }],
		['implementsClause', { fields: [], kinds: ['implements_clause'] }]
	],
	420: [
		['identifier', { fields: [], kinds: ['identifier', 'type_keyword'] }],
		['importClauseGroup', { fields: [], kinds: ['import_clause_group'] }]
	],
	421: [
		[
			'content',
			{
				fields: [],
				kinds: [
					'export_statement_default_from_star_from',
					'export_statement_default_from_ns_from',
					'export_statement_default_from_clause_from',
					'export_clause'
				]
			}
		],
		['automaticSemicolon', { fields: [], kinds: ['automatic_semicolon', 'semi'] }]
	],
	422: [
		['decorators', { fields: ['decorator'], kinds: [] }],
		[
			'content',
			{
				fields: [],
				kinds: [
					'function_declaration',
					'generator_function_declaration',
					'class_declaration',
					'lexical_declaration',
					'variable_declaration',
					'function_signature',
					'abstract_class_declaration',
					'module',
					'internal_module',
					'type_alias_declaration',
					'enum_declaration',
					'interface_declaration',
					'import_alias',
					'ambient_declaration',
					'export_statement_default_declaration_default_kw'
				]
			}
		]
	],
	423: [['source', { fields: ['source'], kinds: [] }]],
	424: [
		['namespaceExport', { fields: [], kinds: ['namespace_export'] }],
		['source', { fields: ['source'], kinds: [] }]
	],
	425: [
		['exportClause', { fields: [], kinds: ['export_clause'] }],
		['source', { fields: ['source'], kinds: [] }]
	],
	426: [
		[
			'content',
			{
				fields: [],
				kinds: [
					'function_declaration',
					'generator_function_declaration',
					'class_declaration',
					'lexical_declaration',
					'variable_declaration',
					'function_signature',
					'abstract_class_declaration',
					'module',
					'internal_module',
					'type_alias_declaration',
					'enum_declaration',
					'interface_declaration',
					'import_alias',
					'ambient_declaration',
					'export_statement_default_declaration_default_kw_value'
				]
			}
		]
	],
	427: [
		['value', { fields: ['value'], kinds: [] }],
		['automaticSemicolon', { fields: [], kinds: ['automatic_semicolon', 'semi'] }]
	],
	428: [
		['name', { fields: ['name'], kinds: [] }],
		['type', { fields: ['type'], kinds: [] }],
		['value', { fields: ['value'], kinds: [] }]
	],
	429: [
		['name', { fields: ['name'], kinds: [] }],
		['type', { fields: ['type'], kinds: [] }]
	],
	432: [
		['left', { fields: ['left'], kinds: [] }],
		['operator', { fields: ['operator'], kinds: [] }],
		['right', { fields: ['right'], kinds: [] }]
	],
	433: [
		['left', { fields: ['left'], kinds: [] }],
		['value', { fields: ['value'], kinds: [] }],
		['operator', { fields: ['operator'], kinds: [] }],
		['right', { fields: ['right'], kinds: [] }]
	],
	434: [
		['kind', { fields: ['kind'], kinds: [] }],
		['left', { fields: ['left'], kinds: [] }],
		['automaticSemicolon', { fields: [], kinds: ['automatic_semicolon'] }],
		['operator', { fields: ['operator'], kinds: [] }],
		['right', { fields: ['right'], kinds: [] }]
	],
	460: [['content', { fields: ['content'], kinds: [] }]],
	462: [['content', { fields: ['content'], kinds: [] }]],
	463: [['content', { fields: ['content'], kinds: [] }]],
	464: [['content', { fields: ['content'], kinds: [] }]],
	465: [['content', { fields: ['content'], kinds: [] }]],
	467: [['content', { fields: ['content'], kinds: [] }]]
});

export const { isNode } = bindRuntime<TypescriptTypeMap>();
