// Auto-generated by @sittir/codegen — do not edit

import type { RustGrammar } from './grammar.js';
import type { NodeData as BaseNodeData, NodeFields as BaseNodeFields, TreeNode as BaseTreeNode, NodeKind } from '@sittir/types';

export type { RustGrammar };

// Grammar-bound type aliases — use NodeData<K> instead of BaseNodeData<G, K>
export type NodeData<K extends NodeKind<RustGrammar>> = BaseNodeData<RustGrammar, K>;
export type NodeFields<K extends NodeKind<RustGrammar>> = BaseNodeFields<RustGrammar, K>;
export type TreeNode<K extends NodeKind<RustGrammar>> = BaseTreeNode<RustGrammar, K>;

/** All named node kinds in this grammar. */
export const enum SyntaxKind {
  AbstractType = 'abstract_type',
  Arguments = 'arguments',
  ArrayExpression = 'array_expression',
  ArrayType = 'array_type',
  AssignmentExpression = 'assignment_expression',
  AssociatedType = 'associated_type',
  AsyncBlock = 'async_block',
  Attribute = 'attribute',
  AttributeItem = 'attribute_item',
  AwaitExpression = 'await_expression',
  BaseFieldInitializer = 'base_field_initializer',
  BinaryExpression = 'binary_expression',
  Block = 'block',
  BlockComment = 'block_comment',
  BoundedType = 'bounded_type',
  BracketedType = 'bracketed_type',
  BreakExpression = 'break_expression',
  CallExpression = 'call_expression',
  CapturedPattern = 'captured_pattern',
  ClosureExpression = 'closure_expression',
  ClosureParameters = 'closure_parameters',
  CompoundAssignmentExpr = 'compound_assignment_expr',
  ConstBlock = 'const_block',
  ConstItem = 'const_item',
  ConstParameter = 'const_parameter',
  ContinueExpression = 'continue_expression',
  DeclarationList = 'declaration_list',
  DynamicType = 'dynamic_type',
  ElseClause = 'else_clause',
  EnumItem = 'enum_item',
  EnumVariant = 'enum_variant',
  EnumVariantList = 'enum_variant_list',
  ExpressionStatement = 'expression_statement',
  ExternCrateDeclaration = 'extern_crate_declaration',
  ExternModifier = 'extern_modifier',
  FieldDeclaration = 'field_declaration',
  FieldDeclarationList = 'field_declaration_list',
  FieldExpression = 'field_expression',
  FieldInitializer = 'field_initializer',
  FieldInitializerList = 'field_initializer_list',
  FieldPattern = 'field_pattern',
  ForExpression = 'for_expression',
  ForLifetimes = 'for_lifetimes',
  ForeignModItem = 'foreign_mod_item',
  FunctionItem = 'function_item',
  FunctionModifiers = 'function_modifiers',
  FunctionSignatureItem = 'function_signature_item',
  FunctionType = 'function_type',
  GenBlock = 'gen_block',
  GenericFunction = 'generic_function',
  GenericPattern = 'generic_pattern',
  GenericType = 'generic_type',
  GenericTypeWithTurbofish = 'generic_type_with_turbofish',
  HigherRankedTraitBound = 'higher_ranked_trait_bound',
  IfExpression = 'if_expression',
  ImplItem = 'impl_item',
  IndexExpression = 'index_expression',
  InnerAttributeItem = 'inner_attribute_item',
  Label = 'label',
  LetChain = 'let_chain',
  LetCondition = 'let_condition',
  LetDeclaration = 'let_declaration',
  Lifetime = 'lifetime',
  LifetimeParameter = 'lifetime_parameter',
  LineComment = 'line_comment',
  LoopExpression = 'loop_expression',
  MacroDefinition = 'macro_definition',
  MacroInvocation = 'macro_invocation',
  MacroRule = 'macro_rule',
  MatchArm = 'match_arm',
  MatchBlock = 'match_block',
  MatchExpression = 'match_expression',
  MatchPattern = 'match_pattern',
  ModItem = 'mod_item',
  MutPattern = 'mut_pattern',
  NegativeLiteral = 'negative_literal',
  OrPattern = 'or_pattern',
  OrderedFieldDeclarationList = 'ordered_field_declaration_list',
  Parameter = 'parameter',
  Parameters = 'parameters',
  ParenthesizedExpression = 'parenthesized_expression',
  PointerType = 'pointer_type',
  QualifiedType = 'qualified_type',
  RangeExpression = 'range_expression',
  RangePattern = 'range_pattern',
  RawStringLiteral = 'raw_string_literal',
  RefPattern = 'ref_pattern',
  ReferenceExpression = 'reference_expression',
  ReferencePattern = 'reference_pattern',
  ReferenceType = 'reference_type',
  RemovedTraitBound = 'removed_trait_bound',
  ReturnExpression = 'return_expression',
  ScopedIdentifier = 'scoped_identifier',
  ScopedTypeIdentifier = 'scoped_type_identifier',
  ScopedUseList = 'scoped_use_list',
  SelfParameter = 'self_parameter',
  ShorthandFieldInitializer = 'shorthand_field_initializer',
  SlicePattern = 'slice_pattern',
  SourceFile = 'source_file',
  StaticItem = 'static_item',
  StringLiteral = 'string_literal',
  StructExpression = 'struct_expression',
  StructItem = 'struct_item',
  StructPattern = 'struct_pattern',
  TokenBindingPattern = 'token_binding_pattern',
  TokenRepetition = 'token_repetition',
  TokenRepetitionPattern = 'token_repetition_pattern',
  TokenTree = 'token_tree',
  TokenTreePattern = 'token_tree_pattern',
  TraitBounds = 'trait_bounds',
  TraitItem = 'trait_item',
  TryBlock = 'try_block',
  TryExpression = 'try_expression',
  TupleExpression = 'tuple_expression',
  TuplePattern = 'tuple_pattern',
  TupleStructPattern = 'tuple_struct_pattern',
  TupleType = 'tuple_type',
  TypeArguments = 'type_arguments',
  TypeBinding = 'type_binding',
  TypeCastExpression = 'type_cast_expression',
  TypeItem = 'type_item',
  TypeParameter = 'type_parameter',
  TypeParameters = 'type_parameters',
  UnaryExpression = 'unary_expression',
  UnionItem = 'union_item',
  UnsafeBlock = 'unsafe_block',
  UseAsClause = 'use_as_clause',
  UseBounds = 'use_bounds',
  UseDeclaration = 'use_declaration',
  UseList = 'use_list',
  UseWildcard = 'use_wildcard',
  VariadicParameter = 'variadic_parameter',
  VisibilityModifier = 'visibility_modifier',
  WhereClause = 'where_clause',
  WherePredicate = 'where_predicate',
  WhileExpression = 'while_expression',
  YieldExpression = 'yield_expression',
  BooleanLiteral = 'boolean_literal',
  EmptyStatement = 'empty_statement',
  FragmentSpecifier = 'fragment_specifier',
  InnerDocCommentMarker = 'inner_doc_comment_marker',
  NeverType = 'never_type',
  OuterDocCommentMarker = 'outer_doc_comment_marker',
  RemainingFieldPattern = 'remaining_field_pattern',
  UnitExpression = 'unit_expression',
  UnitType = 'unit_type',
  CharLiteral = 'char_literal',
  Crate = 'crate',
  DocComment = 'doc_comment',
  EscapeSequence = 'escape_sequence',
  FieldIdentifier = 'field_identifier',
  FloatLiteral = 'float_literal',
  Identifier = 'identifier',
  IntegerLiteral = 'integer_literal',
  Metavariable = 'metavariable',
  MutableSpecifier = 'mutable_specifier',
  PrimitiveType = 'primitive_type',
  Self = 'self',
  Shebang = 'shebang',
  ShorthandFieldIdentifier = 'shorthand_field_identifier',
  StringContent = 'string_content',
  Super = 'super',
  TypeIdentifier = 'type_identifier',
}

// Scoped enums per supertype
export const enum DeclarationStatementKind {
  AssociatedType = 'associated_type',
  AttributeItem = 'attribute_item',
  ConstItem = 'const_item',
  EmptyStatement = 'empty_statement',
  EnumItem = 'enum_item',
  ExternCrateDeclaration = 'extern_crate_declaration',
  ForeignModItem = 'foreign_mod_item',
  FunctionItem = 'function_item',
  FunctionSignatureItem = 'function_signature_item',
  ImplItem = 'impl_item',
  InnerAttributeItem = 'inner_attribute_item',
  LetDeclaration = 'let_declaration',
  MacroDefinition = 'macro_definition',
  MacroInvocation = 'macro_invocation',
  ModItem = 'mod_item',
  StaticItem = 'static_item',
  StructItem = 'struct_item',
  TraitItem = 'trait_item',
  TypeItem = 'type_item',
  UnionItem = 'union_item',
  UseDeclaration = 'use_declaration',
}

export const enum ExpressionKind {
  Literal = '_literal',
  ArrayExpression = 'array_expression',
  AssignmentExpression = 'assignment_expression',
  AsyncBlock = 'async_block',
  AwaitExpression = 'await_expression',
  BinaryExpression = 'binary_expression',
  Block = 'block',
  BreakExpression = 'break_expression',
  CallExpression = 'call_expression',
  ClosureExpression = 'closure_expression',
  CompoundAssignmentExpr = 'compound_assignment_expr',
  ConstBlock = 'const_block',
  ContinueExpression = 'continue_expression',
  FieldExpression = 'field_expression',
  ForExpression = 'for_expression',
  GenBlock = 'gen_block',
  GenericFunction = 'generic_function',
  Identifier = 'identifier',
  IfExpression = 'if_expression',
  IndexExpression = 'index_expression',
  LoopExpression = 'loop_expression',
  MacroInvocation = 'macro_invocation',
  MatchExpression = 'match_expression',
  Metavariable = 'metavariable',
  ParenthesizedExpression = 'parenthesized_expression',
  RangeExpression = 'range_expression',
  ReferenceExpression = 'reference_expression',
  ReturnExpression = 'return_expression',
  ScopedIdentifier = 'scoped_identifier',
  Self = 'self',
  StructExpression = 'struct_expression',
  TryBlock = 'try_block',
  TryExpression = 'try_expression',
  TupleExpression = 'tuple_expression',
  TypeCastExpression = 'type_cast_expression',
  UnaryExpression = 'unary_expression',
  UnitExpression = 'unit_expression',
  UnsafeBlock = 'unsafe_block',
  WhileExpression = 'while_expression',
  YieldExpression = 'yield_expression',
}

export const enum LiteralKind {
  BooleanLiteral = 'boolean_literal',
  CharLiteral = 'char_literal',
  FloatLiteral = 'float_literal',
  IntegerLiteral = 'integer_literal',
  RawStringLiteral = 'raw_string_literal',
  StringLiteral = 'string_literal',
}

export const enum LiteralPatternKind {
  BooleanLiteral = 'boolean_literal',
  CharLiteral = 'char_literal',
  FloatLiteral = 'float_literal',
  IntegerLiteral = 'integer_literal',
  NegativeLiteral = 'negative_literal',
  RawStringLiteral = 'raw_string_literal',
  StringLiteral = 'string_literal',
}

export const enum PatternKind {
  LiteralPattern = '_literal_pattern',
  CapturedPattern = 'captured_pattern',
  ConstBlock = 'const_block',
  GenericPattern = 'generic_pattern',
  Identifier = 'identifier',
  MacroInvocation = 'macro_invocation',
  MutPattern = 'mut_pattern',
  OrPattern = 'or_pattern',
  RangePattern = 'range_pattern',
  RefPattern = 'ref_pattern',
  ReferencePattern = 'reference_pattern',
  RemainingFieldPattern = 'remaining_field_pattern',
  ScopedIdentifier = 'scoped_identifier',
  SlicePattern = 'slice_pattern',
  StructPattern = 'struct_pattern',
  TuplePattern = 'tuple_pattern',
  TupleStructPattern = 'tuple_struct_pattern',
}

export const enum TypeKind {
  AbstractType = 'abstract_type',
  ArrayType = 'array_type',
  BoundedType = 'bounded_type',
  DynamicType = 'dynamic_type',
  FunctionType = 'function_type',
  GenericType = 'generic_type',
  MacroInvocation = 'macro_invocation',
  Metavariable = 'metavariable',
  NeverType = 'never_type',
  PointerType = 'pointer_type',
  PrimitiveType = 'primitive_type',
  ReferenceType = 'reference_type',
  RemovedTraitBound = 'removed_trait_bound',
  ScopedTypeIdentifier = 'scoped_type_identifier',
  TupleType = 'tuple_type',
  TypeIdentifier = 'type_identifier',
  UnitType = 'unit_type',
}

// Node types — grammar-derived, interface for compiler caching
/** @see NodeData<'abstract_type'> — interface extends for compiler caching */
export interface AbstractType extends NodeData<'abstract_type'> {}
/** @see NodeData<'arguments'> — interface extends for compiler caching */
export interface Arguments extends NodeData<'arguments'> {}
/** @see NodeData<'array_expression'> — interface extends for compiler caching */
export interface ArrayExpression extends NodeData<'array_expression'> {}
/** @see NodeData<'array_type'> — interface extends for compiler caching */
export interface ArrayType extends NodeData<'array_type'> {}
/** @see NodeData<'assignment_expression'> — interface extends for compiler caching */
export interface AssignmentExpression extends NodeData<'assignment_expression'> {}
/** @see NodeData<'associated_type'> — interface extends for compiler caching */
export interface AssociatedType extends NodeData<'associated_type'> {}
/** @see NodeData<'async_block'> — interface extends for compiler caching */
export interface AsyncBlock extends NodeData<'async_block'> {}
/** @see NodeData<'attribute'> — interface extends for compiler caching */
export interface Attribute extends NodeData<'attribute'> {}
/** @see NodeData<'attribute_item'> — interface extends for compiler caching */
export interface AttributeItem extends NodeData<'attribute_item'> {}
/** @see NodeData<'await_expression'> — interface extends for compiler caching */
export interface AwaitExpression extends NodeData<'await_expression'> {}
/** @see NodeData<'base_field_initializer'> — interface extends for compiler caching */
export interface BaseFieldInitializer extends NodeData<'base_field_initializer'> {}
/** @see NodeData<'binary_expression'> — interface extends for compiler caching */
export interface BinaryExpression extends NodeData<'binary_expression'> {}
/** @see NodeData<'block'> — interface extends for compiler caching */
export interface Block extends NodeData<'block'> {}
/** @see NodeData<'block_comment'> — interface extends for compiler caching */
export interface BlockComment extends NodeData<'block_comment'> {}
/** @see NodeData<'bounded_type'> — interface extends for compiler caching */
export interface BoundedType extends NodeData<'bounded_type'> {}
/** @see NodeData<'bracketed_type'> — interface extends for compiler caching */
export interface BracketedType extends NodeData<'bracketed_type'> {}
/** @see NodeData<'break_expression'> — interface extends for compiler caching */
export interface BreakExpression extends NodeData<'break_expression'> {}
/** @see NodeData<'call_expression'> — interface extends for compiler caching */
export interface CallExpression extends NodeData<'call_expression'> {}
/** @see NodeData<'captured_pattern'> — interface extends for compiler caching */
export interface CapturedPattern extends NodeData<'captured_pattern'> {}
/** @see NodeData<'closure_expression'> — interface extends for compiler caching */
export interface ClosureExpression extends NodeData<'closure_expression'> {}
/** @see NodeData<'closure_parameters'> — interface extends for compiler caching */
export interface ClosureParameters extends NodeData<'closure_parameters'> {}
/** @see NodeData<'compound_assignment_expr'> — interface extends for compiler caching */
export interface CompoundAssignmentExpr extends NodeData<'compound_assignment_expr'> {}
/** @see NodeData<'const_block'> — interface extends for compiler caching */
export interface ConstBlock extends NodeData<'const_block'> {}
/** @see NodeData<'const_item'> — interface extends for compiler caching */
export interface ConstItem extends NodeData<'const_item'> {}
/** @see NodeData<'const_parameter'> — interface extends for compiler caching */
export interface ConstParameter extends NodeData<'const_parameter'> {}
/** @see NodeData<'continue_expression'> — interface extends for compiler caching */
export interface ContinueExpression extends NodeData<'continue_expression'> {}
/** @see NodeData<'declaration_list'> — interface extends for compiler caching */
export interface DeclarationList extends NodeData<'declaration_list'> {}
/** @see NodeData<'dynamic_type'> — interface extends for compiler caching */
export interface DynamicType extends NodeData<'dynamic_type'> {}
/** @see NodeData<'else_clause'> — interface extends for compiler caching */
export interface ElseClause extends NodeData<'else_clause'> {}
/** @see NodeData<'enum_item'> — interface extends for compiler caching */
export interface EnumItem extends NodeData<'enum_item'> {}
/** @see NodeData<'enum_variant'> — interface extends for compiler caching */
export interface EnumVariant extends NodeData<'enum_variant'> {}
/** @see NodeData<'enum_variant_list'> — interface extends for compiler caching */
export interface EnumVariantList extends NodeData<'enum_variant_list'> {}
/** @see NodeData<'expression_statement'> — interface extends for compiler caching */
export interface ExpressionStatement extends NodeData<'expression_statement'> {}
/** @see NodeData<'extern_crate_declaration'> — interface extends for compiler caching */
export interface ExternCrateDeclaration extends NodeData<'extern_crate_declaration'> {}
/** @see NodeData<'extern_modifier'> — interface extends for compiler caching */
export interface ExternModifier extends NodeData<'extern_modifier'> {}
/** @see NodeData<'field_declaration'> — interface extends for compiler caching */
export interface FieldDeclaration extends NodeData<'field_declaration'> {}
/** @see NodeData<'field_declaration_list'> — interface extends for compiler caching */
export interface FieldDeclarationList extends NodeData<'field_declaration_list'> {}
/** @see NodeData<'field_expression'> — interface extends for compiler caching */
export interface FieldExpression extends NodeData<'field_expression'> {}
/** @see NodeData<'field_initializer'> — interface extends for compiler caching */
export interface FieldInitializer extends NodeData<'field_initializer'> {}
/** @see NodeData<'field_initializer_list'> — interface extends for compiler caching */
export interface FieldInitializerList extends NodeData<'field_initializer_list'> {}
/** @see NodeData<'field_pattern'> — interface extends for compiler caching */
export interface FieldPattern extends NodeData<'field_pattern'> {}
/** @see NodeData<'for_expression'> — interface extends for compiler caching */
export interface ForExpression extends NodeData<'for_expression'> {}
/** @see NodeData<'for_lifetimes'> — interface extends for compiler caching */
export interface ForLifetimes extends NodeData<'for_lifetimes'> {}
/** @see NodeData<'foreign_mod_item'> — interface extends for compiler caching */
export interface ForeignModItem extends NodeData<'foreign_mod_item'> {}
/** @see NodeData<'function_item'> — interface extends for compiler caching */
export interface FunctionItem extends NodeData<'function_item'> {}
/** @see NodeData<'function_modifiers'> — interface extends for compiler caching */
export interface FunctionModifiers extends NodeData<'function_modifiers'> {}
/** @see NodeData<'function_signature_item'> — interface extends for compiler caching */
export interface FunctionSignatureItem extends NodeData<'function_signature_item'> {}
/** @see NodeData<'function_type'> — interface extends for compiler caching */
export interface FunctionType extends NodeData<'function_type'> {}
/** @see NodeData<'gen_block'> — interface extends for compiler caching */
export interface GenBlock extends NodeData<'gen_block'> {}
/** @see NodeData<'generic_function'> — interface extends for compiler caching */
export interface GenericFunction extends NodeData<'generic_function'> {}
/** @see NodeData<'generic_pattern'> — interface extends for compiler caching */
export interface GenericPattern extends NodeData<'generic_pattern'> {}
/** @see NodeData<'generic_type'> — interface extends for compiler caching */
export interface GenericType extends NodeData<'generic_type'> {}
/** @see NodeData<'generic_type_with_turbofish'> — interface extends for compiler caching */
export interface GenericTypeWithTurbofish extends NodeData<'generic_type_with_turbofish'> {}
/** @see NodeData<'higher_ranked_trait_bound'> — interface extends for compiler caching */
export interface HigherRankedTraitBound extends NodeData<'higher_ranked_trait_bound'> {}
/** @see NodeData<'if_expression'> — interface extends for compiler caching */
export interface IfExpression extends NodeData<'if_expression'> {}
/** @see NodeData<'impl_item'> — interface extends for compiler caching */
export interface ImplItem extends NodeData<'impl_item'> {}
/** @see NodeData<'index_expression'> — interface extends for compiler caching */
export interface IndexExpression extends NodeData<'index_expression'> {}
/** @see NodeData<'inner_attribute_item'> — interface extends for compiler caching */
export interface InnerAttributeItem extends NodeData<'inner_attribute_item'> {}
/** @see NodeData<'label'> — interface extends for compiler caching */
export interface Label extends NodeData<'label'> {}
/** @see NodeData<'let_chain'> — interface extends for compiler caching */
export interface LetChain extends NodeData<'let_chain'> {}
/** @see NodeData<'let_condition'> — interface extends for compiler caching */
export interface LetCondition extends NodeData<'let_condition'> {}
/** @see NodeData<'let_declaration'> — interface extends for compiler caching */
export interface LetDeclaration extends NodeData<'let_declaration'> {}
/** @see NodeData<'lifetime'> — interface extends for compiler caching */
export interface Lifetime extends NodeData<'lifetime'> {}
/** @see NodeData<'lifetime_parameter'> — interface extends for compiler caching */
export interface LifetimeParameter extends NodeData<'lifetime_parameter'> {}
/** @see NodeData<'line_comment'> — interface extends for compiler caching */
export interface LineComment extends NodeData<'line_comment'> {}
/** @see NodeData<'loop_expression'> — interface extends for compiler caching */
export interface LoopExpression extends NodeData<'loop_expression'> {}
/** @see NodeData<'macro_definition'> — interface extends for compiler caching */
export interface MacroDefinition extends NodeData<'macro_definition'> {}
/** @see NodeData<'macro_invocation'> — interface extends for compiler caching */
export interface MacroInvocation extends NodeData<'macro_invocation'> {}
/** @see NodeData<'macro_rule'> — interface extends for compiler caching */
export interface MacroRule extends NodeData<'macro_rule'> {}
/** @see NodeData<'match_arm'> — interface extends for compiler caching */
export interface MatchArm extends NodeData<'match_arm'> {}
/** @see NodeData<'match_block'> — interface extends for compiler caching */
export interface MatchBlock extends NodeData<'match_block'> {}
/** @see NodeData<'match_expression'> — interface extends for compiler caching */
export interface MatchExpression extends NodeData<'match_expression'> {}
/** @see NodeData<'match_pattern'> — interface extends for compiler caching */
export interface MatchPattern extends NodeData<'match_pattern'> {}
/** @see NodeData<'mod_item'> — interface extends for compiler caching */
export interface ModItem extends NodeData<'mod_item'> {}
/** @see NodeData<'mut_pattern'> — interface extends for compiler caching */
export interface MutPattern extends NodeData<'mut_pattern'> {}
/** @see NodeData<'negative_literal'> — interface extends for compiler caching */
export interface NegativeLiteral extends NodeData<'negative_literal'> {}
/** @see NodeData<'or_pattern'> — interface extends for compiler caching */
export interface OrPattern extends NodeData<'or_pattern'> {}
/** @see NodeData<'ordered_field_declaration_list'> — interface extends for compiler caching */
export interface OrderedFieldDeclarationList extends NodeData<'ordered_field_declaration_list'> {}
/** @see NodeData<'parameter'> — interface extends for compiler caching */
export interface Parameter extends NodeData<'parameter'> {}
/** @see NodeData<'parameters'> — interface extends for compiler caching */
export interface Parameters extends NodeData<'parameters'> {}
/** @see NodeData<'parenthesized_expression'> — interface extends for compiler caching */
export interface ParenthesizedExpression extends NodeData<'parenthesized_expression'> {}
/** @see NodeData<'pointer_type'> — interface extends for compiler caching */
export interface PointerType extends NodeData<'pointer_type'> {}
/** @see NodeData<'qualified_type'> — interface extends for compiler caching */
export interface QualifiedType extends NodeData<'qualified_type'> {}
/** @see NodeData<'range_expression'> — interface extends for compiler caching */
export interface RangeExpression extends NodeData<'range_expression'> {}
/** @see NodeData<'range_pattern'> — interface extends for compiler caching */
export interface RangePattern extends NodeData<'range_pattern'> {}
/** @see NodeData<'raw_string_literal'> — interface extends for compiler caching */
export interface RawStringLiteral extends NodeData<'raw_string_literal'> {}
/** @see NodeData<'ref_pattern'> — interface extends for compiler caching */
export interface RefPattern extends NodeData<'ref_pattern'> {}
/** @see NodeData<'reference_expression'> — interface extends for compiler caching */
export interface ReferenceExpression extends NodeData<'reference_expression'> {}
/** @see NodeData<'reference_pattern'> — interface extends for compiler caching */
export interface ReferencePattern extends NodeData<'reference_pattern'> {}
/** @see NodeData<'reference_type'> — interface extends for compiler caching */
export interface ReferenceType extends NodeData<'reference_type'> {}
/** @see NodeData<'removed_trait_bound'> — interface extends for compiler caching */
export interface RemovedTraitBound extends NodeData<'removed_trait_bound'> {}
/** @see NodeData<'return_expression'> — interface extends for compiler caching */
export interface ReturnExpression extends NodeData<'return_expression'> {}
/** @see NodeData<'scoped_identifier'> — interface extends for compiler caching */
export interface ScopedIdentifier extends NodeData<'scoped_identifier'> {}
/** @see NodeData<'scoped_type_identifier'> — interface extends for compiler caching */
export interface ScopedTypeIdentifier extends NodeData<'scoped_type_identifier'> {}
/** @see NodeData<'scoped_use_list'> — interface extends for compiler caching */
export interface ScopedUseList extends NodeData<'scoped_use_list'> {}
/** @see NodeData<'self_parameter'> — interface extends for compiler caching */
export interface SelfParameter extends NodeData<'self_parameter'> {}
/** @see NodeData<'shorthand_field_initializer'> — interface extends for compiler caching */
export interface ShorthandFieldInitializer extends NodeData<'shorthand_field_initializer'> {}
/** @see NodeData<'slice_pattern'> — interface extends for compiler caching */
export interface SlicePattern extends NodeData<'slice_pattern'> {}
/** @see NodeData<'source_file'> — interface extends for compiler caching */
export interface SourceFile extends NodeData<'source_file'> {}
/** @see NodeData<'static_item'> — interface extends for compiler caching */
export interface StaticItem extends NodeData<'static_item'> {}
/** @see NodeData<'string_literal'> — interface extends for compiler caching */
export interface StringLiteral extends NodeData<'string_literal'> {}
/** @see NodeData<'struct_expression'> — interface extends for compiler caching */
export interface StructExpression extends NodeData<'struct_expression'> {}
/** @see NodeData<'struct_item'> — interface extends for compiler caching */
export interface StructItem extends NodeData<'struct_item'> {}
/** @see NodeData<'struct_pattern'> — interface extends for compiler caching */
export interface StructPattern extends NodeData<'struct_pattern'> {}
/** @see NodeData<'token_binding_pattern'> — interface extends for compiler caching */
export interface TokenBindingPattern extends NodeData<'token_binding_pattern'> {}
/** @see NodeData<'token_repetition'> — interface extends for compiler caching */
export interface TokenRepetition extends NodeData<'token_repetition'> {}
/** @see NodeData<'token_repetition_pattern'> — interface extends for compiler caching */
export interface TokenRepetitionPattern extends NodeData<'token_repetition_pattern'> {}
/** @see NodeData<'token_tree'> — interface extends for compiler caching */
export interface TokenTree extends NodeData<'token_tree'> {}
/** @see NodeData<'token_tree_pattern'> — interface extends for compiler caching */
export interface TokenTreePattern extends NodeData<'token_tree_pattern'> {}
/** @see NodeData<'trait_bounds'> — interface extends for compiler caching */
export interface TraitBounds extends NodeData<'trait_bounds'> {}
/** @see NodeData<'trait_item'> — interface extends for compiler caching */
export interface TraitItem extends NodeData<'trait_item'> {}
/** @see NodeData<'try_block'> — interface extends for compiler caching */
export interface TryBlock extends NodeData<'try_block'> {}
/** @see NodeData<'try_expression'> — interface extends for compiler caching */
export interface TryExpression extends NodeData<'try_expression'> {}
/** @see NodeData<'tuple_expression'> — interface extends for compiler caching */
export interface TupleExpression extends NodeData<'tuple_expression'> {}
/** @see NodeData<'tuple_pattern'> — interface extends for compiler caching */
export interface TuplePattern extends NodeData<'tuple_pattern'> {}
/** @see NodeData<'tuple_struct_pattern'> — interface extends for compiler caching */
export interface TupleStructPattern extends NodeData<'tuple_struct_pattern'> {}
/** @see NodeData<'tuple_type'> — interface extends for compiler caching */
export interface TupleType extends NodeData<'tuple_type'> {}
/** @see NodeData<'type_arguments'> — interface extends for compiler caching */
export interface TypeArguments extends NodeData<'type_arguments'> {}
/** @see NodeData<'type_binding'> — interface extends for compiler caching */
export interface TypeBinding extends NodeData<'type_binding'> {}
/** @see NodeData<'type_cast_expression'> — interface extends for compiler caching */
export interface TypeCastExpression extends NodeData<'type_cast_expression'> {}
/** @see NodeData<'type_item'> — interface extends for compiler caching */
export interface TypeItem extends NodeData<'type_item'> {}
/** @see NodeData<'type_parameter'> — interface extends for compiler caching */
export interface TypeParameter extends NodeData<'type_parameter'> {}
/** @see NodeData<'type_parameters'> — interface extends for compiler caching */
export interface TypeParameters extends NodeData<'type_parameters'> {}
/** @see NodeData<'unary_expression'> — interface extends for compiler caching */
export interface UnaryExpression extends NodeData<'unary_expression'> {}
/** @see NodeData<'union_item'> — interface extends for compiler caching */
export interface UnionItem extends NodeData<'union_item'> {}
/** @see NodeData<'unsafe_block'> — interface extends for compiler caching */
export interface UnsafeBlock extends NodeData<'unsafe_block'> {}
/** @see NodeData<'use_as_clause'> — interface extends for compiler caching */
export interface UseAsClause extends NodeData<'use_as_clause'> {}
/** @see NodeData<'use_bounds'> — interface extends for compiler caching */
export interface UseBounds extends NodeData<'use_bounds'> {}
/** @see NodeData<'use_declaration'> — interface extends for compiler caching */
export interface UseDeclaration extends NodeData<'use_declaration'> {}
/** @see NodeData<'use_list'> — interface extends for compiler caching */
export interface UseList extends NodeData<'use_list'> {}
/** @see NodeData<'use_wildcard'> — interface extends for compiler caching */
export interface UseWildcard extends NodeData<'use_wildcard'> {}
/** @see NodeData<'variadic_parameter'> — interface extends for compiler caching */
export interface VariadicParameter extends NodeData<'variadic_parameter'> {}
/** @see NodeData<'visibility_modifier'> — interface extends for compiler caching */
export interface VisibilityModifier extends NodeData<'visibility_modifier'> {}
/** @see NodeData<'where_clause'> — interface extends for compiler caching */
export interface WhereClause extends NodeData<'where_clause'> {}
/** @see NodeData<'where_predicate'> — interface extends for compiler caching */
export interface WherePredicate extends NodeData<'where_predicate'> {}
/** @see NodeData<'while_expression'> — interface extends for compiler caching */
export interface WhileExpression extends NodeData<'while_expression'> {}
/** @see NodeData<'yield_expression'> — interface extends for compiler caching */
export interface YieldExpression extends NodeData<'yield_expression'> {}

// Leaf node types
export interface BooleanLiteral extends NodeData<'boolean_literal'> {}
export interface EmptyStatement extends NodeData<'empty_statement'> {}
export interface FragmentSpecifier extends NodeData<'fragment_specifier'> {}
export interface InnerDocCommentMarker extends NodeData<'inner_doc_comment_marker'> {}
export interface NeverType extends NodeData<'never_type'> {}
export interface OuterDocCommentMarker extends NodeData<'outer_doc_comment_marker'> {}
export interface RemainingFieldPattern extends NodeData<'remaining_field_pattern'> {}
export interface UnitExpression extends NodeData<'unit_expression'> {}
export interface UnitType extends NodeData<'unit_type'> {}
export interface CharLiteral extends NodeData<'char_literal'> {}
export interface Crate extends NodeData<'crate'> {}
export interface DocComment extends NodeData<'doc_comment'> {}
export interface EscapeSequence extends NodeData<'escape_sequence'> {}
export interface FieldIdentifier extends NodeData<'field_identifier'> {}
export interface FloatLiteral extends NodeData<'float_literal'> {}
export interface Identifier extends NodeData<'identifier'> {}
export interface IntegerLiteral extends NodeData<'integer_literal'> {}
export interface Metavariable extends NodeData<'metavariable'> {}
export interface MutableSpecifier extends NodeData<'mutable_specifier'> {}
export interface PrimitiveType extends NodeData<'primitive_type'> {}
export interface Self extends NodeData<'self'> {}
export interface Shebang extends NodeData<'shebang'> {}
export interface ShorthandFieldIdentifier extends NodeData<'shorthand_field_identifier'> {}
export interface StringContent extends NodeData<'string_content'> {}
export interface Super extends NodeData<'super'> {}
export interface TypeIdentifier extends NodeData<'type_identifier'> {}

// Fields types — factory config shapes
export interface AbstractTypeFields extends NodeFields<'abstract_type'> {}
export interface ArgumentsFields extends NodeFields<'arguments'> {}
export interface ArrayExpressionFields extends NodeFields<'array_expression'> {}
export interface ArrayTypeFields extends NodeFields<'array_type'> {}
export interface AssignmentExpressionFields extends NodeFields<'assignment_expression'> {}
export interface AssociatedTypeFields extends NodeFields<'associated_type'> {}
export interface AsyncBlockFields extends NodeFields<'async_block'> {}
export interface AttributeFields extends NodeFields<'attribute'> {}
export interface AttributeItemFields extends NodeFields<'attribute_item'> {}
export interface AwaitExpressionFields extends NodeFields<'await_expression'> {}
export interface BaseFieldInitializerFields extends NodeFields<'base_field_initializer'> {}
export interface BinaryExpressionFields extends NodeFields<'binary_expression'> {}
export interface BlockFields extends NodeFields<'block'> {}
export interface BlockCommentFields extends NodeFields<'block_comment'> {}
export interface BoundedTypeFields extends NodeFields<'bounded_type'> {}
export interface BracketedTypeFields extends NodeFields<'bracketed_type'> {}
export interface BreakExpressionFields extends NodeFields<'break_expression'> {}
export interface CallExpressionFields extends NodeFields<'call_expression'> {}
export interface CapturedPatternFields extends NodeFields<'captured_pattern'> {}
export interface ClosureExpressionFields extends NodeFields<'closure_expression'> {}
export interface ClosureParametersFields extends NodeFields<'closure_parameters'> {}
export interface CompoundAssignmentExprFields extends NodeFields<'compound_assignment_expr'> {}
export interface ConstBlockFields extends NodeFields<'const_block'> {}
export interface ConstItemFields extends NodeFields<'const_item'> {}
export interface ConstParameterFields extends NodeFields<'const_parameter'> {}
export interface ContinueExpressionFields extends NodeFields<'continue_expression'> {}
export interface DeclarationListFields extends NodeFields<'declaration_list'> {}
export interface DynamicTypeFields extends NodeFields<'dynamic_type'> {}
export interface ElseClauseFields extends NodeFields<'else_clause'> {}
export interface EnumItemFields extends NodeFields<'enum_item'> {}
export interface EnumVariantFields extends NodeFields<'enum_variant'> {}
export interface EnumVariantListFields extends NodeFields<'enum_variant_list'> {}
export interface ExpressionStatementFields extends NodeFields<'expression_statement'> {}
export interface ExternCrateDeclarationFields extends NodeFields<'extern_crate_declaration'> {}
export interface ExternModifierFields extends NodeFields<'extern_modifier'> {}
export interface FieldDeclarationFields extends NodeFields<'field_declaration'> {}
export interface FieldDeclarationListFields extends NodeFields<'field_declaration_list'> {}
export interface FieldExpressionFields extends NodeFields<'field_expression'> {}
export interface FieldInitializerFields extends NodeFields<'field_initializer'> {}
export interface FieldInitializerListFields extends NodeFields<'field_initializer_list'> {}
export interface FieldPatternFields extends NodeFields<'field_pattern'> {}
export interface ForExpressionFields extends NodeFields<'for_expression'> {}
export interface ForLifetimesFields extends NodeFields<'for_lifetimes'> {}
export interface ForeignModItemFields extends NodeFields<'foreign_mod_item'> {}
export interface FunctionItemFields extends NodeFields<'function_item'> {}
export interface FunctionModifiersFields extends NodeFields<'function_modifiers'> {}
export interface FunctionSignatureItemFields extends NodeFields<'function_signature_item'> {}
export interface FunctionTypeFields extends NodeFields<'function_type'> {}
export interface GenBlockFields extends NodeFields<'gen_block'> {}
export interface GenericFunctionFields extends NodeFields<'generic_function'> {}
export interface GenericPatternFields extends NodeFields<'generic_pattern'> {}
export interface GenericTypeFields extends NodeFields<'generic_type'> {}
export interface GenericTypeWithTurbofishFields extends NodeFields<'generic_type_with_turbofish'> {}
export interface HigherRankedTraitBoundFields extends NodeFields<'higher_ranked_trait_bound'> {}
export interface IfExpressionFields extends NodeFields<'if_expression'> {}
export interface ImplItemFields extends NodeFields<'impl_item'> {}
export interface IndexExpressionFields extends NodeFields<'index_expression'> {}
export interface InnerAttributeItemFields extends NodeFields<'inner_attribute_item'> {}
export interface LabelFields extends NodeFields<'label'> {}
export interface LetChainFields extends NodeFields<'let_chain'> {}
export interface LetConditionFields extends NodeFields<'let_condition'> {}
export interface LetDeclarationFields extends NodeFields<'let_declaration'> {}
export interface LifetimeFields extends NodeFields<'lifetime'> {}
export interface LifetimeParameterFields extends NodeFields<'lifetime_parameter'> {}
export interface LineCommentFields extends NodeFields<'line_comment'> {}
export interface LoopExpressionFields extends NodeFields<'loop_expression'> {}
export interface MacroDefinitionFields extends NodeFields<'macro_definition'> {}
export interface MacroInvocationFields extends NodeFields<'macro_invocation'> {}
export interface MacroRuleFields extends NodeFields<'macro_rule'> {}
export interface MatchArmFields extends NodeFields<'match_arm'> {}
export interface MatchBlockFields extends NodeFields<'match_block'> {}
export interface MatchExpressionFields extends NodeFields<'match_expression'> {}
export interface MatchPatternFields extends NodeFields<'match_pattern'> {}
export interface ModItemFields extends NodeFields<'mod_item'> {}
export interface MutPatternFields extends NodeFields<'mut_pattern'> {}
export interface NegativeLiteralFields extends NodeFields<'negative_literal'> {}
export interface OrPatternFields extends NodeFields<'or_pattern'> {}
export interface OrderedFieldDeclarationListFields extends NodeFields<'ordered_field_declaration_list'> {}
export interface ParameterFields extends NodeFields<'parameter'> {}
export interface ParametersFields extends NodeFields<'parameters'> {}
export interface ParenthesizedExpressionFields extends NodeFields<'parenthesized_expression'> {}
export interface PointerTypeFields extends NodeFields<'pointer_type'> {}
export interface QualifiedTypeFields extends NodeFields<'qualified_type'> {}
export interface RangeExpressionFields extends NodeFields<'range_expression'> {}
export interface RangePatternFields extends NodeFields<'range_pattern'> {}
export interface RawStringLiteralFields extends NodeFields<'raw_string_literal'> {}
export interface RefPatternFields extends NodeFields<'ref_pattern'> {}
export interface ReferenceExpressionFields extends NodeFields<'reference_expression'> {}
export interface ReferencePatternFields extends NodeFields<'reference_pattern'> {}
export interface ReferenceTypeFields extends NodeFields<'reference_type'> {}
export interface RemovedTraitBoundFields extends NodeFields<'removed_trait_bound'> {}
export interface ReturnExpressionFields extends NodeFields<'return_expression'> {}
export interface ScopedIdentifierFields extends NodeFields<'scoped_identifier'> {}
export interface ScopedTypeIdentifierFields extends NodeFields<'scoped_type_identifier'> {}
export interface ScopedUseListFields extends NodeFields<'scoped_use_list'> {}
export interface SelfParameterFields extends NodeFields<'self_parameter'> {}
export interface ShorthandFieldInitializerFields extends NodeFields<'shorthand_field_initializer'> {}
export interface SlicePatternFields extends NodeFields<'slice_pattern'> {}
export interface SourceFileFields extends NodeFields<'source_file'> {}
export interface StaticItemFields extends NodeFields<'static_item'> {}
export interface StringLiteralFields extends NodeFields<'string_literal'> {}
export interface StructExpressionFields extends NodeFields<'struct_expression'> {}
export interface StructItemFields extends NodeFields<'struct_item'> {}
export interface StructPatternFields extends NodeFields<'struct_pattern'> {}
export interface TokenBindingPatternFields extends NodeFields<'token_binding_pattern'> {}
export interface TokenRepetitionFields extends NodeFields<'token_repetition'> {}
export interface TokenRepetitionPatternFields extends NodeFields<'token_repetition_pattern'> {}
export interface TokenTreeFields extends NodeFields<'token_tree'> {}
export interface TokenTreePatternFields extends NodeFields<'token_tree_pattern'> {}
export interface TraitBoundsFields extends NodeFields<'trait_bounds'> {}
export interface TraitItemFields extends NodeFields<'trait_item'> {}
export interface TryBlockFields extends NodeFields<'try_block'> {}
export interface TryExpressionFields extends NodeFields<'try_expression'> {}
export interface TupleExpressionFields extends NodeFields<'tuple_expression'> {}
export interface TuplePatternFields extends NodeFields<'tuple_pattern'> {}
export interface TupleStructPatternFields extends NodeFields<'tuple_struct_pattern'> {}
export interface TupleTypeFields extends NodeFields<'tuple_type'> {}
export interface TypeArgumentsFields extends NodeFields<'type_arguments'> {}
export interface TypeBindingFields extends NodeFields<'type_binding'> {}
export interface TypeCastExpressionFields extends NodeFields<'type_cast_expression'> {}
export interface TypeItemFields extends NodeFields<'type_item'> {}
export interface TypeParameterFields extends NodeFields<'type_parameter'> {}
export interface TypeParametersFields extends NodeFields<'type_parameters'> {}
export interface UnaryExpressionFields extends NodeFields<'unary_expression'> {}
export interface UnionItemFields extends NodeFields<'union_item'> {}
export interface UnsafeBlockFields extends NodeFields<'unsafe_block'> {}
export interface UseAsClauseFields extends NodeFields<'use_as_clause'> {}
export interface UseBoundsFields extends NodeFields<'use_bounds'> {}
export interface UseDeclarationFields extends NodeFields<'use_declaration'> {}
export interface UseListFields extends NodeFields<'use_list'> {}
export interface UseWildcardFields extends NodeFields<'use_wildcard'> {}
export interface VariadicParameterFields extends NodeFields<'variadic_parameter'> {}
export interface VisibilityModifierFields extends NodeFields<'visibility_modifier'> {}
export interface WhereClauseFields extends NodeFields<'where_clause'> {}
export interface WherePredicateFields extends NodeFields<'where_predicate'> {}
export interface WhileExpressionFields extends NodeFields<'while_expression'> {}
export interface YieldExpressionFields extends NodeFields<'yield_expression'> {}

// Tree types — parsed tree nodes with typed navigation
export interface AbstractTypeTree extends TreeNode<'abstract_type'> {}
export interface ArgumentsTree extends TreeNode<'arguments'> {}
export interface ArrayExpressionTree extends TreeNode<'array_expression'> {}
export interface ArrayTypeTree extends TreeNode<'array_type'> {}
export interface AssignmentExpressionTree extends TreeNode<'assignment_expression'> {}
export interface AssociatedTypeTree extends TreeNode<'associated_type'> {}
export interface AsyncBlockTree extends TreeNode<'async_block'> {}
export interface AttributeTree extends TreeNode<'attribute'> {}
export interface AttributeItemTree extends TreeNode<'attribute_item'> {}
export interface AwaitExpressionTree extends TreeNode<'await_expression'> {}
export interface BaseFieldInitializerTree extends TreeNode<'base_field_initializer'> {}
export interface BinaryExpressionTree extends TreeNode<'binary_expression'> {}
export interface BlockTree extends TreeNode<'block'> {}
export interface BlockCommentTree extends TreeNode<'block_comment'> {}
export interface BoundedTypeTree extends TreeNode<'bounded_type'> {}
export interface BracketedTypeTree extends TreeNode<'bracketed_type'> {}
export interface BreakExpressionTree extends TreeNode<'break_expression'> {}
export interface CallExpressionTree extends TreeNode<'call_expression'> {}
export interface CapturedPatternTree extends TreeNode<'captured_pattern'> {}
export interface ClosureExpressionTree extends TreeNode<'closure_expression'> {}
export interface ClosureParametersTree extends TreeNode<'closure_parameters'> {}
export interface CompoundAssignmentExprTree extends TreeNode<'compound_assignment_expr'> {}
export interface ConstBlockTree extends TreeNode<'const_block'> {}
export interface ConstItemTree extends TreeNode<'const_item'> {}
export interface ConstParameterTree extends TreeNode<'const_parameter'> {}
export interface ContinueExpressionTree extends TreeNode<'continue_expression'> {}
export interface DeclarationListTree extends TreeNode<'declaration_list'> {}
export interface DynamicTypeTree extends TreeNode<'dynamic_type'> {}
export interface ElseClauseTree extends TreeNode<'else_clause'> {}
export interface EnumItemTree extends TreeNode<'enum_item'> {}
export interface EnumVariantTree extends TreeNode<'enum_variant'> {}
export interface EnumVariantListTree extends TreeNode<'enum_variant_list'> {}
export interface ExpressionStatementTree extends TreeNode<'expression_statement'> {}
export interface ExternCrateDeclarationTree extends TreeNode<'extern_crate_declaration'> {}
export interface ExternModifierTree extends TreeNode<'extern_modifier'> {}
export interface FieldDeclarationTree extends TreeNode<'field_declaration'> {}
export interface FieldDeclarationListTree extends TreeNode<'field_declaration_list'> {}
export interface FieldExpressionTree extends TreeNode<'field_expression'> {}
export interface FieldInitializerTree extends TreeNode<'field_initializer'> {}
export interface FieldInitializerListTree extends TreeNode<'field_initializer_list'> {}
export interface FieldPatternTree extends TreeNode<'field_pattern'> {}
export interface ForExpressionTree extends TreeNode<'for_expression'> {}
export interface ForLifetimesTree extends TreeNode<'for_lifetimes'> {}
export interface ForeignModItemTree extends TreeNode<'foreign_mod_item'> {}
export interface FunctionItemTree extends TreeNode<'function_item'> {}
export interface FunctionModifiersTree extends TreeNode<'function_modifiers'> {}
export interface FunctionSignatureItemTree extends TreeNode<'function_signature_item'> {}
export interface FunctionTypeTree extends TreeNode<'function_type'> {}
export interface GenBlockTree extends TreeNode<'gen_block'> {}
export interface GenericFunctionTree extends TreeNode<'generic_function'> {}
export interface GenericPatternTree extends TreeNode<'generic_pattern'> {}
export interface GenericTypeTree extends TreeNode<'generic_type'> {}
export interface GenericTypeWithTurbofishTree extends TreeNode<'generic_type_with_turbofish'> {}
export interface HigherRankedTraitBoundTree extends TreeNode<'higher_ranked_trait_bound'> {}
export interface IfExpressionTree extends TreeNode<'if_expression'> {}
export interface ImplItemTree extends TreeNode<'impl_item'> {}
export interface IndexExpressionTree extends TreeNode<'index_expression'> {}
export interface InnerAttributeItemTree extends TreeNode<'inner_attribute_item'> {}
export interface LabelTree extends TreeNode<'label'> {}
export interface LetChainTree extends TreeNode<'let_chain'> {}
export interface LetConditionTree extends TreeNode<'let_condition'> {}
export interface LetDeclarationTree extends TreeNode<'let_declaration'> {}
export interface LifetimeTree extends TreeNode<'lifetime'> {}
export interface LifetimeParameterTree extends TreeNode<'lifetime_parameter'> {}
export interface LineCommentTree extends TreeNode<'line_comment'> {}
export interface LoopExpressionTree extends TreeNode<'loop_expression'> {}
export interface MacroDefinitionTree extends TreeNode<'macro_definition'> {}
export interface MacroInvocationTree extends TreeNode<'macro_invocation'> {}
export interface MacroRuleTree extends TreeNode<'macro_rule'> {}
export interface MatchArmTree extends TreeNode<'match_arm'> {}
export interface MatchBlockTree extends TreeNode<'match_block'> {}
export interface MatchExpressionTree extends TreeNode<'match_expression'> {}
export interface MatchPatternTree extends TreeNode<'match_pattern'> {}
export interface ModItemTree extends TreeNode<'mod_item'> {}
export interface MutPatternTree extends TreeNode<'mut_pattern'> {}
export interface NegativeLiteralTree extends TreeNode<'negative_literal'> {}
export interface OrPatternTree extends TreeNode<'or_pattern'> {}
export interface OrderedFieldDeclarationListTree extends TreeNode<'ordered_field_declaration_list'> {}
export interface ParameterTree extends TreeNode<'parameter'> {}
export interface ParametersTree extends TreeNode<'parameters'> {}
export interface ParenthesizedExpressionTree extends TreeNode<'parenthesized_expression'> {}
export interface PointerTypeTree extends TreeNode<'pointer_type'> {}
export interface QualifiedTypeTree extends TreeNode<'qualified_type'> {}
export interface RangeExpressionTree extends TreeNode<'range_expression'> {}
export interface RangePatternTree extends TreeNode<'range_pattern'> {}
export interface RawStringLiteralTree extends TreeNode<'raw_string_literal'> {}
export interface RefPatternTree extends TreeNode<'ref_pattern'> {}
export interface ReferenceExpressionTree extends TreeNode<'reference_expression'> {}
export interface ReferencePatternTree extends TreeNode<'reference_pattern'> {}
export interface ReferenceTypeTree extends TreeNode<'reference_type'> {}
export interface RemovedTraitBoundTree extends TreeNode<'removed_trait_bound'> {}
export interface ReturnExpressionTree extends TreeNode<'return_expression'> {}
export interface ScopedIdentifierTree extends TreeNode<'scoped_identifier'> {}
export interface ScopedTypeIdentifierTree extends TreeNode<'scoped_type_identifier'> {}
export interface ScopedUseListTree extends TreeNode<'scoped_use_list'> {}
export interface SelfParameterTree extends TreeNode<'self_parameter'> {}
export interface ShorthandFieldInitializerTree extends TreeNode<'shorthand_field_initializer'> {}
export interface SlicePatternTree extends TreeNode<'slice_pattern'> {}
export interface SourceFileTree extends TreeNode<'source_file'> {}
export interface StaticItemTree extends TreeNode<'static_item'> {}
export interface StringLiteralTree extends TreeNode<'string_literal'> {}
export interface StructExpressionTree extends TreeNode<'struct_expression'> {}
export interface StructItemTree extends TreeNode<'struct_item'> {}
export interface StructPatternTree extends TreeNode<'struct_pattern'> {}
export interface TokenBindingPatternTree extends TreeNode<'token_binding_pattern'> {}
export interface TokenRepetitionTree extends TreeNode<'token_repetition'> {}
export interface TokenRepetitionPatternTree extends TreeNode<'token_repetition_pattern'> {}
export interface TokenTreeTree extends TreeNode<'token_tree'> {}
export interface TokenTreePatternTree extends TreeNode<'token_tree_pattern'> {}
export interface TraitBoundsTree extends TreeNode<'trait_bounds'> {}
export interface TraitItemTree extends TreeNode<'trait_item'> {}
export interface TryBlockTree extends TreeNode<'try_block'> {}
export interface TryExpressionTree extends TreeNode<'try_expression'> {}
export interface TupleExpressionTree extends TreeNode<'tuple_expression'> {}
export interface TuplePatternTree extends TreeNode<'tuple_pattern'> {}
export interface TupleStructPatternTree extends TreeNode<'tuple_struct_pattern'> {}
export interface TupleTypeTree extends TreeNode<'tuple_type'> {}
export interface TypeArgumentsTree extends TreeNode<'type_arguments'> {}
export interface TypeBindingTree extends TreeNode<'type_binding'> {}
export interface TypeCastExpressionTree extends TreeNode<'type_cast_expression'> {}
export interface TypeItemTree extends TreeNode<'type_item'> {}
export interface TypeParameterTree extends TreeNode<'type_parameter'> {}
export interface TypeParametersTree extends TreeNode<'type_parameters'> {}
export interface UnaryExpressionTree extends TreeNode<'unary_expression'> {}
export interface UnionItemTree extends TreeNode<'union_item'> {}
export interface UnsafeBlockTree extends TreeNode<'unsafe_block'> {}
export interface UseAsClauseTree extends TreeNode<'use_as_clause'> {}
export interface UseBoundsTree extends TreeNode<'use_bounds'> {}
export interface UseDeclarationTree extends TreeNode<'use_declaration'> {}
export interface UseListTree extends TreeNode<'use_list'> {}
export interface UseWildcardTree extends TreeNode<'use_wildcard'> {}
export interface VariadicParameterTree extends TreeNode<'variadic_parameter'> {}
export interface VisibilityModifierTree extends TreeNode<'visibility_modifier'> {}
export interface WhereClauseTree extends TreeNode<'where_clause'> {}
export interface WherePredicateTree extends TreeNode<'where_predicate'> {}
export interface WhileExpressionTree extends TreeNode<'while_expression'> {}
export interface YieldExpressionTree extends TreeNode<'yield_expression'> {}

// Leaf tree types
export interface BooleanLiteralTree extends TreeNode<'boolean_literal'> {}
export interface EmptyStatementTree extends TreeNode<'empty_statement'> {}
export interface FragmentSpecifierTree extends TreeNode<'fragment_specifier'> {}
export interface InnerDocCommentMarkerTree extends TreeNode<'inner_doc_comment_marker'> {}
export interface NeverTypeTree extends TreeNode<'never_type'> {}
export interface OuterDocCommentMarkerTree extends TreeNode<'outer_doc_comment_marker'> {}
export interface RemainingFieldPatternTree extends TreeNode<'remaining_field_pattern'> {}
export interface UnitExpressionTree extends TreeNode<'unit_expression'> {}
export interface UnitTypeTree extends TreeNode<'unit_type'> {}
export interface CharLiteralTree extends TreeNode<'char_literal'> {}
export interface CrateTree extends TreeNode<'crate'> {}
export interface DocCommentTree extends TreeNode<'doc_comment'> {}
export interface EscapeSequenceTree extends TreeNode<'escape_sequence'> {}
export interface FieldIdentifierTree extends TreeNode<'field_identifier'> {}
export interface FloatLiteralTree extends TreeNode<'float_literal'> {}
export interface IdentifierTree extends TreeNode<'identifier'> {}
export interface IntegerLiteralTree extends TreeNode<'integer_literal'> {}
export interface MetavariableTree extends TreeNode<'metavariable'> {}
export interface MutableSpecifierTree extends TreeNode<'mutable_specifier'> {}
export interface PrimitiveTypeTree extends TreeNode<'primitive_type'> {}
export interface SelfTree extends TreeNode<'self'> {}
export interface ShebangTree extends TreeNode<'shebang'> {}
export interface ShorthandFieldIdentifierTree extends TreeNode<'shorthand_field_identifier'> {}
export interface StringContentTree extends TreeNode<'string_content'> {}
export interface SuperTree extends TreeNode<'super'> {}
export interface TypeIdentifierTree extends TreeNode<'type_identifier'> {}

// Supertype unions (node)
export type DeclarationStatement =
  | AssociatedType
  | AttributeItem
  | ConstItem
  | EmptyStatement
  | EnumItem
  | ExternCrateDeclaration
  | ForeignModItem
  | FunctionItem
  | FunctionSignatureItem
  | ImplItem
  | InnerAttributeItem
  | LetDeclaration
  | MacroDefinition
  | MacroInvocation
  | ModItem
  | StaticItem
  | StructItem
  | TraitItem
  | TypeItem
  | UnionItem
  | UseDeclaration
;

export type Expression =
  | ArrayExpression
  | AssignmentExpression
  | AsyncBlock
  | AwaitExpression
  | BinaryExpression
  | Block
  | BreakExpression
  | CallExpression
  | ClosureExpression
  | CompoundAssignmentExpr
  | ConstBlock
  | ContinueExpression
  | FieldExpression
  | ForExpression
  | GenBlock
  | GenericFunction
  | Identifier
  | IfExpression
  | IndexExpression
  | LoopExpression
  | MacroInvocation
  | MatchExpression
  | Metavariable
  | ParenthesizedExpression
  | RangeExpression
  | ReferenceExpression
  | ReturnExpression
  | ScopedIdentifier
  | Self
  | StructExpression
  | TryBlock
  | TryExpression
  | TupleExpression
  | TypeCastExpression
  | UnaryExpression
  | UnitExpression
  | UnsafeBlock
  | WhileExpression
  | YieldExpression
;

export type Literal =
  | BooleanLiteral
  | CharLiteral
  | FloatLiteral
  | IntegerLiteral
  | RawStringLiteral
  | StringLiteral
;

export type LiteralPattern =
  | BooleanLiteral
  | CharLiteral
  | FloatLiteral
  | IntegerLiteral
  | NegativeLiteral
  | RawStringLiteral
  | StringLiteral
;

export type Pattern =
  | LiteralPattern
  | CapturedPattern
  | ConstBlock
  | GenericPattern
  | Identifier
  | MacroInvocation
  | MutPattern
  | OrPattern
  | RangePattern
  | RefPattern
  | ReferencePattern
  | RemainingFieldPattern
  | ScopedIdentifier
  | SlicePattern
  | StructPattern
  | TuplePattern
  | TupleStructPattern
;

export type Type =
  | AbstractType
  | ArrayType
  | BoundedType
  | DynamicType
  | FunctionType
  | GenericType
  | MacroInvocation
  | Metavariable
  | NeverType
  | PointerType
  | PrimitiveType
  | ReferenceType
  | RemovedTraitBound
  | ScopedTypeIdentifier
  | TupleType
  | TypeIdentifier
  | UnitType
;

// Supertype unions (fields — branch kinds only)
export type DeclarationStatementFields =
  | AssociatedTypeFields
  | AttributeItemFields
  | ConstItemFields
  | EnumItemFields
  | ExternCrateDeclarationFields
  | ForeignModItemFields
  | FunctionItemFields
  | FunctionSignatureItemFields
  | ImplItemFields
  | InnerAttributeItemFields
  | LetDeclarationFields
  | MacroDefinitionFields
  | MacroInvocationFields
  | ModItemFields
  | StaticItemFields
  | StructItemFields
  | TraitItemFields
  | TypeItemFields
  | UnionItemFields
  | UseDeclarationFields
;

export type ExpressionFields =
  | ArrayExpressionFields
  | AssignmentExpressionFields
  | AsyncBlockFields
  | AwaitExpressionFields
  | BinaryExpressionFields
  | BlockFields
  | BreakExpressionFields
  | CallExpressionFields
  | ClosureExpressionFields
  | CompoundAssignmentExprFields
  | ConstBlockFields
  | ContinueExpressionFields
  | FieldExpressionFields
  | ForExpressionFields
  | GenBlockFields
  | GenericFunctionFields
  | IfExpressionFields
  | IndexExpressionFields
  | LoopExpressionFields
  | MacroInvocationFields
  | MatchExpressionFields
  | ParenthesizedExpressionFields
  | RangeExpressionFields
  | ReferenceExpressionFields
  | ReturnExpressionFields
  | ScopedIdentifierFields
  | StructExpressionFields
  | TryBlockFields
  | TryExpressionFields
  | TupleExpressionFields
  | TypeCastExpressionFields
  | UnaryExpressionFields
  | UnsafeBlockFields
  | WhileExpressionFields
  | YieldExpressionFields
;

export type LiteralFields =
  | RawStringLiteralFields
  | StringLiteralFields
;

export type LiteralPatternFields =
  | NegativeLiteralFields
  | RawStringLiteralFields
  | StringLiteralFields
;

export type PatternFields =
  | CapturedPatternFields
  | ConstBlockFields
  | GenericPatternFields
  | MacroInvocationFields
  | MutPatternFields
  | OrPatternFields
  | RangePatternFields
  | RefPatternFields
  | ReferencePatternFields
  | ScopedIdentifierFields
  | SlicePatternFields
  | StructPatternFields
  | TuplePatternFields
  | TupleStructPatternFields
;

export type TypeFields =
  | AbstractTypeFields
  | ArrayTypeFields
  | BoundedTypeFields
  | DynamicTypeFields
  | FunctionTypeFields
  | GenericTypeFields
  | MacroInvocationFields
  | PointerTypeFields
  | ReferenceTypeFields
  | RemovedTraitBoundFields
  | ScopedTypeIdentifierFields
  | TupleTypeFields
;

// Supertype unions (tree)
export type DeclarationStatementTree =
  | AssociatedTypeTree
  | AttributeItemTree
  | ConstItemTree
  | EmptyStatementTree
  | EnumItemTree
  | ExternCrateDeclarationTree
  | ForeignModItemTree
  | FunctionItemTree
  | FunctionSignatureItemTree
  | ImplItemTree
  | InnerAttributeItemTree
  | LetDeclarationTree
  | MacroDefinitionTree
  | MacroInvocationTree
  | ModItemTree
  | StaticItemTree
  | StructItemTree
  | TraitItemTree
  | TypeItemTree
  | UnionItemTree
  | UseDeclarationTree
;

export type ExpressionTree =
  | LiteralTree
  | ArrayExpressionTree
  | AssignmentExpressionTree
  | AsyncBlockTree
  | AwaitExpressionTree
  | BinaryExpressionTree
  | BlockTree
  | BreakExpressionTree
  | CallExpressionTree
  | ClosureExpressionTree
  | CompoundAssignmentExprTree
  | ConstBlockTree
  | ContinueExpressionTree
  | FieldExpressionTree
  | ForExpressionTree
  | GenBlockTree
  | GenericFunctionTree
  | IdentifierTree
  | IfExpressionTree
  | IndexExpressionTree
  | LoopExpressionTree
  | MacroInvocationTree
  | MatchExpressionTree
  | MetavariableTree
  | ParenthesizedExpressionTree
  | RangeExpressionTree
  | ReferenceExpressionTree
  | ReturnExpressionTree
  | ScopedIdentifierTree
  | SelfTree
  | StructExpressionTree
  | TryBlockTree
  | TryExpressionTree
  | TupleExpressionTree
  | TypeCastExpressionTree
  | UnaryExpressionTree
  | UnitExpressionTree
  | UnsafeBlockTree
  | WhileExpressionTree
  | YieldExpressionTree
;

export type LiteralTree =
  | BooleanLiteralTree
  | CharLiteralTree
  | FloatLiteralTree
  | IntegerLiteralTree
  | RawStringLiteralTree
  | StringLiteralTree
;

export type LiteralPatternTree =
  | BooleanLiteralTree
  | CharLiteralTree
  | FloatLiteralTree
  | IntegerLiteralTree
  | NegativeLiteralTree
  | RawStringLiteralTree
  | StringLiteralTree
;

export type PatternTree =
  | LiteralPatternTree
  | CapturedPatternTree
  | ConstBlockTree
  | GenericPatternTree
  | IdentifierTree
  | MacroInvocationTree
  | MutPatternTree
  | OrPatternTree
  | RangePatternTree
  | RefPatternTree
  | ReferencePatternTree
  | RemainingFieldPatternTree
  | ScopedIdentifierTree
  | SlicePatternTree
  | StructPatternTree
  | TuplePatternTree
  | TupleStructPatternTree
;

export type TypeTree =
  | AbstractTypeTree
  | ArrayTypeTree
  | BoundedTypeTree
  | DynamicTypeTree
  | FunctionTypeTree
  | GenericTypeTree
  | MacroInvocationTree
  | MetavariableTree
  | NeverTypeTree
  | PointerTypeTree
  | PrimitiveTypeTree
  | ReferenceTypeTree
  | RemovedTraitBoundTree
  | ScopedTypeIdentifierTree
  | TupleTypeTree
  | TypeIdentifierTree
  | UnitTypeTree
;

export type RustNode =
  | AbstractType
  | Arguments
  | ArrayExpression
  | ArrayType
  | AssignmentExpression
  | AssociatedType
  | AsyncBlock
  | Attribute
  | AttributeItem
  | AwaitExpression
  | BaseFieldInitializer
  | BinaryExpression
  | Block
  | BlockComment
  | BoundedType
  | BracketedType
  | BreakExpression
  | CallExpression
  | CapturedPattern
  | ClosureExpression
  | ClosureParameters
  | CompoundAssignmentExpr
  | ConstBlock
  | ConstItem
  | ConstParameter
  | ContinueExpression
  | DeclarationList
  | DynamicType
  | ElseClause
  | EnumItem
  | EnumVariant
  | EnumVariantList
  | ExpressionStatement
  | ExternCrateDeclaration
  | ExternModifier
  | FieldDeclaration
  | FieldDeclarationList
  | FieldExpression
  | FieldInitializer
  | FieldInitializerList
  | FieldPattern
  | ForExpression
  | ForLifetimes
  | ForeignModItem
  | FunctionItem
  | FunctionModifiers
  | FunctionSignatureItem
  | FunctionType
  | GenBlock
  | GenericFunction
  | GenericPattern
  | GenericType
  | GenericTypeWithTurbofish
  | HigherRankedTraitBound
  | IfExpression
  | ImplItem
  | IndexExpression
  | InnerAttributeItem
  | Label
  | LetChain
  | LetCondition
  | LetDeclaration
  | Lifetime
  | LifetimeParameter
  | LineComment
  | LoopExpression
  | MacroDefinition
  | MacroInvocation
  | MacroRule
  | MatchArm
  | MatchBlock
  | MatchExpression
  | MatchPattern
  | ModItem
  | MutPattern
  | NegativeLiteral
  | OrPattern
  | OrderedFieldDeclarationList
  | Parameter
  | Parameters
  | ParenthesizedExpression
  | PointerType
  | QualifiedType
  | RangeExpression
  | RangePattern
  | RawStringLiteral
  | RefPattern
  | ReferenceExpression
  | ReferencePattern
  | ReferenceType
  | RemovedTraitBound
  | ReturnExpression
  | ScopedIdentifier
  | ScopedTypeIdentifier
  | ScopedUseList
  | SelfParameter
  | ShorthandFieldInitializer
  | SlicePattern
  | SourceFile
  | StaticItem
  | StringLiteral
  | StructExpression
  | StructItem
  | StructPattern
  | TokenBindingPattern
  | TokenRepetition
  | TokenRepetitionPattern
  | TokenTree
  | TokenTreePattern
  | TraitBounds
  | TraitItem
  | TryBlock
  | TryExpression
  | TupleExpression
  | TuplePattern
  | TupleStructPattern
  | TupleType
  | TypeArguments
  | TypeBinding
  | TypeCastExpression
  | TypeItem
  | TypeParameter
  | TypeParameters
  | UnaryExpression
  | UnionItem
  | UnsafeBlock
  | UseAsClause
  | UseBounds
  | UseDeclaration
  | UseList
  | UseWildcard
  | VariadicParameter
  | VisibilityModifier
  | WhereClause
  | WherePredicate
  | WhileExpression
  | YieldExpression
;
